<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar=NULL, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm ipsForm_fullWidth {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	{{foreach $elements['streams'] as $input}}
		<ul class='ipsList_reset'>
			{$input->html($form)|raw}
		</ul>
	{{endforeach}}
	<div id="elFilterFormFull" class="ipsPad {{if isset( $elements['streams'] )}}ipsJS_hide{{endif}}">
		<div class='ipsAreaBackground_light'>
			{{if isset( $elements['title'] )}}
				{{foreach $elements['title'] as $input}}
					<ul class='ipsList_reset ipsPad ipsAreaBackground cStreamForm_mainTitle ipsFieldRow_primary'>
						{$input->rowHtml($form)|raw}
					</ul>
				{{endforeach}}
			{{endif}}
			<div class="ipsGrid ipsGrid_collapsePhone ipsPad ipsSpacer_bottom">
				{{foreach $elements as $tabName => $collection}}
					{{if $tabName != 'streams' and $tabName != 'title'}}
						<div class="ipsGrid_span4">
							<ul class='ipsList_reset'>
								{{foreach $collection as $input}}
									{{if $input instanceof \IPS\Helpers\Form\CheckboxSet}}
										<li data-controller="nexus.admin.support.filterCheckboxSet">
											<h3 class="ipsType_reset ipsType_large cStreamForm_title ipsSpacer_bottom ipsSpacer_half">
												{lang="$input->name"}
												
												<p class='ipsType_reset ipsSpacer_top ipsSpacer_half ipsType_small ipsPos_right'>
													<a href="#all" class="ipsJS_show" data-action="checkAll">{lang="all"}</a> &middot; <a href="#all" class="ipsJS_show" data-action="checkNone">{lang="none"}</a>
												</p>
											</h3>
											<ul class="ipsSideMenu_list ipsSideMenu_withChecks ipsSideMenu_small ipsType_normal cNexusSupportCheckboxes" data-role='searchApp' data-ipsSideMenu data-ipsSideMenu-type="check" data-ipsSideMenu-responsive="false">
												{{foreach $input->options['options'] as $k => $lang}}
													<li>
														<a href='#' id='elSearchToggle_{$k}' class='ipsSideMenu_item {{if \is_array( $input->value ) AND \in_array( $k, $input->value )}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue='{$k}'>
															<input type="checkbox" name="{$input->name}[{$k}]" value="1" {{if \is_array( $input->value ) AND \in_array( $k, $input->value )}}checked{{endif}} id="elRadio_type_{$k}" {{if \is_array( $input->options['toggles'] ) && \count( $input->options['toggles'] )}}data-control="toggle" data-toggles="{expression="implode( ',', $input->options['toggles'][ $k ] )"}" data-toggle-visibleCheck='#elSearchToggle_{$k}'{{endif}}>
															<label for='elRadio_type_{$k}' id='elField_type_{$k}_label' data-role='searchAppTitle'>{lang="$lang"}</label>
														</a>
													</li>
												{{endforeach}}
											</ul>
										</li>
									{{elseif \is_object( $input ) }}
										{$input->rowHtml($form)|raw}
									{{else}}
										{$input|raw}
									{{endif}}
								{{endforeach}}
							</ul>
						</div>
					{{endif}}
				{{endforeach}}
			</div>
			<div class='ipsAreaBackground ipsPad ipsType_center'>
				{expression="implode( '', $actionButtons)" raw="true"}
			</div>
		</div>
	</div>
</form>
<div class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elSaveStream_menu">
	<form action="{url="app=nexus&module=support&controller=requests&do=saveStream"}" method="post">
		<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
		<div class="ipsPad">
			<input type="text" name="stream_title" placeholder="{lang="stream_title"}">
		</div>
		<div class="ipsAreaBackground ipsPad ipsType_center">
			<input type="submit" class="ipsButton ipsButton_fullWidth ipsButton_small ipsButton_primary" value="{lang="save"}">
		</div>
	</form>
</div>