<ips:template parameters="$input" />
<select name="{$input->name}[0]" class="cNexusTicketSort">
	<option value="lt"{{if \is_array( $input->value ) AND $input->value[0] == 'lt'}} selected{{endif}}>{lang='lt'}</option>
	<option value="gt"{{if \is_numeric( $input->value ) or ( \is_array( $input->value ) AND $input->value[0] == 'gt' )}} selected{{endif}}>{lang='gt'}</option>
</select>
{{$bestUnit = 'h';}}
<input
	name="{$input->name}[1]"
	type="number"
	{{if $input->value === NULL}}
		value=""
		data-jsdisable="true"
	{{elseif \is_numeric( $input->value )}}
		value="{expression="number_format( $input->value, mb_strlen( mb_substr( $input->value, mb_strpos( $input->value, '.' ) + 1 ) ), '.', '' )"}"
	{{else}}
		{{$numberValue = $input->value[1] * 3600; $bestUnit = \IPS\Helpers\Form\Interval::bestUnit( $numberValue );}}
		value="{$numberValue}"
	{{endif}}
	class="ipsField_tiny"
	min="0"
>
<select name="{$input->name}[2]" class="cNexusTicketSort">
	<option value="w" {{if $bestUnit == 'w'}}selected{{endif}}>{lang="weeks"}</option>
	<option value="d" {{if $bestUnit == 'd'}}selected{{endif}}>{lang="days"}</option>
	<option value="h" {{if $bestUnit == 'h'}}selected{{endif}}>{lang="hours"}</option>
	<option value="i" {{if $bestUnit == 'i'}}selected{{endif}}>{lang="minutes"}</option>
	<option value="s" {{if $bestUnit == 's'}}selected{{endif}}>{lang="seconds"}</option>
</select>
{lang="ago"}
&nbsp;
<div class="ipsFieldRow_inlineCheckbox">
	{lang="or"}
	&nbsp;
	<span class='ipsCustomInput'>
		<input type="checkbox" role='checkbox' data-control="unlimited" name="{$input->name}_unlimited" id='{$input->name}_unlimited_check' value="1" {{if NULL === $input->value}}checked aria-checked='true'{{endif}} aria-labelledby='{$input->name}_unlimited_label'>
		<span></span>
	</span> <label for='{$input->name}_unlimited_check' id='{$input->name}_unlimited_label' class='ipsField_unlimited'>{lang="support_stream_any_time"}</label>
</div>
