<ips:template parameters="$input, $options" />
<div class="ipsTabs ipsClearfix ipsJS_show acpFormTabBar cNexusStream_tabs" id='elSupportTabs' data-ipsTabBar data-ipsTabBar-disableNav data-ipsTabBar-contentArea='#elRequestsTabContent'>
	<ul role="tablist">
		<a href="#elSupportTabs" data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		{{foreach $options as $stream}}
			<li class="cNexusStream">
				<span class='ipsTabs_item {{if $input->value == $stream->id}}ipsTabs_activeItem{{endif}}'>
					<input type="radio" name="stream" value="{$stream->id}" id="elRadio_stream_{$stream->id}" {{if $input->value == $stream->id}}checked{{endif}} data-action="quickToggle" data-url="{url="app=nexus&module=support&controller=requests&stream={$stream->id}" csrf="true"}">
					<span class='cNexusStream_count ipsCursor_pointer' data-action="quickToggleCount">{$stream->count( \IPS\Member::loggedIn() )}</span>
					<label for='elRadio_stream_{$stream->id}' id='elRadio_stream_{$stream->id}_label' class="ipsCursor_pointer">
						{{if $stream->temporary}}
							<a class='ipsResponsive_hidePhone ipsButton ipsButton_veryVerySmall ipsButton_primary ipsPos_right ipsSpacer_top ipsSpacer_half' href="{url="app=nexus&module=support&controller=requests&do=saveStream&id={$stream->id}"}" data-ipsMenu id="elSaveStream">{lang="save"}</a>
						{{elseif \is_int( $stream->id )}}
							<a class='ipsResponsive_hidePhone ipsButton ipsButton_veryVerySmall ipsButton_veryLight ipsPos_right ipsSpacer_top ipsSpacer_half' href="{url="app=nexus&module=support&controller=requests&do=editStream&id={$stream->id}"}" data-action="editStream">{lang="edit"} <i class='fa fa-angle-down'></i></a>
						{{endif}}
						<span title='{$stream->title}'>{$stream->title}</span>
					</label>
				</span>
			</li>
		{{endforeach}}
		<li class="cNexusStream">
			<span class='ipsTabs_item {{if $input->value == 'custom'}}ipsTabs_activeItem{{endif}}'>
				<input type="radio" name="stream" value="custom" id="elRadio_stream_custom" data-control="toggle" data-toggles="elFilterFormFull" {{if $input->value == 'custom'}}checked{{endif}} data-action="quickToggle">
				&nbsp;
				<label for='elRadio_stream_custom' id='elRadio_stream_custom_label' class="ipsCursor_pointer">
					<i class='fa fa-plus'></i> {lang="support_stream_other"}
				</label>
			</span>
		</li>
	</ul>
</div>