<ips:template parameters="$table, $headers, $rows" />
{{if $table->pages > 1}}
	<div data-role="tablePagination">
		{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
	</div>
	<br>
{{endif}}

<ul class='ipsDataList ipsDataList_large'>
	{{foreach $rows as $row}}
		<li class='ipsDataItem'>
			<div class='ipsDataItem_generic ipsDataItem_size4 ipsType_center ipsPos_top'>
				<ul class='ipsList_inline ipsClearfix ipsRating ipsRating_large'>
					{{foreach range( 1, 5 ) as $i}}
						<li class='{{if $row['rating_rating'] >= $i}}ipsRating_on{{endif}}'><i class='fa fa-star'></i></li>
					{{endforeach}}
				</ul>
			</div>
			<div class='ipsDataItem_main'>
				<h3 class='ipsType_reset ipsType_sectionHead'><span class='ipsType_light ipsType_unbold'>#{$row['r_id']}</span> <a href="{url="app=nexus&module=support&controller=request&id={$row['r_id']}"}">{$row['r_title']}</a></h3>
				<p class='ipsType_reset ipsType_normal ipsType_light'>{lang="performance_rated_by" sprintf="\IPS\Member::load( $row['rating_from'] )->name, \IPS\Member::load( $row['reply_member'] )->name"}</p>
				<p class='ipsType_reset ipsType_medium ipsSpacer_top ipsSpacer_half'>
					{{if $row['rating_note']}}{$row['rating_note']}{{else}}{lang="no_feedback"}{{endif}}
				</p>
			</div>
		</li>
	{{endforeach}}
</ul>

{{if $table->pages > 1}}
	<div data-role="tablePagination">
		{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
	</div>
{{endif}}