<ips:template parameters="$request, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar=NULL, $form=NULL" />

<form accept-charset='utf-8' class="cNexusSupportForm cNexusSupportForm_note ipsAreaBackground_reset ipsPadding ipsComposeArea ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm id='elNoteForm_form'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}

	{{if $elements['']['note']}}
		<div class='cNexusSupportForm_message'>
			{$elements['']['note']->html()|raw}
		</div>
	{{endif}}

	<div class='ipsClearfix ipsPadding_top ipsType_right' data-ipsEditor-toolList>
		<ul class='ipsList_inline ipsPos_left ipsType_left cNexusSupportForm_controls'>
			{{if isset( $elements['']['status'] )}}
				<li>
					<h3 class='ipsType_minorHeading'>{lang="status"}</h3>
					{$elements['']['status']->html()|raw}
				</li>
			{{endif}}
			{{if isset( $elements['']['department'] )}}
				<li>
					<h3 class='ipsType_minorHeading'>{lang="department"}</h3>
					{$elements['']['department']->html()|raw}
				</li>
			{{endif}}
			{{if isset( $elements['']['assign_to'] )}}
				<li>
					<h3 class='ipsType_minorHeading'>{lang="assign_to"}</h3>
					{$elements['']['assign_to']->html()|raw}
				</li>
			{{endif}}
		</ul>
		<button type='submit' class='ipsButton ipsButton_primary ipsButton_large'>{lang="add_note"}</button>
	</div>
</form>