<ips:template parameters="$results, $pagination, $groupByDepartment, $sortBy, $sortDir, $tracked, $participatedIn, $honorSeverities=TRUE" />


<div class="ipsButtonBar acpWidgetToolbar ipsClearfix ipsPad_half cNexusSupportTable_bar">
	<ul class="ipsButtonRow ipsPos_right ipsClearfix">
		<li>
			<a class="ipsJS_show" href="#elCheck_menu" id="elCheck" title='{lang="select_rows_tooltip"}' data-ipsTooltip data-ipsAutoCheck data-ipsAutoCheck-context=".cNexusSupportTable" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active">
				<span class="cAutoCheckIcon ipsType_medium"><i class="fa fa-square-o"></i></span> <i class="fa fa-caret-down"></i>
				<span class='ipsNotificationCount' data-role='autoCheckCount'>0</span>
			</a>
			<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elCheck_menu">
				<li class="ipsMenu_title">{lang="select_rows"}</li>
				<li class="ipsMenu_item" data-ipsMenuValue="all"><a href="#">{lang="all"}</a></li>
				<li class="ipsMenu_item" data-ipsMenuValue="none"><a href="#">{lang="none"}</a></li>
				<li class="ipsMenu_sep"><hr></li>
				<li class="ipsMenu_item" data-ipsMenuValue="read"><a href="#">{lang="read"}</a></li>
				<li class="ipsMenu_item" data-ipsMenuValue="unread"><a href="#">{lang="unread"}</a></li>
				<li class="ipsMenu_sep"><hr></li>
				<li class="ipsMenu_item" data-ipsMenuValue="tracking"><a href="#">{lang="tracking"}</a></li>
				<li class="ipsMenu_item" data-ipsMenuValue="not_tracking"><a href="#">{lang="not_tracking"}</a></li>
				<li class="ipsMenu_sep"><hr></li>
				{{foreach \IPS\nexus\Support\Status::roots() as $status}}
					<li class="ipsMenu_item" data-ipsMenuValue="status_{$status->id}"><a href="#">{$status->_title}</a></li>
				{{endforeach}}
			</ul>
		</li>
	</ul>
	<ul class="ipsButtonRow ipsPos_right ipsClearfix">
		<li>
			<a href="#elSortMenu_menu" id="elSortMenu" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu="radio" data-ipsMenu-stopLinks>{lang="sort_by"} <i class="fa fa-caret-down"></i></a>
			<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elSortMenu_menu">
				{{foreach array( 'r_started', 'r_last_new_reply', 'r_last_reply', 'r_last_staff_reply' ) as $k}}
					<li class="ipsMenu_item {{if $sortBy == $k}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="{$k}">
						<a href="{url="app=nexus&module=support&controller=requests&sortBy={$k}" csrf="true"}" data-group="sortBy" data-action="reloadTable">{lang="$k"}</a>
					</li>
				{{endforeach}}
				<li class="ipsMenu_sep"><hr></li>
				<li class="ipsMenu_item {{if $honorSeverities}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="1">
					<a href="{url="app=nexus&module=support&controller=requests&honorSeverities=1" csrf="true"}" data-group="severitySort" data-action="reloadTable">{lang="support_honor_severity_sort"}</a>
				</li>
				<li class="ipsMenu_item {{if !$honorSeverities}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="0">
					<a href="{url="app=nexus&module=support&controller=requests&honorSeverities=0" csrf="true"}" data-group="severitySort" data-action="reloadTable">{lang="support_no_honor_severity_sort"}</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="#elOrderMenu_menu" id="elOrderMenu" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu="radio" data-ipsMenu-stopLinks>{lang="order_by"} <i class="fa fa-caret-down"></i></a>
			<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elOrderMenu_menu">
				<li class="ipsMenu_item {{if $sortDir == 'ASC'}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="asc">
					<a href="{url="app=nexus&module=support&controller=requests&sortDir=ASC" csrf="true"}">{lang="support_oldest_first"}</a>
				</li>
				<li class="ipsMenu_item {{if $sortDir == 'DESC'}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="desc">
					<a href="{url="app=nexus&module=support&controller=requests&sortDir=DESC" csrf="true"}">{lang="support_newest_first"}</a>
				</li>
			</ul>
		</li>
	</ul>
	<ul class="ipsButtonRow ipsPos_right ipsClearfix">
		<li>
			{{if $groupByDepartment}}
				<a href="{url="app=nexus&module=support&controller=requests&groupByDepartment=0" csrf="true"}" class="ipsButtonRow_active" data-action="reloadTable">{lang="group_by_department"}</a>
			{{else}}
				<a href="{url="app=nexus&module=support&controller=requests&groupByDepartment=1" csrf="true"}" data-action="reloadTable">{lang="group_by_department"}</a>
			{{endif}}
		</li>
	</ul>
	{$pagination|raw}
</div>

<div data-controller='nexus.admin.support.multimod'>
	<form action="{url="app=nexus&module=support&controller=requests&do=multimod"}" method="post" data-ipsPageAction data-role='moderationTools'>
		<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
		{template="requestsTableResults" group="support" params="$results, $pagination, $groupByDepartment, $tracked, $participatedIn"}
	</form>
</div>