<ips:template parameters="$request, $requestActions=array()" />

<div class='cWithInfoPanel cNexusSupportRequest'>
	<div class='cWithInfoPanel_main'>
		{{if isset( \IPS\Request::i()->pending ) and \IPS\Request::i()->pending}}
			<div class="ipsMessage ipsMessage_error ipsJS_hide" data-controller="nexus.admin.support.pendingalert">
				{lang="support_pending"}
			</div>
		{{endif}}

		{{$purchase = $request->purchase;}}
		<p class="ipsMessage ipsMessage_error {{if ( $purchase and $purchase->active ) or !$purchase or !$request->department->require_package}}ipsHide{{endif}}" data-role="purchaseWarning" data-purchaseWarning="purchaseWarningInactiveRequired">{lang="request_purchase_inactive"}</p>
		<p class="ipsMessage ipsMessage_warning {{if ( $purchase and $purchase->active ) or !$purchase or $request->department->require_package or !$request->department->packages}}ipsHide{{endif}}" data-role="purchaseWarning" data-purchaseWarning="purchaseWarningInactiveOptional">{lang="request_purchase_inactive_optional"}</p>
		<p class="ipsMessage ipsMessage_error {{if $purchase or !$request->department->require_package}}ipsHide{{endif}}" data-role="purchaseWarning" data-purchaseWarning="purchaseWarningNoneRequired">{lang="request_purchase_none"}</p>
		<p class="ipsMessage ipsMessage_warning {{if $purchase or $request->department->require_package or !$request->department->packages}}ipsHide{{endif}}" data-role="purchaseWarning" data-purchaseWarning="purchaseWarningNoneOptional">{lang="request_purchase_none_optional"}</p>
		{{if $purchase}}
			<div class='ipsBox'>
				<h2 class='ipsBox_titleBar'>{lang="associated_purchase"}</h2>
				<div class='ipsPad'>
					<div class='ipsColumns ipsColumns_collapsePhone'>
						{{if $purchase->expire and !$purchase->cancelled}}
							<div class='ipsColumn ipsColumn_narrow ipsType_center'>
								{{if $purchase->cancelled || !$purchase->active}}
									<span class='ipsBadge ipsBadge_icon ipsBadge_large ipsBadge_negative'>
										<i class='fa fa-times'></i>
									</span>
								{{else}}
									<span class='ipsBadge ipsBadge_icon ipsBadge_large ipsBadge_positive'>
										<i class='fa fa-check'></i>
									</span>
								{{endif}}
								
								<p class='ipsType_large ipsType_reset ipsSpacer_top ipsSpacer_half'>
									{{if $purchase->cancelled}}
										<strong class='ipsType_negative'>{lang="purchase_canceled"}</strong>
									{{elseif !$purchase->active}}
										<strong class='ipsType_negative'>{lang="purchase_expired"}</strong>
									{{else}}
										<strong class='ipsType_positive'>{lang="purchase_active"}</strong>
									{{endif}}
								</p>
							</div>
						{{endif}}
						<div class='ipsColumn ipsColumn_fluid'>
							<h2 class='ipsType_sectionHead cNexusSupportHeader_title ipsType_blendLinks'><a href="{$purchase->acpUrl()}">{$purchase->_name}</a> <span class="ipsType_small ipsType_light">#{$purchase->id}</span></h2>

							{{if $parent = $purchase->parent()}}
								<p class='ipsType_reset ipsType_medium ipsType_blendLinks'>
									{lang="ps_parent"}:
									<a href="{$parent->acpUrl()}">
										{{if $parent->cancelled}}
											<i class='fa fa-times-circle' title="{lang="purchase_canceled"}" data-ipsTooltip></i>
										{{elseif !$parent->active}}
											<i class='fa fa-exclamation-circle' title="{lang="purchase_expired"}" data-ipsTooltip></i>
										{{endif}}
										{$parent->name}
									</a>
								</p>
							{{endif}}

							{{if $purchase->childrenCount()}}
								<ul class='ipsList_inline ipsType_blendLinks'>
									{{foreach $purchase->children( NULL ) as $child}}
										<li>
											{{if $child->cancelled}}
												<a href='{$child->acpUrl()}' class='ipsType_negative'><i class='fa fa-times-circle' title="{lang="purchase_canceled"}" data-ipsTooltip></i> {$child->name}</a>
											{{elseif !$child->active}}
												<a href='{$child->acpUrl()}' class='ipsType_negative'><i class='fa fa-exclamation-circle' title="{lang="purchase_expired"}" data-ipsTooltip></i> {$child->name}</a>
											{{else}}
												<a href='{$child->acpUrl()}' class='ipsType_positive'><i class='fa fa-check'></i> {$child->name}</a>
											{{endif}}
										</li>
									{{endforeach}}
								</ul>
							{{endif}}
							<hr class='ipsHr ipsHr_small'>
							<table class='cNexusSupportHeader ipsTable ipsTable_responsive' data-controller='nexus.admin.support.packageInfo'>
								{{if $purchase->renewals}}
									<tr class='cNexusSupportHeader_row'>
										<td class='cNexusSupportHeader_colTitle'>
											{lang="billing"}
										</td>
										<td class='cNexusSupportHeader_colInfo ipsTable_wrap'>
											<ul class='ipsList_inline'>
												<li>
													<i class='fa fa-refresh'></i> &nbsp;{lang="renews"} {$purchase->renewals}
												</li>
												{{if $billingAgreement = $purchase->billing_agreement}}
													<li>
														<i class='fa fa-paypal'></i> &nbsp;<a href="{$billingAgreement->acpUrl()}" class="ipsType_blendLinks">{lang="ps_billing_agreement"} {$billingAgreement->gw_id}</a>
														{{if $billingAgreement->canceled}}
															({lang="billing_agreement_canceled"})
														{{endif}}
													</li>
												{{endif}}

												{{if $purchase->grace_period}}
													{{$grace = new \DateInterval( 'PT' . $purchase->grace_period . 'S' );}}
													<li>
														<i class='fa fa-clock-o'></i> &nbsp;{lang="p_grace_period"} {expression="\IPS\DateTime::formatInterval( \IPS\DateTime::create()->diff( \IPS\DateTime::create()->add( $grace ) ), 0 )"}
													</li>
												{{endif}}
											</ul>
										</td>
									</tr>
								{{endif}}
								<tr class='cNexusSupportHeader_row'>
									<td class='cNexusSupportHeader_colTitle'>
										{lang="support_purchase"}
									</td>
									<td class='cNexusSupportHeader_colInfo ipsTable_wrap'>
										<ul class='ipsList_inline'>
											<li>
												<i class='fa fa-calendar-check-o'></i> &nbsp;{lang="ps_start"} {$purchase->start->localeDate()}
											</li>
											{{if $purchase->expire}}
												<li>
													<i class='fa fa-calendar-times-o'></i> &nbsp;{lang="ps_expire"} {$purchase->expire->localeDate()}
												</li>
											{{endif}}
										</ul>
									</td>
								</tr>
								{{if $licenseKey = $request->purchase->licenseKey()}}
									<tr class='cNexusSupportHeader_row'>
										<td class='cNexusSupportHeader_colTitle'>
											{lang="license_key"}
										</td>
										<td class='cNexusSupportHeader_colInfo ipsTable_wrap'>
											<div class="ipsType_monospace cNexusLicenseKey ipsContained ipsType_break">
												{$licenseKey->key}
											</div>
										</td>
									</tr>
								{{endif}}								
								{$purchase->acpSupportView()|raw}
								{{if $purchase->custom_fields}}
									{{$countRows = 0;}}
									{{foreach $purchase->custom_fields as $k => $v}}
										{{try { $pfield = \IPS\nexus\Package\CustomField::load( $k ); } catch( \Exception $e ) { $pfield = NULL; } }}
										{{if $pfield and $displayValue = trim( $pfield->displayValue( $v, TRUE ) )}}
											<tr class='cNexusSupportHeader_row cNexusSupportHeader_optional {{if !isset( request.cookie['showAllPackageInfo'] ) || !request.cookie['showAllPackageInfo']}}ipsHide{{endif}}'>
												<td class='cNexusSupportHeader_colTitle'>{lang="nexus_pfield_{$k}"}</td>
												<td class='cNexusSupportHeader_colInfo ipsTable_wrap'>{$displayValue|raw}</td>
											</tr>
											{{$countRows++;}}
										{{endif}}
									{{endforeach}}
									{{if $countRows}}
										<tr class='cNexusSupportHeader_row'>
											<td colspan='2'>
												<a href='#' data-action='showFewerRows' class='{{if !isset( request.cookie['showAllPackageInfo'] ) || !request.cookie['showAllPackageInfo']}}ipsHide{{endif}}'>{lang="show_fewer_rows"} <i class='fa fa-angle-up'></i></a>
												<a href='#' data-action='showMoreRows' class='{{if isset( request.cookie['showAllPackageInfo'] ) && request.cookie['showAllPackageInfo']}}ipsHide{{endif}}'>{lang="show_x_rows" pluralize="$countRows"} <i class='fa fa-angle-down'></i></a> 
											</td>
										</tr>
									{{endif}}
								{{endif}}
							</table>
						</div>
					</div>
				</div>
			</div>

			<hr class='ipsHr'>
		{{endif}}

		<section class='ipsBox cNexusSupportForm' data-controller='nexus.admin.support.replyArea'>
			<div>
				<div class="ipsTabs ipsTabs_small ipsClearfix" id="elSupportForm" data-ipsTabBar data-ipsTabBar-contentArea="#elSupportForm_content">
					<a href="#elSupportForm" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
					<ul role="tablist">
						<li>
							<a href="#" id="elStaffForm" class="ipsTabs_item ipsType_center ipsTabs_activeItem" data-role='replyTab' role="tab" aria-selected="true">{lang="staff_reply"}</a>
						</li>
						<li>
							<a href='#' id='elNoteForm' class='ipsTabs_item ipsType_center' data-role='noteTab' role="tab" aria-selected="false">{lang="staff_note"}</a>
						</li>
					</ul>
				</div>
				<div id="elSupportForm_content" class="ipsTabs_panels ipsClearfix">
					<div id="ipsTabs_elSupportForm_elStaffForm_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false" data-role="replyForm">
						{$request->staffReplyForm()|raw}
					</div>
					<div id="ipsTabs_elSupportForm_elNoteForm_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false" data-role="noteForm">
						{$request->noteForm()|raw}
					</div>
				</div>			
			</div>
		</section>
		
		<section class='ipsSpacer_top'>
			<div data-controller='core.front.core.commentFeed' {{if settings.auto_polling_enabled}}data-autoPoll{{endif}} data-baseURL='{$request->acpUrl()}' data-feedID='request-{$request->id}'>
				{{$order = isset( \IPS\Request::i()->order ) ? \IPS\Request::i()->order : ( isset( \IPS\Request::i()->cookie['support_replies_order'] ) ? \IPS\Request::i()->cookie['support_replies_order'] : 'desc' );}}

				<div class='ipsClearfix'>
					{{if $request->commentPageCount() > 1}}
						<div class='ipsPos_left ipsResponsive_noFloat'>
							{$request->commentPagination( array(), 'pagination', NULL, $request->acpUrl() )|raw}
						</div>
					{{endif}}
					<ul class='ipsButtonRow ipsClearfix ipsPos_right'>
						<li class='ipsPos_left'>
							<a href='{$request->acpUrl()->setQueryString( array( 'order' => 'asc' ) )->csrf()}' class='{{if $order == 'asc'}}ipsButtonRow_active{{endif}}'>{lang="responses_asc"}</a>
						</li>
						<li>
							<a href='{$request->acpUrl()->setQueryString( array( 'order' => 'desc' ) )->csrf()}' class='{{if $order == 'desc'}}ipsButtonRow_active{{endif}}'>{lang="responses_desc"}</a>
						</li>
					</ul>
				</div>
				
				<hr class='ipsHr'>

				<div data-controller='nexus.admin.support.multimod'>
					<form action="{$request->acpUrl()->setQueryString('do', 'multimod')->setPage('page',\IPS\Request::i()->page)}" method="post" data-ipsPageAction data-role='moderationTools'>
						<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
						{{foreach $request->repliesAndLog( $order ) as $comment}}
							{{if $comment instanceof \IPS\nexus\Support\Reply}}
								{$comment->html()|raw}
							{{else}}
								<p class='ipsType_reset ipsType_medium cNexusSupportRequest_action'>
									{{if $comment->action === 'status'}}
										<i class='fa fa-tag'></i> &nbsp;&nbsp;{lang="reply_action_status" sprintf="$comment->member->name, $comment->new ? $comment->new->_title : '?'"}
									{{elseif $comment->action === 'department'}}
										<i class='fa fa-folder'></i> &nbsp;&nbsp;{lang="reply_action_moved" sprintf="$comment->member->name, $comment->new ? $comment->new->_title : '?'"}
									{{elseif $comment->action === 'severity'}}
										<i class='fa fa-exclamation'></i> &nbsp;&nbsp;{lang="reply_action_severity" sprintf="$comment->member->name, $comment->new ? $comment->new->_title : '?'"}
									{{elseif $comment->action === 'purchase'}}
										{{if $comment->new}}
											<i class='fa fa-cube'></i> &nbsp;&nbsp;{lang="reply_action_associate" sprintf="$comment->member->name, $comment->new->acpUrl(), $comment->new->name"}
										{{else}}
											<i class='fa fa-minus-circle'></i> &nbsp;&nbsp;{lang="reply_action_unassociate" sprintf="$comment->member->name"}
										{{endif}}
									{{elseif $comment->action === 'staff'}}
										{{if $comment->new}}
											<i class='fa fa-user'></i> &nbsp;&nbsp;{lang="reply_action_assign" sprintf="$comment->member->name, $comment->new->name"}
										{{else}}
											<i class='fa fa-minus-circle'></i> &nbsp;&nbsp;{lang="reply_action_unassign" sprintf="$comment->member->name"}
										{{endif}}
									{{elseif $comment->action === 'split_away'}}
										{{if $comment->new}}
											<i class='fa fa-expand'></i> &nbsp;&nbsp;{lang="reply_action_split_away_from" sprintf="$comment->member->name, $comment->new->acpUrl(), $comment->new->title"}
										{{else}}
											<i class='fa fa-expand'></i> &nbsp;&nbsp;{lang="reply_action_split_away" sprintf="$comment->member->name"}
										{{endif}}
									{{elseif $comment->action === 'split_new'}}
										{{if $comment->old}}
											<i class='fa fa-expand'></i> &nbsp;&nbsp;{lang="reply_action_split_new_to" sprintf="$comment->member->name, $comment->old->acpUrl(), $comment->old->title"}
										{{else}}
											<i class='fa fa-expand'></i> &nbsp;&nbsp;{lang="reply_action_split_new" sprintf="$comment->member->name"}
										{{endif}}
									{{elseif $comment->action === 'previous_request'}}
										{{if $comment->old}}
											<i class='fa fa-envelope-o'></i> &nbsp;&nbsp;{lang="reply_action_previous_request" sprintf="$comment->old->acpUrl(), $comment->old->title"}
										{{elseif $comment->new}}
											<i class='fa fa-envelope-o'></i> &nbsp;&nbsp;{lang="reply_action_previous_request_new" sprintf="$comment->new->acpUrl(), $comment->new->title"}
										{{else}}
											<i class='fa fa-envelope-o'></i> &nbsp;&nbsp;{lang="reply_action_previous_request_none"}
										{{endif}}
									{{elseif $comment->action === 'autoresolve_warning'}}
										<i class='fa fa-tag'></i> &nbsp;&nbsp;{lang="reply_action_autoresolve_warning"}
									{{elseif $comment->action === 'autoresolve'}}
										<i class='fa fa-tag'></i> &nbsp;&nbsp;{lang="reply_action_autoresolve" sprintf="$comment->new ? $comment->new->_title : '?'"}
									{{elseif $comment->action === 'merge'}}
										<i class='fa fa-level-up'></i> &nbsp;&nbsp;{lang="reply_action_merge" sprintf="$comment->member->name"}
									{{endif}}
		
									<span class='ipsType_light cNexusAdminSupportMessage_date'>{datetime="$comment->date"}</span>
								</p>
							{{endif}}
						{{endforeach}}
						<div class="ipsClearfix ipsJS_hide" data-role="pageActionOptions">
							<div class="ipsPos_right">
								<select name="modaction" data-role="moderationAction">
									<option value="split" data-icon="expand">{lang="split"}</option>
									<option value="delete" data-icon="trash">{lang="delete"}</option>
								</select>
								<button type="submit" class="ipsButton ipsButton_alternate ipsButton_verySmall">{lang="submit"}</button>
							</div>
						</div>
					</form>
				</div>

				{{if $request->commentPageCount() > 1}}
					<div class='ipsSpacer_top'>
						{$request->commentPagination( array(), 'pagination', NULL, $request->acpUrl() )|raw}
					</div>
				{{endif}}
			</div>
		</section>

		{{$previous = $request->nextPrevious( 1 );}}
		{{$next = $request->nextPrevious();}}
		{{if $next or $previous}}
			<hr class='ipsHr'>
			<nav class="ipsPager ipsSpacer_top">
				<div class="ipsPager_prev">
					{{if $previous}}
						<a href="{$previous->acpUrl()}" title="{lang="keyboard_shortcut_prev_req"}" data-ipsTooltip data-role="prevRequestLink">
							<span class="ipsPager_type">{lang="prev_request"}</span>
							<span class="ipsPager_title ipsType_break ipsTruncate ipsTruncate_line">{$previous->title}</span>
						</a>
					{{endif}}
				</div>
				<div class="ipsPager_next">
					{{if $next}}
						<a href="{$next->acpUrl()}" title="{lang="keyboard_shortcut_next_req"}" data-ipsTooltip data-role="nextRequestLink">
							<span class="ipsPager_type">{lang="next_request"}</span>
							<span class="ipsPager_title ipsType_break ipsTruncate ipsTruncate_line">{$next->title}</span>
						</a>
					{{endif}}
				</div>
			</nav>
		{{endif}}
	</div>
	<div class='cWithInfoPanel_info cNexusSupportRequest_metaInfo'>
		<div id='elNexusRequestInfo'>
			{{if \count( $requestActions )}}
				<div id='elNexusRequestControls' class='ipsPad'  data-ipsSticky data-ipsSticky-spacing='60'>
					{template="requestActions" app="nexus" group="support" params="$requestActions"}
				</div>
			{{endif}}
			<hr class='ipsHr'>

			<div class='ipsPad'>
				<div class="ipsBox ipsSpacer_bottom">
					<h3 class='ipsBox_titleBar'>
						{{if $name = $request->supportAuthor()->name()}}
							{$name}
							{{if $link = $request->supportAuthor()->url()}}
								<a href="{$link}" class='ipsPos_right ipsType_medium'>{lang="view_account"}</a>
							{{endif}}
						{{endif}}
					</h3>
					<div class='ipsPad ipsType_center'>
						
						{{if $photo = $request->supportAuthor()->photo()}}
							{{if $link = $request->supportAuthor()->url()}}
								<a href="{$link}"><img src='{$photo}' class='ipsUserPhoto ipsUserPhoto_medium' alt=''></a>
							{{else}}
								<img src='{$photo}' class='ipsUserPhoto ipsUserPhoto_medium'>
							{{endif}}
							<hr class='ipsHr'>
						{{endif}}
						
						{{if $meta = $request->supportAuthor()->meta()}}
							<ul class='ipsList_reset ipsType_medium'>
								{{foreach $meta as $meta}}
									<li>{$meta}</li>
								{{endforeach}}
							</ul>
						{{endif}}
						
						{{if member.hasAcpRestriction( 'nexus', 'customers', 'customer_notes_view' ) and $request->member}}
							<hr class='ipsHr'>
							<p class='ipsType_reset ipsType_medium'>
								{{if $noteCount = $request->supportAuthor()->noteCount()}}
									<strong><a href='{url="app=core&module=members&controller=members&do=lazyBlock&block=IPS\\nexus\\extensions\\core\\MemberACPProfileBlocks\\Notes&id={$request->member}&support={$request->id}"}' data-ipsDialog data-ipsDialog-title="{lang="customer_notes"}">{lang="num_customer_notes" pluralize="$noteCount"}</a></strong>
								{{else}}
									{lang="num_customer_notes" pluralize="0"}
								{{endif}}
								{{if member.hasAcpRestriction( 'nexus', 'customers', 'customer_notes_add' )}}
									&nbsp;&nbsp;<a href='{url="app=nexus&module=customers&controller=view&id={$request->member}&do=noteForm&support={$request->id}"}' data-ipsDialog data-ipsDialog-title="{lang="add_note"}">{lang="add_note"}</a>
								{{endif}}
							</p>
						{{endif}}

						{{if ( $request->member && \IPS\Member::loggedIn()->hasAcpRestriction( 'core', 'members', 'member_login' ) AND !\IPS\Member::load( $request->member )->isBanned() )}}
							<p class='ipsType_reset ipsType_medium'>
								<a href='{url="app=core&module=members&controller=members&do=login&id={$request->member}" csrf="true"}' target='_blank' rel='noopener'>{lang="sign_in_as_customer"}</a>
							</p>
						{{endif}}
					</div>	
				
					{{$otherRequests = $request->supportAuthor()->supportRequests( 10, $request );}}
					{{$otherRequestsCount = $request->supportAuthor()->supportRequests( 10, $request, '', TRUE );}}
					{{$invoices = member.hasAcpRestriction( 'nexus', 'payments', 'invoices_manage' ) ? $request->supportAuthor()->invoices() : NULL;}}
					{{$invoicesTotalCount = member.hasAcpRestriction( 'nexus', 'payments', 'invoices_manage' ) ? $request->supportAuthor()->invoices( 0, TRUE ) : 0;}}
					
					{{if ( $otherRequests and $otherRequests->count() ) or ( $invoices and $invoices->count() )}}
						{{if ( $otherRequests and $otherRequests->count() ) and ( $invoices and $invoices->count() )}}
							<div class="ipsTabs ipsTabs_small ipsTabs_stretch ipsClearfix ipsSpacer_top" id="elRequestMeta" data-ipsTabBar data-ipsTabBar-contentArea="#elRequestMeta_content">
								<a href="#elRequestMeta" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
								<ul role="tablist">
									{{if $otherRequests and \count( $otherRequests )}}
										<li>
											<a href='#' id='elRequestHistory' class='ipsTabs_item ipsType_center' data-role='noteTab' role="tab" aria-selected="false">{lang="support_info_requests"} ({$otherRequestsCount})</a>
										</li>
									{{endif}}
									{{if $invoices and \count( $invoices )}}
										<li>
											<a href='#' id='elInvoiceHistory' class='ipsTabs_item ipsType_center' data-role='noteTab' role="tab" aria-selected="false">{lang="support_info_invoices"} ({$invoicesTotalCount})</a>
										</li>
									{{endif}}
								</ul>
							</div>
						{{endif}}
						<div id="elRequestMeta_content" class="ipsTabs_panels ipsClearfix">
							{{if $otherRequests}}
								<div id="ipsTabs_elRequestMeta_elRequestHistory_panel" class="ipsTabs_panel ipsPad ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
									{{if !$invoices or !$invoices->count()}}
										<h2 class="ipsType_sectionHead ipsType_large">{lang="support_info_requests"}</h2>
									{{endif}}
									<ul class='ipsDataList ipsDataList_reducedSpacing ipsList_reset'>
										{{foreach $otherRequests as $otherRequest}}
											<li class='ipsDataItem ipsContained'>
												<div class='ipsDataItem_main ipsType_blendLinks ipsTruncate ipsTruncate_line'>
													{template="status" group="support" app="nexus" params="\IPS\nexus\Support\Status::load( $otherRequest->status->id ), 'ipsPos_right'"}
													<a href="{$otherRequest->acpUrl()}" data-ipsDialog data-ipsDialog-title="{$otherRequest->title} (#{$otherRequest->id})" data-ipsDialog-url="{$otherRequest->acpUrl()->setQueryString( 'popup', $request->id )}" class='ipsDataItem_title'>{$otherRequest->title}</a>
													<p class='ipsDataItem_meta ipsType_reset ipsType_small ipsType_light'>#{$otherRequest->id} &nbsp;&nbsp;&nbsp; {datetime="$otherRequest->mapped('date')"}</p>
												</div>
											</li>
										{{endforeach}}
									</ul>
									{{if $otherRequestsCount > 10}}
										<div class="ipsType_center">
											{{$param = $request->member ? "member={$request->member}" : "email={$request->email}";}}
											<a href="{url="app=nexus&module=support&controller=requests&{$param}"}" class="ipsButton ipsButton_verySmall ipsButton_normal">{lang="see_all_support" pluralize="$otherRequestsCount"}</a>
										</div>
									{{endif}}
								</div>
							{{endif}}
							{{if member.hasAcpRestriction( 'nexus', 'payments', 'invoices_manage' ) and $invoices}}
								<div id="ipsTabs_elRequestMeta_elInvoiceHistory_panel" class="ipsTabs_panel ipsPad_half ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
									{{if !$otherRequests or !$otherRequests->count()}}
										<h2 class="ipsType_sectionHead ipsType_large">{lang="support_info_invoices"}</h2>
									{{endif}}
									<ul class='ipsDataList'>
										{{foreach $invoices as $invoice}}
											<li class='ipsDataItem'>
												<div class='ipsDataItem_main ipsType_blendLinks'>
													<p class='ipsType_reset ipsType_normal'>
														<a href="{$invoice->acpUrl()}"><span class='ipsType_light ipsType_medium'>#{$invoice->id}</span> {$invoice->title}</a>
													</p>
													<p class='ipsType_reset ipsType_medium'>
														{template="status" group="invoices" params="$invoice->status"} &nbsp;&nbsp;<strong>{$invoice->total}</strong> &nbsp;&nbsp;<span class='ipsType_light'>{datetime="$invoice->date"}</span>
													</p>
												</div>
											</li>
										{{endforeach}}
									</ul>
									{{if $invoicesTotalCount > 10}}
										<div class="ipsType_center">
											<a href="{url="app=nexus&module=customers&controller=view&id={$request->member}&tab=invoices"}" class="ipsButton ipsButton_verySmall ipsButton_normal">{lang="see_all_invoices" pluralize="$invoicesTotalCount"}</a>
										</div>
									{{endif}}
								</div>
							{{endif}}
						</div>
					{{endif}}
				</div>

				{{if $customFields = $request->department->customFields()}}
					{{$customFieldValues = $request->cfields;}}
					<div class="ipsBox ipsSpacer_bottom">
						<h2 class="ipsBox_titleBar">
							{lang="support_additional_info"}
						</h2>
						&nbsp;&nbsp;<a href="{$request->acpUrl()->setQueryString( 'do', 'cfields' )}" data-ipsDialog data-ipsDialog-title="{lang="custom_support_fields"}" class="ipsType_small">({lang="edit"})</a>
						<ul class='ipsList_reset ipsSpacer_top ipsPad'>
							{{foreach $customFields as $field}}
								<li class='ipsSpacer_bottom ipsSpacer_half'>
									<h4 class='ipsType_minorHeading'>{$field->_title}</h4>
									<div class='ipsType_richText ipsType_medium ipsContained ipsType_break'>
										{{if isset( $customFieldValues[ $field->id ] ) AND ( $customFieldValues[ $field->id ] OR $customFieldValues[ $field->id ] == '0' )}}
											{$field->displayValue( $customFieldValues[ $field->id ], TRUE )|raw}
										{{else}}
											<em class="ipsType_light">{lang="no_value"}</em>
										{{endif}}
									</div>
								</li>
							{{endforeach}}
						</ul>
					</div>
				{{endif}}
				
				{{if $ppiInvoice = $request->ppi_invoice}}
					<div class="ipsBox ipsSpacer_bottom">
						<h2 class="ipsBox_titleBar">
							{lang="ppi_invoice"}
						</h2>
						&nbsp;&nbsp;<a href="{$ppiInvoice->acpUrl()}" class="ipsType_small">({lang="view"})</a>
						{{$summary = $ppiInvoice->summary();}}

						<ul class='ipsDataList ipsDataList_reducedSpacing ipsSpacer_top ipsSpacer_half ipsPad'>
							{{foreach $summary['items'] as $item}}
								{{if !( $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount )}}
									<li class='ipsDataItem'>
										<div class='ipsDataItem_main ipsType_break ipsContained'>
											<span class='ipsType_medium'>
												{{if $item->quantity > 1}}<span class='ipsType_light'>{$item->quantity} x </span>{{endif}}
												{$item->name}
											</span>
											{{if \count( $item->details )}}
												<br>
												<span class="ipsType_light">
													{{foreach $item->details as $k => $v}}
														{lang="nexus_pfield_{$k}"}: {$v}<br>
													{{endforeach}}
												</span>
											{{endif}}
										</div>
										<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right'>
											<span class='cNexusPrice ipsType_normal'>{$item->linePrice()}</span>
											{{if $item->quantity > 1}}
												<p class='ipsType_reset ipsType_small ipsType_light'>{lang="each_short" sprintf="$item->price"}</p>
											{{endif}}
										</div>
									</li>
								{{endif}}
							{{endforeach}}
							{{foreach $summary['items'] as $item}}
								{{if $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount}}
									<li class='ipsDataItem cNexusCheckout_coupon'>
										<div class='ipsDataItem_main ipsType_right'>
											<strong>{lang="coupon"}</strong>
										</div>
										<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
											{$item->linePrice()}
										</div>
									</li>
								{{endif}}
							{{endforeach}}	
							<li class='ipsDataItem cNexusCheckout_subtotal'>
								<div class='ipsDataItem_main ipsType_right'>
									<strong>{lang="subtotal"}</strong>
								</div>
								<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
									{$summary['subtotal']}
								</div>
							</li>
							{{foreach $summary['tax'] as $taxId => $tax}}
								<li class='ipsDataItem'>
									<div class='ipsDataItem_main ipsType_right'>
										<strong>{lang="nexus_tax_{$taxId}"} <span class='ipsType_light ipsType_unbold'>({expression="$tax['rate']*100"}%)</span></strong>
									</div>
									<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
										{$tax['amount']}
									</div>
								</li>
							{{endforeach}}
							<li class='ipsDataItem ipsType_large cNexusCheckout_subtotal'>
								<div class='ipsDataItem_main ipsType_right'>
									<strong>{lang="total"}</strong>
								</div>
								<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
									<strong>{$summary['total']}</strong>
								</div>
							</li>
						</ul>
					</div>
				{{endif}}
				
				<div class="ipsBox">
					<h2 class="ipsBox_titleBar">
						{lang="viewed_by"}
					</h2>
					{{foreach $request->staffViews() as $view}}
						<div class='ipsPad ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
							<img src='{member="photo" id="$view['view_member']"}' class='ipsUserPhoto ipsUserPhoto_tiny ipsPos_left' alt=''>
							<div>
								<strong>{member="name" id="$view['view_member']"}</strong>

								<ul class='ipsList_inline ipsType_small'>
									{{if $view['view_reply']}}
										<li><i class='fa fa-mail-reply'></i> {datetime="$view['view_reply']"}</li>
									{{endif}}
									<li {{if $view['view_last'] !== $view['view_first']}}data-ipsTooltip title="{lang="view_first"} {datetime="$view['view_first']" norelative="true"}"{{endif}}><i class='fa fa-eye'></i> {datetime="$view['view_last']"}</li>
								</ul>
							</div>
						</div>
					{{endforeach}}
				</div>
			</div>
		</div>
	</div>
</div>