<ips:template parameters="$actions" />

<ul class='ipsList_reset'>
	{{foreach $actions as $action}}
		<li>
			{{if \count($action['menu']) > 1}} 
				<a href='#' class='ipsType_blendLinks' {{if isset( $action['menu'] )}}data-ipsMenu id='{{$id = mt_rand();}}{$id}'{{endif}} {{if isset( $action['data'] )}}{{foreach $action['data'] as $k => $v}}data-{$k}="{$v}" {{endforeach}}{{endif}}>
			{{else}}
				<span>
			{{endif}}
			   <h3 class='ipsType_minorHeading'>{$action['tooltip']}</h3>
				<p class='ipsType_reset cNexusSupportStatus_value ipsTruncate ipsTruncate_line'><span data-role="title">{lang="$action['title']"}</span></p>
			{{if \count($action['menu']) > 1}} 
				</a>
			{{else}}
				</span>
			{{endif}}
			{{if isset( $action['menu'] )}}
				<div id='{$id}_menu' class='ipsMenu {{if isset( $action['menuClass'] )}}{$action['menuClass']}{{endif}} ipsHide'>
					<ul>
						{{foreach $action['menu'] as $item}}
							{{if isset( $item['hr'] ) and $item['hr']}}
								<li class='ipsMenu_sep'><hr></li>
							{{else}}
								<li class="ipsMenu_item {{if isset( $item['class'] )}}{$item['class']}{{endif}}" {{if isset( $item['data'] )}}{{foreach $item['data'] as $k => $v}} data-{$k}="{$v}"{{endforeach}}{{endif}}>
									<a href="{$item['link']}">
										{{if isset( $item['icon'] )}}
											<i class='fa fa-{$item['icon']}'></i> &nbsp;&nbsp;
										{{endif}}
										<span data-role="title">{lang="$item['title']"}</span>
									</a>
								</li>
							{{endif}}
						{{endforeach}}
					</ul>
				</div>
			{{endif}}
		</li>
	{{endforeach}}
</ul>