<ips:template parameters="$request, $overviews" />

<div>
	{{if \count( $overviews ) > 1}}
		<div class="ipsTabs ipsTabs_small ipsTabs_container ipsClearfix" id="elSupportRequest_{$request->id}" data-ipsTabBar data-ipsTabBar-contentarea="#elSupportRequest_{$request->id}_content">
			<a href="#elSupportRequest_{$request->id}" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
			<ul role="tablist">
				{{foreach $overviews as $tabID => $tabData}}
					<li>
						<a href="#ipsTabs_elSupportRequest_{$request->id}_elSupportRequest_{$request->id}_{$tabID}_panel" id="elSupportRequest_{$request->id}_{$tabID}" class="ipsTabs_item ipsType_center" role="tab" aria-selected="{{if $tabID == 'firstMessage'}}true{{else}}false{{endif}}">{lang="$tabData[0]"}</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<div id='elSupportRequest_{$request->id}_content' class='ipsTabs_panels ipsTabs_contained ipsScrollbar'>
	{{else}}
		<div class='ipsPad ipsScrollbar'>
	{{endif}}

		{{foreach $overviews as $tabID => $tabData}}
			{{if \count( $overviews ) > 1}}
				<div id='ipsTabs_elSupportRequest_{$request->id}_elSupportRequest_{$request->id}_{$tabID}_panel' class='ipsTabs_panel'>
			{{endif}}
				{template="replyContainer" group="support" params="$request, $tabData[1], TRUE"}
			{{if \count( $overviews ) > 1}}
				</div>
			{{endif}}
		{{endforeach}}
	</div>
</div>