<ips:template parameters="$table" />
<div class="ipsPad ipsType_normal ipsSpacer_bottom ipsAreaBackground_light">
	{lang="severities_desc"}
	<br><br>
	<div class="ipsClearfix">
		<div class="ipsPos_left">
			<strong>{lang="nexus_severities"}</strong><br>
			<span class="ipsType_light ipsType_small">{lang="nexus_severities_desc"}</span>
		</div>
		<div class="ipsPos_left ipsPad_half">
			{{if settings.nexus_severities}}
				<a href="{url="app=nexus&module=support&controller=settings&tab=severities&nexus_severities=0" csrf="true"}"><span class="ipsToggle ipsToggle_on" id="check_sev_public_wrapper" tabindex="0"><span data-role="status">{lang="on"}</span></span></a>
			{{else}}
				<a href="{url="app=nexus&module=support&controller=settings&tab=severities&nexus_severities=1" csrf="true"}"><span class="ipsToggle ipsToggle_off" id="check_sev_public_wrapper" tabindex="0"><span data-role="status">{lang="off"}</span></span></a>
			{{endif}}
		</div>
	</div>
</div>
{$table|raw}