<ips:template parameters="$request, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar=NULL, $form=NULL" />

<form accept-charset='utf-8' class="cNexusSupportForm ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm id='elSupportReplyForm'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	
	<div class='ipsComposeArea ipsAreaBackground_reset ipsPadding'>
						
		<div class='ipsMargin_bottom cNexusSupportForm_sendTo ipsJS_hide ipsClearfix' data-ipsEditor-toolList>
			{{if isset( $elements['']['stock_action'] )}}
				<span class='ipsPos_right ipsResponsive_noFloat cNexusSupportForm_customAction'><i class='fa fa-flash ipsType_large ipsPos_middle' title='{lang="stock_actions"}' data-ipsTooltip></i> {$elements['']['stock_action']->html()|raw}</span>
			{{endif}}
			<div data-role='sendToInfo'>
				<p class='ipsType_reset ipsType_normal cNexusSupportForm_to'>
					<strong>{lang="to"}:</strong> {$elements['']['to']->value}  &nbsp;&nbsp;<a href='#' class='ipsType_small' data-action='showCCForm'>({lang="edit_cc_bcc"})</a>			
				</p>
				{{if \count( $elements['']['cc']->value )}}
					<p class='ipsType_reset ipsType_light'>
						<strong>{lang="cc"}:</strong> {expression="implode(', ', $elements['']['cc']->value )"}
					</p>
				{{endif}}
				{{if \count( $elements['']['bcc']->value )}}
					<p class='ipsType_reset ipsType_light'>
						<strong>{lang="bcc"}:</strong> {expression="implode(', ', $elements['']['bcc']->value )"}
					</p>
				{{endif}}
			</div>
			<ul class='ipsForm ipsForm_horizontal ipsJS_hide' data-role='sendToForm'>
				{{if $elements['']['to']}}
					{$elements['']['to']->rowHtml($form)|raw}
				{{endif}}
				{{if $elements['']['cc']}}
					{$elements['']['cc']->rowHtml($form)|raw}
				{{endif}}
				{{if $elements['']['bcc']}}
					{$elements['']['bcc']->rowHtml($form)|raw}
				{{endif}}
			</ul>
		</div>

		<div>
			{{if $elements['']['message']}}
				<div class='cNexusSupportForm_message'>
					{$elements['']['message']->html()|raw}
				</div>
			{{endif}}
		</div>
		
		<div class='ipsClearfix ipsPadding_top ipsType_right ipsJS_hide' data-ipsEditor-toolList>
			<ul class='ipsList_inline ipsPos_left ipsType_left cNexusSupportForm_controls'>
				{{if isset( $elements['']['status'] )}}
					<li>
						<h3 class='ipsType_minorHeading'>{lang="status"}</h3>
						{$elements['']['status']->html()|raw}
					</li>
				{{endif}}
				{{if isset( $elements['']['department'] )}}
					<li>
						<h3 class='ipsType_minorHeading'>{lang="department"}</h3>
						{$elements['']['department']->html()|raw}
					</li>
				{{endif}}
				{{if isset( $elements['']['assign_to'] )}}
					<li>
						<h3 class='ipsType_minorHeading'>{lang="assign_to"}</h3>
						{$elements['']['assign_to']->html()|raw}
					</li>
				{{endif}}
			</ul>
			{{$next = $request->nextPrevious();}}
			{{$defaultAction = \IPS\nexus\modules\admin\support\request::defaultReplyAction();}}
			<ul class='ipsButton_split ipsType_noBreak ipsPos_right cNexusSupportForm_buttons'>
				{{if $defaultAction == 'stay'}}
					<li><button type='submit' class='ipsButton ipsButton_primary ipsButton_large' data-role='primarySubmit'>{lang="reply_and_stay"}</button></li>
					<li>
						<a href='#' class='ipsButton ipsButton_primary ipsButton_large ipsButton_narrow' id='elSupportReplyForm_more' data-ipsMenu data-ipsMenu-appendTo='#elSupportReplyForm'><i class='fa fa-caret-down'></i></a>
						<ul id='elSupportReplyForm_more_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='next'>{lang="reply_and_go_to_next"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='first'>{lang="reply_and_go_to_first"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='list'>{lang="reply_and_go_to_list"}</button></li>
						</ul>
					</li>
				{{elseif $defaultAction == 'list'}}
					<li><button type='submit' class='ipsButton ipsButton_primary ipsButton_large' data-role='primarySubmit' name='goto' value='list'>{lang="reply_and_go_to_list"}</button></li>
					<li>
						<a href='#' class='ipsButton ipsButton_primary ipsButton_large ipsButton_narrow' id='elSupportReplyForm_more' data-ipsMenu data-ipsMenu-appendTo='#elSupportReplyForm'><i class='fa fa-caret-down'></i></a>
						<ul id='elSupportReplyForm_more_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline'>{lang="reply_and_stay"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='next'>{lang="reply_and_go_to_next"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='first'>{lang="reply_and_go_to_first"}</button></li>
						</ul>
					</li>
				{{elseif $defaultAction == 'next'}}
					<li><button type='submit' class='ipsButton ipsButton_primary ipsButton_large' data-role='primarySubmit' name='goto' value='next'>{lang="reply_and_go_to_next"}</button></li>
					<li>
						<a href='#' class='ipsButton ipsButton_primary ipsButton_large ipsButton_narrow' id='elSupportReplyForm_more' data-ipsMenu data-ipsMenu-appendTo='#elSupportReplyForm'><i class='fa fa-caret-down'></i></a>
						<ul id='elSupportReplyForm_more_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='first'>{lang="reply_and_go_to_first"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline'>{lang="reply_and_stay"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='list'>{lang="reply_and_go_to_list"}</button></li>
						</ul>
					</li>
				{{else}}
					<li><button type='submit' class='ipsButton ipsButton_primary ipsButton_large' data-role='primarySubmit' name='goto' value='first'>{lang="reply_and_go_to_first"}</button></li>
					<li>
						<a href='#' class='ipsButton ipsButton_primary ipsButton_large ipsButton_narrow' id='elSupportReplyForm_more' data-ipsMenu data-ipsMenu-appendTo='#elSupportReplyForm'><i class='fa fa-caret-down'></i></a>
						<ul id='elSupportReplyForm_more_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline'>{lang="reply_and_stay"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='next'>{lang="reply_and_go_to_next"}</button></li>
							<li class='ipsMenu_item'><button type='submit' class='ipsButton ipsButton_link ipsButton_fullWidth ipsMenu_itemInline' name='goto' value='list'>{lang="reply_and_go_to_list"}</button></li>
						</ul>
					</li>
				{{endif}}
			</ul>
		</div>
	</div>
</form>