<ips:template parameters="$users"/>
<div class='ipsGrid ipsGrid_collapsePhone'>
	{{foreach $users as $user }}
	<div class='ipsGrid_span4 ipsBox ipsSpacer_bottom' data-role='validatingRow'>
		<div class='ipsClearfix'>
			<ul class='ipsButton_split ipsPos_right ipsPad ipsPad_half'>
				<li><a
					href='{url="app=core&module=members&controller=privacy&do=approveDeletion&id={$user->_privacy_id}" csrf="true"}'
					data-action='approve' class='ipsButton ipsButton_verySmall ipsButton_positive' title='{lang='approve'}' data-ipsTooltip><i class='fa fa-check'></i></a></li>
				<li><a
					href='{url="app=core&module=members&controller=privacy&do=rejectDeletion&id={$user->_privacy_id}" csrf="true"}'
					data-action='reject' class='ipsButton ipsButton_verySmall ipsButton_negative' title='{lang='reject'}'
					data-ipsTooltip><i class='fa fa-times'></i></a></li>
			</ul>
			<div class='ipsDataItem_main ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
				{template="userPhoto" app="core" group="global" params="$user, 'mini'" }
				<div>
					<h4 class='ipsType_reset ipsType_large'><strong><a href='{$user->acpUrl()}' data-role='userName'>{$user->name}</a></strong>
						<span class='ipsType_light ipsType_unbold ipsType_small'>({$user->email})</span></h4>
					<ul class='ipsList_reset ipsType_medium'>
						<li><strong>{lang='ip_address'}</strong> {$user->ip_address}</li>
						<li><strong>{lang='block_awaiting_registered'}</strong> {datetime="$user->joined"}</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	{{endforeach}}
</div>
