<ips:template parameters="$table" />
{$table|raw}
<div class="ipsSpacer_top ipsSpacer_double">
	<a href="{url="app=core&module=support&controller=errorLogs"}" class="ipsButton ipsButton_primary ipsButton_verySmall">{lang="view_all"}</a>
	{{if member.hasAcpRestriction( 'core', 'support', 'diagnostic_log_settings' )}}
		&nbsp;
		<a href="{url="app=core&module=support&controller=errorLogs&do=settings"}" class="ipsButton ipsButton_light ipsButton_verySmall" data-ipsDialog data-ipsDialog-title="{lang="settings"}">{lang="settings"}</a>
	{{endif}}
</div>
