<ips:template parameters="$notifications" />

<div data-controller="core.global.core.notificationList" class="cNotificationList">
	{{if isset( request.highlightedId ) and array_key_exists( request.highlightedId, $notifications )}}
		{template="indexBlock" group="notifications" params="$notifications[ \IPS\Request::i()->highlightedId ], TRUE"}
	{{endif}}
	
	{{foreach $notifications as $id => $notification}}
		{{if !isset( request.highlightedId ) or $id != request.highlightedId}}
			{template="indexBlock" group="notifications" params="$notification"}
		{{endif}}
	{{endforeach}}
	<div class="ipsPad ipsType_light ipsType_center ipsType_normal {{if \count( $notifications )}}ipsHide{{endif}}" data-role="empty">{lang="no_results_notifications"}</div>
</div>
