<ips:template parameters="$notification, $spacer=FALSE" />
<div data-role="notificationBlock">
	<div class="ipsBox cNotification cNotification_{$notification->style()} ipsSpacer_bottom">
		{{$dismissible = $notification->dismissible();}}
		{{if $dismissible !== $notification::DISMISSIBLE_NO}}
			<a href="{url="app=core&module=overview&controller=notifications&do=dismiss&id={$notification->id}" csrf="true"}" class="cNotification_dismiss" title="{lang="acp_notification_dismiss_{$dismissible}"}" data-ipsTooltip data-action="dismiss">
				<i class="fa fa-times"></i>
			</a>
		{{endif}}
		<h3 class='ipsBox_titleBar'>
			{$notification->title()|raw}
		</h3>
		<div class='ipsPad'>
			{$notification->body()|raw}
		</div>
	</div>
	{{if $spacer}}
		<hr class="ipsHr ipsSpacer_both ipsSpacer_double">
	{{endif}}
</div>