<ips:template parameters="" />
<div class="ipsType_richText ipsType_normal">
	<p>{lang="orig_cleanup_suggested_1"}</p>
	<p>{lang="orig_cleanup_suggested_2"}</p>
</div>
<div class="ipsSpacer_top">
	<a href="{url="app=core&module=overview&controller=notifications&do=removeOrigTables" csrf="true"}" class="ipsButton ipsButton_primary ipsButton_verySmall" data-confirm>{lang="orig_cleanup_suggested_go"}</a>
</div>