<ips:template parameters="$users, $notification, $more" />
<div class="ipsGrid ipsGrid_collapsePhone">
	{{foreach $users as $user}}
		<div class='ipsGrid_span4 ipsBox ipsSpacer_bottom'>
			<div class='ipsClearfix'>
				<div class='ipsDataItem_main ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
					{template="userPhoto" app="core" group="global" params="$user['member'], 'mini'"}
					<div>
						<h4 class='ipsType_reset ipsType_large'><strong><a href='{$user['member']->acpUrl()}' data-role="userName">{$user['member']->name}</a></strong> &nbsp;&nbsp;<span class='ipsType_light ipsType_unbold ipsType_normal'>({$user['member']->email})</span></h4>
						<p class="ipsType_reset ipsType_small">{$user['blurb']}</p>
					</div>
				</div>
			</div>
		</div>
	{{endforeach}}
	{{if $more > 1}}
		<div class='ipsGrid_span4 ipsSpacer_bottom ipsType_center'>
			<div class='ipsClearfix ipsSpacer_top ipsSpacer_double'>
				<h4 class='ipsType_reset ipsType_large'><strong><a href='{url="app=core&module=members&controller=members&filter=members_filter_spam"}'>{lang="acp_notification_NewRegComplete_more" pluralize="$more"}</a></strong></h4>
			</div>
		</div>
	{{endif}}
</div>
<div class="ipsType_light">
	<span class="ipsType_small"><i class="fa fa-info-circle"></i> {lang="acp_notification_Spammer_desc" sprintf="$notification->id"}</span>
</div>