<ips:template parameters="$file, $reviews, $authorized, $installed, $updateAvailable, $licenseValid=FALSE" />

<section>
    <div class='ipsSpacer_bottom'>
        <div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
            <div class='ipsCarousel_inner'>
                <ul class='cFileScreenshotCarousel ipsClearfix' data-role="carouselItems">
                    {{foreach $file['screenshotsThumbnails'] as $k => $f}}
                    <li class='ipsCarousel_item ipsBox ipsPad_half cFileScreenshot' data-ipsLazyLoad>
                        <span data-background-src='{backgroundimage="$f['url']"}' class="ipsThumb ipsThumb_medium ipsThumb_bg ipsCursor_pointer" data-ipsLightbox data-ipsLightbox-group="download_{$file['id']}" data-fullURL="{$file['screenshots'][ $k ]['url']}">
                            <img src='{expression="\IPS\Text\Parser::blankImage()"}' data-src="{$f['url']}" alt="">
                        </span>
                    </li>
                    {{endforeach}}
                </ul>
            </div>
            <span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
            <span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
            <a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
            <a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
        </div>
    </div>
</section>

<div class='ipsColumns ipsColumns_collapseTablet cFileView' data-controller="core.admin.marketplace.launcher" data-disclaimer-location="{{if isset( $file['disclaimerLocation'] )}}{$file['disclaimerLocation']}{{endif}}" data-category-type="{$file['category']['resourceType']}">
	<div class='ipsColumn ipsColumn_fluid'>

        {{if !empty( $file['supportTab'] )}}
        <div class='ipsTabs ipsTabs_small ipsTabs_stretch ipsClearfix' id='elMpTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elMpTabs_content'>
            <ul role="tablist" class='ipsList_reset'>
                <li>
                    <a href='#' id='elMpTabDescription' class='ipsTabs_item ipsTabs_activeItem' data-role="descriptionTab" role="tab" aria-selected='true'>{lang="marketplace_tab_description"}</a>
                </li>
                <li>
                    <a href='#' id='elMpTabSupport' class='ipsTabs_item' data-role="supportTab" role="tab" aria-selected='false'>{lang="marketplace_tab_support"}</a>
                </li>
            </ul>
        </div>

        <div id="elMpTabs_content" class="ipsBox ipsTabs_panels ipsClearfix ipsPad ipsType_richText cFileColorReset">
            <div id="ipsTabs_elMpTabs_elMpTabDescription_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false" data-role="descriptionTab">
                {expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $file['description'] )" raw="true"}

                {{if !empty( $file['extraResources'] )}}
                <h3 class="ipsSpacer_top ipsSpacer_double">{lang="marketplace_extra_resource"}</h3>
                {$file['extraResources']|raw}
                {{endif}}
            </div>
            <div id="ipsTabs_elMpTabs_elMpTabSupport_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false" data-role="supportTab">
                {expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $file['supportTab'] ?? '' )" raw="true"}
            </div>
        </div>
        {{else}}
        <div class="ipsBox ipsPad ipsType_richText cFileColorReset">
            {expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $file['description'] )" raw="true"}
        </div>
        {{endif}}

        {{if $file['reviews']}}
        <h2>{lang="marketplace_reviews"}</h2>
        <div class="ipsBox ipsPadding:half">
			{{foreach $reviews['results'] as $review}}
			<div class="cFileView_review">
				<div class='ipsFlex ipsFlex-ai:center cFileView_reviewHeader'>
					<img src="{$review['author']['photoUrl']}" class="ipsThumb_tiny" width="50" height="50" alt="">
					<div class="ipsFlex-flex:11 ipsPadding_left:half">
						<a href="{$review['author']['profileUrl']}" rel="external noopener" target="_blank">{$review['author']['name']}</a>
                        {{$date = new \IPS\DateTime( $review['date'] ); }}
						<br>{{if $date->getTimestamp()}}{expression="$date->html()" raw="true"}{{else}}{lang="unknown_date"}{{endif}}
					</div>

					<span>{template="rating" app="core" params="'medium', $review['rating'], 5" group="global" location="front"}</span>
				</div>
				<div class="ipsType_richText ipsContained">
				{expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $review['content'] )" raw="true"}
					{{if $review['authorResponse']}}
						<div class='ipsReviewResponse ipsPadding ipsSpacer_bottom ipsAreaBackground_light ipsClearfix'>
							<h4 class='ipsType_sectionHead ipsType_medium ipsType_bold ipsSpacer_bottom ipsType_light'>{lang="review_response_title"}</h4>
							<div data-role="reviewResponse" class="ipsType_richText ipsType_normal ipsContained ipsType_light">
                                {expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $review['authorResponse'] )" raw="true"}
							</div>
						</div>
					{{endif}}
				</div>
			</div>
			{{endforeach}}

			{{if $file['canReview']}}
			<hr class="ipsHr">
			<a href="{$file['url']}#replies" target="_blank" rel="noopener noreferrer" class="ipsButton ipsButton_positive">{lang="marketplace_add_review"}</a>
			{{endif}}
        </div>
		{{if $reviews['totalPages'] > 1}}
		<div class="ipsSpacer_top">
			{template="pagination" group="global" app="core" location="global" params="\IPS\Http\Url::internal('app=core&module=marketplace&controller=marketplace&do=viewFile&id=' . $file['id'] ), $reviews['totalPages'], $reviews['page'], $reviews['perPage'], TRUE, 'page'"}
		</div>
		{{endif}}
		{{endif}}
	</div>

	<div class='ipsColumn ipsColumn_veryWide'>
		<div class="ipsBox ipsPad ipsSpacer_bottom">

			{{if isset( $file['prices']['USD'] )}}
			<div class="ipsSpacer_bottom ipsType_center">
				<span class="ipsType_veryLarge">&dollar;{number="$file['prices']['USD']" decimals="2"}</span>

				{{if isset( $file['renewalTermString'] )}}
				<div class="ipsType_large">{$file['renewalTermString']}</div>
				{{endif}}
            </div>
			{{endif}}

			{{if $authorized AND $licenseValid}}
            <div class="ipsResponsive_hidePhone">
				{{if $installed}}
					{{if !$updateAvailable}}
						<span class="ipsType_light ipsType_blendLinks ipsResponsive_hidePhone ipsResponsive_inline"><i class="fa fa-info-circle"></i> {lang="marketplace_already_installed"}</span>
					{{else}}
						<a href="{url="app=core&module=marketplace&controller=marketplace&do=install&id={$file['id']}" csrf="true"}" class="ipsButton ipsButton_primary ipsButton_fullWidth" data-role="update">{lang="marketplace_update"}</a>
					{{endif}}
				{{else}}
					{{if $file['canDownload']}}
						<a href="{url="app=core&module=marketplace&controller=marketplace&do=install&id={$file['id']}&type=install" csrf="true"}" class="ipsButton ipsButton_primary ipsButton_fullWidth" data-role="install">{lang="marketplace_install"}</a>
					{{endif}}
					{{if $file['canBuy']}}
						{{if !$file['isPurchasable']}}
							<div class="ipsType_light ipsType_blendLinks ipsResponsive_hidePhone ipsSpacer_top"><i class="fa fa-info-circle"></i> {lang="marketplace_purchasing_disabled"}</div>
						{{else}}
						<div data-purchase-url="{url="app=core&module=marketplace&controller=marketplace&do=buyFile&id={$file['id']}" csrf="true"}" data-height="900">
							<button class='ipsButton ipsButton_fullWidth {{if $file['canDownload']}}ipsButton_action ipsSpacer_top{{else}}ipsButton_important{{endif}}' data-action="launchWindow" data-role="purchase">
								<i class='fa fa-shopping-cart'></i> &nbsp;{{if $file['canDownload']}}{lang="marketplace_buy_another"}{{else}}{lang="marketplace_buy_now"}{{endif}}
							</button>
						</div>
						{{endif}}
					{{endif}}
				{{endif}}
			</div>
			<span class="ipsType_light ipsType_blendLinks ipsResponsive_showPhone ipsResponsive_hideTablet ipsResponsive_hideDesktop"><i class="fa fa-info-circle"></i> {lang="marketplace_no_phones"}</span>
            {{elseif $authorized AND !$licenseValid }}
                <span class="ipsType_light ipsType_blendLinks ipsResponsive_hidePhone ipsResponsive_inline"><i class="fa fa-info-circle"></i> {lang="marketplace_inactive_license"}</span>
            {{else}}
				<span class="ipsType_light ipsType_blendLinks ipsResponsive_hidePhone ipsResponsive_inline"><i class="fa fa-info-circle"></i> {lang="marketplace_must_sign_in"}</span>
			{{endif}}
		</div>

        <h2>{lang="marketplace_resource_information"}</h2>
        <div class="ipsBox ipsPad">

            <ul class="ipsDataList ipsDataList_reducedSpacing">

				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="marketplace_file_rating"}</strong></span>
					<span class="ipsDataItem_generic">
						{template="rating" app="core" params="'medium', $file['rating'], 5" group="global" location="front"}
						<span>({number="$file['reviews']" format="short"})</span></span>
				</li>
                {{if $file['isPurchasable']}}
                <li class="ipsDataItem">
                    <span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="marketplace_file_purchases"}</strong></span>
                    <span class="ipsDataItem_generic">{number="$file['purchases']"}</span>
                </li>
				{{endif}}

                <li class="ipsDataItem">
                    <span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="marketplace_file_downloads"}</strong></span>
                    <span class="ipsDataItem_generic">{number="$file['downloads']"}</span>
                </li>

                <li class="ipsDataItem">
                    <span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="marketplace_file_submitted"}</strong></span>
                    <span class="ipsDataItem_generic">{expression="(new \IPS\DateTime($file['date']))->html()" raw="true"}</span>
                </li>

                <li class="ipsDataItem">
                    <span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="marketplace_file_updated"}</strong></span>
                    <span class="ipsDataItem_generic">{expression="(new \IPS\DateTime($file['updated']))->html()" raw="true"}</span>
                </li>
			</ul>
        </div>

		{{if $file['changelog']}}
		<h2>{lang="marketplace_changes_version" sprintf="$file['version']"}</h2>
		<div class="ipsBox ipsPad ipsType_richText cFileColorReset cFileChangelog">
			{expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $file['changelog'] )" raw="true"}
			<a href="{url="app=core&module=marketplace&controller=marketplace&do=fileChangelog&id={$file['id']}"}" data-ipsDialog data-ipsDialog-title="{lang="marketplace_previous_changes"}" class="ipsButton ipsButton_alternate ipsButton_fullWidth ipsButton_small">{lang="marketplace_previous_changes"}</a>
		</div>
		{{endif}}
	</div>
</div>

{{if !empty( $file['downloadDisclaimer'] )}}
<div class="ipsHide">
    {template="termsAndConditions" app="core" location="admin" group="marketplace" params="$file, '', $file['downloadDisclaimer'], $file['authorDisclaimer'] ?? '', $file['author']['name']"}
</div>
{{endif}}