<ips:template parameters="$file" />

<a class='ipsBox ipsMargin_bottom:half cFileCard cFileCard_mini ipsFlex'  href="{url="app=core&module=marketplace&controller=marketplace&do=viewFile&id={$file['id']}" csrf="true"}">
	<span class="ipsThumb_bg ipsPosition:relative" data-background-src="{backgroundimage="$file['primaryScreenshotThumb']['url']"}">
        <span class="cFileCard_cost">
            {{if $file['isPaid']}}
                &dollar;{number="$file['prices']['USD']" decimals="2"}
            {{else}}
                {lang="marketplace_free"}
            {{endif}}
        </span>
	</span>
    <div class="ipsFlex-flex:11 ipsPadding:half ipsPosition:relative">
        <h2 class="cFileCard_title ipsTruncate ipsTruncate_line">{$file['title']}</h2>
        <span class="cFileCard_byLine">By {$file['author']['name']}</span>
        <div class="cFileCard_rating ipsPadding:half">
            {template="rating" app="core" params="'medium', $file['rating'], 5" group="global" location="front"} ({number="$file['reviews']" format="short"})
        </div>
    </div>
</a>