<ips:template parameters="$changeLogs=array()" />

<div class="ipsGrid ipsPad" data-ipsGrid>
	{{foreach $changeLogs as $change}}
		<div class="ipsGrid_span6">
			<h2 class="ipsType_large">{lang="marketplace_version_short" sprintf="$change['version']"} - {expression="( new \IPS\DateTime( $change['date'] ) )->relative()"}</h2>
			<div class="ipsType_richText cFileColorReset">
                {expression="\IPS\core\modules\admin\marketplace\marketplace::_parseRawContent( $change['changelog'] ?? '' )" raw="true"}
			</div>
		</div>
	{{endforeach}}
</div>