<ips:template parameters="$category, $compatible=TRUE" />
<div data-controller="core.admin.marketplace.search" data-category="{$category}" data-compatible="{$compatible}" data-search-literal="true">
	<div class="ipsPad ipsAreaBackground">
		<input type="search" class="ipsField_fullWidth" placeholder="{lang="marketplace_onboard_search"}" data-role="searchBox">
	</div>
	<div class="ipsAreaBackground ipsPadding" data-role="results"></div>
</div>