<ips:template parameters="$rows" />
<form action="{url="app=core&module=marketplace&controller=onboard"}" method="post" data-controller="core.admin.marketplace.onboard">
	<table class="ipsTable ipsTable_responsive ipsTable_zebra">
		<thead>
			<tr>
				<th>{lang="marketplace_onboard_installed"}</th>
				<th>{lang="marketplace_onboard_possible"}</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{{foreach $rows as $row}}
				{$row|raw}
			{{endforeach}}
		</tbody>
	</table>
	<div class="ipsAreaBackground ipsClearfix ipsPad ipsType_center">
		<button type="submit" class="ipsButton ipsButton_primary" data-role="continueButton" class="ipsButton_disabled">{lang="continue"}</button>
	</div>
</form>