<ips:template parameters="$data" />

<!DOCTYPE html>
<html>
	<head>
		<title>{lang="print_gift_card"}</title>
		<style type='text/css'>
			body {
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
				font-size: 13px;
				line-height: 18px;
				margin: 0;
				padding: 30px;
				text-align: center;
			}

			#elNexusGiftcard_border {
				position: relative;
				border: 1px dashed #000;
				padding: 20px;
				display: inline-block;
				text-align: left;
				border-radius: 4px;
			}

			#elNexusGiftcard {
				width: 400px;
				border-radius: 10px;
				margin: 0 auto;
				position: relative;
			}

			#elNexusGiftcard_card {
				height: 230px;
				border-radius: 10px;
				position: relative;
			}

			#icon {
				position: absolute;
				display: block;
				background: #fff;
				border-radius: 50px;
				width: 100px;
				height: 100px;
				top: 15px;
				left: 15px;
				font-size: 60px;
				line-height: 100px;
				text-align: center;
				z-index: 5000;
			}

			#title {
				position: absolute;
				top: 30px;
				right: 15px;
				font-size: 20px;
				font-weight: 400;
				color: rgba(255,255,255,0.6);
			}

			#elNexusGiftcard_card h2 {
				position: absolute;
				right: 15px;
				bottom: 80px;
				color: #fff;
				font-weight: 400;
				font-size: 40px;
				margin: 0;
				padding: 0;
			}

			#value {
				position: absolute;
				right: 15px;
				bottom: 30px;
				color: rgba(255,255,255,0.8);
				font-weight: 300;
				font-size: 52px;
			}

			#message {
				margin: 10px 0;
			}

			#scissors_top,
			#scissors_bottom {
				position: absolute;
				font-size: 22px;
				left: 50%;
			}

			#scissors_top {
				top: -13px;
			}

			#scissors_bottom {
				bottom: -13px;
				transform: rotate(180deg);
			}

			#elNexusGiftcard_personalize {
				font-size: 14px;
				padding: 15px;
				color: #333;
			}

			#elNexusGiftcard_personalize hr {
				border: 0;
				border-top: 1px solid #999999;
				height: 1px;
				margin-top: 15px;
				margin-bottom: 15px;
			}

			#redeem, #code {
				font-size: 12px;
				text-align: center;
			}

				#code strong {
					font-size: 16px;
				}

			#redeem {
				color: #626262;
				margin-top: 5px;
			}

			/*!
			 *  Font Awesome 4.2.0 by @davegandy - http://fontawesome.io - @fontawesome
			 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
			 */
			/* FONT PATH
			 * -------------------------- */
			@font-face {
			  font-family: 'FontAwesome';
			  src: url('{url="applications/core/interface/font/fontawesome-webfont.eot?v=4.2.0" base="none" noprotocol="true"}');
			  src: url('{url="applications/core/interface/font/fontawesome-webfont.eot?#iefix&v=4.2.0" base="none" noprotocol="true"}') format('embedded-opentype'), url('{url="applications/core/interface/font/fontawesome-webfont.woff?v=4.2.0" base="none" noprotocol="true"}') format('woff'), url('{url="applications/core/interface/font/fontawesome-webfont.ttf?v=4.2.0" base="none" noprotocol="true"}') format('truetype'), url('{url="applications/core/interface/font/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular" base="none" noprotocol="true"}') format('svg');
			  font-weight: normal;
			  font-style: normal;
			}

			.fa {
			  display: inline-block;
			  font: normal normal normal 14px/1 FontAwesome;
			  font-size: inherit;
			  text-rendering: auto;
			  -webkit-font-smoothing: antialiased;
			  -moz-osx-font-smoothing: grayscale;
			}

			.fa-scissors:before {
			  content: "\\f0c4";
			}

			.fa-gift:before {
			  content: "\\f06b";
			}
		</style>
	</head>
	<body>
		<div id='elNexusGiftcard_border'>
			<i class='fa fa-scissors' id='scissors_top'></i>
			<i class='fa fa-scissors' id='scissors_bottom'></i>
			<div id='elNexusGiftcard'>
				<div id='elNexusGiftcard_card' style='background-color: {$data['color']}'>
					<span id='icon'><i class='fa fa-gift'></i></span>
					<h2>{lang="gift_voucher"}</h2>
					<strong id='title'>{setting="board_name"}</strong>
					<strong id='value'>{money="$data['amount']" currency="$data['currency']"}</strong>
				</div>
				<div id='elNexusGiftcard_personalize'>
					{{if $data['recipient_name']}}
						<div>
							<strong>{lang="to"} {$data['recipient_name']}</strong>,
						</div>
					{{endif}}
					{{if $data['message']}}
						<div id='message'>
							{expression="nl2br( htmlspecialchars( $data['message'], ENT_DISALLOWED, 'UTF-8', FALSE ) )" raw="true"}
						</div>
					{{endif}}
					{{if $data['sender']}}
						<div><strong>{lang="from"} {$data['sender']}</strong></div>
					{{endif}}
					<hr>
					<div id='code'>
						{lang="redemption_code"}<br>
						<strong>{$data['code']}</strong>
					</div>
					<div id='redeem'>
						{lang="to_redeem_visit"}<br>
						{url="app=nexus&module=store&controller=gifts&do=redeem" seoTemplate="store_giftvouchers_redeem"}
					</div>
				</div>
			</div>
		</div>
	</body>
</html>