<ips:template parameters="$package, $customFieldsForm, $supportUrl, $reactivateUrl, $upgradeDowngradeUrl, $upgradeDowngradeLang, $associatedFiles, $last5AssociatedSupportRequests" />

<hr class='ipsHr ipsSpacer_top ipsSpacer_double'>
{{if $reactivateUrl or $upgradeDowngradeUrl or \IPS\nexus\Package\Item::load( $package->id )->canReview()}}
	<ul class='ipsList_inline'>
		{{if $reactivateUrl}}
			<li><a href="{$reactivateUrl}" class=''>{lang="reactivate_package"}</a></li>
		{{endif}}
		{{if $upgradeDowngradeUrl}}
			<li><a href="{$upgradeDowngradeUrl}" class=''>{lang="$upgradeDowngradeLang"}</a></li>
		{{endif}}
		{{if \IPS\nexus\Package\Item::load( $package->id )->canReview()}}
			<li><a href="{$package->url()}" class=''>{lang="write_package_review"}</a></li>
		{{endif}}
	</ul>
	<hr class='ipsHr ipsSpacer_bottom ipsSpacer_double'>
{{endif}}

{{if member.canAccessModule( \IPS\Application\Module::get( 'nexus', 'support' ) )}}
	<div class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="recent_support_requests"}</h2>
		{{if \count( $last5AssociatedSupportRequests )}}
			<ul class='ipsDataList'>
				{{foreach $last5AssociatedSupportRequests as $row}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main'>
							<h4 class='ipsDataItem_title'>
								{{if $row->unread()}}<span class='ipsItemStatus'><i class="fa fa-circle"></i></span>{{endif}} <a href='{$row->url()}'>{{if $row->mapped('title')}}{$row->mapped('title')}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}</a> <span class='ipsType_light ipsType_unbold ipsType_normal'>#{$row->id}</span>
							</h4>
							<div class='ipsDataItem_meta ipsType_light'>
								<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
									<li>
										{template="status" group="support" location="admin" params="$row->status"}
									</li>
									<li>
										{lang="in"} <strong>{template="department" group="support" location="admin" params="$row->department"}</strong>
									</li>
									<li>
										<i class='fa fa-clock-o'></i>
										{{if $row->replies == 1}}
											{{if $row->last_reply_by === \IPS\Member::loggedIn()->member_id}}
												{lang="support_you_created" sprintf="\IPS\DateTime::ts( $row->last_reply )->relative()"}
											{{else}}
												{lang="support_x_created" sprintf="\IPS\Member::load( $row->last_reply_by )->name, \IPS\DateTime::ts( $row->last_reply )->relative()"}
											{{endif}}
										{{else}}
											{{if $row->last_reply_by === \IPS\Member::loggedIn()->member_id}}
												{lang="support_you_replied" sprintf="\IPS\DateTime::ts( $row->last_reply )->relative()"}
											{{else}}
												{lang="support_x_replied" sprintf="\IPS\Member::load( $row->last_reply_by )->name, \IPS\DateTime::ts( $row->last_reply )->relative()"}
											{{endif}}
										{{endif}}
									</li>
								</ul>
							</div>
							<div class='ipsType_break ipsContained ipsType_medium ipsSpacer_top ipsSpacer_half' data-ipsTruncate data-ipsTruncate-size='2 lines' data-ipsTruncate-type='remove'>
								{$row->truncated()|raw}
							</div>
						</div>
					</li>
				{{endforeach}}
			</ul>
		{{else}}
			<p class='ipsType_reset ipsType_normal ipsPad ipsType_center'>
				{lang="no_recent_support_requests"}
			</p>
		{{endif}}
		{{if $supportUrl}}
			<p class='ipsType_reset ipsPad ipsAreaBackground_light ipsType_center'><a href="{$supportUrl}" class='ipsButton ipsButton_primary ipsButton_verySmall'>{lang="commerce_get_support"}</a></p>
		{{endif}}
	</div>
{{endif}}

<br><br>
{{if \count( $associatedFiles )}}
	<h2 class='ipsType_sectionHead ipsSpacer_bottom ipsSpacer_half'>{lang="package_downloads"}</h2>
	<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
		<div class='ipsCarousel_inner'>
			<div class='cDownloadsCarousel' data-role="carouselItems">
				{{foreach $associatedFiles as $idx => $file}}
					{template="indexBlock" app="downloads" group="browse" params="$file"}
				{{endforeach}}
			</div>
		</div>
		<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
		<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
		<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
		<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
	</div>
{{endif}}

{$customFieldsForm|raw}
