<ips:template parameters="$table, $headers, $rows" />
{{foreach $rows as $row}}
	<li class="ipsDataItem sm:ipsPadding {{if ! $row->enabled}}ipsFaded ipsFaded_withHover{{endif}} ipsDataItem_unread {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if !$row->enabled}}ipsModerated{{endif}} cModCPAlertRow">
		<div class='ipsDataItem_icon ipsPos_top ipsResponsive_hidePhone'>
			{template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
		</div>
		<div class='ipsDataItem_main'>
			<h4 class='ipsDataItem_title ipsContained_container'>
				<span class='ipsType_break ipsContained'>
                    {$row->mapped('title')}
                </span>
                <span class="ipsPadding_horizontal:half">
                {{if $row->anonymous}}
                   <span class='ipsBadge ipsBadge_new ipsBadge_icon ipsBadge_medium'><i class="fa fa-eye" data-ipstooltip="" _title="{lang="alert_anon"}"></i></span>
                {{else}}
                    {{if $row->reply == 1}}
                        <span class='ipsBadge ipsBadge_new ipsBadge_icon ipsBadge_medium'><i class="fa fa-envelope-o" data-ipstooltip="" _title="{lang="alert_can_reply"}"></i></span>
                    {{endif}}
                    {{if $row->reply == 2}}
                         <span class='ipsBadge ipsBadge_new ipsBadge_icon ipsBadge_medium'><i class="fa fa-envelope" data-ipstooltip="" _title="{lang="alert_must_reply"}"></i></span>
                    {{endif}}
                {{endif}}
                {{if $row->recipient_type == 'user'}}
                   <span class='ipsBadge ipsBadge_new ipsBadge_icon ipsBadge_medium'><i class="fa fa-user" data-ipstooltip="" _title="{lang="alert_tooltip_member" sprintf="$row->memberName()"}"></i></span>
                {{else}}
                    {{$names = \IPS\Member::loggedIn()->language()->formatList( $row->groupNames() );}}
                    <span class='ipsBadge ipsBadge_new ipsBadge_icon ipsBadge_medium'><i class="fa fa-users" data-ipstooltip="" _title="{lang="alert_tooltip_groups" htmlsprintf="$names"}"></i></span>
                {{endif}}
                {{if $row->enabled}}
					<span class='ipsBadge ipsBadge_new'>{lang="active"}</span>
				{{else}}
					<span class='ipsBadge ipsBadge_style5'>{lang="inactive"}</span>
				{{endif}}
                {{if ! $row->viewed}}
                    <span class='ipsBadge ipsBadge_style3 ipsBadge_medium'>{lang="alert_not_viewed"}</span>
                {{else}}
                    <span class='ipsBadge ipsBadge_positive ipsBadge_medium'>{lang="alert_viewed_times" sprintf="$row->viewed" pluralize="$row->viewed"}</span>
                {{endif}}
                {{if $row->author()->member_id === member.member_id AND $row->reply > 0 and ( $count = $row->membersRepliedCount() )}}
                    <span class='ipsBadge ipsBadge_positive ipsBadge_medium'><a href="{url="app=core&module=system&controller=alerts&do=viewReplies&id={$row->id}" seoTemplate="alert" csrf="true"}">{lang="alert_users_have_replied" sprintf="$count" pluralize="$count"}</a></span>
                {{endif}}
                </span>
			</h4>
			<p class='ipsType_reset ipsType_light'>{lang="byline" sprintf="$row->author()->name"}{datetime="$row->start" dateonly="true"}{{if $row->end}} - {datetime="$row->end" dateonly="true"}{{endif}}</p>
			<div class='ipsDataItem_meta ipsType_break ipsMargin_top:half'>
				{{$truncateAttributes = array('data-ipsTruncate', 'data-ipsTruncate-size="4 lines"', 'data-ipsTruncate-type="hide"');}}
				{template="richText" group="global" app="core" location="global" params="$row->content(), array('ipsType_medium'), array(), $truncateAttributes"}
			</div>
		</div>
		{{if $table->canModerate()}}
			<div class='ipsDataItem_modCheck ipsType_noBreak ipsPos_center'>
				<a href='#elAlert{$row->id}_menu' id='elAlert{$row->id}' class='ipsType_large ipsPos_middle ipsType_blendLinks ipsPadding_horizontal:half' data-ipsMenu>
					<i class='fa fa-cog'></i> <i class='fa fa-caret-down'></i>
				</a>
				<input type='checkbox' data-role='moderation' name="moderate[{$row->id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{$row->tableStates()}'>

				<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide' id='elAlert{$row->id}_menu'>
                    <li class='ipsMenu_item'>
                        <a href='{$row->url('status')->csrf()}' title='{lang="announce_toggle"}'>
                        <span data-role="ipsMenu_selectedText">{{if $row->enabled}}{lang="announce_mark_inactive"}{{else}}{lang="announce_mark_active"}{{endif}}</span>
                        </a>
                    </li>
					<li class='ipsMenu_item'>
						<a href='{$row->url('create')}' title='{lang="edit_alert"}' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-destructOnClose='true' data-ipsDialog-title='{lang="edit_alert"}'>
							<span data-role="ipsMenu_selectedText">{lang="edit"}</span>
						</a>
					</li>
                    <li class='ipsMenu_item'>
                        <a href='{$row->url('changeAuthor')}' title='{lang="edit_alert_author"}' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-destructOnClose='true' data-ipsDialog-title='{lang="edit_alert_author"}'>
                        <span data-role="ipsMenu_selectedText">{lang="alert_change_author"}</span>
                        </a>
                    </li>
					<li class='ipsMenu_sep'></li>
					<li class='ipsMenu_item'>
						<a href='{$row->url('delete')->csrf()}' data-confirm title='{lang="alert_delete"}'>
							{lang="delete"}
						</a>
					</li>
				</ul>
			</div>
		{{endif}}
	</li>
{{endforeach}}