<ips:template parameters="$table" />
<div class=''>
	<a href='{url="app=core&module=modcp&tab=alerts&action=create" seoTemplate="modcp_alerts"}' id='elAdd_Alert' class='ipsButton ipsButton_primary ipsPos_right' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-title='{lang="add_alert"}'><i class='fa fa-add'></i>&nbsp;<span class='ipsResponsive_inline'>{lang="add_alert"}</span></a>
	<br><br><br>
	<div class='ipsClear ipsBox'>
		{$table|raw}
	</div>
</div>