<ips:template parameters="$class, $report, $container=NULL" />
<div class="ipsMargin_top:half">
<i class='fa fa-{$class::$icon}'></i>
<a href="{$report->url()->setQueryString( array( 'action' => 'find' ) )}">
    {{if $container === NULL}}
	    {lang="$class::$title"}
    {{else}}
        {lang="icon_blurb_in_containers" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $class::$title ), $container->_title"}
    {{endif}}
</a>
{{if $report->status == \IPS\core\Reports\Report::STATUS_REJECTED}}
    <span class="ipsBadge ipsBadge_negative">{lang="report_status_{$report->status}"}</span>
{{elseif $report->status == \IPS\core\Reports\Report::STATUS_OPEN}}
    <span class="ipsBadge ipsBadge_recommended">{lang="report_status_{$report->status}"}</span>
{{else}}
    <span class="ipsBadge ipsBadge_positive">{lang="report_status_{$report->status}"}</span>
{{endif}}
{{foreach $report->getReportedTypes() as $name}}
<span class="ipsBadge ipsBadge_style1">{$name}</span>
{{endforeach}}
</div>