<?php

$lang = array(
	'x_daily' => '{# [1:day][?:days]}',
	'x_weekly' => '{# [1:week][?:weeks]}',
	'x_monthly' => '{# [1:month][?:months]}',
	'x_yearly' => '{# [1:year][?:years]}',
	'every_x' => 'Every {{period}}',
	'x_times' => '{# [1:time][?:times]}',
	'until' => 'until {{date}}',
	'with_end' => '{{interval}}, {{endAfter}}',
	'MO' => 'Monday',
	'TU' => 'Tuesday',
	'WE' => 'Wednesday',
	'TH' => 'Thursday',
	'FR' => 'Friday',
	'SA' => 'Saturday',
	'SU' => 'Sunday',
	'one_day' => 'on {{first}}',
	'multiple_day' => 'on {{days}} and {{last}}',
	'week_string' => '{{week}} {{days}}',
	'doesnt_repeat' => "Doesn't repeat",
	'single_not_allday' => "On <strong>{{startDate}}</strong>, from <strong>{{startTime}}</strong> to <strong>{{endTime}}</strong>",
	'single_not_allday_noendtime' => "On <strong>{{startDate}}</strong>, at <strong>{{startTime}}</strong>",
	'single_allday' => "<strong>{{startDate}}</strong> (all day)",
	'not_single_not_allday' => "From <strong>{{startDate}}</strong> at <strong>{{startTime}}</strong> until <strong>{{endDate}}</strong> at <strong>{{endTime}}</strong>",
	'not_single_allday' => "From <strong>{{startDate}}</strong> to <strong>{{endDate}}</strong>",
	'select_time' => "(select time)",
	'event_reminder_removed'				=> "Reminder Removed",
	'event_reminder_added'					=> "Reminder Saved",
	'event_your_current_location'	=> "Your Current Location",
	'event_your_current_location_sorry'	=> "Sorry, we weren't able to get your location. Do you have location services enabled in your browser?",
	'event_finding_location' => "Finding your location...",
);
