<ips:template parameters="$value, $total, $solved, $previousValue=NULL, $previousTotal=NULL, $previousSolved=NULL, $nodes=array()" />
	<div>
		<span class='cStat__number cStat__number--medium' data-number='{$value}' data-ipsTooltip title="{lang="stats_solved_tooltip" sprintf="$solved, $total"}">{$value}%</span>
		{{if isset( $previousValue )}}
			<p class='ipsType_reset cStat__change cStat__change--large {{if $previousValue > $value}}ipsType_negative{{elseif $previousValue < $value}}ipsType_positive{{else}}ipsType_neutral{{endif}}' data-ipsTooltip title="{lang="stats_solved_tooltip_prev" sprintf="$previousSolved, $previousTotal, $previousValue"}">
				{{if $previousValue > $value}}
					-{expression="$previousValue - $value"}%
				{{elseif $previousValue < $value}}
					{{if $previousValue}}+{expression="$value - $previousValue"}%{{else}}+ ∞{{endif}}
				{{else}}
					&mdash;
				{{endif}}
			</p>
		{{endif}}

		{{if \count( $nodes )}}
			<hr class='ipsHr'>
			<div class='ipsFlex'>
				<div class='cStatTile__split'>
					<p class='ipsType_reset cStat__change cStat__change--small'>
						{lang="overview_stats_curfilter" list="$nodes"}
					</p>
				</div>
			</div>
		{{endif}}
	</div>