<ips:template parameters="$form, $solvedCount, $recommendedCount, $startTime, $endTime" />
<div class=''>
	<div class='ipsBox'>
		<h1 class='ipsBox_titleBar'>{lang="stats_posts_by_type"}</h1>
		<div>
			{$form|raw}
		</div>
	</div>
</div>


<div class='ipsSpacer_top ipsSpacer_double'>
	<table class="ipsTable ipsTable_responsive ipsTable_zebra " data-role="table">
		<thead>
			<tr class="ipsAreaBackground">
				<th>{lang="stats_posts_type_type"}</th>
				<th>{lang="stats_posts_type_count"}</th>
			</tr>
		</thead>
		<tbody>
		<tr class="ipsClearfix">
			<td class="">
				{lang="stats_posts_type_solved"}
			</td>
			<td><a href='{url="app=forums&module=stats&controller=posts&do=showSolvedPosts&startTime={$startTime}&endTime={$endTime}"}' data-ipsDialog data-ipsDialog-title='{lang="stats_posts_type_solved"}' title="{lang="stats_posts_show_posts"}" data-ipsTooltip>{$solvedCount}</a></td>
		</tr>
		<tr>
			<td class=" ipsTable_wrap ipsTable_primary ">
				{lang="stats_posts_type_recommended"}
			</td>
			<td><a href='{url="app=forums&module=stats&controller=posts&do=showRecommendedPosts&startTime={$startTime}&endTime={$endTime}"}' data-ipsDialog data-ipsDialog-title='{lang="stats_posts_type_recommended"}' title="{lang="stats_posts_show_posts"}" data-ipsTooltip>{$recommendedCount}</a></td>
		</tr>
	</tbody>
	</table>
</div>
