<ips:template parameters="$value, $previousValue=NULL, $nodes=array()" />
	<div>
		<span class='cStat__number cStat__number--medium' data-number='{$value}'>{expression="\IPS\DateTime::roundedDiffFromSeconds( $value )"}</span>
		{{if isset( $previousValue )}}
			<p class='ipsType_reset cStat__change cStat__change--large {{if $previousValue < $value}}ipsType_negative{{elseif $previousValue > $value}}ipsType_positive{{else}}ipsType_neutral{{endif}}' data-ipsTooltip title="{lang="previous_period"} {expression="\IPS\DateTime::roundedDiffFromSeconds( $previousValue )"}">
				{{if $previousValue > $value}}
					-{expression="round( 100 - ( $value / $previousValue * 100 ), 2 )"}%
				{{elseif $previousValue < $value}}
					{{if $previousValue}}+{expression="round( ( ( $value - $previousValue ) / $previousValue ) * 100, 2 )"}%{{else}}+ ∞{{endif}}
				{{else}}
					&mdash;
				{{endif}}
			</p>
		{{endif}}

		{{if \count( $nodes )}}
			<hr class='ipsHr'>
			<div class='ipsFlex'>
				<div class='cStatTile__split'>
					<p class='ipsType_reset cStat__change cStat__change--small'>
						{lang="overview_stats_curfilter" list="$nodes"}
					</p>
				</div>
			</div>
		{{endif}}
	</div>