<ips:template parameters="$currentCategory=NULL" />
	{{$categories = $currentCategory ? $currentCategory->children( 'view', NULL, FALSE ) : \IPS\blog\Category::roots();}}
	{{if !\IPS\blog\Category::theOnlyNode( array(), TRUE, FALSE ) and \count( $categories )}}
	<div id='elBlogCategoriesBlock' class='ipsWidget ipsWidget_vertical ipsBox'>
		<h3 class='ipsType_sectionTitle ipsType_reset'>{{if $currentCategory}}{lang="subcategories"}{{else}}{lang="categories"}{{endif}}</h3>
		<div class='ipsPad_half'>
			<div class='ipsSideMenu'>
				<ul class='ipsSideMenu_list'>
					{{foreach $categories as $category}}
						<li>
							<a href="{$category->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><span class='ipsBadge ipsBadge_style1 ipsPos_right cBlogCategoryCount'>{number="$category->childrenCount()"}</span><strong class='ipsType_normal'>{$category->_title}</strong></a>
						</li>
					{{endforeach}}
				</ul>
			</div>
		</div>
	</div>
	{{endif}}
