<ips:template parameters="$featured" />

<div class='ipsBox ipsResponsive_pull ipsSpacer_bottom'>
	<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="featured_entries"}</h2>
	<div class='ipsClearfix'>
		<div class="cFeaturedTopics ipsCarousel ipsClearfix" data-ipsCarousel data-ipsCarousel-slideshow data-ipsCarousel-fullSizeItems data-ipsCarousel-shadows='false'>
			<div class='ipsCarousel_inner'>
				<ul class='cTopicCarousel ipsClearfix ipsList_reset' data-role='carouselItems'>
					{{foreach $featured as $entry}}
						<li class='ipsCarousel_item ipsAreaBackground_reset ipsClearfix'>
							<div class='ipsPadding ipsPhotoPanel ipsPhotoPanel_small ipsClearfix'>
								{template="userPhoto" group="global" app="core" params="$entry->author(), 'small'"}
								<div>
									<h3 class='ipsType_sectionHead'>
										<span class='ipsType_break ipsContained'>
											<a href='{$entry->url( "getPrefComment" )}'>
												{{if $entry->unread()}}
													<span class='ipsItemStatus ' data-ipsTooltip title='{{if !$entry->unread()}}{lang="no_new_posts"}{{else}}{lang="new_posts"}{{endif}}'><i class="fa fa-circle"></i></span>
												{{endif}}
												{$entry->mapped('title')}
											</a>
										</span>
									</h3>
									<p class='ipsType_reset ipsType_medium ipsType_light'>{lang="byline_nodate" htmlsprintf="$entry->author()->link()"} {datetime="$entry->mapped('date')"}</p>
									<div class='ipsType_medium ipsType_richText ipsSpacer_both' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'>
										{$entry->truncated( true )|raw}
									</div>
									<ul class='ipsList_inline ipsClearfix ipsType_light'>
										{{foreach $entry->stats(TRUE) as $k => $v}}
											<li {{if \in_array( $k, $entry->hotStats )}}class="ipsDataItem_stats_hot" data-text='{lang="hot_item"}' data-ipsTooltip title='{lang="hot_item_desc"}'{{endif}}>
												<span class='ipsDataItem_stats_number'>{number="$v"}</span>
												<span class='ipsDataItem_stats_type'>{lang="blog_{$k}" pluralize="$v"}</span>
											</li>
										{{endforeach}}
									</ul>
								</div>
							</div>
						</li>
					{{endforeach}}
				</ul>
			</div>
			<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
			<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
		</div>
	</div>
</div>