<ips:template parameters="$entries, $featured, $blogs, $pagination, $viewMode, $category" />
<div class="ipsPageHeader ipsClearfix ipsMargin_bottom ipsHeaderButtons ipsFlex ipsFlex-ai:center ipsFlex-jc:between">
	<h1 class="ipsType_pageTitle ipsFlex-flex:11 ipsType_break">{lang="blogs"}</h1>
	{{if \count( $blogs ) || \IPS\blog\Blog::canCreate() || \IPS\Settings::i()->blog_allow_grid}}
		<ul class='ipsToolList ipsToolList_horizontal ipsClearfix ipsMargin_bottom:none ipsFlex-flex:00'>
			{template="indexButtons" group="browse" params="$blogs, $viewMode, FALSE, $category"}
		</ul>
	{{endif}}
</div>
{{if \count( $featured )}}
	{template="featuredEntries" group="browse" params="$featured"}
{{endif}}

{{if \count( $blogs ) || \IPS\blog\Blog::canCreate() || \IPS\Settings::i()->blog_allow_grid}}
	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hideDesktop ipsResponsive_hideTablet ipsResponsive_block ipsClearfix">
		{template="indexButtons" group="browse" params="$blogs, $viewMode, TRUE, $category"}
	</ul>
{{endif}}

<section class='ipsType_normal ipsSpacer_both cBlog_grid' data-controller='blog.front.browse.grid'>
	{{if \count($entries)}}		
		{{$count = 0;}}
		{{if $pagination['page'] == 1}}
			<div class='cBlog_grid_row cBlog_grid_row--primary'>
				{{foreach $entries as $id => $entry}}
					{{if $count == 2}}
						{{break;}}
					{{endif}}

					{template="indexGridEntry" app="blog" location="front" group="browse" params="$entry, true"}
					{{$count++;}}
				{{endforeach}}
			</div>
		{{endif}}

		{{$count = 1;}}
		{{$subcount = 0;}}
		<div class='cBlog_grid_row'>
			{{foreach $entries as $id => $entry}}
				{{$subcount++;}}
				{{if ( $pagination['page'] == 1 and $subcount > 2 ) or ( $pagination['page'] > 1 and $subcount)}}
					{template="indexGridEntry" app="blog" location="front" group="browse" params="$entry"}
					{{if $count % 3 == 0}}
						</div>
						<div class='cBlog_grid_row'>
					{{endif}}
					{{$count++;}}
				{{endif}}
			{{endforeach}}
		</div>
	{{else}}
		<div class="ipsBox ipsType_center ipsPad">
			<p class="ipsType_large">{lang="no_entries_yet"}</p>
		</div>
	{{endif}}
</section>
{{if $pagination['pages'] > 1}}
	{template="pagination" app="core" location="global" group="global" params="$pagination['url'], $pagination['pages'], $pagination['page'], $pagination['perpage'], TRUE, 'page'"}
{{endif}}