<ips:template parameters="$billingAgreement, $purchases, $transactions" />
{{if $billingAgreement->status() == $billingAgreement::STATUS_ACTIVE and !$billingAgreement->next_cycle}}
	<p class="ipsMessage ipsMessage_warning">{lang="billing_agreement_run_failed" sprintf="$billingAgreement->acpUrl()->setQueryString( 'do', 'reconcile' )->csrf()"}</p>
{{endif}}
<div class='ipsGrid'>
	<div class='ipsGrid_span4'>
		{{if $billingAgreement->status() == $billingAgreement::STATUS_ACTIVE}}
				<p class='ipsAreaBackground_positive ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
					<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-check-circle'></i> {lang="billing_agreement_active"}</span>
				</p>
		{{elseif $billingAgreement->status() == $billingAgreement::STATUS_SUSPENDED}}
			<p class='ipsAreaBackground ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
				<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-exclamation-circle'></i> {lang="billing_agreement_suspended"}</span>
			</p>
		{{elseif $billingAgreement->status() == $billingAgreement::STATUS_CANCELED}}
			<p class='ipsAreaBackground_negative ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
				<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-times-circle'></i> {lang="billing_agreement_canceled"}</span>
			</p>
		{{endif}}
		<div class="ipsBox ipsSpacer_bottom">
			<h2 class='ipsBox_titleBar'>{lang="billing_agreement_details"}</h2>
			<ul class="ipsDataList">
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong>{lang="ba_gw_id"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$billingAgreement->gw_id}
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong>{lang="billing_agreement_term"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$billingAgreement->term()}
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong>{lang="ba_started"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$billingAgreement->started->localeDate()}
					</span>
				</li>
				{{if $billingAgreement->next_cycle}}
					<li class="ipsDataItem">
						<span class="ipsDataItem_generic ipsDataItem_size4">
							<strong>{lang="billing_agreement_next_payment"}</strong>
						</span>
						<span class="ipsDataItem_generic">
							{$billingAgreement->nextPaymentDate()->localeDate()}
						</span>
					</li>
				{{endif}}
			</ul>
		</div>
		<div class="ipsBox ipsSpacer_bottom">
			<h2 class="ipsBox_titleBar">{lang="purchase_customer_info"}</h2>
			{{if $billingAgreement->member}}
				<div class='ipsPad ipsPhotoPanel ipsPhotoPanel_small ipsClearfix'>
					<a href="{$billingAgreement->member->acpUrl()}" class='ipsPos_left'><img src='{$billingAgreement->member->photo}' class='ipsUserPhoto ipsUserPhoto_small'></a>
					<div class='ipsType_normal'>
						<h3 class='ipsType_large ipsType_reset ipsType_blendLinks'><strong><a href="{$billingAgreement->member->acpUrl()}">{$billingAgreement->member->cm_name}</a></strong></h3>
						{$billingAgreement->member->email}<br>
						{lang="transaction_customer_since" sprintf="$billingAgreement->member->joined->localeDate()"}<br>
						{lang="transaction_spent" sprintf="$billingAgreement->member->totalSpent()"}
					</div>
				</div>
			{{else}}
				<div class='ipsPad ipsClearfix'>
					<p class="ipsMessage ipsMessage_error">{lang="billing_agreement_no_member"}</p>
				</div>
			{{endif}}
		</div>
	</div>
	<div class='ipsGrid_span8'>
		{{if $purchases}}
			<div class="ipsSpacer_bottom">
				<h2 class="acpBlock_title acpBlock_titleDark acpBlock_titleSmall">{lang="billing_agreement_purchases"}</h2>
				{$purchases|raw}
			</div>
		{{endif}}
		{{if $transactions}}
			<div class="ipsSpacer_bottom">
				<h2 class="acpBlock_title acpBlock_titleDark acpBlock_titleSmall">{lang="billing_agreement_transactions"}</h2>
				{$transactions|raw}
			</div>
		{{endif}}
	</div>
</div>