<ips:template parameters="$comment, $item, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed ipsRichEmbed--gallery-image-review' {{if settings.gallery_nsfw}} data-controller="gallery.front.global.nsfw"{{endif}}>
	{template="embedHeader" group="embed" app="core" params="$comment, $item->mapped('title'), $comment->mapped('date'), $url"}
	<div class='ipsPadding'>
		<div class='ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				<div class='ipsImageBlock'>
					{{if $item->media }}
						<a href='{$item->url()}' title='{lang="view_this_video" sprintf="$item->caption"}' class='ipsImageBlock__main'>
							<video data-role="video" preload="metadata" loading="lazy" {{if $item->masked_file_name }} poster="{file="$item->masked_file_name" extension="gallery_Images"}"{{endif}}>
								<source src="{file="$item->original_file_name" extension="gallery_Images"}" type='{$item->file_type}' />
							</video>
						</a>
					{{else}}
						<a href='{$item->url()}' title='{lang="view_this_image" sprintf="$item->caption"}' class='ipsImageBlock__main'>
							<img src='{file="$item->small_file_name" extension="gallery_Images"}' alt="{$item->caption}" loading="lazy">
						</a>
					{{endif}}
					{template="nsfwOverlay" app="gallery" location="front" group="global" params="$item"}
				</div>
				<div class='ipsPadding_top'>
					{template="embedOriginalItem" group="embed" app="core" params="$item"}
				</div>
			</div>
		</div>

		{template="rating" app="core" params="'veryLarge', $comment->mapped('rating')" group="global"} 
		{{if $comment->mapped('votes_total')}}
			<p class='ipsType_reset ipsType_medium'>{$comment->helpfulLine()|raw}</p>
		{{endif}}
		<hr class='ipsHr'>
		<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and \count( $comment->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>