<ips:template parameters="$item, $url, $image=NULL" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$item, $item->mapped('title'), $item->mapped('date'), $url"}
	{{if $item->media }}
		<span class='ipsThumb ipsNoThumb ipsNoThumb_video ipsThumb_embed'>
			<div class='cGallery_videoContainer_embedded'>
				<video data-controller="core.global.core.embeddedvideo" id="elGalleryVideo" data-role="video" class="ipsPos_center" controls preload="auto" width="100%" height="100%"{{if $item->masked_file_name }} poster="{file="$item->masked_file_name" extension="gallery_Images"}"{{endif}}>
					<source src="{file="$item->original_file_name" extension="gallery_Images"}" type='{$item->file_type}' />
					<embed wmode="opaque" autoplay="true" showcontrols="true" showstatusbar="true" showtracker="true" src="{file="$item->original_file_name" extension="gallery_Images"}" width="480" height="360" type='{$item->file_type}' />
				</video>
			</div>
		</span>
	{{else}}
		<a href='{$item->url()}' title='{lang="view_this_image" sprintf="$item->caption"}' class='ipsThumb ipsThumb_embed ipsThumb_bg {{if ! settings.max_internalembed_width}}ipsThumb_embed_fullWidth{{endif}}' style='background-image: url( "{backgroundimage="\IPS\File::get( 'gallery_Images', $item->masked_file_name )->url"}" );'>
			<img src='{file="$item->masked_file_name" extension="gallery_Images"}' alt="{$item->caption}" class='ipsHide'>
		</a>
	{{endif}}
	<div class='ipsPadding ipsClearfix'>
		{{if $desc = $item->truncated(TRUE)}}
			<div class='ipsType_richText ipsType_medium' data-truncate='3'>
				{$desc|raw}
			</div>
		{{endif}}
		{{if $item->copyright}}
			<p class='ipsType_reset ipsType_light ipsType_medium ipsSpacer_top ipsSpacer_half'>
				&copy; {$item->copyright}
			</p>
		{{endif}}
		{template="embedItemStats" group="embed" app="core" params="$item"}
	</div>

	{{if $item->directContainer() instanceof \IPS\gallery\Album}}
		<div class='ipsAreaBackground_light ipsPadding ipsClearfix ipsRichEmbed_moreInfo'>
			<h3 class='ipsType_minorHeading ipsTruncate ipsTruncate_line ipsType_blendLinks'>{lang="from_the_album"} "<a href='{$item->directContainer()->url()}'>{$item->directContainer()->_title}</a>"</h3>
			{{$images = \IPS\Gallery\Image::getItemsWithPermission( array( array( 'image_album_id=?', $item->album_id ) ), ( $item->directContainer()->sort_options == 'title' ) ? 'image_caption ASC' : $item::$databasePrefix . $item::$databaseColumnMap[ $item->directContainer()->sort_options ] . ' DESC', 9 );}}

			{{if \count( $images )}}
				<ul class='ipsList_reset cGalleryEmbed_albumStrip cGalleryEmbed_albumStrip_mini ipsSpacer_top ipsSpacer_half'>
					{{foreach $images as $albumImage}}
						<li>
							<a href='{$albumImage->url()}' style='background-image: url( "{backgroundimage="\IPS\File::get( 'gallery_Images', $albumImage->small_file_name )->url"}") '>
								<img src='{file="$albumImage->small_file_name" extension="gallery_Images"}' class='ipsHide'>
							</a>
						</li>
					{{endforeach}}

					{{if $item->directContainer()->count_imgs > 9}}
						<li class='cGalleryEmbed_albumStrip_last ipsAreaBackground'>
							<a href='{$item->directContainer()->url()}'><span>+{expression="$item->directContainer()->count_imgs - 9"}</span></a>
						</li>
					{{endif}}
				</ul>
			{{endif}}
		</div>
	{{endif}}
</div>