<ips:template parameters="$comment, $item, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$comment, $item->mapped('title'), $comment->mapped('date'), $url"}
	<div class='ipsPadding'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{if $item->media }}
					<a href='{$item->url()}' title='{lang="view_this_video" sprintf="$item->caption"}' class='ipsThumb ipsNoThumb ipsNoThumb_video ipsThumb_medium'>
						<video data-role="video" class="ipsPos_center" preload="metadata" width="100%" height="100%"{{if $item->masked_file_name }} poster="{file="$item->masked_file_name" extension="gallery_Images"}"{{endif}}>
							<source src="{file="$item->original_file_name" extension="gallery_Images"}" type='{$item->file_type}' />
						</video>
					</a>
				{{else}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg cGalleryEmbed_imageComment ipsType_center'>
						<a href='{$item->url()}' title='{lang="view_this_image" sprintf="$item->caption"}' class='ipsThumb ipsThumb_medium ipsThumb_bg' style='background-image: url( "{backgroundimage="\IPS\File::get( 'gallery_Images', $item->small_file_name )->url"}" );'>
							<img src='{file="$item->small_file_name" extension="gallery_Images"}' alt="{$item->caption}" class='ipsHide'>
						</a>
					</div>
				{{endif}}

				<div class='ipsPadding'>
					{template="embedOriginalItem" group="embed" app="core" params="$item"}
				</div>
			</div>
		</div>

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and \count( $comment->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>