<ips:template parameters="$albumItem, $albumNode, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed' {{if settings.gallery_nsfw}} data-controller="gallery.front.global.nsfw"{{endif}}>
	{template="embedHeader" group="embed" app="core" params="$albumItem, $albumItem->mapped('title'), $albumItem->mapped('date'), $url"}
	<div class='ipsPadding'>
		{{if $albumNode->coverPhoto('small')}}
			<div class='ipsImageBlock ipsImageBlock--embed-hero'>
				<a href='{$albumNode->url()}' class='ipsImageBlock__main'>
					<img src='{$albumNode->coverPhoto('masked')}' alt="{$albumItem->name}" loading="lazy">
				</a>
			</div>
		{{endif}}
		{{$images = \IPS\Gallery\Image::getItemsWithPermission( array( array( 'image_album_id=?', $albumNode->id ) ), ( $albumNode->sort_options == 'title' ) ? 'image_caption ASC' : \IPS\gallery\Image::$databasePrefix . \IPS\gallery\Image::$databaseColumnMap[ $albumNode->sort_options ] . ' DESC', 4 );}}
		{{if \count( $images )}}
			<ul class='ipsList_reset cGalleryEmbed_albumStrip ipsAreaBackground_light'>
				{{foreach $images as $albumImage}}
					<li>
						<div class='ipsImageBlock ipsImageBlock--ratio'>
							<a href='{$albumImage->url()}' class='ipsImageBlock__main'>
								{{if $albumImage->masked_file_name}}
									<img src='{file="$albumImage->masked_file_name" extension="gallery_Images"}' loading="lazy">
								{{elseif $albumImage->media}}
									<video preload="metadata" loading="lazy">
										<source src="{file="$albumImage->original_file_name" extension="gallery_Images"}" type='{$albumImage->file_type}' />
									</video>
									<div class='ipsImageBlock__video-icon'></div>
								{{endif}}
							</a>
							{template="nsfwOverlay" app="gallery" location="front" group="global" params="$albumImage, FALSE"}
						</div>
					</li>
				{{endforeach}}

				{{if $albumNode->count_imgs > 4}}
					<li>
						<div class='ipsImageBlock ipsImageBlock--ratio'>
							<a href='{$albumNode->url()}' class='ipsImageBlock__main'><span>+{expression="$albumNode->count_imgs - 4"}</span></a>
						</div>
					</li>
				{{endif}}
			</ul>
		{{endif}}

		<div class='ipsClearfix ipsMargin_top:half'>
			{{if $desc = $albumItem->truncated(TRUE)}}
				<div class='ipsType_richText ipsType_medium' data-truncate='3'>
					{$desc|raw}
				</div>
			{{endif}}
			{template="embedItemStats" group="embed" app="core" params="$albumItem, $albumNode->use_comments"}
		</div>
	</div>
</div>