<ips:template parameters="$item, $url, $image=NULL" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$item, $item->mapped('title'), $item->mapped('date'), $url"}
	<div class='ipsPadding' {{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
		<div class='ipsImageBlock'>
			{{if $item->media }}
				<div class='ipsImageBlock__main'>
					<video data-controller="core.global.core.embeddedvideo" id="elGalleryVideo" data-role="video" controls preload="metadata" {{if $item->masked_file_name }} poster="{file="$item->masked_file_name" extension="gallery_Images"}"{{endif}}>
						<source src="{file="$item->original_file_name" extension="gallery_Images"}" type='{$item->file_type}' />
						<embed wmode="opaque" autoplay="true" showcontrols="true" showstatusbar="true" showtracker="true" src="{file="$item->original_file_name" extension="gallery_Images"}" width="480" height="360" type='{$item->file_type}' />
					</video>
				</div>
			{{else}}
				<a href='{$item->url()}' title='{lang="view_this_image" sprintf="$item->caption"}' class='ipsImageBlock__main'>
					<img src='{file="$item->masked_file_name" extension="gallery_Images"}' alt="{$item->caption}" loading="lazy">
				</a>
			{{endif}}
            {template="nsfwOverlay" app="gallery" location="front" group="global" params="$item, FALSE"}
		</div>
	</div>
	<div class='ipsPadding ipsClearfix'>
		{{if $desc = $item->truncated(TRUE)}}
			<div class='ipsType_richText ipsType_medium' data-truncate='3'>
				{$desc|raw}
			</div>
		{{endif}}
		{{if $item->copyright}}
			<p class='ipsType_reset ipsType_light ipsType_medium ipsSpacer_top ipsSpacer_half'>
				&copy; {$item->copyright}
			</p>
		{{endif}}
		{template="embedItemStats" group="embed" app="core" params="$item"}
	</div>

	{{if $item->directContainer() instanceof \IPS\gallery\Album}}
		<div class='ipsAreaBackground_light ipsPadding ipsClearfix ipsRichEmbed_moreInfo'>
			<h3 class='ipsType_minorHeading ipsTruncate ipsTruncate_line ipsType_blendLinks'>{lang="from_the_album"} "<a href='{$item->directContainer()->url()}'>{$item->directContainer()->_title}</a>"</h3>
			{{$images = \IPS\Gallery\Image::getItemsWithPermission( array( array( 'image_album_id=?', $item->album_id ) ), ( $item->directContainer()->sort_options == 'title' ) ? 'image_caption ASC' : $item::$databasePrefix . $item::$databaseColumnMap[ $item->directContainer()->sort_options ] . ' DESC', 9 );}}

			{{if \count( $images )}}
				<ul class='ipsList_reset cGalleryEmbed_albumStrip cGalleryEmbed_albumStrip_mini ipsSpacer_top'>
					{{foreach $images as $albumImage}}
						<li>
							<div class='ipsImageBlock ipsImageBlock--ratio'>
								<a href='{$albumImage->url()}' class='ipsImageBlock__main'>
									{{if $albumImage->masked_file_name}}
										<img src='{file="$albumImage->masked_file_name" extension="gallery_Images"}' loading="lazy">
									{{elseif $albumImage->media}}
										<video preload="metadata" loading="lazy">
											<source src="{file="$albumImage->original_file_name" extension="gallery_Images"}" type='{$albumImage->file_type}' />
										</video>
										<div class='ipsImageBlock__video-icon'></div>
									{{endif}}
								</a>
								{template="nsfwOverlay" app="gallery" location="front" group="global" params="$albumImage, FALSE"}
							</div>
						</li>
					{{endforeach}}

					{{if $item->directContainer()->count_imgs > 9}}
						<li>
							<div class='ipsImageBlock ipsImageBlock--ratio'>
								<a href='{$item->directContainer()->url()}' class='ipsImageBlock__main'><span>+{expression="$item->directContainer()->count_imgs - 9"}</span></a>
							</div>
						</li>
					{{endif}}
				</ul>
			{{endif}}
		</div>
	{{endif}}
</div>