<ips:template parameters="$albumItem, $albumNode, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$albumItem, $albumItem->mapped('title'), $albumItem->mapped('date'), $url"}
	{{if $albumNode->coverPhoto('small')}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg cGalleryEmbed ipsType_center'>
			<a href='{$albumNode->url()}' style='background-image: url( "{backgroundimage="$albumNode->coverPhoto('masked')"}" )'>
				<img src='{$albumNode->coverPhoto('masked')}' class='ipsHide' alt="{$albumItem->name}">
			</a>
		</div>
	{{else}}
		<br>
		<br>
	{{endif}}

	{{$images = \IPS\Gallery\Image::getItemsWithPermission( array( array( 'image_album_id=?', $albumNode->id ) ), ( $albumNode->sort_options == 'title' ) ? 'image_caption ASC' : \IPS\gallery\Image::$databasePrefix . \IPS\gallery\Image::$databaseColumnMap[ $albumNode->sort_options ] . ' DESC', 4 );}}

	{{if \count( $images )}}
		<ul class='ipsList_reset cGalleryEmbed_albumStrip ipsAreaBackground_reset ipsClearfix'>
			{{foreach $images as $albumImage}}
				<li>
					<a href='{$albumImage->url()}' style='background-image: url( "{backgroundimage="\IPS\File::get( 'gallery_Images', $albumImage->small_file_name )->url"}") '>
						<img src='{file="$albumImage->small_file_name" extension="gallery_Images"}' class='ipsHide'>
					</a>
				</li>
			{{endforeach}}

			{{if $albumNode->count_imgs > 4}}
				<li class='cGalleryEmbed_albumStrip_last ipsAreaBackground'>
					<a href='{$albumNode->url()}'><span>+{expression="$albumNode->count_imgs - 4"}</span></a>
				</li>
			{{endif}}
		</ul>
	{{endif}}

	<div class='ipsPadding ipsClearfix'>
		{{if $desc = $albumItem->truncated(TRUE)}}
			<div class='ipsType_richText ipsType_medium' data-truncate='3'>
				{$desc|raw}
			</div>
		{{endif}}
		{template="embedItemStats" group="embed" app="core" params="$albumItem, $albumNode->use_comments"}
	</div>
</div>