<ips:template parameters="$comment, $item, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$comment, $item->mapped('title'), $comment->mapped('date'), $url"}
	<div class='ipsPad_double'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{$images = \IPS\Gallery\Image::getItemsWithPermission( array( array( 'image_album_id=?', $item->asNode()->id ) ), ( $item->asNode()->sort_options == 'title' ) ? 'image_caption ASC' : \IPS\gallery\Image::$databasePrefix . \IPS\gallery\Image::$databaseColumnMap[ $item->asNode()->sort_options ] . ' DESC', 19 );}}

				{{if \count( $images )}}
					<ul class='ipsList_reset cGalleryEmbed_albumStrip cGalleryEmbed_albumStrip_mini ipsAreaBackground_reset ipsClearfix'>
						{{foreach $images as $albumImage}}
							<li>
								<a href='{$albumImage->url()}' style='background-image: url( "{backgroundimage="\IPS\File::get( 'gallery_Images', $albumImage->small_file_name )->url"}") '>
									<img src='{file="$albumImage->small_file_name" extension="gallery_Images"}' class='ipsHide'>
								</a>
							</li>
						{{endforeach}}

						{{if $item->asNode()->count_imgs > 19}}
							<li class='cGalleryEmbed_albumStrip_last ipsAreaBackground'>
								<a href='{$item->asNode()->url()}'><span>+{expression="$item->asNode()->count_imgs - 19"}</span></a>
							</li>
						{{endif}}
					</ul>
				{{endif}}
				<div class='ipsPad'>
					{template="embedOriginalItem" group="embed" app="core" params="$item"}
				</div>
			</div>
		</div>

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled and \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and \count( $comment->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>