<ips:template parameters="$image, $showButton=TRUE" />
{{if settings.gallery_nsfw and !isset( cookie.nsfwImageOptIn ) and $image and $image->nsfw}}
<div class='ipsImageBlock__nsfw {{if !$showButton}}ipsImageBlock__nsfw--no-content{{endif}}'>
    {{if $showButton}}
        <div>{lang="gallery_image_is_nsfw"}</div>
        <div>
            <button type='button'>{lang="gallery_nsfw_view_anyway"}</button>
        </div>
    {{endif}}
</div>
{{endif}}