<ips:template parameters="$table, $headers, $rows, $quickSearch" />

<div data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-pageParam='albumPage' data-controller='core.global.core.table{{if $table->canModerate()}},core.front.core.moderation{{endif}}'>
	{{if $table->pages > 1}}
		<div data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, 'albumPage'"}
		</div>
		<br>
	{{endif}}

	<ol class='ipsList_reset ipsClear ipsGrid ipsGrid_collapsePhone' data-role='tableRows' data-controller='gallery.front.browse.list' id='elTable_{$table->uniqueId}'>
		{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
	</ol>
</div>