<ips:template parameters="$indexData, $itemData, $albumData, $image, $url, $condensed" />
{{if $image}}
{{$imageObj = \IPS\gallery\Image::constructFromData( $itemData, FALSE );}}
{{endif}}
{{if $condensed}}
	{{if $image}}
		<span class='ipsThumb_bg ipsThumb_small ipsPos_left'>
			<div class='ipsImageBlock ipsImageBlock--ratio'>
				<div class='ipsImageBlock__main'>
					<img src='{file="$image" extension="gallery_Images"}' alt="{$itemData['image_caption']}" loading="lazy">
				</div>
			</div>
	        {template="nsfwOverlay" app="gallery" location="front" group="global" params="$imageObj, FALSE"}
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsStreamItem_columns'{{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
		{{if $image}}
			<div class='ipsStreamItem_columns__thumb cGalleryStreamPreview'>
				<div class='ipsImageBlock'>
					<a href='{$url}' title='{lang="view_this_image" sprintf="$indexData['index_title']"}' class='ipsImageBlock__main'>
						<img src='{file="$image" extension="gallery_Images"}' alt="{$indexData['index_title']}" loading="lazy">
					</a>
	                {template="nsfwOverlay" app="gallery" location="front" group="global" params="$imageObj, FALSE"}
				</div>
			</div>
		{{endif}}
		<div class='ipsStreamItem_columns__content'>
			{{if $albumData}}
				<p class='ipsType_reset ipsType_normal ipsType_light'>
					{lang="from_the_album"} <a href='{url="app=gallery&module=gallery&controller=browse&album={$albumData['album_id']}" seoTemplate="gallery_album" seoTitle="$albumData['album_name_seo']"}'>{$albumData['album_name']}</a>
				</p>
			{{endif}}
			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
					{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
				</div>
			{{endif}}

			{{if $itemData['image_copyright']}}
				<p class='ipsSpacer_top ipsType_light ipsType_medium ipsType_reset'>
					&copy; {$itemData['image_copyright']}
				</p>
			{{endif}}
		</div>
	</div>
{{endif}}