<ips:template parameters="$indexData, $itemData, $images, $url, $condensed" />
{{if $condensed}}
	{{if \count( $images )}}
		{{$firstImage = array_shift( $images );}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left cGallerySearchAlbumThumb'>
			<div class='ipsImageBlock ipsImageBlock--ratio'>
				<a href='{$firstImage->url()}' class='ipsImageBlock__main'>
					<img src='{file="$firstImage->small_file_name" extension="gallery_Images"}' alt="{$firstImage->caption}" loading="lazy">
				</a>
			</div>
		</span>
		<div>
			<ul class='cGallerySearchAlbumThumbs ipsType_noBreak ipsMargin_bottom:half'>
				{{foreach $images as $image }}
					<li>
						<div class='ipsImageBlock ipsImageBlock--ratio'>
							<a href='{$image->url()}' class='ipsImageBlock__main'>
								<img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
							</a>
							{template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	{{if trim( $indexData['index_content'] ) !== ''}}
		<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
			{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
		</div>
	{{endif}}

	{{if \count($images)}}
		<div class='ipsMargin_top'>
			<ul class='cGalleryAlbums_recent' {{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
				{{foreach $images as $k => $image}}
					<li data-imageId="{$image->id}">
						<div class='ipsImageBlock'>
							<a href='{$image->url( "getPrefComment" )}' class='ipsImageBlock__main'>
								{{if $image->small_file_name}}
									<img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
								{{elseif $image->media}}
									<video loading="lazy"{{if $image->masked_file_name }} poster="{file="$image->masked_file_name" extension="gallery_Images"}"{{else}} preload="metadata"{{endif}}>
										<source src="{file="$image->original_file_name" extension="gallery_Images"}{{if !$image->masked_file_name }}#t=1{{endif}}" type='{$image->file_type}' />
									</video>
									<div class='ipsImageBlock__video-icon'></div>
								{{endif}}
							</a>
							{{if ( $image->directContainer()->allow_comments && $image->container()->allow_comments && count($image->comments()) > 0 )}}
								<div class='ipsImageBlock__footer'>
									<span><i class='fa fa-comment'></i> {expression="\count( $image->comments() )"}</span>
								</div>
							{{endif}}
							{template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{endif}}
{{endif}}