<ips:template parameters="$indexData, $itemData, $image, $url, $reviewRating, $condensed" />
{{if $image}}
{{$imageObj = \IPS\gallery\Image::constructFromData( $itemData, FALSE );}}
{{endif}}
{{if $condensed}}
	{{if $image}}
		<span class='ipsThumb_bg ipsThumb_small ipsPos_left'>
			<div class='ipsImageBlock ipsImageBlock--ratio'>
				<div class='ipsImageBlock__main'>
					<img src='{file="$image" extension="gallery_Images"}' alt="{$itemData['image_caption']}" loading="lazy">
				</div>
                {template="nsfwOverlay" app="gallery" location="front" group="global" params="$imageObj, FALSE"}
			</div>
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_noSpacing'>
        {{if $image}}
            <div class='ipsColumn ipsColumn_narrow ipsType_center'>
                <div class='ipsImageBlock ipsImageBlock--ratio'>
                    <a href='{$url}' title='{lang="view_this_image" sprintf="$itemData['image_caption']"}' class='ipsImageBlock__main'>
                        <img src='{file="$image" extension="gallery_Images"}' alt="{$itemData['image_caption']}" loading="lazy">
                    </a>
                    {template="nsfwOverlay" app="gallery" location="front" group="global" params="$imageObj, FALSE"}
                </div>
            </div>
        {{endif}}
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsStream_comment ipsPad'>
				{{if $reviewRating !== NULL}}
					{template="rating" app="core" params="'medium', $reviewRating" group="global"}
				{{endif}}
				{{if trim( $indexData['index_content'] ) !== ''}}
					<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
						{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
					</div>
				{{endif}}
			</div>
		</div>
	</div>
{{endif}}