<ips:template parameters="$indexData, $itemData, $albumData, $image, $url, $condensed" />
{{if $condensed}}
	{{if $image}}
		<span data-ipsLazyLoad class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="(string) \IPS\File::get( 'gallery_Images', $image )->url"}"{{else}}style='background-image: url({backgroundimage="(string) \IPS\File::get( 'gallery_Images', $image )->url"})'{{endif}}>
			<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$image" extension="gallery_Images"}' alt="{$indexData['index_title']}">
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsStreamItem_columns'>
		{{if $image}}
			<div class='ipsStreamItem_columns__thumb cGalleryStreamPreview'>
				<a href='{$url}' title='{lang="view_this_image" sprintf="$indexData['index_title']"}'>
					{{if settings.lazy_load_enabled}}
						<img data-ipsLazyLoad src='{expression="\IPS\Text\Parser::blankImage()"}' data-src='{file="$image" extension="gallery_Images"}' alt="{$indexData['index_title']}" class="ipsImage ipsStream_thumbnail">
					{{else}}
						<img src='{file="$image" extension="gallery_Images"}' alt="{$indexData['index_title']}" class="ipsImage ipsStream_thumbnail">
					{{endif}}				
				</a>
			</div>
		{{endif}}
		<div class='ipsStreamItem_columns__content'>
			{{if $albumData}}
				<p class='ipsType_reset ipsType_normal ipsType_light'>
					{lang="from_the_album"} <a href='{url="app=gallery&module=gallery&controller=browse&album={$albumData['album_id']}" seoTemplate="gallery_album" seoTitle="$albumData['album_name_seo']"}'>{$albumData['album_name']}</a>
				</p>
			{{endif}}
			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
					{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
				</div>
			{{endif}}

			{{if $itemData['image_copyright']}}
				<p class='ipsSpacer_top ipsType_light ipsType_medium ipsType_reset'>
					&copy; {$itemData['image_copyright']}
				</p>
			{{endif}}
		</div>
	</div>
{{endif}}