<ips:template parameters="$indexData, $itemData, $image, $url, $reviewRating, $condensed" />
{{if $condensed}}
	{{if $image}}
		<span data-ipsLazyLoad class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="(string) \IPS\File::get( 'gallery_Images', $image )->url"}"{{else}}style='background-image: url({backgroundimage="(string) \IPS\File::get( 'gallery_Images', $image )->url"})'{{endif}}>
			<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$image" extension="gallery_Images"}' alt="{$itemData['image_caption']}">
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_noSpacing'>
		<div class='ipsColumn ipsColumn_narrow ipsType_center'>
			<a href='{$url}' title='{lang="view_this_image" sprintf="$itemData['image_caption']"}'>
				{{if $image}}
					{{if settings.lazy_load_enabled}}
						<img data-ipsLazyLoad src='{expression="\IPS\Text\Parser::blankImage()"}' data-src='{file="$image" extension="gallery_Images"}'alt="{$itemData['image_caption']}" class="ipsImage ipsStream_thumbnail ipsStream_thumbnailSmall">
					{{else}}
						<img src='{file="$image" extension="gallery_Images"}'alt="{$itemData['image_caption']}" class="ipsImage ipsStream_thumbnail ipsStream_thumbnailSmall">
					{{endif}}
				{{else}}
					<div class='ipsNoThumb_medium ipsNoThumb'></div>
				{{endif}}
			</a>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsStream_comment ipsPad'>
				{{if $reviewRating !== NULL}}
					{template="rating" app="core" params="'medium', $reviewRating" group="global"}
				{{endif}}
				{{if trim( $indexData['index_content'] ) !== ''}}
					<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
						{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
					</div>
				{{endif}}
			</div>
		</div>
	</div>
{{endif}}