<ips:template parameters="$indexData, $itemData, $images, $url, $reviewRating, $condensed" />
{{if $condensed}}
	{{if \count( $images )}}
		{{$firstImage = array_shift( $images );}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left cGallerySearchAlbumThumb'>
			<div class='ipsImageBlock ipsImageBlock--ratio'>
				<div class='ipsImageBlock__main'>
					<img src='{file="$firstImage->small_file_name" extension="gallery_Images"}' alt="{$firstImage->caption}" loading="lazy">
				</div>
			</div>
		</span>
		<div>
			<ul class='cGallerySearchAlbumThumbs ipsType_noBreak ipsMargin_bottom:half'>
				{{foreach $images as $image }}
					<li>
						<div class='ipsImageBlock ipsImageBlock--ratio'>
							<a href='{$image->url()}' class='ipsImageBlock__main'>
								<img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
							</a>
							{template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_noSpacing'>
		<div class='ipsColumn ipsColumn_narrow ipsType_center'>
			<div class='ipsImageBlock'>
				<a href='{$url}' title='{lang="view_this_album" sprintf="$itemData['album_name']"}' class='ipsImageBlock__main'>
					{{if \count( $images )}}
						{{$firstImage = array_shift( $images );}}
						<img src='{file="$firstImage->small_file_name" extension="gallery_Images"}' alt="{$firstImage->caption}" loading="lazy">
					{{endif}}
				</a>
				{template="nsfwOverlay" app="gallery" location="front" group="global" params="$firstImage, FALSE"}
			</div>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsStream_comment ipsPad'>
				{{if $reviewRating !== NULL}}
					{template="rating" app="core" params="'medium', $reviewRating" group="global"}
				{{endif}}
				{{if trim( $indexData['index_content'] ) !== ''}}
					<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
						{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
					</div>
				{{endif}}
			</div>
			<ul class='cGallerySearchAlbumThumbs cGallerySearchExpanded ipsType_noBreak ipsSpacer_top'>
				{{foreach $images as $image }}
					<li>
						<div class='ipsImageBlock ipsImageBlock--ratio'>
							<a href='{$image->url()}' class='ipsImageBlock__main'>
								<img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
							</a>
							{template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
	</div>
{{endif}}