<ips:template parameters="$indexData, $itemData, $images, $url, $condensed" />
{{if $condensed}}
	{{if \count( $images )}}
		{{$firstImage = array_shift( $images );}}
		<a href='{$firstImage->url()}'>
			<span data-ipsLazyLoad class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="\IPS\File::get( 'gallery_Images', $firstImage->small_file_name )->url"}"{{else}}style='background-image: url({backgroundimage="\IPS\File::get( 'gallery_Images', $firstImage->small_file_name )->url"})'{{endif}}>
				<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$firstImage->small_file_name" extension="gallery_Images"}' alt="{$firstImage->caption}" class="">
			</span>
		</a>
		<ul class='ipsList_inline cGallerySearchAlbumThumbs ipsType_noBreak' data-ipsLazyLoad>
			{{foreach $images as $image }}
				<li>
					<a href='{$image->url()}'>
						<span class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="\IPS\File::get( 'gallery_Images', $image->small_file_name )->url"}"{{else}}style='background-image: url({backgroundimage="\IPS\File::get( 'gallery_Images', $image->small_file_name )->url"})'{{endif}}>
							<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}">
						</span>
					</a>
				</li>
			{{endforeach}}
		</ul>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	{{if trim( $indexData['index_content'] ) !== ''}}
		<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
			{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
		</div>
	{{endif}}

	{{if \count($images)}}
		<div class='cGalleryAlbums_recent ipsMargin_top' data-ipsLazyLoad>
			<ul class='ipsList_reset'>
				{{foreach $images as $k => $image}}
					<li {{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="\IPS\File::get( 'gallery_Images', $image->small_file_name )->url"}"{{else}}style='background-image: url({backgroundimage="\IPS\File::get( 'gallery_Images', $image->small_file_name )->url"})'{{endif}} class='cGalleryTrimmedImage'>
						<a href='{$image->url()}'>
							<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}">
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{endif}}
{{endif}}