<ips:template parameters="" />

<!-- Top bit -->
<div class="ipsPad ipsBox">
    <h3 class="ipsType_sectionHead">
        {lang="cloud_smart_community_title"}
    </h3>
    <p class="ipsType_light">
        {lang="cloud_smart_community_desc"}
    </p>
</div>
<br>
<div class="ipsGrid ipsGrid_collapsePhone">
    <!-- IMAGE SCANNER -->
	<div class="ipsGrid_span6">
        <div class="ipsSpacer_bottom ipsSpacer_double">
            <div class="ipsBox ipsFaded_withHover acpEnhancement">
                <div class="acpEnhancement__title">
                    <h3>{lang="cloud_ai_service_imagescan"} &nbsp; <span class="ipsBadge ipsBadge_neutral ipsPos_right">{lang="only_available_on_cloud"}</span></h3>
                </div>
                <div class="ipsType_normal ipsPad">
                    <div class="ipsType_richText">
                        <p>{lang="cloud_ai_service_imagescan_desc"}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- TRENDING -->
    <div class="ipsGrid_span6">
        <div class="ipsSpacer_bottom ipsSpacer_double">
            <div class="ipsBox ipsFaded_withHover acpEnhancement">
                <div class="acpEnhancement__title">
                    <h3>{lang="cloud_ai_service_trending"} &nbsp; <span class="ipsBadge ipsBadge_neutral ipsPos_right">{lang="only_available_on_cloud"}</span></h3>
                </div>
                <div class="ipsType_normal ipsPad">
                    <div class="ipsType_richText">
                        <p>{lang="cloud_ai_service_trending_desc"}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- REALTIME -->
    <div class="ipsGrid_span6">
        <div class="ipsSpacer_bottom ipsSpacer_double">
            <div class="ipsBox ipsFaded_withHover acpEnhancement">
                <div class="acpEnhancement__title">
                    <h3>
                        {lang="cloud_ai_service_realtime"} &nbsp; <span class="ipsBadge ipsBadge_neutral ipsPos_right">{lang="only_available_on_cloud"}</span>
                    </h3>
                </div>
                <div class="ipsType_normal ipsPad">
                    <div class="ipsType_richText">
                        <p>{lang="cloud_ai_service_realtime_desc"}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
	<a href="{url="switch_to_cloud" ips="true"}" target="_blank" class="ipsButton ipsButton_fullWidth ipsButton_medium ipsButton_important">{lang="learn_more"}</a>
</div>