<ips:template parameters="$member, $vid, $email" />

{$email->language->addToStack('email_account_deletion_confirm', FALSE)}
<br/><br/>

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
	<tr>
		<td dir='{dir}' align='center'>
			<a href='{url="app=core&module=system&controller=settings&do=confirmAccountDeletion&vid={$vid}" base="front"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("email_account_delete_link", FALSE)}</a>
		</td>
	</tr>
</table>

<br/><br/>
<em style='color: #8c8c8c'>&mdash; {setting='board_name'}</em>