<ips:template parameters="$notification, $extra, $email" />

<br />

{{if $notification->extra === 'missing' or $notification->extra === 'url'}}
	{$email->language->addToStack("license_error_none")}<br />
	<br />
{{else}}
	{{if $notification->extra === 'expireSoon'}}
		{$email->language->addToStack("license_renewal_soon_email")}<br />
	{{else}}
		{$email->language->addToStack("license_expired_email")}<br />
	{{endif}}
	<br />
	{$email->language->addToStack("license_benefits_info")}
	<br /><br />
	<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
		<tr>
			<td dir='{dir}' align='center'>
				<a href='{url="renew_my_license" ips="true"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("license_renew_now", FALSE)}</a>
			</td>
		</tr>
	</table>

{{endif}}