<ips:template parameters="$notification, $member, $email" />

{$email->language->addToStack('email_notification_pii_data_request', FALSE, array( 'sprintf' => array( $member->url(), $member->name ) ) )}
<br/>
<br/>

<a href='{url="app=core&module=members&controller=privacy" base="admin"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack('pii_review', FALSE)}</a>

<br/><br/>
<em style='color: #8c8c8c'>&mdash; {setting='board_name'}</em>