<ips:template parameters="$notification, $extra, $email" />
<br />
{$email->language->addToStack("acp_notification_ConfigurationError_email")}<br />
<br />
{{if $notification->extra === 'dangerousFunctions'}}
	<strong>{$email->language->addToStack("disable_functions_title")}</strong><br />
	<br />
	{$email->language->addToStack("disable_functions_desc_1")}<br />
	<br />
	{$email->language->addToStack("disable_functions_desc_2")}<br />
	<br />
	{{foreach \IPS\core\extensions\core\AdminNotifications\ConfigurationError::enabledDangerousFunctions() as $function}}
		<code>{$function}</code> &nbsp;
	{{endforeach}}
{{elseif $notification->extra === 'displayErrors'}}
	<strong>{$email->language->addToStack("display_errors_title")}</strong><br />
	<br />
	{$email->language->addToStack("display_errors_desc")}<br />
{{elseif $notification->extra === 'recommendations'}}
	<strong>{$email->language->addToStack("requirements_checker")}</strong><br />
	<br />
	{$email->language->addToStack("system_check_recommended_blurb")}<br />
	<br />
	{$email->language->addToStack("system_check_recommended_email")}
{{elseif mb_substr( $notification->extra, 0, 8 ) === 'taskLock'}}
	<strong>{$email->language->addToStack( "dashboard_tasks_broken", FALSE, array( 'sprintf' => array( \IPS\Task::load( \intval( mb_substr( $notification->extra, 9 ) ) )->key ) ) )}</strong><br />
	<br />
	{$email->language->addToStack("dashboard_tasks_broken_desc")}
{{elseif $notification->extra === 'failedMail'}}
	<strong>{$email->language->addToStack("dashboard_email_broken")}</strong><br />
	<br />
	{$email->language->addToStack( "dashboard_email_broken_desc_1", FALSE, array( 'sprintf' => $email->language->formatNumber( \IPS\Email::countFailedMail() ) ) )}<br />
	<br />
	{$email->language->addToStack("dashboard_email_broken_desc_email")}
{{elseif $notification->extra === 'dataStorageBroken'}}
	<strong>{$email->language->addToStack("dashboard_datastore_broken")}</strong><br />
	<br />
	{$email->language->addToStack("dashboard_datastore_broken_desc")}
{{elseif $notification->extra === 'cacheBroken'}}
	<strong>{$email->language->addToStack("dashboard_invalid_cachesetup")}</strong><br />
	<br />
	{$email->language->addToStack("dashboard_invalid_cachesetup_desc")}
{{elseif $notification->extra === 'cicEmailQuota'}}
	<strong>{$email->language->addToStack("dashboard_cic_email_quota")}</strong><br />
	<br />
	{$email->language->addToStack("dashboard_cic_email_quota_desc")}
{{endif}}
<br /><br />
<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
	<tr>
		<td dir='{dir}' align='center'>
			<a href='{url="app=core&module=overview&controller=notifications" base="admin"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("see_all_notifications", FALSE)}</a>
		</td>
	</tr>
</table>