<ips:template parameters="$notification, $extra, $email" />
<br />

{$email->language->addToStack("acp_notification_bulletin_email")}
<br /><br />

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
	<tr>
		<td dir='{dir}'>
			<table width='100%' cellpadding='0' cellspacing='0' border='0' style='background: #f9f9f9;'>
				<tr>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 18px; font-weight: bold;">
						{$notification->title()}
					</td>
				</tr>
				<tr style='line-height: 10px'>
					<td dir='{dir}' height='10'><img src="{setting="base_url"}applications/core/interface/email/spacer.png" alt='' width="1" height="1" /></td>
				</tr>
				<tr>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">
						{$email->parseTextForEmail( $notification->body() )|raw}
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>


<br /><br />
<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
	<tr>
		<td dir='{dir}' align='center'>
			<a href='{url="app=core&module=overview&controller=notifications" base="admin"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("see_all_notifications", FALSE)}</a>
		</td>
	</tr>
</table>