<ips:template parameters="$address, $key, $email" />

{$email->language->addToStack("email_contact_verify", FALSE)}

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
	<tr>
		<td dir='{dir}' align='center'>
			<a href='{url="app=core&module=contact&controller=contact&do=confirm&key={$key}&email={$address}" base="front" seoTemplate="contact"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("contact_verify", FALSE)}</a>
		</td>
	</tr>
</table>


<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>