<ips:template parameters="$member, $name, $fromEmail, $message, $email" />
{$email->language->addToStack("email_contact_form", FALSE)}
<br />
<br />

<table width='100%' cellpadding='0' cellspacing='0' border='0'>
	<tr>
		<td dir='{dir}' width='40' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
			<img src='{$member->get_photo( true, true )}' width='40' height='40' style='border: 1px solid #777777; vertical-align: middle;'>
		</td>
		<td dir='{dir}' width='30' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
			<br />
			<span style='display: block; width: 0px; height: 0px; border-width: 15px; border-color: transparent #f9f9f9 transparent transparent; border-style: solid'></span>
		</td>
		<td dir='{dir}' valign='top' style='background: #f9f9f9;'>
			<table width='100%' cellpadding='10' cellspacing='0' border='0'>
				<tr>
					<td dir='{dir}'>
						<table width='100%' cellpadding='5' cellspacing='0' border='0'>
							<tr>
								<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 14px;">
									<strong>{$email->language->addToStack("email_contact_said", FALSE, array( 'sprintf' => array( $name, $fromEmail ) ) )}</strong>
								</td>
							</tr>
							<tr>
								<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 14px;">
									{$email->parseTextForEmail( $message, $email->language )|raw}
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>