<ips:template parameters="$member, $badge, $email" />
<br />
{$email->language->addToStack("notification__new_badge", NULL, [ 'sprintf' => [$badge->getTitleForLanguage($email->language)]])}
<br><br>
<table width='100%' cellpadding='0' cellspacing='0' border='0'>
	<tr>
		<td dir='{dir}'>
			<table width='400px' cellpadding='0' cellspacing='0' border='0'>
				<tr>
					<td dir='{dir}' align='center'>
						<table width='80' cellpadding='15' cellspacing='0' border='0'>
							<tr>
								<td dir='{dir}'>
									<img src='{$member->get_photo( true, true )}' width='80' height='80' style='border: 1px solid #777777; vertical-align: middle;'>
								</td>
							</tr>
						</table>
					</td>
					<td dir='{dir}' align='center'>
						<table width='80' cellpadding='15' cellspacing='0' border='0'>
							<tr>
								<td dir='{dir}'>
									<span style="font-size:48px;">=</span>
								</td>
							</tr>
						</table>
					</td>
					<td dir='{dir}' align='center'>
						<table width='80' cellpadding='15' cellspacing='0' border='0'>
							<tr>
								<td dir='{dir}'>
									<img src='{setting="base_url"}applications/core/interface/email/tada.png' width='80' height='80' alt=''>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
{{if $count = $badge->ownedByCount(TRUE)}}
	{$email->language->addToStack("notification_email_did_you_know_count", NULL, ['sprintf'=>[$count]])}
{{endif}}
<br><br>
{$email->language->addToStack("notification_email_keep_it_going")}


<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>