<ips:template parameters="$content, $email" />

{{if $content->author()->member_id}}
{$email->language->addToStack("email_new_content", FALSE, array( 'sprintf' => array( $content->author()->url(), $content->author()->name, $content->indefiniteArticle( $email->language ) ) ) )} <a href='{$content->url()}'>{$content->mapped('title')}</a>
{{elseif $content->author()->real_name}}
{$email->language->addToStack("email_new_content_guest", FALSE, array( 'sprintf' => array( $email->language->addToStack( 'guest_name_shown', FALSE, array( 'sprintf' => array( $content->author()->real_name ) ) ), $content->indefiniteArticle( $email->language ) ) ) )} <a href='{$content->url()}'>{$content->mapped('title')}</a>
{{else}}
{$email->language->addToStack("email_new_content_guest", FALSE, array( 'sprintf' => array( $email->language->addToStack( 'guest_name_shown', FALSE, array( 'sprintf' => array( $email->language->addToStack('guest') ) ) ), $content->indefiniteArticle( $email->language ) ) ) )} <a href='{$content->url()}'>{$content->mapped('title')}</a>
{{endif}}

<br />
<br />

{$content->emailContent( $email, 'html' )|raw}
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>