<ips:template parameters="$content, $email" />

{$email->language->addToStack("email_mentioned", FALSE, array( 'sprintf' => array( $content->author()->name, $content->indefiniteArticle( $email->language ), ( $content instanceof \IPS\Content\Comment ) ? $content->item()->mapped('title') : $content->mapped('title') ) ) )}

<br />
<br />

{$content->emailContent( $email, 'html' )|raw}
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>