<ips:template parameters="$member, $recognize, $email" />
<br />
{$email->language->addToStack( 'notification_new_recognized_mail', FALSE, [ 'sprintf' => [ $recognize->content()->url() ] ] )}
{{if $recognize->message}}
<p style='border-bottom: 1px solid #e0e0e0;border-top: 1px solid #e0e0e0; padding: 10px 0px'>
<strong><em>{$recognize->message}</em></strong>
{{if $awardedBy = $recognize->awardedBy()}}
<br>- <a href="{$awardedBy->url()}">{$awardedBy->name}</a>
{{endif}}
</p>
{{endif}}
{{if $recognize->points}}
<p>{$email->language->addToStack("recognize_points_awarded", NULL, [ 'sprintf' => [ $recognize->points ] ] )}</p>
{{endif}}
{{if $badge = $recognize->badge()}}
{$email->language->addToStack("recognize_badge_awarded", NULL, [ 'sprintf' => [ $badge->_title ] ] )}
<br><br>
{$email->language->addToStack("notification_email_check_it_out")}
<br>
<br><strong>{$badge->_title}</strong>
<br>
<img src="{file="$badge->image" extension="core_Badges"}">
{{endif}}
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>