<ips:template parameters="$request, $email" />

{$email->language->addToStack('email_notification_pii_data')}
<br/>
<br/>
<a href="{url="app=core&module=system&controller=settings&area=mfa" seoTemplate="settings_mfa" base="front"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack('pii_download', FALSE)}</a>

<br/><br/>
<em style='color: #8c8c8c'>&mdash; {setting='board_name'}</em>