<ips:template parameters="$comment, $email" />

{{$item = $comment->item();}}

{$email->language->addToStack("email_new_profile_reply", FALSE, array( 'sprintf' => array( $comment->author()->url(), $comment->author()->name ) ) )}

<br /><br />
<a href='{$item->url()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("email_go_to_your_profile", FALSE)}</a>

<br />
<br />

<table width='100%' cellpadding='0' cellspacing='0' border='0'>
	<tr>
		<td dir='{dir}' width='40' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
			<img src='{$item->author()->get_photo( true, true )}' width='40' height='40' style='border: 1px solid #777777; vertical-align: middle;'>
		</td>
		<td dir='{dir}' width='30' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
			<br />
		</td>
		<td dir='{dir}' valign='top' style='background: #f9f9f9;'>
			<table width='100%' cellpadding='10' cellspacing='0' border='0'>
				<tr>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 14px;">
						<strong>{$email->language->addToStack("email_said", FALSE, array( 'sprintf' => array( $item->author()->name ) ) )}</strong>
					</td>
				</tr>
				<tr>
					<td dir='{dir}'>
						<table width='100%' cellpadding='5' cellspacing='0' border='0'>
							<tr>
								<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 14px;">
									{$email->parseTextForEmail( $item->content(), $email->language )|raw}
								</td>
							</tr>
							<tr>
								<td dir='{dir}'>
									<a href='{$item->url()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("go_to_this_x", FALSE, array( 'sprintf' => array( mb_strtolower( $email->language->addToStack( $item::$title, FALSE ) ) ) ) )}</a>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<br />
<table width='100%' cellpadding='0' cellspacing='0' border='0'>
	<tr>
		<td dir='{dir}' width='40'>&nbsp;</td>
		<td dir='{dir}' width='40' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
			<img src='{$comment->author()->get_photo( true, true )}' width='40' height='40' style='border: 1px solid #777777; vertical-align: middle;'>
		</td>
		<td dir='{dir}' width='30' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
			<br />
			<span style='display: block; width: 0px; height: 0px; border-width: 15px; border-color: transparent #f9f9f9 transparent transparent; border-style: solid'></span>
		</td>
		<td dir='{dir}' valign='top' style='background: #f9f9f9;'>
			<table width='100%' cellpadding='10' cellspacing='0' border='0'>
				<tr>
					<td dir='{dir}'>
						<table width='100%' cellpadding='5' cellspacing='0' border='0'>
							<tr>
								<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 14px;">
									<strong>{$email->language->addToStack("email_replied", FALSE, array( 'sprintf' => array( $comment->author()->name ) ) )}</strong>
								</td>
							</tr>
							<tr>
								<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 14px;">
									{$email->parseTextForEmail( $comment->content(), $email->language )|raw}
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<br />
<p style="margin: 0; font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 12px; color: #8d8d8d">
	{$email->language->addToStack("email_ignore_user_pm", FALSE, array( 'sprintf' => array( $comment->author()->name ) ) )}
</p>

<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>