<ips:template parameters="$comment, $email" />

{{$item = $comment instanceof \IPS\Content\Item ? $comment : $comment->item();}}

{$email->language->addToStack("email_quoted_you", FALSE, array( 'sprintf' => array( $comment->author()->url(), $comment->author()->name, $item->indefiniteArticle( $email->language ) ) ) )}

<br />
<br />
{$comment->emailContent( $email, 'html' )|raw}
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>