<ips:template parameters="$email" />

{$email->language->addToStack("onboard_welcome_message_email", FALSE)}
<br />
<a href='{url="app=core&module=overview&controller=onboard" base="admin"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("onboard_finish_setup", FALSE)}</a>



<br /><br />
{$email->language->addToStack("onboard_email_thanks", FALSE)}
<br />
<em style='color: #8c8c8c'>&mdash; {$email->language->addToStack("onboard_email_tic", FALSE)}</em>