<ips:template parameters="$member,$key,$email" />

{$email->language->addToStack("password_reset_forced", FALSE, array( 'sprintf' => \IPS\Settings::i()->board_name ) )}

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f9f9f9;'>
	<tr>
		<td dir='{dir}' align='center'>
			<a href='{url="app=core&module=system&controller=register&do=setPassword&mid={$member->member_id}&passkey={$key}" base="front" seoTemplate="register"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("set_password", FALSE)}</a>
		</td>
	</tr>
</table>


<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>