<ips:template parameters="$allContent, $secret, $email" />

{$email->language->addToStack("post_before_register_followup_text", FALSE)}
<br />
<br />
<a href='{url="app=core&module=system&controller=register&pbr={$secret}&hidereminder=1" base="front" seoTemplate="register"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("finish_this_submission", FALSE)}</a>



<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>