<ips:template parameters="$member, $email" />

{$email->language->addToStack("email_reg_complete", FALSE, array( 'sprintf' => array( \IPS\Settings::i()->board_name ) ) )}{{if $member->members_pass_hash}} {$email->language->addToStack("email_reg_complete_pass")}{{endif}}

<br />
<br />
<a href='{setting="base_url"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("email_go_to_site", FALSE, array( 'sprintf' => array( \IPS\Settings::i()->board_name ) ) )}</a>

<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>