<ips:template parameters="$item, $comment, $replies, $email" />
{{$member = $item->author();}}
<br />
{$email->language->addToStack("mail_solved_reengagement", FALSE, array( 'htmlsprintf' => array( $item->definiteArticle( $email->language ), $item->url(), $item->mapped('title') ) ) )}
<br /><br />
<em>{$email->language->addToStack("mail_solved_reengagement_wyw")}</em>
<br /><br />
{$comment->emailContent( $email, 'html', false )|raw}
<br /><br />
<em>{$email->language->addToStack("mail_solved_reengagement_others")}</em>
<br><br>
{{foreach $replies as $reply}}
	{$reply->emailContent( $email, 'html' )|raw}
{{endforeach}}
<br><br>
{$email->language->addToStack("mail_solved_reengagement_solved")}
<br /><br />
<a style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;" href="{$item->url()}">{$email->language->addToStack("mail_solved_reengagement_action")}</a>
<br /><br />
<a href="{url="app=core&module=system&controller=unsubscribe&action=markSolved&email=" seoTemplate="unsubscribe" base="front"}{$member->email}&key={expression="md5( $member->email . ':' . $member->members_pass_hash )"}" style='color: #8c8c8c; text-decoration: none; display: inline-block'>{lang="solved_reengagement_stop"}</a>.
<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>