<ips:template parameters="$member, $email" />
<tr>
	<td dir='{dir}' valign="top"><img src='{setting="base_url"}applications/core/interface/email/spacer.png' width='1' height='1' alt=''></td>
	<td dir='{dir}' valign='middle' align='center' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 12px; line-height: 18px; padding-left: 10px;">
		{$email->language->addToStack("unsubscribe_not_needed", FALSE)}
		<br />
	</td>
</tr>