<ips:template parameters="$record, $category, $database, $page, $title, $hasModOptions, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
{{$modOptions = array( 'create_record_state', 'record_expiry_date', 'record_pinned', 'record_allow_comments', 'record_comment_cutoff', 'record_meta_keywords', 'record_meta_description' );}}
{template="pageHeader" if="!\IPS\Request::i()->isAjax()" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( $title )"}
<div id="elCmsPageWrap" data-pageid="{$page->id}">
<form accept-charset='utf-8' class="ipsForm {$class}" data-ipsForm="true" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
		<input type="hidden" name="content_record_form_container" value="{$category->_id}">
	{{endif}}

	<div class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="record_information" sprintf="$database->recordWord(1, TRUE)"}</h2>
		{{if \count( $elements ) > 1}}
			{{if !empty( $errorTabs )}}
				<p class="ipsMessage ipsMessage_error ipsJS_show">{lang="tab_error"}</p>
			{{endif}}
			<div class='ipsTabs ipsTabs_contained ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
				<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
				<ul role='tablist'>
					{{foreach $elements as $name => $content}}
						<li>
							<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item" role="tab">
								{lang="$name"}
							</a>
						</li>
					{{endforeach}}
				</ul>
			</div>
			<div id='ipsTabs_content_{$id}' class='ipsTabs_panels ipsTabs_contained'>
				{{foreach $elements as $name => $contents}}
					<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">

						{{if $hasModOptions && ( $name == 'topic_mainTab' OR $name == 'content_record_form_mainTab' ) }}
							<div class='ipsColumns ipsColumns_collapsePhone'>
								<div class='ipsColumn ipsColumn_fluid'>
						{{endif}}
							<ul class='ipsForm ipsForm_vertical'>
								{{foreach $contents as $inputName => $input}}
									{{if $inputName == 'content_field_' . $database->field_title and isset( $contents['record_static_furl_set'] ) and isset( $contents['record_static_furl'] )}}
										{template="customslug" app="cms" location="global" group="records" params="$collection, $input, $category, $page, $database, $record"}
									{{endif}}
									{{if !\in_array( $inputName, $modOptions ) and $inputName !== 'record_static_furl_set' and $inputName !== 'record_static_furl'}}
										{$input|raw}
									{{endif}}
								{{endforeach}}								
							</ul>
						{{if $hasModOptions && $name == 'content_record_form_mainTab'}}
								</div>
								<div class='ipsColumn ipsColumn_wide'>
									<div class='ipsPad ipsAreaBackground_light'>
									<h3 class='ipsType_sectionHead'>{lang="cms_moderator_options"}</h3>
										<ul class='ipsForm ipsForm_vertical ipsSpacer_top'>
											{{foreach $elements as $collection}}
												{{foreach $collection as $inputName => $input}}
													{{if \in_array( $inputName, $modOptions )}}
														{{if $inputName == 'record_expiry_date' or $inputName == 'record_comment_cutoff'}}
															<li class='ipsFieldRow ipsClearfix'>
																<label class="ipsFieldRow_label" for="elInput_{$inputName}">{lang="$input->name"}</label>
																<ul class='ipsFieldRow_content ipsList_reset cCreateTopic_date'>
																	<li>
																		<i class='fa fa-calendar'></i>
																		<input type="date" name="{$input->name}" id="elInput_{$inputName}" value="{{if $input->value instanceof \IPS\DateTime}}{$input->value->format('Y-m-d')}{{else}}{$input->value}{{endif}}" class="ipsField_short" data-control="date" placeholder='{expression="str_replace( array( 'YYYY', 'MM', 'DD' ), array( \IPS\Member::loggedIn()->language()->addToStack('_date_format_yyyy'), \IPS\Member::loggedIn()->language()->addToStack('_date_format_mm'), \IPS\Member::loggedIn()->language()->addToStack('_date_format_dd') ), str_replace( 'Y', 'YY', \IPS\Member::loggedIn()->language()->preferredDateFormat() ) )"}'>
																	</li>
																	<li>
																		<i class='fa fa-clock-o'></i>
																		<input name="{$input->name}_time" type="time" size="12" class="ipsField_short" placeholder="{lang="_time_format_hhmm"}" step="60" min="00:00" value="{{if $input->value instanceof \IPS\DateTime}}{$input->value->format('H:i')}{{endif}}">
																	</li>
																</ul>
															</li>
														{{else}}
															{$input|raw}
														{{endif}}
													{{endif}}
												{{endforeach}}
											{{endforeach}}
										</ul>
									</div>
								</div>
							</div>
						{{endif}}
					</div>
				{{endforeach}}
			</div>		
		{{else}}
			<div class='ipsPad'>
				{{if $hasModOptions}}
					<div class='ipsColumns ipsColumns_collapsePhone'>
						<div class='ipsColumn ipsColumn_fluid'>
				{{endif}}
					<ul class='ipsForm ipsForm_vertical'>
						{{foreach $elements as $collection}}
							{{foreach $collection as $inputName => $input}}
								{{if $inputName == 'content_field_' . $database->field_title and isset( $collection['record_static_furl_set'] ) and isset( $collection['record_static_furl'] )}}
									{template="customslug" app="cms" location="global" group="records" params="$collection, $input, $category, $page, $database, $record"}
								{{endif}}
								{{if !\in_array( $inputName, $modOptions ) and $inputName !== 'record_static_furl_set' and $inputName !== 'record_static_furl'}}
									{$input|raw}
								{{endif}}
							{{endforeach}}
						{{endforeach}}
					</ul>
				{{if $hasModOptions}}
						</div>
						<div class='ipsColumn ipsColumn_wide'>
							<div class='ipsPad ipsAreaBackground_light'>
							<h3 class='ipsType_sectionHead'>{lang="cms_moderator_options"}</h3>
								<ul class='ipsForm ipsForm_vertical ipsSpacer_top'>
									{{foreach $elements as $collection}}
										{{foreach $collection as $inputName => $input}}
											{{if \in_array( $inputName, $modOptions )}}
												{{if $inputName == 'record_expiry_date' or $inputName == 'record_comment_cutoff'}}
													<li class='ipsFieldRow ipsClearfix'>
														<div data-role="unlimitedCatch">
															<label class="ipsFieldRow_label" for="elInput_{$input->name}">{lang="$input->name"}</label>
															<ul class='ipsFieldRow_content ipsList_reset cCreateTopic_date'>
																<li>
																	<i class='fa fa-calendar'></i>
																	<input type="date" name="{$input->name}" id="elInput_{$input->name}" value="{{if $input->value instanceof \IPS\DateTime}}{$input->value->format('Y-m-d')}{{else}}{$input->value}{{endif}}" class="ipsField_short" data-control="date" placeholder='{{if $input->placeholder !== NULL}}{$input->placeholder}{{else}}{expression="str_replace( array( 'YYYY', 'MM', 'DD' ), array( \IPS\Member::loggedIn()->language()->addToStack('_date_format_yyyy'), \IPS\Member::loggedIn()->language()->addToStack('_date_format_mm'), \IPS\Member::loggedIn()->language()->addToStack('_date_format_dd') ), str_replace( 'Y', 'YY', \IPS\Member::loggedIn()->language()->preferredDateFormat() ) )"}{{endif}}' data-preferredFormat="{{if $input->value instanceof \IPS\DateTime}}{$input->value->localeDate()}{{else}}{$input->value}{{endif}}" {{if $input->disabled}}disabled aria-disabled='true'{{endif}}>
																</li>
																<li>
																	<i class='fa fa-clock-o'></i>
																	<input name="{$input->name}_time" type="time" size="12" class="ipsField_short" placeholder="{lang="_time_format_hhmm"}" step="60" min="00:00" value="{{if $input->value instanceof \IPS\DateTime}}{$input->value->format('H:i')}{{endif}}">
																</li>
																<li>
																	{{if $input->options['unlimited'] !== NULL and ( !$input->disabled or $input->options['unlimited'] === $input->value )}}
																	&nbsp;
																	{lang="or"}
																	&nbsp;
																	<span class='ipsCustomInput'>
																		<input type="checkbox" role='checkbox' data-control="unlimited{{if \count( $input->toggles )}} toggle{{endif}}" name="{$input->name}_unlimited" id='{$input->name}_unlimited' value="{$input->options['unlimited']}" {{if $input->options['unlimited'] === $input->value}}checked aria-checked='true'{{endif}} {{if $input->options['disabled']}}disabled{{endif}} {{if \count( $input->toggles )}}{{if $input->toggleOn === FALSE}}data-togglesOff{{else}}data-togglesOn{{endif}}="{expression="implode( ',', $input->toggles )"}"{{endif}} aria-labelledby='label_{$input->name}_unlimited'>
																		<span></span>
																	</span>
																	<label for='{$input->name}_unlimited' id='label_{$input->name}_unlimited' class='ipsField_unlimited'>{lang="never"}</label>
																	{{endif}}
																</li>
															</ul>
														</div>
													</li>
												{{else}}
													{$input|raw}
												{{endif}}
											{{endif}}
										{{endforeach}}
									{{endforeach}}
								</ul>
							</div>
						</div>
					</div>
				{{endif}}
			</div>
		{{endif}}
		<div class='ipsAreaBackground ipsPad ipsType_center'>
			<button type='submit' class='ipsButton ipsButton_large ipsButton_primary'>{lang="content_record_form_save"}</button>
		</div>
	</div>
</form>
</div>