<ips:template parameters="$modifiedFiles, $form" />
<div data-controller="core.admin.support.md5">
	<div class="{{if $form->error}}ipsHide{{endif}}" data-role="initialScreen">
		<div class='ipsPadding:double ipsType_large'>
			{lang="md5_fail_help_1"}
			<ul>
				{{foreach $modifiedFiles as $file}}
					<li>{$file}</li>
				{{endforeach}}
			</ul>
			{lang="md5_fail_help_2"}
		</div>
		<div class="ipsAreaBackground_light ipsClearfix ipsPadding ipsType_center">
			<div class="ipsJS_show">
				<a href="#" class="ipsButton ipsButton_important" data-action="downloadDelta"><i class="fa fa-cloud-download"></i> {lang="md5_fail_download"}</a>
				<a href="{url="client_area" ips="true"}" target="_blank" rel="noopener" class="ipsButton ipsButton_alternate">{lang="delta_upgrade_download_full"}</a>
			</div>
			<div class="ipsJS_hide">
				<a href="{url="client_area" ips="true"}" class="ipsButton ipsButton_important" target="_blank" rel="noopener">{lang="delta_upgrade_go_to_clientarea"}</a>
			</div>
		</div>
	</div>
	<div data-role="downloadForm" {{if !$form->error}}class="ipsHide"{{endif}}>
		{$form|raw}
	</div>
</div>