<ips:template parameters="$info, $table" />

		
{{if isset( $info['used_memory_human'] ) AND ( isset( $info['total_system_memory'] ) OR isset( $info['maxmemory'] ) )}}
	{{$percentage = ( $info['used_memory'] > 0 ) ? ceil( 100 / ( $info['maxmemory'] ?: $info['total_system_memory'] ) * $info['used_memory'] ) : 0;}}
	<div data-ipsSticky data-ipsSticky-spacing='60' class="ipsPad_half ipsType_center">
		<strong>{lang="redis_space_used_bar"}</strong><br>
		<div class="ipsProgressBar">
			<div class="ipsProgressBar_progress" style="width:{$percentage}%" data-role="percentageBar"><span data-role="percentage">{$percentage}</span>% (<span data-role="number">{$info['used_memory_human']}</span>/{{if $info['maxmemory']}}{$info['maxmemory_human']}{{else}}{$info['total_system_memory_human']}{{endif}})</div>
		</div>
	</div>
{{endif}}
	<br>
	{$table|raw}

