<ips:template parameters="$updates" />
<a href='#supportPatchAvailable' data-ipsDialog data-ipsDialog-content='#supportPatchAvailable' data-ipsDialog-title='{lang="self_service"}'>{lang="health__patch_before_proceed"}</a>

<div class='ipsHide' id='supportPatchAvailable'>
	<div class='ipsPadding:double ipsType_large'>
		{template="patchAvailable" app="core" location="admin" group="support" params="$updates"}
	</div>
	<div class='ipsAreaBackground_light ipsClearfix ipsPadding ipsType_center'>
		<a href='{url="app=core&module=system&controller=upgrade&_new=1&patch=1"}' class="ipsButton ipsButton_veryLight">{lang="upgrade_apply_patch"}</a>
	</div>
</div>