<ips:template parameters="$wizard, $hooks, $redis=NULL" />
<div class="ipsColumns ipsColumns_collapsePhone ipsColumns_collapseTablet">
	<div class="ipsColumn ipsColumn_fluid">
		{$wizard|raw}
	</div>
	<div class="ipsColumn ipsColumn_veryWide">
		<div class="ipsBox ipsOverflow">
			<h2 class="ipsBox_titleBar">{lang="system_information"}</h2>
			<ul class='ipsDataList'>
                {{if !\IPS\CIC}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="php_version"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{lang="acp_version_number_raw" sprintf="PHP_VERSION"}<br>
						<a href="{url="app=core&module=support&controller=support&do=phpinfo"}" class="ipsType_small ipsType_light">phpinfo</a>
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="mysql_version"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{lang="acp_version_number_raw" sprintf="\IPS\Db::i()->server_info"}
						{{if \IPS\Member::loggedIn()->hasAcpRestriction( 'core', 'support', 'sql_toolbox' )}}
							<br>
							<a href="{url="app=core&module=support&controller=sql"}" class="ipsType_small ipsType_light">{lang="sql_toolbox"}</a>
							{{if settings.getFromConfGlobal('sql_utf8mb4') !== TRUE}}
								&middot; <a href="{url="app=core&module=support&controller=utf8mb4&_new=1"}" class="ipsType_small ipsType_light">{lang="enable_utf8mb4"}</a>
							{{endif}}
						{{endif}}
					</span>
				</li>
                {{endif}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="server_path"}</strong>
					</span>
					<span class="ipsDataItem_generic ipsType_small">
						{expression="\IPS\ROOT_PATH"}
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="server_ip"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$_SERVER['SERVER_ADDR']}
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="hooked_classes"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$hooks}<br>
						<a href="{url="app=core&module=support&controller=hookedFiles"}" class="ipsType_small ipsType_light">{lang="view"}</a>
					</span>
				</li>
				{{if $redis AND !\IPS\CIC}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="redis_info"} {{if isset( $redis['redis_version'] )}}{$redis['redis_version']}{{endif}}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{{if isset( $redis['used_memory_human'] )}}
							{{if isset( $redis['total_system_memory'] ) OR isset( $redis['maxmemory'] )}}
								{lang="redis_space_used" sprintf="$redis['used_memory_human'], $redis['maxmemory'] ? $redis['maxmemory_human'] : $redis['total_system_memory_human']"}
							{{else}}
								{lang="redis_space_used_nototal" sprintf="$redis['used_memory_human']"}
							{{endif}}
							<br>
							{{if isset( $redis['db0'] ) }}
								{{$data = explode( ',', $redis['db0'] );}}
								{{list($name, $count) = explode( '=', $data[0] );}}
								{lang="redis_key_count" sprintf="$count"}
								<br>
							{{endif}}
						{{endif}}
						<a href="{url="app=core&module=support&controller=redis"}" class="ipsType_small ipsType_light">{lang="view"}</a>
					</span>
				</li>
				{{endif}}
			</ul>
		</div>
		<br><br>
		<div class="ipsBox ipsOverflow">
			<h2 class="ipsBox_titleBar">{lang="diagnostic_logs"}</h2>
			<ul class='ipsDataList'>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic"><a href="{url="app=core&module=support&controller=errorLogs"}">{lang="error_logs"}</a></span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic"><a href="{url="app=core&module=support&controller=systemLogs"}">{lang="system_logs"}</a></span>
				</li>
			</ul>
		</div>
	</div>
</div>