<ips:template parameters="$entry, $email" />
<tr style='border-bottom: 1px solid #eeeeee'>
	<td dir='{dir}' width='40' align='center' valign='top' class=' '>
		<img src='{$entry->author()->get_photo( true, true )}' width='32' height='32' style='border: 1px solid #000; vertical-align: middle;'>
	</td>
	<td dir='{dir}' align='left'>
		<p style='font-family: "Helvetica Neue", helvetica, sans-serif; margin: 0; font-size: 13px; font-weight: bold'>
			{$email->language->addToStack("x_created_cms_in", FALSE, array( 'sprintf' => array( $entry->author()->name, $entry::database()->recordWord( 1 ), $entry->container()->getTitleForLanguage( $email->language ) ) ) )}
		</p>
		<h2 style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 18px; font-weight: 500 !important; margin: 0">
			<a href='{$entry->url()}' style='text-decoration: none;'>{$entry->_title}</a>
			{{if $entry->mapped('featured')}}&nbsp;&nbsp;<span style='color: #68a72f; font-weight: bold; font-size: 12px; text-transform: uppercase;'>{$email->language->addToStack("featured", FALSE)}</span>{{endif}}
		</h2>
		<div style='font-family: "Helvetica Neue", helvetica, sans-serif; line-height: 22px; margin-top: 10px; margin-bottom: 10px'>
			{$email->parseTextForEmail( $entry->content(), $email->language )|raw}
		</div>
	</td>
</tr>