<ips:template parameters="$image" />
<div data-controller='core.front.core.commentFeed, core.front.core.ignoredComments' {{if settings.auto_polling_enabled}}data-autoPoll{{endif}} data-baseURL='{$image->url()}' {{if $image->isLastPage()}}data-lastPage{{endif}} data-feedID='image-{$image->id}' id='comments'>
	{{if $image->commentPageCount() > 1}}
		{$image->commentPagination( array('tab') )|raw}
		<br><br>
	{{endif}}

	{template="featuredComments" group="global" app="gallery" params="$image->featuredComments(), $image->url()->setQueryString('tab', 'comments')->setQueryString('recommended', 'comments')"}
	{template="commentMultimodHeader" app="core" group="global" params="$image, '#comments'"}

	<div data-role='commentFeed' data-controller='core.front.core.moderation'>
		{{if \count( $image->comments( NULL, NULL, 'date', 'asc', NULL, NULL, NULL, NULL, FALSE, isset( \IPS\Request::i()->showDeleted ) ) )}}
			<form action="{$image->url()->csrf()->setQueryString( 'do', 'multimodComment' )->setPage('page',\IPS\Request::i()->page)}" method="post" data-ipsPageAction data-role='moderationTools'>
				{{$commentCount=0; $timeLastRead = $image->timeLastRead(); $lined = FALSE;}}
				{{foreach $image->comments( NULL, NULL, 'date', 'asc', NULL, NULL, NULL, NULL, FALSE, isset( \IPS\Request::i()->showDeleted ) ) as $comment}}
					{{if !$lined and $timeLastRead and $timeLastRead->getTimestamp() < $comment->mapped('date')}}
						{{if $lined = TRUE and $commentCount}}
							<hr class="ipsCommentUnreadSeperator">
						{{endif}}
					{{endif}}
					{{$commentCount++;}}
					{$comment->html()|raw}
				{{endforeach}}
				{template="commentMultimod" app="core" group="global" params="$image"}
			</form>
		{{else}}
			<p class='ipsType_normal ipsType_light ipsType_reset ipsPad' data-role='noComments'>{lang="no_comments"}</p>
		{{endif}}
	</div>			
	{{if $image->commentPageCount() > 1}}
		<hr class='ipsHr'>
		{$image->commentPagination( array('tab') )|raw}
	{{endif}}

	{{if $image->commentForm() || $image->locked() || \IPS\Member::loggedIn()->restrict_post || \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings'] || !\IPS\Member::loggedIn()->checkPostsPerDay()}}
	<a id='replyForm'></a>
	<div data-role='replyArea' class='{{if !$image->canComment()}}cTopicPostArea_noSize{{endif}} ipsSpacer_top'>
		{{if $image->commentForm()}}
			{{if $image->locked()}}
				<p class='ipsType_reset ipsType_warning ipsComposeArea_warning ipsSpacer_bottom ipsSpacer_half'><i class='fa fa-info-circle'></i> {lang="image_locked_can_comment"}</p>
			{{endif}}
				{$image->commentForm()|raw}
			{{else}}
			{{if $image->locked()}}
				{template="commentUnavailable" group="forms" location="front" app="gallery" params="'image_locked_cannot_comment'"}
			{{elseif \IPS\Member::loggedIn()->restrict_post}}
				{template="commentUnavailable" group="forms" location="front" app="gallery" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
			{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
				{template="commentUnavailable" group="forms" location="front" app="gallery" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
			{{elseif !\IPS\Member::loggedIn()->checkPostsPerDay()}}
				{template="commentUnavailable" group="forms" location="front" app="gallery" params="'member_exceeded_posts_per_day'"}
			{{endif}}
		{{endif}}
	</div>
	{{endif}}
</div>
