<ips:template parameters="$image, $commentsAndReviews=FALSE" />

<div data-controller='gallery.front.view.image' class='cGalleryLightbox' data-role='lightbox'>
	<div class='cGalleryLightbox_inner' data-role="imageSizer">
		<div class='elGalleryHeader' class='cGalleryLightbox_image'>
			{template="imageLightboxFrame" group="view" app="gallery" params="$image"}
		</div>

		<div class='cGalleryLightbox_info ipsAreaBackground_reset'>
			<section data-role='imageInfo'>
				{template="imageLightboxInfo" group="view" params="$image, $commentsAndReviews"}	
			</section>
		</div>
	</div>
</div> 