<ips:template parameters="$image, $commentsAndReviews=FALSE" />

{{if $club = $image->container()->club()}}
	{{if settings.clubs and settings.clubs_header == 'full'}}
		{template="header" app="core" group="clubs" params="$club, $image->container()"}
	{{endif}}
	<div id='elClubContainer'>
{{endif}}

<div data-controller='gallery.front.view.image{{if settings.gallery_nsfw}},gallery.front.global.nsfw{{endif}}' data-lightboxURL='{$image->url()}'>
	<div class='ipsColumns ipsMargin_bottom'>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='cGalleryLightbox_inner' data-role="imageSizer">
				<div class='elGalleryHeader'>
					{template="imageFrame" group="view" app="gallery" params="$image"}
				</div>
			</div>
            {{if $image->hasPreviousOrNext() }}
            {{$prev = array_reverse( array_slice( $image->fetchNextOrPreviousImages( 9, 'ASC' ), 0, 4 ) );}}
            {{$next = $image->fetchNextOrPreviousImages( 9, 'DESC' );}}
			<div class='cGalleryImageThumbs'>
				<ol class='cGalleryCarousel' id='gallery-image-thumbs'>
                    {{$counter = 1;}}
					{{foreach $prev as $id => $carouselImage}}
			            <li class='cGalleryCarousel__item'>
			            	<div class='ipsImageBlock'>
				                {{if $carouselImage->media }}
					                <a href='{$carouselImage->url()}' title='{lang="view_this_video" sprintf="$carouselImage->caption"}' class='ipsImageBlock__main'>
					                    <video data-role="video" preload="metadata" loading="lazy"{{if $carouselImage->masked_file_name }} poster="{file="$carouselImage->masked_file_name" extension="gallery_Images"}"{{endif}}>
					                        <source src="{file="$carouselImage->original_file_name" extension="gallery_Images"}{{if !$carouselImage->masked_file_name }}#t=1{{endif}}" type='{$carouselImage->file_type}' />
					                    </video>
					                </a>
				                {{else}}
					                <a href='{$carouselImage->url()}' title='{lang="view_this_image" sprintf="$carouselImage->caption"}' class='ipsImageBlock__main'>
					                	<img src='{file="$carouselImage->small_file_name" extension="gallery_Images"}' alt="{$carouselImage->caption}" loading="lazy">
					                </a>
				                {{endif}}
                            	{template="nsfwOverlay" app="gallery" location="front" group="global" params="$carouselImage, FALSE"}
                            </div>
                        </li>
                        {{$counter++;}}
			        {{endforeach}}

                    <li class='cGalleryCarousel__item cGalleryCarousel__item--active'>
                    	<div class='ipsImageBlock'>
	                        {{if $image->media }}
	                            <a href='{$image->url()}' title='{lang="view_this_video" sprintf="$image->caption"}' class='ipsImageBlock__main'>
	                                <video data-role="video" loading="lazy" {{if $image->masked_file_name }} poster="{file="$image->masked_file_name" extension="gallery_Images"}"{{else}} preload="metadata"{{endif}}>
	                                    <source src="{file="$image->original_file_name" extension="gallery_Images"}{{if !$image->masked_file_name }}#t=1{{endif}}" type='{$image->file_type}' />
	                                </video>
	                            </a>
	                        {{else}}
	                            <a href='{$image->url()}' title='{lang="view_this_image" sprintf="$image->caption"}' class='ipsImageBlock__main'>
	                                <img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
	                            </a>
                        	{{endif}}
                        	{template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
                        </div>
                        {{$counter++;}}
                    </li>

                    {{foreach $next as $id => $carouselImage}}
                        <li class='cGalleryCarousel__item'>
                        	<div class='ipsImageBlock'>
	                            {{if $carouselImage->media }}
	                                <a href='{$carouselImage->url()}' title='{lang="view_this_video" sprintf="$carouselImage->caption"}' class='ipsImageBlock__main'>
	                                    <video data-role="video" preload="metadata" loading="lazy" {{if $carouselImage->masked_file_name }} poster="{file="$carouselImage->masked_file_name" extension="gallery_Images"}"{{endif}}>
	                                        <source src="{file="$carouselImage->original_file_name" extension="gallery_Images"}{{if !$carouselImage->masked_file_name }}#t=1{{endif}}" type='{$carouselImage->file_type}' />
	                                    </video>
	                                </a>
	                            {{else}}
	                                <a href='{$carouselImage->url()}' title='{lang="view_this_image" sprintf="$carouselImage->caption"}' class='ipsImageBlock__main'>
	                                    <img src='{file="$carouselImage->small_file_name" extension="gallery_Images"}' alt="{$carouselImage->caption}" loading="lazy">
	                                </a>
	                            {{endif}}
	                            {template="nsfwOverlay" app="gallery" location="front" group="global" params="$carouselImage, FALSE"}
	                        </div>
                        </li>
                        {{$counter++;}}
                        {{if $counter == 10}}
                            {{break;}}
                        {{endif}}
                    {{endforeach}}
				</ol>
                <div class='cGalleryCarouselNav cGalleryCarouselNav--overlay' data-carousel-controls='gallery-image-thumbs' data-controller="gallery.front.browse.carousel" hidden>
                    <button class='cGalleryCarouselNav__button' data-carousel-arrow='prev' aria-label='Previous' role='button'>
                        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" width="10"><path d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z"/></svg>
                    </button>
                    <button class='cGalleryCarouselNav__button' data-carousel-arrow='next' aria-label='Next' role='button'>
                        <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" width="10"><path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/></svg>
                    </button>
                </div>
			</div>
            {{endif}}
		</div>
	</div>

	<section data-role='imageInfo'>
		{template="imageInfo" group="view" params="$image"}
	</section>

	<div data-role='imageComments'>
	{{if $commentsAndReviews}}
		<br>
		{{if ( $image->directContainer()->allow_reviews && $image->container()->allow_reviews ) && ( $image->directContainer()->allow_comments && $image->container()->allow_comments ) }}
			<a id="replies"></a>
			<h2 class='ipsHide'>{lang="user_feedback"}</h2>
		{{endif}}
		{$commentsAndReviews|raw}
	{{endif}}
	</div>

</div> 

{{if $image->container()->club()}}
	</div>
{{endif}}