<ips:template parameters="$image" />

<div id='elGalleryImage' class='elGalleryImage' data-role="imageFrame" {{if $image->data}}data-imageSizes='{$image->data}'{{endif}}>
	{{if $image->media }}
		<div class='cGallery_videoContainer'>
			<video data-controller="core.global.core.embeddedvideo" id="elGalleryVideo" data-role="video" class="ipsPos_center" controls preload="auto" width="100%" height="100%"{{if $image->masked_file_name }} poster="{file="$image->masked_file_name" extension="gallery_Images"}"{{endif}}>
				<source src="{file="$image->original_file_name" extension="gallery_Images"}" type='{$image->file_type}' />
				<embed wmode="opaque" autoplay="true" showcontrols="true" showstatusbar="true" showtracker="true" src="{file="$image->original_file_name" extension="gallery_Images"}" width="480" height="360" type='{$image->file_type}' />
			</video>
		</div>
	{{else}}
		<div class='cGalleryViewImage' data-role='notesWrapper' data-controller='gallery.front.view.notes' data-imageID='{$image->id}' {{if $image->canEdit()}}data-editable{{endif}} data-notesData='{$image->_notes_json}'>
			
			<div>
				<img src='{file="$image->masked_file_name" extension="gallery_Images"}' alt="{$image->caption}" title='{$image->caption}' data-role='theImage' class='ipsHide'>
			</div>
			<noscript>
				<img src='{file="$image->masked_file_name" extension="gallery_Images"}' alt="{$image->caption}" title='{$image->caption}' data-role='theImage'>
			</noscript>
			{{if \count( $image->_notes )}}
				<noscript>
					{{foreach $image->_notes as $note}}
						<div class='cGalleryNote' style='left: {$note['LEFT']}%; top: {$note['TOP']}%; width: {$note['WIDTH']}%; height: {$note['HEIGHT']}%'>
							<div class='cGalleryNote_border'></div>
							<div class='cGalleryNote_note'><div>{$note['NOTE']}</div></div>
						</div>
					{{endforeach}}
				</noscript>
			{{endif}}
		</div>
		
		<div class='cGalleryImageFade'>
			{{if !$image->media }}
				<div class='cGalleryImageTopBar'>
					<div class='cGalleryImageTitle'>&nbsp;</div>
					<ul class='cGalleryControls ipsList_inline'>
						<li>
							<a href='{$image->url()}' title='{lang="view_in_lightbox"}' class='ipsButton ipsButton_narrow ipsButton_link ipsButton_verySmall ipsButton_veryLight' data-ipsTooltip data-imageLightbox><i class='fa fa-expand'></i></a>
						</li>
						<li>
							<a href='{file="$image->masked_file_name" extension="gallery_Images"}' title='{lang="view_fullsize_image"}' class='ipsButton ipsButton_narrow ipsButton_link ipsButton_verySmall ipsButton_veryLight' data-ipsTooltip target='_blank' rel='noopener'><i class='fa fa-external-link'></i></a>
						</li>
					</ul>
				</div>
			{{endif}}
			<div class='cGalleryImageBottomBar'>
				<div class='cGalleryCreditInfo ipsType_normal'>
					{{if $image->copyright}}
						<div>
							&copy; {$image->copyright}
						</div>
					{{endif}}

					{{if $image->credit_info}}
						<div>
							<strong>{lang="image_credit_info"}</strong> {$image->credit_info}
						</div>
					{{endif}}
				</div>
				{{if $image->canEdit() OR $image->canDownloadOriginal() OR \IPS\Member::loggedIn()->member_id}}
					<ul class='ipsList_inline'>
						<li>
							<a href='#' data-ipsMenu data-ipsMenu-above='true' id='elImageTools' class='ipsButton ipsButton_link ipsButton_verySmall ipsJS_show cGalleryViewImage_controls'>{lang="image_tools"} <i class='fa fa-caret-down'></i></a>
						</li>
					</ul>
					<ul class='ipsMenu ipsMenu_auto ipsHide' id='elImageTools_menu'>
						{{if $image->canEdit()}}
							<li class='ipsMenu_item ipsResponsive_hidePhone'><a href='#' title='{lang="add_image_note"}' data-action='addNote'>
								<i class='fa fa-fw fa-pencil-square-o'></i> {lang="add_image_note"}</a>
							</li>
							{{if !$image->media}}
								<li class='ipsMenu_item ipsMenu_subItems'>
									<a href='#' title='{lang="rotate_image"}' id='elImage_rotate' data-ipsMenu data-ipsMenu-appendTo='#elGalleryImage'>
										<i class='fa fa-fw fa-rotate-right'></i> {lang="rotate_image"}
									</a>
									<ul class='ipsMenu ipsMenu_auto ipsHide' id='elImage_rotate_menu'>
										<li class='ipsMenu_item'>
											<a href='{$image->url( 'rotate' )->csrf()->setQueryString( 'direction', 'right' )}' title='{lang="rotate_right"}'>
												<i class='fa fa-fw fa-rotate-right'></i> &nbsp;{lang="rotate_right"}
											</a>
										</li>
										<li class='ipsMenu_item'>
											<a href='{$image->url( 'rotate' )->csrf()->setQueryString( 'direction', 'left' )}' title="{lang="rotate_left"}">
												<i class='fa fa-fw fa-rotate-left'></i> &nbsp;{lang="rotate_left"}
											</a>
										</li>
									</ul>
								</li>
							{{endif}}
						{{endif}}
						{{if \IPS\Member::loggedIn()->member_id}}
							<li class='ipsMenu_item{{if $image->canSetAsAlbumCover() OR $image->canSetAsCategoryCover()}} ipsMenu_subItems{{endif}}'>
								{{if $image->canSetAsAlbumCover() OR $image->canSetAsCategoryCover()}}
									<a href='#' title='{lang="set_image_as"}' id='elImageSetAs' data-ipsMenu data-ipsMenu-appendTo='#elGalleryImage'>
										<i class='fa fa-fw fa-object-group'></i> {lang="set_image_as"}
									</a>
									<ul class='ipsMenu ipsMenu_auto ipsHide' id='elImageSetAs_menu'>
										{{if $image->canSetAsAlbumCover() AND $image->canSetAsCategoryCover()}}
											<li class='ipsMenu_item'><a data-action='setAsCover' href='{$image->url()->setQueryString( 'do', 'cover' )->setQueryString( 'set', 'category')->csrf()}'>{lang="cover_category_only"}</a></li>
											<li class='ipsMenu_item'><a data-action='setAsCover' href='{$image->url()->setQueryString( 'do', 'cover' )->setQueryString( 'set', 'album')->csrf()}'>{lang="cover_album_only"}</a></li>
											<li class='ipsMenu_item'><a data-action='setAsCover' href='{$image->url()->setQueryString( 'do', 'cover' )->setQueryString( 'set', 'both')->csrf()}'>{lang="cover_both"}</a></li>
										{{elseif $image->canSetAsCategoryCover()}}
											<li class='ipsMenu_item'><a data-action='setAsCover' href='{$image->url()->setQueryString( 'do', 'cover' )->setQueryString( 'set', 'category')->csrf()}'>{lang="cover_category"}</a></li>
										{{elseif $image->canSetAsAlbumCover()}}
											<li class='ipsMenu_item'><a data-action='setAsCover' href='{$image->url()->setQueryString( 'do', 'cover' )->setQueryString( 'set', 'album')->csrf()}'>{lang="cover_album"}</a></li>
										{{endif}}
										{{if \IPS\Member::loggedIn()->member_id}}
											<li class='ipsMenu_sep'><hr></li>
											<li class='ipsMenu_item'>
												<a href='{$image->url('setAsPhoto')->csrf()}' data-action='setAsProfile' title="{lang="set_gallery_image_photo"}">{lang="set_gallery_image_photo"}</a>
											</li>
										{{endif}}
									</ul>
								{{elseif \IPS\Member::loggedIn()->member_id}}
									<a href='{$image->url('setAsPhoto')->csrf()}' title='{lang="set_gallery_image_photo"}'>
										{lang="set_gallery_image_photo"}
									</a>
								{{endif}}
							</li>
						{{endif}}
						{{if $image->canDownloadOriginal()}}
							<li class='ipsMenu_item'>
								<a href='{$image->url('download')}' title='{lang="download"}'><i class='fa fa-fw fa-download'></i> {lang="download"}</a>
							</li>
						{{endif}}
					</ul>
				{{endif}}
			</div>
		</div>
	{{endif}}
	<span class='elGalleryImageNav'>
		{{if $prev = $image->prevItem()}}
			<a href='{$prev->url()->setQueryString( 'browse', 1 )}' class='elGalleryImageNav_prev' title='{$prev->caption}'><i class='fa fa-angle-left'></i></a>
		{{endif}}
		{{if $next = $image->nextItem()}}
			<a href='{$next->url()->setQueryString( 'browse', 1 )}' class='elGalleryImageNav_next' title='{$next->caption}'><i class='fa fa-angle-right'></i></a>
		{{endif}}
	</span>
</div>