<ips:template parameters="$package, $price, $active, $inactive" />
<div class="ipsPos_right ipsTree_row_cells">
	<span class="ipsTree_row_cell ipsType_light"><a href="{url="app=nexus&module=subscriptions&controller=subscribers&advanced_search_submitted=1&nexus_sub_package_id={$package->id}&filter=nexus_subs_filter_active" csrf="true"}">{lang="nexus_sub_package_count_active" sprintf="$active"}</a></span>
	<span class="ipsTree_row_cell ipsType_light"><a href="{url="app=nexus&module=subscriptions&controller=subscribers&advanced_search_submitted=1&nexus_sub_package_id={$package->id}&filter=nexus_subs_filter_inactive" csrf="true"}">{lang="nexus_sub_package_count_inactive" sprintf="$inactive"}</a></span>
	<span class="ipsTree_row_cell ipsType_light">{$price}</span>
</div>