<ips:template parameters="$output, $pageHeader, $calendar=NULL" />

{{if $calendar and $club = $calendar->club()}}
	{{if settings.clubs and settings.clubs_header == 'full'}}
		{template="header" app="core" group="clubs" params="$club, $calendar"}
	{{endif}}
{{endif}}

{template="pageHeader" group="global" app="core" params="$pageHeader"}

{{if isset( \IPS\Request::i()->do ) and \IPS\Request::i()->do === 'livetopic'}}
<div class="ipsMargin_top ipsMargin_bottom">{lang="ai_service_livetopics_desc"}</div>
{{endif}}

{$output|raw}