<ips:template parameters="$field, $nodeSelect" />

<div class='cNexusStack cNexusStack_usergroup'>
	<ol class='ipsList_reset'>
		<li data-step='{lang="discount_if"}'>
			<strong class='ipsType_medium'>{lang="discount_purchasing"}</strong><br>
			<input type="number" name="{$field->name}[buying]" class="ipsField_short ipsField_stackItemNoMargin" name="{$field->name}[buying]" {{if \is_array( $field->value )}}value="{$field->value['buying']}"{{endif}}>
		</li>
		<li data-step='{lang="discount_of"}'>
			<input type="radio" name="{$field->name}[this]" id="{$field->name}_this_this" value="1" {{if !\is_array( $field->value ) or !$field->value['package']}}checked{{endif}} > <label for="{$field->name}_this_this">&nbsp;<strong class='ipsType_medium'>{lang="discount_this_product"}</strong></label><br>
			<input type="radio" name="{$field->name}[this]" id="{$field->name}_this_other" value="0" data-control='toggle' data-toggles='p_bulk_discounts_nodeSelect{$field->htmlId}' {{if \is_array( $field->value ) and $field->value['package']}}checked{{endif}} > <label for="{$field->name}_this_other">&nbsp;<strong class='ipsType_medium'>{lang="discount_different_product"}</strong></label><br>
			<div id="p_bulk_discounts_nodeSelect{$field->htmlId}">
				{$nodeSelect|raw}
			</div>
		</li>
		<li data-step='{lang="discount_then"}'>
			<strong class='ipsType_medium'>{lang="discount_price_becomes"}</strong><br>
			<ul class='ipsList_reset'>
				{{foreach \IPS\nexus\Money::currencies() as $currency}}
					<li>
						<input type="number" class="ipsField_short ipsField_stackItemNoMargin" name="{$field->name}[price][{$currency}]" {{if \is_array( $field->value )}}value="{$field->value['price'][$currency]}"{{endif}} data-decimals="2" data-decpoint="{expression="\IPS\Member::loggedIn()->language()->locale['decimal_point']"}" data-thousandsseparator="{expression="\IPS\Member::loggedIn()->language()->locale['thousands_sep']"}" step="0.01"> {$currency}
					</li>
				{{endforeach}}
			</ul>
			<br>
			{lang="discount_price_becomes_once"}
		</li>
	</ol>
</div>
