<ips:template parameters="$package, $active, $expiredRenewable, $expredNonRenewable, $canceledCanBeReactivated, $canceledCannotBeReactivated, $upgradeTo" />
<p class="ipsMessage ipsMessage_error ipsType_large">{lang="product_delete_blurb"}</p>
<div class="ipsBox">
	<h2 class="ipsBox_titleBar">
		{lang="product_delete_review"}
	</h2>
	<div class="ipsPad">
		<p class="ipsType_normal ipsType_reset">{lang="product_delete_review_desc"}</p>
		<ul class="ipsDataList ipsSpacer_top">
			<li class="ipsDataItem">
				{{if $active}}
					<div class="ipsDataItem_icon ipsType_warning ipsPos_top ipsType_large"><i class="fa fa-times"></i></div>
					<div class="ipsDataItem_generic ipsType_warning">
				{{else}}
					<div class="ipsDataItem_icon ipsType_success ipsPos_top ipsType_large"><i class="fa fa-check"></i></div>
					<div class="ipsDataItem_generic ipsType_success">
				{{endif}}
					{{if $expiredRenewable or $expredNonRenewable or $package->renew_options}}
						{lang="product_count_active" pluralize="$active"}
					{{else}}
						{lang="product_count_purchases" pluralize="$active"}
					{{endif}}
				</div>
			</li>
			{{if $expiredRenewable or $expredNonRenewable}}
				<li class="ipsDataItem">
					{{if $expiredRenewable}}
						<div class="ipsDataItem_icon ipsType_warning ipsPos_top ipsType_large"><i class="fa fa-times"></i></div>
						<div class="ipsDataItem_generic ipsType_warning">
					{{else}}
						<div class="ipsDataItem_icon ipsType_success ipsPos_top ipsType_large"><i class="fa fa-check"></i></div>
						<div class="ipsDataItem_generic ipsType_success">
					{{endif}}
					{lang="product_count_expired_split" pluralize="$expiredRenewable, $expredNonRenewable"}
					</div>
				</li>
			{{endif}}
			{{if $canceledCanBeReactivated or $canceledCannotBeReactivated}}
				<li class="ipsDataItem">
					{{if $canceledCanBeReactivated}}
						<div class="ipsDataItem_icon ipsType_warning ipsPos_top ipsType_large"><i class="fa fa-times"></i></div>
						<div class="ipsDataItem_generic ipsType_warning">
					{{else}}
						<div class="ipsDataItem_icon ipsType_success ipsPos_top ipsType_large"><i class="fa fa-check"></i></div>
						<div class="ipsDataItem_generic ipsType_success">
					{{endif}}
					{lang="product_count_canceled_split" pluralize="$canceledCanBeReactivated, $canceledCannotBeReactivated"}
					</div>
				</li>
			{{endif}}
		</ul>
		<div class="ipsSpacer_top">
			<a href="{url="app=nexus&module=store&controller=packages&do=massManagePurchases&id={$package->_id}"}" class="ipsButton ipsButton_primary" data-ipsDialog data-ipsDialog-title="{$package->_title}">{lang="mass_change_all_purchases"}</a>
			<a href="{url="app=nexus&module=store&controller=packages&do=viewPurchases&id={$package->_id}"}" class="ipsButton ipsButton_secondary">{lang="view_purchases"}</a>
		</div>
		<p class="ipsType_normal ipsType_reset ipsSpacer_top">{lang="product_delete_review_complete"}</p>
	</div>
</div>
<div class="ipsBox ipsSpacer_top">
	<h2 class="ipsBox_titleBar">
		{lang="product_delete_hide"}
	</h2>
	<div class="ipsPad">
		<p class="ipsType_normal ipsType_reset">{lang="product_delete_hide_desc"}</p>
		<ul class="ipsDataList ipsSpacer_top">
			<li class="ipsDataItem">
				{{if $package->store}}
					<div class="ipsDataItem_icon ipsType_warning ipsPos_top ipsType_large"><i class="fa fa-times"></i></div>
					<div class="ipsDataItem_generic ipsType_warning">
				{{else}}
					<div class="ipsDataItem_icon ipsType_success ipsPos_top ipsType_large"><i class="fa fa-check"></i></div>
					<div class="ipsDataItem_generic ipsType_success">
				{{endif}}
					{lang="product_delete_hide_1"}
				</div>
			</li>
			<li class="ipsDataItem">
				{{if $package->reg}}
					<div class="ipsDataItem_icon ipsType_warning ipsPos_top ipsType_large"><i class="fa fa-times"></i></div>
					<div class="ipsDataItem_generic ipsType_warning">
				{{else}}
					<div class="ipsDataItem_icon ipsType_success ipsPos_top ipsType_large"><i class="fa fa-check"></i></div>
					<div class="ipsDataItem_generic ipsType_success">
				{{endif}}
					{lang="product_delete_hide_2"}
				</div>
			</li>
			<li class="ipsDataItem">
				{{if $upgradeTo}}
					<div class="ipsDataItem_icon ipsType_warning ipsPos_top ipsType_large"><i class="fa fa-times"></i></div>
					<div class="ipsDataItem_generic ipsType_warning">
				{{else}}
					<div class="ipsDataItem_icon ipsType_success ipsPos_top ipsType_large"><i class="fa fa-check"></i></div>
					<div class="ipsDataItem_generic ipsType_success">
				{{endif}}
					{lang="product_delete_hide_3"}
				</div>
			</li>
		</ul>
		<div class="ipsSpacer_top">
			<a href="{url="app=nexus&module=store&controller=packages&subnode=1&do=form&id={$package->_id}"}" target="_blank" class="ipsButton ipsButton_primary">{lang="product_delete_edit"}</a>
		</div>
	</div>
</div>