<ips:template parameters="$type, $item" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	<div class='ipsType_center ipsType_light ipsPadding'>
		<i class='fa fa-frown-o ipsType_veryLarge ipsType_light'></i>
		<p class='ipsType_reset ipsType_normal ipsPad'>
			{lang="embed_comment_unavailable_desc" sprintf="$type, $item->url(), $item->title"}
		</p>
	</div>
</div>