<ips:template parameters="$result, $title, $orientation='vertical'" />

{{if $title}}
<h3 class="ipsType_reset ipsWidget_title">{$title}</h3>
{{endif}}
<div class='ipsWidget_inner'>
	<ul class='ipsDataList ipsDataList_reducedSpacing'>
		{{foreach $result as $row}}
			<li class='ipsDataItem'>
				{{if $row['type'] === 'badge'}}
					<div class='ipsDataItem_icon ipsPos_top'>
						<div class='ipsPos_relative'>
							<div class='cAchievementsWidget__badge'>{$row['badge']->html('ipsDimension:4')|raw}</div>
							<div class='cAchievementsWidget__photo'>
								{template="userPhoto" app="core" group="global" params="$row['member'], 'tinier', '', 'ipsOutline'"}
							</div>
						</div>
					</div>
					<div class='ipsDataItem_main ipsPadding_left:half'>
						{lang="block_achievements_earned_badge" htmlsprintf="$row['member']->link()"}<br>						
						<strong {{if ! empty( $row['badge']->awardDescription )}}title="{$row['badge']->awardDescription}" data-ipsTooltip{{endif}}>{$row['badge']->_title}</strong><br>
						<span class="ipsType_light">{datetime="$row['date']"}</span>
					</div>
				{{else}}
					<div class='ipsDataItem_icon ipsPos_top'>
						<div class='ipsPos_relative'>
							<div class='cAchievementsWidget__badge'>{$row['rank']->html('ipsDimension:4')|raw}</div>
							<div class='cAchievementsWidget__photo'>
								{template="userPhoto" app="core" group="global" params="$row['member'], 'tinier', '', 'ipsOutline'"}
							</div>
						</div>
					</div>
					<div class='ipsDataItem_main ipsPadding_left:half'>
						{lang="block_achievements_earned_rank" htmlsprintf="$row['member']->link()"}<br>
						<strong>{$row['rank']->_title}</strong><br>
						<span class="ipsType_light">{datetime="$row['date']"}</span>
					</div>
				{{endif}}
			</li>
		{{endforeach}}
	</ul>
</div>