<ips:template parameters="$members, $memberCount, $guests, $anonymous, $orientation='vertical'" />
<div data-controller='core.front.core.onlineUsersWidget'>
    <h3 class='ipsType_reset ipsWidget_title'>
        <span class='ipsFlex ipsFlex-jc:between ipsFlex-fw:wrap ipsFlex-ai:center'>
            <span>
                {lang="block_whosOnline"}
                {{if $orientation == 'horizontal'}}
                    &nbsp;&nbsp;<span class='ipsType_light ipsType_unbold ipsType_medium'><span data-memberCount="{$memberCount}">{lang="block_whos_online_info_members" pluralize="$memberCount"}</span>, {lang="block_whos_online_info_anonymous" pluralize="$anonymous"}, {lang="block_whos_online_info_guests" pluralize="$guests"}</span>
                {{endif}}
            </span>
            <span class='ipsType_medium ipsType_light ipsType_unbold ipsType_blendLinks'><a href='{url="app=core&module=online&controller=online" seoTemplate="online"}'>{lang="see_full_list"}</a></span>
        </span>
    </h3>
    <div class='ipsWidget_inner ipsPadding'>
        <ul class='ipsList_inline ipsList_csv ipsList_noSpacing ipsType_normal'>
            {{if $memberCount}}
                {{foreach $members as $row}}
                    <li data-memberId="{$row['member_id']}">{template="userLinkFromData" group="global" app="core" params="$row['member_id'], $row['member_name'], $row['seo_name'], $row['member_group'], TRUE"}</li>
                {{endforeach}}
            {{else}}
                <li class='ipsType_reset ipsType_medium ipsType_light' data-noneOnline>{lang="whos_online_users_empty"}</li>
            {{endif}}
        </ul>
        {{if $orientation == 'vertical' and $memberCount > 60}}
            <p class='ipsType_medium ipsType_reset'>
                <a href='{url="app=core&module=online&controller=online" seoTemplate="online"}'>{lang="and_x_others" pluralize="$memberCount - 60"}</a>
            </p>
        {{endif}}
    </div>
</div>