<ips:template parameters="$item, $url, $image=NULL" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$item, $item->mapped('title'), $item->mapped('date'), $url"}
	{{if $item->primary_screenshot_thumb}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg cFileEmbed ipsType_center'>
			<a href='{$url}' title='{$item->mapped('title')}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image->url )"}") '>
				<img src='{$image->url}' alt="{$item->mapped('title')}" class='ipsHide'>
			</a>
		</div>
	{{endif}}
	<div class='ipsPadding ipsClearfix'>
		{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
			<ul class='ipsList_inline ipsType_normal'>
				<li class='cFilePrice'>
					{{if $item->isPaid()}}
						{$item->price()|raw}
					{{else}}
						{lang="file_free"}
					{{endif}}
				</li>
				{{if $renewalTerm = $item->renewalTerm()}}
					<li class='ipsType_light'>
						{lang="file_renewal_term_val" sprintf="$renewalTerm"}
					</li>
				{{endif}}
			</ul>
		{{endif}}
		{{if $item->container()->version_numbers OR ($item->isPaid() and \in_array( 'purchases', explode( ',', settings.idm_nexus_display ) )) OR (!$item->isPaid() or \in_array( 'downloads', explode( ',', settings.idm_nexus_display ) ))}}
		<ul class='ipsList_inline'>
			{{if $item->container()->version_numbers}} <li><i class='fa fa-info-circle'></i> {lang="version"} {$item->version}</li>{{endif}}
			{{if $item->isPaid() and \in_array( 'purchases', explode( ',', settings.idm_nexus_display ) )}}
				<li {{if !$item->purchaseCount()}}class='ipsType_light'{{endif}}><i class='fa fa-shopping-cart'></i> {lang="x_purchases" pluralize="$item->purchaseCount()"}</li>
			{{endif}}
			{{if !$item->isPaid() or \in_array( 'downloads', explode( ',', settings.idm_nexus_display ) )}}
				<li {{if !$item->downloads}}class='ipsType_light'{{endif}}><i class='fa fa-arrow-circle-down'></i> {lang="num_downloads" pluralize="$item->downloads"}</li>
			{{endif}}
		</ul>
		{{endif}}
		{{if \IPS\Member::loggedIn()->member_id}}
			<div class='ipsSpacer_top ipsSpacer_half'>
				{{if $item->canBuy() AND $item->isPurchasable()}}
					{{if $item->canDownload()}}
						<a href='{{if settings.idm_antileech AND !$item->requiresDownloadConfirmation()}}{$item->url('download')->csrf()}{{else}}{$item->url('download')}{{endif}}' class='ipsButton ipsButton_fullWidth ipsButton_small ipsButton_primary' {{if $item->requiresDownloadConfirmation()}}data-dialog{{endif}}>{lang="download_now"}</a>
					{{else}}
						<a href='{$item->url('buy')->csrf()}' class='ipsButton ipsButton_fullWidth ipsButton_small ipsButton_primary'><i class='fa fa-shopping-cart'></i> &nbsp;{lang="buy_now"}{{if $price = $item->price()}} - {$price|raw}{{endif}}</a>
					{{endif}}
				{{elseif $item->isPaid() AND !$item->isPurchasable( FALSE )}}
					{lang="purchasing_disabled"}
				{{else}}
					{{if $item->canDownload() or !$item->downloadTeaser()}}
						<a href='{{if settings.idm_antileech AND !$item->requiresDownloadConfirmation()}}{$item->url('download')->csrf()}{{else}}{$item->url('download')}{{endif}}' class='ipsButton ipsButton_fullWidth ipsButton_small ipsButton_primary' {{if $item->requiresDownloadConfirmation()}}data-dialog{{endif}}>{lang="download_now"}</a>
					{{else}}
						<span class="ipsButton ipsButton_light ipsButton_fullWidth ipsButton_small ipsButton_disable">{lang="download_teaser"}</span>
					{{endif}}
				{{endif}}
			</div>
		{{endif}}
		<hr class='ipsHr'>

		<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='2'>
			{$item->truncated(TRUE)|raw}
		</div>

		{template="embedItemStats" group="embed" app="core" params="$item, $item->container()->bitoptions['comments']"}
	</div>
</div>