<ips:template parameters="$indexData, $itemData, $screenshot, $url, $price, $condensed" />
{{if $condensed}}
	{{if $screenshot}}
		<span data-ipsLazyLoad class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{file="$screenshot" extension="downloads_Screenshots"}"{{else}}style='background-image: url({file="$screenshot" extension="downloads_Screenshots"})'{{endif}}>
			{{if settings.lazy_load_enabled}}
				<img src='{expression="\IPS\Text\Parser::blankImage()"}' data-src='{file="$screenshot" extension="downloads_Screenshots"}' alt='{lang="idm_screenshot_for" sprintf="$indexData['index_title']"}'>
			{{else}}
				<img src='{file="$screenshot" extension="downloads_Screenshots"}' alt='{lang="idm_screenshot_for" sprintf="$indexData['index_title']"}'>
			{{endif}}
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsStreamItem_columns'>
		<div class='ipsStreamItem_columns__thumb' data-ipsLazyLoad>
			<a href='{$url}'>
				{{if $screenshot}}
					{template="thumbImage" group="global" app="core" location="front" params="$screenshot, $indexData['index_title'], 'large', '', 'view_this', NULL, 'downloads_Screenshots', '', true"}
				{{else}}
					<div class='ipsNoThumb ipsThumb_small'></div>
				{{endif}}
			</a>
		</div>
		<div class='ipsStreamItem_columns__content'>
			{{if $itemData['file_version']}}<p class='ipsType_reset ipsType_light ipsType_normal'>{lang="version"} {$itemData['file_version']}</p>{{endif}}
			{{if !$price or \in_array( 'downloads', explode( ',', settings.idm_nexus_display ) ) }}
				<p class='ipsType_reset ipsType_normal'><i class='fa fa-download'></i> {lang="num_downloads" pluralize="$itemData['file_downloads']"}</p>
			{{endif}}

			
			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsSpacer_top ipsSpacer_half ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
					{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
				</div>
			{{endif}}
			
			{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
				<div class='ipsType_large ipsType_reset ipsSpacer_top ipsSpacer_half'>
					<div class='ipsStream_price'>
						<span class="cNexusPrice">
							{{if $price}}
								{$price|raw}
							{{else}}
								{lang="file_free"}
							{{endif}}
						</span>
					</div>
				</div>
			{{endif}}
		</div>
	</div>
{{endif}}