<ips:template parameters="$record, $database, $id" />
{{$size = ( $id ) ? 'tiny' : 'small';}}
<li class='{{if $id}}ipsGrid_span6{{else}}ipsGrid_span12{{endif}}'>
	<article class='cCmsCategoryFeaturedEntry ipsBox ipsPadding {{if $record->hidden()}}ipsModerated{{endif}}'>
		<header class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_{$size} ipsSpacer_bottom'>
			{template="userPhoto" app="core" params="$record->author(), $size" group="global"}
			<div> 
				<h2 class='ipsType_pageTitle ipsContained_container'>
					{{if $record->prefix()}}
						<span>{template="prefix" group="global" app="core" params="$record->prefix( TRUE ), $record->prefix()"}</span>
					{{endif}}
					{{if $record->isFutureDate() || $record->mapped('pinned') || $record->mapped('featured') || $record->hidden() === -1 || $record->hidden() === 1}}
						<span>
							{{if $record->isFutureDate()}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{$record->futureDateBlurb()}'><i class='fa fa-clock-o'></i></span>
                            {{endif}}
							{{if $record->hidden() === -1}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$record->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
							{{elseif $record->hidden() === 1}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
							{{endif}}
							{{if $record->mapped('pinned')}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
							{{endif}}
							{{if $record->mapped('featured')}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
							{{endif}}
						</span>
					{{endif}}

					<span class='ipsType_break ipsContained'>
						{{if $record->unread()}}
						<a href='{$record->url('getNewComment')}'><span class='ipsItemStatus' data-ipsTooltip title="{lang="cms_unread_record"}"><i class="fa fa-circle"></i></span></a>
						{{endif}}
						<a href="{$record->url( "getPrefComment" )}" title="{lang="read_more_about" sprintf="$record->_title"}">{wordbreak="$record->_title"}</a>
					</span>
				</h2>
				<p class='ipsType_light ipsType_reset cmsInformation'>
					{lang="cms_byline" htmlsprintf="$record->author()->link( NULL, NULL, $record->isAnonymous() ), $record->container()->url(), $record->container()->_title"}{datetime="$record->mapped( 'date' )"}
				</p>
			</div>
		</header>
		{{if \count( $record->customFieldsForDisplay('listing') )}}
			<div class='ipsDataItem_meta'>
			{{foreach $record->customFieldsForDisplay('listing') as $fieldId => $fieldValue}}
				{{if $fieldValue}}
					{$fieldValue|raw}
				{{endif}}
			{{endforeach}}
			</div>
		{{endif}}
		<section class='ipsType_normal ipsType_richText ipsType_break ipsSpacer_both ipsClearfix' data-ipsTruncate data-ipsTruncate-size='7 lines' data-ipsTruncate-type='remove'>
			{{if $record->record_image}}
			<div class="cCmsRecord_image">
				<img class="ipsImage" src="{file="$record->_record_image_thumb" extension="cms_Records"}">
			</div>
			{{endif}}
	
			{$record->truncated()|raw}
		</section>
		{{if \count( $record->tags() )}}
			{template="tags" group="global" app="core" params="$record->tags()"}
		{{endif}}
		<hr class='ipsHr'>
		<ul class='ipsList_inline'>
			<li><strong><a href='{$record->url( "getPrefComment" )}' title="{lang="read_more_about" sprintf="$record->name"}">{lang="read_more"}</a></strong></li>
			{{if $record::database()->options['reviews']}}
				<li>{template="rating" app="core" params="'small', $record->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $record->memberReviewRating()" group="global"}</li>
			{{elseif $record->container()->allow_rating}}
				<li>{template="rating" group="global" location="front" app="core" params="'small', $record->rating_value, \IPS\Settings::i()->reviews_rating_out_of"}
			{{endif}}
			{{if $record::database()->options['comments']}}<li><a href='{$record->url()}#comments' title='{lang="view_comments"}'><i class='fa fa-comment'></i> {lang="num_comments" pluralize="$record->record_comments"}</a></li>{{endif}}
			<li class='ipsType_light'>{lang="num_views_with_number" pluralize="$record->record_views"}</li>
		</ul>
	</article>
</li>