<ips:template parameters="$database, $articles, $url, $pagination" />
<div class='ipsPageHeader ipsBox ipsPadding ipsResponsive_pull ipsClearfix ipsSpacer_bottom'>
	<div class='ipsFlex ipsFlex-ai:center ipsFlex-jc:between sm:ipsFlex-fd:column sm:ipsFlex-ai:stretch ipsGap:4'>
		<div class='ipsFlex-flex:11'>
			<h1 class='ipsType_pageTitle'>{$database->_title}</h1>
			{{if $database->_description}}
				<div class='ipsPageHeader_info ipsType_light'>
					{$database->_description}
				</div>
			{{endif}}
		</div>
		{{if $database->use_categories}}
		<div class='ipsFlex-flex:00'>
			<a href="{$url->setQueryString('show', 'categories')}" class="ipsButton ipsButton_small ipsButton_fullWidth ipsButton_light"><i class="fa fa-folder-open"></i> {lang="cms_show_categories"}</a>
		</div>
		{{endif}}
	</div>
</div>

{{if $database->can('add') or \IPS\Member::loggedIn()->member_id}}
	<ul class="ipsToolList ipsToolList_horizontal ipsClearfix ipsSpacer_both ipsResponsive_hidePhone">
		{{if $database->can('add')}}
			<li class='ipsToolList_primaryAction'>
				<a class="ipsButton ipsButton_medium ipsButton_important ipsButton_fullWidth" {{if $database->use_categories}}data-ipsDialog="1" data-ipsDialog-size="narrow" data-ipsDialog-title="{lang="cms_select_category"}"{{endif}} href="{$url->setQueryString( array( 'do' => 'form', 'd' => \IPS\cms\Databases\Dispatcher::i()->databaseId ) )}">{lang="cms_add_new_record_button" sprintf="$database->recordWord( 1 )"}</a>
			</li>
		{{endif}}
	</ul>
{{endif}}

<section class='ipsType_normal ipsSpacer_both'>
	{{if \count($articles)}}
		{{foreach $articles as $id => $record}}
			{{if $id == 0}}
				<ul class='ipsGrid ipsGrid_collapsePhone'>
				{template="entry" app="cms" location="database" group="category_2_column_first_featured" params="$record, $database, 0"}
				</ul>
			{{else}}
				{{if $id % 2}}
					<ul class='ipsGrid ipsGrid_collapsePhone cmsCategory2col'>
				{{endif}}
				{template="entry" app="cms" location="database" group="category_2_column_first_featured" params="$record, $database, $id"}
				{{if  $id % 2 == 0 or ( \count( $articles ) == ( $id + 1) )}}
					</ul>
				{{endif}}
			{{endif}}
		{{endforeach}}
	{{endif}}
</section>
{{if $database->featured_settings['pagination'] and ( $pagination['pages'] > 1 )}}
	{template="pagination" app="core" location="global" group="global" params="$url, $pagination['pages'], $pagination['page'], $database->featured_settings['perpage'], TRUE, 'page'"}
{{endif}}