<ips:template parameters="$templates, $current, $request" />

<form accept-charset='utf-8' action="{url="app=cms&module=pages&controller=templates&do=save"}" method="POST" id="editorForm">
	<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
	<input type="hidden" name="t_location" value="{$current->location}">
	<input type="hidden" name="t_key" value="{$current->key}">
	<input type="hidden" name="t_id" value="{$current->id}">
	
	<div id='elTemplateEditor' data-controller='cms.admin.templates.main' data-normalURL="{url="app=cms&module=pages&controller=templates"}" data-ajaxURL="{url="app=cms&module=pages&controller=ajax"}">
		<div class='ipsColumns'>
			<div class='ipsColumn ipsColumn_wide' data-role="fileList" data-controller='cms.admin.templates.fileList'>
				<div class='cTemplateControls' id='elTemplateEditor_fileListControls'>
					<div class="ipsClearfix" class="ipsJS_show">
						<input type='text' data-role="templateSearch" placeholder="{lang="search_templates"}" class="ipsPos_left">
						<a href='#elTemplateFilterMenu_menu' id='elTemplateFilterMenu' class='ipsButton ipsButton_light ipsButton_narrow ipsButton_small ipsPos_right' data-ipsMenu data-ipsMenu-selectable><i class="fa fa-filter"></i> &nbsp;<i class='fa fa-caret-down'></i></a>
					</div>
					<ul id='elTemplateFilterMenu_menu' role='menu' class='ipsMenu ipsMenu_selectable ipsMenu_auto ipsMenu_withStem ipsHide'>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='custom'><a href='#'>{lang="cms_theme_template_custom"}</a></li>
						<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='unmodified'><a href='#'>{lang="cms_theme_template_default"}</a></li>
					</ul>
					<ul id='elTemplateEditor_newItemMenu_menu' role='menu' class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide'>
						<li class='ipsMenu_item'><a role='menuitem' href='{url="app=cms&module=pages&controller=templates&do=addTemplate&type=block"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="content_template_add_template_block_title"}'>{lang="content_template_add_template_block"}</a></li>
						<li class='ipsMenu_item'><a role='menuitem' href='{url="app=cms&module=pages&controller=templates&do=addTemplate&type=page"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="content_template_add_template_page_title""}'>{lang="content_template_add_template_page"}</a></li>
						<li class='ipsMenu_item'><a role='menuitem' href='{url="app=cms&module=pages&controller=templates&do=addTemplate&type=database"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="content_template_add_template_database_title""}'>{lang="content_template_add_template_database"}</a></li>
						<li class='ipsMenu_item'><a role='menuitem' href='{url="app=cms&module=pages&controller=templates&do=addTemplate&type=css"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="content_template_add_template_css_title""}'>{lang="content_template_add_template_css"}</a></li>
						<li class='ipsMenu_item'><a role='menuitem' href='{url="app=cms&module=pages&controller=templates&do=addTemplate&type=js"}' data-ipsDialog data-ipsDialog-forceReload data-ipsDialog-title='{lang="content_template_add_template_js_title""}'>{lang="content_template_add_template_js"}</a></li>
					</ul>
				</div>
				<div class='ipsAreaBackground_reset'>
					<div class='ipsTabs ipsClearfix ipsTabs_stretch acpFormTabBar' id='elTemplateEditor_typeTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elTemplateEditor_fileList' data-ipsTabBar-updateURL='false'>
						<ul role="tablist">
							<li><a href='{url="app=cms&module=pages&controller=templates&do=manage&t_type=templates"}' class='ipsTabs_item ipsType_center {{if $current->type == 'templates'}}ipsTabs_activeItem{{endif}}' data-tabURL='{url="app=cms&module=pages&controller=ajax&do=loadMenu&t_type=templates"}' data-type='templates'>{lang="theme_html"}</a></li>
							<li><a href='{url="app=cms&module=pages&controller=templates&do=manage&t_type=css"}' class='ipsTabs_item ipsType_center {{if $current->type == 'css'}}ipsTabs_activeItem{{endif}}' data-tabURL='{url="app=cms&module=pages&controller=ajax&do=loadMenu&t_type=css"}' data-type='css'>{lang="theme_css"}</a></li>
							<li><a href='{url="app=cms&module=pages&controller=templates&do=manage&t_type=js"}' class='ipsTabs_item ipsType_center {{if $current->type == 'js'}}ipsTabs_activeItem{{endif}}' data-tabURL='{url="app=cms&module=pages&controller=ajax&do=loadMenu&t_type=js"}' data-type='css'>{lang="theme_js"}</a></li>
						</ul>
					</div>
					<section id='elTemplateEditor_fileList'>
						{template="menu" params="$templates, $current, $request" app="cms" location="admin" group="templates"}
					</section>
				</div>
				<div class='ipsAreaBackground_light ipsPad' id='elTemplateEditor_newButton'>
					<a href='#elTemplateEditor_newItemMenu_menu' id='elTemplateEditor_newItemMenu' class='ipsButton ipsButton_normal ipsButton_small ipsButton_fullWidth' data-ipsMenu data-ipsMenu-above>{lang="theme_template_new"} &nbsp;<i class='fa fa-caret-down'></i></a>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_fluid'  data-controller='cms.admin.templates.fileEditor'>
				<div class='cTemplateControls'>
					<ul class='ipsList_inline ipsClearfix' id='elTemplateEditor_panelToolbar'>
						<li class='ipsPos_right'>
							<a href='#elTemplateEditor_preferences_menu' id='elTemplateEditor_preferences' class='ipsButton ipsButton_veryLight ipsButton_small' data-ipsMenu data-ipsMenu-selectable><i class='fa fa-cog'></i> <i class='fa fa-caret-down'></i></a>
							<ul id='elTemplateEditor_preferences_menu' class='ipsMenu ipsMenu_selectable ipsMenu_auto ipsMenu_withStem ipsHide'>
								<li class='ipsMenu_item' data-ipsMenuValue='wrap'><a href='#'>{lang="theme_wrap"}</a></li>
								<li class='ipsMenu_item' data-ipsMenuValue='lines'><a href='#'>{lang="theme_show_line"}</a></li>
								<li class='ipsMenu_item' data-ipsMenuValue='diff'><a href='#'>{lang="theme_show_original"}</a></li>
							</ul>
						</li>
						<li class='ipsPos_right'>
							<a href='#' id='elTemplateEditor_variables' class='ipsButton ipsButton_veryLight ipsButton_small' data-ipsDialog data-ipsDialog-title='{lang="content_template_editor_fields_title"}' data-ipsDialog-content="#elTemplateEditor_attributesDialog" data-ipsDialog-size='narrow'>{lang="theme_attributes"}</a>
						</li>
						<li class='ipsPos_right'>
							<a href='{url="app=cms&module=pages&controller=templates&do=delete&t_location={$current->location}&t_key={$current->id}"}' class='ipsButton ipsButton_veryLight ipsButton_small {{if $current->user_edited == 'original'}}ipsButton_disabled{{endif}}' data-action="revert">{{if ! $current->user_edited}}{lang="delete"}{{else}}{lang="revert"}{{endif}}</a>
						</li>
						<li>
							<button type='submit' class='ipsButton ipsButton_primary ipsButton_small' data-action="save">{lang="save"}</button>
						</li>					
						<li>
							<span data-role='loading' class='ipsHide'><i class='icon-spinner2 ipsLoading_tinyIcon'></i>  &nbsp;{lang="loading"}</span>
						</li>
					</ul>
				</div>
				<div id='elTemplateEditor_outerPanelWrap'>
					<div id='elTemplateEditor_panelWrap'>
						<ul id='elTemplateEditor_tabbar' class='ipsTabs ipsClearfix acpFormTabBar' data-ipsTabBar data-ipsTabBar-contentArea='#elTemplateEditor_panels'>
							<li data-fileid='{$current->key}' data-type="{$current->type}" data-location='{$current->location}' data-group="{$current->group}">
								<a href='#' class='ipsTabs_item' id='tab_{$current->key}'>{$current->title} <span data-action='closeTab'><i class='fa fa-times'></i></span></a>
							</li>
						</ul>
						<section data-role="templatePanelWrap" id='elTemplateEditor_panels' data-haseditor="{{if $current->id}}true{{else}}false{{endif}}">
							{template="editor" params="$templates, $current" app="cms" location="admin" group="templates"}
						</section>
					</div>
				</div>
			</div>
		</div>
		<br>
		<div id='elTemplateEditor_attributesDialog' class='ipsHide'>
			<div data-controller='cms.admin.templates.variablesDialog'>
				<div class='ipsPad'>
					<p class='ipsType_textBlock' id='elTemplateEditor_attributes_title'>
						{lang="content_template_editor_fields_params"}
					</p>
					<input class='ipsField_fullWidth' data-role='variables' placeholder="&#36;foo=''">
					<p class='ipsType_textBlock' id='elTemplateEditor_title_title'>
						{lang="content_template_editor_fields_title"}
					</p>
					<input class='ipsField_fullWidth' data-role='title'>
					<p class='ipsType_textBlock' id='elTemplateEditor_group_title'>
						{lang="content_template_editor_fields_container"}
					</p>
					{{foreach array('block','page', 'database') as $type }}
						<select id="elContainer_{$type}_hidden" class='ipsHide' name="group" data-role="group" data-container-type="{$type}">
						{{foreach \IPS\cms\Templates::getGroups( $type ) as $groupName}}
							<option value="{$groupName}">{expression="\IPS\cms\Templates::readableGroupName( $groupName )"}</option>
						{{endforeach}}
						</select>
					{{endforeach}}
					<p class='ipsType_textBlock ipsHide'>
						{lang="content_template_editor_fields_desc"}
					</p>
					<textarea class='ipsHide ipsField_fullWidth' data-role='description'></textarea>
					<input type='hidden' name='_variables_fileid' value=''>
					<input type='hidden' name='_variables_location' value=''>
				</div>
				<div class='ipsPad ipsAreaBackground ipsType_right'>
					<input type='submit' class='ipsButton ipsButton_primary' value='{lang="save"}'>
				</div>
			</div>
		</div>
	</div>
</form>
<ul class='ipsList_inline ipsType_light ipsType_small' id='elTemplateEditor_info'>
	<li class='cTemplateState_changed'> {lang="content_templates_modified"}</li>
	<li class='cTemplateState_custom'> {lang="content_templates_custom"}</li>
    <li class='cTemplateState_inherit'> {lang="content_templates_inherit"}</li>
</ul>