<ips:template parameters="$conflicts, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $formClass='', $attributes=array(), $sidebar=''" />
<form accept-charset='utf-8' data-controller='core.admin.templates.conflict' action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm class="{$formClass}" {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}

	<p class="ipsMessage ipsMessage_error">{lang="theme_conflict_message"}</p>
	
	<div class="acpBlock">
		{{foreach $conflicts as $cid => $data}}
		<div class="ipsPad ipsAreaBackground_dark">{$data['conflict_location']}/{$data['conflict_group']}/{$data['conflict_title']}</div>
		<table class="ipsTable diff restrict_height">
			<tr>
				<th><span data-conflict-id="{$cid}" data-conflict-name="old">{lang="theme_conflict_old_version"}</span></th>
				<th><span data-conflict-id="{$cid}" data-conflict-name="new">{lang="theme_conflict_new_version"} </span></th>
			</tr>
		</table>
		<div data-conflict-id="{$cid}">
		{$data['diff']|raw}
		</div>
		<div class="ipsAreaBackground_light ipsPad">
			<div class='ipsGrid'>
				<div class='ipsGrid_span6'>
					<span class='ipsButton ipsButton_primary' data-conflict-name="old">
						{{foreach $elements as $collection}}
							{{foreach $collection as $name => $input}}
								{{if $name == 'conflict_' . $cid}}
									<input id='elField_{$name}' type="radio" name="{$name}" value="old" checked="checked" />
								{{endif}}
							{{endforeach}}
						{{endforeach}}
						<strong>{lang="theme_conflict_use_this"}</strong>
					</span>
				</div>
				<div class='ipsGrid_span6'>
					<span class='ipsButton ipsButton_primary' data-conflict-name="new">
						{{foreach $elements as $collection}}
							{{foreach $collection as $name => $input}}
								{{if $name == 'conflict_' . $cid}}
									<input id='elField_{$name}'  type="radio" name="{$name}" value="new" />
								{{endif}}
							{{endforeach}}
						{{endforeach}}
						<strong>{lang="theme_conflict_use_this"}</strong>
					</span>
				</div>
			</div>
		</div>
		{{endforeach}}
	</div>
	<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
		{expression="implode( '', $actionButtons)" raw="true"}
	</div>
</form>