<ips:template parameters="$database, $categories, $url" />
<div class='ipsPageHeader ipsClearfix ipsSpacer_bottom'>
	{{if $database->cat_index_type == 1}}
		<div class='ipsPos_right ipsResponsive_noFloat'>
			<a href="{$url}" class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_link"><i class="fa fa-star"></i> {lang="cms_show_featured" sprintf="$database->recordWord()"}</a>
		</div>
	{{endif}}
	<h1 class='ipsType_pageTitle'>{$database->_title}</h1>
	{{if $database->_description}}
		<div class='ipsType_richText ipsType_normal'>
			{$database->_description}
		</div>
	{{endif}}
</div>
<section class="ipsResponsive_pull">
	<ol class='ipsList_reset cCmsDatabase_index' data-controller='core.global.core.table, forums.front.forum.forumList' data-baseURL=''>
		<li class='cForumRow ipsBox ipsSpacer_bottom ipsResponsive_pull'>
			<h2 class="ipsType_sectionTitle ipsType_reset ipsType_blendLinks">
				{lang="content_categories_title"}
			</h2>
			{{if ! \count($categories)}}
				<div class="ipsBox ipsPad">{lang="cms_no_cats_to_show"}</div>
			{{else}}
				<ol class="ipsDataList ipsDataList_large ipsDataList_zebra">
					{{foreach $categories as $category}}
						{template="categoryRow" group="category_index" location="database" app="cms" params="$category"}
					{{endforeach}}
				</ol>
			{{endif}}
		</li>
		{{$categoryClass = 'IPS\cms\Categories' . $database->_id;}}
		{{if settings.club_nodes_in_apps and \IPS\IPS::classUsesTrait( $categoryClass, 'IPS\Content\ClubContainer' ) and $clubCategories = $categoryClass::clubNodes()}}
            {{if \count( $clubCategories )}}
                <li class='cForumRow ipsBox ipsSpacer_bottom ipsResponsive_pull'>
                    <h2 class="ipsType_sectionTitle ipsType_reset ipsType_blendLinks">
                        {lang="club_categories_title"}
                    </h2>
                    <ol class="ipsDataList ipsDataList_large ipsDataList_zebra">
                        {{foreach $clubCategories as $category}}
                            {template="categoryRow" group="category_index" location="database" app="cms" params="$category"}
                        {{endforeach}}
                    </ol>
                </li>
            {{endif}}
		{{endif}}
	</ol>
</section>