<ips:template parameters="$member, $percentage" />

{{$baseUrl = \IPS\Http\Url::internal( "app=core&module=members&controller=profile&id={$member->member_id}&do=content", 'front', 'profile_content', $member->members_seo_name );}}
{{if !\IPS\Request::i()->isAjax()}}
<div data-controller='core.front.profile.main' id='elProfileUserContent'>
	{template="profileHeader" app="core" location="front" group="profile" params="$member, true"}
	<div data-role="profileContent" class='ipsSpacer_top'>
{{endif}}
		<div class='ipsColumns ipsColumns_collapseTablet'>
            {{if $member->canHaveAchievements() and \IPS\core\Achievements\Rank::show() and \IPS\core\Achievements\Rank::getStore() and $rank = $member->rank()}}
                <div class='ipsColumn ipsColumn_veryWide'>
                    <div class='ipsBox ipsSpacer_bottom'>
                        <h2 class='ipsType_sectionTitle ipsType_reset'>{lang="achievements_profile_rank_progress"}</h2>
                        <div class='ipsPadding'>
                            {{if $rank}}
                            <p class='ipsType_reset ipsMargin_bottom'>
                                {{if $percentage}}
                                    {lang="profile_rank_progress_blurb_percentage" sprintf="$member->name, $member->rank()->rankPosition()['pos'], $member->rank()->rankPosition()['max'], $percentage"}
                                <span class="ipsType_light ipsType_small" data-ipsToolTip title="{lang="profile_rank_progress_blurb_percentage_info"}"><i class="fa fa-info-circle"></i></span>
                                {{else}}
                                    {lang="profile_rank_progress_blurb" sprintf="$member->name, $member->rank()->rankPosition()['pos'], $member->rank()->rankPosition()['max']"}
                                {{endif}}
                            </p>
                            <hr class='ipsHr ipsMargin_bottom:double'>
                            {{endif}}

                            <ul class='ipsList_reset cRankHistory ipsPos_relative'>
                                {{if $member->rankHistory()['earned']}}
                                {{foreach $member->rankHistory()['earned'] as $entry}}
                                    <li class='ipsFlex ipsMargin_vertical cRankHistory__item'>
                                        {$entry['rank']->html( 'ipsFlex-flex:00 ipsDimension:4 ipsOutline cRankHistory__itemBadge' )|raw}
                                        <div class='ipsMargin_left:half'>
                                            <h3 class='ipsType_reset ipsType_semiBold ipsType_darkText ipsType_large'>{$entry['rank']->_title}</h3>
                                            {{if ! $entry['time'] or ( $entry['time']->getTimestamp() < settings.achievements_last_rebuilt)}}
                                                {{if \IPS\Settings::i()->achievements_last_rebuilt}}<p class='ipsType_reset ipsType_light'>{lang="badge_earned_date_while_rebuilding" htmlsprintf="\IPS\DateTime::ts( \IPS\Settings::i()->achievements_last_rebuilt )->shortMonthAndFullYear()"}</p>{{endif}}
                                            {{elseif $entry['time']}}
                                            <p class='ipsType_reset ipsType_light'>{lang="badge_earned_date" htmlsprintf="$entry['time']->html()"}</p>
                                            {{endif}}
                                        </div>
                                    </li>
                                {{endforeach}}
                                {{endif}}
                                {{if $member->rankHistory()['not_earned']}}
                                {{foreach $member->rankHistory()['not_earned'] as $entry}}
                                    <li class='ipsFlex ipsMargin_vertical cRankHistory__item'>
                                        {$entry['rank']->html( 'ipsFlex-flex:00 ipsDimension:4 ipsOutline cRankHistory__itemBadge cRankHistory__itemBadge--unearned' )|raw}
                                        <div class='ipsMargin_left:half ipsFaded'>
                                            <h3 class='ipsType_reset ipsType_semiBold ipsType_large'>{$entry['rank']->_title}</h3>
                                            <p class='ipsType_reset'><em>{lang="badge_earned_but_not_really"}</em></p>
                                        </div>
                                    </li>
                                {{endforeach}}
                                {{endif}}
                            </ul>
                        </div>
                    </div>
                </div>
            {{endif}}
			<div class='ipsColumn ipsColumn_fluid'>
				<div class='ipsBox ipsSpacer_bottom'>
					<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="achievements_profile_title" pluralize="$member->badgeCount()"}</h2>
					{{if $member->badgeCount()}}
						<div class='ipsPadding cProfileBadgeGrid'>
							{{foreach $member->recentBadges( NULL ) as $badge}}
								<div class='ipsFlex ipsFlex-ai:center'>
									{$badge->html('ipsFlex-flex:00 ipsDimension:4', FALSE, TRUE)|raw}
									<div class='ipsMargin_left:half'>
										{{if ! empty( $badge->recognize ) AND $badge->recognize->contentWrapper() }}
										<h4 class='ipsType_reset ipsType_semiBold ipsType_medium'>
											{lang="badge_from_recognize" sprintf="$badge->_title, $badge->recognize->content()->url(), $badge->recognize->content()->indefiniteArticle()"}
										</h4>
										{{else}}
										<h4 class='ipsType_reset ipsType_semiBold ipsType_medium'>{$badge->_title}</h4>
										{{endif}}
										{{if ! empty( $badge->awardDescription )}}
											<p class='ipsType_reset ipsType_small ipsType_light'>{$badge->awardDescription}</p>
										{{endif}}
                                        {{if $badge->datetime < settings.achievements_last_rebuilt}}
                                            {{if \IPS\Settings::i()->achievements_last_rebuilt}}<p class='ipsType_reset ipsType_small ipsType_light'>{lang="badge_earned_date_while_rebuilding" htmlsprintf="\IPS\DateTime::ts( \IPS\Settings::i()->achievements_last_rebuilt )->shortMonthAndFullYear()"}</p>{{endif}}
                                        {{else}}
                                        <p class='ipsType_reset ipsType_small ipsType_light'>{lang="badge_earned_date" htmlsprintf="\IPS\DateTime::ts( $badge->datetime )->html()"}</p>
                                        {{endif}}
									</div>
								</div>
							{{endforeach}}
						</div>
					{{else}}
						<div class='ipsPadding ipsType_center ipsType_light'>
							{{if $member->member_id === \IPS\Member::loggedIn()->member_id}}
								{lang="achievements_self_none" sprintf=""}
							{{else}}
								{lang="achievements_member_none" sprintf="$member->name"}
							{{endif}}
						</div>
					{{endif}}
				</div>
			</div>
		</div>
{{if !\IPS\Request::i()->isAjax()}}
	</div>
</div>
{{endif}}