<ips:template parameters="$table, $headers, $rows" />
{{if \count( $rows )}}
	{{foreach $rows as $row}}
		<li class='ipsDataItem'>		
			<div class='ipsDataItem_generic ipsDataItem_size2 ipsType_center ipsResponsive_hidePhone'>
				{template="userPhoto" group="global" app="core" params="\IPS\Member::load( \IPS\Request::i()->id ), 'mini'"}
			</div>
			<div class='ipsDataItem_main'>
				<span class=''>
					{lang="solution_headline" sprintf="\IPS\Member::load( \IPS\Request::i()->id )->name, $row->url(), \IPS\Member::loggedIn()->language()->addToStack( $row::$title . '_lc' ), $row->item()->url(), $row->item()->mapped('title')"}
				</span>
				<span class='ipsType_light ipsType_medium'>&nbsp;&nbsp;{datetime="$row->solved_date"}</span>
				<br>
				{{if $result = $row->truncated()}}
					<div class='ipsType_medium ipsType_richText ipsContained cProfileRepLog_text' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'>
						{$result|raw}
					</div>
				{{endif}}
			</div>
		</li>
	{{endforeach}}
{{endif}}
