<ips:template parameters="$comment, $package, $item" />

<div class='ipsFlex ipsFlex-ai:center sm:ipsFlex-ai:start sm:ipsMargin_top:double'>
	<div class='ipsFlex-flex:00 ipsMargin_right sm:ipsMargin_right:half'>
		{template="thumbImage" group="global" app="core" params="$package->image, $package->_title, 'small', '', 'view_this', $package->url()"}
	</div>
	<div>
		<h3 class='ipsType_sectionHead'><a href="{$package->url()}" data-role='productLink'>{$package->_title}</a></h3>
		<p class='ipsType_normal ipsType_light ipsType_blendLinks ipsType_reset'>{lang="in"} <a href='{$item->container()->url()}'>{$item->container()->_title}</a></p>
		<div class='ipsType_reset ipsTruncate ipsTruncate_line ipsStream_price ipsStream_price_small'>
			{template="packageBlockPrice" app="nexus" group="store" params="$package->fullPriceInfo()"}
		</div>
	</div>
</div>