<ips:template parameters="$item, $renewalTerm=NULL, $url=NULL, $image=NULL" />

{{$asNode = \IPS\nexus\Package::load( $item->id );}}
<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed cNexusEmbed'>
	<div class='ipsRichEmbed_header ipsAreaBackground_light ipsClearfix'>
		<a href='{$item->url()}' class='ipsRichEmbed_openItem'><i class='fa fa-external-link-square'></i></a>
		<div class='ipsType_blendLinks'>
			<div>
				<p class='ipsRichEmbed_title ipsType_reset ipsTruncate ipsTruncate_line'>
					<a href='{$item->url()}'>{lang="a_product_in_our_store"}</a>
				</p>
				<p class='ipsRichEmbed_author ipsType_reset ipsType_light ipsTruncate ipsTruncate_line'>
					{$item->container()->_title}
				</p>
			</div>
		</div>
	</div>
	{{if $images = $item->images() and \count( $images )}}
		{{foreach $images as $image}}
			<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg cNexusEmbedImage ipsType_center' data-imageID='{$item->id}'>
				<a href='{$item->url()}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image )"}" )'>
					<img src='{$image}' class='ipsHide' alt='{$item->mapped('title')}'>
				</a>
			</div>
			{{break;}}	
		{{endforeach}}
	{{else}}
		<div class='cNexusEmbedImage ipsNoThumb ipsNoThumb_product'>&nbsp;</div>
	{{endif}}
	<div class='ipsPadding ipsClearfix'>
		<div class='ipsRichEmbed_itemTitle ipsType_reset ipsTruncate ipsTruncate_line ipsType_blendLinks'>
			<a href='{$item->url()}'>{$item->mapped('title')}</a>
			{{if $item instanceof \IPS\Content\Ratings and $rating = $item->averageRating()}}
				&nbsp;&nbsp;{template="rating" app="core" params="'large', $rating, 5" group="global"}
			{{elseif isset( $item::$reviewClass ) AND $rating = $item->averageReviewRating()}}
				&nbsp;&nbsp;{template="rating" app="core" params="'large', $rating, \IPS\Settings::i()->reviews_rating_out_of" group="global"}<span class='ipsType_light ipsType_medium'>{{if $item->reviews}}({lang="from_num_reviews" pluralize="$item->reviews"}){{else}}{lang="no_reviews_yet"}{{endif}}</span>
			{{endif}}
		</div>
		<p class='ipsType_reset ipsTruncate ipsTruncate_line ipsSpacer_both ipsSpacer_half'>
			{template="packageBlockPrice" app="nexus" group="store" params="$asNode->fullPriceInfo()"}
		</p>
		{{if $asNode->stock === 0}}
			<span class='ipsButton ipsButton_primary ipsButton_small ipsButton_fullWidth ipsButton_disabled ipsCursor_locked'>{lang="out_of_stock"}</span>
		{{else}}
			<a href='{$asNode->url()->setQueryString( 'purchase', 1 )}' class='ipsButton ipsButton_primary ipsButton_fullWidth ipsButton_small ipsButton_narrow' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="store_quick_view"}' data-ipsDialog-forceReload>
				<i class='fa fa-shopping-cart'></i>&nbsp;{lang="add_to_cart"}
			</a>
		{{endif}}
		{{if $desc = $item->truncated(TRUE)}}
			<hr class='ipsHr'>
			<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='3'>
				{$desc|raw}
			</div>
		{{endif}}
	</div>
</div>