<ips:template parameters="$rules" />
{{if settings.nexus_com_rules AND \count( $rules )}}
<div class="ipsBox ipsSpacer_bottom ipsClearfix">
	<div class="ipsAreaBackground_light ipsClearfix ipsPad">
		<strong><i class="fa fa-shopping-basket"></i> {lang="referrals_title"}</strong>
	</div>
	<ul class='ipsDataList ipsPad'>
		{{foreach $rules as $rule}}
		<li class='ipsDataItem'>
			<div class='ipsDataItem_generic ipsDataItem_size2 ipsType_center'>
				<span class='cReferralBadge'>{$rule->commission}%</span>
			</div>
			<div class='ipsDataItem_generic'>
				<strong class='ipsType_normal'>{$rule->description()}</strong>
				{{$limit = $rule->commissionLimit();}}
				{{if $rule->purchase_packages or $limit != ''}}<p class='ipsType_reset ipsType_medium ipsType_light'>({{endif}}
				{{if $rule->purchase_packages}}
					{{if $rule->purchase_package_limit}}
						{lang="ref_comm_limit_yes"}
					{{else}}
						{lang="ref_comm_limit_no"}
					{{endif}}
				{{endif}}
				{{if $rule->commission_limit}}
					{$rule->commissionLimit()}
				{{endif}}
				{{if $rule->purchase_packages or $limit != ''}})</p>{{endif}}
			</div>
		</li>
		{{endforeach}}
	</ul>
</div>
{{endif}}