<ips:template parameters="$indexData, $itemData, $image, $url, $priceInfo, $condensed" />
{{if $condensed}}
	{{if $image}}
		<span data-ipsLazyLoad class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{file="$image" extension="nexus_Products"}"{{else}}style='background-image: url({file="$image" extension="nexus_Products"})'{{endif}}>
			<img {{if settings.lazy_load_enabled}}data-{{endif}}src='{file="$image" extension="nexus_Products"}' alt="">
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsStreamItem_columns'>
		{{if $image}}
			<div class='ipsStreamItem_columns__thumb' data-ipsLazyLoad>
				<a href='{$url}'>
					{template="thumbImage" group="global" app="core" location="front" params="$image, $indexData['index_title'], 'medium', '', 'view_this', NULL, 'nexus_Products', '', true"}
				</a>
			</div>
		{{endif}}
		<div class='ipsStreamItem_columns__content'>			
			<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
				{lang="nexus_package_{$indexData['index_item_id']}_desc"}
			</div>			
			<div class='ipsType_reset ipsStream_price ipsType_bold'>
				{template="packageBlockPrice" app="nexus" group="store" params="$priceInfo"}
			</div>
		</div>
	</div>
{{endif}}