<ips:template parameters="$handlers=array()" />

<div class="ipsMargin" >
    <h2 class="ipsMargin_top:none ipsMargin_bottom:half">{lang="datalayer_title"}</h2>
    <div class="ipsType ipsMargin_bottom ipsPadding_bottom">{lang="datalayer_desc"}</div>
    <div>
        {{if empty($handlers)}}
        <p class="ipsPadding_vertical">
            {lang="datalayer_custom_handler_none"}
        </p>
        <a href='{url="app=core&module=settings&controller=dataLayer&do=addHandler" location="admin"}' class="ipsButton ipsButton_primary">{lang="datalayer_custom_handler_create"}</a>
        {{else}}
        {{foreach $handlers as $handler}}
        <div>
            {{$dataLayerKey = \IPS\Member::loggedIn()->language()->addToStack('datalayer_custom_title_prefix') . ' ' . $handler->datalayer_key;}}
            {template="row" group="trees" location="admin" app="core" params="$handler->url(), $handler->id, $handler->name, false, $handler->buttonHtml, $dataLayerKey, NULL, NULL, FALSE, $handler->enabled"}
        </div>
        {{endforeach}}
        {{endif}}
    </div>
</div>
