<ips:template parameters="$cols, $blocks, $info" />

<div data-controller='core.admin.dashboard.main'>	
	<div class='ipsGrid ipsGrid_collapseTablet'>
		<div class='ipsGrid_span8' data-role="mainerColumn">
			<ol class='ipsList_reset' data-role="mainColumn">
				{{foreach $cols['main'] as $cellKey}}
					{{if array_key_exists( $cellKey, $blocks ) and isset($info[ $cellKey ])}}
						{template="widgetWrapper" group="dashboard" app="core" params="$blocks[ $cellKey ], $info[ $cellKey ], $cols['collapsed']"}
					{{endif}}
				{{endforeach}}
			</ol>
		</div>
		<div class='ipsGrid_span4 acpWidget_sidebar'>
			<ol class='ipsList_reset' data-role="sideColumn">
				{{foreach $cols['side'] as $cellKey}}
					{{if array_key_exists( $cellKey, $blocks ) and isset($info[ $cellKey ])}}
						{template="widgetWrapper" group="dashboard" app="core" params="$blocks[ $cellKey ], $info[ $cellKey ], $cols['collapsed']"}
					{{endif}}
				{{endforeach}}
			</ol>
		</div>
	</div>
</div>