<ips:template parameters="" />

<div class='ipsBox ipsBox_shadowed cOnboardBox cOnboardBox--welcome'>
	<div class='ipsPos_right cOnboardBox__image'>
		<img src='{resource="welcome.svg" app="core" location="admin"}' alt=''>
	</div>
	<h1 class='ipsType_pageTitle'>{lang="onboard_pagetitle"}</h1>
	<p class='ipsMargin_bottom:double ipsMargin_top:none cOnboardBox__text'>{lang="onboard_subtitle"}</p>
	<hr class='ipsHr'>
	{lang="onboard_welcome_message"}

	<div class="ipsClearfix ipsPad ipsType_right">
		<a href='{url="app=core&module=overview&controller=onboard&do=dismiss" csrf="true"}' class='ipsButton ipsButton_link ipsButton_link_secondary'>{lang="onboard_skipquicksetup"}</a>
		<a href='{url="app=core&module=overview&controller=onboard&initial=1"}' class='ipsButton ipsButton_primary'>{lang="onboard_startquicksetup"}</a>
	</div>
</div>
