<ips:template parameters="$id, $action, $tabs, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL, $errorTabs=array()" />

<div class='cOnboard' data-controller='core.admin.dashboard.onboard'>
	<form accept-charset='utf-8' data-formId="{$id}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm class="{$form->class}" {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}}>
		<input type="hidden" name="{$id}_activeTab" value="{$form->activeTab}">
		<input type="hidden" name="{$id}_submitted" value="1">
		{{foreach $hiddenValues as $k => $v}}
			{{if \is_array($v)}}
				{{foreach $v as $_v}}
					<input type="hidden" name="{$k}[]" value="{$_v}">
				{{endforeach}}
			{{else}}
				<input type="hidden" name="{$k}" value="{$v}">
			{{endif}}
		{{endforeach}}
		{{if $uploadField}}
			<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		{{endif}}
		{{if $form->error}}
			<div class="ipsMessage ipsMessage_error">
				{$form->error}
			</div>
		{{endif}}
		{{if !empty( $errorTabs )}}
			<p class="ipsMessage ipsMessage_error ipsJS_show">{lang="tab_error"}</p>
		{{endif}}

		{{$count = 1;}}
		{{foreach $tabs as $name => $collection}}
			{{if $name}}
				{{$closed = TRUE;}}
				{{if $count == 1}}
					{{$closed = FALSE;}}
				{{endif}}
				<div class='ipsBox ipsBox_shadowed ipsMargin_bottom cOnboard__section {{if $closed}}cOnboard__section--closed{{endif}}' data-role="sectionWrap">
					<h2 class='ipsType_pageTitle ipsPadding cOnboard__sectionTitle' data-role="sectionToggle">
						<i class="fa fa-angle-down ipsMargin_right cOnboard__sectionIcon" data-role="closeSection"></i>
						{{if \in_array( $name, $errorTabs )}}<i class="fa fa-exclamation-circle"></i> {{endif}}{lang="$name"}
					</h2>

					<div class="ipsFlex ipsFlex-fd:row sm:ipsFlex-fd:column ipsMargin_vertical:double cOnboard__sectionContents" aria-hidden="false" data-role="sectionForm">
						{{$key = str_replace( 'onboard_tab_', '', $name );}}
						<div class='ipsFlex ipsFlex-fd:column ipsFlex-flex:01 sm:ipsFlex-fd:column ipsPadding_horizontal:double cOnboard__column cOnboard__column--info cOnboard__column--withBorder'>
							<div>
								<h3 class='ipsType_sectionHead cOnboard__infoTitle'>{lang="onboard_what_are_these"}</h3>
								<p>{lang="onboard_msg_$key"}</p>
							</div>
							<div>
								<h3 class='ipsType_sectionHead cOnboard__infoTitle ipsMargin_top'>{lang="onboard_where_are_these"}</h3>
								<p>{lang="onboard_location_$key"}</p>
							</div>
						</div>

						<div class='ipsFlex-flex:11 cOnboard__column cOnboard__column--form ipsPadding_horizontal:double'>
							<ul class='ipsForm {$form->class}'>
								{{foreach $collection as $input}}
									{{if \is_string( $input )}}
										{$input|raw}
									{{else}}
										{$input->rowHtml( $form )|raw}
									{{endif}}
								{{endforeach}}
							</ul>
						</div>
					</div>

					<div class='ipsAreaBackground_light cOnboard__sectionButtons' data-role="sectionButtons">
						<div class='ipsFlex ipsFlex-fd:row sm:ipsFlex-fd:column cOnboard__sectionContents'>
							<div class='cOnboard__column cOnboard__column--info'>&nbsp;</div>
							<div class='cOnboard__column cOnboard__column--form ipsPadding_vertical'>
								<button class='ipsButton ipsButton_veryLight ipsButton_medium' data-action="nextStep" type='button'>{lang="next"}</button>
							</div>
						</div>
					</div>
				</div>
				{{$count++;}}
			{{endif}}
		{{endforeach}}

		<div class="ipsBox ipsBox_shadowed ipsClearfix ipsPad ipsType_center">
			{expression="implode( '', $actionButtons)" raw="true"}
		</div>
	</form>
</div>