<ips:template parameters="" />

<div class='ipsBox ipsBox_shadowed ipsPadding:double cOnboardBox cOnboardBox--nextSteps'>
	<h1 class='ipsType_pageTitle'>{lang="onboard_complete"}</h1>
	<p class='cOnboardBox__text'>{lang="onboard_next_steps_subtitle"}</p>
	<hr class='ipsHr'>

	<p class='cOnboardBox__text'>{lang="onboard_next_steps_intro"}</p>
	<p class='cOnboardBox__text'>{lang="onboard_next_steps_intro2"}</p>

	<hr class='ipsHr'>


	{{if \IPS\Application::appIsEnabled( 'forums' )}}
		<div class='ipsBox ipsBox_shadowed ipsMargin_bottom ipsFlex sm:ipsFlex-fd:column sm:ipsFlex-ai:start ipsFlex-ai:center ipsFlex-jc:center ipsPadding:double'>
			<div class='cOnboardBox__stepIcon ipsFlex-flex:00 ipsType_center ipsMargin_right:double'>
				<i class='fa fa-comments fa-lg'></i>
			</div>
			<div class='cOnboardBox__stepText ipsMargin_right:double sm:ipsMargin_vertical ipsFlex-flex:11'>
				<h2 class='ipsType_reset cOnboardBox__stepTitle ipsMargin_bottom:half'>{lang="onboard_next_forums_title"}</h2>
				<p class='ipsType_reset ipsType_normal'>{lang="onboard_next_forums"}</p>
			</div>
			<div class='ipsFlex-flex:00'>
				<a class="ipsButton ipsButton_light ipsButton_small" href='{url="app=forums&module=forums&controller=forums"}'>{lang="onboard_takeme"}</a>
			</div>
		</div>
	{{endif}}

	<div class='ipsBox ipsBox_shadowed ipsMargin_bottom ipsFlex sm:ipsFlex-fd:column sm:ipsFlex-ai:start ipsFlex-ai:center ipsFlex-jc:center ipsPadding:double'>
		<div class='cOnboardBox__stepIcon ipsFlex-flex:00 ipsType_center ipsMargin_right:double'>
			<i class='fa fa-group fa-lg'></i>
		</div>
		<div class='cOnboardBox__stepText ipsMargin_right:double sm:ipsMargin_vertical ipsFlex-flex:11'>
			<h2 class='ipsType_reset cOnboardBox__stepTitle ipsMargin_bottom:half'>{lang="onboard_next_groups_title"}</h2>
			<p class='ipsType_reset ipsType_normal'>{lang="onboard_next_groups"}</p>
		</div>
		<div class='ipsFlex-flex:00'>
			<a class="ipsButton ipsButton_light ipsButton_small" href='{url="app=core&module=members&controller=groups"}'>{lang="onboard_takeme"}</a>
		</div>
	</div>

	<div class='ipsBox ipsBox_shadowed ipsMargin_bottom ipsFlex sm:ipsFlex-fd:column sm:ipsFlex-ai:start ipsFlex-ai:center ipsFlex-jc:center ipsPadding:double'>
		<div class='cOnboardBox__stepIcon ipsFlex-flex:00 ipsType_center ipsMargin_right:double'>
			<i class='fa fa-unlock-alt fa-lg'></i>
		</div>
		<div class='cOnboardBox__stepText ipsMargin_right:double sm:ipsMargin_vertical ipsFlex-flex:11'>
			<h2 class='ipsType_reset cOnboardBox__stepTitle ipsMargin_bottom:half'>{lang="onboard_next_staff_title"}</h2>
			<p class='ipsType_reset ipsType_normal'>{lang="onboard_next_staff"}</p>
		</div>
		<div class='ipsFlex-flex:00'>
			<a class="ipsButton ipsButton_light ipsButton_small sm:ipsMargin_bottom:half" href='{url="app=core&module=staff&controller=admin"}'>{lang="onboard_takeme_admins"}</a>
			<a class="ipsButton ipsButton_light ipsButton_small" href='{url="app=core&module=staff&controller=moderators"}'>{lang="onboard_takeme_mods"}</a>
		</div>
	</div>

	<div class='ipsBox ipsBox_shadowed ipsMargin_bottom ipsFlex sm:ipsFlex-fd:column sm:ipsFlex-ai:start ipsFlex-ai:center ipsFlex-jc:center ipsPadding:double'>
		<div class='cOnboardBox__stepIcon ipsFlex-flex:00 ipsType_center ipsMargin_right:double'>
			<i class='fa fa-paint-brush fa-lg'></i>
		</div>
		<div class='cOnboardBox__stepText ipsMargin_right:double sm:ipsMargin_vertical ipsFlex-flex:11'>
			<h2 class='ipsType_reset cOnboardBox__stepTitle ipsMargin_bottom:half'>{lang="onboard_next_themes_title"}</h2>
			<p class='ipsType_reset ipsType_normal'>{lang="onboard_next_themes"}</p>
		</div>
		<div class='ipsFlex-flex:00'>
			<a class="ipsButton ipsButton_light ipsButton_small" href='{url="app=core&module=customization&controller=themes"}'>{lang="onboard_takeme"}</a>
		</div>
	</div>

	{{if \IPS\Application::appIsEnabled( 'nexus' )}}

		<div class='ipsBox ipsBox_shadowed ipsMargin_bottom ipsFlex sm:ipsFlex-fd:column sm:ipsFlex-ai:start ipsFlex-ai:center ipsFlex-jc:center ipsPadding:double'>
			<div class='cOnboardBox__stepIcon ipsFlex-flex:00 ipsType_center ipsMargin_right:double'>
				<i class='fa fa-usd fa-lg'></i>
			</div>
			<div class='cOnboardBox__stepText ipsMargin_right:double sm:ipsMargin_vertical ipsFlex-flex:11'>
				<h2 class='ipsType_reset cOnboardBox__stepTitle ipsMargin_bottom:half'>{lang="onboard_next_nexus_title"}</h2>
				<p class='ipsType_reset ipsType_normal'>{lang="onboard_next_nexus"}</p>
			</div>
			<div class='ipsFlex-flex:00'>
				<a class="ipsButton ipsButton_light ipsButton_small sm:ipsMargin_bottom:half" href='{url="app=nexus&module=subscriptions&controller=subscriptions"}'>{lang="onboard_takeme_subs"}</a>
				<a class="ipsButton ipsButton_light ipsButton_small" href='{url="app=nexus&module=store&controller=packages"}'>{lang="onboard_takeme_packages"}</a>
			</div>
		</div>
	{{endif}}
</div>