<ips:template parameters="$online, $chart, $total" />
{{if \count( $online ) > 0}}
	<div class='ipsType_center ipsType_light ipsType_large'>
		{lang="onlineUsersDashboard_title" sprintf="$total" pluralize="$total"}
	</div>
	<div>{$chart|raw}</div>
{{else}}
	<div class='ipsType_center ipsType_light ipsType_large ipsFaded ipsFaded_more'>
		<i class='fa fa-group ipsType_huge'></i>
		<br>{lang="no_online_users"}
	</div>
{{endif}}
