<ips:template parameters="$select, $pagination, $members, $total" />

<div class="acpBlock">
<h1 class="ipsBox_titleBar">{lang="downloads_stats_downloader_count" pluralize="$total"}</h1></div>
<br>
{{if trim( $pagination )}}
	{$pagination|raw}
	<br><br>
{{endif}}
	<table class="ipsTable ipsTable_zebra">
		<thead>
			<tr>
				<th>{lang="member"}</th>
				<th>{lang="downloads"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $select as $row}}
				{{$member = \IPS\Member::constructFromData( $members[ $row['dmid'] ] );}}
				<tr>
					<td>{template="userPhoto" app="core" group="global" params="$member"} {$member->name}</td>
					<td><a href='{url="app=downloads&module=stats&controller=member&do=downloads&id={$member->member_id}&tab=downloads&&type%5Bd74394%5D=Table"}'>{$row['downloads']}</a></td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>
	<br>

	{$pagination|raw}