<ips:template parameters="$page" />

{{if \IPS\Settings::i()->clubs_header != 'sidebar'}}
	{template="header" group="clubs" app="core" params="$page->club, NULL, 'full', $page"}
{{endif}}

<h1 class='ipsType_pageTitle'>{$page->title}</h1>
<br>
<div id='elClubContainer'>
	<div class='ipsBox ipsPad'>
		<div class='ipsType_normal ipsType_richText ipsContained' id='elPageContent'>
			{$page->content|raw}
		</div>
	</div>
</div>