<ips:template parameters="$table, $headers, $rows" />
{{$softwareClass = $table->extra['softwareClass'];}}
{{foreach $rows as $r}}
	<form action='{url="app=convert&module=manage&controller=convert&do=runStep&id={$table->extra['appClass']->app_id}&method={$r['step_method']}"}' method='post' data-controller='convert.admin.convert.menu'>
		<tr class='ipsClearfix' data-keyNavBlock>
			{{foreach $r as $k => $v}}
				{{if $k === 'per_cycle'}}
					<td>
						<input type='text' name='per_cycle' value='{$v|raw}' size='5' style='width:50%'><br>
					</td>
				{{elseif $k === 'empty_local_data'}}
					<td>
						<input type='checkbox' name='empty_local_data' id='empty_local_data_{$r['step_method']}' value='1' /> <label for='empty_local_data_{$r['step_method']}'>{lang="empty_local_data"}</label>
					</td>
				{{elseif $k === 'step_method'}}
					<td>
                        <input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
						{{if \in_array( $r['step_method'], $table->extra['sessionData']['completed'] )}}
							<input class='ipsButton ipsButton_normal ipsButton_verySmall' type='submit' name='submit' value='{lang="convert_again"}' />
							{{if \IPS\IN_DEV == TRUE}}
								<a href='{url="app=convert&module=manage&controller=convert&do=emptyData&id={$table->extra['appClass']->app_id}&method={$r['step_method']}" csrf="true"}' class='ipsButton ipsButton_normal ipsButton_verySmall ipsButton_alternate' data-action='remove_converted_data'>{lang="remove_converted_data"}</a>
							{{endif}}
							{{if \in_array( $r['step_method'], $softwareClass::checkConf() )}}
								<br><input type='checkbox' name='reconfigure' id='reconfigure_{$r['step_method']}' value='1' /> <label for='reconfigure_{$r['step_method']}'>{lang="reconfigure"}</label>
							{{endif}}
						{{elseif \count( array_filter( $table->extra['menuRows'][$r['step_method']]['dependencies'], array( $table->extra['appClass'], 'dependencies' ) ) )}}
							<a href='#' class='ipsButton ipsButton_normal ipsButton_disabled ipsButton_verySmall' data-ipsTooltip title='{lang="cannot_convert_desc"}'>{lang="cannot_convert"}</a>
						{{elseif array_key_exists( $r['step_method'], $table->extra['sessionData']['working'] )}}
							<input type='hidden' name='continue' value='1' />
							<input type='submit' class='ipsButton ipsButton_normal ipsButton_verySmall' name='submit' value='{lang="continue_conversion"}' />
						{{else}}
							<input class='ipsButton ipsButton_normal ipsButton_verySmall' type='submit' name='submit' value='{lang="begin_conversion"}' />
						{{endif}}
						<div id='elReconvertForm_{$v}' class='ipsPad ipsHide'>
							{lang="confirm_reconvert"}<br>
							<ul>
								{{foreach $table->extra['menuRows'] AS $step}}
									{{if \in_array( $r['step_method'], $step['dependencies'] )}}
										<li>{lang="$step['step_method']"}</li>
									{{endif}}
								{{endforeach}}
							</ul><br>
							<input type='submit' class='ipsButton' name='submit' value='{lang="reconvert_button"}' />
						</div>
					</td>
				{{else}}
					<td class='{{if $k === 'photo'}}ipsTable_icon{{endif}} {{if $k === $table->mainColumn}}ipsTable_primary ipsType_break{{endif}} {{if $k === '_buttons'}}ipsTable_controls{{endif}}' {{if $k !== $table->mainColumn && $k !== '_buttons' && $k !== 'photo'}}data-title="{lang="{$table->langPrefix}{$k}"}"{{endif}}>
						{{if $k === '_buttons'}}
							{template="controlStrip" params="$v" group="global" app="core"}
						{{else}}
							{$v|raw}
						{{endif}}
					</td>
				{{endif}}
			{{endforeach}}
		</tr>
	</form>
{{endforeach}}