<ips:template parameters="$gatewayName" />
<div class="ipsType_richText ipsType_normal">
	<p>{lang="acp_notification_nexus_config_error_payoutmethod_desc" sprintf="$gatewayName"}</p>
</div>
<div class="ipsSpacer_top ipsSpacer_double">
	<a href='{url="app=nexus&module=payments&controller=payouts&do=settings"}' class="ipsButton ipsButton_primary ipsButton_verySmall">{lang="help_me_fix_this"}</a>
</div>