<ips:template parameters="$results" />

<div class="ipsGrid ipsGrid_collapsePhone">
	{{foreach $results as $streamId => $result}}
		<div class="ipsGrid_span4 ipsBox ipsSpacer_bottom">
			<h3 class="ipsBox_titleBar ipsType_blendLinks">
				<a href="{url="app=nexus&module=support&controller=requests&stream={$streamId}" csrf="true"}">{expression=" \IPS\nexus\Support\Stream::load( $streamId )->title"}</a>
			</h3>
			<div>
				{$result|raw}
			</div>
		</div>
	{{endforeach}}
</div>