<ips:template parameters="$transactions" />

<div class="ipsGrid" data-controller="nexus.admin.notifications.pendingTransactions">
	{{foreach $transactions as $transaction}}
		<div class="ipsGrid_span3 ipsBox ipsSpacer_bottom">
			<h3 class="ipsBox_titleBar ipsType_blendLinks">
				<a href="{$transaction->acpUrl()}">{$transaction->invoice->title} <span class="ipsType_small">#{$transaction->id}</span></a>
			</h3>
			<div class="ipsPad ipsPad_half">
				<div class='ipsGrid ipsPad ipsPad_half'>
					<div class="ipsGrid_span3 ipsType_center">
						<span class='ipsType_large'>{$transaction->amount}</span>
					</div>
					<div class="ipsGrid_span7">
						{{if $transaction->method}}
							{{if \in_array( $transaction->status, array( \IPS\nexus\Transaction::STATUS_PENDING, \IPS\nexus\Transaction::STATUS_WAITING ) )}}
								{lang="transaction_method_pending" sprintf="$transaction->method->_title"}
							{{else}}
								{lang="transaction_method" sprintf="$transaction->method->_title"}							
							{{endif}}
						{{else}}
							{lang="payment_received"}
						{{endif}}
						<br>
						<span class='ipsType_small'>
							{$transaction->date}
							{{if $transaction->gw_id}}
								<br>
								{lang="payment_reference"}: {{if $transaction->method and $url = $transaction->method->gatewayUrl( $transaction )}}<a href="{$url}" target="_blank" rel="noreferrer">{$transaction->gw_id}</a>{{else}}{$transaction->gw_id}{{endif}}<br>
							{{endif}}
						</span>
					</div>
				</div>
				<hr class="ipsHr ipsHr_small">
				<div class='ipsGrid ipsPad ipsPad_half'>
					<div class="ipsGrid_span3 ipsType_center">
						<a href="{$transaction->member->acpUrl()}"><img src='{$transaction->member->photo}' class='ipsUserPhoto ipsUserPhoto_tiny'></a>
					</div>
					<div class="ipsGrid_span7">
						<a class="ipsType_blendLinks" href="{$transaction->member->acpUrl()}">{$transaction->member->cm_name}</a><br>
						<span class='ipsType_small'>
							{$transaction->member->email}<br>
							{lang="transaction_customer_since" sprintf="$transaction->member->joined->localeDate()"}<br>
							{lang="transaction_spent" sprintf="$transaction->member->totalSpent()"}
						</span>
					</div>
				</div>
				{{if $transaction->fraud or $transaction->fraud_blocked}}
					<hr class="ipsHr ipsHr_small">
					<div class="ipsType_center">
						{{if $transaction->fraud}}
							<div class="{{if ( $transaction->fraud->riskScore !== NULL and $transaction->fraud->riskScore > 80 ) or ( $transaction->fraud->riskScore === NULL and $transaction->fraud->score > 8 )}}ipsType_warning{{endif}} ipsSpacer_top ipsSpacer_bottom ipsSpacer_half">
								{{if $transaction->fraud->riskScore !== NULL}}
									{$transaction->fraud->riskScore}%
								{{else}}
									{expression="round( $transaction->fraud->score * 10 )"}%
								{{endif}}
								{lang="possibility_of_fraud"}
							</div>
						{{endif}}
						{{if $transaction->fraud_blocked}}
							{$transaction->fraud_blocked->name}
						{{endif}}
					</div>
				{{endif}}
				{{if $buttons = array_filter( $transaction->buttons('n'), function( $k ) { return \in_array( $k, array( 'approve', 'review', 'void', 'refund' ) ); }, ARRAY_FILTER_USE_KEY )}}
					<hr class="ipsHr ipsHr_small">
					<div class="ipsType_center ipsSpacer_top">
						<ul class='ipsButton_split' data-role="buttons">
							{{foreach $buttons as $k => $button}}
								<li><a {{if !isset( $button['data']['ipsDialog'] )}}data-action="quickAction"{{else}}{{foreach $button['data'] as $_k => $v}}data-{$_k}="{$v}"{{endforeach}}{{endif}} title="{lang="$button['title']"}" data-ipsTooltip class="ipsButton ipsButton_small {{if $k === 'approve'}}ipsButton_positive{{elseif $k === 'review'}}ipsButton_intermediate{{else}}ipsButton_negative{{endif}}" href="{$button['link']->setQueryString( 'queueStatus', $transaction->status )}"><i class="fa fa-{$button['icon']}"></i></a></li>
							{{endforeach}}
						</ul>
					</div>
				{{endif}}
			</div>
		</div>
	{{endforeach}}
</div>