<ips:template parameters="$payout" />
<div class="ipsGrid ipsGrid_collapsePhone">
	<div class="ipsGrid_span7 ipsAreaBackground">
		<h2 class="ipsType_sectionTitle">{lang="payout_status"}</h2>
		<div class="ipsPad">
			<div class="ipsAreaBackground_light ipsPad ipsType_center">
				<p>{$payout->date}</p>
				<p>
					<span class="ipsType_veryLarge">{$payout->amount}</span><br>
					{lang="payout_method" sprintf="$payout->gateway"}
				</p>
				<p class="ipsType_light"><a class="ipsType_blendLinks" href="{url="app=core&module=members&controller=ip&ip={$payout->ip}"}">{lang="transaction_ip" sprintf="$payout->ip"}</a></p>
			</div>
			<div class="ipsType_center ipsType_veryLarge">
				<i class="fa fa-arrow-down"></i>
			</div>
			{{if $payout->status === $payout::STATUS_CANCELED}}
				<div class="ipsAreaBackground_light ipsPad ipsType_center">
					<p>
						{$payout->completed}
						{{if $payout->processed_by}}
							{lang="by"} {$payout->processed_by->name}
						{{endif}}
					</p>
					<p>
						<span class="ipsType_veryLarge"><i class="fa fa-times"></i></span><br>
						<span class="ipsType_large">{lang="payout_canceled"}</span>
					</p>
				</div>
			{{elseif $payout->status === $payout::STATUS_COMPLETE}}
				<div class="ipsAreaBackground_light ipsPad ipsType_center">
					<p>
						{$payout->completed}
						{{if $payout->processed_by}}
							{lang="by"} {$payout->processed_by->name}
						{{endif}}
					</p>
					<p>
						<span class="ipsType_veryLarge"><i class="fa fa-check-circle"></i></span><br>
						<span class="ipsType_large">{lang="payout_processed"}</span>
					</p>
					{{if $payout->gw_id}}
						<p>{$payout->gw_id}</p>
					{{endif}}
				</div>
			{{else}}
				<div class="ipsAreaBackground_light ipsPad ipsType_center">
					<p>
						<span class="ipsType_veryLarge"><i class="fa fa-pause"></i></span><br>
						<span class="ipsType_large">{lang="payout_pending"}</span>
					</p>
				</div>
			{{endif}}
		</div>
	</div>
	<div class="ipsGrid_span5">
		<div class="ipsAreaBackground_light">
			<h2 class="ipsType_sectionTitle"><a href="{$payout->member->acpUrl()}">{lang="po_member"}</a></h2>
			<div class='ipsPad_half ipsPhotoPanel ipsPhotoPanel_large ipsClearfix'>
				<a href="{$payout->member->acpUrl()}" class='ipsPos_left'><img src='{$payout->member->photo}' class='ipsUserPhoto ipsUserPhoto_medium'></a>
				<div>
					<span class="ipsType_large"><a class="ipsType_blendLinks" href="{$payout->member->acpUrl()}">{$payout->member->cm_name}</a></span><br>
					{$payout->member->email}<br>
				</div>
			</div>
		</div>
		<br><br>
		<div class="ipsAreaBackground_light">
			<h2 class="ipsType_sectionTitle">{lang="payout__data_{$payout->gateway}"}</h2>
			<div class='ipsPad'>
				{template="$payout->gateway" params="$payout" group="payouts"}
			</div>
		</div>
	</div>
</div>