<ips:template parameters="$title, $member, $form, $choice = FALSE"/>
<div class='ipsBox ipsPad'>
    <p class='ipsType_reset ipsType_center ipsType_huge'>
        <i class='fa fa-envelope'></i>
    </p>

    <h1 class='ipsType_veryLarge ipsType_center'>{$title}</h1>

    <div class='ipsType_large ipsType_center ipsType_richText'>
        {{if $choice == 'single'}}
        <div class="ipsMessage ipsMessage_info">{lang="stream_guest_unfollowed_thing" sprintf="$title"}</div>
        {{elseif $choice == 'all'}}
        <div class="ipsMessage ipsMessage_info">{lang="stream_guest_unfollowed_all"}</div>
        {{endif}}
    </div>
    <div class='ipsPadding'>
        {$form|raw}
    </div>
</div>
<p class='ipsType_center'>
    <a href='{url="/"}' class='ipsButton ipsButton_link ipsButton_small'>{lang='go_community_home'}</a>
</p>


