<ips:template parameters="$app" />

<div class="ipsPos_right ipsTree_row_cells ipsType_unbold ipsType_normal">
	&nbsp;
	<span class="ipsTree_row_cell">
		{{if \in_array( $app->directory, \IPS\IPS::$ipsApps )}}
			<span class="ipsType_success"><i class="fa fa-check"></i> {lang="invision"}</span>
		{{else}}
			<span class="ipsType_issue"><i class="fa fa-exclamation-triangle"></i> {lang="custom"}</span>
		{{endif}}
	</span>
</div>