<ips:template parameters="$k" />
<li class="ipsPad" id="googleApi_{$k}">
	<a href="{url="googlemaps_{$k}" ips="true"}" target="_blank" rel="noopener" class="ipsUserPhoto ipsUserPhoto_tiny">
		<img src="{resource="enhancements/google_maps/{$k}.png" app="core" location="admin"}" alt="{$k}">
	</a>
	<a href="{url="googlemaps_{$k}" ips="true"}" target="_blank" rel="noopener">
		{lang="googlemaps_api_{$k}"}
	</a>
</li>