<ips:template parameters="$item, $id, $baseUrl" />
<ul class='ipsList_inline ipsPos_right cMenuManager_tools'>
	<li class='ipsJS_hide'>
		<a href='{$baseUrl->setQueryString( array( 'do' => 'form', 'id' => $id ) )}' data-ipsTooltip title='{lang="edit_menu_item"}' data-action='editItem'>
			{lang="edit"}
		</a>
	</li>
	{{if $item instanceof \IPS\core\extensions\core\FrontNavigation\Menu}}
		<li>
			<a href='#' data-action='editDropdown' data-ipsTooltip title='{lang="menu_manager_dropdown_edit"}' class='ipsType_blendLinks'>
				<i class='fa fa-server'></i> <i class='fa fa-caret-right'></i>
			</a>
		</li>
	{{endif}}
	<li>
		<a href='{$baseUrl->setQueryString( array( 'do' => 'remove', 'id' => $id ) )->csrf()}' data-action='removeItem' data-ipsTooltip title='{lang="menu_manager_dropdown_delete"}' class='ipsType_blendLinks'>
			<i class='fa fa-times'></i></i>
		</a>
	</li>
</ul>