<?php

$lang = array(
	'delete_note' => 'Delete note',
	'save_note'	=> 'Save',
	'saving_note' => 'Saving...',
	'cancel_note' => 'Cancel',
	'count_image' => "{# [1:image][?:images]}",
	'delete_note_confirm' => "Are you sure you want to delete this note?",
	'new_album' => "Adding {{count}} to new album: <strong>{{album}}</strong>",
	'existing_album' => "Adding {{count}} to existing album: <strong>{{album}}</strong>",
	'unsaved_image_data' => "You haven't saved your changes for this image. Are you sure you want to switch image?",
	'unsaved_image_data_desc' => "Information for this image will be lost.",
	'images_without_data' => "You haven't added any information for {{count}}. Are you sure you want to continue?",
	'images_without_data_desc' => "You can edit the images later to update them.",
	'set_as_photo_confirm' => "Are you sure you want to update your profile photo?",
	'rebuildGalleryThumbnails' => "Rebuild existing thumbnails?",
	'rebuildGalleryThumbnailsBlurb' => "Rebuilding existing thumbnails is recommended when you upload a new watermark image or adjust your thumbnail dimensions",
	'rebuildGalleryThumbnailsYes' => "Yes",
	'rebuildGalleryThumbnailsNo' => "No",
	'uploader_add_images'		=> "Add Images",
	'confirmSubmitClose' => "Are you sure you want to exit? Any images you have uploaded won't be saved.",
	'addImages' => 'Add Images',
	'createAlbum' => 'Create Album',
	'existingAlbum' => 'Choose Existing Album',
	'chooseCategory' => 'Choose Category',
	'chooseAlbum' => 'Choose Album',
	'imageUploadErrors' => '{# [1:image][?:images]} had errors',
	'imageUploadErrorsDesc' => 'Correct the errors on the marked {!# [1:image][?:images]} and submit again.'
);
