<?php

$lang = array(
	'__app_gallery'						=> "Gallery",
	'frontnavigation_gallery'			=> "Gallery",
	'gallery_title'						=> "Gallery",
	'__indefart_gallery_image_comment'	=> "a comment on a gallery image",
	'__indefart_gallery_image'			=> "a gallery image",
	'__defart_gallery_image_comment'	=> "comment on a gallery image",
	'__defart_gallery_image_comment_plural'	=> "{!#[1:comment][?:comments]} on a gallery image",
	'__defart_gallery_image'			=> "gallery image",
	'__defart_gallery_image_plural'		=> "gallery {!#[1:image][?:images]}",
	'__indefart_gallery_album_comment'	=> "a comment on a gallery album",
	'__indefart_gallery_album'			=> "a gallery album",
	'__defart_gallery_album_comment'	=> "comment on a gallery album",
	'__defart_gallery_album_comment_plural'	=> "{!#[1:comment][?:comments]} on a gallery album",
	'__defart_gallery_album'			=> "gallery album",
	'__defart_gallery_album_plural'		=> "gallery {!#[1:album][?:albums]}",
	'__indefart_gallery_image_review'	=> "a review on a gallery image",
	'__defart_gallery_image_review'		=> "review on a gallery image",
	'__defart_gallery_image_review_plural'	=> "{!#[1:review][?:reviews]} on a gallery image",
	'__indefart_gallery_album_review'	=> "a review on a gallery album",
	'__defart_gallery_album_review'		=> "review on a gallery album",
	'__defart_gallery_album_review_plural'	=> "{!#[1:review][?:reviews]} on a gallery album",
	'module__gallery_stats'				=> "Statistics",
	'search_contextual_item_gallery_image'	=> "This Image",
	'album_user_own_activity_item'		=> 'Images added to %1$s owned by %2$s in ',
	'club_node_gallery'					=> "Club Images",
	'community_image_categories'		=> "Community Images",
	

	'menu__gallery_gallery'				=> "Gallery",
	'menu__gallery_gallery_categories'	=> "Categories",
	'menu__gallery_gallery_albums'		=> "Albums",
	'menu__gallery_stats'				=> "Gallery",
	'menu__gallery_stats_diskspace'		=> "Top Uploaders",
	'menu__gallery_stats_bandwidth'		=> "Bandwidth Usage",
	'menu__gallery_gallery_settings'	=> "Settings",
	'image'								=> "Image",
	'gallery_image'						=> "Gallery Image",
	'filestorage__gallery_Images'		=> "Gallery Images",
	'acp_search_title_gallery_Categories'	=> "Gallery Categories",
	'acp_search_title_gallery_Albums'	=> "Gallery Albums",
	'gallery_images'					=> "Gallery Images",
	'gallery_media'						=> "Gallery Videos",

	'block_gallery_Overview'			=> "Gallery Overview",
	'total_images'						=> "Total Images",
	'total_disk_spaceg'					=> "Total Diskspace Used",
	'total_albums'						=> "Total Albums",
	'largest_image'						=> "Largest Image",
	'most_viewed_image'					=> "Most Viewed Image",

	'editor__gallery_Albums'			=> "Gallery Albums",
	'editor__gallery_Categories'		=> "Gallery Categories",
	'editor__gallery_Gallery'			=> "Image Comments",
	'editor__gallery_Images'			=> "Gallery Images",
	'editorMedia_gallery_Images'		=> "Gallery Images",
	
	'member_gallery_image'				=> "Keep using my Gallery Image",
	
	'member_restrictions__gallery_Gallery' => "Gallery",
	'restriction_no_gallery_access'		=> "Restricted from accessing Gallery",
	'restriction_no_gallery_uploads'	=> "Restricted from uploading Gallery images",
	'content_stats__gallery_Gallery'	=> "Gallery",

	/* !Groups */
	'group__gallery_Gallery'			=> "Gallery",
	'gallery_album_permissions'			=> "Album Restrictions",
	'g_create_albums'					=> "Can create albums?",
	'g_create_albums_private'			=> "Can create private albums?",
	'g_create_albums_private_desc'		=> "Private albums are albums that only the creator can view",
	'g_create_albums_fo'				=> "Can create restricted access albums?",
	'g_create_albums_fo_desc'			=> "Restricted access albums are albums that only the creator and designated users can view",
	'g_album_limit'						=> "Maximum number of albums",
	'g_img_album_limit'					=> "Maximum number of images per album",
	'gallery_restrictions'				=> "Usage Restrictions",
	'g_movies'							=> "Can upload movies?",
	'g_movie_size'						=> "Maximum size of movies",
	'g_max_upload'						=> "Maximum size of images",
	'g_max_transfer'					=> "Maximum bandwidth consumption",
	'g_max_views'						=> "Maximum image and movie views",
	'gallery_suffix_kb'					=> "kB",
	'gallery_suffix_day'				=> "per day",
	'gallery_suffix_kb_day'				=> "kB/day",
	'gallery_requires_log'				=> "These settings rely on the detailed bandwidth log which can be disabled in the Gallery Settings and cleared periodically. If using these settings, it is recommended that you leave the log turned on and set not to clear more often than every 48 hours otherwise you may experience unexpected behavior.",
	'g_download_original'				=> "Can download original image?",
	'g_download_original_desc'			=> "Users will still be able to download the large size image through their browser",
	'g_download_raw'					=> "Yes, without watermark",
	'g_download_watermarked'			=> "Yes, with watermark",
	'g_download_none'					=> "No",


	/* !ACP Restrictions */
	'r__albums'							=> "Albums",
	'r__albums_manage'					=> "Can view albums?",
	'r__diskspace'						=> "Diskspace",
	'r__diskspace_manage'				=> "Can view diskspace statistics?",
	'r__bandwidth'						=> "Bandwidth",
	'r__bandwidth_manage'				=> "Can view bandwidth statistics?",

	/* !Categories */
	'gcategory_parent_id'				=> "Parent Category",
	'category_sort_options'				=> "Album sort order",
	'category_sort_options_img'			=> "Image sort order",
	'category_approve_img'				=> "Images must be approved?",
	'category_comments_and_ratings'		=> "Comments and Ratings",
	'category_allow_comments'			=> "Allow comments?",
	'category_approve_com'				=> "Comments must be approved?",
	'gcategory_allow_rating'			=> "Allow ratings?",
	'category_can_tag'					=> "Allow tags?",
	'category_tag_prefixes'				=> "Allow prefixes?",
	'category_allow_albums_club'		=> "Allow albums?",
	'category_allow_albums'				=> "Albums",
	'category_allow_albums_desc'		=> "You can control which groups are allowed to create albums from <a href='{internal.app=core&module=members&controller=groups}'>Group Settings</a>. If you require albums but the user does not have permission to create albums, they will not be able to submit to this category.",
	'cat_no_allow_albums'				=> "Do not allow albums",
	'cat_no_allow_albums_desc'			=> "Images can only be submitted directly to the category",
	'cat_allow_albums'					=> "Allow albums",
	'cat_allow_albums_desc'				=> "Images can be submitted directly to the category or to albums within the category",
	'cat_require_albums'				=> "Require albums",
	'cat_require_albums_desc'			=> "Images can only be submitted to albums within the category",
	'category_watermark'				=> "Watermark images?",
	'category_preset_tags'				=> "Preset tags",
	'category_preset_tags_desc'			=> "If using a closed system, users will have to choose from these tags. If using an open system, tags entered here will show as suggestions.",
	'perm__view'						=> "See Category",
	'perm__read'						=> "View Images",
	'perm__add'							=> "Upload Images",
	'perm__comment'						=> "Comment",
	'perm__rate'						=> "Rate Images",
	'perm__review'						=> "Review Images",
	'perm__reply'						=> "Comment",
	'category_rules'					=> "Rules",
	'category_show_rules'				=> "Show rules?",
	'category_show_rules_none'			=> "Do not show",
	'category_show_rules_link'			=> "Show link to rules",
	'category_show_rules_link_desc'		=> "The rules will be shown on a separate page with a link added in the category header",
	'category_show_rules_full'			=> "Show rules",
	'category_show_rules_full_desc'		=> "The rules will be shown inline in the category header",
	'category_rules_title'				=> "Rules title",
	'category_rules_text'				=> "Rules",
	'category_rules_link'				=> "Link to rules",
	'node_move_catsalbums'				=> "Move child categories and albums to",
	'node_move_subalbums'				=> "Move albums to",
	'node_mass_move_delete_albums'		=> "Move albums to / Delete",
	'node_delete_children_catsalbums'	=> "Delete child categories and albums",
	'node_delete_children_cats'			=> "Delete child categories",
	'node_delete_children_albums'		=> "Delete albums",
	'delete_or_move_pick_one'			=> "If you choose not to delete images in this category, you must select a new category or album to move them to instead",
	'acplog__catalbum_mass_move'		=> "Mass Moved %s albums from %s to %s",
	'acplog__catalbum_mass_delete'		=> "Mass Deleted %s albums From %s",
	'galnode_mass_content_move_blurb'	=> "<strong>%s albums</strong> will be moved to %s",
	'galnode_mass_content_delete_blurb'	=> "<strong>%s albums</strong> will be <strong>deleted</strong>.",
	'error_messages'					=> "Error Messages",
	'category_permission_custom_error'	=> "Custom permission denied message",
	'category_permission_custom_error_desc'	=> "This error message will be shown to anyone who can browse the category but cannot view images within it",
	'gallery_permerror_placeholder'		=> "Add an error message...",
	'image_category_id'					=> "Category",
	'node_no_parentg'					=> "No Parent",
	'category_allow_reviews'			=> "Allow reviews?",
	'category_review_moderate'			=> "Reviews must be approved?",

	/* !Albums */
	'albums'							=> "Albums",
	'album_settings'					=> "Settings",
	'album_name'						=> "Name",
	'album_description'					=> "Description",
	'album_owner'						=> "Owner's Name",
	'album_category'					=> "Category",
	'album_sort_options'				=> "Default sort order",
	'album_comments_and_ratings'		=> "Comments and Ratings",
	'album_allow_comments'				=> "Allow comments on images?",
	'album_allow_rating'				=> "Allow ratings?",
	'album_allow_reviews'				=> "Allow reviews of images?",
	'album_use_comments'				=> "Allow comments on this album?",
	'album_use_reviews'					=> "Allow reviews of this album?",
	'album_type'						=> "Privacy",
	'album_public'						=> "Everyone can see this album",
	'album_private'						=> "Only I can see this album",
	'album_private_mod'					=> "Only the owner can see this album",
	'album_private_badge'				=> "Private album",
	'album_friend_only'					=> "I want to choose who can see this album",
	'album_submit_type'					=> "Submissions",
	'album_submit_access_members'		=> "Allowed members",
	'album_submit_access_groups'		=> "Allowed groups",
	'album_friend_only_badge'			=> "Invite-only album",
	'album_allowed_access'				=> "Members with access",
	'album_submittype_owner'			=> "Only I can submit to this album",
	'album_submittype_public'			=> "Anyone can submit to this album",
	'album_submittype_groups'			=> "I want to choose which groups can submit to this album",
	'album_submittype_members'			=> "I want to choose which members can submit to this album",
	'album_submittype_club'				=> "Anyone in this club can submit to this album",
	'set_album_owner'					=> "Owner",
	'set_album_owner_me'				=> "This album is for me",
	'set_album_owner_other'				=> "This album is for someone else",
	'album_sort_caption'				=> "Caption",

	/* !Moderation */
	'modperms__core_Content_gallery_Image'	=> "Gallery Images",
	'modperms__core_Content_gallery_Album_Item'	=> "Gallery Albums",
	'gallery_categories'					=> "Categories",
	'can_pin_gallery_image'					=> "Can pin images?",
	'can_unpin_gallery_image'				=> "Can unpin images?",
	'can_feature_gallery_image'				=> "Can feature images?",
	'can_unfeature_gallery_image'			=> "Can unfeature images?",
	'can_move_gallery_image'				=> "Can move images?",
	'can_move_gallery_image_desc'			=> "Will be able to move images only between the categories they can create new content within.",
	'can_lock_gallery_image'				=> "Can lock images?",
	'can_unlock_gallery_image'				=> "Can unlock images?",
	'can_reply_to_locked_gallery_image'		=> "Can comment on locked images?",
	'can_edit_gallery_image'				=> "Can edit images?",
	'can_hide_gallery_image'				=> "Can hide images?",
	'can_unhide_gallery_image'				=> "Can unhide images?",
	'can_view_hidden_gallery_image'			=> "Can view hidden images?",
	'can_delete_gallery_image'				=> "Can delete images?",
	'can_edit_gallery_image_comment'		=> "Can edit comments?",
	'can_hide_gallery_image_comment'		=> "Can hide comments?",
	'can_unhide_gallery_image_comment'		=> "Can unhide comments?",
	'can_view_hidden_gallery_image_comment'	=> "Can view hidden comments?",
	'can_delete_gallery_image_comment'		=> "Can delete comments?",

	'can_feature_gallery_album'				=> "Can feature albums?",
	'can_unfeature_gallery_album'			=> "Can unfeature albums?",
	'can_edit_gallery_album'				=> "Can edit albums?",
	'can_hide_gallery_album'				=> "Can hide albums?",
	'can_unhide_gallery_album'				=> "Can unhide albums?",
	'can_view_hidden_gallery_album'			=> "Can view hidden albums?",
	'can_move_gallery_album'				=> "Can move albums?",
	'can_move_gallery_album_desc'			=> "Will be able to move albums only between the categories they can create new content within.",
	'can_lock_gallery_album'				=> "Can lock albums?",
	'can_unlock_gallery_album'				=> "Can unlock albums?",
	'can_reply_to_locked_gallery_album'		=> "Can reply to locked albums?",
	'can_add_item_message_gallery_album'	=> "Can add messages to albums?",
	'can_edit_item_message_gallery_album'	=> "Can edit messages on albums?",
	'can_delete_item_message_gallery_album'	=> "Can delete messages on albums?",
	'can_delete_gallery_album'				=> "Can delete albums?",
	'can_edit_gallery_album_comment'		=> "Can edit album comments?",
	'can_hide_gallery_album_comment'		=> "Can hide album comments?",
	'can_unhide_gallery_album_comment'		=> "Can unhide album comments?",
	'can_view_hidden_gallery_album_comment'	=> "Can view hidden album comments?",
	'can_delete_gallery_album_comment'		=> "Can delete album comments?",
	'can_edit_gallery_album_review'			=> "Can edit album reviews?",
	'can_hide_gallery_album_review'			=> "Can hide album reviews?",
	'can_unhide_gallery_album_review'		=> "Can unhide album reviews?",
	'can_view_hidden_gallery_album_review'	=> "Can view hidden album reviews?",
	'can_delete_gallery_album_review'		=> "Can delete album reviews?",

	'can_edit_gallery_image_review'			=> "Can edit reviews?",
	'can_hide_gallery_image_review'			=> "Can hide reviews?",
	'can_unhide_gallery_image_review'		=> "Can unhide reviews?",
	'can_view_hidden_gallery_image_review'	=> "Can view hidden reviews?",
	'can_delete_gallery_image_review'		=> "Can delete reviews?",
	
	'can_feature_comments_gallery_image'			=> "Can recommend comments on an image?",
	'can_unfeature_comments_gallery_image'			=> "Can remove comment recommendations on an image?",
	'can_add_item_message_gallery_image'			=> "Can add messages to images?",
	'can_edit_item_message_gallery_image'			=> "Can edit messages on images?",
	'can_delete_item_message_gallery_image'			=> "Can delete messages on images?",

	/* !Settings */
	'acplogs__gallery_settings'				=> "Gallery settings updated",
	'acplogs__gallery_rebuilt'				=> "Images rebuild tool run.",
	'gallery_dims_explanation'				=> "Copies of all images uploaded to the gallery are created at different sizes and are then used as appropriate in the interface throughout the gallery. You can control the maximum dimensions of each size below.",
	'gallery_large_dims'					=> "Large image dimensions",
	'gallery_small_dims'					=> "Thumbnail image dimensions",
	'gallery_use_square_thumbnails'			=> "Use square thumbnails",
	'gallery_watermark_path'				=> "Watermark image",
	'gallery_watermark_path_desc'			=> "The image provided will be overlaid on all gallery images (for example, to show a copyright message). Be aware that individual categories can disable the watermark on images. For best results, use a small image with a transparent background.",
	'gallery_watermark_images'				=> "Images to watermark",
	'gallery_use_watermarks'				=> "Watermark images?",
	'gallery_watermark_large'				=> "Large images",
	'gallery_watermark_small'				=> "Thumbnail images",
	'gallery_bandwidth'						=> "Bandwidth Logging",
	'gallery_detailed_bandwidth'			=> "Store detailed bandwidth logs",
	'gallery_detailed_bandwidth_desc'		=> "Enabling this setting will cause Gallery image views to tracked. You can then use the bandwidth logs to see how much bandwidth image views consume over periods of time, and you can view bandwidth statistics on a per-member basis when editing members.",
	'gallery_bandwidth_period'				=> "Keep logs for",
	'gallery_bandwidth_period_desc'			=> "Detailed bandwidth logs older than this timeframe will be pruned to improve performance. Certain statistics requiring these logs will no longer be available once the bandwidth logs are pruned.",
	'gallery_options'						=> "General Options",
	'gallery_rss_enabled'					=> "Enable latest images RSS feed",
	'gallery_rebuildimages'					=> "Rebuilding images",
	'rebuilding_gallery_images'				=> "Rebuilding gallery images",
	'cleaning_up_gallery_images'			=> "Cleaning up Gallery images ",
	'gallery_maps_default'					=> "Enable maps by default",
	'gallery_maps_default_desc'				=> "Users can choose whether or not to show a map next to images that have geolocation data embedded into the image. This option controls whether those maps are enabled by default or not, however users can override this preference while submitting their images.",

	/* !Member Settings */
	'member__gallery_Images'				=> "Gallery",
	'remove_gallery_access'					=> "Allowed to access gallery?",
	'remove_gallery_upload'					=> "Allowed to upload images?",
	'gallery_stats'							=> "View Gallery Statistics",
	'history_restrictions_remove_gallery_access_1'		=> "disabled ability to access Gallery",
	'history_restrictions_remove_gallery_access_0'		=> "restored ability to access Gallery",
	'history_restrictions_remove_gallery_upload_1'		=> "disabled ability to upload Gallery images",
	'history_restrictions_remove_gallery_upload_0'		=> "restored ability to upload Gallery images",

	/* !Stats */
	'deleted_image'							=> "Deleted image",
	'bandwidth'								=> "Bandwidth",
	'image_id'								=> "Image",
	'bdate'									=> "Date",
	'bsize'									=> "Image size",
	'bandwidth_stats'						=> "Bandwidth Usage",
	'gallery_images'						=> "Images",
	'images_submitted'						=> "Images Submitted",
	'gdiskspace_used'						=> "Diskspace Used",
	'gaverage_filesize'						=> "Average Filesize",
	'number_of_views'						=> "Number of Views *",
	'gallery_bandwidth_used'				=> "Bandwidth Used *",
	'bandwidth_use_gallery'					=> "Bandwidth Use",
	'images_stat_of_total'					=> "%s (%d%% of total)",
	'images_stat_of_total_link'				=> "%s (%d%% of total) %s",
	'images_stat_average'					=> "%s (average for all users: %s)",
	'gallery_stats_disclaimer'				=> "* This statistic comes from the bandwidth log which may be disabled or set to be pruned periodically.",
	'gallery_graph_disclaimer'				=> "This data comes from the bandwidth log which may be disabled or set to be pruned periodically.",
	'member_images_chart'					=> "%s's Image Statistics",
	'gallery_stats_uploader_count'			=> "{# [1:member][?:members]} uploaded images.",

	'ad_image_lightbox'						=> "In the Gallery image lightbox",

	/* !Front End */
	'embed_gallery_album'					=> "A gallery album by %s",
	'embed_gallery_image'					=> "A gallery image by %s",
	'module__gallery_gallery'				=> "Gallery",
	'add_gallery_image'						=> "Add Images",
	'add_gallery_image_movies'				=> "Add Images or Movies",
	'submit_first_image'					=> "Add the first image",
	'browse_categories'						=> "Browse categories",
	'save_submit_images'					=> "Save images",
	'submit_all_images'						=> "Submit all images",
	'allowed_file_types_link'				=> "Allowed file types",
	'gal_notification_options'				=> "Notification settings",
	'submit_help_info'						=> "Select an image to edit its details.",
	'add_credit'							=> "Add a credit",
	'add_copyright'							=> "Add a copyright",
	'submit_go_back'						=> "Save details",
	'image_info_saved'						=> "Image information saved",
	'gallery_submit_prefix_album'			=> "Uploading to album \"%s\"",
	'gallery_submit_prefix_cat'				=> "Uploading to category \"%s\"",
	'loc_gallery_adding_image'				=> "Uploading an image",
	'loc_gallery_adding_image_action'		=> "%s is uploading an image",
	'upload_more_images'					=> "Upload more images",
	'select_your_images'					=> "Select your images",
	'select_your_movies'					=> "Select your movies",
	'upload_more_movies'					=> "Upload more movies",
	'image_title'							=> "Caption",
	'image_ipaddress'						=> "IP Address",
	'image_tags'							=> "Tags",
	'image_auto_follow'						=> "",
	'image_auto_follow_suffix'				=> "Follow this image",
	'image_description'						=> "Description",
	'image_credit_info'						=> "Credit",
	'image_credit_info_desc'				=> "If credit must be provided for use of the image, supply the source of the image",
	'image_copyright'						=> "Copyright",
	'image_pending_approval'				=> "This image has not yet been approved and is only visible to staff",
	'image_details'							=> "About this image",
	'manage_image'							=> "Manage Image",
	'report_image'							=> "Report image",
	'manage_album'							=> "Manage album",
	'report_album'							=> "Report album",
	'image_uploaded_by'						=> "Uploaded by %s",
	'image_category'						=> "Category",
	'image_album'							=> "Album",
	'image_new_album'						=> "Create new album?",
	'image__comment_placeholder'			=> "Add a comment...",
	'image_submit_comment'					=> "Submit Comment",
	'map_enabled'							=> "Show map?",
	'map_enabled_lightbox'					=> "Show map?",
	'map_privacy'							=> "Map privacy",
	'set_image_as'							=> "Set as",
	'loc_gallery_browsing'					=> "Browsing Gallery",
	'loc_gallery_browsing_action'			=> "%s is browsing the gallery",
	'loc_gallery_browsing_categories'		=> "Browsing gallery categories",
	'loc_gallery_browsing_categories_action'=> "%s is browsing gallery categories",
	'featured_images'						=> "Featured Images",
	'new_images'							=> "New Images",
	'new_image_comments_notification'				=> "Notify me of comments on these images",
	'images_no_number'						=> "{!# [1:image][?:images]}",
	'loc_gallery_viewing_image'				=> "Viewing image: %s",
	'loc_gallery_viewing_image_action'		=> "%s is viewing an image",
	'loc_gallery_viewing_category'			=> "Viewing category: %s",
	'loc_gallery_viewing_category_action'	=> "%s is browsing a gallery category",
	'loc_gallery_viewing_album'				=> "Viewing album: %s",
	'loc_gallery_viewing_album_action'		=> "%s is viewing an album",
	'gallery_rss_title'						=> "Latest Images",
	'gallery_rss_title_container'			=> "Latest Images: %s",
	'gallery_rss_offline'					=> "This RSS feed is disabled",
	'gallery_rss_offline_admin'				=> "The Gallery option \"Enable latest images RSS feed\" is currently disabled. Toggle this option to yes in the admin control panel to enable the latest images RSS feed.",
	'no_images_in_album'					=> "There are no images in this album yet",
	'no_images_in_cat'						=> "There are no images in this category yet",
	'image_gps_show'						=> "Show map?",
	'image_gps_show_desc'					=> "You can optionally display a map for this image showing where it was taken",
	'view_this_image'						=> "View the image %s",
	'view_this_video'						=> "View the video %s",
	'view_this_album'						=> "View the album %s",
	'num_images'							=> "{# [1:image][?:images]}",
	'num_images_in_album'					=> "{# [1:image][?:images]} in this album",
	'album_latest_images'					=> "Latest Images",
	'rotate_image'							=> "Rotate",
	'rotate_left'							=> "Rotate Left",
	'rotate_right'							=> "Rotate Right",
	'gallery_image_rotated'					=> "The image has been rotated",
	'add_more_images'						=> "Add more images",
	'set_cover_photo'						=> "Set cover photo",
	'set_for_album'							=> "Set for album?",
	'set_for_category'						=> "Set for category?",
	'cover_category_only'					=> "Category cover",
	'cover_category'						=> "Set as category cover photo",
	'cover_album_only'						=> "Album cover",
	'cover_album'							=> "Set as album cover photo",
	'cover_both'							=> "Both Category &amp; Album cover",
	'set_as_profile_photo'					=> "This image has been set as your profile photo",
	'set_as_category_done'					=> "This image has been set as the category cover",
	'set_as_album_done'						=> "This image has been set as the album cover",
	'set_as_both_done'						=> "This image has been set as the category and album covers",
	'find_users_images'						=> "View %s's images",
	'change_author'							=> "Change Author",
	'change_author_ititle'					=> "Change the member who owns this image",
	'gallery_metadata'						=> "Photo Information",
	'gallery_no_metadata'					=> "No extra image data",
	'view_all_photo_info'					=> "View all photo EXIF information",
	'view_photo_info'						=> "View photo EXIF information",
	'gallery_images_no_more'				=> "You can't upload any more images to this album.",
	'gallery_images_too_many'				=> "You can only upload {# [1:more image][?:more images]} to this album.",
	'gallery_images_too_many_at_once'		=> "You can only upload 100 images at a time.",
	'gallery_image_or_movie'				=> "You must upload at least one image or one movie",
	'image_thumbnail'						=> "Thumbnail",
	'maximum_daily_views'					=> "You have reached the maximum number of daily image and movie views that the administrator has allowed",
	'maximum_daily_views_admin'				=> "You have reached the value specified for your user group for 'Maximum image and movie views' on the Gallery tab within the last 24 hours",
	'maximum_daily_transfer'				=> "You have reached the maximum amount of bandwidth that the administrator has allowed for image and video viewing in the gallery",
	'maximum_daily_transfer_admin'			=> "You have reached the value specified for your user group for 'Maximum bandwidth consumption' on the Gallery tab within the last 24 hours",
	'move_to_category'						=> "Move to category",
	'move_to_album'							=> "Move to album",
	'move_to_new_album'						=> "New Album",
	'imageLocation'							=> "Upload new image",
	'mediaLocation'							=> "Upload new media file",
	'viewfilter_thumbnails'					=> "Thumbnails",
	'viewfilter_large'						=> "Large Images",
	'set_gallery_image_photo'				=> "Set as my profile photo",
	'view_fullsize_image'					=> "View Full Image",
	'no_photo_for_media'					=> "You can only set an image as your profile photo image",
	'delete_album'							=> "Delete Album",
	'edit_album'							=> "Edit Album",
	'sort_album_count_comments'					=> "Most Image Comments",
	'sort_album_rating_aggregate'			=> "Highest Rated",
	'sort_album_name'						=> "Album Name",
	'sort_album_count_imgs'					=> "Most Images",
	'delete_images'							=> "Delete images?",
	'move_image_category'					=> "Move images to category",
	'move_image_album'						=> "Move images to album",
	'map_not_being_shown'					=> "This image is not currently being displayed to other users.",
	'next_image_set'						=> "Continue",
	'uploaded'								=> "Uploaded",
	'in_album'								=> "In album: ",
	'image__save'							=> "Save Image",
	'gallery_move_title'					=> "Move this image",
	'feature_title_image'					=> "Feature this image",
	'unfeature_title_image'					=> "Unfeature this image",
	'pin_title_image'						=> "Pin this image",
	'unpin_title_image'						=> "Unpin this image",
	'hide_title_image'						=> "Hide this image",
	'unhide_title_image'					=> "Unhide this image",
	'lock_title_image'						=> "Lock this image",
	'unlock_title_image'					=> "Unlock this image",
	'approve_title_image'					=> "Approve this image",
	'delete_title_image'					=> "Delete this image",
	'galleryalbum_move_title'				=> "Move this album",
	'feature_title_album'					=> "Feature this album",
	'unfeature_title_album'					=> "Unfeature this album",
	'hide_title_album'						=> "Hide this album",
	'unhide_title_album'					=> "Unhide this album",
	'lock_title_album'						=> "Lock this album",
	'unlock_title_album'					=> "Unlock this album",
	'approve_title_album'					=> "Approve this album",
	'upload_image_too_big'					=> "Images must be smaller than %s.",
	'upload_movie_too_big'					=> "Movies must be smaller than %s.",
	'unread_cat_images'						=> "This category has new images",
	'image_tools'							=> "Image Tools",
	'image_share'							=> "Share",
	'cannot_download_original_image'		=> "You do not have permission to download images",

	'gallery_unset_cover'					=> "Remove cover photo",
	'gallery_unset_cover_error'				=> "You do not have permission to remove the cover photo",
	'gallery_cover_photo_isunset'			=> "The cover photo has been removed",

	'cat_img_count'							=> "{# [1:image][?:images]}",
	'cat_album_count'						=> "{# [1:album][?:albums]}",
	'cat_comment_count'						=> "{# [1:comment][?:comments]}",
	'image_review_count'					=> "{# [1:review][?:reviews]}",
	'image_comment_count'					=> "{# [1:comment][?:comments]}",

	'from_the_album'						=> "From the album: ",
	'from_the_category'						=> "From the category: ",
	'album_created_by'						=> "Album created by",
	'album_everything_seen'					=> "You've seen everything in this album",
	'album_new_content'						=> "This album has unseen content",
	'camera_information'					=> "Camera information",
	'add_image_note'						=> "Add note",
	'view_in_lightbox'						=> "View in lightbox",
	'view_entire_album'						=> "View the entire %s album",
	'events_in_album'						=> "{!# [1:Event][?:Events]} in this album",
	'notes_no_permission'					=> "You do not have permission to edit notes for this image",

	'view_as_thumbnails'					=> "Show as thumbnails",
	'view_as_large'							=> "Show as large previews",
	'view_as_list'							=> "Show as list",

	'gallery_image_comment'					=> "Image Comment",
	'gallery_image_pl'						=> "Images",
	'gallery_image_pl_lc'					=> "images",
	'gallery_album_item_pl'					=> "Albums",
	'gallery_album_item_pl_lc'				=> "albums",
	'gallery_image_comment_pl'				=> "Image Comments",
	'gallery_image_comment_pl_lc'			=> "image comments",

	'gallery_image_review'					=> "Image Review",
	'gallery_image_review_pl'				=> "Image Reviews",
	'gallery_image_review_pl_lc'			=> "image reviews",

	'gallery_album'							=> "Album",
	'gallery_album_pl'						=> "Albums",
	'gallery_album_pl_lc'					=> "albums",
	'gallery_album_comment'					=> "Album Comment",
	'gallery_album_comment_pl'				=> "Album Comments",
	'gallery_album_comment_pl_lc'			=> "album comments",
	'gallery_image_comments_s'				=> "{# [1:image comment][?:image comments]}",

	'gallery_album_review'					=> "Album Review",
	'gallery_album_review_lc'				=> "album review",
	'gallery_album_review_pl'				=> "Album Reviews",
	'gallery_album_review_pl_lc'			=> "album reviews",
	
	'image_locked_can_comment'				=> "This image is locked, but your permissions allow you to add new comments.",
	'image_locked_cannot_comment'			=> "This image is now closed to further comments.",

	'album_locked_can_comment'				=> "This album is locked, but your permissions allow you to add new comments.",
	'album_locked_cannot_comment'			=> "This album is now closed to further comments.",

	'gallery_edit_details'				=> "Edit Details",
	'gallery_edit_details_title'		=> "Edit this image's details",

	'image_rating_value'				=> "Your rating",
	'image_review_text'					=> "Your review",
	'image__review_placeholder'			=> "Add a review...",
	

	/* !Sidebar */
	'block_imageFeed'					=> "Image Feed",
	'block_imageFeed_desc'				=> "Create a feed of images",
	'widget_feed_container_gallery_image'	=> "Categories",
	'block_galleryStats'				=> "Gallery Statistics",
	'block_galleryStats_desc'			=> "Shows gallery application statistics",
	'block_recentComments'				=> "Recent Comments",
	'block_recentComments_desc'			=> "Shows newest comments",
	'total_images_front_h'				=> "{!#[1:Image][?:Images]}",
	'total_images_front_v'				=> "{!#[?:Images]}",
	'stats_total_comments_v'			=> "{!#[1:Comment][?:Comments]}",
	'stats_total_comments_h'			=> "{!#[?:Comments]}",
	'total_albums_h'					=> "{!#[1:Album][?:Albums]}",
	'total_albums_v'					=> "{!#[?:Albums]}",
	'latest_image'						=> "Latest Image",
	'block_recentImageReviews'			=> "Image Reviews",
	'block_recentImageReviews_desc'		=> "Shows the most recent image reviews",
	'block_recentImages'				=>	"Recent Images",
	'block_recentImages_desc'			=>	"Show newest Images",
	'block_albums'						=> "Album Feed",
	'block_albums_desc'					=> "Create a listing of albums",
	'widget_feed_container_gallery_album'	=> "Category",

	'profile_gallery_album'				=> "Albums",
	'gallery_category_id'				=> "Category",
	'profile_gallery_gallery'			=> "Albums",
	'profile_gallery_galleryImages'		=> "Images",

	/* !Submit screen */
	'choose_album'						=> "Choose Album",
	'choose_category'					=> "Choose Category",
	'upload_images'						=> "Upload Images",
	'image_information'					=> "Add Information",
	'process'							=> "Finish",
	'create_new_album'					=> "Create Album",
	'choose_selected_album'				=> "Use Selected Album",
	'submit_breadcrumb'					=> "Submit Image",
	'submit_directly_to'				=> "Post directly to the category %s",
	'submit_new_album'					=> "Create a brand new album for your images",
	'choose_existing_album_desc'		=> "Choose one of your existing albums",
	'use_plain_editor'					=> "Use plain editor",
	'use_rte_editor'					=> "Use rich text editor",
	'album_create_owner'				=> "Ownership",
	'album_create_privacy'				=> "Privacy",
	'album_create_features'				=> "Album Features",
	'add_information'					=> "Add Image Information",
	'add_information_desc'				=> "Add titles and descriptions to your images",
	'add_information_plus_album_desc'	=> "Add titles and descriptions to your images, and optionally add them to an album",
	'images_you_uploaded'				=> "Images you uploaded",
	'movies_you_uploaded'				=> "Videos you uploaded",
	'media_you_uploaded'				=> "Files you uploaded",
	'new_album' 						=> "Adding {# [1:image][?:images]} to album: <strong>%s</strong>",
	'with_all_images'					=> "With all images",
	'create_album'						=> "Create Album",
	'create_an_album'					=> "Create an album",
	'add_to_existing_album'				=> "Add to an existing album",
	'choose_existing_album'				=> "Choose Existing Album",
	'change_album'						=> "change",
	'set_tags'							=> "Set tags...",
	'set_copyright'						=> "Set copyright...",
	'set_copyright_all'					=> "Set copyright on all",
	'set_credit_all'					=> "Set credit on all",
	'set_tags_all'						=> "Set tags on all",
	'notify_me'							=> "Notify me when comments are posted",
	'album_limit_message'				=> "Albums can contain up to <strong>{# [1:image or video][?:images or videos]}</strong>, but you've uploaded <strong>%d</strong>. Only the first {# [1:image or video][?:images or videos]} will be added to the album when you save; any remaining will be removed.",
	'too_many_images'					=> "Too many images",
	'editing_image'						=> "Editing Image",
	'editing_movie'						=> "Editing Video",
	'ready_to_submit'					=> "Ready to submit",
	'ready_to_submit_blurb'				=> "Click <em>Finish editing images</em> to submit your images to our gallery.",
	'x_of_y'							=> "%d of %d",
	'continue_next_image'				=> "Save this image",
	'finish_all_images'					=> "Finish and save all images",
	'image_info_finish'					=> "Finish editing images",
	'add_gallery_image_desc'			=> "Choose the images you want to add to the gallery",
	'add_gallery_image_limit'			=> "Planning to add these to an album? Albums can contain up to <strong>{# [1:image or video][?:images or videos]}</strong>.",
	'add_gallery_album_limit'			=> "You can upload up to <strong>{# [1:image or video][?:images or videos]}</strong> to this album",
	'album_full'						=> "Album full",
	'choose_album'						=> "Choose Album",
	'album_full_desc'					=> "You can't add any more images to this album",
	'x_more_images_album'				=> "You can add {# [1:more image][?:more images]} to this album",
	'saving_images'						=> "Saving Images",
	'saving_images_desc'				=> "Your images are being stored, please wait...",
	'adding_to_category_x'				=> "Adding images to <strong>%s</strong>",
	'add_copyright_image'				=> "Add a copyright for this image",
	'add_credit_image'					=> "Add a credit for this image",
	'create_new_album'					=> "Create new album",
	'cannot_create_album'				=> "Sorry, you don't have permission to create a new album in this category.",
	'used_max_albums'					=> "You can't create any more albums (maximum of %d).",
	'no_existing_albums'				=> "You have no albums in this category to choose from",
	'use_no_album'						=> "Continue without using an album",
	'uploading_to_x' 					=> "Uploading to %s",
	'choose_existing_album'				=> "Use an existing album",
	'files_had_errors'					=> "Some files had errors",
	'copyright'							=> "Copyright",
	'set_copyright_desc'				=> "Sets the copyright for each image you're uploading except ones you individually add a copyright for.",
	'credit'							=> "Credit",
	'credit_desc'						=> "Sets the credit for each image you're uploading except ones you individually add a credit for.",
	'tags_all_desc'						=> "Sets the tags for each image you're uploading except ones you individually specify tags for.",
    'gallery_clear_uploads_error'       => "Could not delete file %s : %s'",
    'specify_image_tags'				=> "Set tags",
	'gallery_guest_post_normal_header'		=> "You are posting as a guest",
	'gallery_guest_post_pbr_blurb'			=> "You can submit your images now and register an account later.",
	'gallery_guest_post_mod_approval'		=> "<strong>Note:</strong> your images will require approval by a moderator after posting.",
	'gallery_this_will_be_moderated'		=> "Because of a warning you received, your images will be hidden until a moderator approves them.",

	'emailtpl__imageContent'			=> "Gallery image table",


	/* Exif mappings
		If you blank out the value for a "key" then it will not be displayed.
		Keys with "_map_#" relate to mapped values that may be seen.

		http://www.portfoliofaq.com/pfaq/v7mappings.htm
		http://www.portfoliofaq.com/pfaq/FAQ00311.htm
		http://www.exif.org/Exif2-2.PDF
	*/

	'exif_title'						=> "Full EXIF data",
	'gallery_focal_length_mm'			=> "%s mm",
	'gallery_shutterspeed'				=> "1/%s second",
	'gallery_exif_camera'				=> "Taken with",
	'gallery_exif_isospeed'				=> "ISO Speed",
	'gallery_exif_iso'					=> "ISO",
	'FILE.FileName'						=> '',
	'FILE.SectionsFound'				=> '',
	'FILE.FileDateTime'					=> '',
	'FILE.FileType'						=> '',
	'FILE.MimeType'						=> 'Mime Type',
	'FILE.FileSize'						=> 'Original File Size',

	'COMPUTED.html'						=> '',
	'COMPUTED.ApertureFNumber'			=> 'Aperture',
	'COMPUTED.Thumbnail.MimeType'		=> '',
	'COMPUTED.Height'					=> 'Image Height',
	'COMPUTED.Width'					=> 'Image Width',

	'COMPUTED.IsColor'					=> 'Color',
	'COMPUTED.IsColor_map_0'			=> 'FALSE',
	'COMPUTED.IsColor_map_1'			=> 'TRUE',

	'COMPUTED.ByteOrderMotorola' 		=> 'Byte Order Motorola',
	'COMPUTED.ByteOrderMotorola_map_0'	=> 'FALSE',
	'COMPUTED.ByteOrderMotorola_map_1'	=> 'TRUE',
	'COMPUTED.CCDWidth'					=> "CCD Width",
	'COMPUTED.UserCommentEncoding'		=> '',
	'COMPUTED.UserComment'				=> '',
	'COMPUTED.Thumbnail.FileType'		=> '',
	'COMPUTED.FocusDistance'			=> "Focus Distance",


	'IFD0.ImageDescription'				=> 'Image Description',
	'IFD0.Make'							=> 'Camera Make',
	'IFD0.Model'						=> 'Camera Model',
	'IFD0.Artist'						=> 'Artist',
	'IFD0.Copyright'					=> 'Copyright',
	'IFD0.XResolution'					=> 'X-Resolution',
	'IFD0.YResolution'					=> 'Y-Resolution',
	'IFD0.DateTime'						=> 'Last Modified',

	'IFD0.Orientation'					=> 'Orientation',
	'IFD0.Orientation_map_1'			=> 'The 0th row is at the visual top of the image, and the 0th column is the visual left-hand side',
	'IFD0.Orientation_map_2'			=> 'The 0th row is at the visual top of the image, and the 0th column is the visual right-hand side',
	'IFD0.Orientation_map_3'			=> 'The 0th row is at the visual bottom of the image, and the 0th column is the visual right-hand side',
	'IFD0.Orientation_map_4'			=> 'The 0th row is at the visual bottom of the image, and the 0th column is the visual left-hand side',
	'IFD0.Orientation_map_5'			=> 'The 0th row is the visual left-hand side of the image, and the 0th column is the visual top',
	'IFD0.Orientation_map_6'			=> 'The 0th row is the visual right-hand side of the image, and the 0th column is the visual top',
	'IFD0.Orientation_map_7'			=> 'The 0th row is the visual right-hand side of the image, and the 0th column is the visual bottom',
	'IFD0.Orientation_map_8'			=> 'The 0th row is the visual left-hand side of the image, and the 0th column is the visual bottom',
										
	'IFD0.ResolutionUnit'				=> 'Resolution Unit',
	'IFD0.Software'						=> 'Software',

	'IFD0.YCbCrPositioning'				=> 'YCbCr Positioning',
	'IFD0.YCbCrPositioning_map_1'		=> 'centered',
	'IFD0.YCbCrPositioning_map_2'		=> 'co-sited',

	'IFD0.Exif_IFD_Pointer'				=> '',
	'IFD0.GPS_IFD_Pointer'				=> '',

	'EXIF.ExposureTime'					=> 'Exposure Time',
	'EXIF.FNumber'						=> 'F Number',
	'EXIF.ExifVersion'					=> 'Exif Version',
	'EXIF.DateTimeOriginal'				=> 'Date Taken',
	'EXIF.DateTimeDigitized'			=> 'Date Digitized',
	'EXIF.ComponentsConfiguration'		=> '',
	'EXIF.CompressedBitsPerPixel'		=> 'Compressed bits/pixel',
	'EXIF.ExposureBiasValue'			=> 'Exposure Bias Value',
	'EXIF.MaxApertureValue'				=> 'Max Aperture Value',
	'EXIF.FocalLength'					=> 'Focal Length',
	'EXIF.MakerNote'					=> '',
	'EXIF.ShutterSpeedValue'			=> "Shutter Speed",
	'EXIF.ApertureValue'				=> "Aperture Value",
	'EXIF.BrightnessValue'				=> "Brightness Value",
	'EXIF.SubSecTimeOriginal'			=> '',
	'EXIF.SubSecTimeDigitized'			=> '',
	'EXIF.ExposureIndex'				=> "Exposure Index",
	'EXIF.CustomRendered'				=> '',
	'EXIF.DigitalZoomRatio'				=> "Digital Zoom Ratio",
	'EXIF.FocalLengthIn35mmFilm'		=> "Focal Length (35mm equiv)",
	'EXIF.SubjectDistanceRange'			=> "Distance Range",
	'EXIF.SubjectDistance'				=> "Subject Distance",

	'EXIF.FlashPixVersion'				=> 'Flashpix Version',
	'EXIF.FlashPixVersion_map_0100'		=> 'Flashpix Format Version 1.0',

	'EXIF.FileSource'					=> '',
	'EXIF.SceneType'					=> '',

	'EXIF.SceneCaptureType'				=> 'Scene Capture Type',
	'EXIF.SceneCaptureType_map_0'		=> 'Standard',
	'EXIF.SceneCaptureType_map_1'		=> 'Landscape',
	'EXIF.SceneCaptureType_map_2'		=> 'Portrait',
	'EXIF.SceneCaptureType_map_3'		=> 'Night scene',

	'EXIF.GainControl'					=> 'Gain Control',
	'EXIF.GainControl_map_0'			=> 'None',
	'EXIF.GainControl_map_1'			=> 'Low gain up',
	'EXIF.GainControl_map_2'			=> 'High gain up',
	'EXIF.GainControl_map_3'			=> 'Low gain down',
	'EXIF.GainControl_map_4'			=> 'High gain down',

	'EXIF.Contrast'						=> 'Contrast',
	'EXIF.Contrast_map_0'				=> 'Normal',
	'EXIF.Contrast_map_1'				=> 'Soft',
	'EXIF.Contrast_map_2'				=> 'Hard',

	'EXIF.Saturation'					=> 'Saturation',
	'EXIF.Saturation_map_0'				=> 'Normal',
	'EXIF.Saturation_map_1'				=> 'Low saturation',
	'EXIF.Saturation_map_2'				=> 'High saturation',

	'EXIF.Sharpness'					=> 'Sharpness',
	'EXIF.Sharpness_map_0'				=> 'Normal',
	'EXIF.Sharpness_map_1'				=> 'Soft',
	'EXIF.Sharpness_map_2'				=> 'Hard',

	'EXIF.ExposureMode'					=> 'Exposure Mode',
	'EXIF.ExposureMode_map_0'			=> 'Auto exposure',
	'EXIF.ExposureMode_map_1'			=> 'Manual exposure',
	'EXIF.ExposureMode_map_2'			=> 'Auto bracket',

	'EXIF.WhiteBalance'					=> 'White Balance',
	'EXIF.WhiteBalance_map_0'			=> 'Auto white balance',
	'EXIF.WhiteBalance_map_1'			=> 'Manual white balance',

	'EXIF.ExposureProgram'				=> 'Exposure Program',
	'EXIF.ExposureProgram_map_0'		=> 'Not defined',
	'EXIF.ExposureProgram_map_1'		=> 'Manual',
	'EXIF.ExposureProgram_map_2'		=> 'Normal program',
	'EXIF.ExposureProgram_map_3'		=> 'Aperture priority',
	'EXIF.ExposureProgram_map_4'		=> 'Shutter priority',
	'EXIF.ExposureProgram_map_5'		=> 'Creative program (biased toward depth of field)',
	'EXIF.ExposureProgram_map_6'		=> 'Action program (biased toward fast shutter speed)',
	'EXIF.ExposureProgram_map_7'		=> 'Portrait mode (for closeup photos with the background out of focus)',
	'EXIF.ExposureProgram_map_8'		=> 'Landscape mode (for landscape photos with the background in focus)',

	'EXIF.ISOSpeedRatings'				=> 'ISO Speed Ratings',

	'EXIF.MeteringMode'					=> 'Metering Mode',
	'EXIF.MeteringMode_map_0'			=> 'Unknown',
	'EXIF.MeteringMode_map_1'			=> 'Average',
	'EXIF.MeteringMode_map_2'			=> 'CenterWeightedAverage',
	'EXIF.MeteringMode_map_3'			=> 'Spot',
	'EXIF.MeteringMode_map_4'			=> 'MultiSpot',
	'EXIF.MeteringMode_map_5'			=> 'Pattern',
	'EXIF.MeteringMode_map_6'			=> 'Partial',
	'EXIF.MeteringMode_map_255'			=> 'Other',

	'EXIF.LightSource'					=> 'Light Source',
	'EXIF.LightSource_map_0'			=> 'Unknown',
	'EXIF.LightSource_map_1'			=> 'Daylight',
	'EXIF.LightSource_map_2'			=> 'Fluorescent',
	'EXIF.LightSource_map_3'			=> 'Tungsten (incandescent light)',
	'EXIF.LightSource_map_4'			=> 'Flash',
	'EXIF.LightSource_map_9'			=> 'Fine weather',
	'EXIF.LightSource_map_10'			=> 'Cloudy weather',
	'EXIF.LightSource_map_11'			=> 'Shade',
	'EXIF.LightSource_map_12'			=> 'Daylight fluorescent (D 5700 - 7100K)',
	'EXIF.LightSource_map_13'			=> 'Day white fluorescent (N 4600 - 5400K)',
	'EXIF.LightSource_map_14'			=> 'Cool white fluorescent (W 3900 - 4500K)',
	'EXIF.LightSource_map_15'			=> 'White fluorescent (WW 3200 - 3700K)',
	'EXIF.LightSource_map_17'			=> 'Standard light A',
	'EXIF.LightSource_map_18'			=> 'Standard light B',
	'EXIF.LightSource_map_19'			=> 'Standard light C',
	'EXIF.LightSource_map_20'			=> 'D55',
	'EXIF.LightSource_map_21'			=> 'D65',
	'EXIF.LightSource_map_22'			=> 'D75',
	'EXIF.LightSource_map_23'			=> 'D50',
	'EXIF.LightSource_map_24'			=> 'ISO studio tungsten',
	'EXIF.LightSource_map_255'			=> 'Other light source',

	'EXIF.Flash'						=> 'Flash',
	'EXIF.Flash_map_0'					=> 'Flash did not fire',
	'EXIF.Flash_map_1'					=> 'Flash fired',
	'EXIF.Flash_map_5'					=> 'Strobe return light not detected',
	'EXIF.Flash_map_7'					=> 'Strobe return light detected',
	'EXIF.Flash_map_9'					=> 'Flash fired, compulsory flash mode',
	'EXIF.Flash_map_D'					=> 'Flash fired, compulsory flash mode, return light not detected',
	'EXIF.Flash_map_F'					=> 'Flash fired, compulsory flash mode, return light detected',
	'EXIF.Flash_map_10'					=> 'Flash did not fire, compulsory flash mode',
	'EXIF.Flash_map_18'					=> 'Flash did not fire, auto mode',
	'EXIF.Flash_map_19'					=> 'Flash fired, auto mode',
	'EXIF.Flash_map_1D'					=> 'Flash fired, auto mode, return light not detected',
	'EXIF.Flash_map_1F'					=> 'Flash fired, auto mode, return light detected',
	'EXIF.Flash_map_20'					=> 'No flash function',
	'EXIF.Flash_map_41'					=> 'Flash fired, red-eye reduction mode',
	'EXIF.Flash_map_45'					=> 'Flash fired, red-eye reduction mode, return light not detected',
	'EXIF.Flash_map_47'					=> 'Flash fired, red-eye reduction mode, return light detected',
	'EXIF.Flash_map_49'					=> 'Flash fired, compulsory flash mode, red-eye reduction mode',
	'EXIF.Flash_map_4D'					=> 'Flash fired, compulsory flash mode, red-eye reduction mode, return light not detected',
	'EXIF.Flash_map_4F'					=> 'Flash fired, compulsory flash mode, red-eye reduction mode, return light detected',
	'EXIF.Flash_map_59'					=> 'Flash fired, auto mode, red-eye reduction mode',
	'EXIF.Flash_map_5D'					=> 'Flash fired, auto mode, return light not detected, red-eye reduction mode',
	'EXIF.Flash_map_5F'					=> 'Flash fired, auto mode, return light detected, red-eye reduction mode',

	'EXIF.UserComment'					=> '',

	'EXIF.ColorSpace'					=> 'Color Space',
	'EXIF.ColorSpace_map_1'				=> 'sRGB',
	'EXIF.ColorSpace_map_FFFF'			=> 'Uncalibrated',

	'EXIF.ExifImageWidth'				=> 'Image Width',
	'EXIF.ExifImageLength'				=> 'Image Length',
	'EXIF.InteroperabilityOffset'		=> 'Interoperability Offset',

	'EXIF.SensingMethod'				=> 'Sensing Method',
	'EXIF.SensingMethod_map_1'			=> 'Not Defined',
	'EXIF.SensingMethod_map_2'			=> 'One-chip color area sensor',
	'EXIF.SensingMethod_map_3'			=> 'Two-chip color area sensor',
	'EXIF.SensingMethod_map_4'			=> 'Three-chip color area sensor',
	'EXIF.SensingMethod_map_5'			=> 'Color sequential area sensor',
	'EXIF.SensingMethod_map_7'			=> 'Trilinear sensor',
	'EXIF.SensingMethod_map_8'			=> 'Color sequential linear sensor',

	'EXIF.FocalPlaneXResolution'		=> "Focal Plane X-Resolution",
	'EXIF.FocalPlaneYResolution'		=> "Focal Plane Y-Resolution",
	'EXIF.FocalPlaneResolutionUnit'		=> "Focal Plane Resolution Unit",


	'INTEROP.InterOperabilityIndex'		=> 'Inter-operability Index',
	'INTEROP.InterOperabilityVersion'	=> 'Inter-operability Version',
	'INTEROP.RelatedImageWidth'			=> '',
	'INTEROP.RelatedImageHeight'		=> '',

	'MAKERNOTE.ImageType'				=> 'Camera (Maker Note)',
	'MAKERNOTE.FirmwareVersion'			=> 'Firmware Version',
	'MAKERNOTE.ImageNumber'				=> '',
	'MAKERNOTE.OwnerName'				=> '',

	'GPS.GPSVersion'					=> '',
	'GPS.GPSAltitudeRef'				=> '',
	'GPS.GPSProcessingMode'				=> '',
	'EXIF.CFAPattern'					=> '',
	'THUMBNAIL.Make'					=> '',
	'THUMBNAIL.Model'					=> '',
	'THUMBNAIL.XResolution'				=> '',
	'THUMBNAIL.YResolution'				=> '',
	'THUMBNAIL.DateTime'				=> '',
	'THUMBNAIL.Compression'				=> '',
	'THUMBNAIL.Compression_map_1'		=> '',
	'THUMBNAIL.Compression_map_6'		=> '',
	'THUMBNAIL.Orientation'				=> '',
	'THUMBNAIL.Orientation_map_1'		=> '',
	'THUMBNAIL.Orientation_map_2'		=> '',
	'THUMBNAIL.Orientation_map_3'		=> '',
	'THUMBNAIL.Orientation_map_4'		=> '',
	'THUMBNAIL.Orientation_map_5'		=> '',
	'THUMBNAIL.Orientation_map_6'		=> '',
	'THUMBNAIL.Orientation_map_7'		=> '',
	'THUMBNAIL.Orientation_map_8'		=> '',
	'THUMBNAIL.ResolutionUnit'			=> '',
	'THUMBNAIL.JPEGInterchangeFormat'	=> '',
	'THUMBNAIL.JPEGInterchangeFormatLength'	=> '',
	'THUMBNAIL.YCbCrPositioning'		=> '',
	'THUMBNAIL.YCbCrPositioning_map_1'	=> '',
	'THUMBNAIL.YCbCrPositioning_map_2'	=> '',

	/* Newer (but useful) EXIF stuff */
	'EXIF.UndefinedTag:0xA434'			=> "Lens Model",
		
	/* !Digests */
	'digest_area_gallery_image'		=> "Images",
	'digest_area_gallery_album'		=> "Albums",
	'digest_area_gallery_category'	=> "Categories",
	'x_added_image_in'		=> "%s added an image in %s",
	'x_added_video_in'		=> "%s added a video in %s",
	'x_added_album_in'		=> "%s created an album in %s",
	'x_commented_photo'		=> "%s commented on a photo",
	'x_reviewed_photo'		=> "%s reviewed a photo",
	'x_commented_album'		=> "%s commented on an album",
	'x_reviewed_album'		=> "%s reviewed an album",
	
	/* !API */
	'__api_gallery_albums'		=> "Albums",
	'__api_gallery_images'		=> "Images",
	'__api_gallery_comments'	=> "Comments",
	'__api_gallery_reviews'		=> "Reviews",
	'__api_gallery_categories'	=> "Categories",
	

	/* !Member Filters */
	'gallery_bm_filters'			=> "Gallery",
	'mf_has_album'				=> "Member has an Album?",

	'sitemap_gallery_Images'		=> "Gallery Images",
	'sitemap_gallery_Videos'		=> "Gallery Videos",

	/* Webhooks */

	'webhook_galleryAlbum_create' => "Fired when an album is created",

	/* Overview */
	'gallery_overview'			=> "Overview",
	'gallery_view_categories'	=> "View Categories",
	'gallery_recently_commented_images' => "Recently Commented Images",
	'gallery_view_all_categories'		=> "View all categories",
	'gallery_recently_updated_albums' 	=> "Recently Updated Albums",

	'gallery_overview_settings'		=> "Overview",

	'gallery_featured_images'		=> "Featured Images Carousel",
	'gallery_overview_show_carousel'		=> "Show carousel?",
	'gallery_overview_carousel_type'		=> "Show",
	'gallery_overview_carousel_featured'	=> "Featured images",
	'gallery_overview_carousel_new'			=> "New images",
	'gallery_overview_carousel_count'		=> "Number of images to show",

	'gallery_overview_recent_comments'		=> "Recent Comments",
	'gallery_show_recent_comments'		=> "Show recent comments?",

	'gallery_overview_categories'		=> "Categories",
	'gallery_overview_show_categories'		=> "Show categories?",

	'gallery_overview_recent_updated_albums'		=> "Recently Updated Albums",
	'gallery_show_recent_updated_albums'		=> "Show recently updated albums?",
	'gallery_recent_updated_albums_count'		=> "Number of recently updated albums to show",

	'gallery_overview_new_images'		=> "New Images",
	'gallery_show_new_images'		=> "Show new images?",
	'gallery_new_images_count'		=> "Number of new images to show",

	/* NSFW */
	'gallery_nsfw'				=> "Enable NSFW?",
	'gallery_nsfw_desc'			=> "Images can be set as not safe for work (NSFW) and will appear blurred unless the member opts in to viewing them.",
	'gallery_image_is_nsfw'		=> "This image is NSFW",
	'gallery_nsfw_view_anyway'	=> "View anyway",
	'nsfw_set_all'				=> "Set NSFW on all",
	'nsfw_enable_all'			=> "Mark all images as not safe for work",
	'image_nsfw'				=> "Not safe for work?",
	'set_gallery_image_nsfw_on'	=> "Set as NSFW off",
	'set_gallery_image_nsfw_off'=> "Set as NSFW on",

	'gallery_album_num_comments_uc'				=> "{# [1:Album Comment][?:Album Comments]}",
	'gallery_album_num_comments_lc'				=> "{# [1:album comment][?:album comments]}",
	'gallery_album_num_reviews_uc'				=> "{# [1:Album Review][?:Album Reviews]}",
	'gallery_album_num_reviews_lc'				=> "{# [1:album review][?:album reviews]}",
);
