<ips:template parameters="$item, $review" />
{{if $review->isIgnored()}}
	<div class='ipsComment ipsComment_ignored ipsPad_half ipsType_light'>
		{lang="ignoring_content" sprintf="$review->author()->name"}
	</div>
{{else}}
	<article id="review-{$review->id}" class="ipsBox ipsBox--child ipsComment ipsComment_parent ipsClearfix ipsClear {{if $review->hidden() OR $item->hidden() == -2}}ipsModerated{{endif}}">
		<a id="review-{$review->id}"></a>
		<a id="findReview-{$review->id}"></a>
		{template="review" location="database" group="display" app="cms" params="$item, $review, $item::$formLangPrefix . 'review', $item::$application, $item::$module"}
	</article>
{{endif}}