<ips:template parameters="$transaction, $log, $response=NULL, $error=NULL" />

<li class='ipsClearfix cTransaction_intermediate'>
	<div class='cTransaction_icon ipsPos_left'>
		{{if isset( $response->kind ) and $response->kind == \Braintree\Dispute::RETRIEVAL}}
			<i class='fa fa-exclamation-triangle'></i>
		{{else}}
			<i class='fa fa-undo'></i>
		{{endif}}
	</div>
	<div class='cTransaction_info ipsType_normal'>
		<h3 class="ipsType_sectionHead">
			{{if isset( $response->kind ) and $response->kind == \Braintree\Dispute::RETRIEVAL}}
				<strong>
					{lang="tstatus_dspd_inquiry_set"}
				</strong>
			{{else}}
				<strong>
					{lang="tstatus_dspd_set"}
				</strong>
			{{endif}}
		</h3>
		<br>
		
		{{if isset( $log['on'] ) and $log['on']}}
			{expression="\IPS\DateTime::ts( $log['on'] )"}
			{{if isset( $log['by'] ) and $log['by']}}
				<br>
				<span class='ipsType_medium ipsType_light'>
					{lang="byline_nodate" sprintf="\IPS\Member::load( $log['by'] )->name"}
				</span>
			{{endif}}
		{{endif}}
				
		{{if isset( $response->reason )}}
		<p class='ipsType_normal ipsType_reset'>
			{lang="braintree_dispute_reason_{$response->reason}"}
		</p>
		{{endif}}
		
		{{if isset( $response->status ) and \in_array( $response->status, array( \Braintree\Dispute::OPEN, \Braintree\Dispute::DISPUTED ) )}}
			<p class='ipsType_bold ipsType_reset ipsType_warning ipsSpacer_top'>
				{{if isset( $response->kind ) and $response->kind == \Braintree\Dispute::RETRIEVAL}}
					{lang="braintree_dispute_status_{$response->status}_r"}
				{{else}}
					{lang="braintree_dispute_status_{$response->status}"}
				{{endif}}
			</p>
		{{endif}}
				
		{{if $error}}
			<p class='ipsMessage ipsMessage_error'>
				{lang="braintree_dispute_error"}
			</p>
		{{endif}}
		
		{{if isset( $response->status ) and $response->status == \Braintree\Dispute::WON}}
				</div>
			</li>
			<li class='ipsClearfix cTransaction_positive'>
				<div class='cTransaction_icon ipsPos_left'>
					<i class='fa fa-repeat'></i>
				</div>
				<div class='cTransaction_info ipsType_normal'>
					<h3 class="ipsType_sectionHead">
						<strong>
							{lang="transaction_dispute_won"}
						</strong>
					</h3>
					<p class='ipsType_normal ipsType_reset'>
						{lang="transaction_dispute_won_desc"}
					</p>
		{{elseif isset( $response->status ) and \in_array( $response->status, array( \Braintree\Dispute::LOST, \Braintree\Dispute::ACCEPTED, \Braintree\Dispute::EXPIRED ) )}}
				</div>
			</li>
			<li class='ipsClearfix cTransaction_negative'>
				<div class='cTransaction_icon ipsPos_left'>
					<i class='fa fa-times'></i>
				</div>
				<div class='cTransaction_info ipsType_normal'>
					<h3 class="ipsType_sectionHead">
						<strong>
							{lang="transaction_dispute_lost"}
						</strong>
					</h3>
					<p class='ipsType_normal ipsType_reset'>
						{lang="transaction_dispute_lost_desc"}
					</p>
		{{endif}}
		
	</div>
</li>