<ips:template parameters="$transaction, $log" />

<li class='ipsClearfix cTransaction_intermediate'>
	<div class='cTransaction_icon ipsPos_left'>
		{{if $log['to'] === 'credit'}}
			<i class='fa fa-reply'></i>
		{{else}}
			<i class='fa fa-reply-all'></i>
		{{endif}}
	</div>
	<div class='cTransaction_info ipsType_normal'>
		<h3 class="ipsType_sectionHead">
			<strong>
				{{if $log['to'] === 'credit'}}
					{lang="tstatus_credited"}
				{{else}}
					{lang="tstatus_prfd_set"}
				{{endif}}
			</strong>
		</h3>
		<br>
		
		{{if isset( $log['amount'] )}}
			{{if $transaction->amount->amount->compare( new \IPS\Math\Number( $log['amount'] ) ) !== 0}}
				<p class='ipsType_reset ipsType_large'>
					<span class='cNexusPrice'>{money="$log['amount']" currency="$transaction->currency"}</span>
				</p>
			{{endif}}
		{{endif}}

		{{if isset( $log['ref'] ) and $log['ref']}}
			<p class='ipsType_reset ipsType_normal'>
				{$log['ref']}
			</p>
		{{endif}}
		{{if isset( $log['on'] ) and $log['on']}}
			{expression="\IPS\DateTime::ts( $log['on'] )"}
			{{if isset( $log['by'] ) and $log['by']}}
				<br>
				<span class='ipsType_medium ipsType_light'>
					{lang="byline_nodate" sprintf="\IPS\Member::load( $log['by'] )->name"}
				</span>
			{{endif}}
		{{endif}}
	</div>
</li>