<ips:template parameters="$transaction" />

<div class='ipsColumns ipsColumns_collapsePhone'>
	<div class='ipsColumn ipsColumn_wide'>
		<div class="ipsBox ipsType_center ipsPad ipsSpacer_bottom" data-ipsSticky data-ipsSticky-spacing='30' data-ipsSticky-disableIn='phone'>
			<h2 class='ipsType_minorHeading'>{lang="transaction_total"}</h2>
			<span class="ipsType_veryLarge">{$transaction->amount}</span>
			{{if $transaction->status === $transaction::STATUS_PART_REFUNDED}}
				{{if $transaction->partial_refund->amount->isGreaterThanZero()}}
					<div class="ipsSpacer_top">
						<h2 class='ipsType_minorHeading'>{lang="amount_refunded"}</h2>
						<span class="ipsType_large">{$transaction->partial_refund}</span>
					</div>
				{{endif}}
				{{if $transaction->credit->amount->isGreaterThanZero()}}
					<div class="ipsSpacer_top">
						<h2 class='ipsType_minorHeading'>{lang="amount_credited"}</h2>
						<span class="ipsType_large">{$transaction->credit}</span>
					</div>
				{{endif}}
			{{endif}}
			<hr class='ipsHr'>

			<ul class='ipsToolList ipsToolList_vertical'>
				{{foreach $transaction->buttons('v') as $k => $button}}
					<li>
						<a href='{$button['link']}' class='ipsButton ipsButton_fullWidth {{if $k === 'approve'}}ipsButton_veryLarge ipsButton_positive ipsSpacer_bottom ipsSpacer_half{{elseif $k === 'void'}}ipsButton_medium ipsButton_negative{{elseif $k === 'delete'}}ipsButton_link{{else}}ipsButton_medium ipsButton_light{{endif}}' {{if isset( $button['data'] )}}{{foreach $button['data'] as $k => $v}}data-{$k}="{$v}"{{endforeach}}{{endif}}><i class='fa fa-{$button['icon']}'></i> {lang="$button['title']"}</a>
					</li>
				{{endforeach}}
			</ul>
		</div>

	</div>

	<div class='ipsColumn ipsColumn_fluid'>

		<div class="ipsMessage ipsSpacer_bottom {{if $transaction->status == \IPS\nexus\Transaction::STATUS_PAID}}ipsMessage_success{{elseif $transaction->status == \IPS\nexus\Transaction::STATUS_HELD}}ipsMessage_warning{{elseif $transaction->status == \IPS\nexus\Transaction::STATUS_REVIEW}}ipsMessage_warning{{elseif $transaction->status == \IPS\nexus\Transaction::STATUS_REFUSED or $transaction->status == \IPS\nexus\Transaction::STATUS_DISPUTED}}ipsMessage_error{{else}}ipsMessage_info{{endif}}">
			{{if $transaction->auth and \in_array( $transaction->status, array( \IPS\nexus\Transaction::STATUS_HELD, \IPS\nexus\Transaction::STATUS_REVIEW ) )}}
				{lang="tstatus_{$transaction->status}_nc_desc"}
			{{else}}
				{lang="tstatus_{$transaction->status}_desc"}
			{{endif}}
		</div>
		

		{{if isset( $transaction->extra['admin'] )}}
			<div class='ipsMessage ipsMessage_info ipsSpacer_bottom'>
				{lang="transaction_admin_manual" sprintf="\IPS\Member::load( $transaction->extra['admin'] )->name"}
			</div>
		{{endif}}

		{{if $transaction->fraud}}
            {{if $transaction->fraud->id}}
                <div class='ipsBox ipsSpacer_bottom'>
                    <h2 class='ipsBox_titleBar'>{lang="maxmind_title"}</h2>
                    <div class='ipsPad'>
                        {{if $errorMessage = $transaction->fraud->error()}}
                        <div class='ipsMessage ipsMessage_error'>
                            <h3 class='ipsMessage_title'>{lang="error_from_maxmind"}</h3>
                            <p class='ipsType_reset'>
                                {$transaction->fraud->error}
                            </p>
                        </div>
                        {{else}}
                        {{if $warning = $transaction->fraud->warning()}}
                        <div class='ipsMessage ipsMessage_error'>
                            <h3 class='ipsMessage_title'>{lang="warning_from_maxmind"}</h3>
                            <p class='ipsType_reset'>
                                {$transaction->fraud->error}
                            </p>
                        </div>
                        {{endif}}
                        {{endif}}
                        {{if !$errorMessage}}
                        <div class="ipsSpacer_bottom ipsSpacer_double">
                            <h3 class='cTransactionFraud_riskScore ipsType_reset ipsPos_left {{if $transaction->fraud->risk_score > 80}}ipsType_warning{{endif}}'>{$transaction->fraud->risk_score}%</h3>
                            <p class='ipsType_reset cTransactionFraud_riskInfo'>
                                <span class='ipsType_large'>{lang="possibility_of_fraud"}</span><br>
                                <span class='ipsType_normal ipsType_light'>{lang="checked_by_maxmind"}</span>
                            </p>
                        </div>

                        <div class='ipsGrid ipsGrid_collapsePhone'>
                            <div class='ipsGrid_span4 ipsAreaBackground_reset'>
                                <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_geo_ip"}</h3>
                                <div class='ipsPad'>
                                    {{if $transaction->fraud->ip_address['location']['latitude'] AND $transaction->fraud->ip_address['location']['longitude']}}
                                        {{if \IPS\GeoLocation::enabled()}}
                                            {{$map = \IPS\GeoLocation::getByLatLong( $transaction->fraud->ip_address['location']['latitude'], $transaction->fraud->ip_address['location']['longitude'] )->map()->render( 600, 200 );}}
                                            <div class="ipsPad_half">{$map|raw}</div>
                                        {{else}}
                                            <p class='ipsType_normal'>{$transaction->fraud->ip_address['location']['latitude']},{$transaction->fraud->ip_address['location']['longitude']}</p>
                                        {{endif}}
                                    {{endif}}
                                    <p class="ipsType_reset ipsType_normal ipsSpacer_top ipsSpacer_half">{lang="maxmind_distance" sprintf="$transaction->fraud->billing_address['distance_to_ip_location']"}</p>
                                    <p class="ipsType_reset ipsType_small ipsType_light">{{if $transaction->fraud->ip_address['location']['accuracy_radius']}}{lang="maxmind_ip_accuracyRadius" sprintf="$transaction->fraud->ip_address['location']['accuracy_radius']"}{{else}}{lang="maxmind_distance_estimated"}{{endif}}</p>

                                    <ul class='ipsList_reset ipsType_normal ipsSpacer_bottom cTransactionFraud_geoip ipsSpacer_top'>
                                        {{if isset( $transaction->fraud->ip_address['city'] )}}
                                        <li>
                                                    <span {{if $transaction->fraud->ip_address['city']['confidence']}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_address['city']['confidence']"}' data-ipsTooltip{{endif}}>
                                                        {$transaction->fraud->ip_address['city']['names']['en']}
                                                    </span>
                                            {{if isset( $transaction->fraud->ip_address['location']['metro_code'] )}}<span class='ipsType_light'>({$transaction->fraud->ip_address['location']['metro_code']})</span>{{endif}}
                                        </li>
                                        {{endif}}
                                        {{if $transaction->fraud->ip_postalCode}}
                                            <li>
                                                <span {{if $transaction->fraud->ip_address['postal']['confidence']}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_address['postal']['confidence']"}' data-ipsTooltip{{endif}}>
                                                    {{if $transaction->fraud->ip_address['postal']['code']}}{$transaction->fraud->ip_address['postal']['code']}{{endif}}
                                                </span>
                                            </li>
                                        {{endif}}
                                        {{if isset( $transaction->fraud->ip_address['country'] )}}
                                            <li>
                                                <span {{if $transaction->fraud->ip_address['country']['confidence']}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_countryConf"}' data-ipsTooltip{{endif}}>
                                                    {lang="country-{$transaction->fraud->ip_address['country']['iso_code']}"}
                                                </span>
                                            </li>
                                        {{endif}}
                                    </ul>

                                    <ul class='ipsList_reset cTransactionFraud'>
                                        {{if isset( $transaction->fraud->billing_address['is_in_ip_country'] )}}
                                            {{if $transaction->fraud->billing_address['is_in_ip_country']}}
                                            <li class='cTransactionFraud_positive ipsClearfix'>
                                                <i class="fa fa-check"></i>
                                                <p class='ipsType_reset'>{lang="maxmind_countryMatch_y"}</p>
                                            </li>
                                            {{else}}
                                            <li class='cTransactionFraud_negative ipsClearfix'>
                                                <i class="fa fa-exclamation-triangle"></i>
                                                <p class='ipsType_reset'>{lang="maxmind_countryMatch_n"}</p>
                                            </li>
                                            {{endif}}
                                        {{endif}}
                                        {{if isset( $transaction->fraud->ip_address['country']['is_high_risk'] ) and $transaction->fraud->ip_address['country']['is_high_risk']}}
                                            <li class='cTransactionFraud_negative'>
                                                <i class="fa fa-exclamation-triangle"></i>
                                                <p class='ipsType_reset'>{lang="maxmind_highRiskCountry_y"}</p>
                                            </li>
                                        {{else}}
                                            <li class='cTransactionFraud_positive'>
                                                <i class="fa fa-check"></i>
                                                <p class='ipsType_reset'>{lang="maxmind_highRiskCountry_n"}</p>
                                            </li>
                                        {{endif}}
                                    </ul>
                                </div>
                            </div>
                            <div class='ipsGrid_span4 ipsAreaBackground_reset'>
                                <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_ip"}</h3>
                                <div class='ipsPad'>
                                    <div class="ipsProgressBar ipsProgressBar_small ipsProgressBar_fullWidth">
                                        <div class="ipsProgressBar_progress {{if $transaction->fraud->ip_address['risk'] > 75}}ipsProgressBar_warning{{endif}}" style="width: {$transaction->fraud->ip_address['risk']}%">{$transaction->fraud->ip_address['risk']}%</div>
                                    </div>
                                    <p class='ipsType_reset ipsType_medium ipsSpacer_top ipsSpacer_half'>{lang="maxmind_proxyScore"}</p>
                                    <p class='ipsType_reset ipsType_small ipsType_light'>{lang="maxmind_proxyScore_desc"}</p>

                                    <ul class='ipsList_reset cTransactionFraud ipsSpacer_top'>
                                        {{if isset( $transaction->fraud->ip_address['traits']['is_anonymous_proxy'] ) and $transaction->fraud->ip_address['traits']['is_anonymous_proxy']}}
                                            <li class='cTransactionFraud_negative ipsClearfix'>
                                                <i class="fa fa-exclamation-circle"></i>
                                                <p class='ipsType_reset'>
                                                    <span class='cTransactionFraud_geoInfo' title="{lang="maxmind_anonymousProxy_desc"}" data-ipsTooltip>
                                                    {lang="maxmind_anonymousProxy_y"}
                                                    </span>
                                                </p>
                                            </li>
                                        {{else}}
                                            <li class='cTransactionFraud_success ipsClearfix'>
                                                <i class="fa fa-check-circle"></i>
                                                <p class='ipsType_reset'>
                                                    <span class='cTransactionFraud_geoInfo' title="{lang="maxmind_anonymousProxy_desc"}" data-ipsTooltip>
                                                    {lang="maxmind_anonymousProxy_n"}
                                                    </span>
                                                </p>
                                            </li>
                                        {{endif}}
                                        {{if isset( $transaction->fraud->ip_address['traits']['is_tor_exit_node'] ) and $transaction->fraud->ip_address['traits']['is_tor_exit_node']}}
                                        <li class='cTransactionFraud_negative ipsClearfix'>
                                            <i class="fa fa-exclamation-circle"></i>
                                            <p class='ipsType_reset'>
                                                <span class='cTransactionFraud_geoInfo' title="{lang="maxmind_torExit_desc"}" data-ipsTooltip>
                                                {lang="maxmind_torExit_y"}
                                                </span>
                                            </p>
                                        </li>
                                        {{else}}
                                        <li class='cTransactionFraud_success ipsClearfix'>
                                            <i class="fa fa-check-circle"></i>
                                            <p class='ipsType_reset'>
                                                <span class='cTransactionFraud_geoInfo' title="{lang="maxmind_torExit_desc"}" data-ipsTooltip>
                                                {lang="maxmind_torExit_n"}
                                                </span>
                                            </p>
                                        </li>
                                        {{endif}}

                                        {{if isset( $transaction->fraud->ip_address['traits']['isp'] )}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-info-circle"></i>
                                            <p class='ipsType_reset'>
                                                {lang="maxmind_ip_isp"}: {$transaction->fraud->ip_address['traits']['isp']}
                                                {{if $transaction->fraud->ip_address['traits']['organization'] and $transaction->fraud->ip_address['traits']['organization'] != $transaction->fraud->ip_address['traits']['isp']}}
                                                <br><span class="ipsType_light ipsType_small">({$transaction->fraud->ip_address['traits']['organization']})</span>
                                                {{endif}}
                                            </p>
                                        </li>
                                        {{endif}}
                                        {{if isset( $transaction->fraud->ip_address['traits']['user_type'] )}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-info-circle"></i>
                                            <p class='ipsType_reset'>
                                                {lang="maxmind_ip_userType_{$transaction->fraud->ip_address['traits']['user_type']}"}
                                            </p>
                                        </li>
                                        {{endif}}
                                        {{if isset( $transaction->fraud->ip_address['traits']['organization'] )}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-info-circle"></i>
                                            <p class='ipsType_reset'>
                                                {lang="maxmind_ip_timeZone"}: {$transaction->fraud->ip_address['location']['time_zone']}
                                            </p>
                                        </li>
                                        {{endif}}
                                        {{if $transaction->fraud->ip_domain}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-info-circle"></i>
                                            <p class='ipsType_reset'>
                                                {lang="maxmind_ip_domain"}: {$transaction->fraud->ip_domain}
                                            </p>
                                        </li>
                                        {{endif}}
                                        {{if isset( $transaction->fraud->ip_address['traits']['autonomous_system_number'] )}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-info-circle"></i>
                                            <p class='ipsType_reset'>
                                                {lang="maxmind_ip_asnum"}: {$transaction->fraud->ip_address['traits']['autonomous_system_number']}
                                            </p>
                                        </li>
                                        {{endif}}
                                    </ul>
                                </div>
                            </div>
                            <div class='ipsGrid_span4 ipsAreaBackground_reset'>
                                {{if $transaction->fraud->credit_card}}
                                <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_card_issuer"}</h3>
                                <div class='ipsPad'>
                                    {{if isset( $transaction->fraud->credit_card['issuer']['name'] )}}
                                    <p class='ipsType_reset ipsType_large'>
                                        <strong>{$transaction->fraud->credit_card['issuer']['name']}</strong>
                                    </p>
                                    {{if isset( $transaction->fraud->credit_card['country'] ) || isset( $transaction->fraud->credit_card['issuer']['phone_number'] )}}
                                    <ul class='ipsList_reset cTransactionFraud ipsSpacer_top ipsSpacer_half'>
                                        {{if isset( $transaction->fraud->credit_card['country'] )}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-globe"></i>
                                            <p class='ipsType_reset'>
                                                {lang="country-{$transaction->fraud->credit_card['country']}"}
                                            </p>
                                        </li>
                                        {{endif}}
                                        {{if isset( $transaction->fraud->credit_card['issuer']['phone_number'] )}}
                                        <li class='cTransactionFraud_neutral ipsClearfix'>
                                            <i class="fa fa-phone"></i>
                                            <p class='ipsType_reset'>
                                                {$transaction->fraud->credit_card['issuer']['phone_number']}
                                            </p>
                                        </li>
                                        {{endif}}
                                    </ul>
                                    {{endif}}
                                    {{endif}}
                                </div>
                                {{endif}}

                                <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_customer_information"}</h3>
                                <div class='ipsPad'>
                                    <ul class='ipsList_reset cTransactionFraud'>
                                        {{foreach array( 'disposable', 'free', 'high_risk' ) as $k}}
                                        {{if !$transaction->fraud->email['is_' . $k]}}
                                        <li class='cTransactionFraud_positive ipsClearfix'>
                                            <i class="fa fa-check-circle"></i>
                                            <p class='ipsType_reset'>{lang="maxmind_{$k}_n"}</p>
                                        </li>
                                        {{else}}
                                        <li class='cTransactionFraud_negative ipsClearfix'>
                                            <i class="fa fa-exclamation-circle"></i>
                                            <p class='ipsType_reset'>{lang="maxmind_{$k}_y"}</p>
                                        </li>
                                        {{endif}}
                                        {{endforeach}}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <hr class='ipsHr'>
                        <p class='ipsType_reset ipsType_medium ipsType_light'>
                            {lang="maxmind_footer_insights" sprintf="$transaction->fraud->id"} ({lang="maxmind_queries" sprintf="$transaction->fraud->queries_remaining"})
                        </p>
                        {{endif}}
                    </div>
                </div>
            {{else}}
                <div class='ipsBox ipsSpacer_bottom'>
                    <h2 class='ipsBox_titleBar'>{lang="maxmind_title"}</h2>
                    <div class='ipsPad'>
                        {{if $errorMessage = $transaction->fraud->error()}}
                        <div class='ipsMessage ipsMessage_error'>
                            <h3 class='ipsMessage_title'>{lang="error_from_maxmind"}</h3>
                            <p class='ipsType_reset'>
                                {$transaction->fraud->error}
                            </p>
                        </div>
                        {{else}}
                            {{if $warning = $transaction->fraud->warning()}}
                            <div class='ipsMessage ipsMessage_error'>
                                <h3 class='ipsMessage_title'>{lang="warning_from_maxmind"}</h3>
                                <p class='ipsType_reset'>
                                    {$transaction->fraud->error}
                                </p>
                            </div>
                            {{endif}}
                        {{endif}}
                        {{if !$errorMessage}}
                            <div class="ipsSpacer_bottom ipsSpacer_double">
                                {{if $transaction->fraud->riskScore !== NULL}}
                                    <h3 class='cTransactionFraud_riskScore ipsType_reset ipsPos_left {{if $transaction->fraud->riskScore > 80}}ipsType_warning{{endif}}'>{$transaction->fraud->riskScore}%</h3>
                                {{else}}
                                    <h3 class='cTransactionFraud_riskScore ipsType_reset ipsPos_left {{if $transaction->fraud->score > 8}}ipsType_warning{{endif}}'>{expression="round( $transaction->fraud->score * 10 )"}%</h3>
                                {{endif}}
                                <p class='ipsType_reset cTransactionFraud_riskInfo'>
                                    <span class='ipsType_large'>{lang="possibility_of_fraud"}</span><br>
                                    <span class='ipsType_normal ipsType_light'>{lang="checked_by_maxmind"}</span>
                                </p>
                            </div>

                            <div class='ipsGrid ipsGrid_collapsePhone'>
                                <div class='ipsGrid_span4 ipsAreaBackground_reset'>
                                    <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_geo_ip"}</h3>
                                    <div class='ipsPad'>
                                        {{if $transaction->fraud->ip_latitude AND $transaction->fraud->ip_longitude}}
                                            {{if \IPS\GeoLocation::enabled()}}
                                                {{$map = \IPS\GeoLocation::getByLatLong( $transaction->fraud->ip_latitude, $transaction->fraud->ip_longitude )->map()->render( 600, 200 );}}
                                                <div class="ipsPad_half">{$map|raw}</div>
                                            {{else}}
                                                <p class='ipsType_normal'>{$transaction->fraud->ip_latitude},{$transaction->fraud->ip_longitude}</p>
                                            {{endif}}
                                        {{endif}}
                                        <p class="ipsType_reset ipsType_normal ipsSpacer_top ipsSpacer_half">{lang="maxmind_distance" sprintf="$transaction->fraud->distance"}</p>
                                        <p class="ipsType_reset ipsType_small ipsType_light">{{if $transaction->fraud->ip_accuracyRadius}}{lang="maxmind_ip_accuracyRadius" sprintf="$transaction->fraud->ip_accuracyRadius"}{{else}}{lang="maxmind_distance_estimated"}{{endif}}</p>

                                        <ul class='ipsList_reset ipsType_normal ipsSpacer_bottom cTransactionFraud_geoip ipsSpacer_top'>
                                            <li>
                                                <span {{if $transaction->fraud->ip_cityConf}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_cityConf"}' data-ipsTooltip{{endif}}>
                                                    {$transaction->fraud->ip_city}
                                                </span>
                                                {{if isset( $transaction->fraud->ip_metroCode )}}<span class='ipsType_light'>({$transaction->fraud->ip_metroCode})</span>{{endif}}
                                            </li>
                                            {{if $transaction->fraud->ip_regionName || $transaction->fraud->ip_region || $transaction->fraud->ip_postalCode}}
                                                <li>
                                                    {{if $transaction->fraud->ip_regionName || $transaction->fraud->ip_region}}
                                                        <span {{if $transaction->fraud->ip_regionConf}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_regionConf"}' data-ipsTooltip{{endif}}>
                                                            {{if $transaction->fraud->ip_regionName}}{$transaction->fraud->ip_regionName}{{elseif $transaction->fraud->ip_region}}{$transaction->fraud->ip_region}{{endif}}
                                                        </span>
                                                    {{endif}}
                                                    {{if $transaction->fraud->ip_postalCode}}
                                                        <span {{if $transaction->fraud->ip_postalConf}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_postalConf"}' data-ipsTooltip{{endif}}>
                                                            {{if $transaction->fraud->ip_postalCode}}{$transaction->fraud->ip_postalCode}{{endif}}
                                                        </span>
                                                    {{endif}}
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->ip_countryName || $transaction->fraud->countryCode}}
                                                <li>
                                                    <span {{if $transaction->fraud->ip_countryConf}}class='cTransactionFraud_geoInfo' title='{lang="maxmind_ip_accuracy" sprintf="$transaction->fraud->ip_countryConf"}' data-ipsTooltip{{endif}}>
                                                        {{if $transaction->fraud->ip_countryName}}{$transaction->fraud->ip_countryName}{{elseif $transaction->fraud->countryCode}}{lang="country-{$transaction->fraud->countryCode}"}{{endif}}
                                                    </span>
                                                </li>
                                            {{endif}}
                                        </ul>

                                        <ul class='ipsList_reset cTransactionFraud'>
                                            {{if $transaction->fraud->countryMatch == 'Yes'}}
                                                <li class='cTransactionFraud_positive ipsClearfix'>
                                                    <i class="fa fa-check"></i>
                                                    <p class='ipsType_reset'>{lang="maxmind_countryMatch_y"}</p>
                                                </li>
                                            {{else}}
                                                <li class='cTransactionFraud_negative ipsClearfix'>
                                                    <i class="fa fa-exclamation-triangle"></i>
                                                    <p class='ipsType_reset'>{lang="maxmind_countryMatch_n"}</p>
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->highRiskCountry == 'No'}}
                                                <li class='cTransactionFraud_positive'>
                                                    <i class="fa fa-check"></i>
                                                    <p class='ipsType_reset'>{lang="maxmind_highRiskCountry_n"}</p>
                                                </li>
                                            {{else}}
                                                <li class='cTransactionFraud_negative'>
                                                    <i class="fa fa-exclamation-triangle"></i>
                                                    <p class='ipsType_reset'>{lang="maxmind_highRiskCountry_y"}</p>
                                                </li>
                                            {{endif}}
                                        </ul>
                                    </div>
                                </div>
                                <div class='ipsGrid_span4 ipsAreaBackground_reset'>
                                    <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_ip"}</h3>
                                    <div class='ipsPad'>
                                        <div class="ipsProgressBar ipsProgressBar_small ipsProgressBar_fullWidth">
                                            <div class="ipsProgressBar_progress {{if $transaction->fraud->proxyScorePercentage() > 75}}ipsProgressBar_warning{{endif}}" style="width: {$transaction->fraud->proxyScorePercentage()}%">{$transaction->fraud->proxyScorePercentage()}%</div>
                                        </div>
                                        <p class='ipsType_reset ipsType_medium ipsSpacer_top ipsSpacer_half'>{lang="maxmind_proxyScore"}</p>
                                        <p class='ipsType_reset ipsType_small ipsType_light'>{lang="maxmind_proxyScore_desc"}</p>

                                        <ul class='ipsList_reset cTransactionFraud ipsSpacer_top'>
                                            {{if $transaction->fraud->anonymousProxy == 'No'}}
                                                <li class='cTransactionFraud_success ipsClearfix'>
                                                    <i class="fa fa-check-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        <span class='cTransactionFraud_geoInfo' title="{lang="maxmind_anonymousProxy_desc"}" data-ipsTooltip>
                                                            {lang="maxmind_anonymousProxy_n"}
                                                        </span>
                                                    </p>
                                                </li>
                                            {{else}}
                                                <li class='cTransactionFraud_negative ipsClearfix'>
                                                    <i class="fa fa-exclamation-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        <span class='cTransactionFraud_geoInfo' title="{lang="maxmind_anonymousProxy_desc"}" data-ipsTooltip>
                                                            {lang="maxmind_anonymousProxy_y"}
                                                        </span>
                                                    </p>
                                                </li>
                                            {{endif}}

                                            {{foreach array( 'isTransProxy', 'ip_corporateProxy' ) as $k}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {{if $transaction->fraud->$k == 'No'}}
                                                            {lang="maxmind_{$k}_n"}
                                                        {{else}}
                                                            {lang="maxmind_{$k}_y"}
                                                        {{endif}}
                                                    </p>
                                                </li>
                                            {{endforeach}}

                                            {{if $transaction->fraud->ip_isp}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {lang="maxmind_ip_isp"}: {$transaction->fraud->ip_isp}
                                                        {{if $transaction->fraud->ip_org and $transaction->fraud->ip_org != $transaction->fraud->ip_isp}}
                                                            <br><span class="ipsType_light ipsType_small">({$transaction->fraud->ip_org})</span>
                                                        {{endif}}
                                                    </p>
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->ip_userType}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {lang="maxmind_ip_userType_{$transaction->fraud->ip_userType}"}
                                                    </p>
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->ip_timeZone}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {lang="maxmind_ip_timeZone"}: {$transaction->fraud->ip_timeZone}
                                                    </p>
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->ip_netSpeedCell}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {lang="maxmind_ip_netSpeedCell"}: {$transaction->fraud->ip_netSpeedCell}
                                                    </p>
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->ip_domain}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {lang="maxmind_ip_domain"}: {$transaction->fraud->ip_domain}
                                                    </p>
                                                </li>
                                            {{endif}}
                                            {{if $transaction->fraud->ip_asnum}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-info-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {lang="maxmind_ip_asnum"}: {$transaction->fraud->ip_asnum}
                                                    </p>
                                                </li>
                                            {{endif}}
                                        </ul>
                                    </div>
                                </div>
                                <div class='ipsGrid_span4 ipsAreaBackground_reset'>
                                    {{if $transaction->fraud->binMatch !== 'NA' and $transaction->fraud->binMatch !== 'NotFound'}}
                                        <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_card_issuer"}</h3>
                                        <div class='ipsPad'>
                                            {{if $transaction->fraud->binName}}
                                                <p class='ipsType_reset ipsType_large'>
                                                    <strong>{$transaction->fraud->binName}</strong>
                                                </p>
                                                {{if $transaction->fraud->binCountry || $transaction->fraud->binPhone}}
                                                    <ul class='ipsList_reset cTransactionFraud ipsSpacer_top ipsSpacer_half'>
                                                        {{if $transaction->fraud->binCountry}}
                                                            <li class='cTransactionFraud_neutral ipsClearfix'>
                                                                <i class="fa fa-globe"></i>
                                                                <p class='ipsType_reset'>
                                                                    {lang="country-{$transaction->fraud->binCountry}"}
                                                                </p>
                                                            </li>
                                                        {{endif}}
                                                        {{if $transaction->fraud->binPhone}}
                                                            <li class='cTransactionFraud_neutral ipsClearfix'>
                                                                <i class="fa fa-phone"></i>
                                                                <p class='ipsType_reset'>
                                                                    {$transaction->fraud->binPhone}
                                                                </p>
                                                            </li>
                                                        {{endif}}
                                                    </ul>
                                                {{endif}}
                                            {{endif}}

                                            <ul class='ipsList_reset cTransactionFraud {{if $transaction->fraud->binName}}ipsSpacer_top{{endif}}'>
                                                {{if $transaction->fraud->binMatch == 'Yes'}}
                                                    <li class='cTransactionFraud_success ipsClearfix'>
                                                        <i class="fa fa-check-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_binMatch_y"}</p>
                                                    </li>
                                                {{else}}
                                                    <li class='cTransactionFraud_negative ipsClearfix'>
                                                        <i class="fa fa-exclamation-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_binMatch_n"}</p>
                                                    </li>
                                                {{endif}}
                                                <li class='cTransactionFraud_neutral ipsClearfix'>
                                                    <i class="fa fa-exclamation-circle"></i>
                                                    <p class='ipsType_reset'>
                                                        {{if $transaction->fraud->prepaid == 'Yes'}}
                                                            {lang="maxmind_binMatch_y"}
                                                        {{else}}
                                                            {lang="maxmind_binMatch_n"}
                                                        {{endif}}
                                                    </p>
                                                </li>
                                            </ul>
                                        </div>
                                    {{endif}}

                                    <h3 class='acpBlock_title acpBlock_titleSmall'>{lang="maxmind_customer_information"}</h3>
                                    <div class='ipsPad'>
                                        <ul class='ipsList_reset cTransactionFraud'>
                                            {{if $transaction->fraud->custPhoneInBillingLoc and $transaction->fraud->custPhoneInBillingLoc != 'NotFound'}}
                                                {{if $transaction->fraud->custPhoneInBillingLoc == 'No'}}
                                                    <li class='cTransactionFraud_negative ipsClearfix'>
                                                        <i class="fa fa-exclamation-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_custPhoneInBillingLoc_n"}</p>
                                                    </li>
                                                {{else}}
                                                    <li class='cTransactionFraud_positive ipsClearfix'>
                                                        <i class="fa fa-check-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_custPhoneInBillingLoc_y"}</p>
                                                    </li>
                                                {{endif}}
                                            {{endif}}
                                            {{if $transaction->fraud->cityPostalMatch}}
                                                {{if $transaction->fraud->cityPostalMatch == 'No'}}
                                                    <li class='cTransactionFraud_negative ipsClearfix'>
                                                        <i class="fa fa-exclamation-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_cityPostalMatch_n"}</p>
                                                    </li>
                                                {{else}}
                                                    <li class='cTransactionFraud_positive ipsClearfix'>
                                                        <i class="fa fa-check-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_cityPostalMatch_y"}</p>
                                                    </li>
                                                {{endif}}
                                            {{endif}}
                                            {{if $transaction->fraud->shipCityPostalMatch}}
                                                {{if $transaction->fraud->shipCityPostalMatch == 'No'}}
                                                    <li class='cTransactionFraud_negative ipsClearfix'>
                                                        <i class="fa fa-exclamation-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_shipCityPostalMatch_n"}</p>
                                                    </li>
                                                {{else}}
                                                    <li class='cTransactionFraud_positive ipsClearfix'>
                                                        <i class="fa fa-check-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_shipCityPostalMatch_y"}</p>
                                                    </li>
                                                {{endif}}
                                            {{endif}}
                                            {{if $transaction->fraud->shipForward and $transaction->fraud->shipForward != 'NA'}}
                                                {{if $transaction->fraud->shipForward == 'No'}}
                                                    <li class='cTransactionFraud_negative ipsClearfix'>
                                                        <i class="fa fa-exclamation-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_shipForward_n"}</p>
                                                    </li>
                                                {{else}}
                                                    <li class='cTransactionFraud_positive ipsClearfix'>
                                                        <i class="fa fa-check-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_shipForward_y"}</p>
                                                    </li>
                                                {{endif}}
                                            {{endif}}
                                            {{foreach array( 'freeMail', 'carderEmail' ) as $k}}
                                                {{if $transaction->fraud->$k == 'No'}}
                                                    <li class='cTransactionFraud_positive ipsClearfix'>
                                                        <i class="fa fa-check-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_{$k}_n"}</p>
                                                    </li>
                                                {{else}}
                                                    <li class='cTransactionFraud_negative ipsClearfix'>
                                                        <i class="fa fa-exclamation-circle"></i>
                                                        <p class='ipsType_reset'>{lang="maxmind_{$k}_y"}</p>
                                                    </li>
                                                {{endif}}
                                            {{endforeach}}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <hr class='ipsHr'>
                            <p class='ipsType_reset ipsType_medium ipsType_light'>
                                {{if $transaction->fraud->minfraud_version}}
                                    {lang="maxmind_footer" sprintf="$transaction->fraud->service_level, $transaction->fraud->minfraud_version, $transaction->fraud->maxmindID"} ({lang="maxmind_queries" sprintf="$transaction->fraud->queriesRemaining"})
                                {{endif}}
                            </p>
                        {{endif}}
                    </div>
                </div>
            {{endif}}
		{{endif}}
		
		<div class='ipsGrid ipsGrid_collapsePhone'>
			<div class='ipsGrid_span6'>
				<div class="ipsBox">
					<h2 class="ipsBox_titleBar">{lang="transaction_history"}</h2>
					<div class='ipsPad'>
						<ul class='ipsList_reset cTransaction ipsClearfix'>
							<li class='ipsClearfix'>	
								<div class='cTransaction_icon ipsPos_left'>
									<i class='fa fa-shopping-cart'></i>
								</div>
								<div class='cTransaction_info ipsType_normal'>
									<h2 class='ipsType_sectionHead'>
										<strong>
											{{if $transaction->method}}
												{{if \in_array( $transaction->status, array( \IPS\nexus\Transaction::STATUS_PENDING, \IPS\nexus\Transaction::STATUS_WAITING ) )}}
													{lang="transaction_method_pending" sprintf="$transaction->method->_title"}
												{{else}}
													{lang="transaction_method" sprintf="$transaction->method->_title"}							
												{{endif}}
											{{else}}
												{{if $transaction->method !== 0 }}
													{lang="tstatus_okay_deleted"}
												{{else}}
													{lang="tstatus_okay_credit"}
												{{endif}}
											{{endif}}
										</strong>
									</h2>
									<p class='ipsType_reset'>
										{$transaction->date}
									</p>
									{{if $transaction->gw_id}}
										<p class='ipsType_normal ipsType_reset'>
										{lang="payment_reference"}: {{if $transaction->method AND $url = $transaction->method->gatewayUrl( $transaction )}}<a href="{$url}" target="_blank" rel='noreferrer'>{$transaction->gw_id}</a>{{else}}{$transaction->gw_id}{{endif}}<br>
										</p>
									{{endif}}
									{{if $transaction->method and $extraData = $transaction->method->extraData( $transaction )}}
										{$extraData|raw}
									{{endif}}
									{{if $transaction->billing_agreement}}
										<p class='ipsType_normal ipsType_reset'>
										<a href="{$transaction->billing_agreement->acpUrl()}" class="ipsType_blendLinks">{lang="billing_agreement" sprintf="$transaction->billing_agreement->gw_id"}</a><br>
										</p>
									{{endif}}
									{{if $transaction->ip}}
										<span class='ipsType_medium ipsType_light'>
											<a class="ipsType_blendLinks" href="{url="app=core&module=members&controller=ip&ip={$transaction->ip}"}">{lang="transaction_ip" sprintf="$transaction->ip"}</a>
										</span>
									{{endif}}
								</div>
							</li>

							{{if $transaction->fraud_blocked}}
								<li class='ipsClearfix'>
									<div class='cTransaction_icon ipsPos_left'>
										<i class='fa fa-exclamation-circle'></i>
									</div>
									<div class='cTransaction_info ipsType_normal'>
										<h2 class='ipsType_sectionHead'><strong>{lang="triggered_fraud_rule"}</strong></h2>
										<p class='ipsType_normal ipsType_reset'>
											{$transaction->fraud_blocked->name}
										</p>
									</div>
								</li>
							{{endif}}

							{{foreach $transaction->history() as $log}}
								{template="$log['s']" group="transactions" params="$transaction, $log"}
							{{endforeach}}
						</ul>
					</div>
				</div>
			</div>
			<div class='ipsGrid_span6'>
				{{if $transaction->member AND $transaction->member->member_id}}
					<div class='ipsBox ipsSpacer_bottom'>
						<h2 class="ipsBox_titleBar">{lang="transaction_customer"}</h2>
						<div class='ipsPad'>
							<div class='ipsPhotoPanel ipsPhotoPanel_small ipsClearfix'>
								<a href="{$transaction->member->acpUrl()}" class='ipsPos_left'><img src='{$transaction->member->photo}' class='ipsUserPhoto ipsUserPhoto_small'></a>
								<div>
									<h3 class="ipsType_sectionHead ipsType_reset">
										<strong><a class="ipsType_blendLinks" href="{$transaction->member->acpUrl()}">{$transaction->member->cm_name}</a></strong>
										&nbsp;&nbsp;<span class='ipsType_normal ipsType_light'>{$transaction->member->email}</span>
									</h3>
									<p class='ipsType_normal ipsType_reset'>
										{lang="transaction_customer_since" sprintf="$transaction->member->joined->localeDate()"}<br>
										{lang="transaction_spent" sprintf="$transaction->member->totalSpent()"}
									</p>

									{{if member.hasAcpRestriction( 'nexus', 'customers', 'customers_void' )}}
										<a href="{url="app=nexus&module=customers&controller=view&do=void&id={$transaction->member->member_id}&rt={$transaction->id}"}" class="ipsButton ipsButton_light ipsButton_verySmall ipsSpacer_top" data-ipsDialog data-ipsDialog-title="{lang="void_account"}">{lang="void_account"}</a>
									{{endif}}
								</div>
							</div>
						</div>
					</div>
				{{else}}
					<div class='ipsBox ipsSpacer_bottom'>
						<h2 class="ipsBox_titleBar">{lang="transaction_customer"}</h2>
						<div class='ipsPad'>
							<div class='ipsAreaBackground_light ipsPad ipsPhotoPanel ipsPhotoPanel_large ipsClearfix'>
								<img src='{resource="default_photo.png" app="core" location="global"}' class='ipsUserPhoto ipsUserPhoto_medium ipsPos_left'>
								<div>
									{{if $transaction->invoice AND !empty( $transaction->invoice->guest_data )}}
										<h3 class="ipsType_sectionHead ipsType_reset">
											<strong>
												{{if isset( $transaction->invoice->guest_data['member']['name'] )}}
													{$transaction->invoice->guest_data['member']['name']}
												{{elseif isset( $transaction->invoice->guest_data['member']['cm_first_name'] )}}
													{$transaction->invoice->guest_data['member']['cm_first_name']} {$transaction->invoice->guest_data['member']['cm_last_name']}
												{{endif}}
											</strong>
											&nbsp;&nbsp;<span class='ipsType_normal ipsType_light'>{$transaction->invoice->guest_data['member']['email']}</span>
										</h3>
                                    {{elseif !$transaction->member}}
                                        <span class="ipsType_large">{lang="deleted_member"}</span>
									{{else}}
										<span class="ipsType_large">{lang="guest"}</span>
									{{endif}}
								</div>
							</div>
						</div>
					</div>
				{{endif}}
				
				{{if $transaction->invoice}}
					<div class="ipsBox ipsSpacer_bottom">
						<h2 class="ipsBox_titleBar">{lang="invoice_number" sprintf="$transaction->invoice->id"}</h2>
						<div class='ipsPad'>
							{{$summary = $transaction->invoice->summary();}}
							<ul class='ipsDataList ipsDataList_reducedSpacing'>
								{{foreach $summary['items'] as $item}}
									<li class="ipsDataItem ipsClearfix">
										<div class="ipsDataItem_main">
											{$item->name}{{if $item->quantity > 1}} x{$item->quantity}{{endif}}
											{{if \count( $item->details )}}
												<br>
												<span class="ipsType_light">
													{{foreach $item->details as $k => $v}}
														{lang="nexus_pfield_{$k}"}: {$v}<br>
													{{endforeach}}
												</span>
											{{endif}}
										</div>
										<div class="ipsDataItem_generic ipsDataItem_size3 ipsType_right">
											{$item->linePrice()}
										</div>
									</li>
								{{endforeach}}
								<li class="ipsDataItem ipsClearfix cTransactionInvoice_subtotal">
									<div class="ipsDataItem_main">
										<strong>{lang="subtotal"}</strong>
									</div>
									<div class="ipsDataItem_generic ipsDataItem_size3 ipsType_right">
										<strong>{$summary['subtotal']}</strong>
									</div>
								</li>
								{{foreach $summary['shipping'] as $shipping}}
									<li class="ipsDataItem ipsClearfix">
										<div class="ipsDataItem_main">
											{$shipping->name}
										</div>
										<div class="ipsDataItem_generic ipsDataItem_size3 ipsType_right">
											{$shipping->price}
										</div>
									</li>
								{{endforeach}}
								{{foreach $summary['tax'] as $taxId => $tax}}
									<li class="ipsDataItem ipsClearfix">
										<div class="ipsDataItem_main">
											{lang="nexus_tax_{$taxId}"}
											{{if $tax['type'] !== 'single'}}
												{{if $tax['type'] === 'eu' and $transaction->invoice->billaddress->business and $transaction->invoice->billaddress->vat}}
													({lang="tax_rate_eu"}: {expression="$tax['rate']*100"}%)
												{{elseif $transaction->invoice->billaddress->business}}
													({lang="tax_rate_business"}: {expression="$tax['rate']*100"}%)
												{{else}}
													({lang="tax_rate_consumer"}: {expression="$tax['rate']*100"}%)
												{{endif}}
											{{else}}
												({expression="$tax['rate']*100"}%)
											{{endif}}
										</div>
										<div class="ipsDataItem_generic ipsDataItem_size3 ipsType_right">
											{$tax['amount']}
										</div>
									</li>
								{{endforeach}}
								<li class="ipsDataItem ipsType_large ipsClearfix cTransactionInvoice_subtotal">
									<div class="ipsDataItem_main">
										<strong>{lang="total"}</strong>
									</div>
									<div class="ipsDataItem_generic ipsDataItem_size3 ipsType_right">
										<strong>{$summary['total']}</strong>
									</div>
								</li>
							</ul>
							<a href="{$transaction->invoice->acpUrl()}" class="ipsSpacer_top ipsButton ipsButton_light ipsButton_medium ipsButton_fullWidth">
								{lang="invoice_view"} <i class='fa fa-angle-right'></i>
							</a>
						</div>
					</div>
	
					{{if $transaction->invoice->billaddress || $transaction->invoice->shipaddress}}
						<div class="ipsBox">
							<h3 class='ipsBox_titleBar'>{lang="invoice_addresses"}</h3>
							<div class='ipsPad'>
								{{if $transaction->invoice->billaddress}}
									<div class='ipsGrid ipsGrid_collapsePhone ipsSpacer_bottom'>
										{{if \IPS\GeoLocation::enabled()}}
										<div class='ipsGrid_span6'>
											{$transaction->invoice->billaddress->map()->render( 350, 150 )|raw}
										</div>
										<div class='ipsGrid_span6'>
										{{else}}
										<div class='ipsGrid_span12'>
										{{endif}}
											<h4 class='ipsType_minorHeading ipsType_reset'>{lang="billing_address"}</h4>
											<p class='ipsType_reset ipsType_normal'>
												{$transaction->invoice->billaddress->toString('<br>')|raw}
											</p>
											{{if isset( $transaction->invoice->billaddress->vat ) and $transaction->invoice->billaddress->vat}}
												<p class='ipsType_reset ipsType_normal ipsSpacer_top ipsSpacer_half'>
													{lang="cm_checkout_vat_number"}: {template="vatNumber" group="global" params="$transaction->invoice->billaddress->vat"}
												</p>
											{{endif}}
										</div>
									</div>
								{{endif}}
								{{if $transaction->invoice->shipaddress}}
									<div class='ipsGrid ipsGrid_collapsePhone'>
										{{if \IPS\GeoLocation::enabled()}}
										<div class='ipsGrid_span6'>
											{$transaction->invoice->shipaddress->map()->render( 350, 150 )|raw}
										</div>
										<div class='ipsGrid_span6'>
										{{else}}
										<div class='ipsGrid_span12'>
										{{endif}}
											<h4 class='ipsType_minorHeading ipsType_reset'>{lang="shipping_address"}</h4>
											<p class='ipsType_reset ipsType_normal'>
												{$transaction->invoice->shipaddress->toString('<br>')|raw}
											</p>
										</div>
									</div>
								{{endif}}
							</div>
						</div>
					{{endif}}
				{{else}}
					<br>
					<div class="ipsMessage ipsMessage_info">
						{lang="trans_invoice_deleted"}
					</div>
				{{endif}}
			</div>
		</div>
	</div>
</div>	