<ips:template parameters="$transaction, $log" />

<li class='ipsClearfix'>
	<div class='cTransaction_icon ipsPos_left'>
		<i class='fa fa-clock-o'></i>
	</div>
	<div class='cTransaction_info ipsType_normal'>
		<span class="ipsType_large">{lang="tstatus_wait"}</span>
		{{if isset( $log['on'] ) and $log['on']}}
			<br>
			{expression="\IPS\DateTime::ts( $log['on'] )"}
			{{if isset( $log['by'] ) and $log['by']}}
				<br>
				<span class='ipsType_medium ipsType_light'>
					{lang="byline_nodate" sprintf="\IPS\Member::load( $log['by'] )->name"}
				</span>
			{{endif}}
		{{endif}}
		{{if isset( $log['note'] ) and $log['note']}}
			<p class='ipsType_reset cTransaction_note ipsType_medium'>
				{$log['note']}
			</p>
		{{endif}}
	</div>
</li>