<ips:template parameters="$location, $currency" />

<div class='ipsBox_alt'>
	<div class='ipsType_center ipsPad'>
		<i class='ipsType_huge fa fa-shopping-cart'></i>
		<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="your_cart"}</h1>
	</div>

	<div data-controller='nexus.front.store.cartReview'>
		<div data-role="cart">
			{template="cartContents" group="store" params="$location, $currency"}
		</div>
	</div>
</div>