<ips:template parameters="" />
{{$location = NULL;}}
{{if isset( $_SESSION['cart'] ) and \count( $_SESSION['cart'] ) and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'nexus', 'store' ) )}}
	{{$subtotal = new \IPS\Math\Number('0');}}
	<li class='cUserNav_icon' id='elCart_container'>
		<a href='{url="app=nexus&module=store&controller=cart" seoTemplate="store_cart"}' id='elCart' data-ipsTooltip title='{lang="your_cart"}' data-ipsMenu data-ipsMenu-closeOnClick='false'>
			<i class='fa fa-shopping-cart'></i> <span class='ipsNotificationCount'>{expression="\IPS\nexus\Application::cartCount()"}</span>
			&nbsp;{lang="cart"} <i class='fa fa-caret-down'></i>
		</a>
		<div id='elCart_menu' class='ipsMenu ipsMenu_wide ipsHide'>
			<div class="ipsMenu_headerBar"><h4 class="ipsType_sectionHead">{lang="your_cart"}</h4></div>
			<div class='ipsMenu_innerContent ipsPad_half'>
				<ul class='ipsDataList' data-role='cartList' id='elCartContent'>
					{{foreach $_SESSION['cart'] as $id => $item}}
					{{if $item instanceof \IPS\nexus\extensions\nexus\Item\Package}}
						{{try { $package = \IPS\nexus\Package::load( $item->id ); } catch( \OutOfRangeException $e ) { unset($_SESSION['cart'][$id]); continue; } }}
					{{endif}}
						<li class='ipsDataItem cNexusMiniCart_row'>
							<div class='ipsDataItem_icon'>
								{{if $item instanceof \IPS\nexus\extensions\nexus\Item\Package and $package->image}}
									<img src="{$package->image}" class='ipsThumb ipsThumb_tiny' alt="{$package->_title}">
								{{else}}
									<div class='ipsThumb_tiny ipsNoThumb ipsNoThumb_product'>&nbsp;</div>
								{{endif}}
							</div>
							<div class='ipsDataItem_main'>
								<span class='ipsType_medium ipsType_reset ipsType_unbold'>{$item->name}</span>
							</div>
							<div class='ipsDataItem_generic ipsDataItem_size1 ipsType_center'>
								&times;{$item->quantity}
							</div>
							<div class='ipsDataItem_generic ipsDataItem_size3 cNexusPrice ipsType_normal ipsType_right'>
								<strong>
									{{if settings.nexus_show_tax}}
										{{$location = $location ?: \IPS\nexus\Customer::loggedIn()->estimatedLocation();}}
										{{$linePrice = $item->grossLinePrice( $location );}}
									{{else}}
										{{$linePrice = $item->linePrice();}}
									{{endif}}
									{$linePrice}
									{{$subtotal = $subtotal->add( $linePrice->amount );}}
								</strong>
								{{if $item->quantity > 1}}
									<p class='ipsType_reset ipsType_small ipsType_light'>
										{lang="each_short" sprintf="$item->price"}
									</p>
								{{endif}}
							</div>
						</li>
					{{endforeach}}
					<li class='ipsDataItem cNexusMenuCart_totalRow'>
						<div class='ipsDataItem_main ipsType_large ipsType_right'>
							<strong>{lang="subtotal"}</strong>
						</div>
						<div class='ipsDataItem_generic ipsDataItem_size3 cNexusPrice ipsType_large ipsType_right'>
							<strong>{money="$subtotal"}</strong>
						</div>
					</li>
				</ul>
			</div>
			<div class='ipsMenu_footerBar ipsType_center'>
				<a href='{url="app=nexus&module=store&controller=cart" seoTemplate="store_cart"}' class='ipsButton ipsButton_small ipsButton_primary'>{lang="review_and_checkout"}</a>
			</div>
		</div>
	</li>
	<li class='elUserNav_sep' id='elCart_sep'></li>
{{else}}
	<li class='cUserNav_icon ipsHide' id='elCart_container'></li>
	<li class='elUserNav_sep ipsHide' id='elCart_sep'></li>
{{endif}}