<ips:template parameters="" />
{{$location = NULL;}}
{{if isset( $_SESSION['cart'] ) and \count( $_SESSION['cart'] ) and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'nexus', 'store' ) )}}
	{{$subtotal = 0;}}
	<li class='cUserNav_icon'>
		<a href='{url="app=nexus&module=store&controller=cart" seoTemplate="store_cart"}'>
			<span class='ipsNotificationCount'>{expression="\IPS\nexus\Application::cartCount()"}</span>
			<i class='fa fa-shopping-cart'></i>
		</a>
	</li>
{{endif}}