<ips:template parameters="$category, $subcategories, $packages, $pagination, $packagesWithCustomFields, $totalCount" />

<header class="ipsPageHeader ipsBox ipsPadding ipsResponsive_pull ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle ipsType_largeTitle">{$category->_title}</h1>
	{{if $category->description}}
		{template="richText" group="global" app="core" location="global" params="$category->description, array('ipsType_normal')"}
	{{endif}}		
</header>

{{if \count( $subcategories )}}
	<section class='ipsBox ipsResponsive_pull ipsPadding'>
		<ul class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='200' data-ipsGrid-maxItemSize='350' data-ipsGrid-equalHeights='row'>
			{{foreach $subcategories as $group}}
				<li class='ipsGrid_span4 cNexusCategoryBlock'>
					<a href='{$group->url()}' data-grid-ratio='40' {{if $group->image}}style="background-image: url( '{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $group->image )"}' );"{{endif}}>
						<h2 class='ipsType_sectionHead ipsTruncate ipsTruncate_line'>{$group->_title}</h2>
					</a>
				</li>
			{{endforeach}}
		</ul>
	</section>
	<br>
{{endif}}

<div data-role="packageListContainer">
	{template="categoryContents" group="store" params="$category, $subcategories, $packages, $pagination, $packagesWithCustomFields, $totalCount"}
</div>