<ips:template parameters="$category=NULL, $subcategories=NULL, $url=NULL, $havePackages=FALSE, $currency=NULL, $havePackagesWhichAcceptReviews = FALSE, $havePackagesWhichUseStockLevels = FALSE" />

<div data-role="categorySidebar">
	{{if !\IPS\nexus\Package\Group::theOnlyNode( array(), TRUE, FALSE )}}
	<div class='ipsBox ipsSpacer_bottom' id='elNexusCategoriesBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="categories"}</h2>
		<div class='ipsPad_half'>
			{{if $subcategories !== NULL AND \count( $subcategories )}}
				<div class='ipsSideMenu ipsSideMenu_withRadios ipsType_medium' id='elCategories_menu'>
					<h3 class='ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium'>
						<a href='#elCategories_menu' class='ipsPad_double' data-action='openSideMenu'><i class='fa fa-bars'></i> &nbsp;{lang="categories"}&nbsp;<i class='fa fa-caret-down'></i></a>
					</h3>
					<p class='ipsType_reset ipsType_medium cNexusCategoriesBox_back'>
						{{if $category && $category->parent()}}
							<a href='{$category->parent()->url()}' class='ipsType_medium'><i class='fa fa-chevron-left'></i> {$category->parent()->_title}</a>
						{{else}}
							<a href='{url="app=nexus&module=store&controller=store" seoTemplate="store"}'><i class='fa fa-chevron-left'></i> {lang="all_categories"}</a>
						{{endif}}
					</p>
					<hr class='ipsHr'>
					<h4 class='ipsSideMenu_title ipsSpacer_top ipsSpacer_half'>{$category->_title}</h4>
					<ul class='ipsSideMenu_list'>
						{{foreach $subcategories as $idx => $subcategory}}
							<li>
								<a href='{$subcategory->url()}' class='ipsSideMenu_item'><strong>{$subcategory->_title}</strong></a>
								{{if $subcategory->hasSubgroups()}}
									<ul class='ipsSideMenu_list'>
										{{foreach $subcategory->children( 'view', NULL, FALSE ) as $cidx => $child}}
											<li>
												{{if $cidx >= 5}}
													<a href='{$subcategory->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" pluralize="\count( $subcategory->children( 'view', NULL, FALSE ) ) - 5"}</span></a>
													{{break;}}
												{{else}}
													<a href="{$child->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>{$child->_title}</a>
												{{endif}}
											</li>
										{{endforeach}}
									</ul>
								{{endif}}
							</li>
						{{endforeach}}
					</ul>
				</div>
			{{elseif $category && $category->parent()}}
				{{$siblings = $category->parent()->children( 'view', NULL, FALSE );}}
				<div class='ipsSideMenu ipsSideMenu_withRadios ipsType_medium' id='elCategories_menu'>
					<h3 class='ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium'>
						<a href='#elCategories_menu' class='ipsPad_double' data-action='openSideMenu'><i class='fa fa-bars'></i> &nbsp;{lang="categories"}&nbsp;<i class='fa fa-caret-down'></i></a>
					</h3>
					<p class='ipsType_reset ipsType_medium cNexusCategoriesBox_back'>
						<a href='{$category->parent()->url()}' class='ipsType_medium'><i class='fa fa-chevron-left'></i> {$category->parent()->_title}</a>
					</p>
					<hr class='ipsHr'>
					<h4 class='ipsSideMenu_title ipsSpacer_top ipsSpacer_half'>{$category->parent()->_title}</h4>
					<ul class='ipsSideMenu_list'>
						{{foreach $siblings as $idx => $sibling}}
							<li>
								<a href='{$sibling->url()}' class='ipsSideMenu_item {{if $category && $category == $sibling}}ipsSideMenu_itemActive{{endif}}'>{$sibling->_title}</a>
								{{if $sibling instanceof \IPS\nexus\Package\Group && $sibling->hasSubgroups()}}
									<ul class='ipsSideMenu_list'>
										{{$cidx = 0;}}
										{{foreach $sibling->children( 'view', NULL, FALSE ) as $child}}
											{{if $child->hasPackages( NULL, array(), TRUE ) OR $child->hasSubgroups()}}
												{{$cidx++;}}
												<li>
													{{if $cidx >= 5}}
														<a href='{$sibling->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" pluralize="\count( $sibling->children( 'view', NULL, FALSE ) ) - 5"}</span></a>
														{{break;}}
													{{else}}
														<a href="{$child->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>{$child->_title}</a>
													{{endif}}
												</li>
											{{endif}}
										{{endforeach}}
									</ul>
								{{endif}}
							</li>
						{{endforeach}}
					</ul>
				</div>
			{{else}}
				<div class='ipsSideMenu ipsSideMenu_withRadios ipsType_medium' id='elCategories_menu'>
					<h3 class='ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium'>
						<a href='#elCategories_menu' class='ipsPad_double' data-action='openSideMenu'><i class='fa fa-bars'></i> &nbsp;{lang="categories"}&nbsp;<i class='fa fa-caret-down'></i></a>
					</h3>
					<ul class='ipsSideMenu_list'>
						{{foreach \IPS\nexus\Package\Group::rootsWithViewablePackages() as $group}}
							<li>
								<a href='{$group->url()}' class='ipsSideMenu_item {{if $category && $category == $group}}ipsSideMenu_itemActive{{endif}}'><strong>{$group->_title}</strong></a>
								{{if $group->hasSubgroups()}}
									<ul class='ipsSideMenu_list'>
										{{$idx = 0;}}
										{{foreach $group->children( 'view', NULL, FALSE ) as $child}}
											{{if $child->hasPackages( NULL, array(), TRUE ) OR $child->hasSubgroups()}}
												{{$idx++;}}
												<li>
													{{if $idx >= 5}}
														<a href='{$group->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" pluralize="\count( $group->children( 'view', NULL, FALSE ) ) - 5"}</span></a>
														{{break;}}
													{{else}}
														<a href="{$child->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>{$child->_title}</a>
													{{endif}}
												</li>
											{{endif}}
										{{endforeach}}
									</ul>
								{{endif}}
							</li>
						{{endforeach}}
					</ul>
				</div>
			{{endif}}
		</div>
	</div>
	{{endif}}
	
	{{if $havePackages or request.filter or request.minPrice or request.maxPrice or request.minRating or request.inStock}}
	<div class='ipsBox ipsSpacer_bottom' id='elNexusFiltersBox'>
		
		<h2 class='ipsType_sectionTitle ipsType_reset'>
			{{if request.filter or request.minPrice or request.maxPrice or request.minRating or request.inStock}}
				<a href="{$category->url()}" data-action="filter" class="ipsPos_right ipsButton ipsButton_veryLight ipsButton_veryVerySmall ipsSideMenu_titleExtra">{lang="store_clear_filters"}</a>
			{{endif}}
			{lang="store_filter_by"}
		</h2>
		<div class='ipsPad_half'>
			{{foreach $category->filters( \IPS\Member::loggedIn()->language() ) as $filterId => $values}}
				<div class="ipsSideMenu ipsSideMenu_withRadios ipsType_medium">
					<h4 class='ipsSideMenu_title ipsSpacer_top ipsSpacer_half'>{lang="nexus_product_filter_{$filterId}_public"}</h4>
					<ul class='ipsSideMenu_list'>
						{{foreach $values as $valueId => $value}}
							<li>
								{{$active = ( isset( request.filter[ $filterId ] ) and \in_array( $valueId, explode( ',', request.filter[ $filterId ] ) ) );}}
								<a data-action="filter" href='{{if $active}}{$url->setQueryString( 'filter', \IPS\nexus\Package\Filter::queryString( \IPS\Request::i()->filter, $filterId, NULL, $valueId ) )}{{else}}{$url->setQueryString( 'filter', \IPS\nexus\Package\Filter::queryString( \IPS\Request::i()->filter, $filterId, $valueId ) )}{{endif}}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line {{if $active}}ipsSideMenu_itemActive{{endif}}'>
									{$value}
								</a>
							</li>
						{{endforeach}}
					</ul>
				</div>
			{{endforeach}}
			<div class="ipsSideMenu ipsSideMenu_withRadios ipsType_medium">
				<h4 class='ipsSideMenu_title ipsSpacer_top ipsSpacer_half'>{lang="price"}</h4>
				<ul class='ipsSideMenu_list'>
					{{$haveCategoryPriceFilters = ( $category->price_filters and $priceFilters = json_decode( $category->price_filters, TRUE ) and isset( $priceFilters[ $currency ] ) and \count( $priceFilters[ $currency ] ) ); $lastAmount = 0; $activePriceFilter = FALSE;}}
					{{if $haveCategoryPriceFilters}}
						{{foreach $priceFilters[ $currency ] as $amount}}
							<li>
								{{if $lastAmount}}
									{{if request.minPrice and request.maxPrice and request.minPrice == $lastAmount and request.maxPrice == $amount}}
										{{$activePriceFilter = TRUE;}}
										<a data-action="filter" href='{$url->setQueryString( 'minPrice', NULL )->setQueryString( 'maxPrice', NULL )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line ipsSideMenu_itemActive'>
									{{else}}
										<a data-action="filter" href='{$url->setQueryString( 'minPrice', $lastAmount )->setQueryString( 'maxPrice', $amount )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>
									{{endif}}
										{money="$lastAmount" currency="$currency"}&ndash;{money="$amount" currency="$currency"}
									</a>
								{{else}}
									{{if request.maxPrice and request.maxPrice == $amount and !request.minPrice}}
										{{$activePriceFilter = TRUE;}}
										<a data-action="filter" href='{$url->setQueryString( 'maxPrice', NULL )->setQueryString( 'minPrice', NULL )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line ipsSideMenu_itemActive'>
									{{else}}
										<a data-action="filter" href='{$url->setQueryString( 'maxPrice', $amount )->setQueryString( 'minPrice', NULL )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>
									{{endif}}
										{money="0" currency="$currency"}&ndash;{money="$amount" currency="$currency"}
									</a>
								{{endif}}
							</li>
							{{$lastAmount = $amount;}}
						{{endforeach}}
						<li>
							{{if request.minPrice and request.minPrice == $lastAmount and !request.maxPrice}}
								{{$activePriceFilter = TRUE;}}
								<a data-action="filter" href='{$url->setQueryString( 'minPrice', NULL )->setQueryString( 'maxPrice', NULL )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line ipsSideMenu_itemActive'>
							{{else}}
								<a data-action="filter" href='{$url->setQueryString( 'minPrice', $lastAmount )->setQueryString( 'maxPrice', NULL )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>
							{{endif}}
								{money="$lastAmount" currency="$currency"}+
							</a>
						</li>
					{{endif}}
					{{if !$activePriceFilter and ( request.minPrice or request.maxPrice )}}
						<li>
							<a data-action="filter" href='{$url->setQueryString( 'minPrice', NULL )->setQueryString( 'maxPrice', NULL )}' class='ipsSideMenu_item ipsTruncate ipsTruncate_line ipsSideMenu_itemActive'>
								{{if request.minPrice and request.maxPrice}}
									{money="\IPS\Request::i()->minPrice" currency="$currency"}&ndash;{money="\IPS\Request::i()->maxPrice" currency="$currency"}
								{{elseif request.minPrice}}
									{money="\IPS\Request::i()->minPrice" currency="$currency"}+
								{{else}}
									{money="0" currency="$currency"}&ndash;{money="\IPS\Request::i()->maxPrice" currency="$currency"}
								{{endif}}
							</a>
						</li>				
					{{endif}}
					<li>
						<a href='{$url->setQueryString( 'do', 'priceFilter' )}' data-ipsDialog data-ipsDialog-size="narrow" data-ipsDialog-title="{lang="price_filter_set"}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>
							{lang="custom_price_filter"}
						</a>
					</li>				
				</ul>
			</div>
			{{if $havePackagesWhichAcceptReviews}}
				<div class="ipsSideMenu ipsSideMenu_withRadios ipsType_medium">
					<h4 class='ipsSideMenu_title ipsSpacer_top ipsSpacer_half'>{lang="minRating"}</h4>
					<ul class='ipsSideMenu_list'>
						{{foreach range( 5, 1 ) as $minRating}}
							<li>
								<a data-action="filter" href="{$url->setQueryString( 'minRating', \IPS\Request::i()->minRating == $minRating ? NULL : $minRating )}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line {{if request.minRating and request.minRating == $minRating}}ipsSideMenu_itemActive{{endif}}'>
									{template="rating" group="global" app="core" params="'large', $minRating, \IPS\Settings::i()->reviews_rating_out_of"}
								</a>
							</li>
						{{endforeach}}
					</ul>
				</div>
			{{endif}}
			{{if $havePackagesWhichUseStockLevels}}
				<div class="ipsSideMenu ipsSideMenu_withRadios ipsType_medium">
					<h4 class='ipsSideMenu_title ipsSpacer_top ipsSpacer_half'>{lang="nexus_stock"}</h4>
					<ul class='ipsSideMenu_list'>
						<li>
							<a data-action="filter" href="{$url->setQueryString( 'inStock', \IPS\Request::i()->inStock ? NULL : 1 )}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line {{if request.inStock}}ipsSideMenu_itemActive{{endif}}'>
								{lang="in_stock_only"}
							</a>
						</li>
					</ul>
				</div>
			{{endif}}
		</div>
	</div>
	{{endif}}

	{template="chooseCurrency" group="store" params="$category ? $category->url() : \IPS\Http\Url::internal('app=nexus&module=store&controller=store', 'front', 'store')"}
</div>