<ips:template parameters="$category, $subcategories, $packages, $pagination, $packagesWithCustomFields, $totalCount" />
{{if \count( $packages )}}
	{{$view = isset( \IPS\Request::i()->cookie['storeView'] ) ? \IPS\Request::i()->cookie['storeView'] : \IPS\Theme::i()->settings['cm_store_view'];}}
	<section class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'><span class='ipsType_medium'>{lang="products_count" pluralize="$totalCount"}</span></h2>
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				<li>
					<a data-action="filter" href="{$category->url()->setQueryString( 'view', 'grid' )->csrf()}" data-ipsTooltip title='{lang="view_products_grid"}' class="{{if $view == 'grid'}}ipsButtonRow_active{{endif}}"><i class="fa fa-th-large"></i></a>
				</li>
				<li>
					<a data-action="filter" href="{$category->url()->setQueryString( 'view', 'list' )->csrf()}" data-ipsTooltip title='{lang="view_products_list"}' class='{{if $view == 'list'}}ipsButtonRow_active{{endif}}'><i class="fa fa-th-list"></i></a>
				</li>
			</ul>
			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				<li>
					<a href="#elSortByMenu_menu" id="elSortByMenu_products" data-role="sortButton" data-ipsMenu data-ipsMenu-activeclass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="sort_by"} <i class="fa fa-caret-down"></i></a>
					<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elSortByMenu_products_menu">
						{{foreach array( 'default', 'name', 'price_low', 'price_high', 'rating' ) as $k}}
							<li class="ipsMenu_item {{if ( request.sortby and request.sortby == $k ) or ( !request.sortby and $k === 'default' )}}ipsMenu_itemChecked{{endif}}" data-ipsmenuvalue="{$k}">
								{{if $k === 'default'}}
									<a data-action="filter" href="{$category->url()}">
								{{else}}
									<a data-action="filter" href="{$category->url()->setQueryString( 'sortby', $k )}">
								{{endif}}
									{lang="products_sort_{$k}"}
								</a>
							</li>
						{{endforeach}}
					</ul>
				</li>
			</ul>
			{{if $pagination}}
				{$pagination|raw}
			{{endif}}
		</div>
		{{if \count( $packages )}}
			{{if $view == 'list'}}
				<ol class='ipsDataList ipsDataList_large cNexusCategory_list' data-role="packageList">
					{{foreach $packages as $package}}
						{template="packageRow" group="store" params="$package, \in_array( $package->id, $packagesWithCustomFields )"}
					{{endforeach}}
				</ol>
			{{else}}
				<div class='ipsPad'>
					<ol class='ipsGrid ipsGrid_collapsePhone cNexusCategory_grid' data-ipsGrid data-ipsGrid-minItemSize='170' data-ipsGrid-maxItemSize='230' data-ipsGrid-equalHeights='row' data-role="packageList">
						{{foreach $packages as $package}}
							{template="packageBlock" group="store" params="$package"}
						{{endforeach}}
					</ol>
				</div>
			{{endif}}
		{{endif}}
		{{if trim( $pagination ) != ''}}
			<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
				{$pagination|raw}
			</div>
		{{endif}}
	</section>
{{elseif ( !\count( $subcategories ) )}}
	<div class="ipsPad ipsPad_double ipsType_center ipsType_light ipsType_large" data-role="packageList">{lang="store_empty"}</div>
{{endif}}