<ips:template parameters="$baseUrl" />
{{if \count( \IPS\nexus\Money::currencies() ) > 1}}
	{{$memberCurrency = ( ( isset( \IPS\Request::i()->cookie['currency'] ) and \in_array( \IPS\Request::i()->cookie['currency'], \IPS\nexus\Money::currencies() ) ) ? \IPS\Request::i()->cookie['currency'] : \IPS\nexus\Customer::loggedIn()->defaultCurrency() );}}
	<div class='ipsType_center ipsBox ipsPadding ipsSpacer_top ipsSpacer_half' {{if isset( $_SESSION['cart'] ) and \count( $_SESSION['cart'] )}}data-controller="nexus.front.store.currencySelect"{{endif}}>
		<span class='ipsType_normal'>{lang="show_prices_in"}</span><br>
		<ul class='ipsList_inline'>
			{{foreach \IPS\nexus\Money::currencies() as $currency}}
				<li>
					{{if $currency == $memberCurrency}}
						<a data-action="filter" href='{$baseUrl->setQueryString( 'currency', $currency )->csrf()}' class='ipsType_blendLinks' title='{lang="set_currency_to" sprintf="$currency"}'>
							<strong><i class='fa fa-check'></i> {$currency}</strong>
						</a>
					{{else}}
						<a data-action="filter" href='{$baseUrl->setQueryString( 'currency', $currency )->csrf()}' title='{lang="set_currency_to" sprintf="$currency"}'>{$currency}</a>
					{{endif}}
				</li>
			{{endforeach}}
		</ul>
	</div>
{{endif}}