<ips:template parameters="$package, $orientation='vertical', $mini=FALSE, $showAddToCart=FALSE" />

<li class='ipsGrid_span3 {{if $orientation == 'horizontal'}}ipsCarousel_item{{else}}ipsDataItem{{endif}} cNexusWidgetProduct {{if $mini}}cNexusProduct_mini{{endif}} ipsPad_half ipsClearfix {{if $orientation == 'vertical'}}ipsSpacer_bottom{{endif}}'>
	{{if $orientation == 'vertical'}}
		<a href='{$package->url()}' class='cNexusProduct_image ipsType_center'>
			{{if $package->image}}
				<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src="{$package->image}" class='ipsImage' alt='{$package->_title}' width="140">
			{{else}}
				<div class='ipsNoThumb ipsNoThumb_product'>&nbsp;</div>
			{{endif}}
		</a>
	{{else}}
		<a href='{$package->url()}' class='cNexusProduct_image'>
			{{if $package->image}}
				<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src="{$package->image}" class='ipsImage' alt='{$package->_title}' width="140">
			{{else}}
				<div class='ipsNoThumb ipsThumb_large ipsNoThumb_product'>&nbsp;</div>
			{{endif}}
		</a>
	{{endif}}
	<div>
		<div class='cNexusProduct_info ipsSpacer_top ipsSpacer_half'>
			<h2 class='cNexusProduct_title ipsType_normal ipsType_unbold ipsType_reset'>
				<a href="{$package->url()}" data-role='productLink' class='{{if $orientation == 'horizontal'}}ipsTruncate ipsTruncate_line{{endif}}'>{$package->_title}</a>
			</h2>
			<div class='ipsType_reset ipsTruncate ipsTruncate_line cNexusPrice_widget'>
				{template="packageBlockPrice" app="nexus" group="store" params="$package->fullPriceInfo()"}
			</div>
			{{if $package->physical}}
			{{$stockLevel = $package->stockLevel();}}
				{{if $stockLevel === 0}}
					<span class='ipsType_small cNexusStock cNexusStock_notInStock ipsType_warning'>{lang="out_of_stock"}</span>
				{{else}}
					<span class='ipsType_small cNexusStock cNexusStock_inStock'>
						{{if $stockLevel and settings.nexus_show_stock}}
							{lang="x_in_stock" pluralize="$stockLevel"}
						{{else}}
							{lang="in_stock"}
						{{endif}}
					</span>
				{{endif}}
			{{endif}}
			{{if $package->reviewable}}
				<div>
					{template="rating" group="global" app="core" params="'medium', $package->item()->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of"}<span class='ipsType_medium ipsType_light'>({$package->item()->reviews})</span>
				</div>
			{{endif}}
		</div>
	</div>
</li>
