<ips:template parameters="$package, $hasCustomFields=FALSE" />

<li class='ipsDataItem'>
	<div class='ipsDataItem_generic ipsDataItem_size5'>
		<a href='{$package->url()}' class='cNexusProduct_image'>
			{{if $package->image}}
				<img src="{$package->image}" class='ipsImage' alt="{$package->_title}" width="140">
			{{else}}
				<div class='ipsNoThumb ipsNoThumb_product'>&nbsp;</div>
			{{endif}}
		</a>
	</div>
	<div class='ipsDataItem_main'>
		<h2 class='ipsDataItem_title ipsType_sectionHead ipsType_blendLinks'>
			<a href="{$package->url()}" class="ipsContained ipsType_break">
				{$package->_title}
				{{if $package->featured}}<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>{{endif}}
			</a>
		</h2>
		{{if $package->reviewable}}
			<div>
				{template="rating" group="global" app="core" params="'large', $package->item()->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $package->item()->memberReviewRating()"} <span class='ipsType_small'>({lang="num_reviews" pluralize="$package->item()->reviews"})</span>
			</div>
		{{endif}}
		{template="packageBlockPrice" app="nexus" group="store" params="$package->fullPriceInfo()"}
		{{$truncateAttributes = array('data-ipsTruncate', 'data-ipsTruncate-size="4 lines"', 'data-ipsTruncate-type="remove"');}}
		{template="richText" group="global" app="core" location="global" params="$package->description, array('ipsType_medium', 'ipsType_break', 'ipsContained', 'ipsSpacer_top', 'ipsSpacer_half'), array(), $truncateAttributes"}
	</div>
	<div class='ipsDataItem_generic ipsDataItem_size5 ipsPos_top ipsType_right'>
		<div class='ipsPad_half'>
			{{if $package->stock === 0}}
				<span class='ipsButton ipsButton_primary ipsButton_verySmall ipsButton_narrow ipsButton_disabled ipsCursor_locked'>{lang="out_of_stock"}</span>
			{{else}}
				<a href='{$package->url()->setQueryString( 'purchase', 1 )}' class='ipsButton ipsButton_primary ipsButton_verySmall ipsButton_narrow' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="store_quick_view"}' data-ipsDialog-forceReload data-ipsDialog-destructOnClose='true'>
					<i class='fa fa-shopping-cart'></i>&nbsp;
					{{if $hasCustomFields}}
						{lang="add_and_choose_options"}
					{{else}}
						{lang="add_to_cart"}
					{{endif}}
				</a>
			{{endif}}
		</div>
	</div>
</li>