<ips:template parameters="$package, $grid=TRUE, $carousel=FALSE, $mini=FALSE" />

<li class='{{if $grid}}ipsGrid_span3{{endif}} {{if $carousel}}ipsCarousel_item{{endif}} cNexusProduct {{if $mini}}cNexusProduct_mini{{endif}} ipsPad_half ipsClearfix'>
	<a href='{$package->url()}' class='cNexusProduct_image'>
		{{if $package->image}}
		<img src="{$package->image}" class='ipsImage'>
		{{else}}
		<div class='ipsNoThumb ipsNoThumb_product'>&nbsp;</div>
		{{endif}}
	</a>
	<div>
		<h2 class='cNexusProduct_title ipsType_normal ipsType_unbold ipsType_reset ipsType_blendLinks'>
			<a href="{$package->url()}" data-role='productLink' class='{{if $carousel}}ipsTruncate ipsTruncate_line{{endif}}'>{$package->_title}</a>
		</h2>
		<div class='ipsType_reset ipsTruncate ipsTruncate_line'>
			{template="packageBlockPrice" app="nexus" group="store" params="$package->fullPriceInfo()"}
		</div>
		{{if $package->physical}}
		{{if $package->stock !== 0}}
		<span class='ipsType_small cNexusStock cNexusStock_inStock'>{{if settings.nexus_show_stock && $package->stock !== -1 && $package->stock !== -2}}{lang="x_in_stock" pluralize="$package->stock"}{{else}}{lang="in_stock"}{{endif}}</span>
		{{else}}
		<span class='ipsType_small cNexusStock cNexusStock_notInStock ipsType_warning'>{lang="out_of_stock"}</span>
		{{endif}}
		{{endif}}
		{{if $package->reviewable}}
		<div>
			{template="rating" group="global" app="core" params="'medium', $package->item()->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $package->item()->memberReviewRating()"} {{if !$mini}}<span class='ipsType_small'>({$package->item()->reviews})</span>{{endif}}
		</div>
		{{endif}}
	</div>
</li>