<ips:template parameters="$package, $item, $purchaseForm" />

<div class='ipsPad' data-controller='nexus.front.store.packagePage' data-itemTitle="{$package->_title}">
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_medium'>
			{{if $images = $item->images() and \count( $images )}}
				{{$donePrimary = false;}}
				{{foreach $images as $image}}
					{{if !$donePrimary}}
						<a href='{$image}' class='cNexusProduct_primaryImage ipsContained'><img src='{$image}' class="ipsImage ipsImage_thumb"></a>
						{{$donePrimary = true;}}
					{{endif}}
				{{endforeach}}
			{{endif}}
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<h1 class='ipsType_pageTitle'>{$item->mapped('title')}</h1>
			<hr class='ipsHr'>
			{$purchaseForm|raw}
		</div>
	</div>
</div>