<ips:template parameters="$packages" />

<div class='ipsPad'>
	<br>
	<h1 class='ipsType_veryLarge ipsType_center ipsType_reset'>{lang='sign_up'}: {lang="choose_product"}</h1>
	<p class='ipsType_large ipsType_center ipsType_light'>
		{{if settings.nexus_reg_force}}
			{lang="store_forced_purchase"}
		{{else}}
			{lang="store_optional_purchase"}
		{{endif}}
	</p>
	{{if isset( $_SESSION['cart'] ) and \count( $_SESSION['cart'] )}}
		<p class='ipsType_large ipsType_center ipsType_light'>
			<a href='{url="app=nexus&module=store&controller=cart" seoTemplate="store_cart"}'>{lang="continue_to_registration"} <i class='fa fa-caret-right'></i></a>
		</p>
	{{endif}}
	<br>
		
	<section data-controller='nexus.front.store.register'>
		<div class='ipsBox'>
			<div class='ipsPad_half'>
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots data-role='productCarousel'>
					<div class='ipsCarousel_inner'>
						<ul class='cNexusCarousel cNexusCategory_grid ipsClearfix' data-role="carouselItems">
							{{foreach $packages as $package}}
								{template="packageBlock" group="store" params="$package, TRUE, TRUE, TRUE"}
							{{endforeach}}
						</ul>
					</div>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			</div>
		</div>

		<div data-role='productInformationWrapper' class='ipsHide cNexusRegister_info'>
			<hr class='ipsHr'>
			<a href='#' class='cNexusRegister_close ipsHide' data-action='closeInfo'>&times;</a>
			<div class='ipsSpacer_top' data-role='productInformation'></div>
		</div>
	</section>
	
	{{if !settings.nexus_reg_force}}
		<p class='ipsType_right ipsType_normal'><a href='{url="app=core&module=system&controller=register&noPurchase=1" seoTemplate="register"}'>{lang="continue_without_purchasing"} <i class='fa fa-caret-right'></i></a></p>
	{{endif}}
</div>