<ips:template parameters="$purchase" />

<ul class='ipsList_inline'>
	<li>
		<strong class="ipsType_minorHeading">{lang="ps_start"}</strong>
		<br>{$purchase->start->localeDate()}
	</li>
	{{if $purchase->expire}}
		<li>
			<strong class="ipsType_minorHeading">{lang="ps_expire"}</strong>
			<br>{$purchase->expire->localeDate()}
		</li>
	{{endif}}
	{{if $purchase->renewals and !$purchase->grouped_renewals}}
		<li>
			<strong class="ipsType_minorHeading">{lang="purchase_renewal_terms"}</strong>
			<br>{$purchase->renewals->toDisplay( $purchase->member )}
		</li>
	{{endif}}
	{{if $purchase->billing_agreement AND !$purchase->billing_agreement->canceled}}
		<li>
			<strong class="ipsType_minorHeading">{lang="ps_billing_agreement"}</strong>
			<br><a href='{$purchase->billing_agreement->url()}' class="ipsType_blendLinks">{$purchase->billing_agreement->gw_id}</a>
		</li>
	{{endif}}

</ul>

<ul class='ipsList_inline ipsSpacer_top'>
	<li>
		<a href="{$purchase->url()}" class="ipsButton ipsButton_primary">{lang="nexus_subs_view_purchase"}</a>
	</li>
	{{if $pendingInvoice = $purchase->invoice_pending and $pendingInvoice->status === $pendingInvoice::STATUS_PENDING}}
		<li>
			<a href="{$pendingInvoice->checkoutUrl()}" class='ipsButton ipsButton_important' title="{lang="purchase_renew_now_title"}">{lang="purchase_renew_now"}</a>
		</li>
	{{elseif $purchase->expire AND $canRenewUntil = $purchase->canRenewUntil(NULL,TRUE)}}
		<li>
			<a href="{url="app=nexus&module=clients&controller=purchases&do=renew&id={$purchase->id}" base="front" csrf="true" seoTemplate="clientspurchaserenew" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $purchase->name )"}" class='ipsButton ipsButton_important' title="{lang="purchase_renew_now_title"}" {{if $canRenewUntil === TRUE or $canRenewUntil > 1}}data-ipsDialog data-ipsDialog-size='narrow'{{endif}}>{lang="purchase_renew_now"}</a>
		</li>
	{{endif}}
	{{if $purchase->canCancel()}}
		<li>
			<a href="{url="app=nexus&module=clients&controller=purchases&do=cancel&id={$purchase->id}" base="front" csrf="true" seoTemplate="clientspurchasecancel" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $purchase->name )"}" class='ipsButton ipsButton_negative' data-confirm data-confirmSubMessage="{lang="purchase_cancel_renewal_confirm"}">{lang="purchase_cancel_renewal"}</a>
		</li>
	{{endif}}
</ul>
