<ips:template parameters="$item, $lastCommenter, $members, $busy, $reacted, $images" />
{{$commentClass = $item::$commentClass;}}
{{if \IPS\IPS::classUsesTrait( $item, 'IPS\Content\Statistics' )}}
<div class="ipsAreaBackground_light">
<div class='ipsWidget ipsBox {{if ! \IPS\Application::appIsEnabled('cloud')}}ipsMargin_bottom{{endif}}'>
    <h4 class='ipsWidget_title'>{$item->mapped('title')}
        <span class="analytics-and-statistics ipsType_normal ipsType_medium ipsPos_right">
            <span class="ipsMargin_right"><i class="fa fa-comments" aria-hidden="true"></i> {lang="num_replies" pluralize="$item->mapped('num_comments')"}</span>
            <span><i class="fa fa-eye" aria-hidden="true"></i> {lang="num_views_with_number" pluralize="$item->mapped('views')"}</span>
        </span>
    </h4>
</div>
{{if \IPS\Application::appIsEnabled('cloud')}}
    {template="analyticsItem" app="cloud" group="analytics" params="$item"}
{{endif}}
<div class='ipsPad ipsFluidGrid ipsFluidGrid--analytics-and-statistics'>
    <div class='ipsWidget ipsBox'>
        <h4 class='ipsWidget_title'>{lang="active_members"}</h4>
        <div class='ipsWidget_inner'>
            {{if count( $members )}}
                <ul class='ipsDataList ipsDataList_reducedSpacing'>
                    {{foreach $members AS $member}}
                        <li class='ipsDataItem'>
                            <div class='ipsDataItem_icon ipsPos_top'>
                                {template="userPhoto" group="global" app="core" params="$member['member'], 'tiny'"}
                            </div>
                            <div class='ipsDataItem_main'>
                                <div>{$member['member']->link()|raw}</div>
                                <div>{lang="num_comments" pluralize="$member['count']"}</div>
                            </div>
                        </li>
                    {{endforeach}}
                </ul>
            {{else}}
                <p class='ipsPadding'>{lang="no_content_to_show"}</p>
            {{endif}}
        </div>
    </div>
    <div class='ipsWidget ipsBox'>
        <h4 class='ipsWidget_title'>{lang="popular_days"}</h4>
        <div class='ipsWidget_inner'>
            {{if count( $busy )}}
                <ul class='ipsDataList '>
                    {{foreach $busy AS $date => $day}}
                        <li class='ipsDataItem'>
                            <div class='ipsDataItem_main'>
                                <div class='ipsFlex ipsFlex-ai:center ipsFlex-jc:between'>
                                    <a href='{$item->url()->shareableUrl( $day['commentId'] )}' class='ipsType_semiBold'>{datetime="$day['date']"}</a>
                                    <span class='ipsType_light'>{lang="num_comments" pluralize="$day['count']"}</span>
                                </div>
                            </div>
                        </li>
                    {{endforeach}}
                </ul>
            {{else}}
                <p class='ipsPadding'>{lang="no_content_to_show"}</p>
            {{endif}}
        </div>
    </div>
    <div class='ipsWidget ipsBox'>
        <h4 class='ipsWidget_title'>{lang="top_reacted"}</h4>
        <div class='ipsWidget_inner'>
            {{if count( $reacted )}}
                <ul class='ipsDataList ipsDataList_reducedSpacing'>
                    {{foreach $reacted AS $react}}
                        <li class='ipsDataItem'>
                            <div class='ipsDataItem_icon ipsPos_top'>
                                {template="userPhoto" group="global" app="core" params="$react['comment']->author(), 'tiny'"}
                            </div>
                            <div class='ipsDataItem_main'>
                                <div class='ipsFlex ipsFlex-jc:between ipsFlex-fw:wrap'>
                                    <div>
                                        <div class='ipsType_semiBold'>{$react['comment']->author()->link()|raw}</div>
                                        <div class='ipsType_light'><a href="{$react['comment']->url()}" rel="nofollow" class='ipsType_blendLinks'>{$react['comment']->dateLine()|raw}</a></div>
                                    </div>
                                    <div class='ipsType_light'>{lang="react_total" pluralize="$react['count']"}</div>
                                </div>
                                <div class='ipsMargin_top:half' data-ipsTruncate data-ipsTruncate-size='4 lines' data-ipsTruncate-type='remove'>{$react['comment']->truncated()|raw}</div>
                            </div>
                        </li>
                    {{endforeach}}
                </ul>
            {{else}}
                <p class='ipsPadding'>{lang="no_content_to_show"}</p>
            {{endif}}
        </div>
    </div>
</div>
{{if count( $images )}}
<div class="ipsPad">
    <div class='ipsWidget ipsBox'>
        <h4 class='ipsWidget_title'>{lang="images"}</h4>
        <div class='ipsPadding'>
            <div class='ipsImageGrid'>
                {{foreach $images AS $image}}
                    <div><a href='{$image['commentUrl']}'><img src='{file="$image['attach_location']" extension="core_Attachment"}' loading='lazy' alt=''></a></div>
                {{endforeach}}
            </div>
        </div>
    </div>
</div>
{{endif}}
{{endif}}
</div>