<ips:template parameters="$table, $headers, $rows"/>
{{if !empty( $rows )}}
{{foreach $rows as $edit}}
<article class='ipsBox ipsBox--child ipsComment ipsComment_parent ipsClearfix ipsClear'>
    <div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone'>
        {template="userPhoto" app="core" group="global" params="\IPS\Member::load( $edit['member'] ), 'mini'"}
        <div>
            <h3 class='ipsComment_author ipsType_sectionHead'>
                {expression="\IPS\Member::load( $edit['member'] )->link()" raw="true"}
            </h3>
            <p class='ipsComment_meta ipsType_light'>
                {datetime="$edit['time']"}
                {{if $edit['reason']}}
                <br>
                {$edit['reason']}
                {{endif}}
            </p>
        </div>
    </div>
    <div class='ipsAreaBackground_reset ipsPad'>
        <div class='ipsType_richText'>
            {$edit['new']|raw}
        </div>
    </div>
</article>
{{endforeach}}

{{if $table->page == $table->pages AND $table->extra instanceof \IPS\Content}}
<article class='ipsBox ipsBox--child ipsComment ipsComment_parent ipsClearfix ipsClear'>
    <div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone'>
        {template="userPhoto" app="core" group="global" params="$table->extra->author(), 'mini'"}
        <div>
            <h3 class='ipsComment_author ipsType_sectionHead'>
                {$table->extra->author()->link(  NULL, NULL, $table->extra->isAnonymous() )|raw}
            </h3>
            <p class='ipsComment_meta ipsType_light'>
                {datetime="$table->extra->mapped('date')"}
            </p>
        </div>
    </div>
    <div class='ipsAreaBackground_reset ipsPadding_vertical sm:ipsPadding_vertical:half ipsPadding_horizontal'>
        <div class='ipsType_richText'>
            {$edit['old']|raw}
        </div>
    </div>
</article>
{{endif}}

{{else}}
<p class='ipsType_large ipsType_light'>{lang="no_edit_history"}</p>
{{endif}}