<ips:template parameters="$editHistory, $comment" />
{{if !\IPS\Request::i()->isAjax()}}
<h1 class='ipsType_pageTitle'>{lang="edit_history_title"}</h1>
{{endif}}

{{if \IPS\Settings::i()->edit_log_prune > 0}}
	<div class='ipsMessage ipsMessage_info{{if !\IPS\Request::i()->isAjax()}} ipsSpacer_top{{endif}}'>{lang="edit_log_prune_notice" pluralize="\IPS\Settings::i()->edit_log_prune"}</div>
{{endif}}

<div class="ipsPad" data-role="commentFeed">
    {$editHistory|raw}
</div>