<ips:template parameters="$groups, $lang = '', $extraClasses = ''" />

{{foreach $groups as $group}}
	{{$groupNames[] = $group->name;}}
{{endforeach}}
{{$list = \IPS\Member::loggedIn()->language()->formatList( $groupNames );}}

<ul class='ipsList_reset ipsFlex-inline ipsFlex-ai:center ipsGap:1 {$extraClasses}' {{if $lang}}data-ipsTooltip title='{lang="$lang" htmlsprintf="$list"}'{{endif}}>
	{{foreach $groups as $group}}
		{{if $group->g_icon }}
			<li><img src='{file="$group->g_icon" extension="core_Theme"}' alt='' class='cGroupIndicator'></li>
		{{else}}
			<li><span class='ipsBadge ipsBadge_neutral ipsBadge_small'>{$group->name}</span></li>
		{{endif}}
	{{endforeach}}
</ul>