<ips:template parameters="$currentUrl" />

{{if \IPS\Request::i()->cookieConsentEnabled() OR ( !\IPS\Member::loggedIn()->member_id AND !\IPS\Request::i()->cookieConsentEnabled() ) }}
{{$termsLang = \IPS\Member::loggedIn()->language()->addToStack( 'terms_of_use' );}}
{{$privacyLang = \IPS\Member::loggedIn()->language()->addToStack( 'terms_privacy' );}}
{{$glLang = \IPS\Member::loggedIn()->language()->addToStack( 'guidelines' );}}
{{$termsUrl = (string) \IPS\Http\Url::internal( 'app=core&module=system&controller=terms', 'front', 'terms' );}}
{{$terms = "<a href='$termsUrl'>$termsLang</a>";}}

{{if \IPS\Settings::i()->privacy_type == 'internal'}}
{{$privacyUrl = (string) \IPS\Http\Url::internal( 'app=core&module=system&controller=privacy', 'front', 'privacy' );}}
{{else}}
{{$privacyUrl = \IPS\Settings::i()->privacy_link;}}
{{endif}}
{{$privacy = "<a href='$privacyUrl'>$privacyLang</a>";}}

{{if \IPS\Settings::i()->gl_type == 'internal'}}
{{$glUrl = (string) \IPS\Http\Url::internal( 'app=core&module=system&controller=guidelines', 'front', 'guidelines' );}}
{{else}}
{{$glUrl = \IPS\Settings::i()->gl_link;}}
{{endif}}
{{$guidelines = "<a href='$glUrl'>$glLang</a>";}}
{{$cookiesUrl = (string) \IPS\Http\Url::internal( 'app=core&module=system&controller=cookies', 'front', 'cookies' );}}
{{$cookies = \IPS\Member::loggedIn()->language()->addToStack( 'cookies_message', FALSE, array( 'sprintf' => array( $cookiesUrl, $cookiesUrl ) ) );}}
{{$status = (int) !\IPS\Member::loggedIn()->optionalCookiesAllowed;}}
<div id='elGuestTerms' class='ipsPad_half ipsJS_hide' data-role='{{if \IPS\Request::i()->cookieConsentEnabled()}}cookieConsentBar{{else}}guestTermsBar{{endif}}' data-controller='core.front.core.guestTerms'>
	<div class='ipsLayout_container cGuestTerms'>
		<div>
			<h2 class='ipsType_sectionHead'>{lang='guest_terms_title'}</h2>
			<p class='ipsType_reset ipsType_medium cGuestTerms_contents'>{lang="guest_terms_bar_text_value" htmlsprintf="$terms, $privacy, $guidelines, $cookies"}</p>
		</div>
		<div class='ipsFlex-flex:11 ipsFlex ipsFlex-fw:wrap ipsGap:3'>
			{{if \IPS\Request::i()->cookieConsentEnabled()}}
			<form action="{url="app=core&module=system&controller=cookies&do=cookieConsentToggle&ref={$currentUrl}" csrf="true"}" method="post">
			    <input type="hidden" name='ref' value="{$currentUrl}">
                <button type="submit" name="status" value="1" class='ipsButton ipsButton_positive ipsButton_large ipsFlex-flex:11'><i class='fa fa-check'></i>&nbsp;{lang='accept_cookies'}</button>
                <button type="submit" name="status" value="0" class='ipsButton ipsButton_veryLight ipsButton_large ipsFlex-flex:11'>&nbsp;{lang='cookieconstent_reject'}</button>
			</form>
			{{else}}
			<a href='{url="app=core&module=system&controller=terms&do=dismiss&ref={$currentUrl}" csrf="true"}' rel='nofollow' class='ipsButton ipsButton_veryLight ipsButton_large ipsButton_fullWidth' data-action="dismissTerms"><i class='fa fa-check'></i>&nbsp; {lang="guest_terms_close"}</a>
			{{endif}}
		</div>
	</div>
</div>
{{endif}}
