<ips:template parameters="$comment" />
{{$idField = $comment::$databaseColumnId;}}
{{$type = ( $comment instanceof \IPS\Content\Review ) ? 'review' : 'comment';}}

<div class='ipsPadding ipsHide cPostShareMenu' id='elShare{expression="\ucfirst( $type )"}_{$comment->$idField}_menu'>
	<h5 class='ipsType_normal ipsType_reset'>{lang="link_to_$type"}</h5>
	{{if $comment->isFirst() }}
		{{$url = $comment->item()->url();}}
	{{else}}
		{{$url = $comment->shareableUrl( $type );}}
	{{endif}}
	{{if \IPS\Settings::i()->ref_on}}
	{{$url = $url->setQueryString( array( '_rid' => \IPS\Member::loggedIn()->member_id  ) );}}
	{{endif}}
    <span data-ipsCopy data-ipsCopy-flashmessage>
        <a href="{$url}" class="ipsButton ipsButton_light ipsButton_small ipsButton_fullWidth" data-role="copyButton" data-clipboard-text="{$url}" data-ipstooltip title='{lang="copy_share_link"}'><i class="fa fa-clone"></i> {$url}</a>
    </span>

	{{if (!$comment->item()->containerWrapper() OR !$comment->item()->container()->disable_sharelinks ) and \count( $comment->sharelinks() )}}
	<h5 class='ipsType_normal ipsType_reset ipsSpacer_top'>{lang="share_externally"}</h5>
	{template="sharelinks" group="global" app="core" params="$comment"}
	{{endif}}
</div>