<ips:template parameters="$member, $categories" />
<div class='ipsBox ipsSpacer_bottom'>
	<h2 class='ipsBox_titleBar ipsType_reset'>
		<i class="fa fa-bell ipsBox_titleBar__icon" aria-hidden="true"></i>
		{lang="notification_options"}
	</h2>
	<ul class="ipsDataList cMemberNotifications">
		{{foreach $categories as $k => $enabled}}
			<li class="ipsDataItem">
				<a href="{url="app=core&module=members&controller=members&do=editBlock&block=IPS\\core\\extensions\\core\\MemberACPProfileBlocks\\Notifications&id={$member->member_id}&type={$k}"}" class="ipsType_blendLinks" data-ipsDialog data-ipsDialog-title="{lang="notifications__$k"}">
					<div class="ipsDataItem_main">
						<h3 class="ipsDataItem_title ipsType_reset">
							{lang="notifications__$k"}
						</h3>
						<div class="ipsDataItem_meta ipsType_reset ipsType_light">
							{{if \count( $enabled )}}
								{expression="\IPS\Member::loggedIn()->language()->formatList( array_map( function( $option ) { return $option['title']; }, $enabled ), \IPS\Member::loggedIn()->language()->get('member_notifications_list_format') )"}
							{{else}}
								{lang="notifications_off"}
							{{endif}}
						</div>
					</div>
				</a>
			</li>
		{{endforeach}}
	</ul>
</div>