<ips:template parameters="$member" />
{{if settings.achievements_enabled}}
<div class='ipsSpacer_bottom'>
    <div class='ipsGrid ipsGrid_collapsePhone acpMemberView_quotas'>
        <div class='ipsGrid_span6'>
            <div class='acpMemberView_quota ipsBox' style='min-height: 100%'>
                <h2 class='ipsBox_titleBar ipsType_reset'>
                    <i class="fa fa-line-chart ipsBox_titleBar__icon" aria-hidden="true"></i>
                    {{if member.hasAcpRestriction( 'core', 'members', 'member_edit' )}}
                    <a href="{url="app=core&module=members&controller=members&do=editBlock&block=IPS\\core\\extensions\\core\\MemberACPProfileBlocks\\Points&id={$member->member_id}"}" class="ipsPos_right ipsType_medium">{lang="acp_profile_points_manage"}</a>
                    {{endif}}
                    {lang="acp_profile_ranks_title"}
                </h2>
				{{if $member->rank()}}
                <div class='ipsPadding_horizontal ipsPadding_bottom'>
                    <span class='acpMemberView_quotaNumber ipsType_medium'>{$member->rank()->_title}</span><br>
                    <span class='ipsType_medium ipsType_light'>{lang="acp_profile_points" sprintf="$member->achievements_points"}</span>
                    {{if $nextRank = $member->nextRank()}}
                    <div class="ipsAttachment_progress acpMemberView_progress ipsSpacer_bottom ipsSpacer_top ipsSpacer_half"><span style='width: calc({expression="$member->achievements_points"} / {$nextRank->points} * 100%)'></span>
                    </div>
                    <span class='ipsType_medium ipsType_light'>{lang="acp_rank_points_for_next"} {expression="$nextRank->points - $member->achievements_points"}</span>
                    {{endif}}
                </div>
				{{endif}}
            </div>
        </div>
        <div class='ipsGrid_span6'>
            <div class='acpMemberView_quota ipsBox' style='min-height: 100%'>
                <h2 class='ipsBox_titleBar ipsType_reset'>
                    <i class="fa fa-certificate ipsBox_titleBar__icon" aria-hidden="true"></i>
                    {{if member.hasAcpRestriction( 'core', 'members', 'member_edit' )}}
                    <a href="{$member->acpUrl()->setQueryString('do', 'badges')}" class="ipsPos_right ipsType_medium">{lang="acp_profile_manage_badges"}</a>
                    {{endif}}
                    {lang="acp_profile_badges_title"}
                </h2>
                <div class='ipsPadding_horizontal ipsPadding_bottom'>
                    {{foreach $member->recentBadges(20) as $badge}}
                        <span>{$badge->html('ipsDimension:5')|raw}</span>
                    {{endforeach}}
                </div>
            </div>
        </div>
    </div>
</div>
{{endif}}
