<ips:template parameters="$notification, $withdrawal, $email" />
<br />
{$email->language->addToStack( "email_notify_withdrawal", FALSE )}
<br />
<br />
<a href='{url="app=nexus&module=payments&controller=payouts" base="admin"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("payout_view", FALSE)}</a>

<br />
<br />

<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>
<br />
<br />

<table cellpadding="10" cellspacing="0" border="0" width="100%">
	<tr>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" bgcolor="#f0f0f0">
			<strong>{$email->language->addToStack("payout_details", FALSE)}</strong>
		</td>
	</tr>
	<tr>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" bgcolor="#f9f9f9">
			<table width="100%" cellpadding="2" cellspacing="0" border="0">
				<tr>
					<td dir='{dir}' width="150" align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px"><strong>{$email->language->addToStack("payout_status", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">&nbsp;&nbsp;{$email->language->addToStack("payout_pending", FALSE)}</td>
				</tr>
				<tr>
					<td dir='{dir}' width="150" align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px"><strong>{$email->language->addToStack("po_gateway", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">&nbsp;&nbsp;{$withdrawal->gateway}</td>
				</tr>
				<tr>
					<td dir='{dir}' width="150" align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px; vertical-align: top;"><strong>{$email->language->addToStack("po_member", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
						&nbsp;&nbsp;{$withdrawal->member->cm_name} ({$withdrawal->member->email})
					</td>
				</tr>
				<tr>
					<td dir='{dir}' width="150" align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px"><strong>{$email->language->addToStack("po_date", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">&nbsp;&nbsp;{$withdrawal->date}</td>
				</tr>
				<tr>
					<td dir='{dir}' width="150" align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px"><strong>{$email->language->addToStack("po_amount", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">&nbsp;&nbsp;{$withdrawal->amount}</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
