<ips:template parameters="$invoice, $item, $commission, $email" />

{{if $item}}
	{$email->language->addToStack("email_commission_rev_product", FALSE, array( 'sprintf' => array( $item->name, $commission ) ) )} 
{{else}}
	{$email->language->addToStack("email_commission_rev_no_product", FALSE, array( 'sprintf' => array( $commission ) ) )} 
{{endif}}

<br />
<br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>