<ips:template parameters="$server, $encoded, $email" />

{expression="$email->language->addToStack( 'monitor_email_intro', FALSE, array( 'sprintf' => \IPS\Settings::i()->board_name ) )"}
<br />
<br />

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='color: #b52b38;'>
	<tr>
		<td dir='{dir}'>
			<strong>{expression="$email->language->addToStack( 'monitor_email_offline_panic', FALSE, array( 'sprintf' => $server->hostname ) )"}</strong>
		</td>
	</tr>
</table>
<br />

<a href='{setting="base_url"}applications/nexus/interface/monitoring/respond.php?a=a&server={$server->id}&by={$encoded}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{expression="$email->language->addToStack( 'monitor_email_acknowledge', FALSE, array( 'sprintf' => \IPS\Settings::i()->board_name ) )"}</a>

<a href='{setting="base_url"}applications/nexus/interface/monitoring/respond.php?a=r&server={$server->id}&by={$encoded}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{expression="$email->language->addToStack( 'monitor_email_reset', FALSE, array( 'sprintf' => \IPS\Settings::i()->board_name ) )"}</a>

<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>