<ips:template parameters="$rule, $email" />

{expression="$email->language->addToStack( 'monitor_email_intro', FALSE, array( 'sprintf' => \IPS\Settings::i()->board_name ) )"}
<br />
<br />

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='color: #b52b38;'>
	<tr>
		<td dir='{dir}'>
			<strong>{expression="$email->language->addToStack( 'monitor_email_eom', FALSE, array( 'sprintf' => array( $rule->url ) ) )"}</strong>
		</td>
	</tr>
</table>
<br />

<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>