<ips:template parameters="$invoice, $summary, $status, $email" />

{$email->language->get('email_new_invoice')}

<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>

<br /><br />

<h3 style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 24px; font-weight: 500; color: #333333; line-height: 21px; margin: 0 0 5px 0">
	{expression="sprintf( $email->language->get('order_number'), $invoice->id )"}
</h3>
<p style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; line-height: 24px; margin: 0">
	{{if $invoice->po}}
		<strong>{$email->language->get('invoice_po_number')}: {$invoice->po}</strong><br />
	{{endif}}
</p>

{{$updateCard = false;}}
{{if $invoice->status === \IPS\nexus\Invoice::STATUS_PENDING and $invoice->amountToPay()->amount->isGreaterThanZero() and $transactions = $invoice->transactions() and \count( $transactions )}}
	{{foreach $transactions as $transaction}}
		{{if $transaction->status !== $transaction::STATUS_PAID}}
			<p style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
				<strong style='color: #a52638'>
					{expression="sprintf( $email->language->get('email_payment_unsuccessful'), $transaction->method->getTitleForLanguage( $email->language ) )"}
				</strong>
			</p>
			{{$updateCard = true;}}
		{{endif}}
	{{endforeach}}
{{else}}
	<br>
{{endif}}

<a href='{{if $invoice->guest_data and isset( $invoice->guest_data['guestTransactionKey'] )}}{$invoice->url()->setQueryString( array( 'do' => 'printout', 'key' => $invoice->guest_data['guestTransactionKey'] ) )}{{else}}{$invoice->url()}{{endif}}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->get('email_view_order')}</a>


{{if $invoice->status === \IPS\nexus\Invoice::STATUS_PENDING and $invoice->amountToPay()->amount->isGreaterThanZero()}}
	&nbsp;&nbsp;
	<a href='{$invoice->checkoutUrl()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->get('order_pay_now')}</a>
	&nbsp;&nbsp;
	<span style="color: #8d8d8d; font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 13px; line-height: 32px">{expression="sprintf( $email->language->get('email_invoice_outstanding'), $invoice->amountToPay()->toString( $email->language ) )"}</span>
{{endif}}

<br />
<br />
<table cellpadding="10" cellspacing="0" border="0" width="100%">
	<tr>
		<td dir='{dir}' colspan="5" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" bgcolor="#f0f0f0">
			<strong>{$email->language->get("order_details")}</strong>
		</td>
	</tr>
	<tr bgcolor="#f9f9f9">
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
			&nbsp;
		</td>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 13px; color: #333333; line-height: 21px" colspan="2">
			<strong>{$email->language->addToStack('invoice_item', FALSE)}</strong>
		</td>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 13px; color: #333333; line-height: 21px" align='right'>
			<strong>{$email->language->get('total')}</strong>
		</td>
	</tr>
	{{foreach $summary['items'] as $k => $item}}
		<tr style='border-top: 1px solid #f5f5f5'>
			<td dir='{dir}' width='100' valign='top' class='hidePhone' style='width: 0; max-height: 0; overflow: hidden; float: left;'>
				{{if $image = $item->image()}}
					<img src='{$image->url}' width='100' style='border: 0; vertical-align: middle;'>
				{{endif}}
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
				<span style="color: #8d8d8d">{$item->quantity} x</span> {$item->name}
				{{if ( $item instanceof \IPS\nexus\Invoice\Item\Renewal ) AND \IPS\nexus\Purchase::load( $item->id )->expire}}
					<span style="color: #8d8d8d; font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px;">
						({$email->language->addToStack('ps_expire', FALSE)}: {expression="\IPS\nexus\Purchase::load( $item->id )->expire->localeDate( $invoice->member )"})
					</span>
				{{endif}}
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
				{{if \count( $item->details )}}
					{{foreach $item->details as $k => $v}}
						{$email->language->addToStack('nexus_pfield_' . $k, FALSE)}: {expression="\IPS\nexus\Package\CustomField::load( $k )->displayValue( $v )" raw="true"}<br>
					{{endforeach}}
				{{endif}}
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" align='right'>
				<strong>{$item->linePrice()->toString( $email->language )}</strong>
				{{if $item->quantity > 1}}
					<br><span style="color: #8d8d8d; font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px;">{$item->price->toString( $email->language )} {$email->language->get("each_short")}</span>
				{{endif}}
			</td>
		</tr>
	{{endforeach}}

	
	<tr style='border-top: 1px solid #dddddd'>
		<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
			<strong>{$email->language->get('subtotal')}</strong>
		</td>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" align='right'>
			<strong>{$summary['subtotal']->toString( $email->language )}</strong>
		</td>
	</tr>

	{{foreach $summary['shipping'] as $shipping}}
		<tr style='border-top: 1px solid #f5f5f5'>
			<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
				{$shipping->name}
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" align='right'>
				<strong>{$shipping->linePrice()->toString( $email->language )}</strong>
			</td>
		</tr>
	{{endforeach}}

	{{foreach $summary['tax'] as $taxId => $tax}}
		<tr style='border-top: 1px solid #f5f5f5'>
			<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
				{$email->language->get( 'nexus_tax_' . $taxId )} ({expression="$tax['rate']*100"}%)
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" align='right'>
				<strong>{$tax['amount']->toString( $email->language )}</strong>
			</td>
		</tr>
	{{endforeach}}

	{{if $transactions = $invoice->transactions() and \count( $transactions )}}
		<tr style='border-top: 1px solid #dddddd'>
			<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; line-height: 21px">
				<strong>{$email->language->get('total')}</strong>
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; line-height: 21px" align='right'>
				<strong>{$summary['total']->toString( $email->language )}</strong>
			</td>
		</tr>
		{{foreach $transactions as $transaction}}
			{{if $transaction->status === $transaction::STATUS_PAID}}
				<tr>
					<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; line-height: 21px">
						<strong>{$email->language->get('email_paid_by')} {{if $transaction->method}}{$transaction->method->getTitleForLanguage( $email->language )}{{else}}{$email->language->get('account_credit')}{{endif}}</strong>
					</td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; line-height: 21px" align='right'>
						<strong style="font-size: 1.5em">{$transaction->amount->toString( $email->language )}</strong>
					</td>
				</tr>
			{{endif}}
		{{endforeach}}
		<tr style='border-top: 1px solid #dddddd'>
			<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; color: #cd3816; line-height: 21px">
				<strong>{$email->language->get('total_to_pay')}</strong>
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; color: #cd3816; line-height: 21px" align='right'>
				<strong>{$invoice->amountToPay()->toString( $email->language )}</strong>
			</td>
		</tr>
	{{else}}
		<tr style='border-top: 1px solid #dddddd'>
			<td dir='{dir}' colspan='3' align='right' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; color: #cd3816; line-height: 21px">
				<strong>{$email->language->get('total')}</strong>
			</td>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 17px; color: #cd3816; line-height: 21px" align='right'>
				<strong>{$summary['total']->toString( $email->language )}</strong>
			</td>
		</tr>
	{{endif}}
</table>

<br />
<br />

<table cellpadding="0" cellspacing="0" border="0" width="100%" bgcolor="#ffffff" class='responsive_table'>
	<tr>
		<td dir='{dir}' width="{{if $invoice->hasPhysicalItems() and $invoice->shipaddress}}48%{{else}}100%{{endif}}" class='responsive_fullwidth' bgcolor="#f9f9f9">
			<table cellpadding="10" cellspacing="0" border="0" width="100%">
				<tr>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" bgcolor="#f0f0f0">
						<strong>{$email->language->get("billing_address")}</strong>
					</td>
				</tr>
				<tr>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
						{$invoice->member->cm_name}<br />
						{{if $invoice->billaddress}}{$invoice->billaddress->toString('<br />')|raw}{{endif}}
					</td>
				</tr>
			</table>
		</td>
		{{if $invoice->hasPhysicalItems() and $invoice->shipaddress}}
			<td dir='{dir}' width="4%"><img src='{setting="base_url"}applications/core/interface/email/spacer.png' width='1' height='1' alt=''></td>
			<td dir='{dir}' width="48%" class='responsive_fullwidth' bgcolor="#f9f9f9">
				<table cellpadding="10" cellspacing="0" border="0" width="100%">
					<tr>
						<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" bgcolor="#f0f0f0">
							<strong>{$email->language->get("shipping_address")}</strong>
						</td>
					</tr>
					<tr>
						<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
							{$invoice->member->cm_name}<br />
							{$invoice->shipaddress->toString('<br />')|raw}
						</td>
					</tr>
				</table>
			</td>
		{{endif}}
	</tr>
</table>