<ips:template parameters="$request, $member, $email" />

{$email->language->addToStack("support_bounced")}<br /><br />

{{if $request->department->email}}
	{{if $member->member_id}}
		{$email->language->addToStack("support_bounced_member", FALSE, array( 'sprintf' => $request->department->email))}<br /><br />
	
		<a href='{url="app=nexus&module=support&controller=home&do=create" seoTemplate="support_create" base="front"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("support_bounced_link", FALSE)}</a>
	{{else}}
		{$email->language->addToStack("support_bounced_guest", FALSE, array( 'sprintf' => $request->department->email))}
	{{endif}}
{{elseif $member->member_id}}
	<a href='{url="app=nexus&module=support&controller=home&do=create" seoTemplate="support_create" base="front"}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("support_bounced_link", FALSE)}</a>
{{endif}}

<br /><br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>