<ips:template parameters="$shipment, $email" />

{$email->language->addToStack("email_shipment_done", FALSE, array( 'sprintf' => array( $shipment->invoice->id ) ) )}

<br />
<br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>

<br /><br />
{{$data = $shipment->data;}}
<table width='100%' cellpadding='15' cellspacing='0' border='0' bgcolor='#f9f9f9'>
	<tr>
		<td dir='{dir}' width='50%' style="font-family: 'Helvetica Neue', helvetica, sans-serif;" valign='top'>
			<strong>{$data['cm_first_name']} {$data['cm_last_name']}</strong><br>
			{$shipment->address()->toString('<br>')|raw}
		</td>
		<td dir='{dir}' width='50%' style="font-family: 'Helvetica Neue', helvetica, sans-serif;" valign='top'>
			{{if $shipment->method}}
				<strong>{$email->language->addToStack("email_shipping_method", FALSE)}</strong><br>
				{$email->language->addToStack( $shipment->method->_titleLanguageKey, FALSE )}
			{{endif}}
			{{if $shipment->tracknumber}}
				<br><br>
				<strong>{$email->language->addToStack("email_tracking_number", FALSE)}</strong><br>
				{$shipment->tracknumber}
			{{endif}}
		</td>
	</tr>
	{{if $shipment->trackingUrl()}}
		<tr>
			<td dir='{dir}' colspan='2' bgcolor='#f0f0f0'>
				<a href='{$shipment->trackingUrl()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 13px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("order_track_delivery", FALSE)}</a>
			</td>
		</tr>
	{{endif}}
</table>

<br>

<table cellpadding="10" cellspacing="0" border="0" width="100%">
	<tr>
		<td dir='{dir}' colspan="5" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px" bgcolor="#f0f0f0">
			<strong>{$email->language->addToStack("email_items_in_shipment", FALSE)}</strong>
		</td>
	</tr>
	{{foreach $shipment->items as $item}}
		<tr style="border-top: 1px solid #f5f5f5">
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; color: #333333; line-height: 21px">
				<span style="color: #8d8d8d">{$item['quantity']} x</span> {$item['name']}
				{{if \count( $item['details'] )}}
					{{foreach $item['details'] as $k => $v}}
						<br>
						<span style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 13px">
							<strong>{$email->language->addToStack("nexus_pfield_" . $k, FALSE)}: </strong> {$v}
						</span>
					{{endforeach}}
				{{endif}}
			</td>
		</tr>
	{{endforeach}}
</table>