<ips:template parameters="$request, $firstMessage, $email" />
{{if $request->member == $firstMessage->member and $request->email == $firstMessage->email}}
	{$email->language->addToStack("staffnotify_new_header", FALSE, array( 'sprintf' => array( $request->supportAuthor()->name() ) ) )}<br />
{{else}}
	{$email->language->addToStack("staffnotify_new_header_on_behalf", FALSE, array( 'sprintf' => array( $firstMessage->member ? $firstMessage->author()->cm_name : $firstMessage->email, $request->supportAuthor()->name() ) ) )}<br />
{{endif}}
<br />

<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f5f5f5'>
	<tr>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5;">
			<h2 style='margin: 0; font-size: 19px; font-weight: 500'>#{$request->id} {$request->title}</h2>
			{$email->parseTextForEmail( $request->content(), $email->language )|raw}
		</td>
	</tr>
	<tr>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px; color: #8d8d8d">
			{$email->language->addToStack("department", FALSE)}: {$email->language->addToStack("nexus_department_".$request->department->_id, FALSE)} &middot; {$email->language->addToStack("r_severity", FALSE)}: {$email->language->addToStack("nexus_severity_".$request->severity->_id, FALSE)}
		</td>
	</tr>
			
</table>
<br />

<a href='{$request->acpUrl()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("view_support_request", FALSE)}</a> &nbsp; {$email->language->addToStack("or_you_can_reply", FALSE)}

<br />
<br />
<strong style="font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; color: #a52638">{$email->language->addToStack("staffnotify_note_warning", FALSE)}</strong>
<br />
<br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>
<br />
<div style="font-size: 0px; line-height: 0px; color:#ffffff !important;">{$email->language->addToStack("support_reply_email_id", FALSE, array( 'sprintf' => array( '[SR' . $request->id . '.' . $request->email_key . '.' . $request->comments( 1, NULL, 'date', 'asc', NULL, FALSE )->id . ']' ) ) )}</div>