<ips:template parameters="$message, $newMessage, $email" />
{$email->language->addToStack("your_reply_is_pending", FALSE)}<br />
<br />
<a href='{expression="\IPS\Settings::i()->base_url"}applications/nexus/interface/email/sendDiscard.php?id={$message->id}&key={expression="md5( $message->item()->email_key . $message->date )"}&send=1' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: #417ba3; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("send_it", FALSE)}</a>
<a href='{expression="\IPS\Settings::i()->base_url"}applications/nexus/interface/email/sendDiscard.php?id={$message->id}&key={expression="md5( $message->item()->email_key . $message->date )"}&send=0' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: #417ba3; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("discard_it", FALSE)}</a>
<br />
<br />
<table width='100%' cellpadding='15' cellspacing='0' border='0' style='background: #f5f5f5'>
	<tr>
		<td dir='{dir}'>
			{$email->parseTextForEmail( $newMessage->content(), $email->language )|raw}
		</td>
	</tr>
</table>
<br />

<a href='{$message->item()->acpUrl()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("view_support_request", FALSE)}</a><br />

<br />
<br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>