<ips:template parameters="$message, $email" />
{$email->language->addToStack("staffnotify_note_header", FALSE, array( 'sprintf' => array( $message->author()->name ) ) )}<br />
<br />

<table width='100%' cellpadding='15' cellspacing='0' border='0' bgcolor="#f6f0e4" style="border: 3px solid #ecdcb9;">
	<tr>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5;">
			<h2 style='margin: 0; font-size: 19px; font-weight: 500; color: #977b3e !important'>#{$message->item()->id} {$message->item()->title}</h2>
			{$email->parseTextForEmail( $message->content(), $email->language )|raw}
		</td>
	</tr>
	<tr>
		<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px; color: #8d8d8d">
			<table width='100%' cellpadding='0' cellspacing='0' border='0'>
				<tr>
					<td dir='{dir}' width='120' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px;"><strong>{$email->language->addToStack("status", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px;">{$email->language->addToStack("nexus_status_".$message->item()->status->_id."_admin", FALSE)}</td>
				</tr>
				<tr>
					<td dir='{dir}' width='120' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px;"><strong>{$email->language->addToStack("department", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px;">{$email->language->addToStack("nexus_department_".$message->item()->department->_id, FALSE)}</td>
				</tr>
				<tr>
					<td dir='{dir}' width='120' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px;"><strong>{$email->language->addToStack("r_severity", FALSE)}</strong></td>
					<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px;">{$email->language->addToStack("nexus_severity_".$message->item()->severity->_id, FALSE)}</td>
				</tr>
			</table>
		</td>
	</tr>
			
</table>
<br />

<a href='{$message->item()->acpUrl()}' style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">{$email->language->addToStack("view_support_request", FALSE)}</a> &nbsp; {$email->language->addToStack("or_you_can_reply", FALSE)}
<br /><br />

<strong style="font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; color: #a52638">{$email->language->addToStack("staffnotify_note_warning", FALSE)}</strong>

<br />
<br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>
<br />
<div style="font-size: 0px; line-height: 0px; color:#ffffff !important;">{$email->language->addToStack("support_reply_email_id", FALSE, array( 'sprintf' => array( '[SR' . $message->item()->id . '.' . $message->item()->email_key . '.' . $message->id . ']' ) ) )}</div>