<ips:template parameters="$requests, $email" />
{$email->language->addToStack("you_have_assigned_support_requests", FALSE)}<br />
<br />
<table width='100%' cellpadding='0' cellspacing='0' border='0'>
	{{foreach $requests as $request}}
		<tr>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5;">
				<a href="{$request->acpUrl()}" style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 17px; text-decoration: none;"><strong>{$request->title}</strong></a> <span style="color: #8d8d8d; font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 12px">#{$request->id}</span>
			</td>
		</tr>
		<tr>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px">
				<strong>{$email->language->addToStack("email_timeelapsed", FALSE)}:</strong> {expression="\IPS\DateTime::formatInterval( \IPS\DateTime::ts( time() )->diff( \IPS\DateTime::ts( $request->mapped('date') ) ), 2, $email->language )"}
			</td>
		</tr>
		<tr>
			<td dir='{dir}' style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 1.5; font-size: 13px; color: #8d8d8d;">
				<strong>{$email->language->addToStack("status", FALSE)}:</strong> {$email->language->addToStack("nexus_status_".$request->status->_id."_admin", FALSE)} &nbsp;&nbsp;&nbsp;<strong>{$email->language->addToStack("department", FALSE)}:</strong> {$email->language->addToStack("nexus_department_".$request->department->_id, FALSE)} &nbsp;&nbsp;&nbsp;<strong>{$email->language->addToStack("r_severity", FALSE)}:</strong> {$email->language->addToStack("nexus_severity_".$request->severity->_id, FALSE)}
				<br /><br />
			</td>
		</tr>
	{{endforeach}}
</table>
<br />
<br />
<em style='color: #8c8c8c'>&mdash; {setting="board_name"}</em>