<ips:template parameters="$form" />
<div class="ipsPad">
	<a href="{url="app=nexus&module=support&controller=settings&tab=incomingemail&type="}" data-role="toggleView">&larr; {lang="ie_back"}</a>
	<br><br>
	<h2 class="ipsType_sectionHead">{lang="ie_pop3"}</h2>
	<br>
	<ol>
		<li>
			<p>{lang="ie_pop3_details"}</p>
			<br>
			{$form|raw}
		</li>
		{{if !settings.task_use_cron}}
			<li>
				<p>{lang="ie_pop3_cron"}</p>
			</li>
		{{endif}}
		<li>
			{lang="ie_test"} {lang="ie_test_pop3"} 
		</li>
	</ol>
</div>