<ips:template parameters="" />
<div class="ipsPad">
	<a href="{url="app=nexus&module=support&controller=settings&tab=incomingemail&type="}" data-role="toggleView">&larr; {lang="ie_back"}</a>
	<br><br>
	<h2 class="ipsType_sectionHead">{lang="ie_sendgrid"}</h2>
	<p>{lang="ie_sendgrid_intro"}</p>
	<ol>
		<li><p>{lang="ie_sendgrid_1"}</p></li>
		<li>
			<p>{lang="ie_sendgrid_2"}</p>
			<pre>{url="applications/core/interface/incomingemail/sendgrid.php" base="interface"}</pre>
		</li>
		<li><p>{lang="ie_test"}</p></li>
	</ol>
</div>