<?php

$lang = array(
	'__app_downloads'				=> "Downloads",
	'frontnavigation_downloads'		=> "Downloads",
	'__indefart_downloads_file_comment'		=> "a comment on a file",
	'__indefart_downloads_file'				=> "a file",
	'__indefart_downloads_file_review'		=> "a review on a file",
	'__indefart_downloads_file_pending'		=> "a new version",
	'__defart_downloads_file_comment'		=> "comment on a file",
	'__defart_downloads_file'				=> "file",
	'__defart_downloads_file_review'		=> "review on a file",
	'menu__downloads_downloads'		=> "Downloads",
	'module__downloads_downloads'	=> "Downloads",
	'menu__downloads_stats'			=> "Downloads",
	'module__downloads_stats'		=> "Statistics",
	'file_download'					=> "File Download",
	'downloads_file_container'		=> "category",
	'search_contextual_item_downloads_categories'	=> "This Category",
	'search_contextual_item_downloads_file'	=> "This File",
	'downloads_categories'				=> "Downloads Categories",
	
	'filestorage__downloads_Files'			=> "Downloads Files",
	'filestorage__downloads_Screenshots'	=> "Downloads Screenshots",
	'filestorage__downloads_FileField'		=> "Downloads Custom Fields",
	'downloads_files'						=> "Downloads Files",
	'downloads_file'						=> "Downloads File",

	'modlog__action_restorebackup'			=> "Restored a previous version for a file: <a href='%s'>%s</a>",
	'modlog__action_visibilitybackup'		=> "Toggled visibility for a previous version for a file: <a href='%s'>%s</a>",
	'modlog__action_deletebackup'			=> "Deleted a previous version for a file: <a href='%s'>%s</a>",
	'modlog__action_purchasestatus' 		=> "Toggled purchase status for a file: <a href='%s'>%s</a>",
	'modlog__action_newversion_reject'		=> "Rejected a new version for a file: <a href='%s'>%s</a>",
	'modlog__action_newversion_approved'	=> "Approved a new version for a file: <a href='%s'>%s</a>",

	'mark_category_read'					=> "Mark category read",
	'mark_category_read_title'				=> "Mark this category as read",

	'editor__downloads_Categories'			=> "Download Categories",
	'editor__downloads_Downloads'			=> "File Downloads",
	'editorMedia_downloads_Files'			=> "File Downloads",
	'downloads_rebuilding_screenshots'		=> "Rebuilding Screenshot Watermarks",
	
	'member_restrictions__downloads_Downloads' => "Downloads",
	'restriction_no_downloads'				=> "Restricted from submitting files",
	'content_stats__downloads_Downloads'	=> "Downloads",
	
	/* !Categories */
	'menu__downloads_downloads_categories'	=> "Categories",
	'subcategories'							=> "Subcategories",
	'cname'									=> "Name",
	'cbitoptions_disfiles'					=> "Allow files?",
	'cbitoptions_disfiles_desc'				=> "You may want to disable to use this category as a container for other subcategories.",
	'ctypes'								=> "Allowed file extensions",
	'cparent'								=> "Parent Category",
	'any_extensions'						=> "any extensions",
	'cmaxfile'								=> "Maximum file size",
	'ccfields'								=> "Extra fields",
	'category_screenshots'					=> "Screenshots",
	'cbitoptions_allowss'					=> "Allow screenshots?",
	'cbitoptions_allowss_desc'				=> "Images can be submitted with files to provide screenshots or other accompanying images to show in the file listing.",
	'cbitoptions_reqss'						=> "Require screenshots?",
	'cmaxss'								=> "Maximum screenshot filesize",
	'cmaxdims'								=> "Maximum screenshot dimensions",
	'category_display'						=> "Category Display",
	'csortorder'							=> "Default sort order",
	'cbitoptions_comments'					=> "Allow comments?",
	'cbitoptions_reviews'					=> "Allow reviews?",
	'cbitoptions_reviews_mod'				=> "Reviews must be approved?",
	'cbitoptions_reviews_download'			=> "Users must download before reviewing?",
	'cbitoptions_reviews_download_desc'		=> "Requires download log to be on.",
	'cdisclaimer'							=> "Download Terms",
	'cdisclaimer_placeholder'				=> "Before downloading you must agree to the following terms...",
	'category_errors'						=> "Error Messages",
	'category_errors_blurb'					=> "You can define specific error messages to use within this category. If not provided, a generic error message will be used.",
	'noperm_view'							=> "Cannot view files",
	'noperm_view_placeholder'				=> "Add an error message...",
	'noperm_dl'								=> "Cannot download",
	'noperm_dl_placeholder'					=> "Add an error message...",
	'perm_file_perm__label'					=> "",		
	'perm_file_perm__view'					=> "See Category",
	'perm_file_perm__read'					=> "View Files",
	'perm_file_perm__add'					=> "Upload Files",
	'perm_file_perm__download'				=> "Download Files",
	'perm_file_perm__comment'				=> "Comment",
	'perm_file_perm__rate'					=> "Rate Files",
	'perm_file_perm__reply'					=> "Comment",
	'perm_file_perm__review'				=> "Review Files",
	'cbitoptions_moderation'				=> "Files must be approved?",
	'cbitoptions_moderation_edits'			=> "New versions must be approved?",
	'cbitoptions_show_approver'				=> "Show who approved the file?",
	'cbitoptions_show_approver_desc'		=> "Other staff members are always able to see this information.",
	'cbitoptions_comment_moderation'		=> "Comments must be approved?",
	'cversion_numbers'						=> "Version Numbers",
	'version_numbers_disabled'				=> "Disabled",
	'version_numbers_enabled'				=> "Available",
	'version_numbers_required'				=> "Required",
	'cversioning_on'						=> "Keep previous versions?",
	'cversioning_on_desc'					=> "If enabled, when a new version of a file is uploaded, the previous version is stored and remains available.",
	'cversioning'							=> "Number of revisions to keep",
	'category_moderation'					=> "Moderation",
	'category_downloading'					=> "Downloading",
	'category_comments_and_reviews'			=> "Comments",
	'category_logs'							=> "Logs",
	'clog_on'								=> "Log downloads?",
	'clog'									=> "Keep logs for",
	'clog_recount'							=> "Recalculate Download Counts",
	'clog_recount_desc'						=> "This will reset the number of downloads for each file in this category to the number of records currently in the log. If you have updated the log settings, you will need to save them before running this tool. This action is irreversible.",
	'clog_recount_done'						=> "Counts Recalculated",
	'r__categories_recount_downloads'		=> "Can recalculate download counts?",
	'cbitoptions_submitter_log'				=> "Allow file submitter to view log?",
	'cbitoptions_submitter_log_desc'		=> "You can also control which members can view the log from the group settings.",
	'category_submissions'					=> "Submissions",
	'category_allowed_files'				=> "Allowed Files",
	'category_versioning'					=> "Versioning",
	'csubmissionterms'						=> "Submission Terms",
	'csubmissionterms_placeholder'			=> "By submitting a file you agree to the following terms:",
	'file_cat'								=> "Category",
	'file_ipaddress'						=> "IP Address",
	'log_days'								=> "The log is pruned after {# [1:day][?:days]}",
	'category_forums_integration'			=> "Forum Topics",
	'cforum_on'								=> "Post a topic when a file is submitted?",
	'cforum_id'								=> "Forum",
	'ctopic_prefix'							=> "Topic prefix",
	'ctopic_suffix'							=> "Topic suffix",
	'cbitoptions_topic_delete'				=> "Delete topic if file is deleted?",
	'cbitoptions_topic_screenshot'			=> "Include screenshot in topic?",
	'node_no_parentd'						=> "No Parent",
	'view_all_files'						=> "View All Files",
	'downloadcategory_topic_rebuild'		=> "<a href='%s' data-confirm data-confirmMessage='Rebuild Topics' data-confirmSubMessage='This will edit the first post of all topics created by files in this category to match the current settings. This may be useful if you have changed some settings. Any files which do not already have a topic will also have one generated.The rebuild will be processed in the background and you will be able to see the progress on the AdminCP Dashboard.'>Rebuild topic content</a>",
	'cmultiple_files'						=> "Allow Multiple Files",
	'cmultiple_files_desc'					=> "If enabled, the file author can upload multiple files at once when creating/updating a file record.",
	'cdisclaimer_location'					=> "Show Download Terms",
	'cdisclaimer_purchase'					=> "Before Purchase",
	'cdisclaimer_download'					=> "Before Download",
	'cdisclaimer_both'						=> "Before Purchase and Download",


	/* !Moderation */
	'modperms__core_Content_downloads_File'	=> "Downloads",
	'download_categories'					=> "Categories",
	'can_pin_downloads_file'				=> "Can pin files?",
	'can_unpin_downloads_file'				=> "Can unpin files?",
	'can_feature_downloads_file'			=> "Can feature files?",
	'can_unfeature_downloads_file'			=> "Can unfeature files?",
	'can_move_downloads_file'				=> "Can move files?",
	'can_move_downloads_file_desc'			=> "Will be able to move files only between the categories they can create new content within.",
	'can_lock_downloads_file'				=> "Can lock files?",
	'can_unlock_downloads_file'				=> "Can unlock files?",
	'can_reply_to_locked_downloads_file'	=> "Can comment on locked files?",
	'can_edit_downloads_file'				=> "Can edit files?",
	'can_hide_downloads_file'				=> "Can hide files?",
	'can_unhide_downloads_file'				=> "Can unhide files?",
	'can_view_hidden_downloads_file'		=> "Can view hidden files?",
	'can_delete_downloads_file'				=> "Can delete files?",
	'can_edit_downloads_file_comment'				=> "Can edit comments?",
	'can_hide_downloads_file_comment'				=> "Can hide comments?",
	'can_unhide_downloads_file_comment'				=> "Can unhide comments?",
	'can_view_hidden_downloads_file_comment'		=> "Can view hidden comments?",
	'can_delete_downloads_file_comment'				=> "Can delete comments?",
	'can_edit_downloads_file_review'				=> "Can edit reviews?",
	'can_hide_downloads_file_review'				=> "Can hide reviews?",
	'can_unhide_downloads_file_review'				=> "Can unhide reviews?",
	'can_view_hidden_downloads_file_review'		=> "Can view hidden reviews?",
	'can_delete_downloads_file_review'				=> "Can delete reviews?",
	'can_feature_comments_downloads_file'				=> "Can recommend comments on a file?",
	'can_unfeature_comments_downloads_file'			=> "Can remove comment recommendations on a file?",
	'can_add_item_message_downloads_file'				=> "Can add messages to files?",
	'can_edit_item_message_downloads_file'			=> "Can edit messages on files?",
	'can_delete_item_message_downloads_file'			=> "Can delete messages on files?",
	
	/* !Moderator Permissions */
	'modperms__downloads_Files'				=> "Downloads",
	'can_make_purchasable'					=> "Can enable purchases on files?",
	'can_make_unpurchasable'				=> "Can disable purchases on files?",
	
	/* !Fields */
	'menu__downloads_downloads_fields'		=> "Extra Fields",
	'cf_topic'								=> "Include field in topics?",
	'cf_format_desc'						=> "Example: &lt;strong&gt;{title}:&lt;/strong&gt; {content}",
	'downloads_field_location'				=> "Display Location",
	'idm_cfield_below'						=> "Below the description",
	'idm_cfield_tab'						=> "In a separate tab",
	'idm_cfield_sidebar'					=> "In the sidebar",
	'downloads_field_paid'					=> "Purchase Required?",
	'downloads_field_paid_desc'				=> "If enabled, this field's contents will only be shown to members's who have purchased the file. This setting has no effect on free files.",
	
	/* !Settings */
	'menu__downloads_downloads_settings'	=> "Settings",
	'acplogs__downloads_settings'			=> "Updated downloads settings",
	'group__downloads_Downloads'			=> "Downloads",
	'idm_rss'								=> "Enable Latest Files RSS feed?",
	'idm_link_blacklist'					=> "URL Submissions Blacklist",
	'idm_link_blacklist_desc'				=> "Users that are allowed to make URL submissions will not be able to use URLs from the specified domains.",
	'idm_antileech'							=> "Prevent direct linking?",
	'idm_antileech_desc'					=> "If enabled, users will not be able to obtain a URL which directly downloads a file; users will always have to go through the file's page.",
	'idm_watermarkpath'						=> "Screenshot watermark",
	'idm_watermarkpath_desc'				=> "The image provided will be overlaid on all screenshot images (for example, to show a copyright message). For best results, use a small image with a transparent background.",
	'acplogs__downloads_recount_downloads'	=> "Recounted downloads for category: %s",
	'download_settings_saved_rebuilding'	=> "Saved. Your screenshots are rebuilding in the background.",

	/* !Group Settings */
	'idm_view_approvers'					=> "Can view who approved files?",
	'idm_bypass_revision'					=> "Can manage versions?",
	'idm_view_downloads'					=> "Can view who has downloaded files?",
	'idm_view_downloads_desc'				=> "Note that the download log can be disabled per-category and cleared periodically.",
	'idm_throttling'						=> "Maximum Download Speed",
	'idm_max_size'							=> "Maximum submission size",
	'idm_max_size_desc'						=> "Categories can have maximum submission size restrictions as well. Regular submissions will be limited to the lower of the group maximum submission size or the category maximum submission size, while club submissions will be limited to this value.",
	'idm_maxsize_suffix'					=> "kB",
	'idm_throttling_suffix'					=> "kB/second",
	'idm_throttling_desc'					=> "This will <em>throttle</em> downloads to the maximum speed set. If set too low, this may cause your server to time out and the download to fail.",
	'idm_throttling_unlimited'				=> "No restriction",
	'idm_wait_period'						=> "Time user must wait before download starts",
	'idm_bypass_revision_desc'				=> "When an author uploads a new version of a file within a category that has versioning enabled, the previous version is stored and is available for download. When this setting is enabled, the user will be given the option to not store the previous version when uploading a new version, and will be able to restore, hide and delete their previous versions.<br>The user needs permission to edit the file.",
	'limit_sim'								=> "Maximum simultaneous downloads",
	'min_posts'								=> "Posts required to download",
	'download_min_posts'					=> "You may only download files after you have made {# [1:post][?:posts]}.",
	'daily_bw'								=> "Maximum bandwidth usage per day",
	'weekly_bw'								=> "Maximum bandwidth usage per week",
	'monthly_bw'							=> "Maximum bandwidth usage per month",
	'kb_per_day'							=> "kB/day",
	'kb_per_week'							=> "kB/week",
	'kb_per_month'							=> "kB/month",
	'daily_dl'								=> "Maximum downloads per day",
	'weekly_dl'								=> "Maximum downloads per week",
	'monthly_dl'							=> "Maximum downloads per month",
	'downloads_requires_log'				=> "These settings rely on the download log which can be disabled per-category and cleared periodically. If using these settings, it is recommended that you leave the log turned on and set not to clear otherwise you may experience unexpected behavior.",
	'file_management'						=> "File Management",
	'download_restrictions'					=> "Download Restrictions",
	'bandwidth_limits'						=> "Bandwidth Limits",
	'download_limits'						=> "Download Limits",
	'downloads_per_day'						=> "downloads/day",
	'downloads_per_week'					=> "downloads/week",
	'downloads_per_month'					=> "downloads/month",
	'submission_permissions'				=> "Submission Permissions",
	'idm_linked_files'						=> "Can submit URLs?",
	'idm_import_files'						=> "Can import files from the filesystem?",
	'idm_import_files_desc'					=> "When enabled, users will be able to import files located on your server. You should only enable this for staff groups where all the users are trusted.",
	'idm_bulk_submit'						=> "Can submit multiple Downloads Files at once?",
	'idm_paid_restrictions'					=> "Restrictions apply to purchased files?",
	'idm_paid_restrictions_desc'				=> "If enabled, any restrictions set below will also apply to files purchased by the user.",
	
	/* !Front-end */
	'idm_screenshot_for'					=> "Screenshot for %s",
	'rss_offline'							=> "This RSS feed is disabled",
	'rss_offline_admin'						=> "The IP.Downloads option \"Enable Latest Files RSS feed\" is currently disabled. Toggle this option to yes in the admin control panel to enable the latest files RSS feed.",
	'submit_a_file'							=> "Submit a file",
	'submit_single_file'					=> "Submit single file",
	'submit_multiple_files'					=> "Submit multiple files",
	'submit_first_file'						=> "Submit the first file",
	'write_review'							=> "Write a review",
	'file_auto_follow'						=> "",
	'file_auto_follow_suffix'				=> "Follow this file",
	'file'									=> "File",
	'dl_get_support'							=> "Get Support",
	'dl_get_support_title'						=> "Get support for this download",
	'file_information'						=> "File Information",
	'url_files'								=> "Linked Files",
	'url_files_no_perm'						=> "This file has a linked file, but you are no longer permitted to edit it. Please contact an administrator if you need to change it.",
	'import_files'							=> "Import Files",
	'screenshots'							=> "Screenshots",	// This used to be "%d Screenshots" but then the submission form shows this verbatim since 'screenshots' is the field key
	'screenshots_ct'						=> "{# [1:Screenshot][?:Screenshots]}",
	'url_screenshots'						=> "Linked Screenshots",
	'file_title'							=> "File Name",
	'file_submitter'						=> "Submitter",
	'file_submitted'						=> "Submitted",
	'view_file'								=> "View File",
	'version'								=> "Version",
	'file_version'							=> "Version number",
	'file_tags'								=> "Tags",
	'file_changelog'						=> "What's New",
	'new_version_details'					=> "New Version Details",
	'with_version'							=> "With version %s:",
	'file_desc'								=> "About This File",
	'file_primary_screenshot'				=> "Primary Screenshot",
	'file_primary_screenshot_desc'			=> "The primary screenshot is used in category listings.",
	'download_now'							=> "Download this file",
	'file_view_details'						=> "View file",
	'downloads'								=> "Downloads",
	'x_downloads'							=> "{# [1:download][?:downloads]}",
	'idm_purchases'							=> "Purchases",
	'x_purchases'							=> "{# [1:purchase][?:purchases]}",
	'num_downloads'							=> "{# [1:download][?:downloads]}",
	'files_no_number'						=> "{!# [1:file][?:files]}",
	'downloads_file'						=> "File",
	'downloads_file_comment'				=> "File Comment",
	'downloads_file_review'					=> "File Review",
	'downloads_file_pl'						=> "Files",
	'downloads_file_pl_lc'					=> "files",
	'downloads_file_comment_pl'				=> "File Comments",
	'downloads_file_comment_pl_lc'			=> "file comments",
	'downloads_file_review_pl'				=> "File Reviews",
	'downloads_file_review_pl_lc'			=> "file reviews",
	'downloads_file_pending'				=> "New Version",
	'downloads_file_pending_pl'				=> "New File Versions",
	'downloads_file_pending_pl_lc'			=> "new file versions",
	'downloads_category_select'				=> "Category:",
	'report_file'							=> "Report this file",
	'file_review_count'						=> "{# [1:Review][?:Reviews]}",
	'file_comment_count'					=> "{# [1:Comment][?:Comments]}",
	'subcategory'							=> "Sub Category",
	'download_no_perm'						=> "You are not allowed to download that file.",
	'add_files_no_perm'						=> "You are not allowed to upload files to this category.",
	'new_version_versioning'				=> "The previous version will be archived and users will still be able to download it.",
	'file_save_revision'					=> "Save Previous Version?",
	'downloads_edit_details'				=> "Edit Details",
	'downloads_edit_details_title'			=> "Edit this file's details",
	'file__comment_placeholder'				=> "Add a comment...",
	'file_submit_comment'					=> "Submit Comment",
	'whats_new_in_version'					=> "What's New in Version <span data-role='versionTitle'>%s</span>",
	'see_changelog'							=> "See changelog",
	'see_changelog_for'						=> "See changelog for version %s",
	'see_changelog_title'					=> "See the version history for this file",
	'view_downloader_list' 					=> "View list of downloaders",
	'who_downloaded'						=> "Who downloaded this?",
	'downloaders'							=> "Downloaders",
	'download_your_files'					=> "Download your files",
	'download_terms'						=> "Download Terms",
	'download_terms_desc'					=> "Your file is ready for download. Before downloading, you must agree to the following terms:",
	'download_file_count'					=>  "{# [1:file][?:files]}",
	'agree_and_download'					=> "Agree &amp; Download",
	'cancel_downloading'					=> "Cancel download",
	'agree_and_download_full'				=> "Agree to the terms above and download file",
	'download_version'						=> "Download",
	'restore_version'						=> "Restore",
	'delete_version'						=> "Delete",
	'download_purchase_terms'				=> "Terms & Conditions",
	'download_purchase_terms_desc'			=> "Before purchasing, you must agree to the following terms:",
	'agree_and_purchase'					=> "Agree &amp; Purchase",
	'hide_version'							=> "Hide from members",
	'filesize'								=> "File Size",
	'file_pending_approval'					=> "This file is not yet approved and is only visible to staff.",
	'file_pending_approval_version'			=> "A new version of this file is waiting for approval.",
	'file_pending_version_button'			=> "Review New Version",
	'file_approved_by'						=> "(approved by %s, %s)",
	'file_requires_approval_g'				=> "The file you submitted must be approved by a staff member before it will be visible",
	'file_no_changelog'						=> "No changelog available for this version.",
	'file_version_released'					=> "Released %s",
	'restore'								=> "Restore",
	'hide_from_members'						=> "Hide from members",
	'unhide_from_members'					=> "Unhide from members",
	'version_restore_confirm'				=> "Are you sure you want to restore this version?",
	'version_restore_confirm_desc'			=> 'All versions since %1$s will be deleted and the file will be restored to the state it was at version %1$s.',
	'version_delete_confirm'				=> "Are you sure you want to delete this version?",
	'idm_rss_title'							=> "Latest Files",
	'wait_x_seconds_noscript'				=> "Wait {# [1:second][?:seconds]}, then click Download again",
	'download_begins_in'					=> "Download begins in ",
	'file_actions'							=> "File Actions",
	'max_simultaneous_downloads'			=> "You may only download {# [1:file][?:files]} at a time. Wait until {!# [1:your other download has][?:some of your other downloads have]} finished, then try again.",
	'download_min_posts'					=> "You may only download files after you have made {# [1:post][?:posts]}.",
	'bandwidth_limit_daily'					=> "You may only download %s per day. You will be able to download this file after %s.",
	'bandwidth_limit_week'					=> "You may only download %s per week. You will be able to download this file after %s.",
	'bandwidth_limit_month'					=> "You may only download %s per month. You will be able to download this file after %s.",
	'bandwidth_limit_daily_never'			=> "You may only download %s per day. The file you are trying to download is %s which is above your limit.",
	'bandwidth_limit_weekly'				=> "You may only download %s per week. The file you are trying to download is %s which is above your limit.",
	'bandwidth_limit_month'					=> "You may only download %s per month. The file you are trying to download is %s which is above your limit.",
	'download_limit_daily'					=> "You may only download {# [1:file][?:files]} per day. You will be able to download this file after %s.",
	'download_limit_weekly'					=> "You may only download {# [1:file][?:files]} per week. You will be able to download this file after %s.",
	'download_limit_monthly'				=> "You may only download {# [1:file][?:files]} per month. You will be able to download this file after %s.",
	'file_rating_value'						=> "Your rating",
	'file_review_text'						=> "Your review",
	'file__review_placeholder'				=> "Add a review...",
	'err_no_files'							=> "You must upload or link to at least one file.",
	'err_too_many_files'					=> "You can only upload or link to a maximum of one file.",
	'err_no_screenshots'					=> "You must upload or link to at least one screenshot.",
	'err_url_file_blacklist'				=> "URLs from %s are not allowed.",
	'err_import_files'						=> "The file %s does not exist or is not readable.",
	'err_import_files_dir'					=> "%s is a directory. You must specify the path to a file.",
	'change_author_d'						=> "Change Author",
	'change_author_title'					=> "Change the member who owns this file",
	'err_submissions_blocked'				=> "You have been blocked from submitting files.",
	'upload_new_version_title'				=> "Upload a new version of this file",
	'upload_new_version_pending'			=> "New version is pending approval",
	'feature_title_file'					=> "Feature this file",
	'unfeature_title_file'					=> "Unfeature this file",
	'pin_title_file'						=> "Pin this file",
	'unpin_title_file'						=> "Unpin this file",
	'hide_title_file'						=> "Hide this file",
	'unhide_title_file'						=> "Unhide this file",
	'approve_title_file'					=> "Approve this file",
	'lock_title_file'						=> "Lock this file",
	'unlock_title_file'						=> "Unlock this file",
	'downloads_move_title'					=> "Move this file to another category",
	'downloads_delete_title'				=> "Delete this file from the community",
	'find_users_files'						=> "Find their other files",
	'file_versioning_info'					=> '',
	'file_versioning_info_text'				=> "Click here if you would like to upload a new version of the file or screenshot",
	'browse_whats_new'						=> "What's New",
	'browse_highest_rated'					=> "Highest Rated",
	'browse_most_downloaded'				=> "Most Downloaded",
	'no_new_files'							=> "There have been no uploaded files yet.",
	'no_rated_files'						=> "No files have been rated yet.",
	'no_downloaded_files__week'				=> "No files have been downloaded yet this week.",
	'no_downloaded_files__month'			=> "No files have been downloaded yet this month.",
	'no_downloaded_files__year'				=> "No files have been downloaded yet this year.",
	'no_downloaded_files'					=> "No files have been downloaded yet.",
	'no_download_review'					=> "You may only provide a review once you have downloaded the file.",
	'index_discover'						=> "Discover",
	'index_explore'							=> "Explore Categories",
	'browse_categories_d'					=> "Browse Categories",
	'no_files_in_cat'						=> "No files in this category yet.",
	'submit_form_title'						=> "Adding New File",
	'submit_form_title_bulk'				=> "Adding New Files",
	'submit_form_desc'						=> "Adding a file to <em>%s</em>",
	'submit_form_desc_bulk'					=> "Adding files to <em>%s</em>",
	'select_your_files'						=> "Select your files",
	'select_your_file'						=> "Select your file",
	'add_files_by_url'						=> "Add files by URL",
	'add_files_by_path'						=> "Add files from server path",
	'submit_menu_confirm'					=> "Confirm",
	'add_screenshots'						=> "Add screenshots",
	'add_screenshots_by_url'				=> "Add screenshots by URL",
	'submit_file_information'				=> "File Information",
	'save_and_submit_files'					=> "Save &amp; Submit Files",
	'save_and_submit_file'					=> "Save &amp; Submit File",
	'save_and_submit_new_version'			=> "Save &amp; Submit New Version",
	'submit_bulk_information'				=> "Enter File Information",
	'bulk_upload_button'					=> "I want to add multiple records at once",
	'upload_more_files'						=> "Upload more files",
	'downloads_single_upload'				=> "This category allows a single file upload. To upload a new file, delete the existing file then upload the new file.",
	'featured_downloads'					=> "Featured Downloads",
	'next_file'								=> "Next File",
	'prev_file'								=> "Previous File",
	'downloads_category_id'					=> "Category",
	'announce_download_categories'			=> "Categories",
	'view_this_file'						=> "View the file %s",
	'file_locked_can_comment'				=> "This file is locked, but your permissions allow you to add new comments.",
	'file_locked_cannot_comment'			=> "This file is now closed to further comments.",
	'file__save'							=> "Save",
    'downloads_no_file'                     => "File not found",
	'download_teaser'						=> "Create an account or sign in to download this",
	'download_no_permission'				=> "Sorry, you aren't permitted to download this file.",
	'download_no_permission_guest'			=> "Sorry, you aren't permitted to download this file. However, you may be able to download if you sign in.",
	'downloads_file_info'					=> "Downloads",
	'sort_file_downloads'					=> "Most Downloaded",
	'club_node_downloads'					=> "Club Files",
	'file_imported_removed'					=> "The files have been imported and the original copies can now be removed from disk, if desired.",
	'disable_purchases'						=> "Disable Purchases",
	'enable_purchases'						=> "Enable Purchases",
	'purchasing_disabled'					=> "This file is not currently available for purchase.",

	/* !ACP Dashboard Widgets */
	'block_downloads_Overview'				=> "Downloads Overview",
	'total_disk_spaced'						=> "Total Diskspace Used",
	'total_files'							=> "Total Files",
	'total_downloads'						=> "Total Downloads *",
	'total_bandwidth'						=> "Total Bandwidth Used *",
	'current_month_bandwidth'				=> "Bandwidth Used This Month *",
	'largest_file'							=> "Largest File",
	'most_viewed_file'						=> "Most Viewed File",
	'most_downloaded_file'					=> "Most Downloaded File",
	
	/* !Sidebar */
	'total_files_front'						=> "Files",
	'total_authors'							=> "Authors",
	'latest_file'							=> "Latest File",
	'latest_submitter'						=> "Latest Submitter",
	'top_week'								=> "Week",
	'top_month'								=> "Month",
	'top_year'								=> "Year",
	'top_alltime'							=> "All",
	'top_avg_rating'						=> "Average file rating",
	'top_submitters_empty__week'			=> "No ratings this week.",
	'top_submitters_empty__month'			=> "No ratings this month.",
	'top_submitters_empty__year'			=> "No ratings this year.",
	'top_submitters_empty__all'				=> "No ratings.",
	
	/* !Member Form */
	'member__downloads_Downloads'			=> "Downloads",
	'idm_block_submissions'					=> "Allowed to submit files?",
	'idm_block_submissions_desc'			=> "Each category has permissions for who can submit files within it. If this is disabled, the user will not be able to submit any files. If enabled, per-category settings will be honored.",
	'history_restrictions_downloads_1'		=> "disabled ability to submit files",
	'history_restrictions_downloads_0'		=> "restored ability to submit files",
	'downloads_stats'						=> "View Downloads Statistics",
	'submissions'							=> "{# [1:submission][?:submissions]}",
	
	/* !Stats */
	'deleted_file'							=> "Deleted File",
	'dmid'									=> "Member",
	'dfid'									=> "File",
	'dtime'									=> "Date/Time",
	'dsize'									=> "Filesize",
	'dua'									=> "Browser",
	'dip'									=> "IP Address",
	'member_downloads_chart'				=> "%s's Downloads",
	'bandwidth_use'							=> "Bandwidth Use",
	'files_submitted'						=> "Files Submitted",
	'diskspace_used'						=> "Diskspace Used",
	'average_filesize_downloads'			=> "Average Filesize",
	'number_of_downloads'					=> "Number of Downloads *",
	'downloads_bandwidth_used'				=> "Bandwidth Used *",
	'downloads_stat_of_total'				=> "%s (%d%% of total)",
	'downloads_stat_of_total_link'			=> "%s (%d%% of total) %s",
	'downloads_stat_average'				=> "%s (average for all users: %s)",
	'downloadS_stat_average_of_total'		=> "%d% of total; average for all users: %d",
	'download_stats_disclaimer'				=> "* This statistic comes from the download log which may be disabled on a per-category basis or set to be pruned periodically.",
	'download_graph_disclaimer'				=> "This data comes from the download log which may be disabled on a per-category basis or set to be pruned periodically.",
	'menu__downloads_stats_downloads'		=> "Downloads",
	'menu__downloads_stats_downloaders'		=> "Top Downloaders",
	'menu__downloads_stats_submitters'		=> "Top Submitters",
	'r__downloads'							=> "Download Statistics",
	'r__downloads_manage'					=> "Can view Download Statistics?",
	'r__downloaders_manage'					=> "Can view Top Downloaders?",
	'r__submitters_manage'					=> "Can view Top Submitters?",
	'stats_overview_downloads'				=> "File Downloads",
	'stats_overview_downloads_desc'			=> "Logging of downloads and the retention period for logs can be adjusted on a per-category basis",
	
	/* !ACP Log */
	'ipAddresses__downloads_DownloadLog'	=> "Downloads",
	
	/* !Sidebar */
	'block_fileFeed'					=> "Files Feed",
	'block_fileFeed_desc'				=> "Create a feed of files",
	'widget_feed_container_downloads_file'	=> "Categories",
	'block_topSubmitters'				=> "Highest Rated Submitters",
	'block_topSubmitters_desc'			=> "Shows top submitters by file rating",
	'block_downloadStats'				=> "Download Statistics",
	'block_downloadStats_desc'			=> "Shows download application statistics",
	'block_topDownloads'				=> "Top Downloads",
	'block_topDownloads_desc'			=> "Shows most popular downloaded files",
	'block_recentFiles'					=> "Recent Files",
	'block_recentFiles_desc'			=> "Shows recent files",

		
	/* !Online Users */
	'loc_downloads_viewing_file'		=> "Viewing File: %s",
	'loc_downloads_viewing_category'	=> "Viewing Category: %s",
	'loc_downloads_browsing_categories'	=> "Browsing Downloads categories",
	'loc_downloads_adding_file'			=> "Adding a file",
	'loc_downloads_browsing'			=> "Viewing Downloads",
	'loc_downloads_viewing_file_action'	=> "%s is viewing a file",
	'loc_downloads_viewing_category_action'	=> "%s is browsing downloads",
	'loc_downloads_browsing_categories_action' => "%s is browsing downloads",
	'loc_downloads_adding_file_action'	=> "%s is adding a file",
	'loc_downloads_browsing_action'		=> "%s is browsing downloads",
		
	/* !Live Search */
	'acp_search_title_downloads_Downloads'	=> "Downloads Categories",
	'downloads_categories_pagetitle'		=> "Downloads Categories",
	
	/* !Tasks */
	'task__logCleanup'						=> "Prunes the download log.",
	'task__tempFileCleanup'					=> "Removes temporary file uploads.",

	/* !Digests */
	'digest_area_downloads_category'		=> "Files",
	'digest_area_downloads_file'			=> "File",

	'x_created_file_in'			=> "%s uploaded a file to %s",
	'x_commented_file'				=> "%s commented on a file",
	'x_reviewed_file'				=> "%s reviewed a file",
	
	/* !Nexus Integration */
	'paid_file_settings'		=> "Paid Files Settings",
	'idm_nexus_on'				=> "Enable Paid Files?",
	'idm_nexus_on_desc'			=> "If enabled, users who have permission will be able to submit files which must be paid for in order to download.<br>You can control which groups can submit paid files from the <a href='{internal.app=core&module=members&controller=groups}'>Groups</a> page.<br>When someone purchases a paid file, the money will be added to the file submitter's account credit. You can control how users can withdraw account credit from the <a href='{internal.app=nexus&module=payments&controller=payouts&do=settings}'>Withdrawals</a> page.",
	'idm_nexus_tax'				=> "Tax Class for Paid Files",
	'idm_nexus_percent'			=> "Commission for Site",
	'idm_nexus_percent_desc'	=> 'The percentage specified will be deducted from the amount given to the file submitter. For example, if you set this to 10% and someone buys a file for $10, the submitter will be given $9 and $1 will be kept for the site.',
	'idm_nexus_transfee'		=> "Transaction Fee for Site",
	'idm_nexus_transfee_desc'	=> 'The amount specified will be deducted from the amount given to the file submitter. For example, if you set this to $1 and someone buys a file for $10, the submitter will be given $9 and $1 will be kept for the site.',
	'idm_nexus_mincost'			=> 'Minimum Cost',
	'idm_nexus_mincost_desc'	=> 'The minimum cost for paid files. Does not apply to free files.',
	'idm_nexus_gateways'		=> "Payment Methods",
	'idm_nexus_display'			=> "Statistics to Display",
	'idm_nexus_display_desc'	=> "Unpaid files will always show the number of downloads.",
	'idm_nexus_gateways_desc'	=> "Customers will only be able to pay for this product and renewals with the payment methods selected.",
	'idm_add_paid'				=> "Can charge for files?",
	'idm_add_paid_enable'		=> "In order to allow users to charge for files you must <a href='{internal.app=downloads&module=downloads&controller=settings}'>enable paid files</a>.",
	'idm_bypass_paid'			=> "Can download paid files without paying?",
	'file_cost_type'			=> "Type",
	'file_free'					=> "Free",
	'file_free_feed'			=> "Free",
	'file_paid'					=> "Paid",
	'file_associate_nexus'		=> "Associate with product(s)",
	'file_associate_nexus_desc'	=> "Users who have an active purchase of one of the selected products will be able to download this file.",
	'file_cost'					=> "Price",
	'file_renewals'				=> "Renewals",
	'file_renewals_off'			=> "No renewals - once a user has purchased this file they will be able to download all future versions.",
	'file_renewals_on'			=> "I will specify renewal terms. Users must have paid the renewal fee in order to download the current version.",
	'file_renewal_term'			=> "Renewal Term",
	'file_renewal_term_desc'	=> "Once the file is saved, renewal terms cannot be edited.",
	'file_nexus'				=> "Associated Products",
	'file_not_purchased'		=> "You have not purchased this file or your purchase has expired.",
	'buy_now'					=> "Buy Now",
	'file_cost_desc_both'		=> "%s%% commission, plus a %s transaction fee will be deducted.",
	'file_cost_desc_percent'	=> "%s%% commission will be deducted.",
	'file_cost_desc_fee'		=> "A %s transaction fee will be deducted.",
	'file_cost_desc_minimum'	=> " Minimum Cost: %s",
	'file_cost_too_low'			=> "The entered cost is less than the minimum requirement.",
	'file_renewal_term_val'		=> "Renewal Term: %s",
	'choose_file_nexus_blurb'	=> "This file is available with one of the following packages. Please add one of the following packages to your cart to continue.",
	'choose_file_nexus_title'	=> "Choose A Package",
	'file_no_price_for_currency'=> "This file is not currently available in your chosen currency.",	
	'nexus_file_no_longer_available'=> "This file is no longer available for download, please contact the file author for further information.",
	
	/* !Notifications */
	'notifications__downloads_Files'	=> "File Updates",
	'notifications__downloads_Files_desc'	=> "These notifications are sent for new versions where you have opted in to these updates.",
	'email_new_file_version_plain'		=> "%s has uploaded a new version of %s,",
	'email_new_file_version'			=> "<a href='%s'>%s</a> has uploaded a new version of %s,",
	'email_new_file_version_guest'		=> "%s (Guest) has uploaded a new version of %s,",
	'mailsub__downloads_notification_new_file_version' => '{$content->author()->name|raw} has uploaded a new version of {$content->mapped("title")|raw}',
	'notification__new_file_version'	=> "%s uploaded a new version of %s",
        'notification__new_file_version_with'	=> "%s uploaded version %s of %s",
	
	'emailtpl_notification_new_file_version'	=> "New file version notification",
	'emailstats__notification_new_file_version'	=> "New file version notification",
	'backgroundQueue_new_version'		=> "Sending new version notifications for %s",
	
	/* !Widgets */
	'block_downloadsCommentFeed'		=> "Download Comments",
	'block_downloadsCommentFeed_desc'	=> "Display a feed of comments",
	'block_downloadsReviewFeed'			=> "Download Reviews",
	'block_downloadsReviewFeed_desc'	=> "Display a feed of reviews",
	
	/* !API */
	'__api_downloads_files'			=> "Files",
	'__api_downloads_comments'		=> "Comments",
	'__api_downloads_reviews'		=> "Reviews",
	'__api_downloads_categories'	=> "Categories",

	/* Downloads Landing Page Settings */
	'idm_landing_page' => "Downloads Index Page",
	'idm_show_featured' => "Show \"Featured Downloads\" box",
	'idm_featured_count' => "Number of features files to show",
	'idm_show_newest' => "Show \"What's New\" box",
	'idm_newest_categories' => "Categories",

	'idm_show_highest_rated' => "Show \"Highest Rated\" box",
	'idm_show_most_downloaded' => "Show \"Most Downloaded\" box",
	'idm_highest_rated_categories' => "Categories",
	'idm_show_most_downloaded_categories' => "Categories",
	'downloads_forum_used' => 	 "This forum is used by the Downloads App to create topics on file submission and cannot be deleted.<br/>Please remove the association from category %s to proceed",

	/* New version updates */
	'file_subscribe'	=> "Send me version updates",
	'file_unsubscribe'	=> "Disable version updates",
	'file_subscribed'	=> "New version updates enabled",
	'file_unsubscribed'	=> "New version updates disabled",
	'file_notify_heading'	=> "New Version Updates",
	'file_notify_current'	=> "You are currently receiving these notifications by %s",
	'file_notify_none'	=> "You do not have any notification methods set up",

	/* New version pending */
	'file_version_pending_approval' => "The new version of this file is not yet approved and is only visible to staff. The previous version of the file remains visible to members.",
	'pending_no_new_files'	=> "This version does not have any updated files.",
	'pending_no_changelog'	=> "The author did not provide a change log for this version.",
	'pending_version'				=> "Pending version",
	'pending_version_reject'		=> "Reject",
	'pending_version_reject_title'	=> "Reject this version?",
	'pending_version_reject_desc'	=> "This will delete this pending version and leave the current version of the file visible",
	'file_new_version_date'			=> "New Version Submitted: %s"
);
