<ips:template parameters="$entry, $orientation='vertical'" />
<li class='ipsDataItem'>
	<div class='ipsDataItem_icon ipsPos_top'>
		{template="userPhoto" app="core" params="$entry->author(), 'tiny'" group="global"}
	</div>
	<div class='ipsDataItem_main'>
		<div class='ipsContained ipsType_break'><a href="{$entry->url('getLastComment')}" title='{lang="view_this_entry" sprintf="$entry->_title"}' class='ipsDataItem_title'>{$entry->name}</a></div>
		<div class='ipsType_blendLinks ipsType_light ipsType_break ipsContained'>{lang="byline_nodate" htmlsprintf="$entry->author()->link()"} {lang="in"} <a href='{$entry->container()->url()}' class='ipsType_blendLinks'>{$entry->container()->_title}</a></div>
		<div class='ipsMargin_top:half'>
			{{if \IPS\Settings::i()->blog_enable_rating}}
				{template="rating" group="global" location="front" app="core" params="'small', $entry->averageRating(), 5, $entry->memberRating()"} &nbsp;&nbsp;
			{{endif}}
			<span {{if !$entry->num_comments}}class='ipsType_light'{{endif}}>{number="$entry->num_comments"} {lang="blog_comments" pluralize="$entry->num_comments"}</span>
		</div>
		{{if $orientation == 'horizontal'}}
			<div class='ipsMargin_top:half ipsType_medium ipsType_richText ipsType_break' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'>
				{$entry->truncated()|raw}
			</div>
		{{endif}}
	</div>
</li>