<ips:template parameters="$entries, $title, $orientation='vertical'" />
{{if !empty( $entries ) }}
	<h3 class='ipsType_reset ipsWidget_title'>{$title}</h3>
	<div class='ipsPad_half ipsWidget_inner'>
		<ul class='ipsDataList ipsDataList_reducedSpacing'>
			{{foreach $entries as $entry}}
				{template="entryRow" group="widgets" app="blog" params="$entry, $orientation"}
			{{endforeach}}
		</ul>
	</div>
{{endif}}