<ips:template parameters="$form, $blocks, $excludedApps=array()" />
<div data-controller='core.admin.stats.overview' data-url='?app=core&module=activitystats&controller=overview&do=loadBlock'>
	<div class='ipsBox ipsBox_shadowed ipsPad ipsSpacer_bottom ipsClearfix ipsFlex ipsFlex-fw:wrap ipsFlex-jc:between ipsFlex-ai:center'>
		<ul class='ipsList_inline ipsFlex-grow:1 ipsSpacer_both ipsSpacer_half'>
			<li>
				<strong>{lang="stats_show_c"}</strong>
			</li>
			{{$apps = array();}}
			{{foreach $blocks as $blockKey => $block}}
				{{if $block->page == 'activity' AND $subBlocks = $block->getBlocks()}}
					{{foreach $subBlocks as $subBlock}}
						{{if $details = $block->getBlockDetails( $subBlock )}}
							{{if $details['app'] && !isset( $apps[ $details['app'] ] )}}
								{{$apps[ $details['app'] ] = \IPS\Application::load( $details['app'] );}}
							{{endif}}
						{{endif}}
					{{endforeach}}
				{{endif}}
			{{endforeach}}

			{{foreach \IPS\Application::applications() as $key => $app}}
				{{if isset( $apps[ $key ] )}}
					<li>
						<span class='ipsCustomInput'>
							<input type='checkbox' id='toggle_app_{$app->directory}' name='toggle_app_{$app->directory}' data-action='toggleApp' data-toggledApp='{$app->directory}' {{if !\count( $excludedApps ) || !\in_array( $app->directory, $excludedApps )}}checked{{endif}}>
							<span></span>
						</span>
						<label for='toggle_app_{$app->directory}'>{$app->_title}</label>
					</li>
				{{endif}}
			{{endforeach}}
		</ul>
		{$form|raw}
	</div>
	<div class='cStatsGrid'>
		<div class='ipsGrid ipsGrid_collapseTablet' data-ipsGrid data-ipsGrid-minItemSize='350'>
			{{foreach $blocks as $blockKey => $block}}
				{{if $block->page == 'activity' AND $subBlocks = $block->getBlocks()}}
					{{foreach $subBlocks as $subBlock}}
						{{if $details = $block->getBlockDetails( $subBlock )}}
							<div class='ipsGrid_span3 ipsBox ipsBox_shadowed cStatTile {{if \count( $excludedApps ) && \in_array( $details['app'], $excludedApps )}}ipsHide{{endif}}' data-role='statsBlock' data-refresh='{$details['refresh']}' data-block='{$blockKey}' data-subblock='{$subBlock}' data-app='{$details['app']}' data-controller='core.admin.stats.overviewBlock'{{if isset( $details['form'] ) AND $details['form'] === TRUE}} data-nodeFilter=''{{endif}}>
								<div class='cStatTile__header'>
									<h2 class='ipsType_reset cStatTile__title'>{lang="$details['title']"}</h2>
									{{if $details['description']}}
										<a href='javascript:void(0)' class='cStatTile__info' title="{lang="$details['description']"}" data-ipsTooltip>?</a>
									{{endif}}
									{{if isset( $details['form'] ) AND $details['form'] === TRUE}}
										<a href='{url="app=core&module=activitystats&controller=overview&do=loadBlockForm&blockKey={$blockKey}&subBlockKey={$subBlock}"}' data-ipsHover data-ipsHover-onClick="true" data-ipsHover-width="600" class='cStatTile__info cStatTile__form' data-role="filterForm" title="{lang="overview_stats_form"}" data-ipsTooltip id='{$blockKey}_{expression="md5($subBlock)"}'><i class='fa fa-cog'></i></a>
									{{endif}}
								</div>
								<div class='cStatTile__body ipsLoading ipsLoading_small'>
									<div class='cStatTile__bodyInner ipsType_center' data-role='statBlockContent'></div>
								</div>
							</div>
						{{endif}}
					{{endforeach}}
				{{endif}}
			{{endforeach}}
		</div>
	</div>
</div>