<ips:template parameters="$category, $createAlbumForm, $canCreateAlbum, $maximumAlbums, $existingAlbumForm" />

<div class='cGalleryChooseAlbum_wrap' data-controller='gallery.front.submit.chooseCategory'>
	<div data-role='chooseAlbumType' class='cGalleryChooseAlbum_list'>
		<ul class='ipsList_reset'>
			{{if $category->allow_albums != 2}}
				<li>
					<a href='#' class='cGalleryChooseAlbum_listItem' data-type='category'>
						<h2 class='ipsType_sectionHead'>{lang="use_no_album"}</h2>
						<p class='ipsType_reset ipsType_light ipsTruncate ipsTruncate_line'>{lang="submit_directly_to" sprintf="$category->_title"}</p>
					</a>
					<form action="{url="app=gallery&module=gallery&controller=submit&category={$category->_id}&noAlbum=1" seoTemplate="gallery_submit"}" class='ipsHide'>
						<button type="submit" class="ipsButton ipsButton_primary">{lang="use_no_album"} <i class='fa fa-caret-right'></i></button>	
					</form>
				</li>
			{{endif}}
			<li>
				<a href='#' class='cGalleryChooseAlbum_listItem' data-type='createAlbum' {{if !$canCreateAlbum || !$createAlbumForm}}data-disabled{{endif}}>
					<h2 class='ipsType_sectionHead'>{lang="create_new_album"}</h2>
					<p class='ipsType_reset ipsType_light'>
						{{if $createAlbumForm}}
							{lang="submit_new_album"}
						{{elseif !$canCreateAlbum}}
							{lang="cannot_create_album"}
						{{else}}
							{lang="used_max_albums" sprintf="$maximumAlbums"}
						{{endif}}
					</p>
				</a>
			</li>
			<li>
				<a href='#' class='cGalleryChooseAlbum_listItem' data-type='existingAlbum' {{if !$existingAlbumForm}}data-disabled{{endif}}>
					<h2 class='ipsType_sectionHead'>{lang="choose_existing_album"}</h2>
					<p class='ipsType_reset ipsType_light'>
						{{if $existingAlbumForm}}
							{lang="choose_existing_album_desc"}
						{{else}}
							{lang="no_existing_albums"}
						{{endif}}
					</p>
				</a>
			</li>
		</ul>
	</div>

	{{if $createAlbumForm}}
		<div data-role='createAlbumForm' class='ipsHide'>
			{$createAlbumForm|raw}
		</div>
	{{endif}}
	{{if $existingAlbumForm}}
		<div data-role='existingAlbumForm' class='ipsHide'>
			{$existingAlbumForm|raw}
		</div>
	{{endif}}
</div>