<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<ul class='ipsList_reset cGalleryDialog_formPanel ipsPadding_horizontal'>
		{{foreach $elements as $collection}}
			{{foreach $collection as $inputName => $input}}
				{{if \in_array( $inputName, array( 'album_name', 'album_description' ) )}}
					{{if \is_object( $input ) }}
						{$input->rowHtml($form)|raw}
					{{else}}
						{$input|raw}
					{{endif}}
				{{endif}}
			{{endforeach}}
		{{endforeach}}
		<li class='ipsFieldRow' id='elAlbumExtrasRow'>
			<ul class='ipsList_inline ipsSpacer_top ipsType_medium'>
				{{if isset( $elements['']['set_album_owner'] ) && \count( $elements['']['set_album_owner']->options['options'] ) > 1}}
					<li>
						<a href='#elAlbumCreate_owner_menu' id='elAlbumCreate_owner' data-ipsMenu data-ipsMenu-appendTo='#elAlbumExtrasRow' data-ipsMenu-closeOnClick='false'>{lang="album_create_owner"} <i class='fa fa-caret-down'></i></a>
					</li>
				{{endif}}
				{{if ( isset( $elements['']['album_type'] ) && \count( $elements['']['album_type']->options['options'] ) > 1 ) OR ( isset( $elements['']['album_submit_type'] ) && \count( $elements['']['album_submit_type']->options['options'] ) > 1 )}}
					<li>
						<a href='#elAlbumCreate_privacy_menu' id='elAlbumCreate_privacy' data-ipsMenu data-ipsMenu-appendTo='#elAlbumExtrasRow' data-ipsMenu-closeOnClick='false'>{lang="album_create_privacy"} <i class='fa fa-caret-down'></i></a>
					</li>
				{{endif}}
				{{if isset( $elements['']['album_sort_options'] ) || isset( $elements['']['album_allow_comments'] ) || isset( $elements['']['album_allow_reviews'] ) || isset( $elements['']['album_use_comments'] ) || isset( $elements['']['album_use_reviews'] )}}
					<li><a href='#elAlbumCreate_features_menu' id='elAlbumCreate_features' data-ipsMenu data-ipsMenu-appendTo='#elAlbumExtrasRow' data-ipsMenu-closeOnClick='false'>{lang="album_create_features"} <i class='fa fa-caret-down'></i></a></li>
				{{endif}}
			</ul>
		</li>
	</ul>
	<div class='ipsType_right cGalleryDialog_submitBar ipsPadding ipsBorder_top'>
		<button type='submit' class='ipsButton ipsButton_medium ipsButton_primary'>{lang="create_album"}</button>
	</div>
	<div id='elAlbumCreate_features_menu' class='ipsMenu ipsMenu_wide ipsHide'>
		<div class='ipsPad'>
			<ul class='ipsForm ipsForm_horizontal'>
				{{foreach array( 'album_sort_options', 'album_allow_comments', 'album_allow_reviews', 'album_use_comments', 'album_use_reviews' ) as $inputName}}
					{{if isset( $elements[''][ $inputName ] )}}
						{{if \is_object( $elements[''][ $inputName ] ) }}
							{$elements[''][ $inputName ]->rowHtml($form)|raw}
						{{else}}
							{$elements[''][ $inputName ]|raw}
						{{endif}}
					{{endif}}
				{{endforeach}}
			</ul>
		</div>
	</div>
	<div id='elAlbumCreate_privacy_menu' class='ipsMenu ipsMenu_wide ipsHide'>
		<div class='ipsPad'>
			<ul class='ipsForm ipsForm_vertical'>
				{{foreach array( 'album_type', 'album_allowed_access', 'album_submit_type', 'album_submit_access_members', 'album_submit_access_groups' ) as $inputName}}
					{{if isset( $elements[''][ $inputName ] )}}
						{{if \is_object( $elements[''][ $inputName ] ) }}
							{$elements[''][ $inputName ]->rowHtml($form)|raw}
						{{else}}
							{$elements[''][ $inputName ]|raw}
						{{endif}}
					{{endif}}
				{{endforeach}}
			</ul>
		</div>
	</div>
	<div id='elAlbumCreate_owner_menu' class='ipsMenu ipsMenu_wide ipsHide'>
		<div class='ipsPad'>
			<ul class='ipsForm ipsForm_vertical'>
				{{foreach array( 'set_album_owner', 'album_owner' ) as $inputName}}
					{{if isset( $elements[''][ $inputName ] )}}
						{$elements[''][ $inputName ]->rowHtml()|raw}
					{{endif}}
				{{endforeach}}
			</ul>
		</div>
	</div>
</form>