<ips:template parameters="$guestPostBeforeRegister, $modQueued, $continueUrl, $guestEmailError=NULL" />
<div class='ipsType_center ipsPad'>
	<form accept-charset='utf-8' class="ipsForm" action="{$continueUrl}" method="post" data-ipsForm>
		{{if !member.member_id}}
			<h2 class='ipsType_pageTitle'>{lang="gallery_guest_post_normal_header"}</h2>
			<p class='ipsType_large ipsType_reset ipsSpacer_top'>
				{{if $guestPostBeforeRegister}}
					{lang="gallery_guest_post_pbr_blurb"}<br>
				{{endif}}
				{lang="guest_post_sign_in"}
			</p>
			{{if $modQueued}}
				<p class='ipsType_normal ipsType_warning ipsType_reset ipsSpacer_top'>
					{lang="gallery_guest_post_mod_approval"}
				</p>					
			{{endif}}
			{{if $guestPostBeforeRegister}}
				<input type="hidden" name="guest_email_submit" value="1">
				<input type="email" name="guest_email" value="" placeholder="{lang="guest_email"}" class="ipsSpacer_top" required autocomplete="email">
				<br><span class="ipsType_light">{lang="guest_email_desc"}</span>
				{{if $guestEmailError}}
					<p class="ipsType_warning">{lang="$guestEmailError"}</p>
				{{endif}}
			{{else}}
				<input type="hidden" name="_pi" value="1">
			{{endif}}
			<ul class='ipsToolList ipsToolList_horizontal ipsPos_center ipsType_center ipsSpacer_top ipsSpacer_double'>
				<li>
					<button type="submit" class="ipsButton ipsButton_medium ipsButton_primary">{lang="continue"}</button>
				</li>
			</ul>
		{{else}}
			<input type="hidden" name="_pi" value="1">
			<h2 class='ipsType_warning'>{lang="mod_queue_message"}</h2>
			{{$warnings = member.warnings( 1, NULL, 'mq' );}}
			{{if \count( $warnings ) and member.mod_posts > time()}}
				{{if \count( $warnings )}}
					<p class="ipsType_large ipsType_reset ipsSpacer_top">
						{lang="gallery_this_will_be_moderated"}
					</p>
				{{endif}}
				<p class="ipsType_large ipsType_reset ipsSpacer_top">
					{lang="restriction_ends" sprintf="\IPS\DateTime::ts( \IPS\Member::loggedIn()->mod_posts )->relative()"}
				</p>
			{{endif}}
			<ul class='ipsToolList ipsToolList_horizontal ipsPos_center ipsType_center ipsSpacer_top ipsSpacer_double'>
				{{foreach $warnings as $idx => $warning}}
					<li>
						<a href="{$warning->url()}" class='ipsButton ipsButton_medium ipsButton_veryLight' data-ipsDialog data-ipsDialog-size='narrow'>{lang="view_warning_details"}</a>
					</li>
				{{endforeach}}
				<li>
					<button type="submit" class="ipsButton ipsButton_medium ipsButton_primary">{lang="continue"}</button>
				</li>
			</ul>
		{{endif}}
	</form>
</div>