<ips:template parameters="$form, $category" />

<form accept-charset='utf-8' method="post" action="{$form->action}" id='elGallerySubmit' enctype="multipart/form-data">
	<div class='cGallerySubmit_uploadImages' data-controller='gallery.front.submit.uploadImages'>
	{{if $form->error}}
		<div class="ipsMessage ipsMessage_error ipsSpacer_bottom">
			{$form->error}
		</div>
	{{endif}}
		<div class='cGallerySubmit_uploadForm'>
			<input type="hidden" name="{$form->id}_submitted" value="1">
			{{foreach $form->hiddenValues as $k => $v}}
				<input type="hidden" name="{$k}" value="{$v}">
			{{endforeach}}

			<div class='ipsHide'>
				{$form->elements['']['credit_all']->html()|raw}
				{$form->elements['']['copyright_all']->html()|raw}
				{$form->elements['']['tags_all']->html()|raw}
				{$form->elements['']['prefix_all']->html()|raw}
				{$form->elements['']['images_order']->html()|raw}
				{$form->elements['']['images_info']->html()|raw}
				{{if \IPS\Member::loggedIn()->member_id}}{$form->elements['']['images_autofollow_all']->html()|raw}{{endif}}
			</div>

			<div id='elGallerySubmit_imageUploader' class='ipsClear'>
				{$form->elements['']['images']->html( $form )|raw}
				{{if $form->elements['']['images']->error}}
					<br>
					<span class="ipsType_warning">{lang="$form->elements['']['images']->error"}</span>
				{{endif}}
			</div>
		</div>
	</div>
</form>