<ips:template parameters="$comment, $entry, $blog, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed cBlogEmbed'>
	{template="embedHeader" group="embed" app="core" params="$comment, $entry->mapped('title'), $comment->mapped('date'), $url"}	
	<div class='ipsPadding ipsClearfix'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{if $entry->coverPhoto() && $entry->coverPhoto()->file}}
					{{$photo = $entry->coverPhoto()->file;}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
						<a href='{$entry->url( "getPrefComment" )}' title='{$entry->_title}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $photo->url )"}") '>
							<img src='{$photo->url}' alt='{$entry->_title}' class='ipsHide'>
						</a>
					</div>
				{{elseif $blog->coverPhoto() && $blog->coverPhoto()->file}}
					{{$photo = $blog->coverPhoto()->file;}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
						<a href='{$blog->url()}' title='{$blog->_title}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $photo->url )"}") '>
							<img src='{$photo->url}' alt='{$blog->_title}' class='ipsHide'>
						</a>
					</div>
				{{endif}}
				<div class='ipsPadding'>
					{template="embedOriginalItem" group="embed" app="core" params="$entry, TRUE, \IPS\Theme::i()->getTemplate( 'global', 'blog' )->embedEntryItemSnippet( $blog )"}
				</div>
			</div>
		</div>

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if settings.reputation_enabled AND \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and \count( $comment->reactions() )}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>