<ips:template parameters="$blog, $url" />
<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed cBlogEmbed'>
	<div class='ipsRichEmbed_header ipsAreaBackground_light ipsClearfix'>
		<a href='{$blog->url()}' class='ipsRichEmbed_openItem'><i class='fa fa-external-link-square'></i></a>
		{{if !( $blog->owner() instanceof \IPS\Member ) and \count( $blog->contributors() )}}
			<p class='ipsRichEmbed_title ipsType_reset ipsTruncate ipsTruncate_line ipsType_blendLinks'>
				<a href='{$blog->url()}'>
					{$blog->_title}
				</a>
			</p>
			{{if $blog->latestEntry()}}
				<p class='ipsRichEmbed_author ipsType_reset ipsType_light ipsTruncate ipsTruncate_line ipsType_blendLinks'>
					<a href='{$blog->url()}'>{lang="blog_last_entry_date" htmlsprintf="\IPS\DateTime::ts( $blog->latestEntry()->mapped('date') )->html()"}</a>
				</p>
			{{endif}}
		{{else}}
			<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsType_blendLinks'>
				{template="userPhoto" app="core" group="global" params="$blog->owner(), 'tiny'"}
				<div>
					<p class='ipsRichEmbed_title ipsType_reset ipsTruncate ipsTruncate_line'>
						<a href='{$blog->url()}'>{lang="x_created_blog" sprintf="$blog->owner()->name"}</a>
					</p>
					{{if $blog->latestEntry()}}
						<p class='ipsRichEmbed_author ipsType_reset ipsType_light ipsTruncate ipsTruncate_line'>
							<a href='{$blog->url()}'>{lang="blog_last_entry_date" htmlsprintf="\IPS\DateTime::ts( $blog->latestEntry()->mapped('date') )->html()"}</a>
						</p>
					{{endif}}
				</div>
			</div>
		{{endif}}
	</div>
	{{if $blog->coverPhoto() && $blog->coverPhoto()->file}}
		{{$photo = $blog->coverPhoto()->file;}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
			<a href='{$blog->url()}' title='{$blog->_title}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $photo->url )"}") '>
				<img src='{$photo->url}' alt='{$blog->_title}' class='ipsHide'>
			</a>
		</div>
	{{endif}}
	<div class='ipsPadding ipsClearfix'>

		<ul class='ipsList_inline'>
			<li>{lang="num_blog_entries" pluralize="$blog->_items"}</li>
			<li>{lang="num_blog_comments" pluralize="$blog->_comments"}</li>
			<li>{lang="num_blog_views" pluralize="$blog->num_views"}</li>
		</ul>

		{{if $blog->description}}
			<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half' data-truncate='3'>
				{$blog->description|raw}
			</div>
		{{endif}}

		{{if $blog->latestEntry()}}
			<hr class='ipsHr'>
			<p class='ipsType_medium ipsType_reset ipsSpacer_top ipsSpacer_half ipsType_blendLinks'>
				<span class='ipsType_light'>{lang="latest_entry"}:</span> <a href='{$blog->latestEntry()->url( "getPrefComment" )}' title="{$blog->latestEntry()->mapped('title')}">{$blog->latestEntry()->mapped('title')}</a>
			</p>
		{{endif}}
	</div>

	{{if !( $blog->owner() instanceof \IPS\Member ) and \count( $blog->contributors() )}}
		<div class='ipsAreaBackground_light ipsPadding ipsClearfix ipsRichEmbed_moreInfo'>
			<h3 class='ipsType_minorHeading ipsTruncate ipsTruncate_line ipsType_blendLinks'>{lang="num_contributors_to_this" pluralize="\count( $blog->contributors() )"}</h3>
			<ul class='ipsList_inline ipsList_noSpacing ipsSpacer_top ipsSpacer_half ipsType_noBreak'>
				{{foreach $blog->contributors() as $idx => $contributor}}
					<li>
						{template="userPhoto" group="global" app="core" params="$contributor['member'], 'mini'"}<span class='ipsNotificationCount'>{$contributor['contributions']}</span>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{endif}}
</div>