<ips:template parameters="$entry, $blog, $url" />

<div data-embedInfo-maxSize='{{if settings.max_internalembed_width}}{setting="max_internalembed_width"}{{else}}100%{{endif}}' class='ipsRichEmbed cBlogEmbed'>
	{template="embedHeader" group="embed" app="core" params="$entry, $entry->mapped('title'), $entry->mapped('date'), $url"}
	{{if $entry->coverPhoto() && $entry->coverPhoto()->file}}
		{{$photo = $entry->coverPhoto()->file;}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
			<a href='{$entry->url( "getPrefComment" )}' title='{$entry->_title}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $photo->url )"}") '>
				<img src='{$photo->url}' alt='{$entry->_title}' class='ipsHide'>
			</a>
		</div>
	{{elseif $blog->coverPhoto() && $blog->coverPhoto()->file}}
		{{$photo = $blog->coverPhoto()->file;}}
		<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
			<a href='{$blog->url()}' title='{$blog->_title}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $photo->url )"}") '>
				<img src='{$photo->url}' alt='{$blog->_title}' class='ipsHide'>
			</a>
		</div>
	{{endif}}
	<div class='ipsPadding ipsClearfix'>
		{template="embedEntryItemSnippet" group="global" app="blog" params="$blog"}

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$entry->truncated(TRUE)|raw}
		</div>
		{template="embedItemStats" group="embed" app="core" params="$entry"}
	</div>
</div>