<ips:template parameters="$table, $headers, $blogs, $showSmall" />
{{foreach $blogs AS $blog}}
	<li class='ipsAreaBackground_light ipsPad cProfileBlog'>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_fluid'>
				<h3 class='ipsType_sectionHead ipsType_break ipsTruncate ipsTruncate_line'>
					<a href='{$blog->url()}'>{$blog->_title}</a> {{if $showSmall && !($blog->owner() instanceof \IPS\Member)}}&nbsp;&nbsp;<span class='ipsType_light ipsType_medium' data-ipsTooltip title='{lang="this_is_group"}'><i class='fa fa-users'></i> {lang="byline_nodate" sprintf="\IPS\Member::loggedIn()->language()->addToStack( 'blogs_groupblog_name_' . $blog->id )"}</span>{{endif}}
				</h3>
				<ul class='ipsGrid cProfileBlog_stats'>
					<li class='ipsGrid_span4'><strong class='ipsType_normal'>{$blog->_items}</strong><br>{lang="blog_entries" pluralize="$blog->_items"}</li>
					<li class='ipsGrid_span4'><strong class='ipsType_normal'>{$blog->_comments}</strong><br>{lang="blog_comments" pluralize="$blog->_comments"}</li>
					<li class='ipsGrid_span4'><strong class='ipsType_normal'>{$blog->num_views}</strong><br>{lang="blog_views" pluralize="$blog->num_views"}</li>
				</ul>
			</div>
			<div class='ipsColumn ipsColumn_wide'>
				{{if $blog->latestEntry()}}
					<h4 class='ipsType_minorHeading'>{lang="most_recent_entry"}</h4>		
					<a href='{$blog->latestEntry()->url( "getPrefComment" )}' title='{lang="view_this_entry" sprintf="$blog->latestEntry()->name"}' class='ipsType_large ipsTruncate ipsTruncate_line'>
						{{if $blog->latestEntry()->unread()}}
							<span class='ipsItemStatus' data-ipsTooltip title="{lang="unread_blog"}"><i class="fa fa-circle"></i></span>
						{{endif}}
						{$blog->latestEntry()->name}
					</a>
					<ul class='ipsList_inline ipsType_medium ipsType_light'>
						<li>{datetime="$blog->latestEntry()->date"}</li>
						{{if \IPS\Settings::i()->blog_enable_rating}}
							<li>{template="rating" app="core" params="'small', $blog->latestEntry()->averageRating(), 5, $blog->latestEntry()->memberRating()" group="global"}</li>
						{{endif}}
						{{if !$blog->latestEntry()->num_comments}}
							<li class='ipsType_light'>{lang="num_comments" pluralize="$blog->latestEntry()->num_comments"}</li>
						{{else}}
							<li><a href='{$blog->latestEntry()->url( "getPrefComment" )}#comments' title='{lang="see_comments_on_entry"}'>{lang="num_comments" pluralize="$blog->latestEntry()->num_comments"}</a></li>
						{{endif}}
					</ul>
				{{endif}}
			</div>
		</div>
	</li>
{{endforeach}}