<ips:template parameters="$file, $pendingVersion" />

{{if $club = $file->container()->club()}}
	{{if settings.clubs and settings.clubs_header == 'full'}}
		{template="header" app="core" group="clubs" params="$club, $file->container()"}
	{{endif}}
	<div id='elClubContainer'>
{{endif}}

<div>
	<div class='{{if $file->primary_screenshot}}ipsColumns ipsColumns_collapsePhone{{endif}} ipsClearfix'>
		<div {{if $file->primary_screenshot_thumb}}class='ipsColumn ipsColumn_fluid'{{endif}}>
            <div class='ipsPageHeader ipsResponsive_pull ipsBox ipsPadding'>
                <div class='ipsFlex ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:4'>
                    <div class='ipsFlex-flex:11'>
                        <h1 class='ipsType_pageTitle ipsContained_container'>
                            {{if $pendingVersion->hidden() === 1}}
                                <span><span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span></span>
                            {{endif}}
                            <span class='ipsType_break ipsContained'>{{if $file->locked()}}<i class='fa fa-lock'></i> {{endif}}{$file->name}{{if $file->container()->version_numbers}} {$pendingVersion->form_values['file_version']}{{endif}}</span>
                        </h1>

                        {{if $file->isPaid()}}
                            <p class="ipsType_pageTitle ipsType_reset ipsSpacer_top ipsSpacer_half">
                                {{if $price = $file->price()}}
                                    <span class='cFilePrice'>{$price|raw}</span>
                                    {{if $renewalTerm = $file->renewalTerm()}}
                                        <span class='ipsType_light'>&middot; {lang="file_renewal_term_val" sprintf="$renewalTerm"}</span>
                                    {{endif}}
                                {{endif}}
                            </p>
                        {{endif}}
			        </div>
                    <div class='ipsFlex-flex:00'>
                        <span class='ipsType_normal ipsType_light'>{lang="file_new_version_date" htmlsprintf="\IPS\DateTime::ts($pendingVersion->date)->html()"}</span>
                    </div>
                </div>
			    <hr class='ipsHr ipsResponsive_hidePhone'>

                <div class='ipsBox_alt'>
                    <div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix ipsSpacer_bottom'>
                        {template="userPhoto" app="core" group="global" params="$file->author(), 'tiny', $file->warningRef()"}
                        <div>
                            <p class='ipsType_reset ipsType_large ipsType_blendLinks'>
                                {lang="byline_nodate_itemprop" htmlsprintf="$file->author()->link( $file->warningRef(), NULL, $file->isAnonymous() )"}{{if member.group['idm_view_approvers'] and $file->approver}} {lang="file_approved_by" sprintf="\IPS\Member::load( $file->approver )->name" htmlsprintf="\IPS\DateTime::ts( $file->approvedon )->html()"}{{endif}}
                            </p>
                            {{if $file->author()->member_id}}
                            <ul class='ipsList_inline'>
                                {{if $file->author()->member_id}}
                                    <li><a href='{url="app=core&module=members&controller=profile&id={$file->author()->member_id}&do=content&type=downloads_file" base="front" seoTitles="$file->author()->members_seo_name" seoTemplate="profile_content"}'>{lang="find_users_files"}</a></li>
                                {{endif}}
                            </ul>
                            {{endif}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>

	{template="contentItemMessages" group="global" app="core" params="$file->getMessages(), $file"}
	
	{{if $pendingVersion->hidden() === 1 and $pendingVersion->canUnhide()}}
		<div class="ipsMessage ipsMessage_warning ipsSpacer_both">
			<p class="ipsType_reset">{lang="file_version_pending_approval"}</p>
            {{if $file->hidden() === 1}}
            <br>
            <p class="ipsType_reset">{lang="file_version_pending_cannot_approve"}</p>
            {{endif}}
			<br>
			<ul class='ipsList_inline' data-controller="downloads.front.pending.buttons">
                {{if $file->hidden() !== 1}}
				<li><a href="{$pendingVersion->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'unhide' ) )}" class="ipsButton ipsButton_positive ipsButton_verySmall" title='{lang="approve_title_file"}'><i class="fa fa-check"></i> {lang="approve"}</a></li>
				{{endif}}
                <li><a href='{$pendingVersion->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'delete' ) )}' data-confirm  title='{lang="pending_version_reject_title"}' data-confirmMessage="{lang="pending_version_reject_title"}" data-confirmSubMessage="{lang="pending_version_reject_desc"}" class='ipsButton ipsButton_negative ipsButton_verySmall'><i class='fa fa-times'></i> {lang="pending_version_reject"}</a></li>
			</ul>
		</div>
	{{endif}}

	<div class='ipsBox ipsSpacer_top ipsSpacer_double'>
		{{if $file->screenshots( 0, TRUE, NULL, TRUE )->getInnerIterator()->count()}}
			<section>
				<h2 class='ipsType_sectionTitle ipsType_reset ipsHide'>{lang="screenshots_ct" pluralize="$file->screenshots()->getInnerIterator()->count()"}</h2>
				<div class='ipsPad ipsAreaBackground'>
					<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
						<div class='ipsCarousel_inner'>
							<ul class='cDownloadsCarousel ipsClearfix' data-role="carouselItems">
								{{$fullScreenshots = iterator_to_array( $file->screenshots( 0, TRUE, NULL, TRUE) );}}
								{{foreach $file->screenshots( 1, TRUE, NULL, TRUE ) as $id => $screenshot}}
									<li class='ipsCarousel_item ipsAreaBackground_reset ipsPad_half' data-ipsLazyLoad>
										<span {{if settings.lazy_load_enabled}}data-background-src='{backgroundimage="$screenshot->url"}'{{else}}style='background-image: url({backgroundimage="$screenshot->url"})'{{endif}} class="ipsThumb ipsThumb_medium ipsThumb_bg ipsCursor_pointer" data-ipsLightbox data-ipsLightbox-group="download_{$file->id}" data-fullURL="{$fullScreenshots[ $id ]->url}">
											<img {{if settings.lazy_load_enabled}}src='{expression="\IPS\Text\Parser::blankImage()"}' data-{{endif}}src="{$screenshot->url}" alt="">
										</span>
									</li>
								{{endforeach}}
							</ul>
						</div>
						<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
						<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
						<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
						<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
					</div>
				</div>
			</section>
		{{endif}} 
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<article class='ipsColumn ipsColumn_fluid'>
				<div class='ipsPad'>
					<section class='ipsType_normal ipsSpacer_top'>
						<h2 class='ipsType_sectionHead'>{lang="file_changelog"}</h2>
						{{if empty( $pendingVersion->content() )}}
							<p class="ipsType_light">{lang="pending_no_changelog"}</p>
						{{else}}
						<div class='ipsType_richText ipsContained ipsType_break' data-controller='core.front.core.lightboxedImages'>
								{$pendingVersion->content()|raw}
						</div>
						{{endif}}

						<h2 class='ipsType_sectionHead ipsSpacer_top'>{lang="downloads_file_pl"}</h2>
						{{$files = $file->files( NULL, TRUE, TRUE );}}
						{{if \count( $files )}}
						<ul class='ipsDataList ipsDataList_reducedSpacing'>
							{{foreach $files as $f}}
							{{$data = $files->data();}}
							<li class='ipsDataItem'>
								<div class='ipsDataItem_main'>
									<h4 class='ipsDataItem_title ipsContained_container'><a href="{{if settings.idm_antileech AND !$file->requiresDownloadConfirmation()}}{$pendingVersion->url('download')->csrf()->setQueryString( 'fileId', $data['record_id'] )}{{else}}{$pendingVersion->url('download')->setQueryString( 'fileId', $data['record_id'] )}{{endif}}">{$f->originalFilename}</a></h4>
									{{if $data['record_size']}}<p class='ipsType_reset ipsDataItem_meta'>{filesize="$data['record_size']"}</p>{{endif}}
								</div>
								<div class='ipsDataItem_generic ipsDataItem_size4'>
									<span class="ipsHide" data-role="downloadCounterContainer">{lang="download_begins_in"} <span data-role="downloadCounter"></span> {lang="seconds"}</span>
									<a href="{{if settings.idm_antileech AND !$file->requiresDownloadConfirmation()}}{$pendingVersion->url('download')->csrf()->setQueryString( 'fileId', $data['record_id'] )}{{else}}{$pendingVersion->url('download')->setQueryString( 'fileId', $data['record_id'] )}{{endif}}" class='ipsButton ipsButton_primary ipsButton_small'>{lang="download"}</a>
								</div>
							</li>
							{{endforeach}}
						</ul>
						{{else}}
							<p class="ipsType_light">{lang="pending_no_changelog"}</p>
						{{endif}}
					</section>
				</div>
			</article>
			<aside class='ipsColumn ipsColumn_wide'>
				<div class='ipsPad'>
					{{if $file->topic()}}
						<a href='{$file->topic()->url()}' title='{lang="dl_get_support_title"}' class='ipsButton ipsButton_normal ipsButton_fullWidth'>{lang="dl_get_support"}</a>
						<hr class='ipsHr'>
					{{endif}}
					<h2 class='ipsType_sectionHead'>{lang="file_information"}</h2>
					<ul class="ipsDataList ipsDataList_reducedSpacing ipsSpacer_top">
						<li class="ipsDataItem">
							<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="submitted"}</strong></span>
							<span class="ipsDataItem_generic cFileInfoData">{datetime="$file->submitted"}</span>
						</li>
						{{if $file->updated != $file->submitted}}
							<li class="ipsDataItem">
								<span class="ipsDataItem_generic ipsDataItem_size3"><strong>{lang="updated"}</strong></span>
								<span class="ipsDataItem_generic cFileInfoData">{datetime="$file->updated"}</span>
							</li>
						{{endif}}
					</ul>
				</div>
			</aside>
		</div>
	</div>

</div>

{{if $file->container()->club()}}
	</div>
{{endif}}