<ips:template parameters="$comment" />
{{if !\is_array( $comment->ratingData ) OR !$comment->ratingData['rating_rating']}}
	<a href='{$comment->url()->setQueryString( array( 'response' => $comment->id, 'do' => 'rate' ) )}' class='ipsPos_right' data-ipsDialog data-ipsDialog-remoteSubmit data-ipsDialog-flashMessage="{lang="thanks_for_your_feedback"}" data-ipsDialog-size='narrow' data-ipsDialog-title="{lang="rate_this_response"}">{lang="rate_this_response"} <i class='fa fa-caret-down'></i></a>
{{else}}
	<div class='ipsType_reset ipsType_light ipsPos_right'>
		{lang="you_rated_response"}
		<ul class='ipsList_inline ipsRating'>
			{{foreach range( 1, 5 ) as $i}}
				<li class='{{if $i <= $comment->ratingData['rating_rating']}}ipsRating_on{{else}}ipsRating_off{{endif}}'><i class='fa fa-star'></i></li>
			{{endforeach}}
		</ul>
	</div>
{{endif}}