<ips:template parameters="$item, $comment" />
{{$idField = $comment::$databaseColumnId;}}
<div class='ipsBox ipsSpacer_bottom cNexusSupportMessage cNexusSupportMessage_{$comment->type} ipsComment ipsComment_parent' data-commentApp='nexus' data-commentType='support' data-commentID="{$comment->$idField}">
	<div class="ipsColumns ipsColumns_collapsePhone">
		<div class='ipsColumn ipsColumn_medium ipsType_center cNexusSupportMessage_author'>
			<div class='ipsPad'>
				{{if $comment->author()}}
					{template="userPhoto" group="global" app="core" params="$comment->author(), 'small'"}
				{{else}}
					<i class='fa fa-envelope'></i>
				{{endif}}

				<br class='ipsSpacer_bottom'><br>

				{{if $comment->type === $comment::REPLY_EMAIL}}
					By Email
				{{elseif $comment->type === $comment::REPLY_MEMBER or $comment->type === $comment::REPLY_ALTCONTACT}}
					{{if $comment->author()->member_id === \IPS\Member::loggedIn()->member_id}}
						<h3 class='ipsType_sectionHead ipsType_blendLinks'><strong>{lang="you"}</strong></h3>
					{{else}}
						<h3 class='ipsType_sectionHead ipsType_blendLinks'><strong><a href="{$comment->author()->acpUrl()}">{$comment->author()->cm_name}</a></strong></h3>
					{{endif}}
				{{else}}
					<h3 class='ipsType_sectionHead ipsType_blendLinks'><strong>{$comment->author()->cm_name}</strong></h3>
				{{endif}}

				{{if $comment->type === $comment::REPLY_MEMBER}}
					<p class='ipsType_medium ipsType_reset'>{lang="reply_by__accountowner"}</p>
				{{elseif $comment->type === $comment::REPLY_ALTCONTACT}}
					<p class='ipsType_medium ipsType_reset'>{lang="reply_by__altcontact"}</p>
				{{elseif $comment->type === $comment::REPLY_STAFF}}
					<p class='ipsType_medium ipsType_reset'>{lang="reply_by__staff"}</p>
				{{endif}}
			</div>
		</div>
		<div class='ipsColumn ipsColumn_fluid cNexusSupportMessage_message'>
			<div class='ipsPad'>
				<div class='cNexusSupportMessage_date ipsType_medium'>
					{{if $comment->type === $comment::REPLY_STAFF and settings.nexus_support_satisfaction}}
						<div data-controller='nexus.front.support.rate'>
							{template="ratingValue" group="support" params="$comment"}
						</div>
					{{endif}}
					<p class='ipsType_reset ipsType_light'>
						{datetime="$comment->date"}
						{{if $comment->cc}}
							<br><span class='ipsType_small'><strong>{lang="cc"}:</strong> {$comment->cc}</span>
						{{endif}}
						{{if $comment->bcc}}
							<br><span class='ipsType_small'><strong>{lang="bcc"}:</strong> {$comment->bcc}</span>
						{{endif}}
					</p>
				</div>
				<hr class='ipsHr'>
				<div class='ipsType_richText ipsType_normal ipsContained ipsType_break' data-controller="core.front.core.lightboxedImages">
					{$comment->content()|raw}
				</div>
			</div>
		</div>
	</div>
</div>