<ips:template parameters="$table" />

<div class="ipsPageHeader ipsClearfix ipsMargin_bottom ipsHeaderButtons ipsFlex ipsFlex-ai:center ipsFlex-jc:center ipsFlex-fw:wrap">
	<h1 class="ipsType_pageTitle ipsFlex-flex:11 ipsType_break">{lang="your_support_requests"}</h1>

	<ul class="ipsToolList ipsToolList_horizontal ipsClearfix ipsMargin_bottom:none ipsFlex-flex:00">
		<li class='ipsToolList_primaryAction'>
			<a class="ipsButton ipsButton_medium ipsButton_important ipsButton_fullWidth" href="{url="app=nexus&module=support&controller=home&do=create" seoTemplate="support_create"}" data-ipsDialog data-ipsDialog-title='{lang="new_request"}' rel='nofollow noindex'>{lang="new_request"}</a>
		</li>
	</ul>
</div>

<div class='ipsBox'>
	{$table|raw}
</div>