<ips:template parameters="$easyPost" />
{{if isset( $easyPost['messages'] ) and \count( $easyPost['messages'] )}}
	{{foreach $easyPost['messages'] as $message}}
		<p class="ipsMessage {{if $message['type'] == 'rate_error'}}ipsMessage_warning{{else}}ipsMessage_info{{endif}}">{{if isset( $message['carrier'] )}}{$message['carrier']}: {{endif}}{$message['message']}</p>
	{{endforeach}}
{{endif}}
<table class="ipsTable">
	<thead>
		<tr>
			<th>{lang="easypost_carrier"}</th>
			<th>{lang="easypost_service"}</th>
			<th>{lang="easypost_rate"}</th>
			<th>{lang="shiprate_delivery_estimate"}</th>
		</tr>
	</thead>
	<tbody>
		{{if empty( $easyPost['rates'] )}}
			<tr>
				<td colspan="4">
					<div class='ipsPad_double ipsType_light'>
						{lang="easypost_no_results"}
					</div>
				</td>
			</tr>
		{{else}}
			{{foreach $easyPost['rates'] as $row}}
				<tr>
					<td>{$row['carrier']}</td>
					<td>{$row['service']}</td>
					<td>{money="$row['rate']" currency="$row['currency']"}</td>
					<td>{{if $row['est_delivery_days']}}{lang="easypost_delivery_estimate" pluralize="$row['est_delivery_days']"}{{endif}}</td>
				</tr>
			{{endforeach}}
		{{endif}}
	</tbody>
</table>