<ips:template parameters="$album" />

<div data-controller='core.front.core.commentFeed' {{if settings.auto_polling_enabled}}data-autoPoll{{endif}} data-commentsType='reviews' data-baseURL='{$album->url()}' {{if $album->isLastPage('reviews')}}data-lastPage{{endif}} data-feedID='image-{$album->id}-reviews' id='reviews'>
	{{if $album->reviewForm()}}
		<div id='elImageReviewForm'>
			{$album->reviewForm()|raw}
		</div>
	{{else}}
		{{if $album->hasReviewed()}}
			<!-- Already reviewed -->
		{{elseif \IPS\Member::loggedin()->restrict_post}}
			{{if \IPS\Member::loggedIn()->restrict_post == -1}}
				{template="reviewUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment'"}
			{{else}}
				{template="reviewUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
			{{endif}}
		{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
			{template="reviewUnavailable" group="forms" location="front" app="core" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
		{{endif}}
	{{endif}}
	{{if \count( $album->reviews( NULL, NULL, NULL, 'desc', NULL, NULL, NULL, NULL, isset( \IPS\Request::i()->showDeleted ) ) )}}
		{{if !$album->hasReviewed()}}<hr class='ipsHr'>{{endif}}
		<div class="ipsClearfix ipsSpacer_bottom">
			{template="commentMultimodHeader" app="core" group="global" params="$album, '#reviews', 'review'"}
			{{if $album->reviewPageCount() > 1}}
				<div class="ipsPos_left ipsResponsive_noFloat">
					{$album->reviewPagination( array( 'tab', 'sort' ) )|raw}
				</div>
			{{endif}}
			<div class="ipsClearfix ipsPos_right ipsResponsive_hidePhone">
				<ul class="ipsButtonRow ipsClearfix">
					<li data-action="tableFilter">
						<a href="{$album->url()->setQueryString( array( 'tab' => 'reviews', 'sort' => 'helpful' ) )->setPage('page',1)}" class="{{if !isset( request.sort ) or request.sort != 'newest'}}ipsButtonRow_active{{endif}}" data-action="filterClick">{lang="most_helpful"}</a>
					</li>
					<li data-action="tableFilter">
						<a href="{$album->url()->setQueryString( array( 'tab' => 'reviews', 'sort' => 'newest' ) )->setPage('page',1)}" class="{{if isset( request.sort ) and request.sort == 'newest'}}ipsButtonRow_active{{endif}}" data-action="filterClick">{lang="newest"}</a>
					</li>
				</ul>
			</div>
		</div>

		<div data-role='commentFeed' data-controller='core.front.core.moderation'>
			<form action="{$album->url()->csrf()->setQueryString( 'do', 'multimodReview' )->setPage('page',\IPS\Request::i()->page)}" method="post" data-ipsPageAction data-role='moderationTools'>
				{{$reviewCount=0; $timeLastRead = $album->timeLastRead(); $lined = FALSE;}}
				{{foreach $album->reviews( NULL, NULL, NULL, 'desc', NULL, NULL, NULL, NULL, isset( \IPS\Request::i()->showDeleted ) ) as $review}}
					{{if !$lined and $timeLastRead and $timeLastRead->getTimestamp() < $review->mapped('date')}}
						{{if $lined = TRUE and $reviewCount}}
							<hr class="ipsCommentUnreadSeperator">
						{{endif}}
					{{endif}}
					{{$reviewCount++;}}
					{$review->html()|raw}
				{{endforeach}}
				{template="commentMultimod" app="core" group="global" params="$album, 'review'"}
			</form>
		</div>
		{{if $album->reviewPageCount() > 1}}
			<div>
				{$album->reviewPagination( array( 'tab', 'sort' ) )|raw}
			</div>
		{{endif}}
	{{elseif !$album->canReview()}}
		<p class="ipsType_normal ipsType_light ipsType_reset" data-role="noReviews">{lang="no_reviews"}</p>
	{{endif}}
</div>