<ips:template parameters="$album" />
<div>
	<div class='' data-controller='core.front.core.commentFeed, core.front.core.ignoredComments' {{if settings.auto_polling_enabled}}data-autoPoll{{endif}} data-baseURL='{$album->url()}' {{if $album->isLastPage()}}data-lastPage{{endif}} data-feedID='image-{$album->id}' id='comments'>
		<div class=''>
			<h2 class='ipsType_sectionHead ipsType_sectionHead--galleryFeedbackCount ipsMargin_bottom' data-role="comment_count">{lang="num_comments_uc" pluralize="$album->comments"}</h2>
			{{if $album->commentPageCount() > 1}}
				<div class='ipsMargin_bottom:half'>{$album->commentPagination( array('tab') )|raw}</div>
			{{endif}}

			<div data-role='commentFeed' data-controller='core.front.core.moderation'>
				{{if \count( $album->comments( NULL, NULL, 'date', 'asc', NULL, NULL, NULL, NULL, FALSE, isset( \IPS\Request::i()->showDeleted ) ) )}}
					<form action="{$album->url()->csrf()->setQueryString( 'do', 'multimodComment' )->setPage('page',\IPS\Request::i()->page)}" method="post" data-ipsPageAction data-role='moderationTools'>
						{{$commentCount=0; $timeLastRead = $album->timeLastRead(); $lined = FALSE;}}
						{{foreach $album->comments( NULL, NULL, 'date', 'asc', NULL, NULL, NULL, NULL, FALSE, isset( \IPS\Request::i()->showDeleted ) ) as $comment}}
							{{if !$lined and $timeLastRead and $timeLastRead->getTimestamp() < $comment->mapped('date')}}
								{{if $lined = TRUE and $commentCount}}
									<hr class="ipsCommentUnreadSeperator">
								{{endif}}
							{{endif}}
							{{$commentCount++;}}
							{$comment->html()|raw}
						{{endforeach}}
						{template="commentMultimod" app="core" group="global" params="$album"}
					</form>
				{{else}}
					<p class='ipsType_normal ipsType_light ipsType_reset' data-role='noComments'>{lang="no_comments"}</p>
				{{endif}}
			</div>			
			{{if $album->commentPageCount() > 1}}
				<hr class='ipsHr'>
				{$album->commentPagination( array('tab') )|raw}
			{{endif}}

			{{if $album->commentForm() || $album->locked() || \IPS\Member::loggedIn()->restrict_post || \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings'] || !\IPS\Member::loggedIn()->checkPostsPerDay()}}
			<a id='replyForm'></a>
			<div data-role='replyArea' class='ipsBox ipsBox--child ipsPadding sm:ipsPadding:half {{if !$album->canComment()}}cTopicPostArea_noSize{{endif}} ipsSpacer_top'>
				{{if $album->commentForm()}}
					{{if $album->locked()}}
						<p class='ipsType_reset ipsType_warning ipsComposeArea_warning ipsSpacer_bottom ipsSpacer_half'><i class='fa fa-info-circle'></i> {lang="album_locked_can_comment"}</p>
					{{endif}}
						{$album->commentForm()|raw}
				{{else}}
					{{if $album->locked()}}
						{template="commentUnavailable" group="forms" location="front" app="core" params="'album_locked_cannot_comment'"}
					{{elseif \IPS\Member::loggedIn()->restrict_post}}
						{template="commentUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
					{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
						{template="commentUnavailable" group="forms" location="front" app="core" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
					{{elseif !\IPS\Member::loggedIn()->checkPostsPerDay()}}
						{template="commentUnavailable" group="forms" location="front" app="core" params="'member_exceeded_posts_per_day'"}
					{{endif}}
				{{endif}}
			</div>
			{{endif}}
		</div>
	</div>
</div>
