<ips:template parameters="$table, $headers, $albums" />
{{foreach $albums as $album}}
	{{if $album instanceof \IPS\Content\Item}}
		{{$album = $album->asNode();}}
	{{endif}}
	<li class='ipsDataItem sm:ipsPadding ipsAreaBackground_reset{{if $album->asItem()->hidden()}} ipsModerated{{endif}}'>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_wide'>
				<div class='ipsPadding sm:ipsPadding:none'>
					<h3 class='ipsType_sectionHead ipsContained_container'>
						{{if \IPS\gallery\Image::containerUnread( $album )}}
							<span><span class="ipsItemStatus" data-ipsTooltip title="{lang="album_new_content"}"><i class="fa fa-circle"></i></span></span>
						{{endif}}
						{{if $album->asItem()->mapped('featured')}}
							<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span></span>
						{{endif}}
						{{if $album->type === \IPS\gallery\Album::AUTH_TYPE_PRIVATE}}
							<span class='ipsResponsive_hideTablet ipsResponsive_hideDesktop'><span class="ipsBadge ipsBadge_warning">{lang="album_private_badge"}</span></span>
						{{elseif $album->type === \IPS\gallery\Album::AUTH_TYPE_RESTRICTED}}
							<span class='ipsResponsive_hideTablet ipsResponsive_hideDesktop'><span class="ipsBadge ipsBadge_warning">{lang="album_friend_only_badge"}</span></span>
						{{endif}}
						{{if \IPS\gallery\Image::containerUnread( $album )}}<strong>{{endif}}
							<span class='ipsContained ipsType_break'><a href='{$album->url()}' title='{lang="view_this_album" sprintf="$album->_title"}'>{$album->_title}</a></span>
						{{if \IPS\gallery\Image::containerUnread( $album )}}</strong>{{endif}}

						{{if $album->last_img_date}}
							<span class='ipsContained ipsType_break ipsType_light ipsType_small ipsType_reset ipsResponsive_hidePhone'>{lang="updated"} {datetime="$album->last_img_date"}</span>
						{{endif}}
					</h3>

					{{if $album->type === \IPS\gallery\Album::AUTH_TYPE_PRIVATE}}
						<div class='ipsSpacer_top ipsSpacer_bottom ipsSpacer_half ipsResponsive_hidePhone'><span class="ipsBadge ipsBadge_warning">{lang="album_private_badge"}</span></div>
					{{elseif $album->type === \IPS\gallery\Album::AUTH_TYPE_RESTRICTED}}
						<div class='ipsSpacer_top ipsSpacer_bottom ipsSpacer_half ipsResponsive_hidePhone'><span class="ipsBadge ipsBadge_warning">{lang="album_friend_only_badge"}</span></div>
					{{endif}}

					{{if $result = $album->truncated()}}
						<div class='ipsType_medium ipsType_richText ipsSpacer_both ipsContained' data-ipsTruncate data-ipsTruncate-size='3 lines' data-ipsTruncate-type='remove'>
							{$result|raw}
						</div>
					{{else}}
						<p class='ipsSpacer_bottom ipsResponsive_hidePhone'></p>
					{{endif}}

					{{if !isset( \IPS\Request::i()->tab ) || \IPS\Request::i()->tab !== 'node_gallery_gallery'}}
						<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsPhotoPanel_notPhone'>
							{template="userPhoto" group="global" app="core" params="$album->owner(), 'tiny'"}
							<div>
								<span class='ipsType_minorHeading ipsResponsive_hidePhone'>{lang="album_created_by"}</span>
								<span class='ipsType_minorHeading ipsResponsive_hideTablet ipsResponsive_hideDesktop'>{lang="by"}</span>
								<br class='ipsResponsive_hidePhone'>
								<span class='ipsType_normal'>{$album->owner()->link()|raw}</span>
								{{if $album->last_img_date}}
									<span class='ipsType_minorHeading ipsResponsive_hideTablet ipsResponsive_hideDesktop cGalleryUpdated'>{lang="updated"}</span>
									<span class='ipsType_normal ipsResponsive_hideTablet ipsResponsive_hideDesktop'>{datetime="$album->last_img_date"}</span>
								{{endif}}
							</div>
						</div>
					{{endif}}

					<ul class='ipsList_inline ipsType_small ipsResponsive_hidePhone ipsClear ipsSpacer_top ipsAreaBackground_light ipsPad ipsPad_half ipsType_center'>
						<li data-ipsTooltip title='{lang="num_images" pluralize="$album->count_imgs"}'><i class='fa fa-camera'></i> {$album->count_imgs}</li>
						{{if $album->use_comments}}
							<li data-ipsTooltip title='{lang="num_comments" pluralize="$album->comments"}'><i class='fa fa-comment'></i> {$album->comments}</li>
						{{endif}}
						{{if $album->allow_comments}}
							<li data-ipsTooltip title='{lang="gallery_image_comments_s" pluralize="$album->count_comments"}'><i class='fa fa-comment'></i> {$album->count_comments}</li>
						{{endif}}
					</ul>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				{{if $table->canModerate()}}
					<div class='ipsPos_right ipsPad'>
						<input type='checkbox' data-role='moderation' name="moderate[{$album->_id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $album ) )"}" data-state=''>
					</div>
				{{endif}}
				<div class='ipsPad cGalleryAlbums_recent'>
					<ul class='ipsList_reset' data-controller='gallery.front.browse.imageLightbox' data-ipsLazyLoad>
						<li {{if $album->coverPhoto( 'small' )}}{{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="$album->coverPhoto( 'small' )"}"{{else}}style='background-image: url({backgroundimage="$album->coverPhoto( 'small' )"})'{{endif}}{{endif}} class='cGalleryTrimmedImage{{if !$album->coverPhoto('small') AND $album->lastImage() AND $album->lastImage()->media}} ipsNoThumb ipsNoThumb_video{{endif}}'>
							<a href='{$album->url()}' title='{lang="view_this_album" sprintf="$album->_title"}'>
								{{if $album->coverPhoto( 'small' )}}
									<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{$album->coverPhoto( 'small' )}' alt="{$album->_title}">
								{{endif}}
							</a>
						</li>
						{{foreach $album->_latestImages as $image }}
							{{if ( $album->cover_img_id AND $image->id != $album->cover_img_id ) OR ( !$album->cover_img_id AND $album->lastImage() AND $image->id != $album->lastImage()->id )}}
								<li {{if $image->small_file_name}}{{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="\IPS\File::get( 'gallery_Images', $image->small_file_name )->url"}"{{else}}style='background-image: url({backgroundimage="\IPS\File::get( 'gallery_Images', $image->small_file_name )->url"})'{{endif}}{{endif}} class='cGalleryTrimmedImage{{if $image->media}} ipsNoThumb ipsNoThumb_video{{endif}}' data-imageId="{$image->id}">
									<a href='{$image->url( "getPrefComment" )}' data-imageLightbox>
										{{if $image->small_file_name}}<img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}">{{endif}}
										{{if ( $image->directContainer()->allow_comments && $image->container()->allow_comments )}}
											<span class='cGalleryAlbums_comments'><i class='fa fa-comment'></i> {expression="\count( $image->comments() )"}</span>
										{{endif}}
									</a>
								</li>
							{{endif}}
						{{endforeach}}
					</ul>	
				</div>
				<ul class='ipsList_inline ipsType_small ipsResponsive_hideTablet ipsResponsive_hideDesktop sm:ipsMargin_top'>
					<li><i class='fa fa-camera'></i> {lang="num_images" pluralize="$album->count_imgs"}</li>
					{{if $album->use_comments}}
						<li><i class='fa fa-comment'></i> {lang="num_comments" pluralize="$album->comments"}</li>
					{{endif}}
					{{if $album->allow_comments}}
						<li><i class='fa fa-comment'></i> {lang="gallery_image_comments_s" pluralize="$album->count_comments"}</li>
					{{endif}}
				</ul>
			</div>
		</div>
	</li>
{{endforeach}}