<ips:template parameters="$table, $headers, $albums" />
{{foreach $albums as $album}}
	{{if $album instanceof \IPS\Content\Item}}
		{{$album = $album->asNode();}}
	{{endif}}
	<li class='ipsDataItem ipsPadding ipsAreaBackground_reset{{if $album->asItem()->hidden()}} ipsModerated{{endif}}'>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_wide'>
				<div class='ipsPadding sm:ipsPadding:none'>
					<h3 class='ipsType_sectionHead ipsContained_container'>
						{{if \IPS\gallery\Image::containerUnread( $album )}}
							<span><span class="ipsItemStatus" data-ipsTooltip title="{lang="album_new_content"}"><i class="fa fa-circle"></i></span></span>
						{{endif}}
						{{if $album->asItem()->mapped('featured')}}
							<span><span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span></span>
						{{endif}}
						{{if $album->type === \IPS\gallery\Album::AUTH_TYPE_PRIVATE}}
							<span class='ipsResponsive_hideTablet ipsResponsive_hideDesktop'><span class="ipsBadge ipsBadge_warning">{lang="album_private_badge"}</span></span>
						{{elseif $album->type === \IPS\gallery\Album::AUTH_TYPE_RESTRICTED}}
							<span class='ipsResponsive_hideTablet ipsResponsive_hideDesktop'><span class="ipsBadge ipsBadge_warning">{lang="album_friend_only_badge"}</span></span>
						{{endif}}
						{{if \IPS\gallery\Image::containerUnread( $album )}}<strong>{{endif}}
							<span class='ipsContained ipsType_break'><a href='{$album->url()}' title='{lang="view_this_album" sprintf="$album->_title"}'>{$album->_title}</a></span>
						{{if \IPS\gallery\Image::containerUnread( $album )}}</strong>{{endif}}
					</h3>

					{{if $result = $album->truncated()}}
						<div class='ipsType_medium ipsType_richText ipsContained' data-ipsTruncate data-ipsTruncate-size='3 lines' data-ipsTruncate-type='remove'>
							{$result|raw}
						</div>
					{{endif}}

					{{if $album->type === \IPS\gallery\Album::AUTH_TYPE_PRIVATE}}
						<div class='ipsMargin_top:half ipsResponsive_hidePhone'><span class="ipsBadge ipsBadge_warning">{lang="album_private_badge"}</span></div>
					{{elseif $album->type === \IPS\gallery\Album::AUTH_TYPE_RESTRICTED}}
						<div class='ipsMargin_top:half ipsResponsive_hidePhone'><span class="ipsBadge ipsBadge_warning">{lang="album_friend_only_badge"}</span></div>
					{{endif}}

					<ul class='ipsMargin_top ipsList_icons ipsType_semiBold ipsResponsive_hidePhone'>
						{{if !isset( \IPS\Request::i()->tab ) || \IPS\Request::i()->tab !== 'node_gallery_gallery'}}
							<li class='ipsType_light ipsType_unbold'><i class='fa fa-user-circle-o'></i> {lang="album_created_by"} {$album->owner()->link()|raw}</li>
						{{endif}}
						{{if $album->last_img_date}}
							<li class='ipsType_light ipsType_unbold'><i class="fa fa-clock-o"></i> {lang="updated"} {datetime="$album->last_img_date"}</li>
						{{endif}}
						<li class='ipsMargin_top'><i class='fa fa-camera'></i> {lang="num_images" pluralize="$album->count_imgs"}</li>
						{{if $album->use_comments && $album->comments > 0}}
							<li><i class='fa fa-comments-o'></i> {lang="gallery_album_num_comments_lc" pluralize="$album->comments"}</li>
						{{endif}}
						{{if $album->allow_comments && $album->count_comments > 0}}
							<li><i class='fa fa-comment'></i> {lang="gallery_image_comments_s" pluralize="$album->count_comments"}</li>
						{{endif}}
	                    {{if $album->use_reviews && $album->reviews > 0}}
	                        <li><i class='fa fa-comment'></i> {lang="gallery_album_num_reviews_lc" pluralize="$album->reviews"}</li>
	                    {{endif}}
					</ul>

					<ul class='ipsList_inline ipsType_small ipsResponsive_hideTablet ipsResponsive_hideDesktop ipsMargin_top'>
						<li><i class='fa fa-camera'></i> {lang="num_images" pluralize="$album->count_imgs"}</li>
	                    {{if $album->use_comments && $album->comments > 0}}
							<li><i class='fa fa-comments-o'></i> {lang="gallery_album_num_comments_lc" pluralize="$album->comments"}</li>
						{{endif}}
						{{if $album->allow_comments && $album->count_comments > 0}}
							<li><i class='fa fa-comment'></i> {lang="gallery_image_comments_s" pluralize="$album->count_comments"}</li>
						{{endif}}
	                    {{if $album->use_reviews && $album->reviews > 0}}
	                        <li><i class='fa fa-comment'></i> {lang="gallery_album_num_reviews_lc" pluralize="$album->reviews"}</li>
	                    {{endif}}
					</ul>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				{{if $table->canModerate()}}
					<div class='ipsPos_right ipsPad'>
						<input type='checkbox' data-role='moderation' name="moderate[{$album->_id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $album ) )"}" data-state=''>
					</div>
				{{endif}}
				<ul class='cGalleryAlbums_recent' {{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
					{{foreach $album->_latestImages as $image }}
						<li data-imageId="{$image->id}">
							<div class='ipsImageBlock'>
								<a href='{$image->url( "getPrefComment" )}' class='ipsImageBlock__main'>
									{{if $image->small_file_name}}
										<img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
									{{elseif $image->media}}
										<video loading="lazy"{{if $image->masked_file_name }} poster="{file="$image->masked_file_name" extension="gallery_Images"}"{{else}} preload="metadata"{{endif}}>
											<source src="{file="$image->original_file_name" extension="gallery_Images"}{{if !$image->masked_file_name }}#t=1{{endif}}" type='{$image->file_type}' />
										</video>
										<div class='ipsImageBlock__video-icon'></div>
									{{endif}}
								</a>
								{{if ( $image->directContainer()->allow_comments && $image->container()->allow_comments && count($image->comments()) > 0 )}}
									<div class='ipsImageBlock__footer'>
										<span><i class='fa fa-comment'></i> {expression="\count( $image->comments() )"}</span>
									</div>
								{{endif}}
                                {template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
							</div>
						</li>
					{{endforeach}}
				</ul>
			</div>
		</div>
	</li>
{{endforeach}}