<ips:template parameters="$categories" />

{{if \count( $categories )}}
	<ul class='cGalleryCats'{{if settings.gallery_nsfw}} data-controller="gallery.front.global.nsfw"{{endif}}>
	{{foreach $categories as $category}}
		<li class='cGalleryCat'>
			<div class='ipsImageBlock'>
				<a href='{$category->url()}' class='ipsImageBlock__main'>
					{{if $category->lastImage() && $category->lastImage()->media && !$category->cover_img_id}}
						<video preload="metadata" loading="lazy"{{if $category->lastImage()->masked_file_name }} poster="{file="$category->lastImage()->masked_file_name" extension="gallery_Images"}"{{endif}}>
							<source src="{file="$category->lastImage()->original_file_name" extension="gallery_Images"}{{if !$category->lastImage()->masked_file_name }}#t=1{{endif}}" type='{$category->lastImage()->file_type}' />
						</video>
						<div class='ipsImageBlock__video-icon'></div>
					{{elseif $category->coverPhoto('small') !== NULL}}
						<img src="{$category->coverPhoto('small')}" alt="{$category->_title}" loading="lazy">
					{{endif}}
				</a>
				{{if $category->lastImage() && $category->lastImage()->media && !$category->cover_img_id}}
					{template="nsfwOverlay" app="gallery" location="front" group="global" params="$category->lastImage()"}
				{{elseif $category->coverPhoto('small') !== NULL}}
	                {template="nsfwOverlay" app="gallery" location="front" group="global" params="$category->coverPhotoObject()"}
				{{endif}}
			</div>

			<h2 class='cGalleryCats__name'>
				<a href='{$category->url()}'>
					{{if settings.club_nodes_in_apps and $club = $category->club()}}
						{lang="club_node" sprintf="$club->name, $category->_title"}
					{{else}}
						{$category->_title}
					{{endif}}
				</a>
			</h2>
			<ul class='cGalleryCats__stats'>
				{{if $category->lastImage() !== NULL}}<li><i class='fa fa-clock-o'></i> {datetime="$category->lastImage()->date"}</li>{{endif}}
				{{if $category->allow_comments && $category->_commentsForDisplay > 0}}
					<li data-ipsTooltip title='{lang="cat_comment_count" pluralize="$category->_commentsForDisplay"}'><i class='fa fa-comment'></i> {$category->_commentsForDisplay}</li>
				{{endif}}
				{{if $category->allow_albums && $category->public_albums > 0}}
					<li data-ipsTooltip title='{lang="cat_album_count" pluralize="$category->public_albums"}'><i class='fa fa-th-large'></i> {$category->public_albums}</li>
				{{endif}}
				{{$count = \IPS\gallery\Image::contentCount( $category );}}
				{{if $count > 0}}
					<li data-ipsTooltip title='{lang="cat_img_count" pluralize="$count"}'><i class='fa fa-camera'></i> {number="$count"}</li>
				{{endif}}
			</ul>
		</li>
	{{endforeach}}
	</ul>
{{endif}}