<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-controller='core.global.core.table{{if $table->canModerate()}},core.front.core.moderation{{endif}}{{if settings.gallery_nsfw}},gallery.front.global.nsfw{{endif}}'>
	{{if \IPS\Request::i()->app == 'gallery'}}<h2 class='ipsType_sectionTitle ipsType_reset ipsClear ipsType_medium ipsHide'>{lang="num_images" pluralize="$table->count"}</h2>{{endif}}
	{{if $table->canModerate() OR ( $table->showAdvancedSearch AND ( (isset( $table->sortOptions ) and !empty( $table->sortOptions )) OR $table->advancedSearch ) ) OR !empty( $table->filters ) OR $table->pages > 1}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
			{{if $table->canModerate()}}
				<ul class="ipsButtonRow ipsPos_right ipsClearfix">
					<li>
						<a class="ipsJS_show" href="#elCheck_menu" id="elCheck_{$table->uniqueId}" title='{lang="{$table->langPrefix}select_rows_tooltip"}' data-ipsTooltip data-ipsAutoCheck data-ipsAutoCheck-context="#elTable_{$table->uniqueId}" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active">
							<span class="cAutoCheckIcon ipsType_medium"><i class="fa fa-square-o"></i></span> <i class="fa fa-caret-down"></i>
							<span class='ipsNotificationCount' data-role='autoCheckCount'>0</span>
						</a>
						<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elCheck_{$table->uniqueId}_menu">
							<li class="ipsMenu_title">{lang="{$table->langPrefix}select_rows"}</li>
							<li class="ipsMenu_item" data-ipsMenuValue="all"><a href="#">{lang="all"}</a></li>
							<li class="ipsMenu_item" data-ipsMenuValue="none"><a href="#">{lang="none"}</a></li>
							{{if \count($table->getFilters())}}
								<li class="ipsMenu_sep"><hr></li>
								{{foreach $table->getFilters() as $filter}}
									<li class="ipsMenu_item" data-ipsMenuValue="{$filter}"><a href="#">{lang="$filter"}</a></li>
								{{endforeach}}
							{{endif}}
						</ul>
					</li>
				</ul>
			{{endif}}

			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				{{if $table->showAdvancedSearch AND ( ( isset( $table->sortOptions ) and !empty( $table->sortOptions ) ) OR $table->advancedSearch )}}
					<li>
						<a href="#elSortByMenu_menu" id="elSortByMenu_{$table->uniqueId}" data-role='sortButton' data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="sort_by"} <i class="fa fa-caret-down"></i></a>
						<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elSortByMenu_{$table->uniqueId}_menu">
							{{$custom = TRUE;}}
							{{foreach $table->sortOptions as $k => $col}}
								<li class="ipsMenu_item {{if $col === $table->sortBy}}{{$custom = FALSE;}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="{$col}" data-sortDirection='{$table->getSortDirection( $col )}'><a href="{$table->baseUrl->setQueryString( array( 'filter' => $table->filter, 'sortby' => $col, 'sortdirection' => $table->getSortDirection( $col ), 'page' => '1' ) )}" rel="nofollow">{lang="{$table->langPrefix}sort_{$k}"}</a></li>
							{{endforeach}}
							{{if $table->advancedSearch}}
								<li class="ipsMenu_item {{if $custom}}ipsMenu_itemChecked{{endif}}" data-noSelect="true">
									<a href='{$table->baseUrl->setQueryString( array( 'advancedSearchForm' => '1', 'filter' => $table->filter, 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection ) )}' data-ipsDialog data-ipsDialog-title='{lang="custom_sort"}' rel="nofollow">{lang="custom"}</a>
								</li>
							{{endif}}
						</ul>
					</li>
				{{endif}}
				{{if !empty( $table->filters )}}
					<li>
						<a href="#elFilterByMenu_menu" data-role="tableFilterMenu" id="elFilterByMenu_{$table->uniqueId}" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="filter_by"} <i class="fa fa-caret-down"></i></a>
						<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide' id='elFilterByMenu_{$table->uniqueId}_menu'>
							<li data-action="tableFilter" data-ipsMenuValue='' class='ipsMenu_item {{if !$table->filter}}ipsMenu_itemChecked{{endif}}'>
								<a href='{$table->baseUrl->setQueryString( array( 'filter' => '', 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection, 'page' => '1' ) )}' rel="nofollow">{lang="{$table->langPrefix}all"}</a>
							</li>
							{{foreach $table->filters as $k => $q}}
								<li data-action="tableFilter" data-ipsMenuValue='{$k}' class='ipsMenu_item {{if $k === $table->filter}}ipsMenu_itemChecked{{endif}}'>
									<a href='{$table->baseUrl->setQueryString( array( 'filter' => $k, 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection, 'page' => '1' ) )}' rel="nofollow">{lang="{$table->langPrefix}{$k}"}</a>
								</li>
							{{endforeach}}
						</ul>
					</li>
				{{endif}}
			</ul>
            {{if member.member_id}}
                <form action='{$table->baseUrl}' method='post'>
                    <input type='hidden' name='csrfKey' value='{expression="\IPS\Session::i()->csrfKey"}'>
                    <ul class='ipsButtonRow ipsPos_right ipsClearfix'>
                        <li>
                            <button type='submit' name='thumbnailSize' value='thumb' data-ipsTooltip title='{lang="view_as_thumbnails"}' class='ipsCursor_pointer{{if !isset( \IPS\Request::i()->cookie['thumbnailSize'] ) OR \IPS\Request::i()->cookie['thumbnailSize'] == 'thumb' }} ipsButtonRow_active{{endif}}'><i class='fa fa-th-large'></i></button>
                        </li>
                        <li>
                            <button type='submit' name='thumbnailSize' value='large' data-ipsTooltip title='{lang="view_as_large"}' class='ipsCursor_pointer{{if isset( \IPS\Request::i()->cookie['thumbnailSize'] ) AND \IPS\Request::i()->cookie['thumbnailSize'] == 'large' }} ipsButtonRow_active{{endif}}'><i class='fa fa-square'></i></button>
                        </li>
                        <li>
                            <button type='submit' name='thumbnailSize' value='rows' data-ipsTooltip title='{lang="view_as_list"}' class='ipsCursor_pointer{{if isset( \IPS\Request::i()->cookie['thumbnailSize'] ) AND \IPS\Request::i()->cookie['thumbnailSize'] == 'rows' }} ipsButtonRow_active{{endif}}'><i class='fa fa-th-list'></i></button>
                        </li>
                    </ul>
                </form>
            {{endif}}

			<div data-role="tablePagination" {{if $table->pages <= 1}}class='ipsHide'{{endif}}>
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
			</div>
		</div>
	{{endif}}

	{{if $table->canModerate()}}
		<form action="{$table->baseUrl->csrf()}" method="post" data-role='moderationTools' data-ipsPageAction class='ipsClear'>
	{{endif}}
	{{if !empty( $rows ) }}
		{{if isset( \IPS\Request::i()->cookie['thumbnailSize'] ) AND \IPS\Request::i()->cookie['thumbnailSize'] == 'large' AND \IPS\Request::i()->controller != 'search' }}
			<div class='ipsList_reset ipsClear ipsType_center cGalleryLargeList ipsAreaBackground_light ipsPad' id='elTable_{$table->uniqueId}' data-controller='gallery.front.browse.list' data-role='tableRows'>
				{template="tableRowsLarge" group="browse" app="gallery" params="$table, $headers, $rows"}
			</div>
		{{elseif isset( \IPS\Request::i()->cookie['thumbnailSize'] ) AND \IPS\Request::i()->cookie['thumbnailSize'] == 'rows' AND \IPS\Request::i()->controller != 'search' }}
			<div class='ipsDataList ipsList_reset ipsClear cGalleryRowsList' id='elTable_{$table->uniqueId}' data-role='tableRows'>
				{template="tableRowsRows" group="browse" app="gallery" params="$table, $headers, $rows"}
			</div>
		{{else}}
			<ul class='ipsPadding sm:ipsPadding:half iGalleryMasonry' data-controller='gallery.front.browse.list' id='elTable_{$table->uniqueId}' data-role='tableRows'>
				{template="tableRowsThumbs" group="browse" app="gallery" params="$table, $headers, $rows"}
			</ul>
		{{endif}}
	{{else}}
		<div class='ipsType_center ipsPad'>
			<p class='ipsType_large ipsType_light'>{lang="no_rows_in_table"}</p>
		</div>
	{{endif}}
	{{if $table->canModerate()}}
			<div class="ipsAreaBackground ipsPad ipsClearfix ipsJS_hide" data-role="pageActionOptions">
				<div class="ipsPos_right">
					<select name="modaction" data-role="moderationAction">
						{{if $table->canModerate('unhide')}}
							<option value='approve' data-icon='check-circle'>{lang="approve"}</option>
						{{endif}}
						{{if $table->canModerate('feature') or $table->canModerate('unfeature')}}
							<optgroup label="{lang="feature"}" data-icon='star' data-action='feature'>
								{{if $table->canModerate('feature')}}
									<option value='feature'>{lang="feature"}</option>
								{{endif}}
								{{if $table->canModerate('unhide')}}
									<option value='unfeature'>{lang="unfeature"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('pin') or $table->canModerate('unpin')}}
							<optgroup label="{lang="pin"}" data-icon='thumb-tack' data-action='pin'>
								{{if $table->canModerate('pin')}}
									<option value='pin'>{lang="pin"}</option>
								{{endif}}
								{{if $table->canModerate('unpin')}}
									<option value='unpin'>{lang="unpin"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('hide') or $table->canModerate('unhide')}}
							<optgroup label="{lang="hide"}" data-icon='eye' data-action='hide'>
								{{if $table->canModerate('hide')}}
									<option value='hide'>{lang="hide"}</option>
								{{endif}}
								{{if $table->canModerate('unhide')}}
									<option value='unhide'>{lang="unhide"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('lock') or $table->canModerate('unlock')}}
							<optgroup label="{lang="lock"}" data-icon='lock' data-action='lock'>
								{{if $table->canModerate('lock')}}
									<option value='lock'>{lang="lock"}</option>
								{{endif}}
								{{if $table->canModerate('unlock')}}
									<option value='unlock'>{lang="unlock"}</option>
								{{endif}}
							</optgroup>
						{{endif}}
						{{if $table->canModerate('move')}}
							<option value='move' data-icon='arrow-right'>{lang="move"}</option>
						{{endif}}
						{{if $table->canModerate('split_merge')}}
							<option value='merge' data-icon='level-up'>{lang="merge"}</option>
						{{endif}}
						{{if $table->canModerate('delete')}}
							<option value='delete' data-icon='trash'>{lang="delete"}</option>
						{{endif}}
						{{if $table->savedActions}}
							<optgroup label="{lang="saved_actions"}" data-icon='tasks' data-action='saved_actions'>
								{{foreach $table->savedActions as $k => $v}}
									<option value='savedAction-{$k}'>{$v}</option>
								{{endforeach}}
							</optgroup>
						{{endif}}
					</select>
					<button type="submit" class="ipsButton ipsButton_alternate ipsButton_verySmall">{lang="submit"}</button>
				</div>
			</div>
		</form>
	{{endif}}
	
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear {{if $table->pages <= 1}}ipsHide{{endif}}" data-role="tablePagination">
		{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
	</div>
</div>