<ips:template parameters="$table, $headers, $images" />
{{foreach $images as $image}}
	<div class='{{if $image->hidden()}}ipsModerated{{else}}ipsAreaBackground_reset{{endif}} ipsBox ipsPad ipsType_center cGalleryImageItem' data-imageId="{$image->id}" data-ipsLazyLoad>
		{{if $image->media }}
			<a data-imageLightbox href='{$image->url()}' title='{lang="view_this_video" sprintf="$image->caption"}' class='ipsThumb ipsNoThumb ipsNoThumb_video cGalleryNoThumb_full'>
				<video data-role="video" class="ipsPos_center" preload="metadata" width="100%" height="100%"{{if $image->masked_file_name }} poster="{file="$image->masked_file_name" extension="gallery_Images"}"{{endif}}>
					<source src="{file="$image->original_file_name" extension="gallery_Images"}" type='{$image->file_type}' />
				</video>
			</a>
		{{else}}
			<a data-imageLightbox href='{$image->url()}' title='{lang="view_this_image" sprintf="$image->caption"}'>
				{{$sizes = $image->_dimensions;}}
				{{if settings.lazy_load_enabled}}
					{{$ratio = round( ( $sizes['large'][1] / $sizes['large'][0] ) * 100, 2 );}}
					<img src="{expression="\IPS\Text\Parser::blankImage()"}" data-src='{file="$image->masked_file_name" extension="gallery_Images"}' width='{$sizes['large'][0]}' data-ratio='{$ratio}' alt="{$image->caption}" class='ipsImage'>
				{{else}}
					<img src='{file="$image->masked_file_name" extension="gallery_Images"}' width='{$sizes['large'][0]}' alt="{$image->caption}" class='ipsImage'>
				{{endif}}
			</a>
		{{endif}}
		<br>
		<h2 class='ipsType_sectionHead ipsType_normal'>
			{{if $image->unread()}}<span class='ipsItemStatus ipsItemStatus_small' data-ipsTooltip title='{{if $image->unread() === -1}}{lang="new"}{{else}}{lang="updated"}{{endif}}'><i class="fa fa-circle"></i></span>{{endif}}
			{{if $image->prefix()}}
				{template="prefix" group="global" app="core" params="$image->prefix( TRUE ), $image->prefix()"}
			{{endif}}
			<a data-imageLightbox href='{$image->url()}' title='{lang="view_this_image" sprintf="$image->caption"}'>
				{{if $image->unread()}}<strong>{$image->caption}</strong>{{else}}{$image->caption}{{endif}}
			</a>
			{{if $table->canModerate()}}
				<input type='checkbox' data-role='moderation' name="moderate[{$image->id}]" data-actions="{{if $image->mapped('featured')}}unfeature{{else}}feature{{endif}} {{if $image->mapped('pinned')}}unpin{{else}}pin{{endif}} {{if $image->hidden() === -1}}unhide{{elseif $image->hidden() === 1}}approve{{else}}hide{{endif}} {{if $image->mapped('locked')}}unlock{{else}}lock{{endif}} move delete" data-state='{{if $image->tableStates()}}{$image->tableStates()}{{endif}}'>
			{{endif}}
		</h2>
		<ul class='ipsList_inline'>
			{{if $image->directContainer()->allow_comments}}
				<li class='{{if $image->comments == 0}}ipsFaded{{endif}}' data-ipsTooltip title='{lang="num_comments" pluralize="$image->comments"}'><i class='fa fa-comment'></i> {$image->comments}</li>
			{{endif}}
			<li class='{{if $image->views == 0}}ipsFaded{{endif}}' data-ipsTooltip title='{lang="num_views_with_number" pluralize="$image->views"}'><i class='fa fa-eye'></i> {$image->views}</li>
		</ul>
		{{if $image->mapped('pinned') || $image->mapped('featured') || $image->hidden() === -1 || $image->hidden() === 1}}
			<br>
			<ul class='ipsList_inline'>
				<li>
					{{if $image->hidden() === -1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$image->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
					{{elseif $image->hidden() === 1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
					{{endif}}							
					{{if $image->mapped('pinned')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
					{{endif}}
					{{if $image->mapped('featured')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
					{{endif}}
				</li>
			</ul>
		{{endif}}
	</div>
{{endforeach}}
