<ips:template parameters="$table, $headers, $images" />
{{foreach $images as $image}}
	<div class='{{if $image->hidden()}}ipsModerated{{endif}} ipsPadding ipsPadding_bottom:double cGalleryImageItem' data-imageId="{$image->id}">
		<div class='ipsImageBlock'>
			{{if $image->media }}
				<a href='{$image->url()}' title='{lang="view_this_video" sprintf="$image->caption"}' class='ipsImageBlock__main'>
					<video data-role="video" loading="lazy" {{if $image->masked_file_name }} poster="{file="$image->masked_file_name" extension="gallery_Images"}"{{else}} preload="metadata"{{endif}}>
						<source src="{file="$image->original_file_name" extension="gallery_Images"}" type='{$image->file_type}' />
					</video>
				</a>
			{{else}}
				<a href='{$image->url()}' title='{lang="view_this_image" sprintf="$image->caption"}' class='ipsImageBlock__main'>
					{{$sizes = $image->_dimensions;}}
					<img src='{file="$image->masked_file_name" extension="gallery_Images"}' width="{$sizes['large'][0]}" height="{$sizes['large'][1]}" alt="{$image->caption}" loading="lazy">
				</a>
			{{endif}}
            {template="nsfwOverlay" app="gallery" location="front" group="global" params="$image"}
        </div>
		<div class='ipsMargin_top:half'>
			<div class='ipsFlex ipsFlex-fw:wrap ipsFlex-ai:center ipsFlex-jc:between'>
				<div class='ipsFlex ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:2'>
					{{if $image->mapped('pinned') || $image->mapped('featured') || $image->hidden() === -1 || $image->hidden() === 1}}
						<ul class='ipsList_inline'>
							<li>
								{{if $image->hidden() === -1}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$image->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
								{{elseif $image->hidden() === 1}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
								{{endif}}							
								{{if $image->mapped('pinned')}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
								{{endif}}
								{{if $image->mapped('featured')}}
									<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
								{{endif}}
							</li>
						</ul>
					{{endif}}
					<h2 class='ipsType_sectionHead ipsType_large'>
						{{if $image->unread()}}<span class='ipsItemStatus ipsItemStatus_small' data-ipsTooltip title='{{if $image->unread() === -1}}{lang="new"}{{else}}{lang="updated"}{{endif}}'><i class="fa fa-circle"></i></span>{{endif}}
						{{if $image->prefix()}}
							{template="prefix" group="global" app="core" params="$image->prefix( TRUE ), $image->prefix()"}
						{{endif}}
						<a href='{$image->url()}' title='{lang="view_this_image" sprintf="$image->caption"}'>
							{{if $image->unread()}}<strong>{$image->caption}</strong>{{else}}{$image->caption}{{endif}}
						</a>
					</h2>
				</div>
				<div class='ipsFlex ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:2'>
					<ul class='ipsList_inline'>
						{{if $image->directContainer()->allow_comments}}
							<li class='{{if $image->comments == 0}}ipsFaded{{endif}}'>{lang="num_comments" pluralize="$image->comments"}</li>
						{{endif}}
						<li class='{{if $image->views == 0}}ipsFaded{{endif}}'>{lang="num_views_with_number" pluralize="$image->views"}</li>
						{{if $table->canModerate()}}
							<li>
								<input type='checkbox' data-role='moderation' name="moderate[{$image->id}]" data-actions="{{if $image->mapped('featured')}}unfeature{{else}}feature{{endif}} {{if $image->mapped('pinned')}}unpin{{else}}pin{{endif}} {{if $image->hidden() === -1}}unhide{{elseif $image->hidden() === 1}}approve{{else}}hide{{endif}} {{if $image->mapped('locked')}}unlock{{else}}lock{{endif}} move delete" data-state='{{if $image->tableStates()}}{$image->tableStates()}{{endif}}'>
							</li>
						{{endif}}
					</ul>
				</div>
			</div>
		</div>
	</div>
{{endforeach}}
