<ips:template parameters="$select, $pagination, $members, $total" />

<div class="acpBlock">
<h1 class="ipsBox_titleBar">{lang="gallery_stats_uploader_count" pluralize="$total"}</h1></div>
<br>
{{if trim( $pagination )}}
	{$pagination|raw}
	<br><br>
{{endif}}
	<table class="ipsTable ipsTable_zebra acpBlock">
		<thead>
			<tr>
				<th>{lang="member"}</th>
				<th>{lang="gallery_images"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $select as $row}}
				{{if isset( $members[ $row['image_member_id'] ] )}}
					{{$member = \IPS\Member::constructFromData( $members[ $row['image_member_id'] ] );}}
				{{else}}
					{{$member = new \IPS\Member;}}
				{{endif}}
				<tr>
					<td>{template="userPhoto" app="core" group="global" params="$member"} {$member->name}</td>
					<td><a href='{$member->url()->setQueryString( array( 'do' => 'content', 'type' => 'gallery_image' ) )}' target='_blank' rel='noopener'>{$row['images']}</a></td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>
	<br>

	{$pagination|raw}