<ips:template parameters="$albums, $title, $orientation='vertical'" />
{{if !empty( $albums ) }}
	<h3 class='ipsType_reset ipsWidget_title'>{$title}</h3>
		{{if $orientation == 'horizontal'}}
			<div class='ipsWidget_inner ipsPad ipsType_center' {{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
				<div class='ipsCarousel cGalleryCarouselWidget ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<div class='ipsCarousel_inner'>
						<ul class='ipsGrid ipsGrid_collapsePhone' data-role="carouselItems">
		{{else}}
			<div class='ipsWidget_inner'>
				<div class='ipsPad_half'>
					<ul class='cGalleryCats cGalleryWidgetList' {{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
        {{endif}}

		{{foreach $albums as $album}}
			<li class='{{if $orientation == "horizontal"}}ipsCarousel_item{{endif}} cGalleryCat cGalleryWidget cGalleryWidget_album'>
				<div class='ipsImageBlock'>
					<a href='{$album->url()}' class='ipsImageBlock__main'>
						{{if $album->asNode()->coverPhoto('masked')}}
							<img src="{$album->asNode()->coverPhoto('masked')}" alt="{$album->name}" loading="lazy">
						{{endif}}
					</a>
                    {template="nsfwOverlay" app="gallery" location="front" group="global" params="$album->asNode()->coverPhotoObject()"}
				</div>
				<h2 class='cGalleryCats__name'>
					<a href='{$album->url()}'>{$album->name}</a>
				</h2>
				<ul class='cGalleryCats__stats'>
					<li>
						<span>{lang="byline" sprintf="$album->author()->name"}</span>
						{datetime="$album->mapped('updated')"}
					</li>
				</ul>
				<ul class='cGalleryCats__stats'>
					{{if $album->use_comments}}
						<li data-ipsTooltip title='{lang="num_comments" pluralize="$album->comments"}'><i class='fa fa-comment'></i> {$album->comments}</li>
					{{endif}}
					{{if $album->allow_comments}}
						<li data-ipsTooltip title='{lang="gallery_image_comments_s" pluralize="$album->count_comments"}'><i class='fa fa-comments-o'></i> {$album->count_comments}</li>
					{{endif}}
					<li data-ipsTooltip title='{lang="cat_img_count" pluralize="$album->count_imgs"}'><i class='fa fa-camera'></i> {$album->count_imgs}</li>
				</ul>
			</li>
		{{endforeach}}

		{{if $orientation == 'vertical'}}
					</ul>
				</div>
		{{else}}
						</ul>
					</div>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
		{{endif}}
			</div>
{{endif}}