<ips:template parameters="$stats, $latestImage, $orientation='vertical'" />
<h3 class='ipsType_reset ipsWidget_title'>{lang="block_galleryStats"}</h3>
<div class='ipsWidget_inner'>
	{{if $orientation == 'vertical'}}
		<div class='ipsPad_half'>		
			<ul class='ipsDataList' id='elGalleryStats'>
				<li class='ipsDataItem'>
					<div class='ipsDataItem_main ipsPos_middle'>
						<strong>{lang="total_images_front_v" pluralize="$stats['totalImages']"}</strong>
					</div>
					<div class='ipsDataItem_stats ipsDataItem_statsLarge'>
						<span class='ipsDataItem_stats_number'>{number="$stats['totalImages']"}</span>
					</div>
				</li>
				{{if $stats['totalComments']}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main ipsPos_middle'>
							<strong>{lang="stats_total_comments_v" pluralize="$stats['totalComments']"}</strong>
						</div>
						<div class='ipsDataItem_stats ipsDataItem_statsLarge'>
							<span class='ipsDataItem_stats_number'>{number="$stats['totalComments']"}</span>
						</div>
					</li>
				{{endif}}
				{{if $stats['totalAlbums']}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main ipsPos_middle'>
							<strong>{lang="total_albums_v" pluralize="$stats['totalAlbums']"}</strong>
						</div>
						<div class='ipsDataItem_stats ipsDataItem_statsLarge'>
							<span class='ipsDataItem_stats_number'>{number="$stats['totalAlbums']"}</span>
						</div>
					</li>
				{{endif}}
			</ul>
			{{if $latestImage}}
				<hr class='ipsHr'>
				{template="latestImage" group="widgets" app="gallery" params="$latestImage, $orientation"}
			{{endif}}
		</div>
	{{else}}
		{{$columns = 1;}}
		{{$columns += ( $stats['totalComments'] ) ? 1 : 0;}}
		{{$columns += ( $stats['totalAlbums'] ) ? 1 : 0;}}
		{{$span = 12 / $columns;}}
		<div class='ipsGrid ipsGrid_collapsePhone ipsWidget_stats'>
			<div class='ipsGrid_span{$span} ipsType_center'>
				<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['totalImages']"}</span><br>
				<span class='ipsType_light ipsType_medium'>{lang="total_images_front_h" pluralize="$stats['totalImages']"}</span>
			</div>
			{{if $stats['totalComments']}}
				<div class='ipsGrid_span{$span} ipsType_center'>
					<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['totalComments']"}</span><br>
					<span class='ipsType_light ipsType_medium'>{lang="stats_total_comments_h" pluralize="$stats['totalComments']"}</span>
				</div>
			{{endif}}
			{{if $stats['totalAlbums']}}
				<div class='ipsGrid_span{$span} ipsType_center'>
					<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['totalAlbums']"}</span><br>
					<span class='ipsType_light ipsType_medium'>{lang="total_albums_h" pluralize="$stats['totalAlbums']"}</span>
				</div>
			{{endif}}
		</div>
	{{endif}}
</div>