<ips:template parameters="$image, $orientation='vertical'" />
<li class='cGalleryWidget {{if $orientation != 'vertical'}}ipsCarousel_item{{endif}}'>
	<div class='ipsImageBlock'>
		{{if $image->small_file_name}}
			<a href='{$image->url()->setQueryString( 'context', 'widget' )}' title='{lang="view_this_image" sprintf="$image->caption"}' class='ipsImageBlock__main'>
				<img src='{file="$image->small_file_name" extension="gallery_Images"}' alt="{$image->caption}" loading="lazy">
			</a>
		{{else}}
			<a href='{$image->url()->setQueryString( 'context', 'widget' )}' title='{lang="view_this_video" sprintf="$image->caption"}' class='ipsImageBlock__main'>

			</a>
		{{endif}}
		{{if $image->directContainer()->allow_comments && $image->comments}}
			<div class='ipsImageBlock__footer'>
				<div class="cGalleryWidget_comments" data-ipsTooltip title='{lang="num_comments" pluralize="$image->comments"}'>
					<i class='fa fa-comment'></i> {$image->comments}
				</div>
			</div>
		{{endif}}
        {template="nsfwOverlay" app="gallery" location="front" group="global" params="$image, FALSE"}
	</div>	
	<div class='ipsMargin_top:half cGalleryWidgetInfo'>
			<div class='ipsTruncate ipsTruncate_line ipsType_bold'>
				<a href="{$image->url()}" title='{lang="view_this_image" sprintf="$image->caption"}'>
					{$image->caption}
				</a>
			</div>
		<span class='ipsType_medium ipsType_blendLinks ipsTruncate ipsTruncate_line'>
			{lang="byline" htmlsprintf="$image->author()->link()"}
			{datetime="$image->mapped('date')"}
		</span>
	</div>
</li>