<ips:template parameters="$latestImage, $orientation='vertical'" />
<div id='elGalleryStatsLatest' class='ipsClearfix cGalleryWidget' {{if settings.gallery_nsfw}}data-controller="gallery.front.global.nsfw"{{endif}}>
	<div class='ipsMargin_bottom:half'>
		<strong class='ipsType_minorHeading'>{lang="latest_image"}</strong>
	</div>
	<div class='ipsImageBlock'>
		{{if $latestImage->small_file_name}}
			<a href='{$latestImage->url()}' title='{lang="view_this_image" sprintf="$latestImage->caption"}' class='ipsImageBlock__main'>
				<img src='{file="$latestImage->small_file_name" extension="gallery_Images"}' alt="{$latestImage->caption}" loading="lazy">
			</a>
		{{else}}
			<a href='{$latestImage->url()}' title='{lang="view_this_video" sprintf="$latestImage->caption"}' class='ipsImageBlock__main'>
				
			</a>
			<div class='ipsImageBlock__video-icon'></div>
		{{endif}}
		{{if $latestImage->directContainer()->allow_comments && $latestImage->comments > 0}}
			<div class='ipsImageBlock__footer'>
				<div data-ipsTooltip title='{lang="num_comments" pluralize="$latestImage->comments"}'>
					<i class='fa fa-comment'></i> {$latestImage->comments}
				</div>
			</div>
		{{endif}}
		{template="nsfwOverlay" app="gallery" location="front" group="global" params="$latestImage"}
	</div>
	
	<div class='ipsSpacer_top ipsSpacer_half cGalleryWidgetInfo'>
		<div class='ipsTruncate ipsTruncate_line ipsType_semiBold'>
			<a href="{$latestImage->url()}" title='{lang="view_this_image" sprintf="$latestImage->caption"}'>
				{$latestImage->caption}
			</a>
		</div>
		<span class='ipsType_light ipsType_blendLinks'>
			{lang="byline" htmlsprintf="$latestImage->author()->link()"}
			{datetime="$latestImage->mapped('date')"}
		</span>
	</div>
</div>
