<ips:template parameters="$comments, $title, $orientation='vertical'" />
{{if !empty( $comments ) }}
	<h3 class='ipsType_reset ipsWidget_title'>{$title}</h3>
	<div class='ipsPad_half ipsWidget_inner'>
		<ul class='ipsDataList ipsDataList_reducedSpacing'>
			{{foreach $comments as $comment}}
				<li class='ipsDataItem'>
					<div class='ipsDataItem_icon ipsPos_top'>
						{template="thumbImage" group="global" app="core" params="$comment->item()->small_file_name, $comment->item()->caption, 'tiny', '', 'view_this', '', 'gallery_Images'"}
					</div>
					<div class='ipsDataItem_main'>
						<div class='ipsContained ipsType_break'><a href="{$comment->url()}" title='{lang="view_this_image" sprintf="$comment->item()->caption"}' class='ipsType_medium ipsTruncate ipsTruncate_line'>{$comment->item()->caption}</a></div>
						<p class='ipsType_reset ipsType_light ipsType_medium ipsType_blendLinks'>{lang="byline_nodate" htmlsprintf="$comment->author()->link()"} &middot; <a href="{$comment->url()}" class='ipsDataItem_title ipsType_break ipsType_blendLinks'>{$comment->dateLine()|raw}</a></p>
						<div class='ipsType_richText ipsType_medium ipsSpacer_top ipsSpacer_half ipsType_break' data-ipsTruncate data-ipsTruncate-type="remove" data-ipsTruncate-size="2 lines">
							{$comment->truncated()|raw}
						</div>
					</div>
				</li>
			{{endforeach}}
		</ul>
	</div>
{{endif}}