<ips:template parameters="$element" />
<div data-role="filterField" class='cRulesForm_conditionWrap' id="{$element->htmlId}_filter" style='display: none;'>
	<div class="cRulesForm__condition cRulesForm__condition--subCondition ipsBox ipsBox_shadowed ipsPos_relative ipsPadding ipsMargin_top ipsFlex ipsFlex-ai:start sm:ipsFlex-fd:column">
		<h2 class='cRulesForm__condition__title ipsRadius ipsType_center ipsType_medium ipsType_semiBold ipsType_veryLight ipsMargin_vertical:none ipsMargin_right sm:ipsMargin_bottom ipsFlex-flex:00'>{lang="achievement_filter"}</h2>
		<div class='ipsFlex ipsFlex-ai:center ipsFlex-flex:11 ipsGap:2 ipsGap_row:0'>
			<div>{$element->prefix}</div>
			<div>{$element->html()|raw}</div>
			<button type="button" data-action="filterCollapse" data-filter="{$element->htmlId}_filterCheckbox" data-ipsTooltip title='{lang="remove_condition"}' class='cRulesForm__condition__close ipsClose ipsClose_small'></button>
		</div>
	</div>
</div>