<ips:template parameters="$rules, $pagination, $rootButtons" />
<div data-baseurl="{url="app=core&module=achievements&controller=rules"}" data-controller="core.global.core.table">
	<!--<div class="ipsBox ipsBox_shadowed ipsPad ipsSpacer_bottom ipsClearfix">
		<ul class="ipsList_inline">
			<li><strong>{lang="achievement_rules_filters"}</strong></li>
			{{foreach [ 'points', 'badges', 'milestone' ] as $filter}}
				<li>
					<span class="ipsCustomInput">
						<input type="checkbox" id="filter_{$filter}" name="filter_{$filter}" data-action="filter" checked>
						<span></span>
					</span>
					<label for="filter_{$filter}">{lang="achievement_rules_filters_{$filter}"}</label>
				</li>
			{{endforeach}}
		</ul>
	</div>-->
	{{if $data = \IPS\core\Achievements\Rule::getRebuildProgress()}}
		{template="rebuildProgress" group="achievements" params="$data"}
	{{endif}}
	<div class='ipsClearfix'>
		<div data-role="tablePagination" class="ipsSpacer_bottom {{if !$pagination}}ipsHide{{endif}}">{$pagination|raw}</div>
		{template="buttons" params="$rootButtons" group="global" app="core"}
	</div>
	<div class="acpBlock">
		<div class="ipsTree_wrapper">
            {{if empty( $rules )}}
            <div class='ipsType_light ipsPad'>
                {lang="no_results"}
            </div>
            {{else}}
			<div class="ipsTree_rows">
				<ol class="ipsTree" data-role="tableRows">
					{template="rulesListRows" group="achievements" params="$rules"}
				</ol>
			</div>
            {{endif}}
		</div>
	</div>
	<div data-role="tablePagination" class='ipsSpacer_top {{if !$pagination}}ipsHide{{endif}}'>{$pagination|raw}</div>
</div>