<ips:template parameters="$form, $blog=NULL" />

{{if $blog and $club = $blog->club()}}
	{{if settings.clubs and settings.clubs_header == 'full'}}
		{template="header" app="core" group="clubs" params="$club, $blog"}
	{{endif}}
	<div id='elClubContainer'>
{{endif}}

{template="pageHeader" if="!\IPS\Request::i()->isAjax()" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( 'create_blog_entry' )"}
{$form|raw}

{{if $blog and $blog->club()}}
	</div>
{{endif}}