<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
<div class='ipsBox{{if \count( $elements ) <= 1}} ipsPadding{{endif}}'>
	<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm data-ipsFormSubmit>
		<input type="hidden" name="{$id}_submitted" value="1">
		{{foreach $hiddenValues as $k => $v}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endforeach}}
		{{if $uploadField}}
			<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
			<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
		{{endif}}
		{{if \count( $elements ) > 1}}
			<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="entry_information"}</h2>
			<div class='ipsTabs ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
				<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
				<ul role='tablist'>
					{{foreach $elements as $name => $content}}
						<li>
							<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item" role="tab">
								{lang="$name"}
							</a>
						</li>
					{{endforeach}}
				</ul>
			</div>
			<div id='ipsTabs_content_{$id}' class='ipsTabs_panels'>
				{{foreach $elements as $name => $contents}}
					<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
						<ul class='ipsForm ipsForm_vertical'>
							{{foreach $contents as $inputName => $input}}
								{$input|raw}
							{{endforeach}}
						</ul>
					</div>
				{{endforeach}}
			</div>		
		{{else}}
			<ul class='ipsForm ipsForm_vertical'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $inputName => $input}}
						{$input|raw}
					{{endforeach}}
				{{endforeach}}
			</ul>
		{{endif}}

		<div class='ipsAreaBackground_reset ipsBorder_top ipsPadding ipsType_center ipsSpacer_top'>
			<button type='submit' class='ipsButton ipsButton_large ipsButton_primary'>{lang="entry_submit"}</button>
		</div>
	</form>
</div>