<ips:template parameters="$error, $url, $errorMessage" />
{{if $errorMessage}}
	<p class="ipsMessage ipsMessage_error">{lang="api_instructions_error" sprintf="(string)$url"}
		<br>
		{lang="api_returned_error" sprintf="$errorMessage"}
	</p>
{{endif}}
{lang="api_instructions_intro"}
<ol>
	<li>{lang="api_instructions_1"}</li>
	<li>{lang="api_instructions_2" sprintf="\IPS\ROOT_PATH"}</li>
	<li>{lang="api_instructions_3"}</li>
</ol>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	<a href="{url="app=core&module=applications&controller=api&tab=apiLogs&recheck=1"}" class="ipsButton ipsButton_primary">{lang="continue"}</a>
</div>