<ips:template parameters="$name, $value, $required, $options, $multiple=FALSE, $class='', $disabled=FALSE, $toggles=array(), $id=NULL, $unlimited=NULL, $unlimitedLang='all', $unlimitedToggles=array(), $toggleOn=TRUE, $descriptions=array(), $impliedUnlimited=FALSE" />
{{if $multiple}}
<input type="hidden" name="{$name}[__EMPTY]" value="__EMPTY">
{{endif}}
<div data-control="granularCheckboxset" data-count="{expression="\count( $options )"}">
{{if $unlimited !== NULL AND $impliedUnlimited === FALSE}}
<div data-role="checkboxsetUnlimited" class="{{if !\is_array( $value )}}ipsJS_show{{else}}ipsHide{{endif}}">
	<input
		type='checkbox'
		name="{expression="trim( $name, '[]' )"}_unlimited"
	value='{$unlimited}'
	id="{expression="trim( $id ?: $name, '[]' )"}_unlimited"
	{{if $unlimited === $value}}checked aria-checked='true'{{else}}aria-checked='false'{{endif}}
	{{if $disabled}}disabled aria-disabled='true'{{endif}}
	data-ipsToggle
	data-role="checkboxsetUnlimitedToggle"
	>
	&nbsp;
	{lang="or"}
	&nbsp;
	<a class="ipsCursor_pointer" data-action="checkboxsetCustomize">{lang="customize"}</a>
</div>
{{endif}}
<div data-role="checkboxsetGranular" class="ipsField__checkboxOverflow {{if $unlimited !== NULL AND $impliedUnlimited === FALSE and !\is_array( $value )}}ipsJS_hide{{endif}}">

	<div class="ipsGrid">
		{{foreach $options as $k => $v}}
        <div class='ipsGrid_span3'>Span 3</div>

					<span class='ipsCustomInput'>
						<input type="checkbox" {{if $class}}class="{$class}"{{endif}} name="{$name}[{$k}]" value="1" {{if ( $unlimited !== NULL AND $unlimited === $value ) or ( \is_array( $value ) AND \in_array( $k, $value ) )}}checked{{endif}} {{if $disabled === TRUE or ( \is_array( $disabled ) and \in_array( $k, $disabled ) )}}disabled{{endif}} {{if isset( $toggles[ $k ] ) and !empty( $toggles[ $k ] )}}data-control="toggle" {{if $toggleOn === FALSE}}data-togglesOff{{else}}data-togglesOn{{endif}}="{expression="implode( ',', $toggles[ $k ] )"}"{{endif}} id="elCheckbox_{$name}_{$k}">
						<span></span>
					</span>
			<div class='ipsField_fieldList_content'>
				<label for='elCheckbox_{$name}_{$k}' id='elField_{$name}_label' data-role="label">{$v|raw}</label>
				{{if isset( $descriptions[ $k ] )}}
				<br>
				<span class='ipsFieldRow_desc'>
								{$descriptions[ $k ]|raw}
							</span>
				{{endif}}
			</div>
        </div>>
		{{endforeach}}
	</div>

	<div class="ipsSpacer_top ipsSpacer_half ipsJS_show ipsField__checkboxOverflow__toggles" data-role="massToggles">
		{lang="or"}
		&nbsp;
		<a class="ipsCursor_pointer" data-action="checkboxsetAll">{lang="all"}</a> / <a class="ipsCursor_pointer" data-action="checkboxsetNone">{lang="none"}</a>
	</div>
</div>
</div>