<ips:template parameters="$apiKey" />
<p class="ipsType_normal">{lang="zapier_setup_intro"}</p>
<div class="ipsBox">
	<ul class="ipsForm ipsForm_horizontal">
		<li class="ipsFieldRow ipsFieldRow_yesNo ">
			<div class="ipsFieldRow_title">
				{lang="zapier_community_url"}
			</div>
			<div class="ipsFieldRow_content ipsClearfix" data-ipscopy>
				<code class=" prettyprint prettyprinted" data-role="copyTarget">{expression="rtrim( \IPS\Settings::i()->base_url, '/' )"}/</code>
                <button type="button" class="ipsButton ipsButton_light ipsButton_veryVerySmall ipsPos_right" data-role="copyButton" data-clipboard-text="{expression="rtrim( \IPS\Settings::i()->base_url, '/' )"}">{lang="copy"}</button>
            </div>
		</li>

		<li class="ipsFieldRow ipsFieldRow_yesNo ">
			<div class="ipsFieldRow_title">
				{lang="api_id"}
			</div>
			<div class="ipsFieldRow_content ipsClearfix" data-ipscopy>
				<code class=" prettyprint prettyprinted" data-role="copyTarget" >{$apiKey->id}</code>
                <button type="button" class="ipsButton ipsButton_light ipsButton_veryVerySmall ipsPos_right" data-role="copyButton" data-clipboard-text="{$apiKey->id}">{lang="copy"}</button>
            </div>
		</li>
	</ul>
	<hr class="ipsHr_thick">
	<div class="ipsBox ipsPad">
		<script type="module" src="https://zapier.com/partner/embed/app-directory/wrapper.js?app=invision-community&link-target=new-tab&theme=auto&applimit=5&zaplimit=6&zapstyle=card&introcopy=hide"></script>
	</div>

</div>
