<ips:template parameters="$apiKey" />
<p class="ipsType_normal">{lang="zapier_setup_intro"}</p>
<div class="ipsBox">
	<ul class="ipsForm ipsForm_horizontal">
		<li class="ipsFieldRow ipsPad_half">
			<div class="ipsFieldRow_title">
				{lang="zapier_community_url"}
			</div>
			<div class="ipsFieldRow_content">
				<pre>{expression="rtrim( \IPS\Settings::i()->base_url, '/' )"}/</pre>
			</div>
		</li>
		<li class="ipsFieldRow ipsPad_half">
			<div class="ipsFieldRow_title">
				{lang="api_id"}
			</div>
			<div class="ipsFieldRow_content">
				<pre>{$apiKey->id}</pre>
			</div>
		</li>
	</ul>
</div>