<ips:template parameters="$calendars, $date, $featured, $events, $thisCalendar, $months=array()" />
<section class='ipsBox' data-controller="calendar.front.overview.eventList">
	<h2 class='ipsType_sectionTitle'>{lang="events_browse_by_month"}</h2>
	<div class='ipsPadding ipsAreaBackground_light ipsRadius:bl ipsRadius:br'>
		<div class='cEvents__monthNav' data-role='monthNav'>
			{{foreach $months as $monthObj }}
				<a class='cEvents__monthNav__monthItem {{if $monthObj->format( 'n' ) == $date->mon}}cEvents__monthNav__monthItem--active{{endif}}' href="{{if $thisCalendar}}{url="app=calendar&module=calendar&controller=view&id={$thisCalendar->_id}&y={$monthObj->format( 'Y' )}&m={$monthObj->format( 'n' )}"}{{else}}{url="app=calendar&module=calendar&controller=view&y={$monthObj->format( 'Y' )}&m={$monthObj->format( 'n' )}"}{{endif}}" rel='nofollow' data-action='changeMonth' data-month='{$monthObj->format( 'n' )}' data-year='{$monthObj->format( 'Y' )}'>
                <span class='cEvents__monthNav__month'>{lang="_date_month_short" pluralize="$monthObj->format( 'n' )"}</span>
					<span class='cEvents__monthNav__year'>{$monthObj->format( 'Y' )}</span>
				</a>
			{{endforeach}}
		</div>

		<div class='ipsMargin_top'>
			{{if \count($events) }}
				<ul class='eventList' data-role='eventList'>
					{{foreach $events as $event}}
						{template="event" app="calendar" group="events" params="$event, 'normal', \IPS\calendar\Date::getDate( $date->firstDayOfMonth('year'), $date->firstDayOfMonth('mon'), $date->firstDayOfMonth('mday') )"}
					{{endforeach}}
				</ul>
				<div class='ipsPadding_top ipsType_center'>
					<button class='ipsButton ipsButton_light ipsButton_normal {{if \count( $events ) < 16}}ipsHide{{endif}}' data-action='loadMore'>{lang="events_show_more"}</button>
					<p class='ipsType_center ipsType_normal ipsType_light {{if \count( $events ) >= 16}}ipsHide{{endif}}' data-role='noMoreResults'>{lang="events_no_more_this_month"}</p>
				</div>
			{{else}}
                <ul class='eventList' data-role='eventList'>
                    {template="noEvents" app="calendar" group="events"}
                </ul>
			{{endif}}
		</div>
	</div>
</section>