<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar='', $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class} ipsFlex-flex:11" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-controller='calendar.front.overview.search'{{if \IPS\GeoLocation::enabled()}} data-placeholder='{$elements['']['location']->options['placeholder']}'{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
	{{if \is_array($v)}}
	{{foreach $v as $_k => $_v}}
	<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
	{{endforeach}}
	{{else}}
	<input type="hidden" name="{$k}" value="{$v}">
	{{endif}}
	{{endforeach}}

	{{$byLocation = FALSE;}}
	{{if isset( \IPS\Request::i()->lat ) && isset( \IPS\Request::i()->lon )}}
	<input type='hidden' name='lat' value='{request="lat"}'>
	<input type='hidden' name='lon' value='{request="lon"}'>
	{{endif}}

	{{if isset( \IPS\Request::i()->searchNearLocation )}}
	<input type='hidden' name='searchNearLocation' value='1'>
	{{$byLocation = TRUE;}}
	{{endif}}

	<ul class='ipsList_reset cEvents__search'>
		{{foreach $elements[''] as $key => $input}}
		{{if $key === 'location'}}
		<li class='cEvents__search__field cEvents__search__field--location'>
			<label class='cEvents__search__label'>{lang="events_search_location"}</label>
			<div class='cEvents__search__searchWrap'>
				{{if $byLocation}}
				{{$input->options['placeholder'] = \IPS\Member::loggedIn()->language()->addToStack( "events_search_your_location" );}}
				{{$input->options['disabled'] = TRUE;}}
				{$input->html()|raw}
				<a href='#' class='eventSearch__searchLocation ipsJS_show ipsHide' data-action='useMyLocation'><i class='fa fa-crosshairs'></i> <span>{lang="events_search_use_location"}</span></a>
				<a href='#' class='eventSearch__searchLocation ipsJS_show' data-action='cancelLocation'><span>{lang="events_search_cancel_location"}</span></a>
				{{else}}
				{$input->html()|raw}
				<a href='#' class='eventSearch__searchLocation ipsJS_show' data-action='useMyLocation'><i class='fa fa-crosshairs'></i> <span>{lang="events_search_use_location"}</span></a>
				<a href='#' class='eventSearch__searchLocation ipsJS_show ipsHide' data-action='cancelLocation'><span>{lang="events_search_cancel_location"}</span></a>
				{{endif}}
			</div>
		</li>
		{{elseif $key === 'show'}}
		<li class='cEvents__search__field cEvents__search__field--show'>
			<label class='cEvents__search__label'>{lang="events_search_type"}</label>
			{$input->html()|raw}
		</li>
		{{elseif $key === 'date'}}
		<li class='cEvents__search__field cEvents__search__field--date cEvents__search__field--from'>
			<label class='cEvents__search__label'>{lang="events_search_from"}</label>
			{$input->start->html()|raw}
		</li>
		<li class='cEvents__search__field cEvents__search__field--date cEvents__search__field--to'>
			<label class='cEvents__search__label'>{lang="events_search_to"}</label>
			{$input->end->html()|raw}
		</li>
		{{endif}}
		{{endforeach}}
		<li class='cEvents__search__field cEvents__search__field--submit'>
			<button type='submit' class='ipsButton ipsButton_primary ipsButton_medium ipsButton_fullWidth cEvents__search__Submit'>{lang="events_search_search"}</button>
		</li>
	</ul>
</form>