<ips:template parameters="$featured, $nearme, $stream, $searchForm, $mapMarkers, $online, $date, $downloadLinks" />

<div data-role='eventsPage' class='eventsPage'>
	{template="header" group="overview" app="calendar" params="$date, NULL, $downloadLinks"}

	<div class='cEvents__overview-header'>
		{{if \count( $featured )}}
			{template="featured" group="events" app="calendar" params="$featured"}
		{{endif}}
		<div class='ipsBox {{if \count( $featured )}}ipsFlex ipsFlex-fd:column{{endif}}'>
			<h2 class="ipsType_sectionTitle ipsType_reset">{lang="events_search_events"}</h2>
			<div class='ipsPadding {{if \count( $featured )}}ipsFlex-flex:11 ipsFlex ipsFlex-ai:center{{endif}}'>
				<div class='ipsFlex-flex:11 eventSearch {{if \count( $featured )}}eventSearch--vertical{{else}}eventSearch--horizontal{{endif}}'>
					{$searchForm->customTemplate( array( \IPS\Theme::i()->getTemplate( 'overview', 'calendar' ), 'searchBar' ) )|raw}
				</div>
			</div>
		</div>
	</div>

	<div data-role='eventsOverview'>
        {{if \IPS\GeoLocation::enabled() }}
		    {template="nearMe" group="events" app="calendar" params="$nearme, $mapMarkers"}
        {{endif}}
		{template="online" group="events" app="calendar" params="$online"}

		{$stream|raw}
	</div>

	<div data-role='searchResultsWrapper' class='ipsHide'>
		{template="searchResultsWrapper" group="events" app="calendar" params=""}
	</div>
</div>