<?php

$lang = array(
		'__app_blog'					=> "Blogs",
		'frontnavigation_blogs'			=> "Blogs",
		'__indefart_blog_entry_comment'	=> "a comment on a blog entry",
		'__indefart_blog_entry'			=> "a blog entry",
		'__defart_blog_entry_comment'	=> "comment on a blog entry",
		'__defart_blog_entry_comment_plural' => "{!#[1:comment][?:comments]} on a blog entry",
		'__defart_blog_entry'			=> "blog entry",
		'__defart_blog_entry_plural'	=> "{!#[1:blog entry][?:blog entries]}",
		'blog_entry_container'			=> "blog",
		'blog_entry_pl_lc'				=> "blog entries",
		
		/* !ACP */
		
		'module__blog_blogs'			=> "Blogs",
		
		'menu__blog_blogs'				=> "Blogs",
		'menu__blog_blogs_settings'		=> "Settings",
		'menu__blog_blogs_blogs'		=> "Blogs",
		'acp_search_title_blog_Blogs'	=> "Blogs",
		'acplog__entries_published'		=> "Automatically published blog entries (%s published)",
		'filestorage__blog_Entries'		=> "Blog Entries",
		
		'add_blog'						=> "Add Blog",
		
		'block_blog_Overview'			=> "Blog Overview",
		
		'editor__blog_Blogs'			=> "Blogs",
		'editor__blog_Entries'			=> "Blog Entries",
		'editor__blog_Categories'       => "Blog Categories",

		'task__blogrssimport'			=> "Checks RSS/Atom feeds for new articles and imports into Blogs.",
		
		'filestorage__blog_Blogs'		=> "Blog Cover Photos",
		'entry_blog_id'					=> "Blog",

        'r__blogs'                      => "Blogs",
        'r__blog_settings_manage'       => "Can edit blog settings?",
        'r__blogs_manage'               => "Can manage blogs?",
		
		'blog_member_deleted'			=> "Member has been deleted",

		'rebuilding_blog_entry_images'  => "Rebuilding blog entry images",
		
		/* !Settings */
		'acplogs__blog_settings'		=> "Updated blog settings",
		'blog_enable_rating'			=> "Enable blog ratings?",
		'blog_settings_rss'				=> "RSS Settings",
		'blog_allow_rssimport'			=> "Allow RSS imports",
		'blog_allow_rssimport_desc'		=> "Allowing users to import RSS feeds will make your site susceptible to <a href='https://owasp.org/www-community/attacks/Server_Side_Request_Forgery' target='_blank' rel='noopener'>SSRF attacks</a>. You should not allow RSS imports to Blog if untrusted users are permitted to create blogs, and you should only import RSS feeds from sources that are trusted and that do not allow user-submitted content to be included in the feed.",
		'blog_allow_rss'				=> "Allow RSS exports",
		'blog_allow_grid'				=> "Enable grid view",
		'blog_allow_grid_desc'			=> "Grid view showcases blog entries as cards with space for a feature photo",
		'blog_view_mode'				=> "Default view",
		'blog_view_mode_grid'			=> "Grid of latest entries",
		'blog_view_mode_grid_desc'		=> "Displays entries as cards in a grid with space for a feature photo",
		'blog_view_mode_list'			=> "List of blogs",
		'blog_view_mode_list_desc'		=> "Displays blogs as a sortable and filterable list",
		
		/* !Global */
		'blogs'							=> "Blogs",
		'blog_word_custom'				=> "Blog Name",
		'blog_blog_member_id'			=> "Blog Author",
		'blogs_sg'						=> "Blog",
		'blogs_sg_lc'					=> "blog",
		'create_blog'					=> "Create a blog",
		'create_new_blog'				=> "Create a new blog",
		'add_entry_to'					=> "Add entry to a blog",
		'blog_entry'					=> "Blog Entry",
		'blog_entry_pl'					=> "Blog Entries",
		'blog_entry_comment'			=> "Blog Comment",
		'add_blog_entry'				=> "Add Blog Entry",
		'entry_pl'						=> "Blog Entries",
		'blog_entry_comment_pl'			=> "Blog Comments",
		'blog_entry_comment_pl_lc'		=> "blog comments",
		'entry_comments'				=> "Comments",
		'blog_num_views'				=> "{!# [1:view][?:views]}",
		'manage_blog'					=> "Manage Blog",
		'select_blog'					=> "Select Blog",
		'search_contextual_item_blogs'	=> "This Blog",
		'search_contextual_item_blog_entry'	=> "This Entry",
		'view_blogs_as_list'			=> "View Blogs",
		'view_blogs_as_grid'			=> "View Latest Entries",
		
		/* !Add/Edit Blog */
		'blog_settings'					=> "Blog Settings",
		'blog_name'						=> "Name",
		'blog_name_group'				=> "Name",
		'blog_desc'						=> "Description",
		'blog_desc_group'				=> "Description",
		'blog_desc_placeholder'			=> "Add a description...",
		'blog_type'						=> "Type",
		'blog_type_normal'				=> "Single author",
		'blog_type_group'				=> "Group",
		'blog_type_group_desc'			=> "Group blogs are jointly managed by all members in selected groups.",
		'blog_groupblog_ids'			=> "Groups",
		'blog_member_id'				=> "Author",
		'blog_groupblog_name'			=> "Group Name",
		'blog_groupblog_name_desc'		=> "Used in place of the owner's name when viewing a Group Blog.",
		'edit_blog'						=> "Edit Blog",
		'delete_blog'					=> "Delete Blog",
		'blog_privacy'					=> "Privacy",
		'blog_privacy_open'				=> "Everyone can read this blog",
		'blog_privacy_private'			=> "Only the members I choose can read this blog",
		'blog_social_group'				=> "Members allowed to read this blog",
		'no_blog_author_selected'		=> "No Blog Author selected",
		'modlog__action_delete_blog'	=> "Deleted Blog %s",
		'modlog__action_delete_blog_stats'	=> "Deleted Blog",
		'delete_blog_confirm'			=> "Are you sure you want to delete this blog?",
		'delete_blog_warning'			=> "This will permanently delete the blog and all its entries.",
		
		/* !Add/Edit Entry */
		'submit_entry'					=> "Submit New Blog Entry",
		'blog_entry_title'				=> "Title",
		'blog_entry_tags'				=> "Tags",
		'blog_entry_auto_follow'		=> "",
		'blog_entry_auto_follow_suffix'	=> "Follow this entry",
		'blog_entry_content'			=> "Content",
		'blog_entry_date'				=> "Publish Time",
		'blog_entry_publish'			=> "Publish",
		'blog_entry_mainTab'			=> "Blog Entry",
		'blog_entry_pollTab'			=> "Poll",
		'blog_entry_poll'				=> "",
		'create_blog_entry'				=> "Create Blog Entry",
		'entry_submit'					=> "Submit Entry",
		'entry_information'				=> "Entry Details",
		'blog_entry__save'				=> "Save",
		'entry_ip_address'				=> "IP Address",
		'entry_gallery_album'			=> "Album",
		'entry_gallery_album_desc'		=> "You can associate an album from the Gallery with this entry to display images alongside the entry content",		
		'entry_category_choice'			=> "Entry Category",
		'entry_category_choice_new'		=>  "Create a new entry category",
		'entry_category_choice_existing' => "Use an existing entry category",
		
		/* !Widgets */
		'block_entryFeed'				=> "Blog Entry Feed",
		'block_entryFeed_desc'			=> "Create a feed of blog entries",
		'widget_feed_container_blog_entry'	=> "Blogs",
		'block_latestComments'			=> "Latest Comments From Your Blogs",
		'block_latestComments_desc'		=> "Shows a list of latest comments from the logged in member's blogs",
		'view_this_entry'				=> "View the entry %s",
		'block_blogStatistics'			=> "Blog Statistics",
		'block_blogStatistics_desc'		=> "Shows general blog statistics",
		'stats_overview_blogs'			=> "Blogs",
		'stats_overview_blogs_desc'		=> "Blog creation date is not tracked so this is a total count and not limited by any date range restrictions applied",
		'total_blogs'					=> "Total Blogs",
		'total_entries'					=> "Total Entries",
		'block_recentEntries'			=> "Recent Entries",
		'block_recentEntries_desc'		=> "Shows recent entries",

		/* !Entry View */
		'prev_entry'						=> "Previous entry",
		'next_entry'						=> "Next entry",
		'blog_entry__comment_placeholder'	=> "Add a comment...",
		'blog_entry_submit_comment'			=> "Submit Comment",
		'entry_actions'						=> "Entry Actions",
		'edit_title_blog'					=> "Edit this blog entry",
		'feature_title_blog'				=> "Feature this blog entry",
		'unfeature_title_blog'				=> "Unfeature this blog entry",
		'pin_title_blog'					=> "Pin this blog entry",
		'unpin_title_blog'					=> "Unpin this blog entry",
		'hide_title_blog'					=> "Hide this blog entry",
		'unhide_title_blog'					=> "Unhide this blog entry",
		'blog_lock_title'					=> "Lock this blog entry",
		'blog_unlock_title'					=> "Unlock this blog entry",
		'blog_move_title'					=> "Move this blog entry",
		'blog_delete_title'					=> "Delete this blog entry",
		'approve_title_blog'				=> "Approve this blog entry",
		'report_entry'						=> "Report Entry",
		'unpublished'						=> "Unpublished",
		'blog_entry_locked_can_comment'		=> "This blog entry is locked, but your permissions allow you to add new comments.",
		'blog_entry_locked_cannot_comment'	=> "This blog entry is now closed to further comments.",
		'entry_posted'						=> "Entry posted by %s",
        'entry_future_posted'				=> "Entry by %s publishes on",
		'entry_images'						=> "Images",
		'entry_posted_with_cat'				=> "Entry posted by %s in %s",
        'entry_future_posted_with_cat'		=> "Entry by %s in %s publishes on",
		
		/* Browse View */
		'blog_comments'						=> "{!#[1:comment][?:comments]}",
		'blog_entries'						=> "{!#[1:entry][?:entries]}",
		'blog_views'						=> "{!#[1:view][?:views]}",
		'recent_entries'					=> "Recent Entries",
		'featured_entries'					=> "Featured Entries",
		'our_community_blogs'				=> "Our community blogs",
		'my_blogs'							=> "My Blogs",
		'blogs_with_content'				=> "Blogs With Entries",
		'sort_last_edate'					=> "Last Entry",
		'sort_rating_total'					=> "Rating",
		'from_the_blog'						=> "From the blog",
		'see_more_entries'					=> "See more entries from %s",
		'no_entries_yet'					=> "No blog entries yet",
		'read_more_entry'					=> "Read more of this entry",
		'see_comments_on_entry'				=> "See comments for this entry",
		'add_entry'							=> "Add new entry",
		'this_is_group'						=> "This is a group blog",
		'unread_blog'						=> "This entry is unread",
		'read_blog'							=> "You've read this entry",
		'go_to_blog'						=> "Go to the blog %s",
		'latest_entry'						=> "Latest Entry",
		'entry_name_with_cat'				=> "%s in %s",
		
		/* !Blog View */
		'no_entries'						=> "No blog entries have been created",
		'pin_blog'							=> "Pin",
		'unpin_blog'						=> "Unpin",
		'blog_by'							=> "A blog by %s in %s",
		'group_blog_by'						=> "A group blog by %s in %s",
		'club_blog_for'						=> "A club blog for %s",
		'contributors_to_this'				=> "Contributors to this blog",
		'num_contributors_to_this'			=> "{# [1:contributor][?:contributors]} to this blog",
		'about_this_blog'					=> "About this blog",
		'entries_in_this_blog'				=> "Entries in this blog",
		'blog_category_viewing'				=> "Viewing category %s",
		'blog_category_select'				=> "View a category",
		
		/* !RSS */
		'blog_rss_offline'					=> "RSS feed disabled",
		'blog_rss_offline_admin'			=> "This RSS feed is disabled either because the setting \"Allow RSS exports\" is currently disabled in the ACP or it is disabled in the individual blog settings.",
		'blog_enable_rss'					=> "Enable RSS Feed",
		'blog_enable_rss_desc'				=> "Allow this blog to be syndicated with others by enabling RSS",
		'blog_rss_title'					=> "Latest Entries",
		'blog_rss_import'					=> "Atom/RSS Import",
		'blog_rss_import_url'				=> "URL",
		'blog_rss_import_auth_user'			=> "HTTP Authorization Username",
		'blog_rss_import_auth_user_desc'	=> "Most feeds do not require authorization and you can leave this blank.",		
		'blog_rss_import_auth_pass'			=> "HTTP Authorization Password",
		'blog_rss_import_auth_pass_desc'	=> "Most feeds do not require authorization and you can leave this blank.",
		'blog_rss_import_tags'				=> "Tags",
		'blog_rss_import_show_link'			=> "Text to use for link",
		'blog_rss_import_show_link_desc'	=> "Will appear at the bottom of the post, linking to the original article.",
		'blog_rss_import_show_link_default'	=> "View the full article",
		'blog_enable_rss_import'			=> "Enable RSS import",
		'blog_enable_rss_import_desc'		=> "Import entries from an external source using RSS",

		'embed_blog_entry'					=> "Blog Entry",
		'embed_blog'						=> "Blog",
		'view_this_blog'					=> "View this blog",

		/* !Profile */
		'user_blogs'						=> "Blogs",
		'profile_blog_blog'					=> "Blogs",
		'also_contributes'					=> "Also contributes to:",
		'contributes_to'					=> "Contributes To",
		'most_recent_entry'					=> "Most recent entry",

		/* !Embeds */
		'blog_byline_nodate'				=> "A blog by %s",
		'blog_last_entry_date'				=> "Last entry posted %s",
		'num_blog_comments'					=> "{# [1:comment][?:comments]}",
		'num_blog_entries'					=> "{# [1:entry][?:entries]}",
		'num_blog_views'					=> "{# [1:view][?:views]}",
		
		/* !Digests */
		'digest_area_blog_blog'			=> "Blogs",
		'digest_area_blog_entry'		=> "Entries",
		'x_created_blog'		=> "%s created a blog",
		'x_created_entry_in'	=> "%s posted a blog entry in %s",
		'x_commented_entry'		=> "%s commented on an entry",
		'x_commented_blog_entry'=> "%s commented on a blog entry",
		
		/* !Online User Locations */
		'loc_blog_viewing_index' => "Browsing Blogs",
		'loc_blog_creating' => "Creating a Blog",
		'loc_blog_viewing_blog' => "Viewing Blog: %s",
		'loc_blog_adding_entry' => "Adding a Blog Entry in: %s",
		'loc_blog_viewing_entry'	=> "Viewing Entry: %s",
		'loc_blog_viewing_index_action' => "%s is browsing blogs",
		'loc_blog_creating_action' => "%s is creating a blog",
		'loc_blog_viewing_blog_action' => "%s is viewing a blog",
		'loc_blog_adding_entry_action' => "%s is adding a blog entry",
		'loc_blog_viewing_entry_action'	=> "%s is reading a blog entry",
		
		/* !Moderator Permissions */
		'modperms__core_Content_blog_Entry' 	=> "Blog Entries",
		'modperms__blog_Blogs'					=> "Blogs",
		'can_pin_blog_entry'							=> "Can pin entries?",
		'can_unpin_blog_entry'						=> "Can unpin entries?",
		'can_feature_blog_entry'						=> "Can feature entries?",
		'can_unfeature_blog_entry'					=> "Can unfeature entries?",
		'can_edit_blog_entry'						=> "Can edit entries?",
		'can_hide_blog_entry'						=> "Can hide entries?",
		'can_unhide_blog_entry'						=> "Can unhide entries?",
		'can_view_hidden_blog_entry'					=> "Can view hidden entries?",
		'can_mod_blogs'								=> "Can move blogs?",
		'can_move_blog_entry'						=> "Can move entries?",
		'can_move_blog_entry_desc'			=> "Will be able to move entries only between the blogs they can create new content within.",
		'can_lock_blog_entry'						=> "Can lock entries?",
		'can_unlock_blog_entry'						=> "Can unlock entries?",
		'can_reply_to_locked_blog_entry'				=> "Can reply to locked entries?",
		'can_delete_blog_entry'						=> "Can delete entries?",
		'can_edit_blog_entry_comment'			=> "Can edit comments?",
		'can_hide_blog_entry_comment'			=> "Can hide comments?",
		'can_unhide_blog_entry_comment'			=> "Can unhide comments?",
		'can_view_hidden_blog_entry_comment'	=> "Can view hidden comments?",
		'can_delete_blog_entry_comment'			=> "Can delete comments?",
		'can_future_publish_blog_entry'        => "Can set a future publishing date?",
		'can_view_future_blog_entry'           => "Can view pending publishing blog entries authored by other members?",
		'can_feature_comments_blog_entry'		=> "Can recommend comments on entries?",
		'can_unfeature_comments_blog_entry'		=> "Can remove comment recommendations on entries?",
		'can_add_item_message_blog_entry'		=> "Can add messages to entries?",
		'can_edit_item_message_blog_entry'		=> "Can edit messages on entries?",
		'can_delete_item_message_blog_entry'	=> "Can delete messages on entries?",
		
		/* !Group Settings */
		'group__blog_Blog'						=> "Blog",
		'g_blog_allowlocal'						=> "Can create blogs?",
		'g_blog_maxblogs'						=> "Maximum number of blogs",
		'g_blog_allowprivate'					=> "Can create private blogs?",
		'g_blog_allowprivate_desc'				=> "Private blogs can only be seen by the members that the creator chooses.",
		'g_blog_allowpoll'						=> "Can add polls to blog entries?",
		'g_blog_allowcomment'					=> "Can comment on blog entries?",
		'g_blog_allowcomment_guestreg'			=> "<a href='{internal.admin.app=core&module=settings&controller=posting&searchResult=post_before_registering}'>Post Before Registering</a> is enabled, but will be bypassed when you enable this setting.",
		'g_blog_allowownmod'					=> "Can moderate own blog entries?",
		'g_blog_allowownmod_desc'				=> "The user will be able to: edit comments and entries, delete comments and entries, and lock entries from further comments.",
		'g_blog_allowdelete'					=> "Can delete own blogs?",
		
		/* !Widgets */
		'block_blogCommentFeed'			=> "Blog Comments",
		'block_blogCommentFeed_desc'	=> "Display comments from blogs.",
		'block_blogs'					=> "Blogs",
		'block_blogs_desc'				=> "Display a list of blogs.",
		'widget_blog_last_date'			=> "Last entry posted",
		'widget__blog_edate'			=> "Last entry date",
		'widget__blog_count_entries'    => "Number of entries",
		'widget__blog_count_comments'   => "Number of comments",
		
		/* !API */
		'__api_blog_comments'	=> "Comments",
		'__api_blog_entries'	=> "Entries",
		'__api_blog_blogs'		=> "Blogs",
		
		/* !Customizeable Sidebar */
		'blog_sidebar_enabled'		=> "Enable Custom Sidebar?",
		'blog_sidebar'				=> "Sidebar Contents",
		'blog_enable_sidebar'		=> "Enable custom sidebars?",
		'blog_enable_sidebar_desc'	=> "Users with permission to manage blogs will be able to add content above the site sidebar to include social media links etc.",
		'blog_sidebar_title'		=> "Blog Information",

		/* !Member Filters */
		'blog_bm_filters'			=> "Blog",
		'mf_has_blog'				=> "Member has a Blog?",
		
		/* !Grid view things */
		'blog_entry_cover_photo'	=> "Feature Photo",

		/* !Categories */
		'menu__blog_blogs_categories'	=> "Blogs",
		'blog_categories'				=> "Blogs",
		'blog_create_category'			=> "Create New Category",
		'blog_categories_add_child'		=> "Add Blog",
		'blog_category_id'					=> "Category",
		'category_basic_settings'		=> "Basic Settings",
		'blog_category_desc'			=> "Description",
		'category_parent'				=> "Parent",
		'category_desc_placeholder'		=> "Add a description...",
		'__api_blog_categories'			=> "Categories",

		/* !Entry Categories */
		'entry_category_id'				=> "Select Entry Category",
		'blog_entry_new_category'		=> "Entry Category Name",
		'blog_entry_category_new'		=> " - Choose New - ",
		'blog_category_heading'			=> "Viewing entries in %s",
		'blog_manage_entry_categories'  => "Manage Categories",
		'blog_entry_categories'			=> "Entry Categories",
		'blog_error_missing_name'		=> "You need to enter a name for this category",
		'blog_error_not_find_category'	=> "Could not locate that category",
		'blog_categories_all'			=> "Show All",
		'no_entries_in_cat'				=> "There are no entries in this category",
		'__api_blog_entrycategories'	=> "Entry Categories",
		'blog_subcategories'			=> "Subcategories",


		/* Webhooks */
		'webhook_blogBlog_create' => "Fired when a blog is created"
);
