<ips:template parameters="" />
{{$prefix = \IPS\COOKIE_PREFIX;}}
{template="pageHeader" if="!\IPS\Request::i()->isAjax()" group="global" params="\IPS\Member::loggedIn()->language()->addToStack('cookies_about')"}
<div class='ipsBox_alt'>
    <div class='ipsBox'>
	<div class='ipsType_normal ipsType_richText ipsPad'>
		{lang="cookies_about_header"}
	

 	    <h3 class="ipsType_large">{lang="cookies_standard"}</h3>
        <div>{lang="cookie_standard_desc"}</div>
        <details>
        <summary>{lang="cookies_standard"}</summary>
        <div class='ipsType_normal ipsType_richText ipsPad'>
			{{foreach \IPS\Request::getEssentialCookies() as $cookie}}
			<strong class='ipsType_medium'>{$prefix}{$cookie}</strong>
			<div>{lang="cookie_{$cookie}_description"}</div>
			<br>
            {{endforeach}}
        </div>
    </details>
    {{if \IPS\Request::i()->cookieConsentEnabled()}}
        <h3 class='ipsType_large'>{lang='cookies_optional'}
            {{$currentUrl = base64_encode((string) request.url());}}
            {{$status = (int) !\IPS\Member::loggedIn()->optionalCookiesAllowed;}}
            <a href='{url="app=core&module=system&controller=cookies&do=cookieConsentToggle&ref={$currentUrl}&status={$status}" csrf="true"}' rel='nofollow'>
                {{$allowed = $status ? "_off" : '_on' ;}}
                <i class='ipsToggle ipsToggle{$allowed}' aria-hidden='true'><span class='status'></span> </i>
            </a>
        </h3>
        <div>{lang="cookies_optional_desc"}</div>
    {{endif}}
   <hr>
		{{if \IPS\Member::loggedIn()->language()->checkKeyExists('cookie_3rdpartynotice_value') AND !empty( \IPS\Member::loggedIn()->language()->get('cookie_3rdpartynotice_value') )}}
	<h3 class="ipsType_large">{lang="cookies_third_party"}</h3>
	<div class='ipsType_normal ipsType_richText '>
		{lang="cookie_3rdpartynotice_value"}
	</div>
		   {{endif}}
	<h3 class="ipsType_large">{lang="cookies_change_header"}</h3>
	<div class='ipsType_normal ipsType_richText '>
		{lang="cookies_change_text"}
	</div>
    </div>
    </div>
</div>