<ips:template parameters="$categories" />
{template="pageHeader" group="global" params="\IPS\Member::loggedIn()->language()->addToStack('notification_options')"}
<div class="ipsBox ipsResponsive_pull ipsSpacer_both">
	<h2 class="ipsType_sectionTitle ipsType_reset">{lang="what_notifications_you_receive"}</h2>
	<div class='ipsAreaBackground_light ipsPadding:half'>
		<ul class="ipsList_reset cNotificationTypes" >
			{{foreach $categories as $k => $enabled}}
				{template="notificationSettingsIndexRow" group="system" params="$k, $enabled"}
			{{endforeach}}
		</ul>
	</div>
</div>
<div class="ipsBox ipsResponsive_pull ipsSpacer_both ipsSpacer_double">
	<h2 class="ipsType_sectionTitle ipsType_reset">{lang="where_you_receive_notifications"}</h2>
	<div class="ipsGrid ipsGrid_collapsePhone">
		<div class="ipsGrid_span4 ipsPadding">
			<div class="cNotificationMethodIcon">
				<img src="{resource="notification_settings/notification_bell.svg"}">
			</div>
			<div class="cNotificationMethodDetails">
				<p class="ipsType_reset ipsType_large">{lang="member_notifications_inline"}</p>
				<p class="ipsType_light">{lang="member_notifications_inline_desc"}</p>
			</div>
		</div>
		{{if \IPS\Notification::webPushEnabled() || \count( \IPS\Member::loggedIn()->getPwaAuths() )}}
			<div class="ipsGrid_span4 ipsPadding">
				<div class="cNotificationMethodIcon">
					<img src="{resource="notification_settings/push.svg"}">
				</div>
				<div class="cNotificationMethodDetails">
					<p class="ipsType_reset ipsType_large">{lang="member_notifications_push"}</p>
						<p class="ipsType_light">{lang="member_notifications_push_desc"}</p>
					<ul class='ipsList_reset'>
						{{if \IPS\Notification::webPushEnabled()}}
							<li class='ipsBorder_top ipsPadding_vertical:half' data-action="enablePush" style='display: none'>
								<a href='#' title="{lang="member_notifications_push_enable"}">{lang="member_notifications_push_enable"} <i class='fa fa-angle-right'></i> </a>
							</li>
						{{endif}}
						{{if \IPS\Notification::webPushEnabled() && \count( \IPS\Member::loggedIn()->getPwaAuths() ) }}
							<li class='ipsBorder_top ipsPadding_vertical:half'>
								<a href="{url="app=core&module=system&controller=notifications&do=disable&type=push" csrf="true"}" data-confirm data-confirmIcon="false" data-confirmMessage="{lang="member_notifications_push_stop_desc"}" data-confirmSubMessage="{lang="member_notifications_push_stop_desc_sub"}">{lang="member_notifications_push_stop"} <i class='fa fa-angle-right'></i></a>
							</li>
						{{endif}}
					</ul>
				</div>
			</div>
		{{endif}}
		<div class="ipsGrid_span4 ipsPadding">
			<div class="cNotificationMethodIcon">
				<img src="{resource="notification_settings/email.svg"}">
			</div>
			<div class="cNotificationMethodDetails">
				<p class="ipsType_reset ipsType_large">{lang="member_notifications_email"}</p>
				<p class="ipsType_light">{lang="member_notifications_email_desc" sprintf="\IPS\Member::loggedIn()->email"}</p>
				<ul class='ipsList_reset'>
					<li class='ipsBorder_top ipsPadding_vertical:half'>
						<a href="{url="app=core&module=system&controller=notifications&do=disable&type=email" csrf="true"}" data-confirm>{lang="member_notifications_email_stop"} <i class='fa fa-angle-right'></i></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
{{if \IPS\core\Stream\Subscription::hasSubscribedStreams() }}
<div class="ipsBox">
    <h2 class='ipsType_sectionTitle ipsType_reset'>{lang='stream_subscriptions'}</h2>

        {{foreach \IPS\core\Stream\Subscription::getSubscribedStreams() as $stream }}
    <div class='ipsGrid '>
        <div class='ipsGrid_span8 ipsPadding'>
            <a href="{$stream->stream->url()}">{$stream->stream->_title}</a>
        </div>
        <div class='ipsGrid_span4 ipsPadding'>
           <a href="{$stream->stream->url()->setQueryString('do','unsubscribe')->csrf()}" data-confirm data-confirmSubMessage="{lang="stream_unsubscribe_confirm"}" >{lang="stream_unsubscribe"}</a>
        </div>
    </div>
        {{endforeach}}

</div>
{{endif}}