<ips:template parameters="$k, $enabled" />
<li class="cNotificationTypes__row ipsAreaBackground_reset ipsPos_relative ipsLoading_tiny">
	<a href="{url="app=core&module=system&controller=notifications&do=options&type={$k}" seoTemplate="notifications_options"}" class="ipsFlex ipsFlex-ai:center sm:ipsFlex-ai:start ipsFlex-jc:between ipsType_blendLinks ipsPadding" data-action="showNotificationSettings">
		{template="notificationSettingsIndexRowDetails" group="system" params="$k, $enabled"}
	</a>
	<div data-role="notificationSettingsWindow" class="ipsHide ipsPadding">
		
	</div>
</li>