<ips:template parameters="$title, $form, $ajax=FALSE" />
{{if $ajax}}
	<div class="ipsClearfix">
		<a href="#" class="ipsDialog_close" data-action="closeNotificationSettings">×</a>
		<h3 class="ipsType_reset ipsType_large ipsType_bold ipsType_darkText cNotificationTypes__row__title">
			{$title}
		</h3>
	</div>
	<div class="ipsSpacer_top">
		{$form|raw}
	</div>
{{else}}
	{template="pageHeader" group="global" params="$title"}
	<div class="ipsBox ipsPadding">
		{$form|raw}
	</div>
{{endif}}