<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div class='cReferal_members' data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-controller='core.global.core.table{{if $table->canModerate()}},core.front.core.moderation{{endif}}' {{if $table->getPaginationKey() != 'page'}}data-pageParam='{$table->getPaginationKey()}'{{endif}} data-tableID='{expression="md5($table->baseUrl->stripQueryString($table->getPaginationKey()))"}'>
	{{if $table->title}}
		<h2 class='ipsType_sectionTitle ipsType_reset ipsClear'>{lang="$table->title"}</h2>
	{{endif}}
    {{if \count( $rows )}}
		<ol class='ipsList_inline ipsClearfix ipsSpacer_top ipsSpacer_half' id='elTable_{$table->uniqueId}' data-role="tableRows">
			{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
		</ol>
    <div class="ipsButtonBar ipsPadding_top ipsBorder:none ipsClearfix ipsClear {{if $table->pages <= 1}}ipsHide{{endif}}" data-role="tablePagination">
        {template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
    </div>
	{{else}}
		{lang="referral_no_referrals"}
	{{endif}}
</div>