<ips:template parameters="$indexData, $itemData=null" />
{{if trim( $indexData['index_content'] ) !== ''}}
	<div class='ipsType_richText ipsContained ipsType_medium'>
		<div {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
			{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
		</div>
	</div>
{{endif}}
{{if isset( $itemData['attachedImages'] )}}
    <div class='ipsFlex ipsFlex-fw:wrap ipsGap:2 ipsMargin_top:half' data-controller="core.front.core.lightboxedImages" data-ipsLazyLoad>
        {{foreach $itemData['attachedImages'] as $image }}
            {{$imagePath = $image['thumb_location'] ?: $image['location'];}}
            <div>
                <a href='{file="$image['location']" extension="$image['extension']"}' {{if $image['labels']}}title="{lang="alt_label_could_be"} {$image['labels']}"{{endif}} data-ipsLightbox {{if $image['labels']}}title="{lang="alt_label_could_be"} {$image['labels']}"{{endif}} data-ipsLightbox-group='g{$indexData['index_class_type_id_hash']}'>
                    <span class='ipsThumb_bg ipsThumb_small ipsPos_left' {{if settings.lazy_load_enabled}}data-background-src="{backgroundimage="\IPS\File::get( $image['extension'], $imagePath )->url"}"{{else}}style='background-image: url({backgroundimage="\IPS\File::get( $image['extension'], $imagePath )->url"})'{{endif}}>
                        <img {{if settings.lazy_load_enabled}}src="{expression="\IPS\Text\Parser::blankImage()"}" data-{{endif}}src='{file="$imagePath" extension="$image['extension']"}' {{if $image['labels']}}alt="{lang="alt_label_could_be"} {$image['labels']}"{{endif}}>
                    </span>
                </a>
            </div>
        {{endforeach}}
    </div>
{{endif}}