<ips:template parameters="" />
<h3 class="ipsType_reset ipsWidget_title">{lang="current_donation_goals"}</h3>

<div class='ipsWidget_inner'>
	<ul class='ipsDataList'>
		{{foreach \IPS\nexus\Donation\Goal::roots() as $goal}}
			<li class="ipsDataItem">
                {{if member.member_id }}
				<a href="{$goal->url()}" class="ipsType_blendLinks" data-ipsDialog data-ipsDialog-title="{$goal->_title}">
                {{endif}}

					<div class='ipsDataItem_main'>
						<div class='ipsType_large ipsType_break ipsType_blendLinks'>{$goal->_title}</div>
						{{if $goal->goal}}
								<div class="ipsType_center ipsSpacer_top">
									<div class="cDonateProgressBar cDonateProgressBar_condensed">
										<div class="cDonateProgressBar_progress" style="width:{expression="number_format( 100/$goal->goal*$goal->current, 2, '.', '')"}%"></div>
									</div>
									<span class="ipsType_light ipsType_small">
										{lang="donate_progress" sprintf="new \IPS\nexus\Money( $goal->current, $goal->currency ), new \IPS\nexus\Money( $goal->goal, $goal->currency )"}
									</span>
								</div>
						{{else}}
							<div class="ipsType_light ipsType_small">
								{lang="donate_sofar" sprintf="new \IPS\nexus\Money( $goal->current, $goal->currency )"}
							</div>
						{{endif}}
					</div>
                {{if member.member_id }}
				</a>
                {{endif}}
			</li>
		{{endforeach}}
	</ul>
</div>