<ips:template parameters="$field, $gateway, $clientId" />
<div data-controller="nexus.global.gateways.stripeamex" data-id="{$gateway->id}" class="ipsType_center" {{if $field->htmlId}}id="{$field->htmlId}"{{endif}}>
	<noscript>
		<div class="ipsMessage ipsMessage_error">{lang="card_requires_js"}</div>
	</noscript>
	{{if \IPS\NEXUS_TEST_GATEWAYS}}
		<amex:init client_id="86a947f9-098d-4a9c-a0ef-22f30f3322fa" env="qa" callback="aecCallbackHandler" button_color="light"/>
	{{else}}
		<amex:init client_id="{$clientId}" env="production" callback="aecCallbackHandler"/>
	{{endif}}
	<input type='hidden' name="{$field->name}" value="" data-role="value">
	<div id="amex-express-checkout"></div>
</div>