<ips:template parameters="$clientToken, $type, $field, $vaultAccounts, $invoice, $amount, $gateway, $shippingAddress, $venmoProfile, $paymentScreenType, $advancedFraud, $payPalCredit, $googlepayMerchant" />
<div data-controller="nexus.global.gateways.braintree" data-method="{$type}" data-clientToken="{$clientToken}" data-env="{{if \IPS\NEXUS_TEST_GATEWAYS}}sandbox{{else}}production{{endif}}" data-currency="{$amount->currency}" data-amount="{$amount->amount}" data-id="{$gateway->id}" {{if $field->htmlId}}id="{$field->htmlId}"{{endif}} {{if $shippingAddress}}data-shipping='{$shippingAddress}'{{endif}} data-venmo-profile="{$venmoProfile}" data-fieldName="{$field->name}" data-forceVault="{{if $paymentScreenType === 'card'}}true{{else}}false{{endif}}" data-advanced-fraud="{{if $advancedFraud}}true{{else}}false{{endif}}" data-googlepay-merchant="{$googlepayMerchant}">
	<div class="ipsJS_hide" data-role="error">
		<div class="ipsMessage ipsMessage_error" data-role="errorMessage">{lang="card_requires_js"}</div>
	</div>
	<div class="ipsJS_show" data-role="paymentMethodForm">
		{{if $type == 'applepay' or $type == 'googlepay'}}
			<div class="ipsType_center ipsLoading ipsLoading_small" data-role="newAccountContainer" style="height:47px">
				<button type="button" data-role="applePayButton" class="ipsHide ipsButton ipsButton_primary ipsButton_veryLarge ipsButton_fullWidth" style="-webkit-appearance: -apple-pay-button;">&nbsp;</button>
				<div data-role="googlePayButton"></div>
			</div>
		{{else}}
			<div class="ipsBox ipsPad ipsSpacer_bottom">
				<div class="ipsFieldRow {{if !$vaultAccounts}}ipsHide{{endif}}" data-role="showWhenVaultAccountAdded">
					<ul class='ipsFieldRow_content ipsField_fieldList' data-role="vaultAccountList">
						{{$j = 0;}}
						{{if $vaultAccounts !== NULL}}
							{{foreach $vaultAccounts as $i => $vaultAccount}}
								<li>
									<span class='ipsCustomInput'>
										<input type='radio' name="{$field->name}[stored]" value="{$vaultAccount->data}" id="{$field->name}_stored{$i}" {{if $j === 0}}checked{{endif}} data-control="toggle" data-toggles="{$field->name}_existing">
										<span></span>
									</span>
									<div class='ipsField_fieldList_content'>
										<label for='{$field->name}_stored{$i}'>{$vaultAccount->card->number}</label>
									</div>
								</li>
								{{$j++;}}
							{{endforeach}}
						{{endif}}
						<li data-role="newVaultOption">
							<span class='ipsCustomInput'>
								<input type='radio' name="{$field->name}[stored]" value="0" id="{$field->name}_stored0" {{if $j === 0}}checked{{endif}} data-control="toggle" {{if $vaultAccounts}}data-toggles="{$field->name}_new"{{endif}}>
								<span></span>
							</span>
							<div class='ipsField_fieldList_content'>
								<label for='{$field->name}_stored0'>{lang="use_new_braintree_vault"}</label><br>
							</div>
						</li>
					</ul>
				</div>
				<div id="{$field->name}_new">
					<hr class="ipsHr {{if !$vaultAccounts}}ipsHide{{endif}}" data-role="showWhenVaultAccountAdded">
					{{if $vaultAccounts !== NULL}}
						<div class='ipsFieldRow ipsFieldRow_checkbox' id="{$field->name}_newVault">
							<span class='ipsCustomInput'>
								<input type='checkbox' data-role="braintreeVault" name="{$field->name}[save]" value="1" checked id="el{$field->name}Save">
								<span></span>
							</span>
							<div class='ipsFieldRow_content'>
								<label for='el{$field->name}Save'>{lang="braintree_vault_save"}</label>
							</div>
						</div>
					{{endif}}
					<div class="ipsType_center ipsLoading ipsLoading_small" data-role="newAccountContainer" style="height:47px">
						{{if $payPalCredit}}
							<div class="ipsGrid">
								<div class="ipsGrid_span6">
									<div data-role="paypalButton" id="pp{expression="md5(uniqid())"}"></div>
								</div>
								<div class="ipsGrid_span6">
									<div data-role="paypalCreditButton" id="pp{expression="md5(uniqid())"}"></div>
								</div>
							</div>
						{{else}}
							<div data-role="paypalButton" id="pp{expression="md5(uniqid())"}"></div>
						{{endif}}
						<button type="button" data-role="venmoButton" class="ipsHide ipsButton ipsButton_primary ipsButton_veryLarge ipsButton_fullWidth cVenmoButton"><img src="{resource="cards/venmo_white.svg" location="front"}" alt="{lang="braintree_type_venmo"}"></button>
					</div>
				</div>
			</div>
			<div id='{$field->name}_existing' class="{{if !$vaultAccounts}}ipsHide{{endif}}">
				<button type="submit" class="ipsButton ipsButton_primary ipsButton_veryLarge ipsButton_fullWidth"><i class="fa fa-check-circle"></i> {{if $amount->amount->compare( $invoice->total->amount ) !== 0}}{lang="confirm_and_pay_split" sprintf="$amount"}{{else}}{lang="confirm_and_pay"}{{endif}}</button>
			</div>
		{{endif}}
	</div>
</div>