<ips:template parameters="$name, $value" />
<ul class='ipsField_translatable ipsList_reset'>
	<li class='ipsClearfix'>
		<span class="ipsFlag fa fa-user"></span>
		<input type='text' name="{$name}[un]" placeholder="{lang="username"}" {{if isset( $value['un'] )}}value="{$value['un']}"{{endif}}>
	</li>
	<li class='ipsClearfix'>
		<span class="ipsFlag fa fa-lock"></span>
		<input type='password' name="{$name}[pw]" placeholder="{lang="password"}" {{if isset( $value['pw'] )}}value="{$value['pw']}"{{endif}}>
	</li>
</ul>