<?php

$lang = array(

	/* !ACP */
	'__app_convert'						=> "Converter",
	
	'menu__convert_manage'				=> 'Conversions',
	'menu__convert_manage_manage_start'	=> 'Start New Conversion',
	'menu__convert_manage_manage'		=> 'Manage Conversions',

	'converter_uninstall'				=> 'Uninstall Converter',
	'converter_uninstall_warning'		=> 'Uninstalling this application will prevent the URL redirections from your old platform working. This action is irreversible.',
	
	/* !Manage Conversion */
	'convert_sw'						=> 'Applications',
	'convert_app_key'					=> 'Source Software',
	'convert_name'						=> 'Identifier',
	'convert_parent'					=> 'Parent Conversion',
	'convert_start_date'				=> 'Start Date',
	'convert_finished'					=> "Finished?",
	'convert_no_parent'					=> '<em>No Parent</em>',
	'convert_start'						=> 'Start New Conversion',
	'conversion_app_already_exists'		=> 'A conversion has already been configured for this software. We have taken you to that conversion now.',
	'conversion_app_not_found'			=> "The conversion you were managing could not be found",
	'convert_start_application'			=> 'What do you want to convert?',
	'choose_what_to_convert'			=> "Choose what to convert",
	'core_node_select'					=> "Member and System Information",
	'forums_node_select'				=> "Forum and Topic Data",
	'blog_node_select'					=> "Blog Data",
	'calendar_node_select'				=> "Calendar and Event Data",
	'downloads_node_select'				=> "Downloads Data",
	'gallery_node_select'				=> "Gallery and Images Data",
	'cms_node_select'					=> "Pages and Record Data",
	'nexus_node_select'					=> "Commerce, Support, and Purchase Data",
	'convert_start_source_software'		=> 'What software are you converting from?',
	'convert_start_database_details'	=> 'Database Details',
	'convert_start_conversion_details'	=> "Conversion Details",
	'convert_start_database_host'		=> 'Database Host',
	'convert_start_database_port'       => 'Database Port',
	'convert_start_database_name'		=> 'Database Name',
	'convert_start_database_user'		=> 'Database User',
	'convert_start_database_pass'		=> 'Database Password',
	'convert_start_database_prefix'		=> 'Database Table Prefix',
	'convert_start_database_charset'	=> 'Database Character Set',
	'enter_database_details'			=> 'Supply database details',
	'enter_conversion_details'			=> "Supply conversion details",
	'start_conversion'					=> "Start Conversion",
	'edit_conversion'					=> 'Edit Conversion',
	'db_host'							=> 'Database Host',
	'db_port'							=> 'Database Port',
	'db_db'								=> 'Database Name',
	'db_user'							=> 'Database User',
	'db_pass'							=> 'Database Password',
	'db_prefix'							=> 'Database Table Prefix',
	'db_charset'						=> 'Database Character Set',
	'could_not_count_rows'				=> "Failed to count rows in table '%s' - is your table prefix set correctly?",
	'file_location'						=> "Location of files",
	'new_software'						=> "Create New Converter",
	'new_library'						=> "Create New Library",
	'classname'							=> "Class Name",
	'classname_desc'					=> "The path for the generated file must exist. Format must be in the form of IPS\\myapp\\Namespace\\Classname.",
	'library'							=> "Library",
	'new_software_not_in_dev'			=> "You can only create new converters while IN_DEV.",
	'new_library_not_in_dev'			=> "You can only create new libraries while IN_DEV.",
	'source_path'						=> "Path to %s installation.",
	'path_invalid'						=> "The path entered appears to be invalid.",
	'convert_finish_confirm'			=> "Finishing the conversion should only be done once all parts of your conversion are completed",
	'convert_finish_confirm_title'		=> "Finish Conversion",
	'convert_cant_connect_db'			=> "The details provided are not correct or the database is unavailable.",
	'convert_cant_connect_db_charset'	=> "The database character set you supplied is not a valid database character set.",
	'convert_cant_connect_db_prefix'	=> "The database table prefix you supplied appears to be incorrect.",
	'convert_again'						=> "Convert Again",
	'begin_conversion'					=> "Begin Conversion",
	'confirm_reconvert'					=> "Are you sure you wish to convert again? If you reconvert this step, then you MUST also reconvert the following steps.",
	'reconvert_button'					=> "Reconvert",
	'avatar_gallery_location'			=> "Path to Avatar Gallery files",
	'convert_cms_info_message'			=> "<strong>Note:</strong> Items that contain customized HTML, such as pages and blocks, may not work properly when converted into Invision Community. It is recommended that you review these items, once the conversion has completed, and update them accordingly.",
	'convert_wp_typical_path'			=> "This is typically: /path/to/wordpress/wp-content/uploads",
	'convert_ee_sig_attach_path'		=> "This is typically: /path/to/expressionengine/images/signature_attachments/",
	'convert_ee_avatar_path'			=> "This is typically: /path/to/expressionengine/images/avatars/",
	'convert_ee_pm_attach_path'			=> "This is typically: /path/to/expressionengine/images/pm_attachments/",
	'convert_ee_forum_at_path'			=> "This is typically: /path/to/expressionengine/images/forum_attachments",
	'convert_groupicon_hint'			=> "(Optional) Location where group images or icons are stored",
	'convert_phpbb_emoticons'			=> "This is typically: /path/to/phpbb/images/smilies",
	'convert_phpbb_randstring'			=> "This is the string of characters that precedes the filename of all uploaded avatars - if you are not sure what this is, you can typically find it by referencing the files located at /path/to/phpbb/images/avatars/upload",
	'convert_phpbb_avatars'				=> "This is typically: /path/to/phpbb/images/avatars/upload",
	'convert_phpbb_avatargallery'		=> "This is typically: /path/to/phpbb/images/avatars/gallery - leave blank to skip converting avatars from the avatar gallery",
	'convert_phpbb_ranks_path'			=> "This is typically: /path/to/phpbb/images/ranks",
	'convert_phpbb_attach_path'			=> "This is typically: /path/to/phpbb/files",
	'convert_vanilla_photopath'			=> "This is typically: /path/to/vanilla/uploads",
	'convert_vb_smilie_path'			=> "This is typically: /path/to/vb/images/smilies",
	'convert_vb_avatar_gallery_path'	=> "This is typically: /path/to/vb/images/avatars",
	'convert_vb5_smilie_path'			=> "This is typically: /path/to/vb5/core/images/smilies",
	'convert_xf_attach_path'			=> "This is typically: /path/to/xenforo/internal_data/attachments",
	'convert_xf_gal_path'				=> "This is typically: /path/to/xenforo/data/xengallery",
	'convert_xf_avatar_path'			=> "This is typically: /path/to/xenforo/data/avatars",
	'convert_mybb_attach_path'			=> "This is typically: /path/to/mybb/uploads",
	'convert_smf_attach_path'			=> "This is typically: /path/to/smf/attachments",
	'convert_ubb_attach_path'			=> "This is typically: /path/to/ubb/uploads/attachments",
	'convert_phpbb_preconvert'			=> "You can typically obtain these details from the file located at /path/to/phpbb/config.php",
	'convert_vanilla_preconvert'		=> "You can typically obtain these details from the file located at /path/to/vanilla/conf/config.php",
	'convert_vb4_preconvert'			=> "You can typically obtain these details from the file located at /path/to/vb4/includes/config.php",
	'convert_vb5_preconvert'			=> "You can typically obtain these details from the file located at /path/to/vb5/core/includes/config.php",
	'convert_wordpress_preconvert'		=> "You can typically obtain these details from the file called wp-config.php",
	'convert_xf_preconvert'				=> "You can typically obtain these details from the file located at /path/to/xenforo/library/config.php",
	'convert_coppermine_filehint'		=> "This is typically: /path/to/coppermine/albums",
	'convert_photoplog_hint'			=> "This is typically: /path/to/photoplog/images",
	'convert_invision_mismatch'			=> "Both of your Invision Community installations <strong>must</strong> be using the same version, please upgrade them to the latest version available.",
	'convert_invision_upload_path'		=> "This is typically: /path/to/ips4/uploads",
	'convert_invision_upload_input'		=> "Upload Path",
	'convert_invision_upload_input_desc'=> "Your source Invision Community must have all files stored in the default /uploads location",
	'convert_ubbthreads_photo_path'		=> "This is typically the absolute path to your domain root (do not include any subfolders if UBBThreads is in a subfolder)",
	'convert_photopost_image_path'		=> "This is typically: /path/to/photopost/data",
	'convert_woltlab_avatar'			=> "Avatar Path",
	'convert_woltlab_avatar_desc'		=> "This is typically: /path/to/woltlab/images/avatars",
	'convert_woltlab_cover'				=> "Cover Photo Path",
	'convert_woltlab_cover_desc'		=> "This is typically: /path/to/woltlab/images/coverPhotos",
	'convert_woltlab_attach_path'		=> "This is typically: /path/to/woltlab/attachments",
	'use_fluid_view_convert'			=> "Use fluid view for forums?",
	'reaction_convert_help'				=> "Choose which reaction to convert to",
	'rep_positive'						=> "Up Vote",
	'rep_positive_desc'					=> "Select the reaction to use for up votes",
	'rep_negative'						=> "Down Vote",
	'rep_negative_desc'					=> "Select the reaction to use for down votes",
	'rep_neutral'						=> "Neutral",
	'rep_neutral_desc'					=> "Select the reaction to use for neutral votes",
	'rep_like'							=> "Like",
	'rep_like_desc'						=> "Select the reaction to use for likes",
	'nothing_to_finish'					=> "There was not anything that needed to be finished, the conversion may have already been finished.",
	'convert_mod_rewrite_urls'			=> "You have not enabled the setting <a href='{internal.app=core&module=promotion&controller=seo}'>Rewrite Urls</a> in Invision Community. If you do not enable this option, URLs may not correctly redirect to the new locations.",
	'convert_configure_permissions'		=> "After your conversion is complete, you must configure permissions for your member groups. Go to the <a href='{internal.app=core&module=members&controller=groups}'>members group</a> page and click the 'padlock' icon next to each member group.",
	'conversion_app_finished'			=> "This conversion has been marked as completed.",
	'nothing_convertable_found'			=> "No items could be found to convert. This may be because there is no data present to convert in your old database.",

	'convert_reaction_choose'			=> "Choose",
	'convert_create_reaction'			=> "Create new Reaction",
	'err_convert_reaction'				=> "There was a problem selecting reactions, please try again",
	'err_convert_reaction_not_exist'	=> "A reaction you have selected does not exist",
	'err_convert_reaction_not_selected' => "You have not selected an option for every reaction",
	
	/* !Conversion Menu */
	'converter_supports_settings'		=> "Convert settings",
	'converter_supports_settings_link'	=> "If you wish to convert settings, <a href='%s'>click here</a> to convert them before proceeding with any other steps.",
	'converting_settings'				=> "Converting Settings",
	'converting_settings_desc'			=> "The following settings will be converted to their Invision Community equivalents.",
	'convert_setting_x_to_x'			=> "<em>%s</em> to <em>%s</em>: %s",
	'convert_settings'					=> "Convert Settings",
	'_convert_settings'					=> "Settings",
	'converting_x_to_x'					=> '<strong>Converting from %s to %s</strong>',
	'convert_data_prefix'				=> "Convert %s",
	'step_title'						=> "Step",
	'ips_rows'							=> "Current Count",
	'source_rows'						=> "Source Count",
	'per_cycle'							=> "Rows Per Cycle",
	'empty_local_data'					=> "Empty Local Data",
	'remove_converted_data'				=> "Remove Converted Data",
	'removing_data'						=> "Removing Converted Data",
	'step_method'						=> '', /* this space intentionally left blank */
	'more_info_needed'					=> "More Information Needed",
	'converting'						=> "Converting...",
	'converted_x_of_x'					=> "Completed %d of %d %s",
	'removed_x_of_x'					=> "Removed %s %s out of %s total",
	'finish'							=> "Finish",
	'reconfigure'						=> "Reconfigure",
	'cannot_convert'					=> "Cannot Convert Yet",
	'cannot_convert_desc'				=> "This step cannot be run until the steps before this one have been run.",
	'waiting_previous_process'			=> "Waiting for a previous conversion cycle to finish",
	'no_conversion_app'					=> "The conversion you attempted to run could not be found.",
	'converter_could_not_continue'		=> "There was a problem proceeding with the conversion, a previous cycle was still running. Please go back to <a href='{internal.app=convert&module=manage&controller=manage}'>the conversion</a> to continue.",

	/* !Convert BBCode */
	'convert_custom_bbcode'				=> "Convert Custom BBCode",
	'_convert_custom_bbcode'			=> "Custom BBCode",
	
	/* !Convert Emoticons */
	'convert_emoticons'					=> "Convert Emoticons",
	'_convert_emoticons'				=> "Emoticons",
	'emoticon_path'						=> "Path to emoticons",
	'keep_existing_emoticons'			=> "Keep Existing?",
	'keep_existing_emoticons_desc'		=> "If checked, then any emoticons that are inserted that have the same typed code as an existing emoticon will be merged into the already existing one.",
	'emoticon_missing_ids'				=> "Emoticon missing ID",
	'emoticon_missing_code'				=> "Emoticon missing code",
	'emoticon_no_file'					=> "No emoticon file provided",
	'emoticon_no_filename'				=> "No emoticon filename provided",

	/* !Convert Reactions */
	'convert_reactions'					=> "Convert Reactions",
	'_convert_reactions'				=> "Reactions",
	
	/* !Convert Follows */
	'follow_failed_insert'				=> "Follow failed to insert",
	'convert_follows'					=> "Convert Follows",
	'_convert_follows'					=> "Follows",
	
	/* !Convert Profile Field Groups */
	'convert_profile_field_groups'		=> "Convert Profile Field Groups",
	'_convert_profile_field_groups'		=> "Profile Field Groups",
	'profile_field_group_missing_ids'	=> "Profile Field Group missing ID",
	'profile_field_group_missing_name'	=> "Profile Field Group missing name",
	'map_pfgroup_desc'					=> "Select the profile field group to merge this one with, or select 'None' to create new.",
	
	/* !Convert Profile Fields */
	'convert_profile_fields'			=> "Convert Profile Fields",
	'_convert_profile_fields'			=> "Profile Fields",
	'map_pfield_desc'					=> "Select the profile field to merge this one with, or select 'None' to create new.",
	
	/* !Convert Member Groups */
	'convert_groups'					=> "Convert Member Groups",
	'_convert_groups'					=> "Member Groups",
	'map_group_desc'					=> "Select the group to merge this one with, or select 'None' to create new.",
	
	/* !Convert Members */
	'convert_members'					=> "Convert Members",
	'convert_members_followers'         => "Convert Member Followers",
	'_convert_members'					=> "Members",
	'_convert_members_followers'        => "Member Followers",
	'photo_type'						=> "Photos to Retain",
	'photo_type_desc'					=> "This software supports multiple types of images to represent an account. Only one of these can be retained, however. If a photo of the selected type does not exist for a member, than the other will attempt to be used instead.",
	'photo_location'					=> "Location of Photos",
	'photo_location_desc'				=> "If member photos are presently stored in the database, then select 'Database', otherwise select 'File System' and then enter the absolute path to profile photos in the textbox provided.",
	'photo_location_nodb_desc'			=> "The path to profile photos.",
	'photo_hash'						=> "Avatar Hash",
	'gallery_location'					=> "Gallery Location",
	'pseudo_field'						=> "Field: %s",
	'pseudo_field_desc'					=> "This field is stored directly in the database, rather than as a custom profile field. You can choose to either convert it into a new profile field, or not convert it at all. If creating a new field, then you may enter the name of the field into the textbox.",
	'avatars'							=> "Avatars",
	'profile_photos'					=> "Profile Photos",
	'conv_store_database'				=> "Database",
	'conv_store_file_system'			=> "File System",
	'no_convert'						=> "Do not convert",
	'create_field'						=> "Create New Field",
	'member_exists'						=> "Member %s exists as %s.",
	'member_email_invalid'				=> "Member email invalid (%s) using %s instead.",
	'member_name_in_use'				=> "Name '%s' is currently in use, member renamed to '%s'",
	'member_name_too_long'				=> "Name '%s' is too long, member renamed to '%s'",
	'member_name_invalid_chars'			=> "Name '%s' contained invalid characters, member renamed to '%s'",
	'member_missing_name'				=> "Members name missing, member renamed to %s",
	'username_or_display_name'			=> "Name to keep",
	'user_name'							=> "User Name",
	'display_name'						=> "Display Name",
	'username_hint'						=> "You can only convert one name, do you want to keep usernames or display names?",
	'convert_member_history'			=> "Convert Member History",
	'_convert_member_history'			=> "Member History",
	
	/* !Convert Status Updates */
	'convert_statuses'					=> "Convert Status Updates / Profile Comments",
	'convert_status_replies'			=> "Convert Status Comments",
	'_convert_statuses'					=> "Status Updates / Profile Comments",
	'_convert_status_replies'			=> "Status Comments",
	'status_update_missing_ids'			=> "Status Update Missing ID",
	'status_update_no_member'			=> "No Member ID provided.",
	'status_update_no_author'			=> "No Author ID provided",
	'status_update_no_content'			=> "No comment text",
	
	/* !Convert Ignored Users */
	'convert_ignored_users'				=> "Convert Ignored Users",
	'_convert_ignored_users'			=> "Ignored Users",
	'ignored_user_missing_ids'			=> "Missing Ignore ID",
	'ignored_user_missing_owner'		=> "No Member ID provided",
	'ignored_user_missing_ignore'		=> "No Ignored Member ID provided",
	
	/* !Convert Announcements */
	'convert_announcements'				=> "Convert Announcements",
	'_convert_announcements'			=> "Announcements",
	'announcement_missing_id'			=> "Announcement Missing ID",
	'announcement_missing_title'		=> "Announcement Missing Title",
	'announcement_missing_content'		=> "Announcement Missing Content",
	'announcement_missing_member_id'	=> "Announcement Missing Member ID",
	
	/* !Convert Private Message */
	'convert_private_messages'			=> "Convert Private Messages",
	'_convert_private_messages'			=> "Private Messages",
	'private_message_topic_ids_missing'	=> "PM missing topic ID",
	'private_message_topic_no_posts'	=> "PM does not have any posts",
	'private_message_topic_no_users'	=> "PM does not have any users",
	'private_message_topic_title_missing' => "PM title is missing.",
	'private_message_topic_starter_missing' => "PM starter missing.",
	'private_message_post_missing_ids'	=> "PM post missing ID",
	'private_message_post_no_content'	=> "PM post missing content",
	'private_message_map_missing_user'	=> "PM map missing user",
	'private_message_topic_missing_maps'=> "No member maps inserted.",
	'convert_private_message_replies'	=> "Convert Private Message Replies",
	'_convert_private_message_replies'	=> "Private Message Replies",
	
	/* !Convert Display Name Change Logs */
	'convert_dname_changes'				=> "Convert Display Name Change Logs",
	'_convert_dname_changes'			=> "Display Name Change Logs",
	
	/* !Convert Ranks */
	'convert_ranks'						=> "Convert Member Ranks",
	'_convert_ranks'					=> "Member Ranks",
	'rank_missing_ids'					=> "Rank ID Missing",
	'rank_missing_title'				=> "Rank Missing Title",
	'rank_location'						=> "Rank Image Location",
	
	/* !Convert Ratings */
	'core_rating_duplicate'				=> "Duplicate Rating",
	'convert_ratings'					=> "Convert Ratings",
	'_convert_ratings'					=> "Ratings",
	
	/* !Convert Profanity Filters */
	'convert_profanity_filters'			=> "Convert Profanity Filters",
	'_convert_profanity_filters'		=> "Profanity Filters",
	
	/* !Convert Banfilters */
	'convert_banfilters'				=> "Convert Ban Filters",
	'convert_banfilters2'				=> "Convert Ban Filters",
	'_convert_banfilters'				=> "Ban Filters",
	'_convert_banfilters2'				=> "Ban Filters",
	
	/* !Convert Question and Answer */
	'convert_question_and_answers'		=> "Convert Question and Answer Verification",
	'_convert_question_and_answers'		=> "Question and Answer Verification",

	/* !Convert Reputation Levels */
	'convert_reputation_levels'			=> "Convert Reputation Levels",
	'_convert_reputation_levels'		=> "Reputation Levels",
	
	/* !Convert Warning Actions */
	'convert_warn_actions'				=> "Convert Warning Actions",
	'_convert_warn_actions'				=> "Warning Actions",
	
	/* !Convert Warning Reasons */
	'convert_warn_reasons'				=> "Convert Warning Reasons",
	'_convert_warn_reasons'				=> "Warning Reasons",

	/* !Convert Moderators */
	'convert_moderators'				=> "Convert Moderators",
	'_convert_moderators'				=> "Moderators",
	
	/* !Convert Forums */
	'convert_forums_forums'				=> "Convert Forums",
	'convert_forums_forums_followers'   => "Convert Forum Followers",
	'_convert_forums_forums'			=> "Forums",
	'_convert_forums_forums_followers'  => "Forum Followers",
	'convert_forum_password'			=> "Password for %s",
	'convert_forum_password_desc'		=> "This forum has a password set, however we are unable to decrypt the password for conversion into Invision Community. Please enter the password you wish to use for this forum. <strong>Note:</strong> Not entering a password here will result in no password being set for the forum.",

	/* !Convert Topics Multimod */
	'convert_forums_topics_multimods'	=> "Convert Multi-moderation Settings",
	'_convert_forums_topics_multimods'	=> "Multi-moderation Settings",

	/* !Convert QA */
	'convert_forums_question_ratings'	=> "Convert Question Ratings",
	'convert_forums_answer_ratings'		=> "Convert Answer Ratings",
	'_convert_forums_question_ratings'	=> "Question Ratings",
	'_convert_forums_answer_ratings'	=> "Answer Ratings",

	/* !Convert Topics */
	'convert_forums_topics'				=> "Convert Topics",
	'convert_forums_topics_followers'   => 'Convert Topic Followers',
	'_convert_forums_topics'			=> "Topics",
	'_convert_forums_topics_followers'  => 'Topic Followers',

	/* !Convert Posts */
	'convert_forums_posts'				=> "Convert Posts",
	'convert_forums_archive_posts'      => "Convert Archived Posts",
	'_convert_forums_posts'				=> "Posts",
	'_convert_forums_archive_posts'     => "Archived Posts",

	/* !Convert RSS */
	'convert_forums_rss_imports'		=> "Convert RSS Feeds",
	'convert_forums_rss_imported'		=> "Convert Imported RSS Content",
	'_convert_forums_rss_imports'		=> "RSS Feeds",
	'_convert_forums_rss_imported'		=> "Imported RSS Content",
	
	/* !Convert Attachments */
	'convert_attachments'				=> "Convert Attachments",
	'convert_forums_attachments'		=> "Convert Post Attachments",
	'_convert_attachments'				=> "Attachments",
	'_convert_forums_attachments'		=> "Post Attachments",
	'attach_location'					=> "Path to attachments",

	/* !Convert Acronyms */
	'convert_acronyms'					=> "Convert Acronyms",
	'_convert_acronyms'					=> "Acronyms",

	/* !Convert Blogs */
	'convert_blogs'						=> "Convert Blogs",
	'convert_blog_categories'			=> "Convert Blog Categories",
	'convert_blog_entries'				=> "Convert Blog Entries",
	'convert_blog_entry_categories'		=> "Convert Blog Entry Categories",
	'convert_blog_comments'				=> "Convert Blog Entry Comments",
	'convert_blog_attachments'			=> "Convert Blog Entry Attachments",
	'_convert_blogs'					=> "Blogs",
	'_convert_blog_categories'			=> "Blog Categories",
	'_convert_blog_entries'				=> "Blog Entries",
	'_convert_blog_entry_categories'	=> "Blog Entry Categories",
	'_convert_blog_comments'			=> "Blog Entry Comments",
	'_convert_blog_attachments'			=> "Blog Entry Attachments",
	
	/* !Convert Calendars */
	'convert_calendar_calendars'		=> "Convert Calendars",
	'convert_calendar_events'			=> "Convert Calendar Events",
	'convert_calendar_comments'			=> "Convert Calendar Event Comments",
	'convert_calendar_reviews'			=> "Convert Calendar Event Reviews",
	'convert_calendar_attachments'		=> "Convert Calendar Event Attachments",
	'convert_calendar_venues'			=> "Convert Calendar Event Venues",
	'convert_calendar_reminders'		=> "Convert Calendar Event Reminders",
	'_convert_calendar_calendars'		=> "Calendars",
	'_convert_calendar_events'			=> "Calendar Events",
	'_convert_calendar_comments'		=> "Calendar Event Comments",
	'_convert_calendar_reviews'			=> "Calendar Event Reviews",
	'_convert_calendar_attachments'		=> "Calendar Event Attachments",
	'_convert_calendar_venues'			=> "Calendar Event Venues",
	'_convert_calendar_reminders'		=> "Calendar Event Reminders",
	
	/* !Convert Gallery */
	'convert_gallery_categories'		=> "Convert Gallery Categories",
	'convert_gallery_albums'			=> "Convert Gallery Albums",
	'convert_gallery_album_comments'	=> "Convert Gallery Album Comments",
	'convert_gallery_album_reviews'		=> "Convert Gallery Album Reviews",
	'convert_gallery_images'			=> "Convert Gallery Images",
	'convert_gallery_comments'			=> "Convert Gallery Image Comments",
	'convert_gallery_reviews'			=> "Convert Gallery Image Reviews",
	'convert_gallery_attachments'		=> "Convert Gallery Image Attachments",
	'members_gallery_category'			=> "Members Gallery Category",
	'_convert_gallery_categories'		=> "Gallery Categories",
	'_convert_gallery_albums'			=> "Gallery Albums",
	'_convert_gallery_album_comments'	=> "Gallery Album Comments",
	'_convert_gallery_album_reviews'	=> "Gallery Album Reviews",
	'_convert_gallery_images'			=> "Gallery Images",
	'_convert_gallery_comments'			=> "Gallery Image Comments",
	'_convert_gallery_reviews'			=> "Gallery Image Reviews",
	'_convert_gallery_attachments'		=> "Gallery Image Attachments",
	'members_gallery_category_desc'		=> "Invision Community requires all albums belong to a category. Please select the category to place albums with no category into, or select None to create one automatically.",
	'media_thumb_location'				=> "Media Thumbnail Location",
	
	/* !Convert Downloads */
	'convert_author_replies_to_comments'		=> "Convert author replies to comments?",
	'convert_author_replies_to_comments_desc'	=> "If Yes, then replies by the author to reviews will be converted into normal comments, with the review in quotes. If No, replies will not be converted.",
	'convert_downloads_cfields'			=> "Convert File Custom Fields",
	'convert_downloads_categories'		=> "Convert File Categories",
	'convert_downloads_files'			=> "Convert Files",
	'convert_downloads_reviews'			=> "Convert File Reviews",
	'convert_downloads_comments'		=> "Convert File Comments",
	'_convert_downloads_cfields'		=> "File Custom Fields",
	'_convert_downloads_categories'		=> "File Categories",
	'_convert_downloads_files'			=> "Files",
	'_convert_downloads_reviews'		=> "File Reviews",
	'_convert_downloads_comments'		=> "File Comments",
	
	/* !Convert Pages */
	'convert_cms_pages'					=> "Convert Pages",
	'convert_cms_databases'				=> "Convert Databases",
	'convert_cms_database_categories'	=> "Convert Database Categories",
	'convert_cms_database_records'		=> "Convert Database Records",
	'convert_cms_database_comments'		=> "Convert Database Comments",
	'convert_cms_database_reviews'		=> "Convert Database Reviews",
	'convert_cms_media'					=> "Convert Media",
	'convert_cms_blocks'				=> "Convert Blocks",
	'convert_cms_attachments'			=> "Convert Database Attachments",
	'_convert_cms_pages'				=> "Pages",
	'_convert_cms_databases'			=> "Databases",
	'_convert_cms_database_categories'	=> "Database Categories",
	'_convert_cms_database_records'		=> "Database Records",
	'_convert_cms_database_comments'	=> "Database Comments",
	'_convert_cms_database_reviews'		=> "Database Reviews",
	'_convert_cms_media'				=> "Media",
	'_convert_cms_blocks'				=> "Blocks",
	'_convert_cms_attachments'			=> "Database Attachments",
	
	/* !Convert Clubs */
	'convert_clubs'						=> "Convert Clubs",
	'convert_club_members'				=> "Convert Club Members",
	'convert_club_pages'				=> "Convert Club Pages",
	'convert_club_forums'				=> "Convert Club Forums",
	'convert_club_topics'				=> "Convert Club Topics",
	'convert_club_posts'				=> "Convert Club Topic Posts",
	'convert_club_blogs'				=> "Convert Club Blogs",
	'convert_club_blog_entries'			=> "Convert Club Blog Entries",
	'convert_club_blog_comments'		=> "Convert Club Blog Entry Comments",
	'convert_club_downloads_categories'	=> "Convert Club File Categories",
	'convert_club_downloads_files'		=> "Convert Club Files",
	'convert_club_downloads_comments'	=> "Convert Club File Comments",
	'convert_club_downloads_reviews'	=> "Convert Club File Reviews",
	'convert_club_gallery_categories'	=> "Convert Club Gallery Categories",
	'convert_club_gallery_images'		=> "Convert Club Gallery Images",
	'convert_club_gallery_comments'		=> "Convert Club Gallery Image Comments",
	'convert_club_gallery_reviews'		=> "Convert Club Gallery Image Reviews",
	'_convert_clubs'					=> "Clubs",
	'_convert_club_members'				=> "Club Members",
	'_convert_club_pages'				=> "Club Pages",
	'_convert_club_forums'				=> "Club Forums",
	'_convert_club_topics'				=> "Club Topics",
	'_convert_club_posts'				=> "Club Topic Posts",
	'_convert_club_blogs'				=> "Club Blogs",
	'_convert_club_blog_entries'		=> "Club Blog Entries",
	'_convert_club_blog_comments'		=> "Club Blog Entry Comments",
	'_convert_club_downloads_categories'=> "Club File Categories",
	'_convert_club_downloads_files'		=> "Club Files",
	'_convert_club_downloads_comments'	=> "Club File Comments",
	'_convert_club_downloads_reviews'	=> "Club File Reviews",
	'_convert_club_gallery_categories'	=> "Club Gallery Categories",
	'_convert_club_gallery_images'		=> "Club Gallery Images",
	'_convert_club_gallery_comments'	=> "Club Gallery Image Comments",
	'_convert_club_gallery_reviews'		=> "Club Gallery Image Reviews",
	'club_photo_location_desc'			=> "If club photos are presently stored in the database, then select 'Database', otherwise select 'File System' and then enter the absolute path to club photos in the textbox provided.",
	'club_photo_location_nodb_desc'		=> "The path to club photos.",

	/* !Miscellaneous Strings */
	'queue_deleting_empty_topics'		=> "Deleting empty topics",
	'queue_rebuilding_gallery_images'	=> "Rebuilding Gallery Images",
	'queue_rebuilding_conversation_first_id' => "Rebuilding Personal Conversation first post ids",
	'queue_rebuilding_tag_cache'		=> "Rebuilding %s tags",
	'queue_recounting_question_ratings' => "Rebuilding Question Ratings",
	'queue_recounting_answer_ratings'	=> "Rebuilding Answer Ratings",
	'queue_recounting_club_members'		=> "Recounting Club Members",
	'continue_conversion'				=> "Continue Conversion",

	/* !Convert Nexus/Commerce */
	'convert_nexus_customers'			=> "Convert Customers",
	'convert_nexus_payment_methods'		=> "Convert Payment Methods",
	'convert_nexus_package_groups'		=> "Convert Package Groups",
	'convert_nexus_packages'			=> "Convert Packages",
	'convert_nexus_invoices'			=> "Convert Invoices",
	'convert_nexus_transactions'		=> "Convert Transactions",
	'convert_nexus_purchases'			=> "Convert Purchases",
	'_convert_nexus_customers'			=> "Customers",
	'_convert_nexus_package_groups'		=> "Package Groups",
	'_convert_nexus_packages'			=> "Packages",
	'_convert_nexus_invoices'			=> "Invoices",
	'_convert_nexus_transactions'		=> "Transactions",
	'_convert_nexus_purchases'			=> "Purchases",

	/* Finish messages */
	'f_blog_entries_rebuilding'			=> "Rebuilding blog entries",
	'f_entry_comments_rebuilding'		=> "Rebuilding entry comments",
	'f_blogs_recounting'				=> "Resyncing blog counts",
	'f_entry_tags_cache'				=> "Rebuilding blog entry tags",
	'f_gallery_images_rebuild'			=> "Rebuilding gallery images",
	'f_gallery_cat_recount'				=> "Resyncing gallery category counts",
	'f_gallery_album_recount'			=> "Resyncing gallery album counts",
	'f_gallery_image_recount'			=> "Resyncing gallery image counts",
	'f_image_tags_recount'				=> "Rebuilding gallery image tags",
	'f_forum_last_post_data'			=> "Resyncing forum last post information",
	'f_rebuild_posts'					=> "Rebuilding posts",
	'f_recounting_forums'				=> "Resyncing forum counts",
	'f_recounting_topics'				=> "Resyncing topic counts",
	'f_topic_tags_recount'				=> "Rebuilding topic tags",
	'f_search_index_rebuild'			=> "Rebuilding search index",
	'f_clear_caches'					=> "Clearing caches",
	'f_rebuild_pms'						=> "Rebuilding private messages",
	'f_signatures_rebuild'				=> "Rebuilding signatures",
	'f_announce_rebuild'				=> "Rebuilding announcements",
	'f_rebuild_attachments'				=> "Rebuilding attachment thumbnails",
	'f_recount_cms_categories'			=> "Resyncing database category counts",
	'f_rebuild_cms_tags'				=> "Rebuilding database tags",
	'f_rebuild_events'					=> "Rebuilding calendar events",
	'f_recount_calendar'				=> "Resyncing calendar and event counts",

	/* API */
	'__api_convert_converters'			=> "Converters",
	
	/* !ACP Restrictions */
	'r__manage'							=> "Manage Conversions",
	'r__manage_manage'					=> "Can manage conversions",
	'r__convert'						=> "Conversions",
	'r__convert_manage'					=> "Can run conversions",
	'r__create'							=> "Create Conversions",
	'r__create_manage'					=> "Can create conversions",

);
