<ips:template parameters="$topic, $email" />
<tr style='border-bottom: 1px solid #eeeeee'>
	<td dir='{dir}' width='40' align='center' valign='top' class=' '>
		<img src='{$topic->author()->get_photo( true, true )}' width='32' height='32' style='border: 1px solid #000; vertical-align: middle;'>
	</td>
	<td dir='{dir}' align='left'>
		<p style='font-family: "Helvetica Neue", helvetica, sans-serif; margin: 0; font-size: 13px; font-weight: bold'>
			{{if $topic->isQuestion()}}
				{$email->language->addToStack("x_asked_new_question", FALSE, array( 'sprintf' => array( $topic->author()->name, $topic->container()->getTitleForLanguage( $email->language ) ) ) )}
			{{else}}
				{$email->language->addToStack("x_created_topic_in", FALSE, array( 'sprintf' => array( $topic->author()->name, $topic->container()->getTitleForLanguage( $email->language ) ) ) )}
			{{endif}}
		</p>
		<h2 style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 20px; font-weight: 500 !important; margin: 0;">
			<a href='{$topic->url()}' style='text-decoration: none;'>{$topic->title}</a>
			{{if $topic->mapped('featured')}}&nbsp;&nbsp;<span style='color: #68a72f; font-weight: bold; font-size: 12px; text-transform: uppercase;'>{$email->language->addToStack("featured", FALSE)}</span>{{endif}}
		</h2>
		<div style="font-family: 'Helvetica Neue', helvetica, sans-serif; line-height: 22px; margin-top: 10px; margin-bottom: 10px;">
			{$email->parseTextForEmail( $topic->content(), $email->language, ( \IPS\Settings::i()->email_truncate ? 150 : NULL ) )|raw}
		</div>
		<p style="font-family: 'Helvetica Neue', helvetica, sans-serif; margin: 0; font-size: 13px;">

			{{if $topic->isQuestion()}}
				<strong style="font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 12px; color: #4a7c20; display: inline-block;">&#10003; {$email->language->addToStack("answered", FALSE)}</strong>&nbsp;&nbsp;&nbsp;&nbsp;
			{{endif}}

			{{if $topic->container()->forum_allow_rating}}
				{{foreach range( 1, 5 ) as $i}}{{if $i <= $topic->averageRating()}}<img src='{resource="email/rating_on.png" location="interface" app="core"}' width='14' height='13' style='vertical-align: middle; margin-right: 2px'>{{elseif ( $i - 0.5 ) <= $topic->averageRating()}}<img src='{resource="email/rating_half.png" location="interface" app="core"}' width='14' height='13' style='vertical-align: middle; margin-right: 2px'>{{else}}<img src='{resource="email/rating_off.png" location="interface" app="core"}' width='14' height='13' style='vertical-align: middle; margin-right: 2px'>{{endif}}{{endforeach}}
				&nbsp;&nbsp;&nbsp;&nbsp;
 			{{endif}}

			<strong>
				<img src='{resource="email/comment.png" location="interface" app="core"}' width='13' height='12' style='vertical-align: middle'>&nbsp; 
				{{if $topic->isQuestion()}}
					{$email->language->addToStack("answers_number", FALSE, array( 'pluralize' => array( ( $topic->posts ) ? $topic->posts - 1 : 0 ) ) )}
				{{else}}
					{$email->language->addToStack("replies_number", FALSE, array( 'pluralize' => array( ( $topic->posts ) ? $topic->posts - 1 : 0 ) ) )}
				{{endif}}
			</strong>
		</p>
	</td>
</tr>