<ips:template parameters="$member" />
<li class='ipsPhotoPanel ipsPhotoPanel_mini ipsPad_half ipsClearfix' data-role='result'>
	<a href="{$member->acpUrl()}" class="ipsUserPhoto ipsUserPhoto_mini" target="_blank" rel='noopener'>
		<img src='{$member->photo}'>
	</a>
	<div>
		<h2 class='ipsType_sectionHead'><strong><a href='{$member->acpUrl()}'>{$member->cm_name}</a></strong></h2><br>
		{$member->email}
	</div>
</li>