<ips:template parameters="$account" />
<li class='ipsPhotoPanel ipsPhotoPanel_mini ipsPad_half ipsClearfix' data-role='result'>
	<div>
		<h2 class='ipsType_sectionHead'>
			<strong><a href='{$account->purchase()->acpUrl()}' class='ipsPos_left'>{$account->domain}</a></strong>
		</h2><br>
		{$account->server->hostname} &middot; {$account->username} &middot; {$account->purchase()->name} &middot; {$account->purchase()->member->cm_name}
	</div>
</li>