<ips:template parameters="$purchase" />
<li class='ipsPhotoPanel ipsPhotoPanel_mini ipsPad_half ipsClearfix' data-role='result'>
	<div>
		<h2 class='ipsType_sectionHead'>
			<strong><a href='{$purchase->acpUrl()}' class='ipsPos_left'>{$purchase->name}</a></strong>
			&nbsp;
			{{if $purchase->cancelled}}
				<span class="ipsBadge ipsBadge_style5">{lang="purchase_canceled"}</span>
			{{elseif !$purchase->active}}
				<span class="ipsBadge ipsBadge_style6">{lang="purchase_expired"}</span>
			{{endif}}
		</h2><br>
		{lang="purchase_number" sprintf="$purchase->id"} &middot; {$purchase->member->cm_name}
	</div>
</li>