<ips:template parameters="$support" />
<li class='ipsPhotoPanel ipsPhotoPanel_mini ipsPad_half ipsClearfix' data-role='result'>
	<div>
		<h2 class='ipsType_sectionHead'>
			<strong><a href='{$support->acpUrl()}' class='ipsPos_left'>{$support->title}</a></strong>
		</h2><br>
		#{$support->id} &middot; {$support->status->_title} &middot; {$support->department->_title} &middot; {$support->supportAuthor()->name()}
	</div>
</li>