<ips:template parameters="$url, $item" />

{{if $item instanceof \IPS\cms\Media}}
	<li class='ipsGrid_span4' data-role='mediaItem' data-fileid='{$item->id}' data-uploaded='{datetime="$item->added" dateonly="true"}' data-path='{$item->full_path}' data-filename='{$item->filename}' data-url='{$item->url()}?_cb={expression="time()"}' data-fileType='{{if $item->is_image}}image{{else}}file{{endif}}'>
		<div class='cMedia_item {{if $item->is_image}}cMedia_itemImage{{endif}}'>
			<div class='ipsAreaBackground_light'>
				{{if $item->is_image}}
					<img src='{$item->url()}?_cb={expression="time()"}'>
				{{else}}
					<div class='ipsNoThumb'></div>
				{{endif}}
			</div>
			<p class='cMedia_filename ipsType_reset ipsTruncate ipsTruncate_line'>{$item->filename}</p>
		</div>
	</li>
{{endif}}