<ips:template parameters="$canAdd" />
<div class='ipsAreaBackground_light ipsPad ipsClearfix'>
	<div>
		<h2 class='ipsType_sectionHead'><strong>{lang="profile_complete_blurb_title"}</strong></h2>
		<div class='ipsType_normal ipsType_reset'>
			{lang="profile_complete_blurb_desc"}
			{{if ! $canAdd}}
				<div class="ipsMessage ipsMessage_info">
					{lang="profile_complete_no_add"}
				</div>
			{{endif}}
		</div>
	</div>
</div>