<ips:template parameters="$customer, $table, $title, $type" />
<div class="ipsBox ipsSpacer_bottom">
	{{$count = \count( $table->getRows(NULL) );}}
	<h3 class='ipsBox_titleBar'>{{if $count}}<strong>{{endif}}{$title}{{if $count}}</strong>{{endif}}</h3>
	<div class="ipsPad">
		{$table|raw}
		<p class='ipsType_reset ipsSpacer_top ipsSpacer_half'>
			<a href='{url="app=core&module=members&controller=members&do=editBlock&block=IPS\\core\\extensions\\core\\MemberACPProfileBlocks\\Referrals&id={$customer->member_id}"}' data-ipsDialog data-ipsDialog-title='{lang="customer_tab_{$type}"}' class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_fullWidth'>
				{lang="customer_manage_{$type}"}
			</a>
		</p>
	</div>
</div>