<ips:template parameters="$name, $value, $easy" />
<div data-controller="core.admin.members.allowedCharacters" data-easy="{{if $easy}}1{{else}}0{{endif}}">
	<input type="hidden" name="{$name}[easy]" value="0" data-role="easyInput">
	<div data-role="easy" class="ipsHide">
		<ul class="ipsField_fieldList">
			<li>
				<strong>{lang="username_characters_letters"}</strong>
				<ul class="ipsField_fieldList ipsClearfix" role="radiogroup">
					<li>
						<span class='ipsCustomInput'>
							<input type="radio" name="{$name}[letters]" value="all" id="elRadio_{$name}_letters_all" {{if !$easy or $easy['letters'] === 'all'}}checked{{endif}}>
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_letters_all'>{lang="username_characters_letters_all"}</label>
						</div>
					</li>
					<li>
						<span class='ipsCustomInput'>
							<input type="radio" name="{$name}[letters]" value="latin" id="elRadio_{$name}_letters_latin" {{if $easy and $easy['letters'] === 'latin'}}checked{{endif}}>
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_letters_latin'>{lang="username_characters_letters_latin"}</label>
						</div>
					</li>
				</ul>
			</li>
			<li>
				<strong>{lang="username_characters_numbers"}</strong>
				<ul class="ipsField_fieldList ipsClearfix" role="radiogroup">
					<li>
						<span class='ipsCustomInput'>
							<input type="radio" name="{$name}[numbers]" value="all" id="elRadio_{$name}_numbers_all" {{if !$easy or $easy['numbers'] === 'all'}}checked{{endif}}>
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_numbers_all'>{lang="username_characters_numbers_all"}</label>
						</div>
					</li>
					<li>
						<span class='ipsCustomInput'>
							<input type="radio" name="{$name}[numbers]" value="arabic" id="elRadio_{$name}_numbers_arabic" {{if $easy and $easy['numbers'] === 'arabic'}}checked{{endif}}>
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_letters_latin'>{lang="username_characters_numbers_arabic"}</label>
						</div>
					</li>
					<li>
						<span class='ipsCustomInput'>
							<input type="radio" name="{$name}[numbers]" value="none" id="elRadio_{$name}_numbers_none" {{if $easy and $easy['numbers'] === 'none'}}checked{{endif}}>
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_letters_latin'>{lang="none"}</label>
						</div>
					</li>
				</ul>
			</li>
			<li>
				<strong>{lang="username_characters_special"}</strong>
				<ul class="ipsField_fieldList ipsClearfix" role="radiogroup">
					<li>
						<span class='ipsCustomInput'>
							<input type="checkbox" name="{$name}[spaces]" value="1" id='elRadio_{$name}_spaces' {{if !$easy or $easy['spaces']}}checked{{endif}}>
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_spaces'>{lang="username_characters_spaces"}</label><br>
							<span class='ipsFieldRow_desc'>{lang="username_characters_spaces_desc"}</span>
						</div>
					</li>
					<li>
						<span class='ipsCustomInput'>
							<input type="checkbox" name="{$name}[extra_enabled]" value="1" id='elRadio_{$name}_extra' {{if !$easy or $easy['extra']}}checked{{endif}} data-control="toggle" data-toggles="elRadio_{$name}_extra_input">
							<span></span>
						</span>
						<div class='ipsField_fieldList_content'>
							<label for='elRadio_{$name}_extra'>{lang="username_characters_extra"}</label>
							<div id="elRadio_{$name}_extra_input">
								<input type="text" name="{$name}[extra]" value="{{if $easy}}{$easy['extra']}{{else}}_.-,{{endif}}">
							</div>
						</div>
					</li>
				</ul>
			</li>
		</ul>
		<br>
		<a href="#" class="ipsHide" data-action="regex">{lang="username_characters_regex"}</a>
	</div>
	<div data-role="regex">
		<input type="text" name="{$name}[regex]" value="{$value}" placeholder="/^[A-Z0-9]+$/i"> <a href="#" class="ipsHide" data-action="easy">{lang="username_characters_easy"}</a>
	</div>
</div>