<ips:template parameters="$customer, $sparkline, $primaryBillingAddress, $addressCount" />
<div class="ipsPad">
    {{if $sparkline }}
	<div id='elCustomerIncome'>{$sparkline|raw}</div>
	<p class='ipsType_reset ipsType_light ipsType_small ipsSpacer_top ipsSpacer_half'>
		{lang="revenue_past_12_months"}
	</p>
	{{endif}}

	{{if \IPS\Member::loggedIn()->hasAcpRestriction( 'nexus', 'customers', 'customers_view_credit' )}}
	<hr class='ipsHr'>
	{{foreach \IPS\nexus\Money::currencies() as $currency}}
		<div class='ipsAreaBackground{{if isset( $customer->cm_credits[ $currency ] ) && $customer->cm_credits[ $currency ]->amount->isGreaterThanZero()}}_positive{{endif}} ipsPad_half ipsType_center ipsType_large cCustomerCredit'>
			<h2 class='ipsType_reset ipsType_minorHeading'>{lang="client_credit"}</h2>
			{{if isset( $customer->cm_credits[ $currency ] )}}
				{$customer->cm_credits[ $currency ]}
			{{else}}
				{money="0" currency="$currency"}
			{{endif}}
			{{if member.hasAcpRestriction( 'nexus', 'customers', 'customers_edit_credit' )}}
				<p class='ipsType_reset'><a href='{url="app=nexus&module=customers&controller=view&id={$customer->member_id}&do=credits"}' data-ipsDialog data-ipsDialog-title='{lang="edit_credit"}' data-ipsDialog-size='narrow' class='ipsType_small'>{lang="edit"}</a></p>
			{{endif}}
		</div>
	{{endforeach}}
	{{endif}}

	<hr class='ipsHr'>
	
	<h2 class='ipsType_sectionHead ipsType_large'>{lang="primary_address"}</h2>
	{{if $primaryBillingAddress}}
		<p class='ipsType_reset ipsType_medium ipsSpacer_top ipsSpacer_half'>
			{$primaryBillingAddress->toString('<br>')|raw}
			{{if isset( $primaryBillingAddress->vat ) and $primaryBillingAddress->vat}}
				<br>
				{lang="cm_checkout_vat_number"}: {template="vatNumber" app="nexus" group="global" params="$primaryBillingAddress->vat"}
			{{endif}}
		</p>
	{{else}}
		<p class='ipsType_reset ipsType_medium ipsSpacer_top ipsSpacer_half ipsType_light'>
			{lang="no_primary_address"}
		</p>
	{{endif}}
	<p class='ipsType_reset'>
		<a href='{url="app=nexus&module=customers&controller=view&id={$customer->member_id}&do=addresses"}' data-ipsDialog data-ipsDialog-title='{lang="customer_addresses"}' class='ipsType_small'>{lang="edit_addresses_count" sprintf="$addressCount"}</a>
	</p>
	
	{{if \count( \IPS\nexus\Customer\CustomField::roots() ) or member.hasAcpRestriction( 'nexus', 'customers', 'customers_edit_details' )}}
		<hr class='ipsHr'>
		<h2 class='ipsType_sectionHead ipsType_large ipsSpacer_bottom ipsSpacer_half'>{lang="customer_information"}</h2>
		{{if member.hasAcpRestriction( 'nexus', 'customers', 'customers_edit_details' )}}
			<p class='ipsType_reset ipsSpacer_bottom ipsSpacer_half'>
				<a href='{url="app=nexus&module=customers&controller=view&id={$customer->member_id}&do=edit"}' class='ipsType_small' data-ipsDialog data-ipsDialog-title='{lang="edit_customer_info"}'>{lang="edit_information"}</a>
			</p>
		{{endif}}					
		{{foreach \IPS\nexus\Customer\CustomField::roots() as $field}}
			{{$column = $field->column;}}
			{{if $displayValue = $field->displayValue( $customer->$column, TRUE )}}
				<div class="ipsSpacer_bottom ipsSpacer_half">
					<h2 class='ipsType_reset ipsType_minorHeading'>{$field->_title}</h2>
					<p class='ipsType_reset ipsType_medium'>
						{$displayValue|raw}
					</p>
				</div>
			{{endif}}
		{{endforeach}}
	{{endif}}

	{{if member.hasAcpRestriction( 'nexus', 'customers', 'customers_void' )}}
		<hr class='ipsHr'>
		<a href="{url="app=nexus&module=customers&controller=view&do=void&id={$customer->member_id}"}" class="ipsButton ipsButton_verySmall ipsButton_negative ipsButton_fullWidth" data-ipsDialog data-ipsDialog-title="{lang="void_account"}">{lang="void_account"}</a>
	{{endif}}
</div>