<ips:template parameters="$customer, $table, $title, $type" />
<div class="ipsPad">
	{{$count = \count( $table->getRows(NULL) );}}
	<h3 class='ipsType_sectionHead ipsType_large ipsTruncate ipsTruncate_line {{if !$count}}ipsType_light{{endif}}'>{{if $count}}<strong>{{endif}}{$title}{{if $count}}</strong>{{endif}}</h3>
	{$table|raw}
	<p class='ipsType_reset ipsSpacer_top ipsSpacer_half'>
		<a href='{url="app=core&module=members&controller=members&do=editBlock&block=IPS\\nexus\\extensions\\core\\MemberACPProfileBlocks\\AccountInformation&id={$customer->member_id}&type={$type}"}' data-ipsDialog data-ipsDialog-title='{lang="customer_tab_{$type}"}' class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_fullWidth'>
			{lang="customer_manage_{$type}"} <i class='fa fa-caret-down'></i>
		</a>
	</p>
</div>