<ips:template parameters="$table, $headers, $rows" />

{{$billing = null;}}
{{$shipping = null;}}

{{foreach $rows as $row}}
	{{if $row['primary_billing'] == true}}
		{{$billing = $row;}}
	{{endif}}
	{{if $row['primary_shipping'] == true}}
		{{$shipping = $row;}}
	{{endif}}
{{endforeach}}

{{if $billing || $shipping}}
	<div class='ipsGrid ipsGrid_collapsePhone'>
		{{if $billing}}
			<div class='ipsGrid_span6 ipsAreaBackground_light ipsPad'>
				<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="address_default_billing"}</h2>
				{template="addressItem" group="customers" app="nexus" params="$billing"}
			</div>
		{{endif}}
		{{if $shipping}}
			<div class='ipsGrid_span6 ipsAreaBackground_light ipsPad'>
				<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="address_default_shipping"}</h2>
				{template="addressItem" group="customers" app="nexus" params="$shipping"}
			</div>
		{{endif}}
	</div>
{{endif}}

<hr class='ipsHr'>

{{if ( $billing && $shipping && \count( $rows ) > 2 ) || ( $billing || $shipping && \count( $rows ) > 1 ) || !$billing && !$shipping && \count( $rows )}}
	<ul class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='350' data-ipsGrid-maxItemSize='600' data-ipsGrid-equalHeights='row'>
		{{foreach $rows as $row}}
			{{if !$row['primary_billing'] && !$row['primary_shipping']}}
				<li class='ipsGrid_span6'>
					{template="addressItem" group="customers" app="nexus" params="$row"}
				</li>
			{{endif}}
		{{endforeach}}
	</ul>
{{endif}}