<ips:template parameters="$table, $headers, $rows, $quickSearch" />

{template="buttons" params="$table->rootButtons, ''" group="global" app="core" if="isset( $headers['_buttons'] )"}

{{if \count( $rows )}}
	<ul class='ipsList_inline cNexusCards ipsSpacer_top ipsType_center'>
		{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
	</ul>
{{else}}
	<p class='ipsType_light ipsType_large ipsType_center'>
		{lang="no_credit_cards"}
	</p>
{{endif}}