<ips:template parameters="$table, $headers, $rows" />

{{foreach $rows as $row}}
	<li class='ipsDataItem'>
		<div class='ipsDataItem_size4 ipsDataItem_generic ipsType_center'>
			<span class='cNexusCustomerInvoice'>{$row['i_total']}</span>
			{$row['i_status']|raw}
		</div>
		<div class='ipsDataItem_main'>
			<p class='ipsType_reset ipsType_normal ipsType_blendLinks'>
				{{if $row['_buttons']['view']}}
					<a href='{$row['_buttons']['view']['link']}'>
				{{endif}}
				{$row['i_title']|raw} <span class='ipsType_light ipsType_medium'>#{$row['i_id']}</span>
				{{if $row['_buttons']['view']}}
					</a>
				{{endif}}
			</p>
			<p class='ipsType_reset ipsType_medium'>
				<span class='ipsType_light'>{lang="invoice_created"} {datetime="$row['i_date']"}</span>
			</p>
		</div>
		<div class='ipsDataItem_generic ipsDataItem_size4 ipsType_right'>
			{template="controlStrip" params="$row['_buttons']" group="global" app="core"}
		</div>
	</li>
{{endforeach}}