<ips:template parameters="$customer, $invoices, $invoiceCount" />
<div class='ipsSpacer_bottom ipsSpacer_double'>
	<div class='ipsBox'>
		<h2 class='ipsBox_titleBar'>
			{{if $invoiceCount > $invoices->limit}}
				<a href="{url="app=nexus&module=payments&controller=invoices&member={$customer->member_id}"}" class="ipsPos_right ipsType_medium">{lang="see_all_invoices" pluralize="$invoiceCount"}</a>
			{{endif}}
			{lang="menu__nexus_payments_invoices"} ({$invoiceCount})
		</h2>
		<div class='ipsPad_half'>
			{$invoices|raw}
		</div>
	</div>
</div>