<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div class="ipsClearfix">
	{{if $table->pages > 1}}
		<div class="ipsPos_left ipsPad_half">
			{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
		</div>
	{{endif}}
	{template="buttons" params="$table->rootButtons, ''" group="global" app="core" if="isset( $headers['_buttons'] )"}
</div>
{{foreach $rows as $note}}
	<article class="ipsComment">
		<div class="ipsPos_right ipsPad_half">
			{template="controlStrip" params="$note['_buttons'], 'ipsControlStrip_showText'" group="global" app="core"}
		</div>
		<div class="ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini">
			{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $note['note_author'] ), 'mini'"}
			<div>
				<strong class="ipsType_large">{member="name" id="$note['note_author']"}</strong><br>
				<span class="ipsType_light">{datetime="$note['note_date']"}</span>
			</div>
		</div>
		<div class="ipsPadding_vertical sm:ipsPadding_vertical:half ipsPadding_horizontal ipsType_normal ipsType_richText ipsType_break ipsContained">
			{$note['note_text']|raw}
		</div>
	</article>
{{endforeach}}
{{if $table->pages > 1}}
	<div  class="ipsAreaBackground_light ipsPad_half">
		{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
	</div>
{{endif}}