<ips:template parameters="$customer, $noteCount, $notes" />
{{if $noteCount}}
	<div class='ipsSpacer_bottom ipsSpacer_double'>
		<div class='ipsBox cNotesBox'>
			<h2 class='ipsBox_titleBar'>
				<a href='{url="app=core&module=members&controller=members&do=lazyBlock&block=IPS\\nexus\\extensions\\core\\MemberACPProfileBlocks\\Notes&id={$customer->member_id}"}' data-ipsDialog data-ipsDialog-title='{lang="customer_notes"}' class='ipsPos_right ipsType_medium'>
					{lang="manage_notes"}
				</a>
				{lang="num_customer_notes_uc" pluralize="$noteCount"} ({$noteCount})
			</h2>
			<div class='ipsPad'>
				{$notes|raw}
			</div>
		</div>
	</div>
{{else}}
	<div class='ipsPad ipsType_light cCustomerNotes_none ipsSpacer_bottom'>
		<a href='{url="app=core&module=members&controller=members&do=lazyBlock&block=IPS\\nexus\\extensions\\core\\MemberACPProfileBlocks\\Notes&id={$customer->member_id}"}' data-ipsDialog data-ipsDialog-title='{lang="customer_notes"}' class='ipsPos_right ipsType_medium'>
			{lang="manage_notes"}
		</a>
		{lang="num_customer_notes_uc" pluralize="$noteCount"} ({$noteCount})
	</div>
{{endif}}