<ips:template parameters="$customer, $tabs, $activeTabKey, $activeTabContents" />
<div class='ipsBox ipsSpacer_bottom'>
	<h2 class="ipsBox_titleBar">{lang="purchases"}</h2>
	<div class='ipsTabs ipsTabs_stretch' id='elPurchasesTabs' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_elPurchasesTabs'>
		<a href="#elPurchasesTabs" data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		<ul role='tablist'>
			{{foreach $tabs as $k => $tab}}
			<li>
				<a href='{$customer->acpUrl()->setQueryString( array( 'do' => 'view', 'blockKey' => 'nexus_Purchases', 'block[nexus_Purchases]' => $k ) )}' class='ipsTabs_item ipsType_center  {{if $activeTabKey == $k}}ipsTabs_activeItem{{endif}}' id='purchase_tab_{$k}'>
				{lang="purchase_tab_{$k}"}
				({$tab['count']})
				</a>
			</li>
			{{endforeach}}
		</ul>
	</div>
	<div id='ipsTabs_content_elPurchasesTabs' class='ipsTabs_panels acpFormTabContent'>
		<div id='ipsTabs_elPurchasesTabs_purchase_tab_{$activeTabKey}_panel' class='ipsTabs_panel' aria-labelledby='purchase_tab_{$activeTabKey}' aria-hidden='false'>
			{$activeTabContents|raw}
		</div>
	</div>
</div>