<ips:template parameters="$table, $headers, $rows" />

{{foreach $rows as $row}}
	{{$obj = \IPS\nexus\Support\Request::load( $row['r_id'] );}}
	<tr class='ipsClearfix'>
		<td class='ipsType_center cNexusSupportTable_icon ipsPos_top'>
			<span class='ipsItemStatus'>{{if $obj->unread()}}<i class="fa fa-circle"></i>{{endif}}</span>
		</td>
		<td class='cNexusSupportTable_body ipsPos_top'>
			<span class='ipsType_large'>{$row['r_title']|raw}</span>
			<div class='ipsType_medium ipsType_richText ipsContained ipsType_break' data-ipsTruncate data-ipsTruncate-size='1 lines' data-ipsTruncate-type='remove'>
				{$obj->truncated}
			</div>
			<p class='ipsType_medium ipsType_reset '>
				<span>{lang="in_department" sprintf="$row['dpt_position']"}</span> {{if isset( $row['r_staff'] )}}&nbsp;&nbsp;<strong class='ipsType_success'>{lang="assigned_to_x" sprintf="$row['r_staff']"}</strong>{{endif}}
			</p>

			<p class='ipsType_medium ipsType_reset ipsType_light ipsType_blendLinks'>
				{lang="request_last_by_x" htmlsprintf="$row['r_last_reply_by'], $row['r_last_reply']"}
			</p>
		</td>
		<td class='cNexusSupportTable_status ipsType_right'>
			{$row['status_position']|raw}
		</td>
	</tr>
{{endforeach}}