<ips:template parameters="$customer, $support, $supportCount" />
<div>
	<div class='ipsBox'>
		<h2 class='ipsBox_titleBar'>
			{{if true or $supportCount > 15}}
				<a href="{url="app=nexus&module=support&controller=requests&member={$customer->member_id}" csrf="true"}" class="ipsPos_right ipsType_medium">{lang="see_all_support" pluralize="$supportCount"}</a>
			{{endif}}
			{lang="support"} ({$supportCount})
		</h2>
		<div class='ipsPad_half'>
			{$support|raw}
		</div>
	</div>
</div>