<ips:template parameters="$billingAddress = NULL, $shippingAddress = NULL, $otherAddresses" />
<a href='{url="app=nexus&module=clients&controller=addresses&do=form" seoTemplate="clientsaddresses"}' class='ipsPos_right ipsButton ipsButton_important ipsButton_verySmall' title="{lang="address_add_title"}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="address_add"}'>{lang="address_add"}</a>
<h1 class='ipsType_pageTitle'>{lang="address_book"}</h1>

<p class='ipsType_reset ipsType_normal ipsSpacer_bottom'>
	{lang="address_book_info"}
</p>

{{if $billingAddress || $shippingAddress}}
	<div class='ipsGrid ipsGrid_collapsePhone'>
		{{if $billingAddress}}
			<div class='ipsGrid_span6 ipsBox ipsPad'>
				<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="address_default_billing"}</h2>
				{template="address" group="clients" app="nexus" params="$billingAddress"}
			</div>
		{{endif}}
		{{if $shippingAddress}}
			<div class='ipsGrid_span6 ipsBox ipsPad'>
				<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="address_default_shipping"}</h2>
				{template="address" group="clients" app="nexus" params="$shippingAddress"}
			</div>
		{{endif}}
	</div>
{{endif}}

{{if \count( $otherAddresses )}}
	<hr class='ipsHr'>
	<div class='ipsPad'>
		<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="address_other_addresses"}</h2>
		<ul class='ipsGrid ipsGrid_collapsePhone' data-ipsGrid data-ipsGrid-minItemSize='350' data-ipsGrid-maxItemSize='600' data-ipsGrid-equalHeights='row'>
			{{foreach $otherAddresses as $address}}
				<li class='ipsGrid_span6'>
					{template="address" group="clients" app="nexus" params="$address"}
				</li>
			{{endforeach}}
		</ul>
	</div>
{{endif}}