<ips:template parameters="$protected=FALSE" />
<a href='{url="app=nexus&module=clients&controller=alternatives&do=form" seoTemplate="clientsalternatives"}' class='ipsPos_right ipsButton ipsButton_important ipsButton_verySmall' title="{lang="altcontact_add_title"}" data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="altcontact_add"}">{lang="altcontact_add"}</a>
<h1 class='ipsType_pageTitle'>{lang="altcontact_title"}</h1>

<p class='ipsType_reset ipsType_normal ipsSpacer_bottom'>
	{lang="altcontact_info"}
</p>

{{if !$protected}}
	{{if !\count( \IPS\nexus\Customer::loggedIn()->alternativeContacts() )}}
		<div class='ipsBox ipsPad ipsType_large ipsType_center ipsType_light'>
			{lang="altcontact_none" sprintf="\IPS\Member::loggedIn()->language()->addToStack('altcontact_add')"}
		</div>
	{{else}}
		<ul class='ipsBox ipsPad ipsDataList ipsDataList_large'>
			{{foreach \IPS\nexus\Customer::loggedIn()->alternativeContacts() as $contact}}
				<li class='ipsDataItem cAlternateContactPerms'>
					<div class='ipsDataItem_icon ipsPos_top'>
						{template="userPhoto" group="global" app="core" params="$contact->alt_id"}
					</div>
					<div class='ipsDataItem_main'>
						<h2 class='ipsDataItem_title ipsType_large ipsType_blendLinks'>
							<strong>{template="userLink" group="global" app="core" params="$contact->alt_id"} {lang="altcontact_can"}:</strong>
						</h2>
						<ul class='ipsList_reset cAlternateContactPerms_perms'>
							{{if \count( $contact->purchases )}}
								<li class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
									<span class='ipsBadge ipsBadge_icon ipsBadge_positive ipsPos_left'>
										<i class='fa fa-check'></i>
									</span>
									<div class='ipsType_normal'>
										{lang="altcontact_perm_manage" pluralize="\count( $contact->purchases ), \count( $contact->purchases )"}
										<ul class="ipsDataItem_subList ipsList_inline">
											{{foreach $contact->purchases as $purchase}}
												<li>
													<a href="{$purchase->url()}">{$purchase->name}</a>
												</li>
											{{endforeach}}
										</ul>
									</div>
								</li>
							{{endif}}
							{{if $contact->support}}
								<li class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
									<span class='ipsBadge ipsBadge_icon ipsBadge_positive ipsPos_left'>
										<i class='fa fa-check'></i>
									</span>
									<div class='ipsType_normal'>
										{lang="altcontact_perm_support"}
									</div>
								</li>
							{{else}}
								<li class='ipsPhotoPanel ipsPhotoPanel_tiny ipsFaded ipsClearfix'>
									<span class='ipsBadge ipsBadge_icon ipsBadge_neutral ipsPos_left'>
										<i class='fa fa-times'></i>
									</span> 
									<div class='ipsType_normal'>
										{lang="altcontact_perm_support"}
									</div>
								</li>
							{{endif}}
							{{if $contact->billing}}
								<li class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
									<span class='ipsBadge ipsBadge_icon ipsBadge_positive ipsPos_left'>
										<i class='fa fa-check'></i>
									</span>
									<div class='ipsType_normal'>
										{lang="altcontact_perm_billing"}
									</div>
								</li>
							{{else}}
								<li class='ipsPhotoPanel ipsPhotoPanel_tiny ipsFaded ipsClearfix'>
									<span class='ipsBadge ipsBadge_icon ipsBadge_neutral ipsPos_left'>
										<i class='fa fa-times'></i>
									</span> 
									<div class='ipsType_normal'>
										{lang="altcontact_perm_billing"}
									</div>
								</li>
							{{endif}}
						</ul>
					</div>
					<div class='ipsDataItem_generic ipsDataItem_size3 ipsPos_top'>
						<ul class='ipsToolList ipsToolList_vertical'>
							<li>
								<a href="{url="app=nexus&module=clients&controller=alternatives&do=form&id={$contact->alt_id->member_id}" seoTemplate="clientsalternatives"}" class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_fullWidth' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="altcontact_edit"}' title='{lang="altcontact_edit"}'>{lang="edit"}</a>
							</li>
							<li>
								<a href="{url="app=nexus&module=clients&controller=alternatives&do=delete&id={$contact->alt_id->member_id}" seoTemplate="clientsalternatives" csrf="true"}" class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_fullWidth' data-confirm data-confirmMessage="{lang="altcontact_delete_confirm"}" title="{lang="altcontact_delete"}">{lang="delete"}</a>
							</li>
						</ul>
					</div>
				</li>
			{{endforeach}}
		</ul>
	{{endif}}
{{endif}}