<ips:template parameters="$billingAgreements" />

<h1 class='ipsType_pageTitle'>{lang="billing_agreements_title"}</h1>

<p class='ipsType_reset ipsType_normal ipsSpacer_bottom'>
	{lang="billing_agreements_info"}
</p>

{{if !\count( $billingAgreements )}}
	<div class='ipsBox ipsPad ipsType_large ipsType_center ipsType_light'>
		{lang="billing_agreements_none"}
	</div>
{{else}}
	<ol class='ipsDataList ipsDataList_reducedSpacing'>
		{{foreach $billingAgreements as $billingAgreement}}
			<li class='ipsDataItem'>
				<div class='ipsDataItem_generic ipsDataItem_size1 ipsType_large ipsType_center ipsPos_middle'>
					{{if $billingAgreement['status'] === \IPS\nexus\Customer\BillingAgreement::STATUS_ACTIVE}}
						<span class='ipsBadge ipsBadge_icon ipsBadge_positive' data-ipsTooltip title='{lang="billing_agreement_active"}'>
							<i class='fa fa-check ipsType_large'></i>
						</span>
					{{elseif $billingAgreement['status'] === \IPS\nexus\Customer\BillingAgreement::STATUS_SUSPENDED}}
						<span class='ipsBadge ipsBadge_icon ipsBadge_neutral'  data-ipsTooltip title='{lang="billing_agreement_suspended"}'>
							<i class='fa fa-clock-o ipsType_large'></i>
						</span>
					{{elseif $billingAgreement['status'] === \IPS\nexus\Customer\BillingAgreement::STATUS_CANCELED}}
						<span class='ipsBadge ipsBadge_icon ipsBadge_negative'  data-ipsTooltip title='{lang="billing_agreement_canceled"}'>
							<i class='fa fa-times ipsType_large'></i>
						</span>
					{{else}}
						<span class='ipsBadge ipsBadge_icon ipsBadge_neutral'  data-ipsTooltip title='{lang="billing_agreement_unknown"}'>
							<i class='fa fa-question ipsType_large'></i>
						</span>
					{{endif}}
				</div>
				<div class='ipsDataItem_main'>
					<strong class='ipsType_large'>{$billingAgreement['id']}</strong>
					<p class='ipsDataItem_meta cNexusPrice'>
						{$billingAgreement['term']}
					</p>
				</div>
				<div class='ipsDataItem_generic ipsDataItem_size4 ipsType_right'>
					<a href="{$billingAgreement['url']}" class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="billing_agreement_view"}</a>
				</div>
			</tr>
		{{endforeach}}
	</ol>
{{endif}}