<ips:template parameters="$billingAgreement, $purchases, $invoices, $invoicePagination" />

<div class="ipsClearfix ipsSpacer_bottom">
	<div class='ipsType_large ipsType_center ipsPos_left ipsPad_half'>
		{{if $billingAgreement->status() === \IPS\nexus\Customer\BillingAgreement::STATUS_ACTIVE}}
			<span class='ipsBadge ipsBadge_icon ipsBadge_positive' data-ipsTooltip title='{lang="billing_agreement_active"}'>
				<i class='fa fa-check ipsType_large'></i>
			</span>
		{{elseif $billingAgreement->status() === \IPS\nexus\Customer\BillingAgreement::STATUS_SUSPENDED}}
			<span class='ipsBadge ipsBadge_icon ipsBadge_neutral'  data-ipsTooltip title='{lang="billing_agreement_suspended"}'>
				<i class='fa fa-clock-o ipsType_large'></i>
			</span>
		{{elseif $billingAgreement->status() === \IPS\nexus\Customer\BillingAgreement::STATUS_CANCELED}}
			<span class='ipsBadge ipsBadge_icon ipsBadge_negative'  data-ipsTooltip title='{lang="billing_agreement_canceled"}'>
				<i class='fa fa-times ipsType_large'></i>
			</span>
		{{endif}}
	</div>
	<div class="ipsPos_left">
		<h1 class='ipsType_pageTitle'>{lang="billing_agreement" sprintf="$billingAgreement->gw_id"}</h1>
		<span class="cNexusPrice ipsType_large">{$billingAgreement->term()}</span>
	</div>
	<div class="ipsPos_right ipsType_right ipsType_normal">
		{{if $billingAgreement->status() === \IPS\nexus\Customer\BillingAgreement::STATUS_ACTIVE}}
			<a href="{$billingAgreement->url()->setQueryString( array( 'do' => 'act', 'act' => 'suspend' ) )->csrf()}" class="ipsButton ipsButton_verySmall ipsButton_light" data-confirm data-confirmSubMessage="{lang="billing_agreement_suspend_confirm"}">{lang="billing_agreement_suspend"}</a>
		{{endif}}
		{{if $billingAgreement->status() === \IPS\nexus\Customer\BillingAgreement::STATUS_SUSPENDED}}
			<a href="{$billingAgreement->url()->setQueryString( array( 'do' => 'act', 'act' => 'reactivate' ) )->csrf()}" class="ipsButton ipsButton_verySmall ipsButton_light" data-confirm>{lang="billing_agreement_reactivate"}</a>
		{{endif}}
		{{if $billingAgreement->status() !== \IPS\nexus\Customer\BillingAgreement::STATUS_CANCELED}}
			<a href="{$billingAgreement->url()->setQueryString( array( 'do' => 'act', 'act' => 'cancel' ) )->csrf()}" class="ipsButton ipsButton_verySmall ipsButton_light" data-confirm>{lang="billing_agreement_cancel"}</a>
		{{endif}}
	</div>
</div>
{{if isset( $purchases[0] ) and \count( $purchases[0] )}}
	<hr class="ipsHr">
	<h2 class="ipsType_sectionHead ipsSpacer_bottom">{lang="billing_agreement_purchases"}</h2>
	<ul class='ipsList_reset'>
		{template="purchaseList" group="clients" params="0, $purchases, FALSE, $billingAgreement"}
	</ul>
{{endif}}
<hr class="ipsHr">
<h2 class="ipsType_sectionHead ipsSpacer_bottom">{lang="billing_agreement_payments"}</h2>
{{if $invoicePagination}}
	<div class="ipsBox ipsPadding:half ipsMargin_bottom">
		{$invoicePagination|raw}
	</div>
{{endif}}
	<ul class='ipsDataList ipsDataList_large cNexusOrderList'>
		{{foreach $invoices as $invoice}}
			{template="invoiceList" group="clients" params="$invoice, $billingAgreement"}
		{{endforeach}}
	</ul>
{{if $invoicePagination}}
	<div class="ipsBox ipsPadding:half ipsMargin_top">
		{$invoicePagination|raw}
	</div>
{{endif}}