<ips:template parameters="$invoices, $pagination" />
{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack('orders_title')"}
<div class="ipsBox">
	{{if \count( $invoices )}}
		{{if trim($pagination)}}
			<div class='ipsButtonBar ipsPad_half ipsClearfix ipsClear'>
				{$pagination|raw}
			</div>
		{{endif}}
		<ul class='ipsDataList ipsDataList_large cNexusOrderList'>
			{{foreach $invoices as $invoice}}
				{template="invoiceList" group="clients" params="$invoice"}
			{{endforeach}}
		</ul>
		{{if $pagination}}
			<div class='ipsButtonBar ipsPad_half ipsClearfix ipsClear'>
				{$pagination|raw}
			</div>
		{{endif}}
	{{else}}
		<div class='ipsType_center ipsPadding'>
			<p class="ipsType_reset ipsType_large">{lang="orders_none"}</p>
		</div>
	{{endif}}
</div>