<ips:template parameters="$invoice" />
<ul class='ipsDataList cNexusPaymentLog'>
	{{foreach $invoice->transactions( array( \IPS\nexus\Transaction::STATUS_PAID, \IPS\nexus\Transaction::STATUS_WAITING, \IPS\nexus\Transaction::STATUS_HELD, \IPS\nexus\Transaction::STATUS_REVIEW, \IPS\nexus\Transaction::STATUS_REFUSED, \IPS\nexus\Transaction::STATUS_REFUNDED, \IPS\nexus\Transaction::STATUS_PART_REFUNDED, \IPS\nexus\Transaction::STATUS_GATEWAY_PENDING ) ) as $thisTransaction}}
		<li class='ipsDataItem'>
			{{if $thisTransaction->status === $thisTransaction::STATUS_PAID}}
				<div class='ipsDataItem_icon ipsType_success'>
					<i class="fa fa-check-circle"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<strong>{lang="transaction_paid" sprintf="$thisTransaction->amount, ( $thisTransaction->method ) ? $thisTransaction->method->_title : \IPS\Member::loggedIn()->language()->get('account_credit')"}</strong>
					</p>
					<p class='ipsType_small ipsType_light ipsType_reset'>
						{datetime="$thisTransaction->date"}
					</p>
				</div>
			{{elseif $thisTransaction->status === $thisTransaction::STATUS_WAITING}}
				<div class='ipsDataItem_icon ipsType_issue'>
					<i class="fa fa-exclamation-triangle"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<a href="{$thisTransaction->url()}"><strong>{lang="transaction_wait" sprintf="$thisTransaction->method->_title"}</strong></a>
					</p>
				</div>
			{{elseif $thisTransaction->status === $thisTransaction::STATUS_HELD or $thisTransaction->status === $thisTransaction::STATUS_REVIEW}}
				<div class='ipsDataItem_icon ipsType_issue'>
					<i class="fa fa-clock-o"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<strong>{lang="transaction_awaiting_approval"}: {lang="transaction_paid" sprintf="$thisTransaction->amount, $thisTransaction->method->_title"}</strong>
						&nbsp;&nbsp;<span class='ipsType_light ipsType_noBreak'>{datetime="$thisTransaction->date"}</span>
					</p>
					{{if $thisTransaction->gw_id}}
						<p class='ipsType_small ipsType_light ipsType_reset'>
							{lang="payment_ref"}: {$thisTransaction->gw_id}
						</p>
					{{endif}}
				</div>
			{{elseif $thisTransaction->status === $thisTransaction::STATUS_GATEWAY_PENDING}}
				<div class='ipsDataItem_icon ipsType_issue'>
					<i class="fa fa-clock-o"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<strong>{lang="transaction_processing"}: {lang="transaction_paid" sprintf="$thisTransaction->amount, $thisTransaction->method->_title"}</strong>
						&nbsp;&nbsp;<span class='ipsType_light ipsType_noBreak'>{datetime="$thisTransaction->date"}</span>
					</p>
				</div>
			{{elseif $thisTransaction->status === $thisTransaction::STATUS_REFUSED}}
				<div class='ipsDataItem_icon ipsType_warning'>
					<i class="fa fa-times-circle"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<strong>{lang="transaction_declined" sprintf="$thisTransaction->amount, $thisTransaction->method->_title"}</strong>
					</p>
					{{if $thisTransaction->gw_id}}
						<p class='ipsType_small ipsType_light ipsType_reset'>
							{lang="payment_ref"}: {$thisTransaction->gw_id}
						</p>
					{{endif}}
				</div>
			{{elseif $thisTransaction->status === $thisTransaction::STATUS_REFUNDED}}
				<div class='ipsDataItem_icon ipsType_neutral'>
					<i class="fa fa-circle-arrow-left"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<strong>{lang="transaction_refunded" sprintf="$thisTransaction->amount, ( $thisTransaction->method ) ? $thisTransaction->method->_title : \IPS\Member::loggedIn()->language()->get('account_credit')"}</strong>
					</p>
					{{if $thisTransaction->gw_id}}
						<p class='ipsType_small ipsType_light ipsType_reset'>
							{lang="payment_ref"}: {$thisTransaction->gw_id}
						</p>
					{{endif}}
				</div>
			{{elseif $thisTransaction->status === $thisTransaction::STATUS_PART_REFUNDED}}
				<div class='ipsDataItem_icon ipsType_success'>
					<i class="fa fa-check-circle"></i>
				</div>
				<div class='ipsDataItem_main'>
					<p class='ipsType_normal ipsType_reset'>
						<strong>{lang="transaction_paid" sprintf="$thisTransaction->amount, ( $thisTransaction->method ) ? $thisTransaction->method->_title : \IPS\Member::loggedIn()->language()->get('account_credit')"}</strong>
						&nbsp;&nbsp;<span class='ipsType_light ipsType_noBreak'>{datetime="$thisTransaction->date"}</span>
					</p>
					{{if $thisTransaction->partial_refund->amount->isGreaterThanZero()}}
						<p class='ipsType_medium ipsType_reset'>
							{lang="transaction_part_refunded" sprintf="$thisTransaction->partial_refund"}
						</p>
					{{endif}}
					{{if $thisTransaction->credit->amount->isGreaterThanZero()}}
						<p class='ipsType_medium ipsType_reset'>
							{lang="transaction_part_credited" sprintf="$thisTransaction->credit"}
						</p>
					{{endif}}
					{{if $thisTransaction->gw_id}}
						<p class='ipsType_small ipsType_light ipsType_reset'>
							{lang="payment_ref"}: {$thisTransaction->gw_id}
						</p>
					{{endif}}
				</div>
			{{endif}}
		</li>
	{{endforeach}}
</ul>