<ips:template parameters="$purchase" />
{{try { $extra = $purchase->clientAreaPage(); } catch( \ErrorException $e ) { $extra = array(); } }}

<div class='ipsBox'>
<div class='ipsAreaBackground ipsPad cNexusPurchase_titleArea ipsClearfix'></div>

<div class='ipsColumns ipsColumns_collapsePhone cNexusPurchase'>
	<div class='ipsColumn ipsColumn_wide'>
		{{if $image = $purchase->image()}}
			<span class='cNexusPurchase_image' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image->url )"}" );'>&nbsp;</span>
		{{else}}
			<span class='ipsThumb ipsNoThumb {{if $purchase->type == 'giftvoucher'}}ipsNoThumb_gift{{else}}ipsNoThumb_product{{endif}}'>&nbsp;</span>
		{{endif}}

		<hr class='ipsHr'>

		{{if ( $purchase->expire AND $canRenewUntil = $purchase->canRenewUntil(NULL,TRUE) ) OR $purchase->canCancel()}}
			<ul class='ipsToolList ipsToolList_vertical cNexusPurchase_renewActions'>
				{{if $purchase->expire AND $canRenewUntil}}
					<li><a href="{url="app=nexus&module=clients&controller=purchases&do=renew&id={$purchase->id}" base="front" csrf="true" seoTemplate="clientspurchaserenew" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $purchase->name )"}" class='ipsButton ipsButton_important ipsButton_fullWidth ipsButton_small' title="{lang="purchase_renew_now_title"}" {{if $canRenewUntil === TRUE or $canRenewUntil > 1}}data-ipsDialog data-ipsDialog-size='narrow'{{endif}}>{lang="purchase_renew_now"}</a></li>
				{{endif}}
				{{if $purchase->canCancel()}}
					<li><a href="{url="app=nexus&module=clients&controller=purchases&do=cancel&id={$purchase->id}" base="front" csrf="true" seoTemplate="clientspurchasecancel" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $purchase->name )"}" class='ipsButton ipsButton_link ipsButton_fullWidth ipsButton_small' data-confirm data-confirmSubMessage="{lang="purchase_cancel_renewal_confirm"}">{lang="purchase_cancel_renewal"}</a></li>
				{{endif}}
			</ul>
		{{endif}}

		<dl class='ipsList_reset cNexusPurchase_info ipsSpacer_top'>
			<dt class='ipsType_minorHeading'><strong>{lang="ps_start"}</strong></dt>
			<dd class='ipsType_normal'>{$purchase->start->localeDate()}</dd>
			{{if $purchase->expire}}
				<dt class='ipsType_minorHeading'><strong>{lang="ps_expire"}</strong></dt>
				<dd class='ipsType_normal'>{$purchase->expire->localeDate()}</dd>
			{{endif}}
			{{if $purchase->renewals and !$purchase->grouped_renewals}}
				<dt class='ipsType_minorHeading'><strong>{lang="purchase_renewal_terms"}</strong></dt>
				<dd class='ipsType_normal'>{$purchase->renewals->toDisplay( $purchase->member )}</dd>
			{{endif}}
			{{if $purchase->billing_agreement AND !$purchase->billing_agreement->canceled}}
				<dt class='ipsType_minorHeading'><strong>{lang="ps_billing_agreement"}</strong></dt>
				<dd class='ipsType_normal ipsType_blendLinks'><a href='{$purchase->billing_agreement->url()}'>{$purchase->billing_agreement->gw_id}</a></dd>
			{{endif}}
		</dl>
	</div>
	<div class='ipsColumn ipsColumn_fluid'>
		<h1 class="ipsType_pageTitle">{$purchase->name}</h1>
		<p class='ipsType_reset ipsType_normal'>
			{{if $purchase->cancelled}}
				<span class='ipsBadge ipsBadge_negative'>{lang="purchase_canceled"}</span>&nbsp;
			{{elseif !$purchase->active}}
				<span class='ipsBadge ipsBadge_neutral'>{lang="purchase_expired"}</span>&nbsp;
			{{elseif $purchase->expire}}
				{{if $purchase->grace_period and $purchase->expire->getTimestamp() < time()}}
					<span class='ipsBadge ipsBadge_positive'>{lang="purchase_in_grace_period_front"}</span>&nbsp;
				{{else}}
					<span class='ipsBadge ipsBadge_positive'>{lang="purchase_active"}</span>&nbsp;
				{{endif}}
			{{endif}}
            {lang="$purchase->getTypeTitle()"}
		</p>
		<br><br>

		{{if $pendingInvoice = $purchase->invoice_pending and $pendingInvoice->status === $pendingInvoice::STATUS_PENDING}}
			<div class='ipsSpacer_bottom ipsMessage ipsMessage_info'>
				{lang="purchase_pending_invoice"} {{if $pendingInvoice->canView()}}<a href="{$pendingInvoice->checkoutUrl()}" title="{lang="order_pay_now_title"}">{lang="order_pay_now"}</a>{{endif}}
			</div>
		{{endif}}

		{{if $lkey = $purchase->licenseKey()}}
			<div class='ipsAreaBackground_light ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double'>
				<h2 class='ipsType_minorHeading ipsSpacer_bottom ipsSpacer_half'>{lang="purchase_license_key"}</h2>
				<div class='ipsType_large ipsType_monospace cNexusLicenseKey'>
					{$lkey->key}
				</div>
			</div>
		{{endif}}

		{{if isset( $extra['packageInfo'] )}}
			<h2 class='ipsType_sectionHead ipsSpacer_bottom ipsSpacer_half'>{lang="purchase_package_info"}</h2>
				{template="richText" group="global" app="core" location="global" params="$extra['packageInfo'], array('ipsType_normal', 'ipsContained', 'ipsType_break', 'ipsSpacer_bottom')"}
		{{endif}}

		{{if isset( $extra['purchaseInfo'] )}}
			<div>{$extra['purchaseInfo']|raw}</div>
			<br><br>
		{{endif}}
	</div>
</div>
</div>