<ips:template parameters="$purchase, $advertisement" />
<div class="ipsGrid ipsPad_half ipsType_center ipsSpacer_bottom">
	<div class="ipsGrid_span6">
		<span class="ipsType_veryLarge">{$advertisement->impressions}{{if $advertisement->maximum_unit == 'i' and $advertisement->maximum_value != -1}} / {$advertisement->maximum_value}{{endif}}</span>
		<br>
		{lang="impressions"}
	</div>
	<div class="ipsGrid_span6">
		<span class="ipsType_veryLarge">{$advertisement->clicks}{{if $advertisement->maximum_unit == 'c' and $advertisement->maximum_value != -1}} / {$advertisement->maximum_value}{{endif}}</span>
		<br>
		{lang="clicks"}
	</div>
</div>
<div class="ips{expression="mb_ucfirst(\IPS\SUITE_UNIQUE_KEY)"} ipsAreaBackground_reset ipsType_center">
	{{$images = array_filter( json_decode( $advertisement->images, TRUE ) );}}
	{{$link = \IPS\Http\Url::external( $advertisement->link );}}
	
	{{if \count( $images ) > 1}}
		<div class='ipsTabs ipsClearfix acpFormTabBar' id='elTabs_adView' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_adView' data-ipsTabBar-updateURL='false'>
			<a href='#elTabs_adView' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
			<ul role='tablist'
				{{foreach $images as $key => $image}}
					<li>
						<a href='#ipsTabs_elTabs_adView_adView_tab_{$key}_panel' id='adView_tab_{$key}' class="ipsTabs_item {{if $key == "large"}}ipsTabs_activeItem{{endif}}" title='{$key}' role="tab" aria-selected="{{if $key == "large"}}true{{else}}false{{endif}}">
							{{if $key === 'large'}}{lang="ad_image"}{{else}}{lang="ad_image_{$key}"}{{endif}}
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<section id='ipsTabs_content_adView' class='acpFormTabContent'>
			{{foreach $images as $key => $image}}
				<div id='ipsTabs_elTabs_adView_adView_tab_{$key}_panel' class="ipsTabs_panel" aria-labelledby="adView_tab_{$key}" aria-hidden="false">
					<div class="ipsPad">
						<a href="{$link}" target='_blank' rel='nofollow noreferrer'><img src="{file="$image" extension="$advertisement->storageExtension()"}" class="ipsImage ipsContained"></a>
					</div>
				</div>
			{{endforeach}}
		</section>
	{{else}}
		<div class="ipsPad">
			{{foreach $images as $key => $image}}
				<a href="{$link}" target='_blank' rel='nofollow noreferrer'><img src="{file="$image" extension="$advertisement->storageExtension()"}" class="ipsImage ipsContained"></a>
			{{endforeach}}
		</div>
	{{endif}}
	<div class="ipsType_small"><a href="{$link}" rel="noreferrer">{$advertisement->link}</a></div>
	&nbsp;
</div>