<ips:template parameters="$purchase, $data" />

<div class='ipsPad ipsAreaBackground_light'>
	<div class='ipsColumns'>
		<div class='ipsColumn ipsColumn_wide'>
			<h2 class='ipsType_minorHeading'>{lang="gift_voucher"}</h2>
			<p class='ipsType_reset ipsType_large cNexusGiftCardPrice'>
				{money="$data['amount']" currency="$data['currency']"}
			</p>	
			<div class='ipsType_large'>
				<strong>{$data['code']}</strong>
			</div>
			<p class='ipsType_medium'>
				{{if $data['method'] === 'email'}}
					{lang="sent_to"} {$data['recipient_email']}
				{{else}}
					<a href='{$purchase->url()->setQueryString( 'do', 'extra' )}'>{lang="printable_version"}</a>
				{{endif}}
			</p>
		</div>
		<div class='ipsColumn ipsColumn_fluid ipsAreaBackground_reset'>
			<div class='ipsPad ipsType_medium'>
				{{if $data['recipient_name']}}
					<strong>{$data['recipient_name']},</strong>
					<br>
					<br>
				{{endif}}
				{{if $data['message']}}
					{expression="nl2br( htmlspecialchars( $data['message'], ENT_DISALLOWED, 'UTF-8', FALSE ) )" raw="true"}
				{{endif}}
				{{if $data['sender']}}
					<br><br>
					<strong>{lang="from"} {$data['sender']}</strong>
				{{endif}}
			</div>
		</div>
	</div>
</div>