<ips:template parameters="$purchase, $account" />

<tr class='cNexusSupportHeader_row'>
	<td class='cNexusSupportHeader_colTitle'>
		{lang="hosting_info"}
	</td>
	<td class='cNexusSupportHeader_colInfo'>
		<ul class='ipsList_inline'>
			<li>
				<i class='fa fa-globe'></i> &nbsp;<a href="{expression="\IPS\Http\Url::external( 'http://' . $account->domain )"}" target="_blank" rel='noreferrer'>{$account->domain}</a>
			</li>
			<li>
				<i class='fa fa-server'></i> &nbsp;{$account->server->hostname}
			</li>
			<li>
				<i class='fa fa-lock'></i> &nbsp;<span class="ipsType_monospace">{$account->username}</span> / <span class="ipsType_monospace">{$account->password}</span>
			</li>
			<li>
				<a href="{$account->ftpLink()}">{lang="account_ftp"}</a> / <a href="{$account->controlPanelLink()}" target="_blank" rel='noopener'>{lang="account_{$account->server->type}_control_panel"}</a>
			</li>
		</ul>
	</td>
</tr>