<ips:template parameters="$purchase" />
<div class="ipsPageHead_special">
	{$purchase->name} (#{$purchase->id})
</div>
<ul class="ipsDataList">
	{{foreach $purchase->custom_fields as $k => $v}}
		{{if $displayValue = trim( \IPS\nexus\Package\CustomField::load( $k )->displayValue( $v, TRUE ) )}}
			<li class="ipsDataItem">
				<span class="ipsDataItem_generic ipsDataItem_span6"><strong>{lang="nexus_pfield_{$k}"}</strong></span>
				<span class="ipsDataItem_generic">{$displayValue|raw}</span>
			</li>	
		{{endif}}
	{{endforeach}}
</ul>