<ips:template parameters="$purchase" />

<div class='ipsPad ipsAreaBackground_light ipsType_center ipsSpacer_bottom'>
	<h2 class='ipsType_minorHeading ipsSpacer_bottom ipsSpacer_half'>{lang="license_key"}</h2>
	<div class='ipsType_large ipsSpacer_bottom ipsSpacer_half'>
		{lang="no_license_key_generated"}
	</div>

	{{if member.hasAcpRestriction( 'nexus', 'customers', 'lkeys_reset' ) || $licensekey->uses}}
		<ul class='ipsList_inline ipsSpacer_top'>
			{{if member.hasAcpRestriction( 'nexus', 'customers', 'lkeys_reset' )}}
				<li>
					<a href="{$purchase->acpUrl()->setQueryString( array( 'do' => 'extra', 'act' => 'lkeyReset' ) )->csrf()}" data-confirm class="ipsButton ipsButton_light ipsButton_verySmall">{lang="generate_new_key"}</a>
				</li>
			{{endif}}
		</ul>
	{{endif}}
</div>