<ips:template parameters="$purchase, $customer, $children, $invoices, $customFields" />
{{if $billingAgreement = $purchase->billing_agreement AND !$purchase->billing_agreement->canceled}}
	<p class="ipsMessage ipsMessage_info">{lang="billing_agreement_purchase_info" sprintf="$billingAgreement->acpUrl()"}</p>
{{endif}}
<div class="ipsGrid">
	<div class='ipsGrid_span4'>		
		{{if $purchase->cancelled}}
			<p class='ipsAreaBackground_negative ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
				<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-times-circle'></i> {lang="purchase_canceled"}</span>
				<br>
				{{if $purchase->can_reactivate}}
					{lang="purchase_canceled_ra"}
				{{else}}
					{lang="purchase_canceled_no_ra"}
				{{endif}}
			</p>
		{{elseif !$purchase->active}}
			<p class='ipsAreaBackground ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
				<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-exclamation-circle'></i> {lang="purchase_expired"}</span>
			</p>
		{{elseif $purchase->expire}}
			{{if $purchase->grace_period and $purchase->expire->getTimestamp() < time()}}
				<p class='ipsAreaBackground ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
					<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-clock-o'></i> {lang="purchase_in_grace_period"}</span>
				</p>
			{{else}}
				<p class='ipsAreaBackground_positive ipsPad ipsType_center ipsSpacer_bottom ipsSpacer_double ipsType_reset'>
					<span class='ipsType_reset ipsType_sectionHead'><i class='fa fa-check-circle'></i> {lang="purchase_active"}</span>
				</p>
			{{endif}}
		{{endif}}

		<div class="ipsBox">
			<h2 class='ipsBox_titleBar'>{lang="purchase_details"}</h2>
			<ul class="ipsDataList">
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong>{lang="ps_start"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$purchase->start->localeDate()}
					</span>
				</li>
				{{if $purchase->expire}}
					<li class="ipsDataItem">
						<span class="ipsDataItem_generic ipsDataItem_size4">
							<strong>{lang="ps_expire"}</strong>
						</span>
						<span class="ipsDataItem_generic">
							{$purchase->expire->localeDate()}
						</span>
					</li>
				{{endif}}
				{{if $purchase->grace_period}}
					<li class="ipsDataItem">
						<span class="ipsDataItem_generic ipsDataItem_size4">
							<strong>{lang="p_grace_period"}</strong>
						</span>
						<span class="ipsDataItem_generic">
							{{$grace = new \DateInterval( 'PT' . $purchase->grace_period . 'S' );}}
							{expression="\IPS\DateTime::formatInterval( \IPS\DateTime::create()->diff( \IPS\DateTime::create()->add( $grace ) ), 0 )"}
							{{if $purchase->expire}}
								<span class="ipsType_light ipsType_small">{$purchase->expire->add( $grace )->localeDate()}</span>
							{{endif}}
						</span>
					</li>
				{{endif}}
				{{if $purchase->renewals}}
					<li class="ipsDataItem">
						<span class="ipsDataItem_generic ipsDataItem_size4">
							<strong>{lang="ps_renewals"}</strong>
						</span>
						<span class="ipsDataItem_generic">
							{$purchase->renewals}{{if $purchase->renewals->tax}}{lang="plus_tax_rate" sprintf="$purchase->renewals->tax->_title"}{{endif}} {{if $purchase->grouped_renewals}}({lang="purchase_grouped"}){{endif}}
							{{if $purchase->pay_to and $purchase->commission < 100}}
								<br>
								{{if $purchase->fee}}
									{lang="purchase_renewal_commission_fee" htmlsprintf="100 - $purchase->commission, $purchase->fee, $purchase->pay_to->link()"}
								{{else}}
									{lang="purchase_renewal_commission" htmlsprintf="100 - $purchase->commission, $purchase->pay_to->link()"}
								{{endif}}
							{{endif}}
						</span>
					</li>
					{{if $purchase->billing_agreement}}
						<li class="ipsDataItem">
							<span class="ipsDataItem_generic ipsDataItem_size4">
								<strong>{lang="ps_billing_agreement"}</strong>
							</span>
							<span class="ipsDataItem_generic">
								<a href="{$purchase->billing_agreement->acpUrl()}">{$purchase->billing_agreement->gw_id}</a>
								{{if $purchase->billing_agreement->canceled}}
									({lang="billing_agreement_canceled"})
								{{endif}}
							</span>
						</li>
					{{endif}}
				{{endif}}
				{{if $parent = $purchase->parent()}}
					<li class="ipsDataItem">
						<span class="ipsDataItem_generic ipsDataItem_size4">
							<strong>{lang="ps_parent"}</strong>
						</span>
						<span class="ipsDataItem_generic">
							<a href="{$parent->acpUrl()}">{$parent->name}</a>
						</span>
					</li>
				{{endif}}
			</ul>
		</div>
		<br>
		
		<div class="ipsBox">
			<h2 class="ipsBox_titleBar">{lang="purchase_customer_info"}</h2>
			{{if $customer}}
				<div class='ipsPad ipsPhotoPanel ipsPhotoPanel_small ipsClearfix'>
					<a href="{$purchase->member->acpUrl()}" class='ipsPos_left'><img src='{$purchase->member->photo}' class='ipsUserPhoto ipsUserPhoto_small'></a>
					<div class='ipsType_normal'>
						<h3 class='ipsType_large ipsType_reset ipsType_blendLinks'><strong><a href="{$purchase->member->acpUrl()}">{$purchase->member->cm_name}</a></strong></h3>
						{$purchase->member->email}<br>
						{lang="transaction_customer_since" sprintf="$purchase->member->joined->localeDate()"}<br>
						{lang="transaction_spent" sprintf="$purchase->member->totalSpent()"}
					</div>
				</div>
			{{else}}
				<div class='ipsPad ipsClearfix'>
					<p class="ipsMessage ipsMessage_error">{lang="purchase_no_member"}</p>
				</div>
			{{endif}}
		</div>
		<br><br>
	</div>
	<div class='ipsGrid_span8'>
		{{if $content = $purchase->acpPage()}}
			{$content|raw}
		{{endif}}
		
		{{if \count( $customFields )}}
			<div class="ipsBox">
				<h2 class='ipsBox_titleBar'>{lang="p_custom_fields"}</h2>
				<ul class="ipsDataList">
					{{foreach $customFields as $k => $v}}
						<li class="ipsDataItem">
							<span class="ipsDataItem_generic ipsDataItem_size4">
								<strong>{lang="nexus_pfield_{$k}"}</strong>
							</span>
							<span class="ipsDataItem_generic">
								{$v|raw}
							</span>
						</li>
					{{endforeach}}
				</ul>
			</div>
		{{endif}}
		
		{{if $purchase->childrenCount()}}
		<div class='ipsBox'>
			<h2 class="ipsBox_titleBar">{lang="child_purchases"}</h2>
			{$children|raw}
		</div>
		{{endif}}

		{$invoices|raw}
	</div>
</div>