<ips:template parameters="$table, $headers, $rows" />

{{foreach $rows as $idx => $row}}
	<li class='ipsDataItem'>
		<div class='ipsDataItem_main ipsType_medium'>
			<span class='ipsType_minorHeading'>{lang="invoice_shipment_x" sprintf="$idx + 1"}</span><br>
			<h3 class='ipsType_reset ipsType_sectionHead'><strong>{$row['o_method']}</strong> &nbsp;&nbsp;{$row['o_status']|raw}</h3> 
			<p class='ipsType_reset ipsType_medium ipsType_light ipsSpacer_bottom'>{$row['o_shipped_date']}</p>
			
			<strong>{lang="invoice_in_shipment"}:</strong> <ul class='ipsList_inline'><li>{lang="product"}</li><li>{lang="product"}</li></ul>
		</div>
		<div class='ipsDataItem_generic ipsDataItem_size4 ipsType_right ipsPos_top'>
			{template="controlStrip" params="$row['_buttons']" group="global" app="core"}
		</div>
	</li>
{{endforeach}}