<ips:template parameters="" />
<li class="ipsFieldRow ipsFieldRow_noFlex">
	<div id="elPages_block_preview_wrapper" class='ipsSpacer_bottom'>
		<iframe class='loading' src='{url="app=cms&module=pages&controller=builder&do=previewBlock" base="front" protocol="\IPS\Http\Url::PROTOCOL_RELATIVE"}' data-base-url="{url="app=cms&module=pages&controller=builder&do=previewBlock" base="front" protocol="\IPS\Http\Url::PROTOCOL_RELATIVE"}" frameborder="0" name="elpages_block_preview" id="elpages_block_preview"></iframe>
		<p class='ipsType_reset'>
			<span data-role="refreshPreview" class="ipsButton ipsButton_light ipsButton_small">{lang="cms_block_preview_refresh"}</span>
		</p>
	</div>
<li>