<ips:template parameters="$name, $value, $cReactions, $ipsReactions, $descriptions" />

<div class="ipsGrid ipsGrid_collapseTablet ipsGrid_collapsePhone ipsAttachment_fileList ipsContained cReactionMapper" data-ipsGrid data-ipsGrid-equalHeights='row' >
	{{foreach $cReactions as $id => $cReaction}}
	<div class='ipsGrid_span2 ipsBox ipsAttach ipsImageAttach ipsPad_half' data-controller="convert.admin.forms.reactionmapper" data-reactionid="{$id}">
        {{if $cReaction['icon']}}
        <div class='ipsType_center ipsPadding_top:half cReactionImage'>
            <img src="{$cReaction['icon']}" alt='' class='ipsImage'>
        </div>
        {{endif}}
        <div class="ipsType_center ipsPad_half">
            <input type="hidden" value="0" name="{$name}[{$id}]" />
            <p class='ipsType_center'>{$cReaction['title']|raw}</p>
            <div>
                <a href='#elReactionMapper{$id}_menu' id='elReactionMapper{$id}' class='ipsButton ipsButton_normal ipsButton_small ipsButton_fullWidth' data-ipsMenu><span class="elMenuSelect_replace">{lang="convert_reaction_choose"}</span> &nbsp;<i class='fa fa-caret-down'></i></a>
            </div>
            <ul id='elReactionMapper{$id}_menu' role='menu' class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide'>
                {{foreach $ipsReactions as $reactionId => $reaction}}
                <li class='ipsMenu_item'><a role='menuitem' href='#' data-id="{$reactionId}" {{if(isset($value[$id]) aND $value[$id] ==$reactionId)}}data-default="true"{{endif}}>{{if( !empty( $reaction ))}}<img src="{$reaction}" alt="" class="cReactionSmall"/> {{endif}}{$descriptions[ $reactionId ]}</a></li>
                {{endforeach}}
            </ul>
        </div>
	</div>
	{{endforeach}}
</div>