<ips:template parameters="$lang, $warnings=array(), $ends=NULL" />
<div class='ipsComposeArea ipsComposeArea_unavailable ipsClearfix'>
	<div class='ipsComposeArea_editor'>
		<div class="ipsComposeArea_dummy">
			<span class='ipsType_warning'><i class="fa fa-warning"></i> {lang="$lang"} {{if $ends !== NULL AND $ends > 0}}{lang="restriction_ends" sprintf="\IPS\DateTime::ts( $ends )->relative()"}{{endif}}</span>
		
			{{if \count( $warnings) }}
				{{foreach $warnings as $idx => $warning}}
					{{if $idx === 0}}
						<br><br>
						<a href="{$warning->url()}" data-ipsDialog data-ipsDialog-size='narrow' class='ipsButton ipsButton_verySmall ipsButton_light'>{lang="view_warning_details"}</a>
					{{endif}}
				{{endforeach}}
			{{endif}}
		</div>
	</div>
</div>