<ips:template parameters="$login" />
<ul class='ipsForm ipsForm_vertical'>
	<li class="ipsFieldRow ipsFieldRow_fullWidth">
		{{$authType = $login->authType();}}
		<div class="ipsFieldRow_content">
			{{if $authType === \IPS\Login::AUTH_TYPE_USERNAME}}
				<input autofocus type="text" placeholder="{lang="username"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} autocomplete="username">
			{{elseif $authType === \IPS\Login::AUTH_TYPE_EMAIL}}
				<input autofocus type="email" placeholder="{lang="email_address"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} autocomplete="email">
			{{else}}
				<input autofocus type="text" placeholder="{lang="username_or_email"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} autocomplete="email">
			{{endif}}
		</div>
	</li>
	<li class="ipsFieldRow ipsFieldRow_fullWidth">
		<div class="ipsFieldRow_content">
			<input type="password" placeholder="{lang="password"}" name="password" id="password" {{if isset( \IPS\Request::i()->password )}}value="{request="password"}"{{endif}} autocomplete="current-password">
		</div>
	</li>
	<li class='ipsFieldRow_fullWidth'>
		<button type='submit' name="_processLogin" value="usernamepassword" class='ipsButton ipsButton_primary ipsButton_medium'><i class='fa fa-lock'></i> {lang="login"}</button>
	</li>
</ul>
