<ips:template parameters="$link=NULL" />
<div class="ipsPad">
	<div class="ipsSpacer_bottom">
		<h2 class='ipsType_sectionHead'>{lang="download_upgrade_error"}</h2>
	</div>
	<div class="ipsSpacer_bottom">
		<p>{lang="delta_upgrade_manual"}</p>
		<div class="ipsType_center">
			<a href="{url="client_area" ips="true"}" class="ipsButton ipsButton_important ipsButton_large" target="_blank" rel="noopener">{lang="delta_upgrade_go_to_clientarea"}</a>
		</div>
		<p>{lang="delta_upgrade_manual_footer"}</p>
	</div>
</div>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	<a href="upgrade" class="ipsButton ipsButton_primary">{lang="continue"}</a>
</div>