<ips:template parameters="$log" />
<div class="ipsMargin_bottom">
	<div class='ipsFlex ipsFlex-ai:center ipsGap'>
		<div class='ipsFlex-flex:00'>
			<span class='ipsUserPhoto ipsUserPhoto_medium'>
				<img src='{member="photo" id="$log->member_id"}' alt=''>
			</span>
		</div>
		<div class='ipsFlex-flex:11'>
			<h1 class='ipsType_reset'>
				{{if $log->member_id}}
					<a href="{url="app=core&module=members&controller=members&do=view&id="}{$log->member_id}" data-ipsTooltip title='{lang="triggered_by" sprintf="\IPS\Member::load($log->member_id)->name"}'>{member="name" id="$log->member_id"}</a>
				{{else}}
					{lang="triggered_guest"}
				{{endif}}
				({expression="\IPS\Member\Group::load( \IPS\Member::load( $log->member_id )->member_group_id )->formattedName" raw="true"})
			</h1>
			<div>{datetime="$log->time"}</div>
			<div class='ipsContained ipsType_break'>
				<div class='ipsTruncate'>
					{lang="triggered_at"} {{if $log->url}}<a href='{$log->url}' target='_blank' rel="noopener" title='{$log->url}'>{$log->url}</a>{{else}}<em>{lang="log_missing_data"}</em>{{endif}}
				</div>
			</div>
		</div>
	</div>
</div>
<div class="ipsMargin_bottom">
	{{if $log->exception_class}}
		<code>{$log->exception_class}::{$log->exception_code}</code><br>
		<br>
	{{endif}}
	<textarea rows="15" style="font-family: monospace;">{$log->message}</textarea>
</div>
<div class="ipsMargin_bottom">
	<h3 class="ipsType_minorHeading">{lang="log_backtrace"}</h3>
	<textarea rows="8" style="font-family: monospace;">{$log->backtrace}</textarea>
</div>