<ips:template parameters="$version" />
<div class="ipsPad">
	<div class="ipsSpacer_bottom">
		<h2 class='ipsType_sectionHead'>{lang="download_upgrade_database_check_fail_title"}</h2>
	</div>
	<div class="ipsSpacer_bottom">
		<p>{lang="download_upgrade_database_check_fail_desc"}</p>
	</div>
</div>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	<a href="{url="app=core&module=support&controller=support&do=databasefail&_upgradeVersion={$version}" csrf="true"}" data-ipsDialog data-ipsDialog-title="{lang="self_service"}" class="ipsButton ipsButton_primary">{lang="help_me_fix_this"}</a>
</div>
