<ips:template parameters="" />
<div data-controller='core.admin.system.autoupgradetimer'>
	<div class="ipsPad">
		<div class="ipsSpacer_bottom">
			<h2 class='ipsType_sectionHead'>{lang="delta_upgrade_cic2"}</h2>
		</div>
		<div class="ipsSpacer_bottom">
			<p>{lang="delta_upgrade_cic2_desc"}</p>
		</div>
	</div>
	<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
		<span data-role="counter-wrapper">{lang="delta_upgrade_cic2_cont"}</span>
		<span data-role="continue-button" class='ipsJS_hide'><a href="{url="app=core&module=system&controller=upgrade&check=1"}" class="ipsButton ipsButton_primary">{lang="continue"}</a></span>
	</div>
</div>