<ips:template parameters="$version, $resources" />
<form action="{url="app=core&module=system&controller=upgrade" csrf="1"}" method="post">
	<input type="hidden" name="version" value="{$version}">
	<input type="hidden" name="select_version_submitted" value="1">
	<input type="hidden" name="skip_md5_check" value="1">
	<input type="hidden" name="skip_resource_check" value="1">
	<div class="ipsPad">
        <div class="ipsSpacer_bottom">
            <h2 class='ipsType_sectionHead'>{lang="download_upgrade_initial_resource_title"}</h2>
        </div>
        <div class="ipsSpacer_bottom">
            <p class="ipsType_normal">{lang="download_upgrade_initial_resource_explain"}</p>
        </div>
        {{foreach $resources as $type => $res}}
        {{if \count( $res )}}
        <h3 class="ipsMargin_bottom:none">{lang="download_upgrade_initial_resource_upgrade_{$type}" sprintf="\count($res)" pluralize="\count($res)"}</h3>
        {lang="download_upgrade_initial_resource_upgrade_{$type}_blurb"}
        <ul class="ipsFlex ipsFlex-ai:center ipsGap_row:2 sm:ipsFlex-ai:stretch sm:ipsFlex-fd:column ipsFlex-fw:wrap sm:ipsFlex-flex:11 ipsSpacer_half ipsSpacer_top">
        {{foreach $res AS $r }}
            <li>{$r['title']}</li>
        {{endforeach}}
        </ul>
        {{endif}}
        {{endforeach}}
	</div>
	<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
		<input type="submit" class="ipsButton ipsButton_primary" name="skip_resource_check" value="{lang="continue"}">
	</div>
</form>
