<ips:template parameters="$version, $conflicts" />
<form action="{url="app=core&module=system&controller=upgrade" csrf="1"}" method="post">
	<input type="hidden" name="version" value="{$version}">
	<input type="hidden" name="select_version_submitted" value="1">
	<input type="hidden" name="skip_md5_check" value="1">
	<input type="hidden" name="skip_theme_check" value="1">
	<div class="ipsPad">
		<div class="ipsSpacer_bottom">
			<h2 class='ipsType_sectionHead'>{lang="download_upgrade_initial_theme_conflicts_title" pluralize="\count($conflicts)"}</h2>
		</div>
		<div class="ipsSpacer_bottom">
			<p class="ipsType_normal">{lang="download_upgrade_initial_theme_conflicts_explain" pluralize="\count($conflicts)"}</p>
		</div>
		{{foreach $conflicts as $themeId => $categories}}
			{{$theme = \IPS\Theme::load( $themeId );}}
			<div class="ipsSpacer_bottom">
				<h3>{$theme->_title}</h3>
				<ul>
					{{if isset( $categories['html'] )}}
						{{foreach $categories['html'] as $templateName => $templateId}}
							<li>
								{{list( $app, $location, $group, $name ) = explode( '/', $templateName );}}
								<a href="{url="app=core&module=customization&controller=themes&do=templates&id={$themeId}&t_type=templates&t_app={$app}&t_location={$location}&t_group={$group}&t_name={$name}"}" target="_blank" rel="noopener">
									{$app} &rarr; {$location} &rarr; {$group} &rarr; {$name}
								</a>
							</li>
						{{endforeach}}
					{{endif}}
					{{if isset( $categories['css'] )}}
						{{foreach $categories['css'] as $cssName => $cssId}}
							<li>
								{{list( $app, $location, $group, $name ) = explode( '/', $cssName );}}
								<a href="{url="app=core&module=customization&controller=themes&do=templates&id={$themeId}&t_type=css&t_app={$app}&t_location={$location}&t_group={$group}&t_name={$name}"}" target="_blank" rel="noopener">
									{$app} &rarr; {$location} &rarr; {$group} &rarr; {$name}
								</a>
							</li>
						{{endforeach}}
					{{endif}}
				</ul>
			</div>
		{{endforeach}}	
		<p class="ipsType_small">{lang="download_upgrade_initial_theme_conflicts_tip"}</p>	
	</div>
	<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
		<input type="submit" class="ipsButton ipsButton_primary" name="skip_theme_check" value="{lang="continue"}">
	</div>
</form>