<ips:template parameters="$supportEmail" />
<div class="ipsPadding ipsBox">
	<h2 class="ipsType_pageTitle ipsType_center">{lang="managed_upgrade_block_head"}</h2>
	<div class="ipsPad ipsSpacer_top ipsSpacer_bottom ipsType_center"><img src='{resource="machine.png" app="core" location="admin"}'></div>
	<p class="ipsType_large ipsType_center">{lang="managed_upgrade_block_msg" sprintf="$supportEmail, $supportEmail"}</p>
</div>