<ips:template parameters="$featured" />

{{if \count( $featured )}}
	<div class='cFeaturedEvents' {{if \count( $featured ) > 1}}data-controller="calendar.front.overview.carousel"{{endif}}>
		<ul class='cFeaturedEvents__scroller'>
			{{foreach $featured as $idx => $event}}
				{template="featuredEvent" app="calendar" group="events" params="$event, $idx"}
			{{endforeach}}
		</ul>
		{{if \count( $featured ) > 1}}
			<div class='cFeaturedEvents__dots' aria-hidden='true'>
				{{foreach $featured as $idx => $item}}
					<button data-carousel-dot="{$idx + 1}"><span></span></button>
				{{endforeach}}
				<div class='cFeaturedEvents__current-dot'></div>
			</div>
		{{endif}}
	</div>
{{endif}}