<ips:template parameters="$events" />
{{if \count( $events )}}
	<section class='ipsBox ipsMargin_bottom'>
		<h2 class='ipsType_sectionTitle'>{lang="events_online_events"}</h2>
		<div class='ipsPadding ipsAreaBackground_light ipsRadius:bl ipsRadius:br'>
			<ul class='eventList'>
				{{foreach $events as $event}}
					{template="event" app="calendar" group="events" params="$event, 'small'"}
				{{endforeach}}
			</ul>
		</div>
	</section>
{{endif}}