<ips:template parameters="$results=array(), $mapMarkers=NULL" />

<div class='cEvents__searchTools'>
	<a href='{url="app=calendar"}' class='ipsType_normal cEvents__searchTools__back' data-action='backToOverview'><i class='fa fa-angle-left'></i> {lang="events_search_back_to_overview"}</a>
	<a href='#' class='ipsType_normal ipsType_blendLinks cEvents__searchTools__sort' id='elSortMenu' data-ipsMenu data-ipsMenu-selectable='radio'>
		<strong>{lang="events_search_sort_by"}</strong> <span data-role='searchOrder'>{lang="events_search_distance"}</span> <i class='fa fa-caret-down'></i>
	</a>
	<ul id='elSortMenu_menu' class='ipsMenu ipsMenu_selectable ipsMenu_radio ipsHide'>
		<li class='ipsMenu_item ipsMenu_itemChecked' data-ipsMenuValue='nearest'>
			<a href='#'>{lang="events_search_distance"}</a>
		</li>
		<li class='ipsMenu_item' data-ipsMenuValue='date'>
			<a href='#'>{lang="events_search_date"}</a>
		</li>
	</ul>
</div>
<div class='cEvents__searchMap cEvents__searchMap--loading event ipsAreaBackground ipsPad ipsSpacer_bottom ipsSpacer_double' data-role='searchResultsMap' {{if $mapMarkers}}data-markers="{$mapMarkers}"{{endif}}></div>
<ul class='eventList {{if !\count( $results )}}ipsHide{{endif}}' data-role='searchResults'>
	{template="searchResults" app="calendar" group="events" params="$results"}
</ul>
<div class='ipsPad ipsType_center'>
	<button class='ipsButton ipsButton_light ipsButton_normal ipsHide' data-action='loadMoreSearch'>{lang="events_search_show_more"}</button>
	<p class='ipsType_center ipsType_normal ipsType_light ipsHide' data-role='noMoreSearchResults'>{lang="events_search_no_events"}</p>
</div>
<div class='ipsAreaBackground_light ipsPad_double ipsType_center ipsType_large ipsType_light {{if \count( $results )}}ipsHide{{endif}}' data-role='noSearchResults'>
    {lang="events_search_no_events_long"}
</div>