<ips:template parameters="$currentCategory=NULL, $categories=array(), $blog" />
	{{if \count( $categories )}}
	<div id='elBlogCategoriesBlock' class='ipsWidget ipsWidget_vertical ipsBox'>
		{{if $blog->canEdit()}}
			<span class='ipsPos_right ipsPad_half ipsType_light'><a href="{$blog->url()->setQueryString( array( 'do' => "manageCategories" ) )}" data-ipsDialog data-ipsDialog-size='narrow'><i class='fa fa-pencil'></i></a></span>
		{{endif}}
		<h3 class='ipsType_sectionTitle ipsType_reset'>{lang="categories"}</h3>
		<div class='ipsPad_half'>
			<div class='ipsSideMenu'>
				<ul class='ipsSideMenu_list'>
					{{foreach $categories as $category}}
						<li{{if $currentCategory and $currentCategory->id == $category->id}} class="ipsAreaBackground_light"{{endif}}>
							<a href="{$category->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><strong class='ipsType_normal'>{$category->name}</strong></a>
						</li>
					{{endforeach}}
				</ul>
			</div>
		</div>
	</div>
	{{endif}}
