<ips:template parameters="$form, $count, $members, $type='overview'" />
<div class=''>
	<div class='ipsBox'>
		<h1 class='ipsBox_titleBar'>{{if $type=="overview"}}{lang="activity_date"}{{else}}{lang="activity_no_activity"}{{endif}}</h1>
		<div>
			{$form|raw}
		</div>
	</div>
</div>

{{if $count !== NULL}}
	<div class='ipsSpacer_top ipsSpacer_double'>
		{$members|raw}
	</div>
{{endif}}