<ips:template parameters="$charts" />

<div class='ipsGrid ipsGrid_collapsePhone'>
{{foreach $charts AS $chart}}
	<div class='ipsGrid_span6' data-controller='core.admin.members.lazyLoadingProfileBlock' data-url='{url="app=core&module=overview&controller=mycharts&do=getChart&chartId="}{$chart}'>
		<div class="ipsSpacer_bottom ipsType_center">
			<img src="{resource="tiny_loading.gif" app="core"}">
		</div>
	</div>
{{endforeach}}
</div>