<ips:template parameters="$form, $blocks" />
<div data-controller='core.admin.stats.overview' data-url='?app=core&module=stats&controller=overview&do=loadBlock'>
	<div class='ipsBox ipsBox_shadowed ipsPad ipsSpacer_bottom ipsClearfix ipsFlex ipsFlex-jc:center ipsFlex-ai:center'>
		<div class='ipsFlex-grow:1'></div>
		{$form|raw}
	</div>
	<div class='cStatsGrid'>
		<div class='ipsGrid ipsGrid_collapseTablet' data-ipsGrid data-ipsGrid-minItemSize='350'>
			{{foreach $blocks as $blockKey => $block}}
				{{if $block->page == 'user' AND $subBlocks = $block->getBlocks()}}
					{{foreach $subBlocks as $subBlock}}
						{{if $details = $block->getBlockDetails( $subBlock )}}
							<div class='ipsGrid_span3 ipsBox ipsBox_shadowed cStatTile' data-role='statsBlock' data-block='{$blockKey}' data-subblock='{$subBlock}' data-refresh='{$details['refresh']}' data-app='{$details['app']}' data-controller='core.admin.stats.overviewBlock'>
								<div class='cStatTile__header'>
									<h2 class='ipsType_reset cStatTile__title'>{lang="$details['title']"}</h2>
									{{if $details['description']}}
										<a href='#' class='cStatTile__info' title="{lang="$details['description']"}" data-ipsTooltip>?</a>
									{{endif}}
								</div>
								<div class='cStatTile__body ipsLoading ipsLoading_small'>
									<div class='cStatTile__bodyInner ipsType_center' data-role='statBlockContent'></div>
								</div>
							</div>
						{{endif}}
					{{endforeach}}
				{{endif}}
			{{endforeach}}
		</div>
	</div>
</div>