<ips:template parameters="$values, $previousValues=array()" />
{{if \count( $values )}}
    <table class='ipsTable ipsType_large ipsSpacer_top ipsSpacer_double ipsType_left'>
        {{foreach $values as $title => $count}}
            <tr>
                <td>{lang="$title"}</td>
                <td class='ipsType_right {{if isset( $previousValues[ $title ] ) AND $previousValues[ $title ] > $count}} ipsType_negative{{elseif isset( $previousValues[ $title ] ) AND $previousValues[ $title ] < $count}} ipsType_positive{{else}} ipsType_neutral{{endif}}'>
                    {number="$count"}
                    {{if isset( $previousValues[ $title ] )}}
                        {{if $previousValues[ $title ] > $count}}
                            <i class='fa fa-arrow-down' title='{expression="round( 100 - ( $count / $previousValues[ $title ] * 100 ) )"}%'></i>
                        {{elseif $previousValues[ $title ] < $count}}
                            <i class='fa fa-arrow-up' title='{{if $previousValues[ $title ]}}{expression="round( ( ( $count - $previousValues[ $title ] ) / $previousValues[ $title ] ) * 100 )"}%{{endif}}'></i>
                        {{endif}}
                    {{endif}}
                </td>
            </tr>
        {{endforeach}}
    </table>
{{else}}
    <p class='ipsType_light ipsType_center'>
        {lang="no_data"}
    </p>
{{endif}}