<ips:template parameters="$select, $pagination, $members, $total, $column, $activeTab" />
<h2 class="ipsBox_titleBar">{lang="stats_{$activeTab}_desc"}</h2>
{{if trim( $pagination )}}
	{$pagination|raw}
	<br><br>
{{endif}}
	<table class="ipsTable ipsTable_zebra">
		<thead>
			<tr>
				<th>{lang="member"}</th>
				<th>{lang="count"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $select as $row}}
				{{$member = \IPS\Member::constructFromData( $members[ $row[$column] ] );}}
				<tr>
					<td>{template="userPhoto" app="core" group="global" params="$member"} {$member->name}</td>
					<td>{$row['count']}</td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>
	<br>

	{$pagination|raw}
