<ips:template parameters="$select, $pagination, $members, $total" />

<div class="acpBlock">
<h1 class="ipsBox_titleBar">{lang="core_stats_referrer_count" pluralize="$total"}</h1></div>
<br>
{{if trim( $pagination )}}
	{$pagination|raw}
	<br><br>
{{endif}}
	<table class="ipsTable ipsTable_zebra">
		<thead>
			<tr>
				<th>{lang="member"}</th>
				<th>{lang="count"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $select as $row}}
				{{$member = \IPS\Member::constructFromData( $members[ $row['member_id'] ] );}}
				<tr>
					<td>{template="userPhoto" app="core" group="global" params="$member"} {$member->name}</td>
					<td>{$row['count']}</td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>
	<br>

	{$pagination|raw}
