<ips:template parameters="$badge, $cssClass = NULL, $tooltip = TRUE, $showRare = FALSE" />

<span class='ipsPos_relative'>
    <img src='{file="$badge->image" extension="core_Badges"}' loading="lazy" alt="{$badge->_title}" class='ipsOutline {$cssClass}' {{if $tooltip}}data-ipsTooltip title='{$badge->_title}'{{endif}}>
    {{if $showRare && $badge->isRare()}}
        <span class='ipsBadge ipsBadge_small ipsBadge_rare'>{lang="rare_badge"}</span>
    {{endif}}
</span>