<ips:template parameters="$mapParameters" />


{{$width = $mapParameters['width'] ?? 500;}}
{{$height = $mapParameters['height'] ?? 500;}}
<div data-controller="ips.core.map.googlemap" data-map-data='{expression="json_encode( $mapParameters )"}' style="width:{$width}px; height: {$height}px; max-width: 100%; max-height: 100%; overflow: hidden;" >
    {{if isset($mapParameters['lat']) and isset($mapParameters['long']) }}
    <span itemscope itemtype='http://schema.org/GeoCoordinates'>
		<meta itemprop='latitude' content='{$mapParameters["lat"]}'>
		<meta itemprop='longitude' content='{$mapParameters["long"]}'>
	</span>
    {{endif}}
    <div data-role="mapContainer" style="width: 100%; height: 100%;"></div>
</div>