<ips:template parameters="$existing, $object, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar=NULL, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm id='elPromoteDialogContent'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}

	<div data-role='promoteDialogBody' class='ipsPad'>
		{{if $existing}}
			{{if $existing->sent}}
				<div class="ipsMessage ipsMessage_info">
					<h4 class="ipsMessage_title">{lang="promote_dialog_sent"}</h4>
					<div>{lang="promote_dialog_sent_desc" htmlsprintf="$existing->sentDateTime()->html()"}</div>
				</div>
			{{else}}
				<div class="ipsMessage ipsMessage_info">
					<h4 class="ipsMessage_title">{lang="promote_dialog_used"}</h4>
					<div>{lang="promote_dialog_used_desc" htmlsprintf="$existing->scheduledDateTime()->html()"}</div>
				</div>
			{{endif}}
		{{endif}}
		{{if $groups = $object->cannotViewGroups()}}
		<div class="ipsMessage ipsMessage_warning">
			<h4 class="ipsMessage_title">{lang="promote_dialog_not_all_view"}</h4>
			<div>{lang="promote_dialog_not_all_view_desc" list="$groups"}</div>
		</div>
		{{endif}}
		<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_collapseTablet'>
			<div class='ipsColumn ipsColumn_fluid'>
				<ul class='ipsList_reset'>
					{{foreach $elements['promote_links'] as $id => $input}}
						{{if \is_object( $input ) }}
							{$input->rowHtml($form)|raw}
						{{else}}
							{$input|raw}
						{{endif}}
					{{endforeach}}
				</ul>
				<ul class='ipsList_reset'>
					{{$text = \IPS\core\Promote::objectContent( $object );}}
					<li class='cPromote_text_wrapper ipsClearfix ipsFieldRow ipsAreaBackground_light ipsPad'>
						<div id='eOriginalText' class='cPromote_text_fade'>
							<textarea>{$text|raw}</textarea>
						</div>
						<a href='#' data-action="expandTextarea">{lang="promote_show_original_content"}</a>
					</li>
				</ul>
				<ul class='ipsList_reset'>
					{{foreach $elements['promote_content'] as $id => $input}}
						{{if $id != 'promote_social_title_internal'}}
							{{if \is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						{{endif}}
					{{endforeach}}
				</ul>
			</div>
			<div class='ipsColumn ipsColumn_veryWide'>
				<div class='ipsPad ipsAreaBackground_light'>
					{{foreach $elements['promote_meta'] as $id => $input}}
						<h3 class='ipsType_reset ipsType_normal ipsSpacer_bottom'>{lang="promote_meta_{$id}"}</h3>
						<ul class='ipsList_reset'>
							{{if \is_object( $input ) }}
								{$input->rowHtml($form)|raw}
							{{else}}
								{$input|raw}
							{{endif}}
						</ul>
					{{endforeach}}
				</div>
			</div>
		</div>

		<div id='elSchedulePromote_menu' class='ipsMenu ipsMenu_auto ipsPad ipsHide'>
			<ul class='ipsList_reset'>
				{{foreach $elements['promote_schedule'] as $id => $input}}
					{{if \is_object( $input ) }}
						{$input->rowHtml($form)|raw}
					{{else}}
						{$input|raw}
					{{endif}}
				{{endforeach}}
			</ul>
		</div>

        {{if isset( $elements['promote_content']['promote_social_title_internal'] ) }}
            <div id='elInternalTitle_menu' class='ipsMenu ipsMenu_wide ipsPad ipsHide'>
                <ul class='ipsList_reset'>
                    <h3 class='ipsType_reset ipsTruncate ipsTruncate_line ipsPadding_bottom'>{lang="promote_social_title_internal"}</h3>
                    {$elements['promote_content']['promote_social_title_internal']->html()|raw}
                </ul>
            </div>
        {{endif}}
	</div>

	<ul class="ipsPad ipsToolList ipsToolList_horizontal ipsList_reset ipsClearfix ipsAreaBackground cPromoteSubmit">
		{{foreach $actionButtons as $button}}
			<li>{$button|raw}</li>
		{{endforeach}}

		<li>
			<a href='#' class='ipsButton ipsButton_veryLight ipsButton_fullWidth' id='elSchedulePromote' data-ipsMenu data-ipsMenu-appendTo='#elPromoteDialogContent'><i class='fa fa-clock-o'></i> {lang="promote_schedule_dialog"} <span data-role="promoteSchedule"></span> <i class='fa fa-caret-down'></i></a>
		</li>
	</ul>
</form>