<ips:template parameters="$member" />
{{if $subscription = \IPS\nexus\Subscription::loadActiveByMember( $member )}}
	<div class='cProfileSidebarBlock ipsSpacer_bottom'>
		<a href='{url="app=nexus&module=subscriptions&controller=subscriptions" seoTemplate="nexus_subscriptions"}'>
			<div class='cProfileSubscription {{if $subscription->package->_image}}cProfileSubscription--with-image{{else}}cProfileSubscription--no-image{{endif}}'>
				{{if $subscription->package->_image}}
					<div class="cProfileSubscription_bg" style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $subscription->package->_image->url )"}" )'></div>
					<div class='cProfileSubscription_gradient'></div>
				{{endif}}
				<span class='cProfileSubscription_text'><i class="fa fa-certificate"></i> &nbsp;{lang="nexus_subs_subscriber" sprintf="$subscription->package->_title"}</span>
			</div>
		</a>
	</div>
{{endif}}