<ips:template parameters="$package, $subscription, $showImagePlaceholder=FALSE" />
<!--{$package->id}-->
<div class='ipsBox cSubscriptions ipsFlex ipsFlex-fd:column {{if isset( \IPS\Request::i()->id ) and \IPS\Request::i()->id == $package->id}}cSubscription_highlighted{{endif}} {{if $subscription and $subscription->package and $subscription->package->id === $package->id}}cSubscriptions_active {{if !$subscription->active}}cSubscriptions_expired{{endif}}{{endif}}'>
	{{if $package->_image || $showImagePlaceholder}}
		{{if $subscription and $subscription->package and $subscription->package->id === $package->id}}<strong class="cSubscriptionActive" data-ipstooltip _title="{lang="nexus_subs_active"}"><i class="fa fa-certificate"></i></strong>{{endif}}
		<span href='#' class='ipsAreaBackground_dark cSubscriptionsHeader' {{if $package->_image}}style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $package->_image->url )"}" )'{{endif}}>
			{{if $package->_image}}<img src='{$package->_image->url}' class='ipsHide'>{{endif}}
			{{if $subscription and $subscription->package and $subscription->package->id === $package->id}}
				<div class='cSubscriptionRenew'>{$subscription->currentBlurb()}</div>
			{{endif}}
		</span>
	{{endif}}
	<div class='ipsPadding ipsFlex-flex:11'>
		<h2 class='ipsType_reset ipsType_blendLinks ipsType_pageTitle'>
			{$package->_title}
		</h2>
		<div>
			{{if $priceInfo = $package->priceInfo() and $priceInfo['primaryPrice']}}
				{template="packageBlockPrice" app="nexus" group="store" params="$priceInfo"}
			{{else}}
				<span class="cNexusPrice">{lang="nexus_sub_cost_unavailable"}</span>
			{{endif}}
        </div>
		<div class="cSubscription_desc ipsType_richText ipsType_normal ipsMargin_top">{$package->description}</div>
	</div>
	{{if $subscription}}
		{{if $subscription->package and $subscription->purchase}}
			{{$upgradeCost = $package->costToUpgrade( $subscription->package, \IPS\nexus\Customer::loggedIn() );}}
			{{if $subscription->package->id === $package->id}}
				{{if $subscription->purchase->expire and ( $canRenewUntil = $subscription->purchase->canRenewUntil( NULL,TRUE ) or ( !$subscription->purchase->renewals and $subscription->purchase->can_reactivate ) or ( $pendingInvoice = $subscription->purchase->invoice_pending and $pendingInvoice->status === $pendingInvoice::STATUS_PENDING ) or $subscription->purchase->canCancel())}}
					<div class='cSubscriptionInfo ipsBorder_top ipsType_center ipsPadding:half ipsFlex-flex:00'>
						<ul class='ipsFlex ipsFlex-jc:center ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:3 ipsGap_row:1'>
							{{if $pendingInvoice = $subscription->purchase->invoice_pending and $pendingInvoice->status === $pendingInvoice::STATUS_PENDING}}
								<li>
									<a href="{$pendingInvoice->checkoutUrl()}" class='ipsButton ipsButton_small ipsButton_link ipsButton_fullWidth' title="{lang="order_pay_now_title"}">
										{lang="purchase_renew_now"}
									</a>
								</li>
							{{elseif $canRenewUntil}}
								<li>
									<a href="{url="app=nexus&module=clients&controller=purchases&do=renew&id={$subscription->purchase->id}" base="front" csrf="true" seoTemplate="clientspurchaserenew" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $subscription->purchase->name )"}" class='ipsButton ipsButton_small ipsButton_link ipsButton_fullWidth' title="{lang="purchase_renew_now_title"}" {{if $canRenewUntil === TRUE or $canRenewUntil > 1}}data-ipsDialog data-ipsDialog-size='narrow'{{endif}}>
										{lang="purchase_renew_now"}
									</a>
								</li>
							{{elseif !$subscription->purchase->renewals and $renewOptions = json_decode( $package->renew_options, TRUE ) and \count( $renewOptions ) and $subscription->purchase->can_reactivate and ( !$subscription->purchase->billing_agreement or $subscription->purchase->billing_agreement->canceled )}}
								<li>
									<a href="{url="app=nexus&module=subscriptions&controller=subscriptions&do=reactivate&id={$package->id}" base="front" csrf="true" seoTemplate="nexus_subscription"}" class='ipsButton ipsButton_small ipsButton_link ipsButton_fullWidth' title="{lang="purchase_renew_now_title"}">
										{lang="reactivate_package"}
									</a>
								</li>
							{{endif}}
							{{if $subscription->purchase->canCancel()}}
								<li>
									<a href="{url="app=nexus&module=clients&controller=purchases&do=cancel&id={$subscription->purchase->id}" base="front" csrf="true" seoTemplate="clientspurchasecancel" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $subscription->purchase->name )"}&ref={expression="base64_encode( \IPS\Http\Url::internal( 'app=nexus&module=subscriptions&controller=subscriptions', 'front', 'nexus_subscriptions' ) )"}" class="ipsButton ipsButton_small ipsButton_link ipsButton_link--negative ipsButton_fullWidth" data-confirm data-confirmSubMessage="{lang="purchase_cancel_renewal_confirm"}">
										{lang="purchase_cancel_renewal"}
									</a>
								</li>
							{{endif}}
						</ul>
					</div>
				{{endif}}
			{{elseif $upgradeCost !== NULL}}
				<div class='cSubscriptionInfo ipsBorder_top ipsType_center ipsPadding:half ipsFlex-flex:00'>
					<ul class='ipsFlex ipsFlex-jc:center ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:3 ipsGap_row:1'>
						{{if $upgradeCost->amount->isGreaterThanZero() or ( $upgradeCost->amount->isZero() and $package->price() >= $subscription->package->price())}}
							<li>
								{{if $upgradeCost->amount->isZero()}}
								<a href="{url="app=nexus&module=subscriptions&controller=subscriptions&do=change&id={$package->id}" csrf="true" seoTemplate="nexus_subscription"}" class="ipsButton ipsButton_small ipsButton_light" data-change-subscription data-change-message="{lang="nexus_sub_change_no_charge"}">
								{{else}}
								<a href="{url="app=nexus&module=subscriptions&controller=subscriptions&do=change&id={$package->id}" csrf="true" seoTemplate="nexus_subscription"}" class="ipsButton ipsButton_small ipsButton_light" data-change-subscription data-change-message="{lang="nexus_sub_change_confirm_upgrade" sprintf="$subscription->package->_title, $package->_title, $upgradeCost"}">
								{{endif}}
									{lang="nexus_subs_upgrade_button"}
								</a>
							</li>
						{{else}}
							<li>
								{{if $upgradeCost->amount->isZero()}}
								<a href="{url="app=nexus&module=subscriptions&controller=subscriptions&do=change&id={$package->id}" csrf="true" seoTemplate="nexus_subscription"}" class="ipsButton ipsButton_negative" data-change-subscription data-change-message="{lang="nexus_sub_change_no_charge"}">
								{{else}}
								<a href="{url="app=nexus&module=subscriptions&controller=subscriptions&do=change&id={$package->id}" csrf="true" seoTemplate="nexus_subscription"}" class="ipsButton ipsButton_negative" data-change-subscription data-change-message="{lang="nexus_sub_change_confirm_downgrade" sprintf="$subscription->package->_title, $package->_title, $upgradeCost"}">
								{{endif}}
									{lang="nexus_subs_downgrade_button"}
								</a>
							</li>
						{{endif}}
					</ul>
				</div>
			{{endif}}
		{{endif}}
	{{else}}
		<div class='cSubscriptionInfo ipsBorder_top ipsType_center ipsPadding:half ipsFlex-flex:00'>
			<ul class='ipsFlex ipsFlex-jc:center ipsFlex-ai:center ipsFlex-fw:wrap ipsGap:3 ipsGap_row:1'>
				<li>
					<a href="{url="app=nexus&module=subscriptions&controller=subscriptions&do=purchase&id={$package->id}" csrf="true" seoTemplate="nexus_subscription"}" class="ipsButton ipsButton_small ipsButton_primary ipsButton_fullWidth">
						{lang="nexus_subs_buy"}
					</a>
				</li>
			</ul>
		</div>
	{{endif}}
</div>