<ips:template parameters="$table, $headers, $rows" />

{{$forcePlaceholders = FALSE;}}
{{if \count( $rows )}} 
	{{foreach $rows as $row}}
		{{if $row->_image}}
			{{$forcePlaceholders = TRUE;}}
			{{break;}}
		{{endif}}
	{{endforeach}}

	{{foreach $rows as $row}}
		<div class='cSubscriptionGrid {{if \count( $rows ) == 1}}ipsGrid_span12{{elseif \count( $rows ) == 2}}ipsGrid_span6{{else}}ipsGrid_span4{{endif}}'>
			{template="row" params="$row, $table->activeSubscription, $forcePlaceholders" app="nexus" group="subscription"}
		</div>
	{{endforeach}}
{{endif}}