<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}

	<div class='ipsPad ipsGrid ipsGrid_collapsePhone cNexusCheckout_addresses' data-controller='nexus.front.checkout.shippingForm'>
		<div class='ipsGrid_span6'>
			<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="your_address_book"}</h2>
			{{foreach $elements as $collection}}
				{{foreach $collection as $inputName => $input}}
					{{if $inputName == 'shipping_address'}}
						<div class='ipsGrid' data-ipsGrid data-ipsGrid-equalHeights='row' data-ipsGrid-minItemSize='150' data-ipsGrid-maxItemSize='250'>
							{{foreach $input->options['options'] as $val => $option}}
								{{if $val !== 0}}
									<div class='ipsGrid_span6 ipsClearfix'>
										<span class='ipsCustomInput ipsPos_left'>
											<input type="radio" name="{$input->name}" value="{$val}" class='ipsPos_left' {{if (string) $input->value == (string) $val or ( isset( $input->options['userSuppliedInput'] ) and !\in_array( $input->value, array_keys( $input->options['options'] ) ) and $val == $input->options['userSuppliedInput'] )}}checked{{endif}} {{if $input->required === TRUE}}required{{endif}} {{if $input->disabled === TRUE or ( \is_array( $input->disabled ) and \in_array( $val, $input->disabled ) )}}disabled{{endif}} id="elRadio_{$input->name}_{$val}_{$input->htmlId}">
											<span></span>
										</span>
										<div class='ipsField_fieldList_content ipsType_break'>
											<label for='elRadio_{$input->name}_{$val}_{$input->htmlId}' id='elField_{$input->name}_label'>{$option|raw}</label>
										</div>
									</div>
								{{endif}}
							{{endforeach}}
						</div>
					{{endif}}
				{{endforeach}}
			{{endforeach}}
		</div>
		<div class='ipsGrid_span6'>
			<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="add_new_address"}</h2>
			<div class='ipsClearfix'>
				<span class='ipsCustomInput ipsPos_left'>
					<input type='radio' name='shipping_address' value='0' class='ipsPos_left'>
					<span></span>
				</span>
				<div class='ipsField_fieldList_content ipsType_break'>
					{{foreach $elements as $collection}}
						{{foreach $collection as $inputName => $input}}
							{{if $inputName == 'new_shipping_address'}}
								{$input->html()|raw}
							{{endif}}
						{{endforeach}}
					{{endforeach}}
				</div>
			</div>
		</div>
	</div>
	
	<div class='ipsBorder_top ipsPadding ipsType_right ipsSpacer_top'>
		<button type='submit' class='ipsButton ipsButton_primary ipsButton_medium'>{lang="change_address"}</button>
	</div>
</form>