<ips:template parameters="$content, $checkoutStatus = NULL" />

<div class='ipsBox_alt'>
	<div class='ipsType_center ipsPad'>
		{{if $checkoutStatus && $checkoutStatus != 'continue'}}
			{{if $checkoutStatus === 'complete'}}
				<i class='ipsType_huge fa fa-check-circle'></i>
				<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="transaction_title_success"}</h1>	
			{{elseif $checkoutStatus === 'waiting'}}
				<i class='ipsType_huge fa fa-clock-o'></i>	
				<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="transaction_title_waiting"}</h1>
			{{elseif $checkoutStatus === 'hold'}}
				<i class='ipsType_huge fa fa-clock-o'></i>	
				<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="transaction_title_hold"}</h1>
			{{elseif $checkoutStatus === 'pending'}}
				<i class='ipsType_huge fa fa-clock-o'></i>	
				<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="transaction_title_pending"}</h1>
			{{elseif $checkoutStatus === 'refused'}}
				<i class='ipsType_huge fa fa-exclamation-triangle'></i>	
				<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="transaction_title_refused"}</h1>
			{{endif}}
		{{else}}
			<i class='ipsType_huge fa fa-shopping-cart'></i>
			<h1 class='ipsType_reset ipsType_veryLarge ipsType_center'>{lang="checkout"}</h1>
		{{endif}}
		{{if \IPS\Request::i()->isSecure() === TRUE}}
			<i class='fa fa-lock'></i> {lang="secure_page"}
		{{endif}}
	</div>

	<section>
		<div class='ipsBox ipsPad' id='elCheckoutContent'>
			{$content|raw}
		</div>
	</section>
</div>