<ips:template parameters="$shippingAddress, $shippingAddressErrors, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<h2 class='ipsType_sectionHead'>{lang="shipping_to"}</h2>
	<div class='ipsJS_show'>
		<p class='ipsType_normal ipsType_reset'>
			{$shippingAddress}
		</p>
		{{if !empty( $shippingAddressErrors )}}
			<strong class="ipsType_warning">
				{expression="implode('<br>', $shippingAddressErrors )" raw="true"}
			</strong><br>
		{{endif}}
		<a href='{$attributes['data-new-billing-address-url']}' class='ipsType_small' data-action='changeShippingAddress'>{lang="ship_to_different_address"} <i class='fa fa-caret-right ipsPos_middle'></i></a>
	</div>
	<ul class='ipsList_reset ipsJS_hide'>
		{{foreach $elements as $collection}}
			{{foreach $collection as $inputName => $input}}
				{{if $inputName != 'shipping_method'}}
					{$input|raw}
				{{endif}}
			{{endforeach}}
		{{endforeach}}
	</ul>

	<div class='ipsSpacer_top ipsSpacer_double'>
		<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="shipping_options"}</h2>
		{{foreach $elements as $collection}}
			{{foreach $collection as $inputName => $input}}
				{{if $inputName == 'shipping_method'}}
					{$input->html()|raw}
				{{endif}}
			{{endforeach}}
		{{endforeach}}
	</div>
	<hr class='ipsHr'>
	<div class='ipsType_right ipsSpacer_top'>
		<button type='submit' class='ipsButton ipsButton_primary ipsButton_medium {{if !empty($shippingAddressErrors)}}ipsButton_disabled{{endif}}' {{if !empty($shippingAddressErrors)}}disabled{{endif}}>{lang="continue_to_review"} &nbsp;<i class='fa fa-chevron-right ipsPos_middle'></i></button>
	</div>
</form>