<ips:template parameters="$summary" />

{{$totalItems = 0;}}
{{$itemTotal = new \IPS\Math\Number('0');}}
{{foreach $summary['items'] as $item}}
	{{if !( $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount )}}
		{{$itemTotal = $itemTotal->add( $item->linePrice()->amount );}}
		{{$totalItems += $item->quantity;}}
	{{endif}}
{{endforeach}}
<div class='ipsAreaBackground_light ipsPad'>
	<h2 class='ipsType_sectionHead'>{lang="order_review"}</h2>
	<ul class='ipsDataList ipsDataList_reducedSpacing ipsSpacer_top'>
		<li class='ipsDataItem'>
			<div class='ipsDataItem_main'>
				<span class='ipsType_medium'>{lang="summary_items" pluralize="$totalItems"}</span>
			</div>
			<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right'>
				<span class='cNexusPrice ipsType_normal'>{money="$itemTotal"}</span>
			</div>
		</li>
		{{foreach $summary['items'] as $item}}
			{{if $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount}}
				<li class='ipsDataItem cNexusCheckout_coupon'>
					<div class='ipsDataItem_main ipsType_right'>
						<strong>{lang="coupon"}</strong>
					</div>
					<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
						{$item->linePrice()}
					</div>
				</li>
			{{endif}}
		{{endforeach}}	
		<li class='ipsDataItem cNexusCheckout_subtotal'>
			<div class='ipsDataItem_main ipsType_right'>
				<strong>{lang="subtotal"}</strong>
			</div>
			<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
				{$summary['subtotal']}
			</div>
		</li>
		{{foreach $summary['shipping'] as $shipping}}
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main ipsType_right ipsContained ipsType_break'>
					<strong>{lang="shipping"} <span class='ipsType_light ipsType_unbold'>({$shipping->name})</span></strong>
				</div>
				<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
					{$shipping->linePrice()}
				</div>
			</li>
		{{endforeach}}
		{{foreach $summary['tax'] as $taxId => $tax}}
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main ipsType_right'>
					<strong>{lang="nexus_tax_{$taxId}"} ({expression="$tax['rate']*100"}%)</strong>
				</div>
				<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
					{$tax['amount']}
				</div>
			</li>
		{{endforeach}}
	</ul>
</div>