<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-role='couponForm'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}

	<div class='ipsPad ipsAreaBackground_light'>
		{{if $form->error}}
			<div class="ipsMessage ipsMessage_error">
				{$form->error}
			</div>
		{{endif}}	
		<h2 class='ipsType_minorHeading'>{lang="do_you_have_coupon"}</h2>
		<div class='ipsGrid ipsGrid_collapsePhone ipsSpacer_top ipsSpacer_half'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $inputName => $input}}
					<div class='ipsGrid_span8'>
						{$input->html()|raw}
						{{if $input->error}}
							<p class="ipsType_reset ipsSpacer_top ipsSpacer_half ipsType_small ipsType_warning">{lang="$input->error"}</p>
						{{endif}}
					</div>
				{{endforeach}}
			{{endforeach}}
			<div class='ipsGrid_span4'>
				<button type='submit' class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_fullWidth'>{lang="apply_coupon"}</button>
			</div>
		</div>
	</div>
</form>