<ips:template parameters="$informationForm, $login, $loginError, $invoice" />
{{if $login !== NULL}}
	<section data-controller='nexus.front.checkout.register' {{if isset( \IPS\Request::i()->customer_submitted )}}data-regform="true"{{endif}}>
		{{$usernamePasswordMethods = $login->usernamePasswordMethods();}}
		{{$buttonMethods = $login->buttonMethods();}}
		{{if \IPS\Login::registrationType() != 'disabled' or ( $usernamePasswordMethods and $buttonMethods )}}
			<div class='ipsGrid ipsGrid_collapsePhone ipsSpacer_top' data-role="memberChoice">
				<div class='ipsGrid_span6 ipsPad cNexusCheckout_returning'>
					<h2 class="ipsType_sectionHead ipsSpacer_bottom">{lang="returning_member"}</h2>
					<div class='ipsForm_fullWidth'>
						{{if $loginError !== NULL}}
							{template="message" group="global" location="global" app="core" params="$loginError, 'error'"}
							<br>
						{{endif}}
						<form accept-charset='utf-8' method='post' action='{$login->url}' class="ipsForm" data-controller="core.global.core.login">
							<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
							{{if $usernamePasswordMethods}}
								{template="loginForm" app="core" group="system" params="$login"}
							{{elseif $buttonMethods}}
								<div class='ipsGap:2 ipsMargin_top:half'>
									{{foreach $buttonMethods as $method}}
										<div class='ipsType_center'>
											{$method->button()|raw}
										</div>
									{{endforeach}}
								</div>
							{{endif}}
						</form>
					</div>
				</div>
				<div class='ipsGrid_span6 ipsPad'>
					{{if \IPS\Login::registrationType() != 'disabled'}}
						<div class="ipsSpacer_bottom ipsSpacer_double">
							<h2 class="ipsType_sectionHead">{lang="new_customers"}</h2>
							<p class='ipsType_normal'>
								{lang="new_customer_blurb"}
							</p>
							{{if \IPS\Login::registrationType() == 'redirect'}}
								<a href="{expression="\IPS\Settings::i()->allow_reg_target"}" class='ipsButton ipsButton_primary ipsButton_medium'>{lang="sign_up"}</a>
							{{else}}
								<button data-action='newMember' class='ipsButton ipsButton_primary ipsButton_medium'>{lang="continue_as_new_member"}</button>
							{{endif}}
						</div>
					{{endif}}
					{{if $usernamePasswordMethods and $buttonMethods}}
						<div class='ipsAreaBackground_light ipsPad_half'>
							<form accept-charset='utf-8' method='post' action='{$login->url}' class="ipsForm" data-controller="core.global.core.login">
								<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
								<p class='ipsType_reset ipsType_small ipsType_center'><strong>{lang="sign_in_with_these"}</strong></p>
								<div class='ipsGap:2 ipsMargin_top:half'>
									{{foreach $buttonMethods as $method}}
										<div class='ipsType_center'>
											{$method->button()|raw}
										</div>
									{{endforeach}}
								</div>
							</form>
						</div>
					{{endif}}
				</div>
			</div>
			<div class="ipsPad ipsJS_hide" data-role='newCustomerForm'>
				<h2 class='ipsType_sectionHead ipsSpacer_top'>{lang="create_new_account"}</h2>
				{$informationForm|raw}
			</div>
		{{else}}
			<div class="ipsPad">
				<div>
					{{if $loginError !== NULL}}
						{template="message" group="global" location="global" app="core" params="$loginError, 'error'"}
						<br>
					{{endif}}
					<form accept-charset='utf-8' method='post' action='{$login->url}' class="ipsForm" data-controller="core.global.core.login">
						<input type="hidden" name="csrfKey" value="{expression="\IPS\Session::i()->csrfKey"}">
						{{if $usernamePasswordMethods}}
							{template="loginForm" app="core" group="system" params="$login"}
						{{elseif $buttonMethods}}
							<div class='ipsGap:2 ipsMargin_top:half'>
								{{foreach $buttonMethods as $method}}
									<div class='ipsType_center'>
										{$method->button()|raw}
									</div>
								{{endforeach}}
							</div>
						{{endif}}
					</form>
				</div>
			</div>
		{{endif}}
	</section>
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone ipsSpacer_top ipsSpacer_double'>
		<div class='ipsColumn ipsColumn_fluid'>
			<h2 class='ipsType_sectionHead ipsSpacer_bottom'>{lang="billing_information"}</h2>
			{$informationForm|raw}
		</div>
		<div class='ipsColumn ipsColumn_wide'>
			{template="checkoutOrderSummary" group="checkout" app="nexus" params="$invoice->summary()"}
		</div>
	</div>	
{{endif}}