<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	{{if $form->error}}
		<div class="ipsMessage ipsMessage_error">
			{$form->error}
		</div>
	{{endif}}

	<ul class='ipsList_reset'>
		{{foreach $elements as $collection}}
			{{foreach $collection as $inputName => $input}}
				{$input|raw}
			{{endforeach}}
		{{endforeach}}
	</ul>
	<hr class='ipsHr'>
	<div class='ipsType_right ipsSpacer_top'>
		<button type='submit' class='ipsButton ipsButton_primary ipsButton_medium'>{lang="continue_to_review"} &nbsp;<i class='fa fa-chevron-right ipsPos_middle'></i></button>
	</div>
</form>