<ips:template parameters="$invoice" />

<section class='ipsBox ipsSpacer_top'>
	<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="order_review"}</h2>
	<div class='ipsPad'>
		{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'nexus', 'clients' ) ) }}
			<a href='{{if $invoice->guest_data and isset( $invoice->guest_data['guestTransactionKey'] )}}{$invoice->url()->setQueryString( array( 'do' => 'printout', 'key' => $invoice->guest_data['guestTransactionKey'] ) )}{{else}}{$invoice->url()->setQueryString( 'do', 'printout' )}{{endif}}' target="_blank" rel='noopener' class='ipsJS_show ipsButton ipsButton_light ipsButton_verySmall ipsPos_right'>{lang="order_invoice_print"}</a>
		{{endif}}
		<h2 class='ipsType_pageTitle'>{lang="order"} #{$invoice->id}</h2>
		<hr class='ipsHr'>
		<div class='ipsGrid ipsGrid_collapsePhone ipsSpacer_top'>
			<div class='ipsGrid_span6'>
				{{if $invoice->billaddress or $invoice->hasPhysicalItems()}}
					<div class='ipsGrid ipsGrid_collapsePhone ipsSpacer_bottom ipsSpacer_double'>
						{{if $invoice->billaddress}}
							<div class='ipsGrid_span6'>
								<h3 class='ipsType_sectionHead'>{lang="billing_address"}</h3>
								<div class='ipsType_medium ipsSpacer_top'>
									{$invoice->billaddress->toString('<br>')|raw}
								</div>
							</div>
						{{endif}}
						{{if $invoice->hasPhysicalItems()}}
							<div class='ipsGrid_span6'>
								<h3 class='ipsType_sectionHead'>{lang="shipping_address"}</h3>
								<div class='ipsType_medium ipsSpacer_top'>
									{$invoice->shipaddress->toString('<br>')|raw}
								</div>
							</div>
						{{endif}}
					</div>
				{{endif}}

				<h3 class='ipsType_sectionHead'>{lang="payment_details"}</h3>
				{template="paymentLog" group="clients" app="nexus" params="$invoice"}
			</div>
			<div class='ipsGrid_span6'>
				<h2 class='ipsType_sectionHead'>{lang="order_review"}</h2>
				{{$summary = $invoice->summary();}}
				<ul class='ipsDataList ipsDataList_reducedSpacing ipsSpacer_top'>
					{{foreach $summary['items'] as $item}}
						{{if !( $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount )}}
							<li class='ipsDataItem'>
								<div class='ipsDataItem_generic ipsDataItem_size1'>
									{{if $image = $item->image()}}
										<img src="{$image->url}" class='ipsImage ipsThumb_tiny'>
									{{else}}
										<div class='ipsNoThumb ipsNoThumb_product ipsThumb_tiny'>&nbsp;</div>
									{{endif}}
								</div>
								<div class='ipsDataItem_main'>
									<span class='ipsType_medium'><span class='ipsType_light'>{$item->quantity} x </span>{$item->name}</span>
									{{if \count( $item->details )}}
										<br>
										<span class="ipsType_light">
											{{foreach $item->details as $k => $v}}
												<strong>{lang="nexus_pfield_{$k}"}: </strong> {expression="\IPS\nexus\Package\CustomField::load( $k )->displayValue( $v )" raw="true"}<br>
											{{endforeach}}
										</span>
									{{endif}}
								</div>
							</li>
						{{endif}}
					{{endforeach}}
				</ul>
			</div>
		</div>
	</div>	
</section>