<ips:template parameters="$invoice, $amountToPay, $showSubmitButton, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar=NULL, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-role="paymentForm">
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if \is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	
	{{if $form->error}}
		<div class="ipsMessage ipsMessage_error">
			{$form->error}
		</div>
	{{endif}}

	{{foreach $elements as $collection}}
		{{foreach $collection as $inputName => $input}}
			{{if $inputName == 'payment_method'}}
				<div class='ipsFieldRow'>
					<label class='ipsFieldRow_label' for='elInput_{$input->htmlId}'>
						<span class='ipsType_sectionHead'>{lang="$inputName"}</span>
					</label>
					<div class='ipsFieldRow_content'>
						{{if $invoice->canSplitPayment()}}
							<a class='ipsPos_right ipsType_medium ipsFieldRow_inlineCheckbox' href="{$invoice->checkoutUrl()->setQueryString( 'do', 'split' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title="{lang="split_payment"}" data-ipsTooltip title='{lang="split_payment_title"}'>{lang="split_payment"} <i class='fa fa-caret-down'></i></a>
						{{endif}}
						<ul class='ipsList_reset'>
							{{foreach $input->options['options'] as $k => $v}}
								<li class='ipsFieldRow_inlineCheckbox'>
									<span class='ipsCustomInput'>
										<input type="radio" {{if (string) $input->value == (string) $k or ( isset( $input->options['userSuppliedInput'] ) and !\in_array( $input->value, array_keys( $input->options['options'] ) ) and $k == $input->options['userSuppliedInput'] )}}checked{{endif}} {{if $input->required === TRUE}}required{{endif}} {{if $input->disabled === TRUE or ( \is_array( $input->disabled ) and \in_array( $k, $input->disabled ) )}}disabled{{endif}} {{if isset( $input->options['toggles'][ $k ] ) and !empty( $input->options['toggles'][ $k ] )}}data-control="toggle" data-toggles="{expression="implode( ',', $input->options['toggles'][ $k ] )"}"{{endif}} id="elRadio_{$input->name}_{$k}" name="{$input->name}" value="{$k}">
										<span></span>
									</span>
									<label for='elRadio_{$input->name}_{$k}' id='elField_{$input->name}_label'>{$v|raw}</label>
								</li>
							{{endforeach}}
						</ul>
					</div>
				</div>
			{{else}}
				<ul class='ipsList_reset'>
					{$input->rowHtml()|raw}
				</ul>
			{{endif}}
		{{endforeach}}
	{{endforeach}}
	
	{{if $showSubmitButton}}
		<div class='ipsSpacer_top' id="paymentMethodSubmit">
			<button type='submit' class='ipsButton ipsButton_primary ipsButton_veryLarge ipsButton_fullWidth'>
				<i class='fa fa-check-circle'></i>
				{{if $amountToPay->amount->isZero()}}
					{lang="confirm_and_no_pay"}
				{{elseif $amountToPay->amount->compare( $invoice->total->amount ) !== 0}}
					{lang="confirm_and_pay_split" sprintf="$amountToPay"}
				{{else}}
					{lang="confirm_and_pay"}
				{{endif}}
			</button>
		</div>
	{{endif}}
</form>