<ips:template parameters="$transaction" />

<p class='ipsType_large ipsType_center'>
	<strong>{lang="order_fail_blurb"}</strong>
</p>

{{if isset( $transaction->extra['publicNote'] )}}
	<div class='ipsType_richText ipsContained ipsType_break ipsAreaBackground ipsPad ipsSpacer_both'>
		{$transaction->extra['publicNote']}
	</div>
{{endif}}

<p class='ipsType_center'>
	{{if \IPS\Member::loggedIn()->canUseContactUs() and !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'contact' )}}
		<a href="{url="app=core&module=contact&controller=contact" seoTemplate="contact"}" class='ipsButton ipsButton_primary ipsButton_small'>{lang="contact"}</a>
	{{endif}}
	<a href="{$transaction->invoice->checkoutUrl()}" class='ipsButton ipsButton_secondary ipsButton_small'>{lang="try_another_payment"}</a>
</p>