<ips:template parameters="$transaction, $complete, $purchases" />

{{if $complete}}
	<p class='ipsType_large ipsType_center'>
		<strong>{lang="order_thanks_blurb"}</strong>
	</p>
	<p class='ipsType_medium ipsType_center ipsType_reset'>
		<i class='fa fa-info-circle'></i> {lang="manage_orders_in_billing"}.
	</p>

	{template="orderReview" group="checkout" app="nexus" params="$transaction->invoice"}
{{else}}
	<p class='ipsType_large ipsType_center'>
		<strong>{lang="order_split_payment_success"}</strong>
	</p>
	<p class='ipsType_large ipsType_center'>
		{lang="order_split_payment_success2"}
	</p>
	{{if $invoice = $transaction->invoice}}
		<p class='ipsType_center'>
			<a href="{$invoice->checkoutUrl()}" class='ipsButton ipsButton_primary ipsButton_medium'>{lang="return_to_checkout"}</a>
		</p>
	{{endif}}
{{endif}}