<ips:template parameters="$transaction, $invoice=NULL" />

<p class='ipsType_large ipsType_center'>
	{lang="order_thanks_blurb_no_email"}
</p>
<p class='ipsType_large ipsType_center'>
	<strong>{lang="order_processing_blurb"}</strong><br>
	{lang="order_processing_blurb2"}
</p>
{{if member.member_id}}
    <p class='ipsType_medium ipsType_center ipsType_reset'>
        <i class='fa fa-info-circle'></i> {lang="track_orders_in_billing"}
    </p>
{{endif}}

{template="orderReview" group="checkout" app="nexus" params="$invoice ?: $transaction->invoice"}