<ips:template parameters="$countryCode, $phoneNumber, $showingMultipleForms, $methods, $error" />
<div id="elVerify">
	<div class='ipsPad'>
		{{if !$showingMultipleForms}}
			<h1 class='ipsType_center ipsType_pageTitle ipsSpacer_bottom ipsSpacer_half'>{lang="mfa_popup_setup_title"}</h1>
		{{endif}}
		<div class="ipsType_medium ipsType_richText ipsType_center c2FA_info">
				{{if !$showingMultipleForms}}
					{lang="verify_mfa_desc_phone_prefix"}
				{{endif}}
				{{if \count( $methods ) > 1}}
					{lang="verify_mfa_desc_sms_or_phone"}
				{{elseif \in_array( 'phone', $methods )}}
					{lang="verify_mfa_desc_phone"}
				{{else}}
					{lang="verify_mfa_desc_sms"}
				{{endif}}
		</div>
	</div>
	<div class="ipsPad">
		<div class='ipsGrid'>
			<div class='ipsGrid_span5 ipsType_center'>
				<select data-sort name="countryCode">
					{{foreach \IPS\Helpers\Form\Tel::$diallingCodes as $country => $codes}}
						{{foreach $codes as $code}}
							<option value="{$country}-{$code}" data-code="+{$code}" data-text="{lang="country-{$country}"} (+{$code})" {{if $country == $countryCode or "{$country}-{$code}" == $countryCode}}selected{{endif}}>{lang="country-{$country}"} (+{$code})</option>
						{{endforeach}}
					{{endforeach}}
				</select>
			</div>
			<div class='ipsGrid_span7 ipsType_center'>
				<input name="phoneNumber" type="tel" value="{$phoneNumber}" placeholder="{lang="verify_placeholder"}" autocomplete="tel-national">
			</div>
		</div>
		{{if request.countryCode}}
			<p class="ipsType_warning">{lang="$error"}</p>
		{{endif}}
	</div>
	<div class="ipsPad ipsAreaBackground">
			{{if \in_array( 'phone', $methods )}}
				<div class="ipsMargin_bottom">
					<button type='submit' name="method" value="phone" class='ipsButton ipsButton_primary ipsButton_fullWidth ipsButton_medium'>
						<i class='fa fa-phone'></i>&nbsp; {lang="verify_submit_call"}
					</button>
				</div>
			{{endif}}
			{{if \in_array( 'sms', $methods )}}
				<div class="ipsMargin_bottom">
					<button type='submit' name="method" value="sms" class='ipsButton ipsButton_primary ipsButton_fullWidth ipsButton_medium'>
						<i class='fa fa-commenting'></i>&nbsp; {lang="verify_submit_sms"}
					</button>
				</div>
			{{endif}}
            {{if \in_array( 'whatsapp', $methods )}}
                <div class="ipsMargin_bottom">
                    <button type='submit' name="method" value="whatsapp" class='ipsButton ipsButton_primary ipsButton_fullWidth ipsButton_medium'>
                        <i class='fa fa-comment-o'></i>&nbsp; {lang="verify_submit_whatsapp"}
                    </button>
                </div>
            {{endif}}
	</div>
    {template="mfaSetupOptOut" app="core" group="login" location="global"}
</div>