<ips:template parameters="$category, $table" />

{{if $club = $category->club()}}
	{{if settings.clubs and settings.clubs_header == 'full'}}
		{template="header" app="core" group="clubs" params="$club, $category"}
	{{endif}}
	<div id='elClubContainer'>
{{endif}}

<div class='ipsPageHeader ipsResponsive_pull ipsBox ipsPadding ipsClearfix ipsSpacer_bottom'>
	<div class='ipsFlex ipsFlex-jc:between ipsFlex-ai:center ipsMargin_bottom:half'>
		<h1 class="ipsType_pageTitle ipsFlex-flex:11 ipsType_break">{$category->_title}</h1>
		<div class='ipsFlex-flex:00 ipsResponsive_hidePhone'>
            {{if \IPS\Application::appIsEnabled('cloud')}}
                {template="analyticsButton" app="cloud" group="analytics" params="$category, $category->id"}
            {{endif}}
			{template="follow" app="core" group="global" params="'downloads', 'category', $category->_id, \IPS\downloads\File::containerFollowerCount( $category )"}
		</div>
	</div>
	{{if $category->hasChildren()}}
		<a href='#elDownloadsCategories_menu' data-ipsMenu id='elDownloadsCategories' class='ipsButton ipsButton_fullWidth ipsButton_light ipsButton_small ipsResponsive_block ipsResponsive_hideDesktop'>{lang="subcategory"} &nbsp;<i class='fa fa-caret-down'></i></a>
	{{endif}}
	{{if $category->description}}
		{template="richText" group="global" app="core" location="global" params="$category->description, array('ipsPageHeader_info')"}
	{{endif}}
</div>

<div data-controller='downloads.front.downloads.browse'>
	{template="categoryMenu" group="browse" params="$category->children()"}

	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_both">
		{template="categoryButtons" group="browse" params="$category->can('add'), $category, FALSE"}
	</ul>

	<div class='ipsBox ipsResponsive_pull cDownloadsCategoryTable'>
	{$table|raw}
	</div>

	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_showPhone ipsResponsive_block ipsClearfix ipsSpacer_top">
		{template="categoryButtons" group="browse" params="$category->can('add'), $category, TRUE"}
	</ul>
</div>

<div class='ipsResponsive_showPhone ipsResponsive_block ipsSpacer_top'>
	{template="follow" app="core" group="global" params="'downloads', 'category', $category->_id, \IPS\downloads\File::containerFollowerCount( $category )"}
</div>

{{if $category->club()}}
	</div>
{{endif}}