<ips:template parameters="$featured, $new, $rated, $downloaded" />
<div class="ipsPageHeader ipsClearfix ipsFlex ipsFlex-ai:center ipsFlex-jc:between sm:ipsFlex-fd:column sm:ipsFlex-ai:stretch ipsMargin_bottom sm:ipsMargin:none">
	<h1 class="ipsType_pageTitle">{lang="downloads"}</h1>
	<ul class="ipsToolList ipsToolList_horizontal ipsClearfix ipsFlex-flex:11 ipsMargin_bottom:none sm:ipsMargin_bottom sm:ipsMargin_top:half">
		{{if \IPS\downloads\Category::canOnAny('add') OR \IPS\downloads\Category::theOnlyNode()}}
			{template="categoryButtons" group="browse" params="\IPS\downloads\Category::canOnAny('add'), NULL, FALSE"}
			{{if \IPS\downloads\Category::theOnlyNode() and ( !\IPS\Settings::i()->club_nodes_in_apps or !\IPS\downloads\Category::clubNodes() )}}
				<li class='ipsResponsive_hidePhone'><a class='ipsButton ipsButton_link ipsButton_medium ipsButton_fullWidth' href='{expression="\IPS\downloads\Category::theOnlyNode()->url()"}'>{lang="view_all_files"}</a></li>
			{{endif}}
		{{endif}}
		{{if !\IPS\downloads\Category::theOnlyNode()}}
			<li class='ipsResponsive_hideDesktop ipsResponsive_hideTablet ipsToolList_primaryAction'>
				<a href='#elDownloadsCategories_menu' data-ipsMenu id='elDownloadsCategories' class='ipsButton ipsButton_fullWidth ipsButton_veryLight ipsButton_medium'><span class='ipsType_light'>{lang="downloads_category_select"}&nbsp;&nbsp;</span> {lang="all"} <i class='fa fa-caret-down'></i></a>
				{template="categoryMenu" group="browse" params="\IPS\downloads\Category::roots()"}
			</li>
		{{endif}}
	</ul>
</div>

{{if !empty( $featured )}}
	<div class='ipsBox ipsResponsive_pull ipsSpacer_bottom'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="featured_downloads"}</h2>
		<section id='elDownloadsFeatured'>
			<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-fullSizeItems data-ipsCarousel-slideshow data-ipsCarousel-shadows='false'>
				<div class='ipsCarousel_inner'>
					<ul class='cDownloadsCarousel ipsClearfix' data-role="carouselItems">
						{{foreach $featured as $file}}
							{template="featuredFile" group="browse" app="downloads" params="$file"}
						{{endforeach}}
					</ul>
				</div>
				<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
				<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
				<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
				<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
			</div>
		</section>
	</div>
{{endif}}

{{if settings.idm_show_newest }}
	<div class='ipsBox ipsResponsive_pull'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="browse_whats_new"}</h2>
		<div class='ipsPad_half'>
			{{if \count( $new )}}
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<div class='ipsCarousel_inner'>
						<ul class='cDownloadsCarousel' data-role="carouselItems">
							{{foreach $new as $idx => $file}}
								{template="indexBlock" group="browse" params="$file"}
							{{endforeach}}
						</ul>
					</div>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			{{else}}
				<p class='ipsType_reset ipsType_light ipsPad'>{lang="no_new_files"}</p>
			{{endif}}
		</div>
	</div>
{{endif}}

{{if settings.idm_show_highest_rated }}
	<div class='ipsBox ipsResponsive_pull ipsSpacer_top'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="browse_highest_rated"}</h2>
		<div class='ipsPad_half'>
			{{if \count( $rated )}}
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<div class='ipsCarousel_inner'>
						<ul class='cDownloadsCarousel' data-role="carouselItems">
							{{foreach $rated as $idx => $file}}
								{template="indexBlock" group="browse" params="$file"}
							{{endforeach}}
						</ul>
					</div>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			{{else}}
				<p class='ipsType_reset ipsType_light ipsPad'>{lang="no_rated_files"}</p>
			{{endif}}
		</div>
	</div>
{{endif}}

{{if settings.idm_show_most_downloaded }}
	<div class='ipsBox ipsResponsive_pull ipsSpacer_top'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="browse_most_downloaded"}</h2>
		<div class='ipsPad_half'>
			{{if \count( $downloaded )}}
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<div class='ipsCarousel_inner'>
						<ul class='cDownloadsCarousel' data-role="carouselItems">
							{{foreach $downloaded as $idx => $file}}
								{template="indexBlock" group="browse" params="$file"}
							{{endforeach}}
						</ul>
					</div>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			{{else}}
				<p class='ipsType_reset ipsType_light ipsPad'>{lang="no_downloaded_files"}</p>
			{{endif}}
		</div>
	</div>
{{endif}}

{{if \IPS\downloads\Category::canOnAny('add') OR \IPS\downloads\Category::theOnlyNode()}}
	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_showPhone ipsResponsive_block ipsClearfix ipsSpacer_top">
		{template="categoryButtons" group="browse" params="\IPS\downloads\Category::canOnAny('add'), NULL, TRUE"}
		{{if \IPS\downloads\Category::theOnlyNode() and ( !\IPS\Settings::i()->club_nodes_in_apps or !\IPS\downloads\Category::clubNodes() )}}
			<li><a class='ipsButton ipsButton_link ipsButton_medium ipsButton_fullWidth' href='{expression="\IPS\downloads\Category::theOnlyNode()->url()"}'>{lang="view_all_files"}</a></li>
		{{endif}}
	</ul>
{{endif}}