<ips:template parameters="$table, $headers, $files" />

{{if \count( $files )}}
    {{if \IPS\downloads\Category::getMemberView() == 'grid'}}
        <div class="ipsFluidGrid ipsFluidGrid--downloads">
            {{foreach $files as $file}}
            <li class='ipsDataItem {{if $file->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $file, 'tableClass' ) && $file->tableClass()}}ipsDataItem_{$file->tableClass()}{{endif}} {{if $file->hidden()}}ipsModerated{{endif}}'>
            	<div class='ipsMargin_bottom:half'>
					{template="thumbImage" group="global" app="core" params="$file->primary_screenshot_thumb, $file->name, 'large', '', '', $file->url( 'getPrefComment' )"}
				</div>
				{{$price = NULL;}}
				{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
					<div class="cWidgetPrice ipsType_light ipsType_semiBold">
						{{if $file->isPaid()}}
							{{if $price = $file->price()}}
								{$price|raw}
							{{endif}}
						{{else}}
							{lang="file_free_feed"}
						{{endif}}
					</div>
				{{endif}}
				<div class='ipsFlex ipsFlex-jc:between ipsGap:1'>
					<h4 class='ipsContained_container'>
						{{if $file->unread()}}
						<span><span class='ipsItemStatus ipsItemStatus_small' data-ipsTooltip title='{{if $file->unread() === -1}}{lang="new"}{{else}}{lang="updated"}{{endif}}'><i class="fa fa-circle"></i></span>&nbsp;</span>
						{{endif}}
						{{if $file->mapped('pinned') || $file->mapped('featured') || $file->hidden() === -1 || $file->hidden() === 1}}
						{{if $file->hidden() === -1}}
						<span><span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{$file->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span></span>
						{{elseif $file->hidden() === 1}}
						<span><span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span></span>
						{{endif}}
						{{if $file->mapped('pinned')}}
						<span><span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span></span>
						{{endif}}
						{{if $file->mapped('featured')}}
						<span><span class="ipsBadge ipsBadge_small ipsBadge_icon ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span></span>
						{{endif}}
						{{endif}}
						{{if $file->prefix()}}
						<span>{template="prefix" group="global" app="core" params="$file->prefix( TRUE ), $file->prefix()"}</span>
						{{endif}}
						<span class='ipsType_semiBold ipsType_normal ipsType_break ipsContained'><a href='{$file->url( "getPrefComment" )}' title='{lang="view_this_file" sprintf="$file->name"} {{if $file->canEdit()}}{lang="click_hold_edit"}{{endif}}' {{if $file->canEdit()}}data-role="editableTitle"{{endif}}>{$file->name}</a></span>
					</h4>
					{{if $file->container()->bitoptions['reviews']}}
						<div class='ipsFlex-flex:00'>
							{template="rating" group="global" location="front" app="core" params="'small', $file->rating, \IPS\Settings::i()->reviews_rating_out_of"}
						</div>
					{{endif}}
				</div>
				<div class='ipsType_richText ipsType_break ipsMargin_bottom:half' data-ipsTruncate data-ipsTruncate-type="remove" data-ipsTruncate-size="2 lines">
					{$file->truncated()|raw}
				</div>
				<div class='ipsFlex ipsFlex-ai:center ipsFlex-fw:wrap ipsFlex-jc:between ipsGap:1'>
					<div class='ipsFlex-flex:11 ipsType_light ipsType_medium ipsType_blendLinks'>{lang="byline_nodate" htmlsprintf="$file->author()->link( NULL, NULL, $file->isAnonymous() )"}</div>
					<div>
						<div class='ipsFlex ipsFlex-ai:center ipsGap:4 ipsGap_row:2 ipsType_light'>
							{{if $file->isPaid() and !$file->nexus and \in_array( 'purchases', explode( ',', settings.idm_nexus_display ) )}}
								<span {{if !$file->purchaseCount()}}class='ipsType_light'{{endif}} title='{lang="idm_purchases"}' data-ipsTooltip><i class='fa fa-shopping-cart'></i> {$file->purchaseCount()}</span>
							{{endif}}
							{{if !$file->isPaid() or \in_array( 'downloads', explode( ',', settings.idm_nexus_display ) )}}
								<span {{if !$file->downloads}}class='ipsType_light'{{endif}} title='{lang="downloads"}' data-ipsTooltip><i class='fa fa-download'></i> {number="$file->downloads"}</span>
							{{endif}}
							{{if $file->container()->bitoptions['comments']}}<span {{if !$file->comments}}class='ipsType_light'{{endif}} title='{lang="total_comments"}' data-ipsTooltip><i class='fa fa-comments-o'></i> {$file->comments}</span>{{endif}}
							{{if $table AND method_exists( $table, 'canModerate' ) AND $table->canModerate()}}
							<div>
								<span class='ipsCustomInput'>
									<input type='checkbox' data-role='moderation' name="moderate[{$file->id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $file ) )"}" data-state='{{if $file->tableStates()}}{$file->tableStates()}{{endif}}'>
									<span></span>
								</span>
							</div>
							{{endif}}
						</div>
					</div>
				</div>
			</li>
			{{endforeach}}
		</div>
	{{else}}
		{{foreach $files as $file}}
			{template="tableRow" group="browse" app="downloads" params="$file, $table"}
		{{endforeach}}
	{{endif}}
{{endif}}