<ips:template parameters="$form, $category, $terms, $newSubmission=TRUE, $bulk=0, $postingInformation='', $versioning=0" />

{{$nonInfoFields = array('files', 'import_files', 'url_files', 'screenshots', 'url_screenshots');}}
{{$step = 1;}}

{{if $newSubmission}}
	{{if $bulk}}
	{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( 'submit_form_desc_bulk', TRUE, array( 'sprintf' => $category->_title ) )"}
	{{else}}
	{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( 'submit_form_desc', TRUE, array( 'sprintf' => $category->_title ) )"}
	{{endif}}
{{else}}
	{{if $versioning and !member.group['idm_bypass_revision']}}
	{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( 'upload_new_version' ), \IPS\Member::loggedIn()->language()->addToStack( 'new_version_versioning' )"}
	{{else}}
	{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( 'upload_new_version' )"}
	{{endif}}
{{endif}}

{{if $postingInformation}}
{$postingInformation|raw}
{{endif}}

{{if $form->error}}
<div class="ipsMessage ipsMessage_error">
	{$form->error}
</div>
<br>
{{endif}}

<form accept-charset='utf-8' method="post" action="{$form->action}" id='elDownloadsSubmit' enctype="multipart/form-data" {{if $category->bitoptions['allowss'] AND $category->bitoptions['reqss']}}data-screenshotsReq='1'{{endif}} {{if $bulk}}data-bulkUpload='1'{{endif}} {{if $category->multiple_files}}data-multipleFiles='true'{{endif}} {{if !$newSubmission}}data-newVersion='true'{{endif}} data-ipsForm data-ipsFormSubmit data-controller='downloads.front.submit.main'>
	<input type="hidden" name="{$form->id}_submitted" value="1">
	{{foreach $form->hiddenValues as $k => $v}}
	<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}

	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_veryNarrow ipsType_center'>
			<span class='cDownloadsSubmit_step'>{$step}{{$step++;}}</span>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsBox'>
				<h3 class='ipsType_sectionTitle ipsType_reset'>{{if $category->multiple_files}}{lang="select_your_files"}{{else}}{lang="select_your_file"}{{endif}}</h3>
				<div class='ipsPadding ipsClearfix'>
					{{if isset( $form->elements['']['import_files'] ) || isset( $form->elements['']['url_files'] )}}
					<ul class='ipsList_inline ipsClearfix ipsType_right'>
						{{if isset( $form->elements['']['url_files'] )}}
						<li>
							<a href='#' class='ipsButton ipsButton_veryLight ipsButton_verySmall' id='elURLFiles' data-ipsMenu data-ipsMenu-closeOnClick='false' data-ipsMenu-appendTo='#elDownloadsSubmit'>
								<i class='fa fa-globe'></i>&nbsp; {lang="add_files_by_url"} <i class='fa fa-caret-down'></i>
								<span class='ipsNotificationCount {{if !\count( $form->elements['']['url_files']->value )}}ipsHide{{endif}}' data-role='fileCount'>{expression="\count( $form->elements['']['url_files']->value )"}</span>
							</a>
							<div id='elURLFiles_menu' class='ipsMenu ipsMenu_normal ipsHide ipsPad'>
								<ul class='ipsFieldRow_fullWidth'>
									{$form->elements['']['url_files']|raw}
								</ul>
								<hr class='ipsHr'>
								<a href='#' class='ipsButton ipsButton_fullWidth ipsButton_important' data-action='confirmUrls'>{lang="submit_menu_confirm"}</a>
							</div>
						</li>
						{{endif}}
						{{if isset( $form->elements['']['import_files'] )}}
						<li>
							<a href='#' class='ipsButton ipsButton_veryLight ipsButton_verySmall' id='elImportFiles' data-ipsMenu data-ipsMenu-closeOnClick='false' data-ipsMenu-appendTo='#elDownloadsSubmit'>
								<i class='fa fa-folder'></i>&nbsp; {lang="add_files_by_path"} <i class='fa fa-caret-down'></i>
								<span class='ipsNotificationCount {{if !\count( $form->elements['']['import_files']->value )}}ipsHide{{endif}}' data-role='fileCount'>{expression="\count( $form->elements['']['import_files']->value )"}</span>
							</a>
							<div id='elImportFiles_menu' class='ipsMenu ipsMenu_normal ipsHide ipsPad'>
								<ul class='ipsFieldRow_fullWidth'>
									{$form->elements['']['import_files']|raw}
								</ul>
								<hr class='ipsHr'>
								<a href='#' class='ipsButton ipsButton_fullWidth ipsButton_important' data-action='confirmImports'>{lang="submit_menu_confirm"}</a>
							</div>
						</li>
						{{endif}}
					</ul>
					{{endif}}
					<div id='elDownloadsSubmit_progress' class='ipsClear' data-ipsSticky>
						<div class='ipsProgressBar ipsProgressBar_animated ipsClear' >
							<div class='ipsProgressBar_progress' data-progress='0%'></div>
						</div>
					</div>
					<div id='elDownloadsSubmit_uploader' class='ipsClear'>
						{$form->elements['']['files']->html( $form )|raw}
						{{if $category->multiple_files}}
						<button type='button' class='ipsButton ipsButton_light ipsButton_verySmall ipsHide ipsMargin_top' data-action='uploadMore'>{lang="upload_more_files"}</button>
						{{endif}}
					</div>
				</div>
			</div>
		</div>
	</div>

	{{if !$bulk }}
	{{if $category->bitoptions['allowss'] }}
	<div id='elDownloadsSubmit_screenshots'>
		<br><br>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_veryNarrow ipsType_center'>
				<span class='cDownloadsSubmit_step'>{$step}{{$step++;}}</span>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				<div class='ipsBox'>
					<h3 class='ipsType_sectionTitle ipsType_reset'>{lang="add_screenshots"}</h3>
					<div class='ipsPadding_horizontal ipsPadding_vertical:half'>
						{{if isset( $form->elements['']['url_screenshots'] )}}
						<ul class='ipsList_inline ipsClearfix ipsType_right'>
							<li>
								<a href='#' class='ipsButton ipsButton_veryLight ipsButton_verySmall' id='elURLScreenshots' data-ipsMenu data-ipsMenu-closeOnClick='false' data-ipsMenu-appendTo='#elDownloadsSubmit_screenshots'>
									<i class='fa fa-globe'></i>&nbsp; {lang="add_screenshots_by_url"} <i class='fa fa-caret-down'></i>
									<span class='ipsNotificationCount {{if !isset( $form->elements['']['url_screenshots']->value['values'] ) OR !\count( $form->elements['']['url_screenshots']->value['values'] )}}ipsHide{{endif}}' data-role='fileCount'>{expression="\count( $form->elements['']['url_screenshots']->value['values'] ?? array() )"}</span>
								</a>
								<div id='elURLScreenshots_menu' class='ipsMenu ipsMenu_wide ipsHide ipsPad'>
									<ul class='ipsFieldRow_fullWidth'>
										{$form->elements['']['url_screenshots']|raw}
									</ul>
									<hr class='ipsHr'>
									<a href='#' class='ipsButton ipsButton_fullWidth ipsButton_important' data-action='confirmScreenshotUrls'>{lang="submit_menu_confirm"}</a>
								</div>
							</li>
						</ul>
						{{endif}}
						{{if isset( $form->elements['']['screenshots'] )}}
						<div id='elDownloadsSubmit_screenshots'>
							{$form->elements['']['screenshots']->html( $form )|raw}
						</div>
						{{endif}}
					</div>
				</div>
			</div>
		</div>
	</div>
	{{endif}}

	<div id='elDownloadsSubmit_otherinfo'>
		<br><br>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_veryNarrow ipsType_center'>
				<span class='cDownloadsSubmit_step'>{$step}{{$step++;}}</span>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				<div class='ipsBox'>
					<h3 class='ipsType_sectionTitle ipsType_reset'>{{if $newSubmission}}{lang="submit_file_information"}{{else}}{lang="new_version_details"}{{endif}}</h3>
					<div class='ipsPad'>
						<ul class='ipsForm ipsForm_vertical'>
							{{foreach $form->elements as $collection}}
							{{foreach $collection as $fieldName => $input}}
							{{if !\in_array( $fieldName, $nonInfoFields )}}
							{$input|raw}
							{{endif}}
							{{endforeach}}
							{{endforeach}}
						</ul>
					</div>
				</div>
			</div>
		</div>

		{{if $terms}}
		<br><br>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_veryNarrow ipsType_center'>
				<span class='cDownloadsSubmit_step'>{$step}{{$step++;}}</span>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				<div class='ipsBox'>
					<h3 class='ipsType_sectionTitle ipsType_reset'>{lang="csubmissionterms_placeholder"}</h3>
					<div class='ipsPad ipsType_richText'>
						{$terms|raw}
					</div>
				</div>
			</div>
		</div>
		{{endif}}
	</div>
	{{elseif $terms}}
	<br>
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_veryNarrow ipsType_center'>
			<span class='cDownloadsSubmit_step'>{$step}{{$step++;}}</span>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsBox'>
				<h3 class='ipsType_sectionTitle ipsType_reset'>{lang="csubmissionterms_placeholder"}</h3>
				<div class='ipsPad ipsType_richText'>
					{$terms|raw}
				</div>
			</div>
		</div>
	</div>
	{{endif}}

	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_veryNarrow'></div>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsBox ipsPadding ipsType_center ipsMargin_top:double'>
				<button type='submit' class='ipsButton ipsButton_large ipsButton_primary' data-role='submitForm'>
					{{if $bulk}}
						{lang="continue"}
					{{else}}
						{{if $newSubmission}}
							{{if $category->multiple_files}}
								{lang="save_and_submit_files"}
							{{else}}
								{lang="save_and_submit_file"}
							{{endif}}
						{{else}}
							{lang="save_and_submit_new_version"}
						{{endif}}
					{{endif}}
				</button>
			</div>
		</div>
	</div>
</form>