<ips:template parameters="$forum, $depth=0" />
<div data-controller="forums.front.forum.flow" data-rootForum="{$forum->_id}" class='ipsBox cForumMiniList_wrapper' id='elFluidFormFilters'>
	<div class='ipsSideMenu'>
		<ul class='ipsSideMenu_list cForumMiniList cForumMiniList_multiRoot'>
			<li class="cForumMiniList_category" data-category>
				{{if $forum->sub_can_post}}
					{{$lastPost = $forum->lastPost();}}
					{{$unread = \IPS\forums\Topic::containerUnread( $forum );}}
					{{$children = $forum->children();}}
					<a href="{$forum->url()}" data-parent-id="{$forum->_id}" data-node-id="{$forum->_id}" data-has-children="1" class='ipsSideMenu_item'>
						<span class='cForumMiniList_blob' {{if $forum->feature_color}}style="background-color: {$forum->feature_color}; color: {$forum->_featureTextColor};"{{endif}} {{if $lastPost AND $lastPost['date']}}title="{lang="forum_simple_view_last_post"} {datetime="$lastPost['date']"}" data-ipsTooltip data-ipsTooltip-safe{{endif}}>
							<span></span>
							<i class='fa fa-check'></i>
						</span>
						<span class='cForumMiniList_title ipsTruncate ipsTruncate_line'>
							{{if $unread}}<strong>{{endif}}{$forum->_title}{{if $unread}}</strong>{{endif}}
						</span>
						<span class='ipsType_small ipsType_light cForumMiniList_count'>{number="\IPS\forums\Topic::contentCountItemsOnly( $forum )" format="short"}</span>
					</a>
				{{else}}
					<a href="{$forum->url()}" data-parent-id="{$forum->_id}" data-node-id="{$forum->_id}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'>{$forum->_title}</a>
				{{endif}}
				{{if $forum->hasChildren()}}
					<ul class='ipsSideMenu_list cForumMiniList'>
						{template="simplifiedViewForumSidebar_children" app="forums" location="front" group="index" params="$forum, $depth+1"}
					</ul>
				{{endif}}
			</li>			
		</ul>
	</div>
	<div class='ipsResponsive_hideDesktop ipsResponsive_block'>
		<hr class='ipsHr'>
		<a href='#' class='ipsButton ipsButton_fullWidth ipsButton_primary ipsButton_medium' data-action='dialogClose'>{lang="done_forum_filtering"}</a>
	</div>
</div>