<ips:template parameters="$parent" />
{{if $parent->hasChildren() }}
	{{foreach $parent->children() as $idx => $forum}}
		{{$lastPost = $forum->lastPost();}}
		{{$unread = \IPS\forums\Topic::containerUnread( $forum );}}
		{{$children = $forum->children();}}
		{{if ! $forum->redirect_on and ( $forum->can('read') or !$forum->sub_can_post ) }}
			<li class="{{if $children}}cForumMiniList_category{{endif}}">
				<a href="{$forum->url()}" data-parent-id="{$parent->_id}" data-node-id="{$forum->_id}" data-has-children="{{if $children}}1{{else}}0{{endif}}" class='ipsSideMenu_item {{if !$unread}}cForumMiniList_unread{{endif}}'>
					<span class='cForumMiniList_blob' {{if $forum->feature_color}}style="background-color: {$forum->feature_color}; color: {$forum->_featureTextColor};"{{endif}} {{if $lastPost AND $lastPost['date']}}title="{lang="forum_simple_view_last_post"} {datetime="$lastPost['date']"}" data-ipsTooltip data-ipsTooltip-safe{{endif}}>
						<span></span>
						<i class='fa fa-check'></i>
					</span>
					<span class='cForumMiniList_title ipsTruncate ipsTruncate_line'>
						{{if $unread}}<strong>{{endif}}{$forum->_title}{{if $unread}}</strong>{{endif}}
					</span>
					<span class='ipsType_small ipsType_light cForumMiniList_count'>{number="\IPS\forums\Topic::contentCountItemsOnly( $forum )" format="short"}</span>
				</a>
				{{if $children}}
					<ul class='ipsSideMenu_list cForumMiniList'>
						{template="simplifiedViewForumSidebar_children" app="forums" location="front" group="index" params="$forum, 1"}
					</ul>
				{{endif}}
			</li>
		{{endif}}
	{{endforeach}}
{{endif}}