<ips:template parameters="$percentages, $rawCounts" />
<div class="ipsPad ipsAreaBackground_light">
	<h2 class='ipsType_sectionHead'>{lang="stats_club_types"}</h2>
	<div class='acpStatsBar ipsSpacer_bottom'>
		{{foreach $percentages as $type => $percent}}
			<div class='acpStatsBar_segment' style='width: {$percent}%;' title='{lang="club_type_{$type}"}: {number="$rawCounts[ $type ]"}' data-ipsTooltip-label='{lang="club_type_{$type}"}: {number="$rawCounts[ $type ]"}' data-ipsTooltip data-ipsTooltip-safe></div>
		{{endforeach}}
	</div>
	<ul class='ipsList_inline'>
		{{foreach $percentages as $type => $percent}}
			<li class='acpStatsBar_legend'>
				<span class='acpStatsBar_preview'></span>
				{lang="club_type_{$type}"}
			</li>
		{{endforeach}}
	</ul>
</div>