<ips:template parameters="$url, $orientation='vertical'" />
{{$catClass = '\IPS\cms\Categories' . \IPS\cms\Databases\Dispatcher::i()->databaseId;}}
{{$categories = $catClass::roots();}}
{{if !empty( $categories )}}
	<div{{if $orientation == "horizontal"}} class="ipsBox"{{endif}}>
		<h3 class='ipsWidget_title ipsType_reset'>{lang="categories"}</h3>
		<div class='ipsSideMenu ipsCategoriesMenu ipsAreaBackground_reset ipsPad_half'>
			<ul class='ipsSideMenu_list'>
				{{foreach $categories as $category}}
					<li>
						<a href="{$category->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><span class='ipsBadge ipsBadge_style1 ipsPos_right'>{expression="\IPS\cms\Records::contentCount( $category )"}</span><strong class='ipsType_normal'>{$category->_title}</strong></a>
						{{if $category->hasChildren()}}
							<ul class="ipsSideMenu_list">
								{{$counter = 0;}}
								{{foreach $category->children() as $idx => $subcategory}}
								{{$counter++;}}
									<li>
										{{if $counter >= 5}}
											<a href='{$category->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" pluralize="\count( $category->children() ) - 4"}</span></a>
											{{break;}}
										{{else}}
											<a href="{$subcategory->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><strong class='ipsPos_right ipsType_small'>{expression="\IPS\cms\Records::contentCount( $subcategory )"}</strong>{$subcategory->_title}</a>
										{{endif}}
									</li>
								{{endforeach}}
							</ul>
						{{endif}}
					</li>
				{{endforeach}}
				{{if settings.club_nodes_in_apps and \IPS\IPS::classUsesTrait( $catClass, 'IPS\Content\ClubContainer' ) and $clubCategories = $catClass::clubNodes()}}
                    {{if \count( $clubCategories )}}
                    <li>
                        <div class="ipsType_bold ipsType_large ipsMargin_top:double ipsBorder_bottom ipsPadding_bottom:half">{lang="club_categories_title"}</div>
                        <ul class="ipsSideMenu_list ipsMargin_top:half">
                            {{foreach $clubCategories as $category}}
                            <li>
                                <a href="{$category->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><span class='ipsBadge ipsBadge_style1 ipsPos_right'>{expression="\IPS\cms\Records::contentCount( $category )"}</span><strong class='ipsType_normal'>{$category->_title}</strong></a>
                            </li>
                            {{endforeach}}
                        </ul>
                    </li>
                    {{endif}}
                {{endif}}
			</ul>
			<p class='ipsType_center'>
				<a href='{$url->setQueryString('show','categories')}' class=''>{lang="cms_show_categories"} &nbsp;<i class='fa fa-caret-right'></i></a>
			</p>
		</div>
	</div>
{{endif}}